microsoft/pxt

webapp/public/custom.css
PR fixes #176 by limiting the max-width of the filelist ui (left sidebar)
=> Fix for issue 167: Lengthy errors mess up the Error card and Filelist UI

webapp/src/app.tsx
PR fixes #101 
Before (Chrome): 
After (Chrome): 
After (Firefox): 
After (Edge):
=> Fix for issue 101: Increase the length of the "Browse" edit field when importing .hex file

cli/cli.ts, cli/uploader.ts, docfiles/docs.js, pxtlib/docsrender.ts
- Renamed`pxt testsnippets` to `pxt snippets`
- Added `-i` flag to ignore snippets previously believed to compile correctly
- Added `-re REGEX` option to only test snippets in files whose name matches the regex
- Ignore certain snippet types that are never meant to be compiled to blocks, such as those that are strictly TypeScript or are meant to demonstrate syntax errors. You can force the test to ignore a snippet by appending `-ignore` after its type
- Use the `package` snippet at the end of a file to determine whether to use extra packages when compiling (e.g. `microbit-radio`, `microbit-bluetooth`, etc)
- Search the original documentation files for snippets, rather than the snippets directory. This means that `pxt snippets` can be run without running `pxt checkdocs` or `pxt serve`
This …
=> Reduce false negative rate when testing documentation snippets

pxtsim/svg.ts
This is necessary in a few places in the pxt-arduino target where we want to construct SVG elements but not append them to any parent yet. This is a more functional approach.
=> adds pure versions of svg factory methods

pxtlib/emitter/driver.ts, pxtlib/emitter/emitter.ts, pxtrunner/runner.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
This leverages @mmoskal's work on collecting "usedSymbols" to pass a list of "parts" mentioned in the code as annotated by the `//% parts="..."` annotations. This is essential for the pxt-arduino target, but it could also be used by any target that wants to know this information statically.
=> computes and passes component parts list to simulators

pxteditor/monaco.ts, webapp/src/monaco.tsx
Ensures that ARM assembly is correctly highlighted in the Monaco editor.
Before:
After:
The highlighting rules are based on the [guide to Monarch](https://microsoft.github.io/monaco-editor/monarch.html) and the [ARM Assembly reference](http://infocenter.arm.com/help/topic/com.arm.doc.qrc0006e/QRC0006_UAL16.pdf).
=> ARM Assembly highlighting support

cli/cli.ts, cli/server.ts, docfiles/template.html, pxtlib/docsrender.ts
Resolves https://github.com/Microsoft/pxt/issues/143
For any documentation page this adds a link to the corresponding Markdown on GitHub - it is necessary to set the URL to the GitHub repository in `pxtarget.json` ([I have already done this for pxt-microbit](https://github.com/Microsoft/pxt-microbit/commit/6deb0683b6bd4122ff6cf9057c1f056501cfe517)).
=> Edit button for documentation pages

pxtblocks/blocklyloader.ts
Short words may have multiple meanings, and such words should be translated into different words or sentences in different contexts. The `{id:...}` part in translation source strings will not appear in web pages even when the locale is English or when no translation is available. We can use `{id:...}` to identify the context.
=> Add `{id:}` to short translation source strings

localtypings/pxtarget.d.ts, pxtlib/browserutils.ts, webapp/public/custom.css, webapp/src/cmds.ts
This pull request resolves https://github.com/Microsoft/pxt/issues/238.
The instructions for downloading are now a little shorter, with an optional link to a help guide (the URL of which is specified in `pxtarget.json`). If you click on a step then you get more detailed instructions. For example, these instructions are show in Chrome on OS X:
The download dialog now shows until it is dismissed, to give people enough time to click on the instructions.
The URLs to the screenshots are also specified in `pxtarget.json`, and can be specialised per browser and OS. I have verified that the browser and OS detection works correctly in Edge, IE11, Chrome, and Firefox on Windows and Safari, Chrome, and Firefox on OS X. Each image should be specified as:
```js
{
"name": "connection" //Currently one …
```
=> Download instructions

localtypings/pxtarget.d.ts, pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/cmds.ts
This pull request improves the browser detection code, adds a function [`isBrowserSupported`](https://github.com/Microsoft/pxt/blob/browser-redirect/pxtlib/browserutils.ts#L136) for determining which browsers we allow, and adds rules to `pxtarget.json` for a redirection policy depending on which unsupported OS or browser is being used (it uses the system introduced in https://github.com/Microsoft/pxt/pull/330).
Currently I'm enforcing the following policy:
* If a browser is *actually* one of Edge, Safari, Chrome, or Firefox I allow it. These browsers are all frequently updated, and I have not run into any major issues using any of them with PXT. I also allow Opera, if it is one of the more recent versions that is essentially a skinned Chromium
* Older versions of Opera are not allowed
* …
=> Detection of unsupported browsers

cli/cli.ts, cli/nodeutil.ts, cli/server.ts
These changes allow a PXT target to be used as a dependency in another project, such as an Electron app. Normally the directory structure is:
```
pxt-microbit
| node_modules
| pxt-core
```
This pull request supports structures such as:
```
- electron_app
| node_modules
| pxt-core
| pxt-microbit
```
It also adds an (undocumented) flag `-no-browser` on `pxt serve` that ensures a browser window is not opened and PXT is not rebuilt.
=> Electron support

pxtlib/browserutils.ts
Really minor fixes to the browser checking. This doesn't resolve the issue with Safari, local storage, and private browsing not working as I will separate that out into a separate pull request.
=> New browser check fixes

Jakefile.js
We had a few tasks that were marked as async when they actually weren't and one task that was async but never called complete. This was preventing our tests from running in Travis even though the build claims it passed.
=> Fixing async usage in jakefile

pxtlib/emitter/decompiler.ts
Fixes #371 
The issue was a newline being added to the field name. While I was there, I also fixed up the HTML escaping.
=> Fixing html escaping and whitespace in decompiler

Jakefile.js, backendutils/tsconfig.json, cli/cli.ts, pxtblocks/tsconfig.json, pxteditor/tsconfig.json, pxtlib/tsconfig.json, pxtrunner/tsconfig.json, pxtsim/tsconfig.json
This adds an optional flag to enable source maps for debugging purposes when building and serving the web app. The source maps only seem to work with Chrome right now.
With Jake:
```
jake sourceMaps=true
```
With the CLI:
```
pxt serve -include-source-maps
```
I also removed the `rootDir` option we were specifying in a few of our `tsconfig.json` files because it wasn't doing anything (it only has an effect when used with `outDir` http://www.typescriptlang.org/docs/handbook/compiler-options.html)
=> Adding a flag to enable source maps in the web app

localtypings/pxtarget.d.ts, pxtlib/emitter/driver.ts, pxtsim/instructions.ts, pxtsim/simlib.ts, pxtsim/visuals/boardhost.ts, pxtsim/visuals/breadboard.ts, pxtsim/visuals/genericboard.ts
Especially notice how the breadboard wireframe looks:
**Before**
**After**
=> fixes instructions visual regressions and improves instructions readability

pxtblocks/blocklycompiler.ts, pxtlib/emitter/emitter.ts
Fixes #2 (mostly)
Makes using floating point numbers when targeting a board that does not support them an error. It looks like this:
As part of this, I had to move the max-int check from the block compiler to the emitter, so typing in a huge number will give a similar error now. I also removed the max-float check because it didn't work (not sure if we want to add in a different working one?)
=> Display an error for floating point numbers if not supported

localtypings/blockly.d.ts, webapp/src/blocks.tsx
Fixes #112 
Walks the top blocks and removes any shadow blocks whenever a shadow block is created. Unfortunately, you can still see a flicker of the shadow block appearing and disappearing. Not sure if there is a better solution that doesn't involve altering Blockly.
=> Remove top-level shadow blocks when created by editor

webapp/src/app.tsx
If in sandboxOn mode (sandbox=1)
- launch full editor without sandbox
If in sandboxPub mode (sandbox:PUBID) 
- ensure published project is the latest, if not, publish the project, then go to full editor with new published project id (pub:PUBID in the path)
If in sandboxProject mode (sandbox:FILECONTENTS)
- export project to get the latest file contents, then go to full editor with project:FILECONTENTS in the path
=> "Open in full editor" button in sandbox mode, fixes #426

libs/pxt-common/pxt-core.d.ts, localtypings/blockly.d.ts, pxtblocks/blocklyloader.ts, pxtlib/emitter/emitter.ts, webapp/public/custom.css, webapp/src/toolbox.ts
Fixes #436 
Adds support for the "advanced" comment attribute for blocks and namespaces. If a block is marked as advanced, it will be placed in a "More..." subcategory of its parent category like so:
Here is the subcategory expanded:
Namespaces that are marked as advanced will be placed in a special "Advanced" subcategory at the end of the toolbox
And here is what that category looks like when expanded
=> Subcategories

docs/defining-blocks.md
=> Documenting the "advanced" comment attribute

webapp/src/app.tsx
- larger 'download' button, green
- no text on start/stop buttons
- added "download" class for further skinning
=> reorganize simulator buttons

cli/cli.ts, pxtlib/crowdin.ts
This change allows to store translations for multiple targets in the same crowdin project and share translations.
=> pushing target files to subfolder with targetid

pxteditor/monaco.ts, pxtlib/browserutils.ts, webapp/public/custom.css, webapp/src/app.tsx
Mobile default: 
Desktop default:
=> Setting the default editor font size to be smaller on mobile devices.

pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/block_for2.blocks, tests/decompile-test/block_for2.ts
Now we support both `++i` and `i++`. I could also special-case `i += 1`, but I don't think it's worth it because there are just too many cases to consider.
Fixes #520
=> Support prefix unary incrementors when decompiling for loops

pxtrunner/runner.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/133
Asm code in the hex was file. The source code was incorrect as it always included the default happy face.
=> fixing hex files not retaining the old code

webapp/src/app.tsx, webapp/src/sui.tsx
Refactoring of React modals to avoid rendering them at startup (and calling github for example).
The 'visible' state is now a property maintained by ScriptSearch and ShareEditor.
=> Script search

pxtblocks/blocklyloader.ts, pxtlib/emitter/decompiler.ts, pxtsim/embed.ts
This is a breaking change for the simulator. In support of https://github.com/Microsoft/pxt-microbit/pull/287
=> Modifying simulator interface and fixing mutation property name

docs/defining-blocks.md, pxtblocks/blocklyloader.ts, pxtlib/emitter/emitter.ts
If you mark a typescript API with `//% deprecated=true`, the blocks will not appear in the toolbox but can still be loaded into projects.
Also added some documentation for mutators while I was in that file because I forgot to add it earlier.
=> Adding support for deprecated flag

pxtlib/main.ts, webapp/src/blocks.tsx
Fixes #571 
This event will fire whenever a Blockly project is loaded, including when you switch from TypeScript to Blockly after making a change in the TypeScript. The payload for the event is a map of deprecated block IDs to the number "1" because the API of `pxt.tickEvent` will only take a number or string map. Does `mixpanel.track()` support arrays? If so, I'll change it to just be an array of block IDs.
=> Adding mixpanel event for loading projects that use deprecated blocks

cli/server.ts, package.json
Allow running pxt on platform where serialport fails to install.
=> making serialport optional

pxtblocks/blocklyloader.ts
Part of https://github.com/Microsoft/pxt/issues/595
=> Fix rename property order in mutation attributes

webapp/src/app.tsx
When editing in javascript, the type checking and simulator restart is too agressive. Toning down their excitment a bit.
=> less aggressive on background compilation and saving

pxtlib/emitter/emitter.ts
While emitting property assignment negative enums were treated as run time calls.
=> Fixing the regex issue with negative value enums.

localtypings/pxtarget.d.ts, webapp/src/app.tsx
- Adding flag in pxtarget.json to disable sidedocs completely. 
- Don't show docs menu if missing or empty
=> adding option to disable side docs

docs/develop/blocklyupgrade.md, pxtblocks/blocklyloader.ts, theme/themes/pxt/globals/site.overrides
Blockly removed the option to create a new variable from the variables dropdown. 
Adding option in the Variables menu to create a new variable, like so: 
fixes #630
=> Fix not being able to create new variables in blockly.

webapp/src/monaco.tsx
Removes the double rountrip to validate decompiled blocks.
Extra: removes the "remove block" button.
=> Remove roundtrip

theme/pxt.less, webapp/public/custom.css
=> Fix for sizing issue of the red blocks within the showLed block

localtypings/blockly.d.ts, pxteditor/monaco.ts, theme/pxt.less, webapp/public/custom.css, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/srceditor.tsx
No more global resize event firing when the Project component is updated. 
- Blockly resizing itself (as recommended: https://developers.google.com/blockly/guides/configure/web/resizable)
- Monaco using Auto layout
Tested Main and Sandbox view on Chrome and Safari. 
This needs to be tested on IE and Edge.
Fixes #691
=> Fixing the Blockly Monaco resize issue.

localtypings/blockly.d.ts, pxtblocks/blocklyloader.ts, webapp/src/app.tsx, webapp/src/blocks.tsx
Fixes #668
- Dragging: A change is incomplete if we are still dragging. So similar to how we don't record a change in monaco when the Intellisense menu is up. Dragging now also limits the calls to typecheck / run simulator, if we are dragging.
- Saving: If a change is incomplete, dragging / intellisense, then we don't save.
- Record Undo: Fixes undo bug where we weren't recording that a change had happened when we undo in blockly. fixes #672 
- Debounce: Any change made will trigger a change of debounce events like so: 
- A change has happened, 1 second
- Typecheck, 1 second
- Run Simulator, 1 second in Blocks, 2 in Javascript
- Although, when the editor is updated (first load / switch between blocks and JS), the first step is skipped and we go straight to Typechecking. I've added a check …
=> Blockly / Simulator Optimizations

cli/cli.ts, cli/nodeutil.ts, cli/server.ts, pxtlib/main.ts
Offline HEX cache is now under built/, and gets populated by `pxt serve`
=> Move hex cache

README.md
The code ensures node version is correct, but the user is not warned of requirements in connection with planning the installation of pxt.
=> Ensure minimum node version is specified

pxtlib/emitter/service.ts, pxtlib/emitter/util.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, pxtsim/embed.ts, webapp/src/app.tsx, webapp/src/compiler.ts
When opening side doc page, transfer locale + language context to allow doc rendering to fetch proper translations and show JS or Blocks by default.
=> Editorcontext

webapp/src/app.tsx
When the "download" button is near the scroll point, it flickers the vertical scroll. Using simple "title" attributes for those.
=> disable semantic tooltip as they generate unwanted scrolling

cli/cli.ts, cli/nodeutil.ts
Needed for Electron.
Also removed a couple `else` in `serveAsync()`, because some arguments should not be mutually exclusive (i.e. we should be able to specify --cloud and --just-serve)
=> Update pxtCoreDir when targetDir is updated

cli/cli.ts, cli/nodeutil.ts
Our CLI does not account for NPM 3 vs NPM 2, and assumes that pxt-core is under pxt-microbit/node_modules/pxt-core (which is not always true in NPM 3).
This is a band-aid fix until we can come up with a way for the target to expose its pxt-core dependency, so the CLI won't need to guess where pxt-core is anymore.
=> Fix for pxtCoreDir path on npm 3+

webapp/src/app.tsx
Simplifies the experience in blocks mode.
=> hide start/stop button for simulator in blocks mode

cli/server.ts
This dir doesn't seem to be used at all; after running local serve and playing around with my project, it is still empty. Also, searching both repos for "docstmp" doesn't give any result.
This temp dir is making the Electron app crash when it is installed in C:\Program Files, because you need admin privileges to create a folder in that directory
=> Remove unused temp dir

localtypings/pxtarget.d.ts, theme/pxt.less, theme/themes/pxt/collections/menu.variables, theme/themes/pxt/globals/site.variables, webapp/public/custom.css, webapp/src/app.tsx
Adding getting started button for the widescreen view (in the top right corner). See screenshot:
+ Ui layout cleanups
+ Fix for Explorer / Sim buttons showing up before the editor has fully loaded.
The getting started button disappears after the user has loaded any content in the side docs.
=> Adding getting started button

pxtblocks/blocklyimporter.ts, pxtblocks/blocklylayout.ts, pxtlib/analytics.ts, pxtlib/main.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/core.ts, webapp/src/workeriface.ts
Reporting "error" popup as a tick -- as the error should have been handled upstream. Also sending message as property instead of string to avoid incorrect hashing.
=> report tick instead of crash for user error

pxtlib/main.ts
Richard noticed LZMA compression algorithm kicking in and consuming lot of CPU cycles in Chromebook. We don't need to do compression and generate embedblob for the simulator.
=> Avoiding LZMA compression if the compilation is for simulator

pxtblocks/blocklyloader.ts, pxtlib/emitter/assembler.ts
This change requires the following fix in any target that relies on the inverted toolbox having rounded top and bottom corners: 
Add this in style.less:
.blocklyTreeRow.blocklyTreeRowTop {
border-top-left-radius: 10px;
border-top-right-radius: 10px;
}
.blocklyTreeRow.blocklyTreeRowBottom {
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
}
This fix means the rounded corner radius is no longer a hard coded radius inside pxt, and can be altered in the target using the classname blocklyTreeRowTop and blocklyTreeRowBottom.
=> Remove set top and bottom radius in inverted blackly toolbox.

webapp/src/core.ts
Fixes #793 
By default, semantic just uses a selector that gets all `<body />` elements when it tries to dim the screen for a modal (it assumes there is only one in the page). Blockly comments use `<body />` elements for their bubbles, so when a bubble is present Semantic throws an exception. This fix just overrides that selector.
=> Fixing modal dimmer jquery selector

cli/cli.ts, cli/server.ts, webapp/src/app.tsx
Needed by Electron to communicate with the WebApp. The built-in Electron messaging channels are a security issue for us, because they would let the web app require Node core modules such as fs.
=> Add local server support for external messaging

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/github.ts
Adding feature to publish a project to an anonymous gist.
To test: 
```
mkdir testproject; cd testproject
pxt init
pxt gist
```
Command line output: 
Publishing project to gist anonymously.
Uploading....
Success, your gist url is https://gist.github.com/527cb76153bb38b5c86aac5697619a6e
You can load your published project at https://pxt.microbit.org/#pub:gh/gists/527cb76153bb38b5c86aac5697619a6e
Also fixed issue with package install, see github.ts
=> Publish anonymous gist from command line

localtypings/pxtarget.d.ts, webapp/public/custom.css, webapp/src/monaco.tsx
Add an option in the monaco editor context menu to load up the reference docs of a specific function or namespace in the side docs. 
Fixes #799
Also, (custom.css) fix for monaco editor signaturehelp CSS bug in Safari: https://github.com/Microsoft/monaco-editor/issues/253
=> Add option to show the definition of a method in the sidebar

localtypings/pxtpackage.d.ts, pxtlib/cpp.ts
Allows package to declare a set of optional compilation flag that can be safely overriden.
=> support for yotta.optionalConfig flags

cli/cli.ts, localtypings/pxtpackage.d.ts, pxtlib/github.ts
Publish a gist under a user using a github TOKEN.
Saving current gist in pxt.json
cli options to force create a new gist, and publishing a public gist (default to secret).
**Create an anonymous gist**
```
pxt gist
```
**Create an gist under a user account**
```
pxt gist --token TOKEN
```
**Create a new gist (if preexisting)**
```
pxt gist --new
```
**Create a public gist (instead of secret)*
```
pxt gist --public
```
valid example: pxt gist --token TOKEN --new --public
=> Publish a gist under a user account using a github TOKEN.

pxtblocks/blocklyloader.ts, theme/pxt.less, theme/themes/pxt/globals/site.variables, webapp/src/app.tsx, webapp/src/blocks.tsx
Adding an "Add package" button to the blockly toolbox. Clicking on the button opens up the Add package dialog.
Button is the same size in all viewports.
See examples below:
=> Adding an "Add package" button to the blockly toolbox

webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/sui.tsx
Although built-in tooltips don' look quite as good, there are rendering issues with the Semantic CSS tooltips. Switching all tooltips to use "title" to stay on the safe side.
=> using "title" instead of semantic "tooltip"

webapp/src/app.tsx
Rename "Open project" to "Projects" in the main menu
I've kept the icon as the open folder icon
=> Rename "Open project" to "Projects" in the main menu

localtypings/blockly.d.ts, pxtblocks/blocklycompiler.ts
- when a block has external inputs turned on, generate argument on new lines.
- apply formatting to generated TS code.
=> use externalinputs information when generating TS

webapp/src/app.tsx, webapp/src/db.ts
Couple of issues
- Pouchdb  promises were native promises instead of bluebird based. This is due to the fact we initialize window.Promise after requiring pouchdb. Reordered initialization to generate the right promise
- Unload event would trigger saving the scripts again. Guard against the reload. 
Fixes https://github.com/Microsoft/pxt/issues/804
=> fixes for reset issue 

webapp/src/app.tsx
- stop simulator and restart as needed around compilation
- display "loading" circle on download button and prevent multiple-download for overzealous button smashers
=> stop simulator while compiling

localtypings/pxtarget.d.ts, pxtlib/cpp.ts, pxtlib/emitter/emitter.ts
Useful to figure the exact yotta module content from the web ide.
=> emit 'yotta.json' or 'platformio.json' along with build output

pxtblocks/blocklymutators.ts, pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/mutator_object_destructuring.blocks
Fixes #641 
This fixes the issue where if you rename a piece of a radio packet and then remove and re-add the variable in the callback block, the variable name in the block reverts back to the property name instead of the user name. Now renames done by the user will be persisted.
=> Persist the renames in object destructuring mutators

pxtblocks/blocklyloader.ts, theme/pxt.less, webapp/src/blocks.tsx
Adding an undo button at the bottom of the blockly toolbox.
In Mobile: 
Fixes #851
=> Adding an undo button in the blockly toolbox

webapp/public/custom.css
This overrides macOS Lion+ functionality to hide scrollbars when not in use. 
Fixes #814
=> Always show scrollbars when a div can be scrolled

theme/pxt.less
Fix ensures we no longer rely on a hard coded margin value.
=> Fix the sidebar bottom whitespace that appears on certain resolutions

webapp/src/codecard.tsx
The classname `orange` was misspelled `oragne`.
=> Fixed typo in codecard markup.

theme/pxt.less, webapp/src/app.tsx
Showing the getting started button for the computer and tablet form factors, as well as on browsers that don't support sidedocs. Opening the getting started docs in a new tab in that case.
Fixes #841
=> Opening the getting started docs in new tab when sidedocs is not supported

.travis.yml, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/pxtjson.tsx, webapp/src/srceditor.tsx, webapp/src/sui.tsx
- project input box moved to settings page
- project name displayed in window title
- window title gets updated with name
- projects and /blocksjavascript buttons swapped
- blocks/javascript have an active state
- remove editor specific menu item
- renamed "Project Settings..." to "Rename..."
- hamburger menu to the right, using "setting" icon
Updated icons.
=> nav menu refactoring

pxtlib/emitter/driver.ts, webapp/src/app.tsx, webapp/src/cmds.ts
Add a "Save Project" button under "Project" that generates a .pxt file (LZMA project contents).
=> resurect  "save .pxt file" support

pxtblocks/blocklyloader.ts
Allows to provide a default value for field parameters (instead of the first default value)
@param foo bla bla bla, eg: Foo.Bar
=> support for specifying default values on enum parameters

pxtblocks/blocklycompiler.ts
Before, they just compiled to "Infinity" and you got a "name not recognized" error.
=> Fix error when very large numbers are typed into blocks

localtypings/blockly.d.ts, pxtblocks/blocklyimporter.ts, webapp/src/monaco.tsx
lighten namespace and method colors by 60 % when using the inverted monaco theme.
=> Use lighter colors for inverted monaco themes

pxtblocks/blocklycompiler.ts, webapp/src/blocks.tsx
Issue not addressed in this PR: in general, we don't store disabled blocks in Javascript. This creates a rountrip issue where we potentially loose code when the user modifies the javascript. We need to support this scenario for the "on start" event functionality any so it will be addressed in a future PR.
=> Detect and disable duplicate events

webapp/src/app.tsx
How do you think to show "description" string from "pxtarget.json" in the About dialog? This could be useful to show the origin of this software (PXT) and who are providing when customized by the target.
=> Show description in About dialog

pxtlib/blocks.ts, pxtlib/emitter/service.ts
You know that the natural languages have different structures and logic. It is unable to translate phrases one-to-one basis.
Currently, PXT is checking translated block name strings have same structures in compared to the original strings in its runtime (`localizeApisAsync()` in `pxtlib/emitter/service.ts`). This constraint makes it very hard to translate blocks.
This PR is to remove the constraint. However, the vertical bar `|` is still required after argument names `%var`.
=> Remove check for translated block definition

pxtblocks/blocklycompiler.ts, pxtlib/cpp.ts, pxtlib/emitter/decompiler.ts, pxtlib/emitter/emitter.ts
See https://github.com/Microsoft/pxt/blob/master/docs/defining-blocks.md#auto-create for docs
This generally avoids null-deref errors in blocks. Neopixel should be treated with this one.
=> Implement autoCreate blocks attribute

docs/writing-docs.md, pxtrunner/renderer.ts, theme/pxt.less
Inline code blocks in markdown with start/ending `[` and `]` will be rendered as  blocks.
=> Inline blocks in docs

electron/dev_tools/test_data/release.json, electron/src/main.ts, electron/src/typings/interfaces.d.ts, electron/src/updater/updateservice.ts, webapp/src/electron.ts
Enables us to mark certain versions for "url updates", which causes the update prompts to open a URL in the default browser instead of downloading the update directly.
=> Add support for website updates

pxteditor/monaco.ts, webapp/src/monaco.tsx
Note: Always showing English namespace names in the monaco toolbox, even if the rest of the app is localized. This is to match the namespace names found in intellisense. 
Perf improvement: No longer compiling blocks to populate the toolbox. Populating the toolbox from the definitions collected using typescript's getNavigationBarItems, including toolbox category colors and weights.
=> Fix for localization bugs in the monaco toolbox.

package.json
This adds some Jake tasks most frequently used during local development
as NPM run scripts to avoid requirement of installing Jake tool globally
as adviced in README. Instead default NPM client behavior is used to run
local version of Jake from locally installed modules:
https://docs.npmjs.com/cli/run-script
Thanks!
```bash
npm run
Lifecycle scripts included in pxt-core:
test
jake travis --trace
start
jake default
available via `npm run-script`:
clean
jake clean
lint
jake lint
test:all
jake test
test:decompiler
jake testdecompiler
test:decompiler-errors
jake testdecompilererrors
test:err
jake testerr
test:fmt
jake testfmt
test:lang
jake testlang
update
jake update
```
=> Add most commonly used Jake tasks to NPM run scripts

pxtblocks/blocklycompiler.ts, pxtlib/emitter/decompiler.ts, pxtlib/emitter/emitter.ts, tests/decompile-test/baselines/string_concat.blocks, tests/decompile-test/string_concat.ts
Fixes #678 
This makes it so that string concatenation works when going from typescript to blocks. I think the future plan is to have a whole string package that gets added when you use strings, but I don't think that story is 100% thought out yet. In the blocks, I am using Blockly's built in `text_join` block. For example,
With this typescript:
```typescript
let x = "hello" + (5 + 6) + "okay";
```
You get these blocks:
I don't do type checking in the blocks for the inputs. Rather, I ensure that the block always outputs a string by checking if the first input is a string and adding an empty string if it is not. That ensures that these blocks:
Produce this TS:
```typescript
//  A string 
let x = "" + 5 + 6
```
And not this TS:
```typescript
// A number
let x = 5 + 6
```
Blockly solves that …
=> Handle string concatenation in the blocks

webapp/public/index.html, webapp/src/core.ts
Fixes #857 
To Test: 
- Load PXT in Blocks view, add a comment to a block, show a dialog (eg: Reset)
- Load PXT in JS view, show a dialog (eg: Reset)
- Load PXT in JS view, switch to Blocks view, add comment to block, show a dialog (eg: Reset)
@guillaumejenkins could you test the fix in an electron app
=> Fix for 'Dialogs in JavaScript completely break the layout'

localtypings/blockly.d.ts, localtypings/pxtpackage.d.ts, pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtblocks/codecardrenderer.ts, theme/pxt.less, webapp/public/runnertest.html, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/codecard.tsx
Display the code card as a tooltip rather than anchored in the lower right.
- tooltip shows rendered javascript ( https://github.com/Microsoft/pxt/pull/1030 )
- codecard removed https://github.com/Microsoft/pxt/pull/987
=> Display code card as tooltip

localtypings/pxtarget.d.ts, pxtblocks/blocklyimporter.ts, pxtblocks/blocklyloader.ts, webapp/src/blocks.tsx
This PR ensures that an "on start" event is always available in blocks.
=> ensure that 'on start' is always present in workspace

localtypings/blockly.d.ts, package.json, pxtblocks/blocklyloader.ts, theme/pxt.less, theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/globals/site.variables, webapp/public/custom.css, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/pxtjson.tsx, webapp/src/srceditor.tsx
The editor toolbox should encapsulate all the editor specific actions. 
Mobile: 
Mobile collapsed: 
Tablet: 
Tablet collapsed: 
Computer:
Widescreen: 
Fixes #1042
Fixes #930
Fixes #909
Fixes #906
=> Create an editor toolbox

pxtsim/libgeneric.ts
This adds default values for 
- Missing values are no more error instead default value is returned.
- Out of bound access for array are no more error, default value is returned.
Default values are 
- number[]->0
- string[]->null
- boolean[]->false
- object[]->null 
Related change in pxt-microbit: https://github.com/Microsoft/pxt-microbit/pull/335
Fixes https://github.com/Microsoft/pxt/issues/1053 & https://github.com/Microsoft/pxt/issues/1054
=> Default values for array

localtypings/blockly.d.ts, pxtblocks/blocklycompiler.ts, pxtblocks/blocklylayout.ts, webapp/src/blocks.tsx, webapp/src/compiler.ts, webapp/src/monaco.tsx
When converting JS to blocks, lookup position of existing events to reposition blocks.
=> Repositioning events from existing blocks positions

pxtblocks/blocklylayout.ts, webapp/src/compiler.ts
After decompiling javascript to blocks, reinject disabled blocks that were stripped out.
=> inject disabled blocks after conversion

webapp/src/app.tsx
Removing transition animation on each step, as it messes with blockly's render logic.
Fixes #1070
=> Getting Started UI issues in Edge & IE11

webapp/src/blocks.tsx
Handle empty xml file loading and missing on start.
=> always go through importxml if on_start missing

pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtblocks/blocklymutators.ts, pxtlib/blocks.ts, pxtlib/emitter/decompiler.ts, pxtlib/emitter/emitter.ts
Adds the ability to specify a default instance for object-oriented blocks so that the ability to change the instance being referenced in the blocks is hidden behind a mutator. Right now the input is tacked onto the end of the block due to limitations in Blockly.
=> Support for default classes in OOBlocks

webapp/src/app.tsx, webapp/src/blocks.tsx
When loading invalid blockly XML, clear blockly xml and switch back to javascript.
=> handle failing block loading in editor

pxtsim/runtime.ts, pxtsim/simlib.ts
Helper methods to enable: 
pxsim.control.eventValue and pxsim.control.eventTimestamp
Note: using performance.now() in order to get microsecond precision since start time
Fixes #395
@mmoskal please review
=> Control event value and event timestamp

theme/pxt.less
Fixes #1162
When sidebar showing, make room for the sidebar.
=> UI toolbar + sidebar fixes

localtypings/blockly.d.ts, localtypings/pxtarget.d.ts, pxtblocks/blocklyimporter.ts, pxtblocks/blocklyloader.ts, webapp/src/app.tsx, webapp/src/blocks.tsx
Preventing the deletion of "on start" creates frustration when it is not needed. This change allows onstart to be deletable and adds it to the toolbox.
=> allow on start to be deleteable

pxtblocks/blocklyloader.ts, webapp/src/monaco.tsx
Before: 
After: 
Initially it was making two document calls and writing the style at every category. n = number of categories. Once for each toolbox (blockly / monaco).
Changed to append to a buffer, and only write to the page at the end of the toolbox processing.
=> Inject toolbox icon css optimization

pxtblocks/blocklyimporter.ts, pxtblocks/blocklyloader.ts
When importing a script without 'on start', we assume that the script is old and might need patching. This change makes sure not to nest events under 'on start'.
=> do not nest events when importing old scripts

pxtlib/browserutils.ts
Leads to "compilation failed" message if there are no resources defined in a target.
=> Fixing undefined check

localtypings/pxtarget.d.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, pxtsim/simlib.ts, webapp/src/app.tsx, webapp/src/simulator.ts
Split the sim toolbar into two parts (as you can see in the screenshot)
=> Mute simulator using the simulator toolbar

webapp/src/app.tsx, webapp/src/core.ts, webapp/src/data.ts
Fixes https://github.com/Microsoft/pxt/issues/1184
Our current setup for network requests always reports 404's even when performing a search (where a 404 might be a legitimate response to indicate no results). This adds another API that lets the caller deal with 404 errors instead.
=> Fix network request error on search

Jakefile.js, theme/pxtsemantic.less
Only including the modules that we use from semantic JS: 
Reduces semantic.js from 734 KB to 568 KB.
=> Optimization: Semantic JS file

theme/pxt.less
Semantic ui does this: 
/**
* Correct overflow not hidden in IE 9/10/11.
*/
svg:not(:root) {
overflow: hidden;
}
Which messes with new blockly drag optimization: 
https://github.com/google/blockly/commit/e1cd21842a191bf9a2b3f90ad9f4c2d4436f58d1
This fix works around that. 
Needs to be tested on IE, since that semantic css was meant for IE.
=> Fix nasty bug with new blockly drag optimisation and semantic ui.

theme/pxt.less, webapp/src/app.tsx
Making blockly css more specific in order for Edge and IE to execute the css in the right order. 
Fixes #1189
=> Blockly CSS More specific

webapp/src/monaco.tsx
Fixes https://github.com/Microsoft/pxt/issues/1141
The errors still show up on the block for a second before disappearing, but they no longer stick around. I couldn't get them to not show up altogether.
=> Actually discard changes when unable to decompile

pxtblocks/blocklyloader.ts, pxtlib/blocks.ts, pxtlib/emitter/service.ts, webapp/src/blocks.tsx, webapp/src/compiler.ts
Fixes #1140
Part of this PR moves strings for the blocks into a different file and JSON format so that I could use them for searching. I don't think this change has a large impact on perf; I tried to cache data wherever possible to reduce search times. The results aren't perfect either; most blocks turn up just fine in the results but blocks with generic names ("if", "change", etc.) are hard to search for.
=> Refine search to only the toolbox and include builtin blocks

cli/electron.ts, electron/gulpfile.js
Packaging Electron using a released target from NPM was not working due to path issues (packaging local target was not affected)
=> Packaging Electron for a released target

pxtblocks/blocklyloader.ts
Fixing tooltip for built in blocks that need to calculate their tooltip at runtime and cannot be cached. (Math plus minus device etc)
Fixes #1226
=> Fix tooltip for Math blocks. 

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/simulator.ts
there is a race between the debounced events where restart commands get lost
=> ignore isdirty flag when restarting

theme/pxt.less, webapp/src/app.tsx
Hiding zoom, download text in mobile to avoid simulator overlap
=> mobile: hide zoom / download text in expanded mode

webapp/src/monaco.tsx
Fixes #1260
Setting a flag: loadingMonaco when in the process of loading the monaco editor.
=> Fix for Loader.js is loaded more than once

pxtlib/main.ts
=> Verspec conflict logic now ignores 'file:' versions completely

cli/cli.ts
Fixes #1263 
Any file ending in `test.ts` will be excluded from the project (and thus not show up in vscode). This should handle neopixel without any changes there.
=> Exclude test files in pxt_modules from default project

libs/pxt-common/pxt-core.d.ts
Makes the blocks much easier to work with. The old blocks populated everything with "item" by default which was pretty annoying if you were already using the "item" variable. Instead of this:
We now have this:
=> Populate string blocks with shadow blocks and not variable blocks

pxtlib/emitter/util.ts, webapp/src/app.tsx
Original polyfill was moved to a different file. This changed the load order of stuff and is now causing a crash in IE11, which prevents our webapp from loading at all. Moving the polyfill back to the original place for now.
FIxes #1296
=> Moving the Uint8Array.slice polyfill back to the original location

pxteditor/monaco.ts
Double slashes in URL may be harmful on some file systems.
=> Fix double slash

webapp/src/monaco.tsx
Hiding jsdocs from monaco toolbar -- it 's too heavy on text.
* with
* without
=> removing docs from toolbox

theme/pxt.less
Fixes font overlap issues in Edge.
Tested in Windows Chrome, FF, Edge, IE11. Looking good.
=> avoiding 1rem in Edge to avoid blockly bug

theme/pxt.less, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/tutorial.tsx
=> Updating menubar UI

localtypings/pxtpackage.d.ts, theme/pxt.less, theme/themes/pxt/elements/segment.variables, webapp/public/custom.css, webapp/public/index.html, webapp/src/app.tsx, webapp/src/codecard.tsx, webapp/src/core.ts, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx, webapp/src/share.tsx, webapp/src/sui.tsx
=> Updating Projects and Share dialog UI.

pxtlib/browserutils.ts
When saving a website to the home screen, the User Agent string of the launched website doesn't have "Safari" in it.
Example of iPhone (viewing page in Browser) :
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1
And the same phone (viewing the same page in WebApp) :
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69
Fix: Adding check for iPhone, iPod or iPad in the UA string for Safari detection.
Fixes #1252
=> IOS Home screen UA issue

theme/pxt.less
Removing color from the make a variable block to make it appear different to the other blocks under Variables, and highlight the fact that it's not a block (but a button). 
Before: 
After: 
Fixes #915
=> Make a variable button

webapp/src/monaco.tsx
Fixes names that show up like this: `{{buffer}}` in the Monaco toolbox
=> Remove curly braces from unsupported types in monaco toolbox

cli/server.ts
This has been annoying me for a while. When you use the `--browser` flag of `pxt serve`, launch the browser as a detached process so that `ctrl-c` doesn't kill it along with the server. Otherwise the browser complains about not being shut down properly.
=> PXT serve should launch browsers as a detached process

localtypings/pxtarget.d.ts, pxtsim/simdriver.ts, theme/pxt.less, webapp/src/app.tsx, webapp/src/editortoolbar.tsx, webapp/src/simulator.ts
Also, targets that set headless to true will default to a collapsed simulator.
=> Allow targets to run simulator even while collapsed

pxtblocks/blocklyloader.ts
This is necessary so that API's using the `blockNamespace` comment attribute are sorted correctly against their sibling blocks.
=> Use block namespace comment attribute when sorting by weight

pxtlib/emitter/service.ts
This was causing a bug where fixed instance interfaces were not respecting each other's inheritance information.
=> Prevent type inheritance info from being overwritten

pxtblocks/blocklycompiler.ts
Fixes #652
Redo of #1216 that now lets typescript choose what characters are supported. The variable escaping now works like this:
1. Whitespace is replaced with an underscore (e.g. `my var` becomes `my_var`)
2. Invalid identifier parts (e.g. `:`, `{`, etc) are deleted
3. If the identifier doesn't start with a valid start character (e.g. starts with a number), an underscore is added to the beginning
4. If any identifiers clash as a result of renames, a number will be added to the end of the identifier and incremented until there isn't a conflict
These variable name changes will not roundtrip. That is, the decompiler will not undo them at this time. That's something we could look into doing later if we consider it important.
=> Support valid identifiers in the blocks

pxtsim/simlib.ts
- Using triangle instead of default sine type (as it sounds better). 
- Creating a new OscillatorNode for every note, so the frequency doesnt fade from one note to another, and plays an absolute frequency instead.
=> Improving audio context to sound better

cli/cli.ts, docs/cli.md, docs/cli/bump.md, docs/cli/update.md
Make pxt-core update optional in "pxt bump" . Use ``pxt bump --update`` to update the pxt reference as well.
=> Bump with optional update

pxtlib/emitter/decompiler.ts, tests/decompile-test/always_decompile_classes.ts, tests/decompile-test/baselines/always_decompile_classes.blocks, tests/decompile-test/testBlocks/mb.ts
No issue open for this one, but the problem was that Enums are treated as a special case for the decompiler and that meant that property access expressions on class members were not decompiled properly.
=> Decompiler should handle property access expressions that aren't enums

pxtblocks/blocklyloader.ts
Allow updating of the search input handler (after coming back from a getting started guide). 
If the search box existed, we weren't updating it's handler when updating the toolbox. 
Fixes #1368
=> Update searchhandler after toolbox update

pxtblocks/blocklyloader.ts
Fix issue where IE11 returns null for parentElement. (for XML). 
Having to use parentNode instead. 
Fixes #1431
=> Fixing ie11 tutorial fix.

webapp/src/app.tsx
If the target sets `hasHex` to false, use the download button to save a `.pxt` file (download button does not appear in this scenario)
=> Save project to compressed json when no hex file is available

webapp/src/monaco.tsx, webapp/src/sui.tsx
There's a race condition in the project dialog's state that is breaking the react state. 
Not 100% sure why, but this change should make the open state handled by the component (and not in the prop).
Fixes #1479
=> Projects dialog race condition

pxtlib/emitter/emitter.ts
Otherwise, the ones with `...` were always treated as used
=> Make sure globals initialized with `...` are treated just like "..."

pxtlib/emitter/emitter.ts, pxtlib/emitter/service.ts
Reverting to previous regex for the @param. Using parameter.min and parameter.max in the comments to set min and max values for a parameter.
=> Revert @param regex

localtypings/pxtarget.d.ts, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/container.tsx
Feedback button:
based on feedbackUrl path in target.
Getting started: 
based on tutorial:true field for docsMenu in target.
Note: this will support adding other tutorials in the Menu.
Fixes #1541
=> Feedback and Getting started in the Menu

pxtblocks/blocklyloader.ts, pxtlib/emitter/emitter.ts
Resurrecting this old PR, updated to master. Allows namespace to have subcategories. By default subcategories are sorted by name, but namespaces may also specify an ordering as an array of strings. The ordering is always deterministic. Not really sure how to do localization, @pelikhan thoughts?
=> Subcategories redo

pxteditor/monaco.ts, webapp/src/monaco.tsx
Remove monaco editor error line, and add compiler message markers and error descriptions. 
Fixing undo issue with formatting, using monaco editor's formatting.
=> Monaco editor errors

webapp/src/core.ts
This was a race condition that only happened when Blockly loaded too fast and the loading dimmer never got initialized. In that case, the dimmer would get created incorrectly and start consuming all the clicks for the projects dialog for some reason.
=> Fix project dialog freezing

theme/pxt.less, webapp/src/monaco.tsx
Updating the monaco toolbox blocks so that they look more like blocks
Before: 
After:
=> Monaco toolbox blocks

pxteditor/editor.ts, theme/pxt.less, theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/collections/menu.variables, theme/themes/pxt/elements/header.overrides, theme/themes/pxt/globals/site.variables, webapp/public/custom.css, webapp/src/app.tsx
Adding new embedded thin view. 
This view is for Sandbox (Embedded) AND Portrait (Tablet + Mobile) AND Thin (<24rem height) views:
> 24 rem height in mobile still resorts to this view:
=> New Embedded Thin View

docfiles/toc.html, docfiles/tocheader.html
#1652
form has id
input type=search
no target _blank for sidebar TOC (so it works in Safari)
=> Fix TOC docs search on IOS Safari.

pxtblocks/blocklyloader.ts, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/package.ts, webapp/src/srceditor.tsx
Adding support for global toolbox filters for both blocks and javascript.
Interface:
```
export interface ProjectFilters {
namespaces?: { [index: string]: FilterState; }; // Disabled = 2, Hidden = 0, Visible = 1
blocks?: { [index: string]: FilterState; }; // Disabled = 2, Hidden = 0, Visible = 1
fns?: { [index: string]: FilterState; }; // Disabled = 2, Hidden = 0, Visible = 1
defaultState?: FilterState; // hide, show or disable all by default
}
export enum FilterState {
Hidden = 0,
Visible = 1,
Disabled = 2
}
```
=> Global toolbox filters from controller

pxtlib/docsrender.ts
Crowdin has the bad habit of capitalizing youtube links.
=> make youtube regex case insensitive

webapp/src/container.tsx
With this change, all links from the help menu open in new window (- tutorial)
* Provide a consistent experience accross all browser sizes
* Documentation is browsable/searchable from the full page view
* side doc is really meant to see the help of a particular block (right click help still opens sidedocs) or follow a project (starting package from "projects" dialog still opens sidedocs)
=> always open help urls in new window

pxtlib/emitter/cloud.ts, pxtlib/github.ts, pxtlib/main.ts, webapp/src/scriptsearch.tsx
=> Easier packages

docs/cli/staticpkg.md
I think there are some minor mistakes in the `staticpkg` documentation.
I am not sure the `--route foo` option is for the same purpose as the old cli command `pxt stataicpkg foo`.
=> Fix the cli staticpkg command documentation

pxtblocks/blocklycompiler.ts
Fixes #1609 
The stacktrace was caused by us complaining about a non-Boolean variable being dragged into an if-statement. It also repros in other conditionals (e.g. AND, OR, NOT, WHILE). This change stops our blockly compiler from trying to infer variables to be Booleans based on their use in conditionals and pushes the blocks closer to JS semantics. You still can't drag numbers into if-statements, but variables are fine.
=> Stop inferring boolean from conditionals in blockly compiler

localtypings/pxtarget.d.ts, pxtblocks/blocklycompiler.ts, pxtlib/emitter/decompiler.ts, pxtlib/emitter/emitter.ts
Configurable in the target. Prevents you from having comments in your code that say "On start" but we don't really have a better way of managing that in the decompiler and it's an unlikely scenario.
=> Add optional comment when compiling on start event

pxtlib/browserutils.ts, webapp/src/cmds.ts
=> Save as msg

webapp/src/app.tsx
On mobile, always launched collapsed to maximize space.
=> start collapsed on mobile

pxtblocks/blocklyloader.ts, pxtlib/emitter/service.ts, theme/pxt.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/srceditor.tsx, webapp/src/toolbox.ts
Fixes #1725 
This is a minor UI breaking change! This PR fixes the subcategory behavior and removes our hack for advanced categories. Instead, advanced categories and the "Add Package" category are now hidden underneath a toggle.
Regular toolbox:
Inverted toolbox:
=> Better advanced category and subcategory support

pxteditor/monaco.ts, webapp/src/monaco.tsx, webapp/src/monacoSnippets.ts
Adds an advanced toggle to the Monaco toolbox, more built-in categories with TS snippets, and fixes the sorting of the categories.
Still to do: subcategories
=> Make the monaco toolbox categories match the Blockly ones

pxtlib/emitter/decompiler.ts, tests/decompile-test/always_fixed_instance.ts, tests/decompile-test/baselines/always_fixed_instance.blocks, tests/decompile-test/testBlocks/cp.ts, tests/decompile-test/testBlocks/pxt.json
Fixes #1773
Like enums, these should decompile to dropdowns. Also like enums, we should go to grey blocks if they are accessed anywhere other than in a direct method call of the format we support. I couldn't add full tests for this because it requires C++ and our decompiler test suite isn't currently set up to handle that.
=> Fixing decompilation of fixed instance APIs

theme/common.less
When the Z index of the BlocklyWidgetDiv was lowered, we also should have lowered the Blockly scrollbars so that they're still shown beneath it.
=> Lower Blockly scrollbar Z index to be shown beneath the widget

localtypings/pxtarget.d.ts, pxtlib/browserutils.ts
On mobile safari, always use app protocol instead relying on query arguments.
=> support for specifying download protocol in target

pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/no_extra_on_start.blocks, tests/decompile-test/no_extra_on_start.ts, tests/decompile-test/testBlocks/mb.ts
Fixes an error in some docs snippets where an empty on start block gets decompiled alongside the event handler code.
=> Don't decompile empty on start handlers

pxtblocks/blocklyloader.ts, webapp/src/monaco.tsx
Fixes #1794 
If there are no advanced categories but that target supports packages, the add package button will show where the advanced toggle normally does (sorry no screenshots).
=> Hide the advanced toggle when there are no advanced categories

cli/cli.ts, cli/nodeutil.ts, pxtlib/main.ts
When a package is bundled from ``node_modules/..../libs/yyyy``, all files under ``libs/yyyy`` will automatically override the imported files.
=> Support for overriding files in bundled packages from npm

docs/defining-blocks.md, pxtlib/emitter/emitter.ts, pxtlib/emitter/util.ts
when using ``block`` comment attribute.
=> uncapitalize generated block names

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
Allows to specify multiple galleries in the projects dialog.
Allows to specify the "type" of a card: example, tutorial,
=> support for multiple galleries in open project dialog

pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/block_max.blocks, tests/decompile-test/baselines/functions_outputs_as_statements.blocks, tests/decompile-test/block_max.ts, tests/decompile-test/testBlocks/core.ts
Also fixing some incorrect test cases.
=> Don't decompile output call expressions as statements

localtypings/pxtarget.d.ts, pxtlib/emitter/util.ts, pxtlib/main.ts, pxtrunner/runner.ts, webapp/src/app.tsx
Add flag to load translations from crowdin by default. This change allows to pull in translations without having to push a new release.
=> live translations from editor

pxtlib/emitter/service.ts
Typescript expects the host to return a string, not null. This aligns this host with the other implementations we have, but honestly I don't know what `no-default-lib.d.ts` refers to. I think it's just a non-existent file.
=> Fixing worker crash when trying to normalize a null file path

pxtrunner/renderer.ts
Fixes a regression where we started to not render output call expressions correctly in docs (we were rendering them as grey blocks)
=> Don't render grey blocks for output expression signatures in docs

webapp/src/app.tsx
Make mute sim button turn red when muted as a better visual representation
=> Mute button turning red when muted

theme/tutorial.less, webapp/src/app.tsx, webapp/src/tutorial.tsx
Tutorials are now no longer temporary. Always saves as projects. 
Tutorial complete window gives users the option to 
- Complete more tutorials 
- Exit tutorial
=> New tutorial complete view

pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts, webapp/src/share.tsx
Only show SVG screenshot options when enabled. When not in IE.
Fixes #1917
Fixes #1617
=> Disable screenshots in IE

pxtsim/runtime.ts
Here is a project that illustrates the issue:
https://pxt.microbit.org/58676-87874-12525-65291
In the simulator, press the A button three times quickly. It should show "AAA", "BBB", "AAA" but it instead shows "AAA", "AAA", "AAA" because each fiber is executing immediately instead of being queued.
=> Fix interleaving of events in simulator event queue

webapp/src/monaco.tsx
Returning a shoulddecompile flag to indicate when not to decompile after an async format.
Fixes #1960
=> Fixing IE 11 decompile in new project

cli/cli.ts, pxtblocks/blocklyloader.ts, webapp/src/blocks.tsx
When a user loads blocks from 3rd party packages, automatically generate a help url that points back to ``/pkg/::org::/::repo::#::qName::``. Makes package docs much more intuitive to find.
=> Automatically route block help of packages to package doc page.

pxtcompiler/emitter/backjs.ts, pxtsim/langsupport.ts
Added check in generated JS code to make sure we don't try to dereference a property of null/undefined.
=> Add runtime check to generated JS code

webapp/src/simulator.ts
simulator iFrame was using document.referrer to check for sandbox, but in shared projects, the sandbox flag is in the url #hash, which is not passed to the iFrame document.referrer
This blocks sim modals at the webapp level when in sandbox mode
=> Fix popup in sandbox mode

cli/cli.ts
Build specific libraries should be called on demand to avoid creating hard bound dependencies.
rtlcss/autoprefixer are only needed for LESS compilation and not require in other cases.
=> resolve rtcss/autoprefixer when compiling semantic only

pxtlib/github.ts, pxtrunner/runner.ts
When rendering a document page, cached resolve github repos to avoid querying them for each snippet.
=> cached resolve github package in docs

pxtblocks/blocklyloader.ts, pxtlib/service.ts, webapp/src/monaco.tsx
use block attribute on namespace as friendly category name:
```
//% color=#B4009E weight=90
//% block="Shift Instructions"
namespace shift { }
```
Yields
=> Friendly namespace

theme/common.less
=> Make the blockly widget appear above the top menu bar

pxtblocks/blocklyloader.ts, pxtlib/service.ts
`nsn.attributes.block` is already translated; for the category's `nameid`, we want the non-translated name
Fixes #2001
=> Fix missing blocks and duplicated categories when language is not EN

pxtlib/typescript.ts, webapp/src/blocks.tsx, webapp/src/compiler.ts
Running into this error when there is a Diagnostics message: 
missing ts.DiagnosticsCategory enum in compiler.ts
It looks like parts of the compiler that call setDiagnostics don't run in the web worker and thus don't have the ts definitions for the DiagnosticsCategory enum.
=> Fix Diagnostics error

cli/cli.ts
Removing support for "-yt" and always run yotta locally.
=> always turn on yotta when building locally

pxtblocks/blocklycompiler.ts, pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/custom_field_editors.blocks, tests/decompile-test/custom_field_editors.ts, tests/decompile-test/testBlocks/basic.ts
If a block has a field editor inline, we need a way to decompile literals into a field with that value passed to the field editor.
=> Support for decompiling field editors when they are on the block

cli/cli.ts, docs/target-creation.md
If there is no tsprj we now generate it from blocksprj.
This also removes the *prj from bundledpkgs in appTarget. If you know any reason it's needed there, please shout! @pelikhan @microsoftsam @riknoll
=> Autogenerate tsprj from blocksprj if needed. Remove *prj from bundled pkgs

pxtlib/service.ts, webapp/src/app.tsx
These changes let targets that override `deployCoreAsync()` download files and show confirm dialogs. This is required for targets that use a modulator deployment.
=> File download in extensions

pxtblocks/blocklyloader.ts
Fixes https://github.com/Microsoft/pxt/issues/2067
Idea is to simply extract the shadow value and insert it back to the front
=> Fix logic for showing shadowvalue at the top of dropdown

cli/pyconv.ts, pxtcompiler/emitter/backjs.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxtsim/libgeneric.ts, test-errors/tagged-templates.ts
This might be useful if we want to embed some data in sources - compact representation in sources and doesn't take any RAM (literals go into flash)
```
const sound = hex `FE01DD...`
```
Whitespace is allowed in the hex literal.
=> Add support for "hex `01FF00`" - Buffer literals

pxtblocks/fields/field_gridpicker.ts
- Item background color is now slightly faded instead of pure white
- Column widths are now uniform
Before:
After:
=> Change grid picker looks for text items

libs/pxt-common/pxt-core.d.ts, pxtblocks/blocklyloader.ts
Our loader currently only ever appends blocks to the end of a category which means that you can't have dynamically loaded blocks appear before ones hard-coded in the toolbox definition. This hack makes it so that any block with a weight greater than 50 will appear above those blocks. Not ideal, but I'm concerned that the other option of storing the weights in the DOM and sorting as blocks are inserted would impact performance.
Fixes #2115
=> Reorder loops

pxtblocks/blocklyimporter.ts, pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts, pxtrunner/renderer.ts, pxtsim/simdriver.ts, pxtsim/svg.ts, pxtsim/visuals/microservo.ts, webapp/src/app.tsx
Removing all references to querySelector and querySelectorAll (well, except one in the servo part that should be safe). IE11 does not like CSS selectors, so this fixes a bunch of issues.
Fixes #2116
=> No more querySelectors 

Jakefile.js
#1944
This fix doesn't completely solve all android monaco editor keyboard issues, but it tackles a big part of them.
Disabling autocomplete on the text field.
=> Fix for android keyboard issues

cli/cli.ts, cli/nodeutil.ts
See https://github.com/Microsoft/pxt-common-packages/pull/63
This builds the simulator code in pxt-common-packages and copies it into the target's built directory. If you have a better idea for how the build should work, let me know.
=> Build common sim as part of the target build

pxteditor/editorcontroller.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/public/controller.html, webapp/src/simulator.ts
Adds simulator events for the editor including the usual start, stop, resume, exception, and a new one for when the top level code has finished executing.
=> Adding simulator editor events

webapp/src/app.tsx, webapp/src/appcache.ts
Fixes the bug where if we publish a release and you navigate to a page with our editor embedded, then the embedded editor will update and the embedded project will be replaced with the template project.
=> Preserve embedded pages across reloads

cli/cli.ts
Watching all of pxt-common-packages was causing the build to loop.
=> Only watch sim folders in pxt common packages

pxtblocks/blocklycompiler.ts
Not sure how this broke (or rather, not sure how this ever worked).
=> Fixing NaN appearing in block fields that use a slider

pxtblocks/blocklycompiler.ts, pxtcompiler/emitter/driver.ts, pxtlib/jsoutput.ts, webapp/src/monaco.tsx
Fixes #2224 
This changes the behavior in Monaco so that multi-line statements (e.g. if-statements) get highlighted in their entirety instead of just the first line during slow-mo. It looks like this:
This also fixes the highlighting in blocks for code with comments, which was previously broken.
=> Fix execution trace for statements with comments

pxtblocks/blocklycompiler.ts, tests/blocklycompiler-test/baselines/variables_reserved_names.ts, tests/blocklycompiler-test/test.spec.ts, tests/blocklycompiler-test/variables_reserved_names.blocks
Fixes #2142 
Fixes variable name collisions with reserved TS words, namespaces, and enum names. Let me know if I forgot anything.
=> Change reserved and already taken names when compiling blocks

localtypings/blockly.d.ts, webapp/src/blocks.tsx
Should fix the bug where sometimes it scrolls to the center instead of the top left after translating the blocks.
=> Force scroll of workspace in addition to translating block positions

theme/common.less
This fixes the issue where the simulator overflows the editor toolbar in the tablet and mobile views by overriding the style that is set programmatically by the simdriver. The weird percentage comes from the default value for that padding set elsewhere in `common.less`. Tested across all targets except micro:bit.
=> Disable simulator aspect ratio on smaller screens

theme/common.less
Fix overflow of JS in blockly tooltip showing a non usable horizontal scrollbar.
Fixes #2247
=> Blockly JS tooltip overflow

pxtrunner/runner.ts
Fix bug in tutorial rendering logic. Fixes #2189
The issue was after the full page was rendered by markdown, I had HTML in string format, and I needed the first element of each step. I was using regex to parse the HTML. I am now using the contentdiv passed in and temporarily setting the HTML of each step, and extracting the first elements HTML. Using the DOM to do the parsing.
=> Fix tutorial rendering. 

cli/serial.ts, localtypings/pxtarget.d.ts
micro:bit on windows serial info: 
```
comName: 'COM18',
manufacturer: 'mbed',
serialNumber: undefined,
pnpId: 'USB\\VID_0D28&PID_0204&MI_01\\9900000040304E4500431003000000150000000097969901',
locationId: 'mbed Serial Port',
vendorId: '0D28',
productId: '0204'
```
on mac: 
```
comName: '/dev/cu.usbmodem1422',
manufacturer: 'ARM',
serialNumber: '9900000040304e4500431003000000150000000097969901',
pnpId: undefined,
locationId: '0x14200000',
vendorId: '0x0d28',
productId: '0x0204' 
```
Changing our serial filter logic to filter by vendor / product id and not manufacturer. 
To test, change serial section of pxtarget.json in pxt-microbit to: 
```
"serial": {
"productFilter": "0x0204",
"vendorFilter": "0x0d28",
"nameFilter": "^mbed Serial Port",
"log": true
},
```
=> Filter serial by vendor and product id instead of manufacturer

pxtblocks/blocklyloader.ts
In tutorial mode, we always remove the variables category even if you use variable blocks in your code because the category itself doesn't have any child blocks in its definition. This fixes that bug.
=> Don't always filter out the variables category in tutorials

cli/buildengine.ts
It should work but would be good to test on Windows - check if it says it's removing lots of files like `/source/core/core.cpp` etc.
=> Remove stale C++ files from build directories (as they confuse pio and yt)

webapp/src/app.tsx
It is the responsibility of the embed editor to show the cookie notification.
=> Remove cookie notification from sandbox mode

pxtcompiler/emitter/driver.ts
The introduction of the custom,.ts file for blocks created a problem, as the custom.ts file was ordered after main.ts, resulting in issues like:
https://github.com/Microsoft/pxt/issues/2308
This PR fixes the problem by ensuring that main.ts is the last file in the compilation order.
=> fix compile order problem

pxtblocks/blocklyloader.ts, pxtcompiler/emitter/service.ts, pxtlib/blocks.ts, pxtlib/service.ts
This fixes two issues:
1. We were parsing the default values for parameters in two places which led to the Monaco toolbox not picking up the ones set with the `eg.` syntax
2. The name of the field for the slider block changed at some point and we didn't patch blocklyloader (so blocks with slider inputs didn't have default values set)
=> Fix parameter defaults in blocks and monaco

webapp/src/share.tsx, webapp/src/sui.tsx
In order to make sure we don't select part of the share URl. This ensures whenever we click or focus on the field, it selects the entire share URL string. Same for advanced sharing.
=> Select all input on click in share dialog

docs/defining-blocks.md
The "defining blocks" documentation section talking about icons includes a link to the Semantic UI documentation, that page does not include the unicode characters required, so a link to the Font Awesome website (which does include that information) has been added.
Fixes https://github.com/Microsoft/pxt/issues/2347.
=> Clarify doc information about block icons

webapp/src/core.ts, webapp/src/sui.tsx
Fix issue with Mobile Safari where copy doesn't work in the share dialog.
Element.select() doesn't work in Mobile Safari. Using setSelectionRange instead: 
https://stackoverflow.com/questions/3272089/programmatically-selecting-text-in-an-input-field-on-ios-devices-mobile-safari
=> Mobile Safari input copy fix

localtypings/blockly.d.ts, pxtblocks/blocklyloader.ts, webapp/src/blocks.tsx
- 300ms debounce
- No Jquery
- Show flyout after search completes. 
- Show flyout on click, Fixes #2071 
- Intercept Blockly toolbox key down event for valid characters, and switch focus to search input. (If a user is browsing the toolbox, and starts typing, we immediately switch focus to the search input)
=> Better search interactions

pxtblocks/blocklyloader.ts, theme/common.less, theme/themes/pxt/globals/site.variables
Making it relative to the blockly div, and not the blockly toolbox div. Fixes #2328
=> Fix positioning of the blockly trash icon

webapp/src/app.tsx
While we set the filters on theEditor.state.filters on workspacesync,
we end up overwriting them when theEditor.loadHeaderAsync(*, null) is called.
=> Apply filters that are passed in with workspacesync

webapp/src/monaco.tsx
Not sure if this is the right place for this fix.
I'm able to add 1 to the line number to avoid the off by 1 issue, but the monaco editor is just surfacing what is returned inside file.diagnostics. 
@mmoskal should this fix be done in the compiler?
=> Fix monaco editor error markers, line number's off by 1.

localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
Support examples that compile to blocks, using the cardType: blocksExample.
eg: 
```
{
"name": "Blinky",
"url":"/examples/basics/blinky",
"cardType": "blocksExample"
},
```
=> Examples that compile to blocks

webapp/src/monaco.tsx
- If no defaultState is specified, the default is effectively VISIBLE in Blocks mode. This appears to be because the Block creation generates the entire list of blocks, then filters them out in filterBlocks(). Because there's no default case statement to handle the case where defaultState is undefined, blocks are NOT removed.
https://github.com/Microsoft/pxt/blob/master/pxtblocks/blocklyloader.ts#L1107
However in text mode, it's the opposite. If the defaultState is not specified, the block is excluded:
https://github.com/Microsoft/pxt/blob/master/webapp/src/monaco.tsx#L680
- There's an uncaught exception here that prevents blocks from loading if el==undefined
https://github.com/Microsoft/pxt/blob/master/webapp/src/monaco.tsx#L614
- There's an uncaught exception if an advanced category is …
=> Fix a couple of monaco editor filter bugs.

pxtblocks/blocklyloader.ts, pxtlib/blocks.ts, tests/blocklycompiler-test/baselines/lists_empty_inputs2.ts, tests/blocklycompiler-test/baselines/lists_length_with_for_of.ts, tests/blocklycompiler-test/cases/lists_length_with_for_of.blocks, tests/blocklycompiler-test/test.spec.ts
Fixes #2374 
We have two length blocks (one for strings and one for arrays) that up until now have been interchangeable. Unfortunately, our compiler doesn't support that and it caused type inference issues where arrays would occasionally be declared as strings. This PR makes them explicitly separate and alters the checks in the block definition so that they only accept either strings or arrays but not both.
Before:
After:
I'll need to cherry-pick this into V0 once merged. This might be a minor breaking change...
=> Separate the two length blocks

pxteditor/editor.ts, webapp/src/monacoSnippets.ts
The comments here weren't entirely true: https://github.com/playi/pxt-wonder/issues/74
They're closer now, but `MonacoToolboxBlockDefinition` still isn't quite the same as `MonacoBlockDefinition`, as the former doesn't have a nested `attributes`.
=> Add group label to monaco blocks

docfiles/macros.html, pxtlib/docsrender.ts
You can see the issue this fixes [here](https://makecode.microbit.org/docs). Try to expand the nested accordions under the courses heading and they collapse immediately. The fix is that only top-level accordions should have the `ui` class added to them
=> Fixing nested toc accordions in the docs

package.json, pxtblocks/blocklycompiler.ts, pxtblocks/blocklymutators.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/service.ts, tests/decompile-test/baselines/functions_callbacks2.blocks, tests/decompile-test/cases/functions_callbacks2.ts
Fixes #1676 
This is a big change to our generated TypeScript, so let's make sure we're all on the same page before merging. Instead of compiling event handlers to arrow functions, we will instead compile to function expressions because the keyword makes it easier to understand.
In other words, this:
Will now compile to this:
```typescript
input.buttonA.onEvent(ButtonEvent.Click, function () {
})
```
Instead of this:
```typescript
input.buttonA.onEvent(ButtonEvent.Click, () => {
})
```
=> Use function keyword for blocks instead of arrow functions

docfiles/docs.js
This was causing the docs to not render because IE11 doesn't support arrow functions. The regression happened here: https://github.com/Microsoft/pxt/commit/262d7e30a706e2a61ef15fa626d3e58d399a8c98
=> Fixing syntax error in IE 11

webapp/src/app.tsx
Fixes #2423 
We had a bug where if you navigated to a file in the file explorer while in the javascript view, you could then switch to blocks and lose your code. This prevents that behavior by always decompiling if the "main.ts" file has been opened regardless of the current file. when switching
=> Always decompile regardless of current editor

localtypings/pxtarget.d.ts, theme/common.less, webapp/src/share.tsx, webapp/src/sui.tsx
Simple Facebook and Twitter social icons in the share dialog that open up new popups into the Facebook sharer / Twitter inject pages: 
Twitter message: "Check out what I made with @twitterHandle and @orgTwitterHandle! LINK"
=> Facebook and Twitter social icons in the share dialog

pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
Guillaume and I pair programmed a solution for pxt targets to be able to access the cdn url. That way targets can use the same generic url to load files locally and remotely. Now the simulator run message passes along the cdn url so that it can be accessed in the initAsync() function.
=> cdn Url now passed to the sim run message

docs/docs.md, docs/targets/samd21targets.md
Trying to get some more detailed docs for setting up a SAMD21 target. I'm deliberately not linking to these anywhere yet because they're not quite ready. Also, I have not gone through these steps myself; I'm just documenting based off memory and looking at pxt-adafruit.
=> Adding more detailed docs for setting up a target

localtypings/blockly.d.ts, pxtblocks/blocklyloader.ts
This does not make a cogwheel appear, it just saves the name of the function in a mutation as well as a field. Our XML still won't match the Blockly XML exactly, but this is compatible at least.
Blockly xml (and what the decompiler produces):
```xml
<block type="procedure_callnoreturn">
<mutation name="foo" />
</block>
```
Our XML after this change (note the redundant field):
```xml
<block type="procedure_callnoreturn">
<mutation name="foo" />
<field name="NAME">foo</field>
</block>
```
We can't get rid of that extra field because a dropdown is editable and all editable fields are automatically saved.
=> Restoring the mutation to the procedure block

localtypings/pxtarget.d.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/driver.ts, webapp/src/compiler.ts
We support a flag in `pxtarget.json` that makes it so the "on start" block can't be deleted. However, we had a bug where you could still delete that block if you switch to JavaScript because the decompiler would not emit it. This fixes the decompiler so that we respect that flag.
=> Decompiler should respect the undeletable onstart flag

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/editortoolbar.tsx
New behavior: When one of the 2 buttons is clicked, it starts spinning, and both buttons are disabled during the operation
Current behavior: Only "download" spins, and neither buttons are ever disabled
Fixes https://github.com/Microsoft/pxt-adafruit/issues/244
=> Better handling of save vs download buttons

webapp/src/monacoSnippets.ts
Looks like if there's two blocks with the same jsDoc, they get merged with some odd behavior.  There should be a modulus operator, but it just shows up as a block with just "0".  I've always assumed that this was a simple number block, but it's the broken modulus block.
Fixing the jsDoc makes this turn into the modulus block.
=> Fix modulus op in monaco flyout

pxtlib/service.ts, tests/blocklycompiler-test/commentparsing.spec.ts, tests/blocklycompiler-test/tsconfig.json
Fixes https://github.com/Microsoft/pxt/issues/2443
In addition to fixing that bug, this PR also unites the behavior of the `eg.` and `.defl=` methods of specifying default parameters. I've also added a ton of Karma tests for testing the comment attribute parser.
=> Fixing default parameter parsing and adding tests

pxtblocks/blocklyloader.ts, pxtlib/service.ts
Fixes #2471 
I'm soft-deprecating the old comment attribute in favor of this new one. Gives three modes "inline", "external" and "auto".
=> Give better control over inline inputs

pxtblocks/blocklycompiler.ts, tests/blocklycompiler-test/baselines/lists_empty_arrays.ts, tests/blocklycompiler-test/cases/lists_empty_arrays.blocks, tests/blocklycompiler-test/test.spec.ts
=> Fixing array inference with the create_empty block

webapp/src/blocks.tsx
Fixes https://github.com/Microsoft/pxt/issues/2102
The issue was that `diag.endline` is undefined on compiler diagnostics.
=> Fix warning labels for blocks

localtypings/pxtarget.d.ts, pxtblocks/blocklycompiler.ts, pxtcompiler/emitter/decompiler.ts, pxtlib/service.ts
Adds a feature where empty event handlers are marked with a comment, like this:
```typescript
input.buttonA.onEvent(ButtonEvent.Click, function () {
// code goes here
})
```
As a result, the decompiler will ignore any comment with the text "code goes here". I'd make that text configurable but we don't have a good way to localize string in `pxtarget.json`
=> Adding optional comments for empty event handlers

pxtblocks/blocklylayout.ts, pxtblocks/blocklyrenderer.ts, webapp/src/blocks.tsx
Every time we decompile, we lose the block location information and so we format the user's block code. If the Blockly workspace's height is greater than its width, then we should format the blocks so that they are arranged vertically rather than horizontally. This fixes that.
=> Friendlier layout of blocks in portrait mode

webapp/src/app.tsx, webapp/src/core.ts, webapp/src/monaco.tsx
Original PR merged to anticipate an Accessibility meeting => [https://github.com/Microsoft/pxt/pull/2426](https://github.com/Microsoft/pxt/pull/2426)
Adding a hidden menu displayed only when the user starts to use tab in the page.
Give the focus to the JS editor when using the "Skip to JS" menu. Give it too when the page load and that we are in JS mode. But don't give the focus when using the Explorer menu.
To reach this last goal, I had to edit app.tsx because of a specific situation : 
1. Create a new project in MakeCode
2. Switch to JavaScript
3. In Explorer, switch to pxt.json
4. Switch back to JS by using the "JavaScript" button or hidden menu (not the Explorer).
As I've made a system that prevent to give the focus if we click on an Explorer item, in this specific case, without …
=> [Accessibility] Hidden tab menu - focus on Monaco editor

theme/highcontrast.less, webapp/src/app.tsx, webapp/src/core.ts, webapp/src/sui.tsx
Multiple bug fix :
- The tab navigation in the Import modal was broken.
- Changed the behavior of the dropdown menu to close/open it by pressing Enter on the menu (but not necessarily a menu item).
- In high contrast mode, the focus was not rendered on the dropdown menu.
- In high contrast mode, the Learn More flyout was not supported.
- In high contrast mode, the info messages like errors for example were not supported.
- In high contrast mode, the background color of the simulator in full screen mode was not supported.
- In high contrast modem, the selected item in the blocky/monaco editor's toolbox was not supported.
=> [Accessibility] Multiple minor fixes and improvement

webapp/src/core.ts
Fixed a bug where pressing Enter in the input field of Make a Variable and Make a function modals was not doing the behavior of a click on the OK button.
Original issue : [https://github.com/Microsoft/pxt/issues/2459](https://github.com/Microsoft/pxt/issues/2459)
=> Fixed a bug where pressing Enter was not validating a Modal.

common-docs/reference/string.md, common-docs/reference/text/char-at.md, common-docs/reference/text/compare.md, common-docs/reference/text/parse-int.md, common-docs/reference/text/substr.md, libs/pxt-common/ns.ts, libs/pxt-common/pxt-core.d.ts, pxtrunner/renderer.ts
* The four methods currently exposed in the editor.
* adjust _renderer.ts_ to use lower case for "/string" rather than "/String" to match our pathing convention from ns names.
* Add the help paths to pxt-core.
----
Ok, so _renderer_ is currently setup to make non-statements/non-block items go to "/reference". I put the 'text' docs under "/reference/text" for now. Fix this or leave it and put stuff in "/reference"? This will also apply to Arrays later.
Also, I don't know how to alias 'text' for 'String' so there's a namespace switch requiring a _string.md_, and not a _text.md_, to then contain cards for docs in _/text/file-name.md_.
=> Add initial 'text' docs and rendering support.

webapp/public/index.html, webapp/src/app.tsx, webapp/src/codecard.tsx, webapp/src/container.tsx, webapp/src/core.ts, webapp/src/projects.tsx, webapp/src/sui.tsx
- The items of the My Stuff, Projects and Examples are now announced as selected.
- The Create new project and Important project are now announced as button.
- The <input file> are now described correctly by the Narrator.
- The <input file> keep the focus when selecting a file on Edge and IE.
- The messages displayed after a click on the Download button or Import file are now read by the screen readers.
- The "Open documentation in a new tab" is now accessible with the keyboard and readable by the screen reader.
- A minor bug linked to the tabindex of the tablist has been fixed on Edge and IE.
Linked issues : [https://github.com/Microsoft/pxt/issues/2520](https://github.com/Microsoft/pxt/issues/2520), [https://github.com/Microsoft/pxt/issues/2522](https://github.com/Microsoft/pxt/issues/25 …
=> [Accessibility] A set of fixes linked to the screen readers in the Projects modal.

webapp/src/app.tsx
Resolves https://github.com/Microsoft/pxt/issues/1918
Slow-mo is selected in normal editor...
...but when we switch to tutorial mode, it's gone.
This state is also cleared when switching _from_ the tutorial _to_ the normal editor.
=> Clear 'tracing' state when switching between normal and tutorial modes

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/array_get.blocks, tests/decompile-test/baselines/block_logic_operators.blocks, tests/decompile-test/baselines/block_text.blocks, tests/decompile-test/baselines/custom_field_editors_no_literals.blocks, tests/decompile-test/baselines/default_declarations.blocks, tests/decompile-test/baselines/functions_output.blocks, tests/decompile-test/baselines/number_with_enum_shadow.blocks, tests/decompile-test/baselines/whitespace.blocks, tests/decompile-test/cases/number_with_enum_shadow.ts, tests/decompile-test/cases/testBlocks/basic.ts
This fixes the shadow block handling so that we always decompile shadow blocks correctly. We used to only do it correctly for strings, Booleans, and numbers.
=> Fixing shadow block handling in decompiler

pxtblocks/blocklyloader.ts, theme/common.less
Blockly toolbox deleting flash red towards the end.
=> Blockly toolbox delete animation

docs/about.md
The proposed change is for the micro:bit and Adafruit Circuit Playground Express! repository hyperlinks. They do not point to an repository, and have had the "microsoft" added into the user part of the link. the format for github repository links is "https://github.com/username/repository" with an example being "https://github.com/microsoft/pxt".
=> Update to about.md to correct hyperlinks

package.json, pxtblocks/fields/field_note.ts
Allows blocks to be built from Javascript syntax like `music.ringTone(music.noteFrequency(Note.D));` 
See https://github.com/Microsoft/pxt/issues/2516
=> Bug 2516 fix v0

pxtsim/accessibility.ts
Fixed an issue where while using only the A, B button and Pin (but no thermometer or light level) in the microbit simulator, a space/padding was moving the simulator.
After fixing this issue, the tag used as an aria-live was visible, so I hidden it too.
Finally, I fixed an issue where the simulator's UI was not correctly displayed at loading on FireFox while using only the A, B button and Pin (but no thermometer or light level). It had an impact on tabbing into the Pin.
This fix is linked to pxt-microbit [https://github.com/Microsoft/pxt-microbit/pull/471](https://github.com/Microsoft/pxt-microbit/pull/471)
=> [Accessibility] Fixed an issue where the accessibility of the Pin was broken and was breaking the simulator.

pxtsim/runtime.ts, pxtsim/simlib.ts
Implements pxsim.control.eventTimestamp and eventValue.  Resolves https://github.com/Microsoft/pxt/issues/395.
=> Bug 395 fix v0

cli/cli.ts
This allows us to generate type declaration files. Otherwise, browserify will error because `.d.ts` files fail to compile.
=> browserify bundle ignores non-js files

pxtlib/blocks.ts, pxtlib/service.ts
Don't load loc strings is invalid spaces or invalid parameter names.
=> Normalizing and validating loc strings

theme/common.less, theme/themes/pxt/collections/grid.overrides, webapp/src/projects.tsx
Tablet layout before:
With these changes:
=> Start page: fix mobile layout for ios / electron; greatly improve tablet layout

common-docs/blocks.md, libs/pxt-common/pxt-core.d.ts, pxtrunner/renderer.ts
Namespaces for some built-ins don't match block naming, such as **Array** to **arrays** and **String** to **text**. So, the help urls are formed like _/reference/String/char-at_ instead of _/reference/text/char-at_. These don't match editor block groups or the doc tree. Here's a proposed fix:
Be careful of the new ```declare namespace Array{}``` since I broke **String** doing this once before :-(
This is related to https://github.com/Microsoft/pxt/pull/2657.
=> Render changes for namespace aliasing.

webapp/src/blocks.tsx, webapp/src/monaco.tsx
Since the latest Blockly release (April), Blockly changes some of the ui events that are called and we no longer get a category close event when a new Block is created.
This meant that we need to explicitly change the state of the editor floats after creating a block.
Also enabled the whole scenario for the monaco toolbox as well.
Fixes #2643
=> Fix editor floats and bring it to the monaco toolbox

webapp/src/monaco.tsx
In case the Advanced section introduces categories with greater length like in #2582
Fixes 2582
=> Resize the monaco editor after clicking Advanced 

localtypings/pxtarget.d.ts, pxtsim/logs.ts, webapp/src/logview.tsx
The Chrome extension of micro:bit is still link in PXT. Refactoring this out to allow 3rd party extensions using the ``?chromeserial=...`` href flag
=> chrome extension is now specified via config

localtypings/pxtarget.d.ts, pxtsim/logs.ts, webapp/src/logview.tsx
Allow ``?chromeserial=...`` to use another extension
=> Allow query argument to override chrome extension for serial

pxtlib/browserutils.ts
Use the download attribute to indicate the file name desired. 
http://caniuse.com/#feat=download
Fixes #2679, Fixes #1421
=> Safari v10.1 now supports download attribute

webapp/src/app.tsx
Fixed an issue where the virtual keyboard on smartphone was not appearing properly after clicking on the JavaScript button.
**Previously :** 
We were giving the focus to the Monaco editor once clicked on the JavaScript button, and the virtual keyboard was not appearing.
**Now :** 
We dont' give the focus anymore with this button. We continue to give the focus to Monaco with the hidden menu.
=> [Accessibility] Fixed an accessibility issue related to the virtual keyboard on a Smartphone.

.vscode/launch.json, docfiles/docs.html, docfiles/docs.js, docfiles/footer.html, docfiles/macros.html, docfiles/pageheader.html, docfiles/style.css, docfiles/toc.html, docfiles/tocheader.html, pxtlib/docsrender.ts, theme/common.less
- Made the tree view in the side bar accessible with the keyboard and screen reader.
- Made the breadcrumb accessible by the screen reader.
- Added a hidden menu to skip the side menu.
- Changed the behavior of the hamburger menu to give the focus to the side menu once opened.
- Made the menu descriptive for the screen reader in general.
Related issues : [https://github.com/Microsoft/pxt/issues/2625](https://github.com/Microsoft/pxt/issues/2625), [https://github.com/Microsoft/pxt/issues/2623](https://github.com/Microsoft/pxt/issues/2623), [https://github.com/Microsoft/pxt/issues/2648](https://github.com/Microsoft/pxt/issues/2648), [https://github.com/Microsoft/pxt/issues/2626](https://github.com/Microsoft/pxt/issues/2626)
=> [Accessibility] Documentation menu accessible with keyboard and screen reader

theme/common.less, theme/sidedoc.less, theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/globals/site.variables
Fixed the color contrast of tab items, disabled headers and item description.
Also added a darker hover and focus color for the Side Documentation button and the buttons in the toolbox.
Related issues : [https://github.com/Microsoft/pxt/issues/2519](https://github.com/Microsoft/pxt/issues/2519), [https://github.com/Microsoft/pxt/issues/2534](https://github.com/Microsoft/pxt/issues/2534), [https://github.com/Microsoft/pxt/issues/2499](https://github.com/Microsoft/pxt/issues/2499), [https://github.com/Microsoft/pxt/issues/2525](https://github.com/Microsoft/pxt/issues/2525)
=> [Accessibility] Color contrast and focus visual render fixed

pxtrunner/runner.ts, webapp/src/app.tsx
Allow tutorials to load if they don't have any filters.
Fix tutorial code regex to support whitespace after ```blocks
=> Minor tutorial authoring fixes

webapp/src/app.tsx
Fixing an issue where the hidden menu was showing the wrong menus on a target (adafruit in this case)
=> [Accessibility] Accessibility adafruit issues

pxtblocks/blocklyloader.ts, pxtrunner/renderer.ts
Use default color if color is null.
Fixes #2716
=> Fix regression in adding packages with no namespace color set. 

theme/common.less, theme/highcontrast.less, webapp/src/container.tsx, webapp/src/core.ts, webapp/src/sui.tsx
- Fixed an issue where the hidden menu was staying opened when it was loosing the focus but has the mouse hover.
- Fixed an issue that was generating a warning in the console after closing a modal with the Escape key because of a bad state in React.
- Fixed an issue where the focus was not trapped in the Import modal when we closed another modal before the Project modal (for i.e : the issue was appearing after using the Language modal, and then the Projects/Import).
- Fixed an issue where, in High contrast mode, the Open documentation in a new tab button was not clearly visible (yellow color on white background when the High Contrast of the system was not enabled). I changed the color and put the background to black so it's visible even if the background color of the documentation is …
=> [Accessibility] Multiple minor fixes

pxtlib/blocks.ts
Addresses: https://github.com/Microsoft/pxt/issues/1708.
=> Adjust cached block help path for 'number'.

pxtsim/accessibility.ts
Edited the enableKeyboardInteraction method to support the keydown and keyup. It is useful for the Adafruit simulator ([https://github.com/Microsoft/pxt-adafruit/pull/287](https://github.com/Microsoft/pxt-adafruit/pull/287)).
This change will be required to support the Adafruit simulator accessibility features.
This change imply another PR that updates the micro:bit simulator to support this change : [https://github.com/Microsoft/pxt-microbit/pull/508](https://github.com/Microsoft/pxt-microbit/pull/508)
=> [Accessibility] Updated the accessibility helper of the simulator for Adafruit

theme/tutorial.less, webapp/public/index.html, webapp/src/app.tsx, webapp/src/core.ts, webapp/src/projects.tsx
Each of these components use dimmers and they interfere with each other's click events causing unexpected behaviour. 
Clearing tutorial mode when creating a new project of any kind. #2120 
Fixes #1803 
Fixes #2120
Fixes #2013
Fixes #2101
I have designated the
body.dimmable area for react dimmers and modals 
#content.dimmable area for the loading dimmer
#root.dimmable area for other semantic dimmers and modals
This way they won't interfere with each other.
=> Fix interference of react, semantic ui and tutorial dimmers

cli/cli.ts
Static packages didn't add the target information in the pxtConfig. This prevented the telemetry from them adding it.
=> Adding target initialization on static packages to ge the telemetry

webapp/src/app.tsx
Fixed an issue where, after a Caps Lock + Right arrow, the narrator was focusing on a hidden element that was describing the simulator. With this fix, the narrator focus on the simulator and describe it, instead of a hidden element and describe it as a simulator.
Related issue : [https://github.com/Microsoft/pxt/issues/2629](https://github.com/Microsoft/pxt/issues/2629)
=> [Accessibility] Narrator focus was navigating to hidden element in item mode and reading it as 'simulator'.

cli/cli.ts
We also ignore /--docs style links that maybe be used in the docs when testing for broken urls
=> ignore /--... urls

pxtblocks/blocklyloader.ts, theme/accessibility.less, theme/common.less, theme/highcontrast.less, theme/pxt.less, theme/sidedoc.less, theme/tutorial.less
Mostly cleaning up CSS. 
Adding a focus outline like so: 
```
*:focus{
outline: 2px dotted black !important;
z-index: 1000;
}
```
TODO:
=> Mostly cleanup, adding focus outline

webapp/src/app.tsx
Impact on the Screen Reader : 
- On Edge with the Narrator : once focused on a button of the simulator, instead of announcing "Simulator region, A button",  it announces the title of the page in the iframe, which is something like "BBC micro:bit simulator, A button".
- On Firefox and Chrome with NVDA and JAWS, the behavior doesn't change, it still announce "Simulator region, A button".
=> [Accessibility] Made the simulator frame not focusable with the keyboard.

cli/cli.ts
editor.js was not being appended to the release manifest when building with staticpkg.
=> Fixing appcache for target editor extensions using staticpkg

docfiles/editorcards.html, docs/index.html
Add tick events to all makecode.com cards. 
Formatting changes, use  ?w=1 to ignore.
Note: editorcards assumes the tickEvent function exists, I wonder if I should change it to pxt.tickEvent to support the app scenario @pelikhan? 
Alternatively, footer.html isn't instrumented here because of that same reason, it's used in docs. I believing renaming the function to pxt.tickEvent would fix that issue.
=> Instrument makecode.com

theme/themes/pxt/globals/site.variables, webapp/src/sui.tsx
Fixed the color contrast of links in the blog, and fixed the duplication of title and aria-label in button link.
Related issues : [https://github.com/Microsoft/pxt/issues/2624](https://github.com/Microsoft/pxt/issues/2624), [https://github.com/Microsoft/pxt/issues/2564](https://github.com/Microsoft/pxt/issues/2564)
=> [Accessibility] Minor issues.

Jakefile.js
Testing monaco-editor on Android versions 5.1 (Chrome 40), 6.0.1 (Chrome 50) and 7.1.1 (Chrome 55) concluded the following: 
- Android 5.1 does not respect the auto-capitalize setting to off, and begins by capitalizing the first character. Most namespaces start with a lowercase character and so this is annoying. No workaround for this.
- Chrome 40 on Android 5.1 returns different values for ranges.getClientRects than monaco expects with later versions of Chrome. This yields to the monaco editor cursor not updating as the user types, and always snapping left. Fixed in this PR by using the getClientRects's right bounds. Filed monaco-editor issue: https://github.com/Microsoft/monaco-editor/issues/562 with video of repro. 
- Android 6.0.1 keyboards return the back (backspace key) on key down …
=> Android monaco editor issues

pxteditor/extension.ts, webapp/public/extension.html, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/extensionManager.ts, webapp/src/extensions.tsx
Adds the initial handshake for extensions, support for the extensions reading an writing code to their packages, and a test extension. To use the test extension:
1. Add `#debugExtensions` to your URL
2. Add the pxt-neoanim package to your project
3. Open the lights category and click the button. The test extension will load instead of pxt-neoanim.
=> Adding test extension and more protocol work

pxtlib/browserutils.ts
Data shows that we're not allowing many iPad devices through, and marking them as unsupported. Looking at the regex we're using it looks like we weren't supporting the following UAs: 
```
Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 | 295 |  
  | Mozilla/5.0 (iPad; CPU OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E304 | 263 |  
  |Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Mobile/15A5341f | 51 |  
  |Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 | 50 |  
  | Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 | 48 |  
  | Mozilla/5.0 (iPad; CPU OS 10_3 like …
```
=> Allow iPads to use PXT

localtypings/pxtarget.d.ts, pxteditor/editor.ts, theme/common.less, webapp/src/app.tsx, webapp/src/scriptsearch.tsx
**Add ?w=1 to the github URL to ignore whitespace changes in this PR**
Adds navigation to custom pathnames. Needed to test /beta and other pathnames (/acc, /newblocks, etc) inside released apps (electron, uwp, etc).
Also displays a warning banner when this navigation is used, as a fail-safe for users accidentally navigating:
=> Add custom pathnames for apps and warning banner

webapp/src/app.tsx
Small fix to not show the "This is an experimental version of the editor" when doing local development.
Using `location.hostname` instead of `cloud.isLocalHost()` to also support `?nolocalhost=1` in the URL (for which `cloud.isLocalHost()` returns false)
=> No localhost banner

docfiles/footer.html
Fixed an issue where the Narrator in Edge was focusing on a hidden element in reading mode.
Related issue : [https://github.com/Microsoft/pxt/issues/2803](https://github.com/Microsoft/pxt/issues/2803)
=> [Accessibility] Fix narrator hidden focus documentation

webapp/src/blocks.tsx
When in snail mode, if you remove a block it remains highlighted even if the program is not running. This fixes that by clearing the highlight on save.
=> Unhighlight blocks on save

webapp/src/app.tsx
Fix editor load telemetry to use actual window width and height.
screen.width = width of the screen
screen.availWidth = width of the screen - scrollbars / toolbars
window.innerWidth = width of the browser
=> Editor load telemetry with actual window width and height

theme/accessibility.less, webapp/src/app.tsx, webapp/src/core.ts, webapp/src/monaco.tsx, webapp/src/pxtjson.tsx, webapp/src/scriptsearch.tsx, webapp/src/tutorial.tsx
- Fixed an issue where the focus was not given to the JavaScript editor when this one was already displayed.
- Fixed an issue where the focus was not being reset after a specific action.
- Fixed an issue where the focus outline was not displayed in the contextual menu.
- Fixed an issue where the color of the notifications was not reset after leaving the high contrast mode.
- Fixed an issue in Rename Your Project where the color of the Save button was not green anymore.
- Fixed an issue where the search button's border in Add Package was not round anymore.
- Removed the focus outline in a dropdown menu in Blockly.
=> [Accessibility] Fixed a set of minor issues mainly related to focus.

common-docs/reference/math/from-char-code.md, libs/pxt-common/pxt-core.d.ts
Not sure why this API is under **Math**.
=> Add the 'fromCharCode' api doc.

localtypings/blockly.d.ts, pxtblocks/blocklycompiler.ts, pxtblocks/blocklycustomeditor.ts, pxtblocks/fields/field_textinput.ts, pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/custom_field_editors.blocks, tests/decompile-test/cases/custom_field_editors.ts, tests/decompile-test/cases/testBlocks/basic.ts
Support FieldTextInput compilation and decompilation on a parent block
(i.e.: not shadow blocks)
=> FieldTextInput parent block compilation

docfiles/footer.html, docs/index.html
* Fixed the focus outline of makecode.com
* Fixed an issue where the narrator was outlining a hidden element in the footer.
Related issues : [https://github.com/Microsoft/pxt/issues/2604](https://github.com/Microsoft/pxt/issues/2604), [https://github.com/Microsoft/pxt/issues/2803](https://github.com/Microsoft/pxt/issues/2803)
=> [Accessibility] Fixed the focus outline of makecode.com

theme/accessibility.less
Mainly fixed an issue where some interactive element that didn't had a specified tabIndex on IE specifically didn't had a focus outline. The reason why is that on IE, the TabIndex HTML attribute value is different from the TabIndex property that we can get in the prototype in JavaScript.
By fixing this issue I also had to precise to do not apply a focus outline on the href elements from the Monaco editor (the context menu use href...).
=> [Accessibility] Fixed IE related issues

pxtlib/blocks.ts
The general math topic includes a section for **Math.abs()**.
=> Point abs() block help to math.md.

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/always_local_variable.blocks, tests/decompile-test/baselines/always_null_and_undefined.blocks, tests/decompile-test/baselines/no_nested_events.blocks
Part of the fix for #2860 
If a variable is referenced in a grey block and the declaration looks like one we auto-generated, then emit the declaration as a grey block
=> Conservatively decompile variables referenced inside grey blocks

webapp/src/monaco.tsx
Fixes #2867 
The line numbers in out diagnostics are off by one, but Monaco's are not. We were adding one where we shouldn't be. I think the issue might be slightly different in V0; I'll take a look after this is merged.
=> Fixing placement of errors in monaco editor

pxtblocks/blocklyloader.ts
How do you guys feel about changing this text?  The block count appears to confuse many users.  i.e., it counts the "on start" block, but we don't delete that block.
=> Remove block count from delete blocks context menu

pxteditor/editor.ts, pxtrunner/runner.ts, webapp/src/app.tsx, webapp/src/tutorial.tsx
Workaround to not download the tutorial markdown for tutorial step lookahead, and use the values returned once the steps are rendered.
=> Do not download tutorial markdown in client, use step length returned by runner

webapp/src/monaco.tsx
Slightly different than the fix for master. This fixes the placement of the red squiggles in the Monaco editor.
=> V0 Fixing placement of errors in monaco editor

pxtrunner/runner.ts
In tutorial, some steps may not have a hint.
=> do not show the "hint" bubble when no hint is available

pxtblocks/blocklylayout.ts
For large block canvas, don't render in high pixel density.
Fix for https://github.com/Microsoft/pxt/issues/2330
=> don't do high density for large images

pxtblocks/fields/field_note.ts
Text is 2 pixels bigger and 2 more pixels are added by a border set in the CSS.
=> Fixing label size for piano editor

pxtblocks/blocklyloader.ts, pxteditor/editor.ts, pxteditor/editorcontroller.ts, webapp/public/controller.html, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx
Option to hide searcher on workspaceSync. Also, hiding search in all tutorials. 
Refactoring editorSyncState to only allow workspaceSync to manipulate the editorState and not the entire appState on sync.
=> Hide search

docfiles/macros.html, pxtlib/docsrender.ts
Fixed an issue where the focus was moving to some hidden link showing on left panel on documentation page.
Version for V0 : [https://github.com/Microsoft/pxt/pull/2923](https://github.com/Microsoft/pxt/pull/2923)
Related issue : [https://github.com/Microsoft/pxt/issues/2795](https://github.com/Microsoft/pxt/issues/2795)
I managed to support those special cases where there is no link for the header of a menu, but that the markdown parser was still generating a href tag.
=> Fixed an issue where the focus was moving to some hidden link showing

theme/_theme/theme.config, theme/theme.config, theme/themes/pxt/globals/site.variables
Fixed an issue where the color contrast of the green text in the documentation was not correct.
Related issue : [https://github.com/Microsoft/pxt/issues/2528](https://github.com/Microsoft/pxt/issues/2528)
Related PR : [https://github.com/Microsoft/pxt-microbit/pull/536](https://github.com/Microsoft/pxt-microbit/pull/536), [https://github.com/Microsoft/pxt-sparkfun/pull/47](https://github.com/Microsoft/pxt-sparkfun/pull/47), [https://github.com/Microsoft/pxt-minecraft/pull/322](https://github.com/Microsoft/pxt-minecraft/pull/322), [https://github.com/Microsoft/pxt-adafruit/pull/323](https://github.com/Microsoft/pxt-adafruit/pull/323), [https://github.com/Microsoft/pxt-chibitronics/pull/68](https://github.com/Microsoft/pxt-chibitronics/pull/68)
For some reason, this issue was fixed by the …
=> [Accessibility] Fixed the color contrast issue in the documentation

cli/cli.ts
Fix crowdin early bailout issue that skips the all folders after seeing a crowdinignore file
I now do a pass and search for the crowdinignore file keeping a list of ignored directories, and checking the directory of the file against those directory.
```
Using target PXT/microbit with build engine yotta
Target dir:   /Users/sam/pxt-microbit
PXT Core dir: /Users/sam/pxt
upload microbit/target-strings.json (11 strings) to https://crowdin.com/project/kindscript
upload microbit/sim-strings.json (0 strings) to https://crowdin.com/project/kindscript
uploading 8 files to crowdin
uploading libs/bluetooth/_locales/bluetooth-strings.json to microbit/bluetooth-strings.json
uploading libs/bluetooth/_locales/bluetooth-jsdoc-strings.json to microbit/bluetooth-jsdoc-strings.json
uploading …
```
=> Fix crowdin early bailout issue

webapp/src/app.tsx
Fixed an issue where the hidden menu was missed positioned in Chibitronics.
Related issue : [https://github.com/Microsoft/pxt-chibitronics/issues/67](https://github.com/Microsoft/pxt-chibitronics/issues/67)
There was no CSS solution. Setting the display to none, visibility to hidden/collapse, position absolute and negative top were not fixing the issue. So I just moved the DOM and it fix the issue without creating marge somewhere else.
=> [Accessibility] Fixed hidden menu position on Chibitronics

webapp/src/core.ts
Accessibility changes regressed the default button class being positive as it adds a focused class to all agree / disagree classes of prompts. 
Fix: Add focused to the button class and keep the default as empty for agreeClass.
=> [Accessibility] Fix agreeClass defaults

docfiles/style.css, pxtlib/docsrender.ts
Images tend to be too large in docs and incur a lot of paginations.
=> Better support for printed images in docs

pxtblocks/blocklycompiler.ts, pxtlib/service.ts
The fix discussed in https://github.com/Microsoft/pxt/issues/2385
Needs to be moved to V0 as well.
=> Add an option to move APIs after on start

cli/cli.ts
Fixes https://github.com/Microsoft/pxt/issues/2954
The solution was to just filter out those errors; the sim implementation check still works. The only other option was to compile a complete program, which would include all of the dependencies in the built folder and ends up being a maintenance nightmare. I started down that path but gave up.
=> Filter out errors in sim implementation check

common-docs/blocks/on-start.md
RE: https://github.com/Microsoft/pxt/issues/2385 and https://github.com/Microsoft/pxt/pull/2940.
The idea here is that the targets will include in their own _on-start.md_ a note about event registration order. This allows for api differences in support for 'late registration' of things like **forever** and **runInBackground** which can be target specific.
The target's version of _on-start.md_ can include a note which might look like:
```markdown
**Who goes first?**
All events are registered before the **onStart** block runs. If your program has a
**[forever](/reference/loops/forever)** loop or a
**[runInBackground](/reference/control/run-in-background)** block, these will not
start until after the code in **onStart** begins.
```
=> Add a event order note replacement tag in `on-start.md`.

webapp/src/sui.tsx
IE 11 doesn't like the use of classList.add with multiple classes. 
Fix is to split it up into multiple calls to classList.add
Fixes #2985
=> Fix IE 11 scrolling in projects dialog.

pxteditor/editor.ts, webapp/src/app.tsx
Fix: when visibility is updated to true, only run simulator if it was running when visibility became false
`?w=1` in URL to ignore whitespace
=> Visibility update only resumes sim if it was running

pxtblocks/blocklycompiler.ts
This fixes the issue where sometimes you get a variable named `_` declared
=> Remove that extra variable declared by blocks with event handler args

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/always_local_variable.blocks, tests/decompile-test/baselines/always_null_and_undefined.blocks, tests/decompile-test/baselines/grey_blocks_multi_declarations.blocks, tests/decompile-test/baselines/no_nested_events.blocks, tests/decompile-test/cases/grey_blocks_multi_declarations.ts
Fixes https://github.com/Microsoft/pxt/issues/2964
Stupid mistake on my part. I'm going to try and add stricter tests for the decompiler and documentation soon.
=> Fixing variable auto declarations in grey blocks

webapp/src/projects.tsx, webapp/src/sui.tsx
Basically, the issue was that every time you type a letter into the project name we would save it. When we save the name it changes the state of the ProjectView which causes the Modal to re-render. Then, the accessibility code that controls the focus of the elements tries to focus the first input in the dialog and messes up the typing.
The solution was to make it so that we only save the name when the user selects save. I had to rework the input class so that it actually updates its text when you type. Previously it did not do that and we were relying on the parent to update the text by passing it as a property.
=> Fixing the input in the save and exit dialog

common-docs/types/function/define.md
The wrong doc was copied as _define.md_ on the back merge for the function type docs from `master`. This is the correct one.
RE: https://github.com/Microsoft/pxt/commit/5e3aa630d813e9078d604ddf7050f36dfa2347df
=> Replace incorrect 'define.md' for function type docs

pxtlib/util.ts, pxtrunner/runner.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/simulator.ts
Refactored `updateLocalizationAsync()` so that the download step is a separate function. This lets the webapp download the sim strings without overwriting the current translations. The webapp can then send these strings to the sim.
=> Sim strings are now localized

theme/home.less, webapp/src/app.tsx, webapp/src/carousel.tsx, webapp/src/projects.tsx, webapp/src/share.tsx, webapp/src/sui.tsx, webapp/src/tutorial.tsx
Mostly accessibility fixes.
Also fixed: 
- Margin between home screen cards
- Margin in hint card. Fixes https://github.com/Microsoft/pxt/issues/2901
=> Home screen accessibility fixes

theme/blockly-core.less
Make blocks a little translucent while dragging so you can see what's behind them.
=> Translucent blocks during drag

webapp/src/projects.tsx, webapp/src/sui.tsx
Fixing a couple of issues here: 
- Exit and save modal was not hiding itself when it was saved. 
- When switching from one modal to another, since everything is async, the first modal would close and cleanup the 'dimmable' 'dimmed' classes from the mountNode (body), and that would break scrolling for the next modal. The fix is to always make sure that the dimmable and dimmed attributes are set when the modal has a dimmer attached.
=> Fix scrolling issues with the projects modal

pxtlib/util.ts, pxtsim/embed.ts, pxtsim/localization.ts, pxtsim/simdriver.ts
Ended up having to duplicate some `lf` logic in the sim. Tried to keep it minimal.
pxtsim does not depend on pxtrunner or any other namespace - which means it needs its own `lf`
=> Fix sim locale

theme/blockly-core.less, webapp/src/projects.tsx
- Removing default padding around blockly tree root
- Adding focused class to the new project and import button for accessibility
=> Very Minor ui fixes

webapp/src/projects.tsx
In console, we see the following message when the homescreenhero image is not defined in the pxtarget:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```
=> Fix undefined error when home screen hero is not defined.

common-docs/reference/arrays/create.md
Will do a pick to ``v0`` also.
=> Fix 'create.md' for arrays.

webapp/src/app.tsx, webapp/src/projects.tsx
If you're on the home screen after loading the editor and you select an example, it will fail to load. The error was that we were trying to decompile before a project was loaded and an exception was being thrown. It has been masked up until now because before the home screen we always had a project loaded in the editor.
Scenarios to test:
=> Create a project before trying to decompile

theme/themes/pxt/views/card.overrides
Fix for https://github.com/Microsoft/pxt-minecraft/issues/381
=> remove vertical bar right of logo

theme/common.less, theme/themes/pxt/views/card.overrides, webapp/src/sui.tsx, webapp/src/tutorial.tsx
- Alignment of buttons and text in the top menu. 
- Right align and attach next and finish tutorial button
- Card fixes:
- add ellipsis to the text if it's too long
- make the header color white only if there's an image
=> Button and card UI fixes

webapp/src/blocks.tsx
No need to have such a fine grained zoom. Zoom twice as much on each button click
=> Better zoom

pxteditor/editor.ts, pxtlib/browserutils.ts, pxtlib/emitter/cloud.ts, pxtrunner/runner.ts, pxtsim/embed.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/core.ts, webapp/src/electron.ts, webapp/src/logview.tsx, webapp/src/monaco.tsx, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx
This PR includes changes to bring a loading queue to the core show/hide loading methods. The issue with the current paradigm of just showing the loading spinner at different points and then hiding it at various points is that it's non deterministic and it's possible to be done with one action, but not done with another (namely tutorials). It's common to find yourself still waiting for the tutorial to load but since the new project has finished loading and all the blocks are there, the spinner disappears. 
This introduces an ID associated with each show/hide loading call, and uses a queue to show the messages. If one action is complete, it shows the next until there are no more to show. 
PR also includes a couple of catch clauses and a tutorial error message to send the parent if we fail …
=> More robust tutorials. Loading queue.

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/projects.tsx
Couple of issues here: 
- When exiting and saving it was async and not waiting until the new project name was saved, hence you see for a second the old file name, and then react updates. Fix here is to make it return a promise and wait for that
- Tutorials were removing the previous project and creating a new one with the same files. Re-using the same tutorial project. This also gets rid of the flatten children warning we see with react as the two projects were identical and had the same timestamp. 
Removing delay for start (not needed), adding delay for end so you can visual see that you're entering / exiting the tutorial experience.
=> Fixing issues with saving projects / tutorials

theme/common.less, webapp/src/app.tsx, webapp/src/electron.ts
Always show cookie on top of everything else. 
Cleanup electron logic so that there's one centralized place for the source of truth. Also only showing cookie message on website, not in an app.
=> Show cookie on top

pxtblocks/blocklyloader.ts, pxtlib/service.ts
I could have used the same comment attribute that we already have for creating multiple instances of mutator blocks but creating a new one seemed cleaner since the behavior is slightly different.
=> Mutate defaults for handler parameter blocks

theme/blockly-core.less, webapp/src/editortoolbar.tsx
Fixes https://github.com/Microsoft/pxt/issues/3086
@guillaumejenkins please test, I remove the previous CSS that was setting it explicitly to 8 as Blockly has: 
- blocklyFlyout at 20
- blocklyFlyoutScrollbar at 30
and your comment was that it should be below the widgetDiv, however the widgetDiv is set to 100 above it. Please test this @guillaumejenkins 
Also: While testing I found this issue with the scrollbars in the mobile view where the editortoolbar's grid is shown above the scrollbar and restricts the user from getting to the scrollbar: 
Fixing in this PR as well.
=> Fix z-index of flyout scrollbars so it's above the flyout.

theme/themes/pxt/modules/modal.overrides, theme/themes/pxt/modules/modal.variables, webapp/src/projects.tsx, webapp/src/sui.tsx
The package extension modal is fullscreen and the fullscreen modal was previously reserved for the home screen. 
Making the home screen have it's own size modal called home, and adding CSS just for that. 
Modal for package extension can still use a fullscreen size.
=> Fix package extension css interfering with home screen

libs/pxt-common/pxt-core.d.ts, pxtlib/blocks.ts, webapp/src/toolbox.ts
- join: "Hello" "World"
- substring had a default length of 1000000 ??
- changed `length of text ""` to `length of ""`
- changed parseInt to have a default number string to make it's function a little more obvious
I would have liked to change the compare block, but I don't think it's possible with our current architecture. @riknoll thoughts?
Before:
After:
=> Update text blocks with better defaults

docfiles/style.css
Fix issue with navigation buttons overlapping the body text making it hard to select the text.
This has to be in v0 as it's a docs fix and we need to publish the doc CSS from v0.
The fix was to make sure the nav buttons had a limited width smaller than the padding of the main body text.
After: 
Fixes https://github.com/Microsoft/pxt/issues/3104
=> Fix overlapping navigation buttons in docs

pxtblocks/blocklyloader.ts, pxtlib/blocks.ts
Revert https://github.com/Microsoft/pxt/pull/3141
Blockly is not defined in the web worker which is where search happens. Using out own enum to define Output Shapes (with the exception of initBlock, where Blockly is defined). 
The enum matches Blockly's values for shapes.
=> Fixing search whilst still maintaining outputShape

pxtblocks/fields/field_colorwheel.ts
=> Using a subtractive color spectrum for the color slider.

pxtblocks/blocklyloader.ts, pxtlib/blocks.ts
Since we already dug this up, removing output shapes for builtins as it's not required at this point.
Filing an issue to clean up other features that are not used: https://github.com/Microsoft/pxt/issues/3145
=> Cleanup output shapes

webapp/src/app.tsx
No need for the modulator DOM elements, the target will take over those.
Related PR: https://github.com/Microsoft/pxt-chibitronics/pull/92
=> Cleanup modulator DOM elements

localtypings/pxtarget.d.ts, theme/common.less, theme/home.less, theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/views/card.overrides, theme/themes/pxt/views/card.variables, webapp/src/app.tsx, webapp/src/projects.tsx, webapp/src/sui.tsx
- Deprecating sideDoc option
- Removing first time here and get started button
- Bringing back the New button in the My projects carousel 
- Clicking on the brand icon inside the editor takes you back to home
=> Home screen changes as discussed at the UI meeting

localtypings/blockly.d.ts, pxtblocks/fields/field_note.ts
Fix field note background, since we can't trust the block color when it's a lone block.
Explanation of fix:
The dropdown for the note picker was relying on either the parent block's color or the shadow block's color for determining what color to use as the background of the dropdown. 
This is problematic for blocks like the note block which use block colors of white. When the block is alone like so: 
It's blockColor is white and it has no parent block to indicate what color to use for the dropdown, so instead of making the dropdown white. I've added an option for the fieldNote to use a custom color that's authored by the developer (editorColour).
=> FieldNote dropdown colour for lone blocks

webapp/src/data.ts
gallery path is encoded on the caller side, so decoding on the service side. Necessary to point to subfolders.
=> decode gallery path in service

docs/index.html, docs/labs.html
If you notice as you scroll the header on makecode.com jumps around. This makes it so that the header is always fixed positioned and the top padding of the underneath element is what changes in the different views / whether we have scrolled past a certain point or not.
Before:
After:
Also fixes a small issue with the positioning of the images in the resource cards in mobile view: 
This is what they looked like currently: 
Tested on:
=> Fix makecode.com header scrolling

pxtblocks/fields/field_imagedropdown.ts, pxtblocks/fields/field_note.ts, theme/themes/pxt/modules/modal.overrides, webapp/src/projects.tsx
Fix home screen scrollbar background.
The scrollbar was white, now it's black and targets can change it to whatever color they want:
- Minor cleanup fixes for image dropdown, and note field picker.
- Fix chgCode when changing into a code example (hide loading)
=> Fix home screen scrollbar color

cli/cli.ts, localtypings/pxtarget.d.ts, package.json, webapp/src/projects.tsx
Galleries are specific in the targetconfig which allows to modify them without shipping the entire editor.
=> load gallery list from targetconfig

pxtlib/cpp.ts
One can now do:
```
yotta: { config: { "CODAL_FOO_BAR": 12 } }
```
=> Allow arbitrary 'yotta' settings

pxtblocks/blocklycompiler.ts, pxteditor/editor.ts, pxtlib/workeriface.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/compiler.ts, webapp/src/gallery.ts, webapp/src/projects.tsx
I was looking into why loading examples was slow. The following was happening: 2 workers (1 for blocks, 1 for compiler), 2 monaco workers (since typescript editor was loaded first). 
This PR addresses these issues. There's been some white space movement so use ?w=1. It shaves off 2 scripting seconds on load on my laptop so probably much more with Minecraft running on the side.
=> Lazy workers

localtypings/blockly.d.ts, localtypings/pxtblockly.d.ts, pxtblocks/blocklycustomeditor.ts, pxtblocks/blocklyloader.ts, pxtblocks/fields/field_toggle.ts, pxtblocks/fields/field_toggle_onoff.ts, pxtblocks/fields/field_toggle_yesno.ts
Localising the text inside of the field editor, supporting custom text length (dependent on language). 
Adding two new field editors: 
- FieldToggleYesNo
- FieldToggleOnOff
The default toggle is now True / False. 
Creating new fields with custom text is a simple as extending FieldToggle and replacing the getTrueText and getFalseText methods. 
Sample:
Tested on: 
- Chrome Mac
- Edge 15
- IE 11
=> Support localized and custom text inside Field toggle

theme/blockly-core.less, theme/common.less, theme/extension.less, theme/fieldeditors.less, theme/highcontrast.less, theme/home.less, theme/sidedoc.less, theme/themes/pxt/collections/menu.variables, theme/themes/pxt/globals/site.variables, theme/themes/pxt/globals/zindex.variables, theme/themes/pxt/views/card.overrides, theme/tutorial.less, webapp/public/custom.css
We've had plenty of issues with z-index in the past. This is a way for us to hopefully get around issues like that in the future, by having all z-index references in one file: 
- referencing each other wherever possible (eg: x = editorZindex + 1). 
- better readibility
zindex.variables file:
```
/* Above everything */
@aboveEverythingZIndex: 100000;
@editorMessageZIndex: 10000;
/* Dimmer */
@dimmerZIndex: 1000; /* From semantic */
/* Menu bar */
@menuBarZIndex: 101; /* From semantic */
/* Editor */
@aboveEditorZIndex: 100;
/* Blockly */
@blocklyToolboxZIndex: 40;
@blocklyWidgetDivZIndex: 100;
@blocklyFlyoutZIndex: 20;
/* From Blockly css.js */
/* blocklyFlyout: 20 */
/* blocklyMainWorkspaceScrollbar: 20 */
/* blocklyFlyoutScrollbar: 30 */
/* blocklyBlockDragSurface: 50 */
/* …
```
=> Z-index organization and grouping

theme/themes/pxt/globals/zindex.variables
Lower editor zindex so the menu dropdown / menu is above the sidedoc
=> Fix dropdown menu / sidedoc zindex conflict

webapp/src/projects.tsx, webapp/src/share.tsx, webapp/src/sui.tsx
sui.Link was by default adding a label class. 
Some links don't have to be labels such as the Embed link in the share dialog. 
Adding support for both.
=> Support label and non label links

pxtblocks/blocklyloader.ts, pxtblocks/fields/field_imagedropdown.ts, webapp/src/monaco.tsx
- Only show group labels when there are blocks in that group
- Use groups for subcategories
- Show a subcategory heading label such as: 
- Fix icondropdown field removing its explicit width when it's hidden
=> Misc blockly fixes

pxtcompiler/emitter/service.ts
Don't generate loc strings for deprecated blocks and typescript functions start with __. This is required for app compat work in Adafruit.
=> do not generate loc strings for deprecated blocs

webapp/src/scriptsearch.tsx
Logging the github package name that's added to a project to get a good idea of what packages are used. This PR is against v0.
=> Log adding github package name.

pxtlib/browserutils.ts, pxtsim/simlib.ts
For sim events, we've been using pointer events on pointer event enabled devices and mouse events on all the rest. 
There is another class of events, touch events, that we should use on touch devices since mouse events are still triggered on touch devices, but much later in the process. 
ie: on a desktop a 2 second long hold goes as follows: mouse down, 2 seconds, then mouse up
on a touch devices, the same action would do: touch start, 2 seconds, touch end, mouse down, mouse up. 
Here's the full order on touch devices: 
```
touchstart
touchmove
touchend
mouseover
mousemove
mousedown
mouseup
click
```
Fixes #2405 and probably a bunch of other issues on touch devices
Fix needs to be integrated to master.
Test matrix: 
Tested with this code snippet: 
```
basic.forever(() => {
if …
```
=> Use touch events on touch devices for sim events

pxtlib/browserutils.ts, pxtsim/simlib.ts
Use touch events on touch devices for sim events. Instead of mouse events.
Integrating https://github.com/Microsoft/pxt/pull/3305 to master
=> [Integrate] Use touch events on touch devices for sim events.

libs/pxt-common/pxt-core.d.ts
Remove extra fullstop causing autocomplete to add an extra full stop when completing the random function.
```
Math.random(4.)
```
is what gets inserted
Only affects v0. Fixes #3292
=> Remove extra fullstop from Math.random eg parameter

cli/cli.ts
A fix for pxt-common-packages. We should not try to build the docs from there. The idea is that if a target does not have a theme, it does not have a front end - thus it is not complete. So we don't build the docs.
=> don't build docs if no theme

theme/themes/pxt/globals/site.variables
Goes with https://github.com/Microsoft/pxt-adafruit/pull/414
=> Make serialTextColor dark by default

localtypings/pxtpackage.d.ts, package.json, pxtblocks/blocklyloader.ts, pxtblocks/codecardrenderer.ts, theme/home.less, theme/packagedialog.less, theme/pxt.less, theme/themes/pxt/views/card.overrides, webapp/public/custom.css, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/codecard.tsx, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx, webapp/src/sui.tsx, webapp/src/tutorial.tsx
Fix issue with sub category menu breaking drag. Fixes https://github.com/Microsoft/pxt-adafruit/issues/401
Add extracontent area in codecards, allowing us to add the package disclaimer in that area
Moving scriptsearch css logic into its own file and making the package cards more standardized
Fix issue with saving in the middle of a drag Fixes https://github.com/Microsoft/pxt-adafruit/issues/355
Support the "longer" type of modals introduced in semantic 2.2.11, useful for hints / extension dialog
=> Various UI fixes

pxtblocks/blocklycompiler.ts, pxtcompiler/emitter/decompiler.ts
Fixes https://github.com/Microsoft/pxt-adafruit/issues/384
The underlying issue is probably a blockly bug. A bunch of spaces were being added for seemingly no reason.
=> Trim whitespace before decompiling and compiling expression blocks

pxtblocks/blocklyloader.ts
This is to make it possible to translate this dialog.
Please do not forget to update the `strings.json` file soon.
=> Translate the delete variable confirmation dialog

pxtlib/hf2.ts, webapp/src/app.tsx
Fixes #3325
It also adds a loop that pings the device every few seconds, and only when the device fails to respond (most likely disconnected), it tries to re-connect.
=> Fix HID/serial re-connecting

webapp/src/toolbox.ts
Translate the default list var name in the `controls_for_of` block.
Missing in #3249 and eaa5b7c?
=> Translate list var name in controls_for_of

pxtsim/allocator.ts
Update the readPin regex to support pins of the format: input.pinA0 and input.ButtonD0
=> update readPin regex

webapp/src/projects.tsx
Automatically load the example markdown in the side docs to allow for authoring a context.
=> open example markdown in sidedocs when opening example

webapp/src/worker.ts
The compiler is broken in IE11 because we forgot some polyfills. These polyfills are duplicated from `pxtsim/util.ts` because pxtsim and pxtcompiler don't have a common dependency we can put these in.
=> Adding missing polyfills in pxtcompiler

common-docs/SUMMARY.md, common-docs/blocks-embed.md, common-docs/share.md, pxtblocks/blocklylayout.ts, pxtlib/browserutils.ts, pxtrunner/runner.ts, pxtsim/embed.ts, webapp/public/docs.html, webapp/public/rendertest.html, webapp/src/app.tsx, webapp/src/package.ts
The foundation is starting to include a lot of screenshots in their web site. This change allows them to easily integrate MakeCode rendered blocks into their page.
The change exposes a new endpoint in /--docs where the embedded IFrame acts as a rendering engine for block program. There is no interference with the 3rd party CSS or JS since it just requires loading the IFrame and send/receive a few messages.
* lanch ``http://localhost:3232/rendertest.html`` to test the feature.
This is a first stab at this kind of feature. We should make it ridicuslouly easy for web devs to support rendered blocks in their blogs/web sites. Because this loads a single IFrame for all doc snippets, it is much faster to render than using individual embeds.
=> 3rd party docs rendering

localtypings/pxtarget.d.ts, pxteditor/editor.ts, pxtlib/browserutils.ts, theme/home.less, webapp/src/app.tsx, webapp/src/projects.tsx
Improve home screen performance by making it not a modal. Shying away from having to handle the home screen state all over the place. The App is now in charge of the home screen state.
The result is fantastic, the home screen loads right away with no weird transition in between.
Two modes. A user is either in home, or in the editor. 
The only way to switch to editor mode is to load a header (loadHeaderAsync). (so for card actions that open urls, or when errors occur, the editor is not loaded). This avoids having to constantly show home when an error occurs anywhere.
When a header is loaded, the url hash changes to #editor (so if a user reloads, they go back to their previous project). 
If you go back to home, the hash is cleared. 
The import dialogs are now part of home, and so they show …
=> Home screen perf improvements

webapp/src/pxtjson.tsx
Fix the settings editor, ensuring it doesn't save the file unless save is clicked.
Also don't save, and give an error if the project name field is empty.
Fixes https://github.com/Microsoft/pxt-adafruit/issues/419
=> Fix settings editor saving

pxtsim/embed.ts, pxtsim/langsupport.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
We were leaking refcounted objects in the simulator. Moving ref counting in the runtime state.
=> moving refcounting in runtime to recycle between runs

pxteditor/editor.ts, pxtlib/cmds.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/projects.tsx
Targets can use the extension story to override download instructions.
=> Allow targets to override download instructions

webapp/src/serial.tsx
Fixes https://github.com/Microsoft/pxt/issues/3364 - CSV headings will be "source1", "source2", etc.
=> Map each data source name to a more readable name

theme/blockly-core.less, theme/home.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/globals/zindex.variables, theme/tutorial.less, webapp/src/projects.tsx
Scroll home screen to element. Placing the selected element in the top left.
Couple other minor UI home screen fixes.
Fixes https://github.com/Microsoft/pxt-adafruit/issues/445
=> Scroll home screen to selected element

docfiles/docs.html, docfiles/style.css, docs/index.html, pxtlib/docsrender.ts, theme/accessibility.less
PR https://github.com/Microsoft/pxt/pull/3389 switched the accmenu to have a class instead of an ID. 
Since v0 and master share the same semantic ui. I'm bringing back the id just for the docs, but still adding the class to allow us to fix this in the future.
=> Fix acc menu for semantic version running in v0

cli/cli.ts, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtrunner/runner.ts, webapp/src/app.tsx
We are using the pxt branch information which does necessarily match crowdin. Pulling the correct branch info from the crowdinbranch field.
This impacts the Minecraft/Seeed editor, where target-strings.json is not being loaded.
=> store crowdin branch information in versions object

docs/defining-blocks.md, docs/packages/getting-started/objects-instances.md, docs/packages/getting-started/ref-docs.md, docs/packages/getting-started/simple-package.md, docs/packages/getting-started/sources.md
=> Add 'objects & instances' topic to packages

webapp/src/monaco.tsx
Fix for https://github.com/Microsoft/pxt-adafruit/issues/469
=> handle namespaces where all blocks are hidden

localtypings/pxtarget.d.ts, theme/common.less, theme/serial.less, webapp/src/serial.tsx
A number of improvements to make the charts more useful when looking at data:
=> improvement to serial view

cli/cli.ts
When compiling snippets using checkdocs, also dump all outputs to subfolder
=> dump all outputs from checkdocs build in subfolder

pxtblocks/blocklyloader.ts, webapp/src/blocks.tsx, webapp/src/monaco.tsx
Caching happens too early for exported variables. This impacts localization of "Advanced" and "Extensions" in the editor.
=> localized strings cannot be used before the language is loaded

theme/home.less
Fix import button position so that it's above the carousel container and can be clicked
Fixes https://github.com/Microsoft/pxt-adafruit/issues/501
=> Fix import button positioning

docfiles/editorcards.html, docfiles/labscards.html, docs/courses/cornellMPS2017.md, pxtlib/emitter/cloud.ts, pxtlib/util.ts, webapp/src/db.ts
This change provides offline storage for localization files.
=> Offline translation files

localtypings/pxtarget.d.ts, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/backthumb.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/ir.ts, pxtcompiler/emitter/thumb.ts
It improves perf by about 2.5x.
This also disables commonalize pass by default - it shrinks code by 25% but causes 25% speed overhead - we're not short of space on any ARM targets using that right now, so let's disable by default.
=> performance improvements in Thumb code generator

pxtsim/langsupport.ts
Fix undefined pxsim.noRefCounting by adding it back using the new runtime.refCounting to indicate when the refCounting is off.
Issue: https://github.com/Microsoft/pxt/pull/3401#issuecomment-345413821
Verified this fix resolves the error introduced in the SIM.
=> Fix undefined pxsim.noRefCounting.

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/emitter/cloud.ts
When an editor is packaged, load targetconfig from local path
=> Support for targetconfig in packaged editors

cli/cli.ts, localtypings/pxtarget.d.ts
When building a new editor, it is not productive to keep the docs fully compliant.
=> add flag to ignore docs errors

webapp/src/app.tsx, webapp/src/core.ts
Fixes https://github.com/Microsoft/pxt/issues/3546.
Problem seems to be that the "about" modal adds class `dimmed` to `#root` when it appears.  The re-render caused by the banner toggle removes this class.  When the `dimmed` class isn't there, modal close doesn't remove the dimmer.  I added a separate element `#dimmerRoot` so that changing the classes on `#root` won't affect the modal/dimmer.
Needs to go into master too.
=> Create separate div for dimmer context

webapp/src/app.tsx, webapp/src/core.ts
Instead of having a separate "dimmerRoot" element, preserve jQuery classes attached to "root" upon re-render.
Needs to go to master too.
=> New approach for fixing dimmer issues

pxtblocks/blocklylayout.ts
Fixes Safari SVG rendering parseerror issue. 
More details in v0 PR: https://github.com/Microsoft/pxt/pull/3610
=> [master] Workaround for Safari parseerror renderblocks issue

pxtblocks/blocklylayout.ts
When rendering blockly SVG to an image, we first parse the XML generated by blockly. The on-start block and any blocks that contain a space in their name will have &nbsp; in the text content. This is valid HTML but in the XML SVG standard. 
A workaround for this as outlined in this chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=340794
is to do a string replace for &nbsp; and convert it to &#160; 
In all our rendered images we always had a parseerror section in the XML including in Chrome, but Chrome / Firefox just recovered better and ignored the parseerror section, whereas Safari didn't.
```
<parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the …
```
=> Workaround to fix parseerror in SVG xml when rendering blocks [Safari]

theme/common.less, theme/serial.less, webapp/src/serial.tsx
Fix for https://github.com/Microsoft/pxt/issues/3619.
- separator is localizable string
- using tab instead of , (tested in Excel)
(+ integrating style fixes for serial from master)
=> Localizable CSV output separator

pxtcompiler/emitter/emitter.ts, pxtsim/langsupport.ts, pxtsim/libgeneric.ts
This is a forward port of #3623 - it doesn't affect SAMD21, and should not affect pure JS targets. It should affect AVR and LTC.
=> Fix switch ref-counting in native integer targets

pxtwinrt/winrtworkspace.ts
Fix for https://github.com/Microsoft/pxt/issues/3618. Tested in Ja/app.
=> Correctly escaping file names in WinRT runtime

cli/cli.ts
I broke this with the TS 2.6.1 change. The issue was that our typing for rimraf was too vague and ended up confusing the TS compiler into thinking the callback was an argument and not a node.js-style callback. That messes up the `promisify` typing and it cascaded from there.
=> Fixing our rimraf usage

localtypings/pxtarget.d.ts, pxtcompiler/emitter/hexfile.ts
Microbit has a bootloader after `0x3c000` - we used to have this hardcoded. This doesn't need to go in `v0`, but if it ever does, I also added the setting to microbit `pxtarget.json` https://github.com/Microsoft/pxt-microbit/commit/1fc80ba6bd25b80afba8b1c04b7f5cad92f5fad3
=> Make one more microbit-specific setting configurable: flashUsableEnd

common-docs/blocks/logic.md, common-docs/blocks/logic/boolean.md
In the new TS version you can't compare two different numbers directly because they are considered different literal types (i.e. instead of "number" and "number" the types would be "0" and "42"). This doesn't have much of a practical effect because those expressions will always evaluate the same way anyways.
=> Fixing equality operators in common docs

libs/pxt-common/pxt-core.d.ts
Enable block context help for **randomRange()**.
RE: https://github.com/Microsoft/pxt-adafruit/issues/566
=> Fix help path for 'randomRange'

.travis.yml, Jakefile.js, README.md, package.json
With the move to TypeScript 2.6.1, we now use @types
=> Removing references to typings and tsd

webapp/src/lang.tsx
The English word「Taiwan」in Chinese (Traditional, Taiwan) should be 臺灣 instead of 台湾 since 台湾 is the word in Chinese (Simplified, China).And when talking about localization we will use 正體中文 instead of just 中文.
=> Correct the localization for Taiwan

pxtblocks/blocklylayout.ts
Fix nbsp issue to replace all instances of nbsp instead of the first one. 
Nbsp issue affects Safari rendering of SVGs as it yields a parse error in the XML. 
Further details here: http://jsfiddle.net/5zk67h59/4/
=> Fix nbsp issue to replace all globally

pxtcompiler/emitter/backjs.ts, pxtcompiler/emitter/emitter.ts, pxtsim/langsupport.ts, pxtsim/libgeneric.ts, tests/compile-test/lang-test0/02numbers.ts
Adding support for ~, ** operator in JS.
=> support for emitting ~, ** op in JS

webapp/src/monaco.tsx
Reworks creation of monaco snippets for fixed instances in toolbox and javascript editor.
- Toolbox snippets now look like `fixedInstanceName.method()`, e.g., `A0.analogRead()`.
- Javascript editor snippets now look like `namespace.fixedInstanceName.method()`, e.g., `pins.A0.analogRead()`.
- New logic to map fixed instances w/specialized classes to the correct namespace by creating a lookup array of all classes and subclasses within the namespace.
=> Correct monaco snippets for fixed instances

localtypings/blockly.d.ts, pxtblocks/blocklyloader.ts, pxtblocks/fields/field_boldtext.ts, theme/blockly-core.less
Adds support for bold fields inside of the text label. 
This is annotated inside the block annotation using markdown annotation (*). 
For example: 
```
//% blockId="testFunction" block="test *function*"
export function testFunction() {
}
```
In the above, function will be bold.
=> Add support for bold field annotation inside the block text

theme/highcontrast.less
Support a better high contrast mode for Blockly blocks: 
This gives us a better contrast ratio between the black background and the white text, avoiding any issues users might run in contrasting between the white text and the color of a block. 
We should still aim to have colors that contrast well with white, but if users are struggling or if the color is still not 100% within the color contrast ratio limits, this gives users another end point to view the blocks that they are struggling to distinguish or read the text.
=> Support a better high contrast mode for Blockly blocks

webapp/src/share.tsx
In favor of lightweight codembed option.
- screenshot can be slow
- screenshot does not work on IE
- screenshot generates huge URLs
=> Removing share -> screenshot option

localtypings/pxtarget.d.ts, pxtlib/github.ts, webapp/src/core.ts, webapp/src/data.ts
Also:
* add a flag to disable proxy (for external deployments if desired)
* fix a bug that would send requests for `/api/foo` several time per second when searching for `"foo"`
Seems to work on Adafruit for me. Requires more testing.
=> Use github.com proxy in our cloud to avoid throttling

common-docs/reference/math.md, common-docs/reference/math/abs.md, common-docs/reference/math/max.md, common-docs/reference/math/min.md, common-docs/reference/math/random-range.md, common-docs/reference/math/trigonometry.md
Fixes https://github.com/Microsoft/pxt-chibitronics/issues/158.
-[x] Move trigonometry out into a side-doc to preserve the content.
-[x] Add _abs_, _min_, _max_ topics for the **Math** reference.
Not adding any _math_ cards as block decompile/generation for Math functions is especially tangled up in _core.d.ts_, _pxt-helpers.ts_, _blocks.ts_, _blocklyloader.ts_, and so on.
=> Split out math topics

pxtlib/package.ts
when a package has multiple core packages, keep the last one only.
=> keep last core package only to avoid conflicts

cli/cli.ts, pxtlib/main.ts, pxtlib/package.ts
This PR:
* builds packages before simulator
* writes shims.d.ts etc even if the common-packages version is the same (for consistency)
* right now, if we change the shims.d.ts generation, it will likely break github packages; after this change it should work (force in writeFile)
* adds `pxt cleangen` to delete generated files
=> Allow for not checking in shims.d.ts and _locales

pxtsim/simlib.ts, pxtsim/svg.ts, pxtsim/visuals/buttonpair.ts
Handle touch or mouse input. Test this change on a computer with touch support. Both mouse and touch should work.
=> support for touch+mouse scenarios

pxtlib/hf2.ts, pxtwinrt/hiddeploy.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/hidbridge.ts
- Uses the WinRT device watcher to reconnect as little as possible to HID devices
- As a result, the serial data polling logic is no longer needed, since we already reconnect when a device is newly plugged in
Not sure if this will fix the Adafruit crash issue, but it certainly makes the whole HID connection much cleaner for UF2
=> Uwp hid improvements

webapp/src/serial.tsx
=> Serial view improvement

pxtblocks/blocklylayout.ts, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/hexfile.ts, pxtlib/browserutils.ts, pxtlib/cpp.ts, pxtlib/main.ts, pxtlib/service.ts, pxtlib/util.ts, pxtrunner/renderer.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/worker.ts
- always use ts.pxtc.encodeBase64 or ts.pxtc.decodeBase64 instead of atob/btoa (not defined in Safari web workers)
This fix should solve the long standing issue around files generated by Safari that cannot be reloaded.
=> Atob or not atob

Jakefile.js, docfiles/apptracking.html, docfiles/pxtweb/README.md, docfiles/pxtweb/cookieCompliance.ts, docfiles/pxtweb/tsconfig.json, docfiles/tracking.html, localtypings/mscc.d.ts, pxtlib/analytics.ts, pxtlib/main.ts, theme/common.less, theme/highcontrast.less, webapp/public/index.html, webapp/src/app.tsx, webapp/src/editortoolbar.tsx, webapp/src/monaco.tsx, webapp/src/projects.tsx, webapp/src/serial.tsx, webapp/src/share.tsx, webapp/src/tutorial.tsx
Bringing over the changes in master to V0. I did this entire merge by hand, so please take a look to make sure I didn't make any obvious mistakes. I still need to do testing.
I had to do a lot more granular instrumentation in this PR than I did in the previous one. In master, every target enters through the home screen which was pretty well covered by our telemetry (every UI element had a call to `pxt.tickEvent()` that I could instrument). App.tsx is much more complicated than the home screen because most of the methods that are called in `onClick` handlers are also called elsewhere. The cookie can only be set in response to user action so I had to edit every click handler to set the consent separately from the telemetry.
Another note is that I couldn't think of an easy way to instrument …
=> Port new cookie consent to V0

cli/cli.ts
Most targets do not have a tsprj these days.
=> fixing "pxt init" when tsprj is missing

docfiles/pxtweb/cookieCompliance.ts, pxtblocks/blocklyloader.ts
Accidentally merged in some test code when porting these changes to V0.
Luckily, this never got released. It probably wouldn't have even been an issue because the test data has a purposefully fake "minimum consent date" so that the cookies always get cleared anyways. The MSCC cookie is still set but it only contains a timestamp and will be cleared on reload.
=> Fixing some cherry pick errors in cookie banner

localtypings/pxtarget.d.ts, localtypings/pxtparts.d.ts, pxtlib/package.ts, pxtlib/webusb.ts, theme/common.less, webapp/src/cmds.ts
- when download fails, a first dialog is shown
- the upgrade firmware dialog is displayed. The URL is board specific and specified in targetconfig.
- the pairing dialog is shown
=> Web USB download dialogs

cli/nodeutil.ts
First try to resolve the issue #3847 on the Markdown `@extended` documentation. I have just added an `"/"` at the end of the `dirs` array.
=> Correct the path resolving of the `@extended` documentation (#3847)

webapp/src/data.ts
This 1/2 line fix solves the issue of the gallery not loading when no scripts where installed. The root of the issue is that only the first component subscribe to a path was "force updated". That worked when you had scripts but failed when you didn't.
It's not clear why we are not seeing this in other targets.
test build:
https://makecode.adafruit.com/app/6c6371385ae0c2ae88523f20a37544f123b83f33-41283cc61a
=> execute forceUpdates async instead synchronously

pxtlib/blocks.ts
I broke the Minecraft onChat block with the parser updates.
=> Fixing handler args blocks

docfiles/pxtweb/cookieCompliance.ts, webapp/src/blocks.tsx
This fix comes with a caveat: we need to be vigilant to make sure that we don't accidentally automate something in the future that causes Blockly to fire this event. Right now this works great
=> Dismiss banner on toolbox click and in native apps

pxtblocks/fields/field_note.ts, theme/fieldeditors.less
Fix field note regression hiding the text field underneath it. 
Fixed by pushing the pianoDiv down 20 pixels to give room for the textbox.
Fixes https://github.com/Microsoft/pxt-microbit/issues/620
Doesn't affect master. 
Tested on Chrome 64, Edge 16, IE 11, Firefox and Safari.
=> [v0] Fix regression in Field Note 

pxtblocks/blocklymutators.ts, pxtblocks/fields/field_parameter.ts
Fixes the confusing dropdown in the radio blocks. This PR is for V0 only.
Changes include:
1. No more dropdown, you now just get a rename dialog when you click on the parameter
2. Parameters cannot be renamed to an existing variable name
3. Parameters cannot be renamed to other parameters on the block (e.g. `receivedNumber` cannot be renamed to `receivedString`). That check ignores whitespace and capitalization (`receivedstring` and `received string` will both be rejected).
4. Attempting to delete the variable from another block will revert the parameter field to its default value. Previously it deleted the entire block and all of its children
This change is backwards compatible and hopefully subtle enough to not break screenshots. BTW, the above GIF doesn't have quotes around the …
=> Adding new parameter field for destructuring mutator

pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtblocks/mathOperations.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/service.ts, pxtlib/blocks.ts, pxtlib/service.ts, tests/decompile-test/baselines/constant_shim.blocks, tests/decompile-test/baselines/math_ops.blocks, tests/decompile-test/cases/constant_shim.ts, tests/decompile-test/cases/math_ops.ts, tests/decompile-test/cases/testBlocks/constantShim.ts, tests/decompile-test/cases/testBlocks/pxt.json, webapp/src/toolbox.ts
This PR adds a math function block. My criteria for which functions were included was mostly about which ones I have ever used in my life, and the list I came up with was:
1. `Math.sin(0)`
2. `Math.cos(1)`
3. `Math.tan(2)`
4.  `Math.sqrt(3)`
5.  `Math.ceil(4)`
6. `Math.floor(5)`
7. `Math.atan2(6, 7)`
And here are the ones that were cut:
1. `Math.asin(0)`
2. `Math.acos(1)`
3. `Math.atan(2)`
4. `Math.log(3)`
5. `Math.exp(4)`
6. `Math.trunc(5)`
6. `Math.round(6)`
7. `Math.imul(7, 8)`
7. `Math.idiv(9, 10)`
In addition to functions, I have also added support for constants on namespaces. It works exactly like enum blocks work; you add a dummy shim function (with the comment attribute `constantsShim`) and then annotate the constants you want in the dropdown with `blockIdentity="qName"`. I don't …
=> Add support for math functions and constants

pxtwinrt/hiddeploy.ts, pxtwinrt/serial.ts, pxtwinrt/winrt.ts, webapp/src/app.tsx, webapp/src/lang.tsx, webapp/src/scriptsearch.tsx
Ok so here's what was happening:
- `reader.loadAsync(32)` in our serial logic blocks the device until 32 bytes have been read
- Until 32 bytes have been read, we cannot close the device
- If we navigate (/beta, change lang, reset workspace) while there is an active `loadAsync()` call, even if the navigation occurs, the device remains stuck in that `loadAsync()` call; disconnecting the device doesn't work and reconnecting is impossible until it is unplugged
- `loadAsync()` can be cancelled, but the cancellation is not enough to put the device into a good state, we need to wait until the `loadAsync()` call fully returns (the `cancel()` will make it reject the promise)
So, the overview of this fix:
- If we're about to change lang, go to /beta or reset workspace, we stop all ongoing …
=> Release all devices on reset, lang change and /beta

pxtblocks/blocklycompiler.ts
This fixes those intermittent errors you see that immediately disappear on blocks. Those errors did nothing (we ignore them) and should be coming from the TS compiler anyhow.
=> Removing blockly compiler type checking errors

pxtblocks/blocklyloader.ts, pxtcompiler/emitter/service.ts, pxtlib/service.ts
- Search now respects `disabled` and `hidden` filters, both at the category and the block level
- Search now includes localized category name (since it's different from the namespace)
=> Include localized category in search and respect filters

README.md, package.json
Wanting to slim down our install steps, there's no need to install jake globally with this change.
Note: we (MakeCode) might still want it installed globally for v0 / I think @riknoll uses it to serve repos, but I think a new pxt developer can avoid the need to install it globally with this change.
This method is also more future proof if we change our build tools (away from jake for example), we won't have to change our install steps.
=> Remove the need to install jake globally

pxteditor/editor.ts, pxtlib/browserutils.ts, webapp/src/cmds.ts
When hosted in a webkit view, sniff for the 'host' message handler
=> webkit host support [v0]

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/enum_shadow_blocks.blocks, tests/decompile-test/cases/enum_shadow_blocks.ts, tests/decompile-test/cases/testBlocks/enums.ts, tests/decompile-test/cases/testBlocks/pxt.json, tests/decompile-test/decompilerunner.ts
This fixes a ton of really specific bugs around enums and decompilation where enums were being decompiled into values (i.e. shadow blocks) when they should have been fields (i.e. dropdowns).
=> Fixing some decompiler edge cases around enums

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/projects.tsx
This removes main.blocks from project when type is `codeExample` and `example`. For 32 this is what we want, because blocks are just missing and conversion changes semantics. I think this is the usual scenario.
=> For TS only on "codeExample" cards

cli/cli.ts
This fixes this build error:
```
*** Build failed: target build failed: ENOENT: no such file or directory, open '/Users/michal/src/pxt-32/built/sim.d.ts'
```
The missing implementation checking doesn't seem very effective anyways, so I guess it's fine to do with a delay of one build.
=> Fixing first time build of sim-only targets

webapp/src/app.tsx
We use `#sandbox`  in the share page instead of `#pub`. I can't test this locally.
=> Preserve sandbox hash in embedded pages

pxtsim/embed.ts, webapp/src/simulator.ts
Hopefully this should fix the bug where the editor updates its appcache, reloads the page, and the simulator does not appear. I can't test the end-to-end scenario but I did verify that my reload message works as expected.
=> Handle app cache updates in the simulator

localtypings/pxtarget.d.ts, pxtcompiler/emitter/backjs.ts, pxtlib/package.ts, pxtsim/langsupport.ts, webapp/src/app.tsx, webapp/src/screenshot.ts
This adds `saveAsPNG` option in pxtarget. When enabled, the save button will ask the simulator for a screenshot and embed the project source code in the screenshot. Also adds loading.
Also, adds `pxsim.title` with the title of the project (it can be printed on the screenshot)
=> Support saving projects in PNG screenshots

pxtblocks/blocklyloader.ts
The "edges" of blockly labels come with an implicit space, so we can remove whitespace from either side of the labels that we add to blocks
=> Remove extra spaces from Blockly labels

pxtblocks/blocklyloader.ts, pxtcompiler/emitter/service.ts, pxtlib/blocks.ts, pxtlib/service.ts
- Port search improvements from stable2.4:
- Filtered (disabled and hidden) blocks are excluded from search
- Localized category names are now searched
- Fix search crash caused by `pxt.appTarget` being undefined inside workers
=> Port search improvements and fix search crash

docfiles/apptracking.html, docfiles/tracking.html
Var scriptIdRegex is not hoisted up and when the call to scrubURL function is invoked it sees scriptIdRegex being undefined and doesn't scrub the URL. 
It is ok to declare it as a local variable as all the browsers cache the regex parse tree. 
I will port to v0.
=> Fixes the leaky key in the telemetry URL

pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, tests/blocklycompiler-test/baselines/array_return_type.ts, tests/blocklycompiler-test/cases/array_return_type.blocks, tests/blocklycompiler-test/test-library/expandableBlocks.ts, tests/blocklycompiler-test/test.spec.ts
Type inference doesn't work at all right now because it always calculates the return type as `number[]`
=> Handle array return types in blocks

docs/defining-blocks.md, pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtcompiler/emitter/decompiler.ts, tests/blocklycompiler-test/baselines/to_string_arg.ts, tests/blocklycompiler-test/cases/to_string_arg.blocks, tests/blocklycompiler-test/test-library/pxt.json, tests/blocklycompiler-test/test-library/toStringArgs.ts, tests/blocklycompiler-test/test.spec.ts, tests/decompile-test/baselines/to_string_inputs.blocks, tests/decompile-test/cases/testBlocks/basic.ts, tests/decompile-test/cases/to_string_inputs.ts
Finally you can drag any block into `console.log()` and `serial.write()`!
=> Allow block parameters to be implicitly converted to strings

cli/cli.ts
Samples like turltle/blockchain fail as they require to download the package from github
=> ignore snippets in docs relying on github package

pxtlib/github.ts
When adding a package, only consider v**.**.** tags (fix for blocklytalkBLE who had some other tags)
=> Tags should be versions

libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts, tests/compile-test/lang-test0/241arrayforeach.ts, tests/compile-test/lang-test0/pxt.json
Note that both Array.Map and Array.forEach should leave a sparse array sparse, but they don't in our case.
=> adding array.foreach

webapp/src/app.tsx
I was copying and pasting a block in the blocks editor and it caused the entire app to freeze. I guess I had a PNG on my clipboard (not sure why copying a block didn't overwrite that) because it was hanging in the decode function. I don't know why it hung, but we shouldn't try to load PNG's in non-PNG supporting editors anyhow.
=> Only import PNG files if the target has saveAsPNG turned on

cli/buildengine.ts, cli/cli.ts, cli/gdb.ts, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtlib/cpp.ts, pxtlib/main.ts, pxtlib/package.ts
This adds `variants` map in `pxtarget.json` which can be used to override anything in the target definition. It's used to define a target variant for a different MCU - which redefines compile service, usage of UF2 vs HEX, GDB command, etc. The particular variant is then selected from `pxt.json`. It allows for variant-specific packages, eg `core---nrf52832` which masquerades as `core`. These still share code from common-packages, but can have different platform overrides. 
Not much code, but much flexibility.
This is initially for BLE Nano support in maker.
=> Add support for different MCUs in a single target

docs/defining-blocks.md, pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/service.ts, pxtlib/service.ts
This adds support for a new `//% blockCombine` attribute that can be specified on properties to generate enum-like setter and getter. See changes in docs for docs. This includes compiler and decompiler support.
It also fixes support for `//% block` without arguments and inference of `blockId` - IMHO we should remove `blockId` from the non-shipped APIs for simplicity.
=> Support for `//% blockCombine`

pxtlib/service.ts
With the new auto block logic, we try to generate blocks for namespaces, classes, interfaces.
=> Fix for #3988

cli/cli.ts
Was a simple order of operation bug. I ended up just removing uf2 caching, since it will never be needed in v0.
=> v0: Fix hex cache generation

cli/cli.ts
UF2 base images are still hexfiles, so we should be saving them with .hex extension in the offline cache. This fixes 2 issues:
- We were filtering offline cache on `\.hex$`, so .uf2 files were not put in the manifest
- We were going to put the .uf2 files in the manifest after filtering, which would never have been hit because the editor queries the base file as .hex
With this, 1st time uf2 offline compilation should now work
=> Fix offline cache for uf2 targets

docs/defining-blocks.md, pxtblocks/blocklyloader.ts, pxtlib/service.ts
When function instantiates an object, we most likely want to store it in a variable. the ``blockSetVariable`` does that automatically.
TODO: support a formatting in "block" to specify the name of the return variable so that it can be localized.
=> add ``blockSetVariable`` to auto-wrap factory into set variable

pxtlib/github.ts, webapp/src/db.ts
Caches pxt.config and /text lookups in memory and/or pouchdb.
* /refs is not cached
* repoes pointing to "master" are not stored offline as they might be changing.
=> Client-side github repo caching

pxtlib/github.ts, webapp/src/db.ts
Port of github caching to v0. Github package are caching in memory and in storage if applicable. Reduces the amount of data downloaded and ensures packages still work while offline. https://github.com/Microsoft/pxt-microbit/issues/706
=> Client-side github repo caching (#4013)

pxtrunner/runner.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, pxtsim/visuals/boardhost.ts, theme/light.less, theme/pxt.less, webapp/public/custom.css, webapp/public/run.html, webapp/src/app.tsx, webapp/src/projects.tsx, webapp/src/simulator.ts
- Disable transitions
- Pass light mode to simulator on initialization and through runoptions
- Disable loading and dimmer animations
- Remove blockly workspace and drag filters
- Remove simulator reveal and remove transitions
Still yet to come, dynamically enabling light mode when compile is slow.
=> Light mode optimizations.

pxtcompiler/emitter/decompiler.ts
Fixes https://github.com/Microsoft/pxt-32/issues/50
=> Fix for invalid decompilation of properties with blockCombine

theme/themes/pxt/globals/site.variables, webapp/src/app.tsx, webapp/src/editortoolbar.tsx
Expand tiny share view to a wider height range.
Don't allow collapse in sandbox mode as it conflicts with sim embed view.
=> Expand tiny share view

pxtblocks/fields/field_colour.ts
This is non-breaking, the default behavior is unchanged. I've added two extra modes to the color picker for returning strings and return indices instead of hex values.
=> Adding output modes to the field_colour

localtypings/pxtarget.d.ts, webapp/src/app.tsx
Just a flag to enable the sim debugger without ?dbg=1.
=> Add pxtarget option to display debugger by default

cli/cli.ts, cli/gitfs.ts
Add cli support to directly upload git refs to the cloud. 
CLI command recurses through all git references (commit, tree, blob) and checks the cloud for their status in chunks (50 per request). It then uploads to the cloud any missing hashes. 
Finally it calls the cloud to update the git refs config file.
=> cli: git uploadrefs

cli/cli.ts
This allows for easy handling of non-sheet images - just don't specify width/height anywhere
=> Allow for missing width/height in pxt buildsprites

localtypings/blockly.d.ts, pxtblocks/blocklyimporter.ts, pxtblocks/blocklylayout.ts
Don't use blockly ids when serializing xml.
=> Don't use blockly ids when serializing xml.

localtypings/blockly.d.ts, pxtblocks/blocklyimporter.ts, pxtblocks/blocklylayout.ts
In the interest of saving cloud space, and local space, we decided to strip out these ids as Blockly can generate them when loaded anyway. 
master pr: https://github.com/Microsoft/pxt/pull/4063
=> [v0] Don't use blockly ids when serializing xml.

webapp/src/core.ts
Previous PR: https://github.com/Microsoft/pxt/pull/4066 enabled optional icons for modal actions. Had to add a default for prompt and confirm dialog.
=> Fixing missing checkmark icons (in modal)

theme/themes/pxt/globals/site.variables, webapp/src/monaco.tsx
Fix monaco toolbox resizing text (line height). 
When zoomed in all the way in the monaco toolbox. 
Before: 
After: 
Also: 
- Clear highlight when passed null. 
- Use a better default toolbox color for blockly.
=> Fix monaco toolbox resizing text

webapp/src/monaco.tsx
Include both built in blocks and blocks in a namespace when populating the theme for all blocks.
=> Fix monaco editor function coloring for top level blocks

theme/highcontrast.less
Invert flyout button backgrounds in high contrast
=> Flyout buttons in High contrast

webapp/src/pxtjson.tsx, webapp/src/sui.tsx
Clear the project settings name input when returning to the editor or loading a different file.
=> Clear project name val when the editor file changes

pxtblocks/blocklyloader.ts
Remove the default variable in the Variables flyout. Always start with a simple "Make a variable" button. 
Users don't see the variable blocks until they create a variable..
Resolves https://github.com/Microsoft/pxt/issues/1539
=> No default variable (Flyout)

theme/serial.less, theme/themes/pxt/globals/site.variables, webapp/src/serial.tsx
Add text to the serial back button + some ui theming support.
=> Serial back button

cli/cli.ts, pxtlib/browserutils.ts, pxtlib/docsrender.ts, webapp/public/release.manifest, webapp/src/container.tsx, webapp/src/projects.tsx
Move target images out of target.json and over into the release manifest to reduce the size of target.json and allow us to make use of browser app cache for those images between releases. 
Works locally, need to test on the cloud.
=> Move target logos into app cache

webapp/src/projects.tsx
Remove funny characters when creating project from template.
=> escape new project name

webapp/src/app.tsx
Here are the screenshot before and after
Before: 
After:
Basically removes 3 reference to the board to just single one. Took cue from Edge about dialog
=> Simplify the about dialog

webapp/src/core.ts
https://github.com/Microsoft/pxt/commit/79579505b3f8ec17c2a7624e5179649dd488ee47#diff-d8cf7897d76809964c79553d02e3e75c broke the delete and reset buttons. 
Mostly we do something real silly and attach to "approve buttons" in the modal, which I didn't realise at the time as it didn't make sense to add the approve class to all buttons, but anyway here's the fix.
=> Fix delete and reset buttons

pxtlib/browserutils.ts, pxtlib/main.ts
Move image patching to the right place such that it gets saved appropriately. 
For targets (maker) that override the pxt.apptarget theme per board.
=> Move cdn image patching to the right place

localtypings/pxtarget.d.ts, pxtlib/cpp.ts, webapp/src/app.tsx
Allows to specify additional target ids to load hex files from older targets. Typically this is useful when switching between compatible targets with older ids.
=> allow loading scripts from other targets

pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/service.ts, pxtlib/service.ts, webapp/src/monaco.tsx
**pxtcompiler/emitter/decompiler.ts**
- Lookup for setter using qualified name that now includes property type (retType).
**pxtcompiler/emitter/service.ts**
- Fix check for readonly symbolinfo and include property declarations.
**pxtlib/service.ts**
- Support value of retType and not 'number'.
- To do this needed to expand the qualified name for the block to be
```typescript
const mkey = `${s.namespace}.${s.retType}` `
```
- Also added in a %blockCombineShadow attribute that will allow the set accessors to default to a shadow type, e.g. a color picker.
For example,
```typescript
//% blockNamespace=design
declare class Material {
//% blockCombine
//% blockCombineShadow=color_picker
//% group="Material"
//% shim=.color property
public color: Color;
//% blockCombine
//% …
```
=> Several changes and bug-fix to allow for combined property blocks that differ in return type.

theme/themes/pxt/elements/loader.overrides, webapp/public/docs.html, webapp/public/index.html, webapp/src/core.ts
We don't want to show the big pxt loader for all loader, only the main editor one. 
Everything else can use the spinning wheel, or maybe customize later.
=> Don't overuse pxt loader

common-docs/about/editor-features.md
This is in response to #1247 asking for an editor overview page. This is a base page which is overridden in the target, if desired, to add customized feature images and possibly additional sections.
=> Add an 'editor features' base page

localtypings/pxtarget.d.ts, pxtlib/docsrender.ts
In order to have a "friendly" name for a board or product when `@boardname@` is used for strict branding, I suggest something like `@nickname@`. This is declared in appTheme as `boardCommonName`.
=> Suggest a friendly name replacement macro

cli/buildengine.ts, cli/cli.ts, docs/simshim.md, pxtblocks/blocklyloader.ts, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts
* the `shim=@f4` annotation for images now uses column-major, little endian order, used by most screens, improving performance
* image encoding refactored and simplified
* the data in `BoxedBuffer` is now word-aligned for better performance
* add `pxt builddatdts` to force rebuild of dal.d.ts
This needs to be synchronized with a PR in common packages: https://github.com/Microsoft/pxt-common-packages/pull/288
=> swapping x/y in image format

webapp/src/blocks.tsx, webapp/src/monaco.tsx
Centre on block when a debugger breakpoint is hit.
Both for blocks and monaco. (Monaco only centers once you have enough lines to move the cursor to the middle, which makes sense)
=> Debugger 9001

cli/cli.ts
Automates the process of search, clone, building approved packages
```
$ pxt testghpkgs
Using target adafruit with build engine codal
target: v1.1.7 C:\gh\pxt-adafruit
pxt-core: v3.10.4 C:\gh\pxt
testing github packages
microsoft/pxt-gestures#v0.0.2
microsoft/pxt-neoanim#v0.4.1
found 2 packages
microsoft/pxt-neoanim
[run] git clone -q -b v0.4.1 https://github.com/microsoft/pxt-neoanim built\ghpkgs\microsoft\pxt-neoanim
Note: checking out '2b045dd3bd1c042802b5c6b2f88677a2b4b73dc9'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by …
```
=> "pxt testghpkgs"

pxtcompiler/emitter/hexfile.ts
Without this my asteroids crash (the one pixel start is mis-encoded)
=> Fix for encoding one-pixel images (possibly others)

docfiles/pxtweb/cookieCompliance.ts
There are two cases where AI can still be loaded without the cookie:
1. There is an error when trying to contact our backend to get the mscc payload
2. The editor is in sandbox mode
Otherwise, we will only load AI if cookie consent is given. This affects all pages; not just the editor. For docs you will either have to have already given consent (i.e. in the editor) or click a link since those are the only interactive elements on those pages.
=> Only load AI when cookie consent given

pxtsim/simlib.ts
We added a playAudioBuffer to the audio context but never added a stop for it, so calling the context.stop was only stopping any "tone" sounds playing and not any audio buffers. 
Fixing it.
=> Stop the audio buffer if one is running.

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/tagged_template_fixed_instance.blocks, tests/decompile-test/cases/tagged_template_fixed_instance.ts, tests/decompile-test/cases/testBlocks/templateStrings.ts, tests/decompile-test/decompilerunner.ts
Fixes a bug where the `Image` type could not be passed as a parameter to an API unless the thing being passed is declared as a fixed instance. This lets shim APIs declare that they can take indirect references to fixed instances as parameters.
=> Adding a decompiler flag for fixed instance parameters

libs/pxt-common/pxt-core.d.ts
Found by the translators. Tiny fix.
=> Fix JsDoc string for array.every() parm

webapp/src/projects.tsx
Display version in bottom of home screen. Too annoying to check the about dialog for that one.
=> display version in home screen

common-docs/blocks-embed.md, pxtsim/simdriver.ts, theme/debugger.less, webapp/src/blocks.tsx, webapp/src/debugger.tsx
=> Fix debugger move computation

pxtlib/browserutils.ts
This is another cross-version interaction with docs.js. pxt.BrowserUtils.loadScriptAsync does expand url. It should not expanded pre-expanded urls (isomorphic).
=> don't expand full script urls

pxtcompiler/emitter/backthumb.ts, pxtcompiler/emitter/emitter.ts
(and possibly a memory leak for '^')
The lists of operators were not the same - both had 4 operations, but one `|` the other `^`
=> Fix crash when applying '|' on float on Thumb

libs/pxt-common/pxt-core.d.ts
The 'A' was confusing the translators when reviewing the jsdoc string.
=> Change jsDoc desc for parseInt to lower 'a'

pxtlib/service.ts
Allowable `%blockCombineShadow` strings:-
'{name shadow},' or '{value shadow}' or ',{value shadow}' or '{name shadow},{value shadow}' 
e.g.
```
/**
* Active camera.
*/
//% blockCombine
//% blockCombineShadow=world_scene,camera_perspective
//% shim=.camera property
camera: Camera;
```
Fixes https://github.com/Microsoft/pxt/issues/4195.
=> Allow for optional shadowing of object instance of property get/set.

libs/pxt-common/pxt-core.d.ts, package.json, pxtsim/libgeneric.ts
Introduce various int math operators (idiv, imul, floor, ceil, etc...) for the micro:bit/v0. This will allow package writer to update their code so that it does not break when we switch to floating point arithmetic.
Requires shims in pxt-microbit https://github.com/Microsoft/pxt/pull/4208
=> Integer math operators [v0]

pxtblocks/blocklycompiler.ts, pxtblocks/blocklylayout.ts, pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/comments.blocks, tests/decompile-test/baselines/workspace_comments_exp.blocks, tests/decompile-test/baselines/workspace_comments_parent.blocks, tests/decompile-test/baselines/workspace_comments_typescript.blocks, tests/decompile-test/baselines/workspace_comments_var.blocks
Adds support for grouping workspace comments with event handlers. Any top level comment in Typescript will now be grouped with the nearest event upon decompilation/formatting. Comments are placed to the right of the event block and stacked vertically; I originally tried laying them out above the block but the right looks much more natural in practice. The formatting algorithm is pretty naïve so we could definitely improve upon it.
Likewise, the Blockly compiler now emits the comments above the nearest event handler in the blocks. The grouping from blocks -> TS is done with a heuristic based on distance and bounding boxes of comments and can probably also be improved but it handles the round-trip scenario pretty well.
Other nice fixes:
1. workspace comments no longer compile with too many …
=> Improved workspace comment compilation/decompilation

theme/pxtsemantic.less
We're too fast now that you see icons loading when you load the page as they're being read by the browser. Moving icons to the top of the semantic css file so that they load first.
=> Load icons first

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/core.ts, webapp/src/simulator.ts
React no has support for error boundaries: https://reactjs.org/docs/error-boundaries.html
This would mean that if an unhandled error occurs somewhere in the React components, we can display a message like so, and get users to reload the page, log the error etc. 
Alternatively, we can just reload the page for them but I feel like that's a little intrusive. 
thoughts?
=> Add an error guard around app

pxtblocks/blocklylayout.ts, pxtblocks/blocklyrenderer.ts, pxteditor/editor.ts, pxtrunner/runner.ts, pxtsim/embed.ts, theme/tutorial.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/dialogs.ts, webapp/src/editortoolbar.tsx, webapp/src/marked.tsx, webapp/src/projects.tsx, webapp/src/toolbox.tsx, webapp/src/tutorial.tsx
We used to load the tutorial page in an iframe of the doc pages and then split it up based on some predefined format and just displayed it in the relevant parts of the editor. 
This meant that we had to re-load all editor resources in the iframe (which were already loaded in the editor and could be re-used).
Marked was also already included in the package so I decided to make use of that and just render the blocks on an as needed bases (ie: when the user clicks on the hint). 
Instead, here's what I'm doing: 
- User starts the tutorial engine
- We download the markdown from /docs. We parse it and store it in the state
- We then look for any block / snippet tags used and concat them into one snippet that we decompile in order to find the toolbox blocks used. 
- Update the toolbox with the …
=> Fix tutorial perf

docfiles/docs.html, docfiles/style.css, theme/accessibility.less, theme/common.less, webapp/src/app.tsx
Note: this is a minor UI change for accessible users.
The semantic.css shared in pxt-deployment-config is used by docs.html in both v0 and master. 
A recent change to update that drop with a new semantic.css snap from master broke the accessibility menu in v0. 
Attempt to fix https://github.com/Microsoft/pxt/issues/2807
Porting over the new accessibility menu from master, so they can share the same structure and semantic.css
Here's what the old one looked like: 
Here's what the new one we're using in master looks like: 
and in docs: 
The styling and color used matches the MDN accessibility page.
=> Port over accessibility menu from master

webapp/src/sui.tsx
Support links and download / filename in modal buttons. 
Useful for targets that extend the download dialog.
=> Links, Filename and download in modals

webapp/src/gallery.ts
Automatically extract the description parameter in the example markdown and inject it as a workspace comment.
=> extract paragraph of comment into workspace

webapp/src/marked.tsx
In tutorials, don't escape inline blocks if setting text content.
Otherwise you end up with this: 
It's already been escaped by marked.
=> Don't escape inline blocks

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/workspace_comments_variable_statements.blocks, tests/decompile-test/cases/workspace_comments_variable_statements.ts
For some reason, the baseline in the test case was generated without the actual comment content. I expect this has something to do with the decompiler test runner so don't worry about it. I've tested the same code in the browser and it works fine.
=> Don't throw away comments on auto declarations in decompiler

webapp/src/tutorial.tsx
Tutorial unplugged mode fixes (fullscreen but skips to next step). 
use @unplugged to test
Hiding the modal does the equivalent of "Ok"
Added back button, shown on landscape view, hide text only icon on portrait (tablet), and not visible at all in mobile view.
=> Tutorial fixes

theme/blockly-core.less, theme/common.less, theme/highcontrast.less, theme/home.less, webapp/src/app.tsx, webapp/src/sui.tsx, webapp/src/toolbox.tsx, webapp/src/tutorial.tsx
- adding option to access hc directly with a flag ?hc=1
- Reverting Halo mode. 
- High contrast difference between simulator, toolbox, and then blocks / JS. 
- Always show the same theme across all editors regardless of light / dark theme. 
Adafruit:
Chibitronics:
Fixes https://github.com/Microsoft/pxt-adafruit/issues/667
Fixes https://github.com/Microsoft/pxt-adafruit/issues/645
Fixes https://github.com/Microsoft/pxt-adafruit/issues/608
Fixes https://github.com/Microsoft/pxt-adafruit/issues/602
=> High contrast fixes

webapp/src/toolbox.tsx
Issue was with how we were counting number of elements in the toolbox when we had subcategories. 
Fix accessibile toolbox navigation and refresh toolbox selection.
Fixes https://github.com/Microsoft/pxt-adafruit/issues/710
=> Fix accessibile navigation in toolbox

pxteditor/editor.ts, pxteditor/editorcontroller.ts, theme/tutorial.less, webapp/src/app.tsx, webapp/src/marked.tsx
Use blockly XML in the tutorial instead of images. Use innerHTML instead of InnerText so that IE doesn't escape new line characters in <code> blocks
=> Fix tutorials in IE

pxtlib/cpp.ts
If hex is not found in local cache, attempt to hit live endpoint. This PR accomplishes this by forcing live endpoint to get the CDN url, which is then used for /compile endpoint
=> live compile for app if online

webapp/src/blocks.tsx
mutated blocks show multiple blocks in the toolbox.
Support returning a number of blocks instead of one when calling getBlocksXML in the new toolbox.
mutated blocks is used by micro:bit for the radio blocks.
=> Support mutatedBlocks in toolbox properly

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/events_in_code_blocks.blocks, tests/decompile-test/cases/events_in_code_blocks.ts
Basically, we were not decompiling this code (note the code block):
```typescript
{
forever(() => {})
}
```
=> Decompile events in top-level code blocks

localtypings/pxtarget.d.ts, webapp/src/app.tsx
Following the semver semantic, if the editor detects a script with a major version greater than current, refuse to load.
This PR will go in v0 as well.
=> Thou shalt not load a script from an editor 1 major version above

pxtblocks/blocklycompiler.ts, pxtlib/service.ts
Support block authoring a custom handler key to use when comparing block event duplicates.
=> Support custom handler key

cli/cli.ts
To stop the tests from breaking on `.md` files that start with a number
=> Add snippet to package name

pxtcompiler/emitter/decompiler.ts
Fixes https://github.com/Microsoft/pxt/issues/4313.
=> Do not provide non-sensical symbol information for implicit 'this' parameter.

theme/common.less
More specific about CSS rule used for simulators.
=> be more specific about highlight macro (clashes with sni[ppets)

.vscode/launch.json, cli/cli.ts, cli/commandparser.ts, cli/nodeutil.ts, localtypings/pxtpackage.d.ts, pxtlib/browserutils.ts
A side effect of applying upgrades on load (which are needed to handle multiple editor versions loading from the same local storage store), is that we were upgrading bundled projects -- in Adafruit in particular.
This change assumes that a project loaded from the CLI has the current target version (if omitted) to avoid any kind of accidental rewrite.
(Also consistently use 4 spaces to write pxt.json)
=> Assign current target version to CLI-loaded project

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtblocks/fields/sprite/spriteFieldEditor.ts, pxtlib/package.ts
Updates to support full screen sprite editor sizes.
(small fix around initial screen size)
=> support for screensize specification

pxtlib/package.ts, webapp/src/app.tsx, webapp/src/package.ts
When loading a header, we use the target version information to decide whether upgrade rules are applied.
=> Header versioning fix

pxtlib/docsrender.ts
Adds vN to all links rendered by the markdown if it exists. We also add the vN prefix for all links in the docs sidemenu.
Reason for changes, if you start browsing on makecode.microbit.org/vN you want to stay browsing on that site, rather than switch to latest.
=> Add the version into all links in the docs if it exists.

webapp/src/blocksSnippets.ts
Show eq and less than block compare snippets in toolbox
We were showing the less than and greater than. 
Note: these are just defaults it was still possible to get to the eq but this makes more sense. 
Before: 
After:
=> Show equality comparitor in toolbox

Jakefile.js, pxtlib/commonutil.ts, pxtlib/docsrender.ts, pxtlib/util.ts
Trying to minimize the amount of code in utils in the backend. 
Split utils into two files (commonutils and utils). docsrender (backend) only depends on common utils.
Marked the methods the backend calls in directly. They're all in docsrenderer.ts
Tested on staging.
=> Cleanup backendutils

cli/server.ts, pxtrunner/renderer.ts
Two things: 
- Added CLI support to ignore /vN/docs for markdown files (as we don't have local versions)
- Doc cards are rendered on the client so if we're in a doc version, we'd have to detect it from the pathname and patch it in.
Tested for: 
http://localhost:3232/v1/projects
http://localhost:3232/v1/blocks/loops
=> Add doc version in doc cards

cli/server.ts
I was parsing them incorrectly. 
targetconfig paths are in the format: 
```
projects 
v1/projects
```
Note: this is just for local pxt serve
=> Parse local targetconfig versions properly

webapp/src/container.tsx
@pelikhan not sure why this was done for https://github.com/Microsoft/pxt/pull/3924
but some menuitems can be configured to be a "tutorial" link and thus should start the tutorial rather than show the side menu.
=> A tutorial menu item should open the tutorial.

.vscode/launch.json, cli/buildengine.ts, cli/cli.ts, cli/commandparser.ts, cli/nodeutil.ts, cli/pyconv.ts, pxtlib/package.ts
Background: applying upgrade rules to Adafruit bundled projects leads to stack overflow issues. Upgrade rules should not be applied to bundled packages.
In order to track down what goes on in the build, I've added a lot on every written file. This helps debugging when someone funny happens.
=> Do not inject targetversion when using "pxt build"

pxtlib/emitter/cloud.ts
Note: Do not merge until changes to the cloud have been integrated to prod.
Append targetconfig version when querying from backend.
=> Append target config version 

cli/cli.ts, cli/server.ts, pxtlib/emitter/cloud.ts, pxtlib/main.ts, tests/blocklycompiler-test/test.spec.ts, webapp/src/share.tsx
Sharing: 
Initially we added the version on the client side in share.tsx as per https://github.com/Microsoft/pxt/pull/4329 but that introduces issues for Simulator share where runUrl already contains the version path and adding it again introduces an issue with duplicate vN in the url. Instead let the cloud handle this. Adding a parameter in webConfig that returns the version path and if it exists we prepend it to the url. 
Markdown versions: 
Initially I added the vN path into the url for docs and handled it by the backend, but it turns out the backend already handles custom doc versions by the client passing it the targetVersion. Although we were initially passing the backend the version it passes us through webConfig (targetVersion), but I think we should instead pass in the client's …
=> More versioning fixes

cli/buildengine.ts, cli/cli.ts, localtypings/pxtarget.d.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxtcompiler/emitter/thumb.ts, pxtlib/cpp.ts, pxtlib/main.ts, pxtlib/util.ts
* don't flash sources on the device for `.hex` targets (there's no read-back there anyway)
* stop creating `dal.d.ts` except when `pxt builddaldts`
* some ARM peephole improvements
* fixes for size stats
=> microbit v1 support

pxtsim/embed.ts, webapp/src/app.tsx
The hosting iframe can send a "importfile" message (see ImportFileMessage interface) to inject a hex file into the editor.
=> support for importfile message [v0]

cli/cli.ts, localtypings/pxtarget.d.ts, pxtcompiler/emitter/emitter.ts
When running ``pxt build --compat``, the compiler will do additional changes that might have compatibility issues. The first one is detecting that a package is using /  which needs to be addressed for micro:bit
=> added div warning flag

pxtlib/package.ts
Only consider the major version when deciding if a script is too old to be loaded in the current target.
=> only compare major versions for checking minimum target version load

localtypings/pxtarget.d.ts, pxtblocks/fields/field_images.ts, theme/home.less, webapp/src/dialogs.tsx, webapp/src/projects.tsx
Option to add footer / copyright text at the bottom of the Home screen and About dialog.
=> Support for copyright text in the footer

webapp/src/app.tsx
In v0 we simply removed the call to `initSerial()`. In v1 we must adjust the conditions to return early.
Fixes https://github.com/Microsoft/pxt-microbit/issues/843
=> Fix crash during initialization in micro:bit V1 UWP app

pxtblocks/blocklylayout.ts, webapp/src/marked.tsx
We need to serialize the SVG before reusing it from cache in tutorials for Safari.
Fixes https://github.com/Microsoft/pxt-microbit/issues/842
=> Fix tutorial cache in Safari

pxtblocks/blocklyloader.ts
In Arcade, hit blocks surface under "scene" instead of "sprite"
=> when "blocknamespace" specified, force using namespace color

pxtrunner/renderer.ts
We don't need to patch the cards in the editor because that goes through a different path to rendering the docs (it already goes through the backend which is passed targetVersion and returns the versioned docs that way)
Partly fixes https://github.com/Microsoft/pxt-microbit/issues/841 for cards
=> Skip patching version in rendered cards when in editor

pxtrunner/renderer.ts
Fix in editor check for whether or not to append target version to card urls.
Previous PR https://github.com/Microsoft/pxt/pull/4420 didn't correctly check for inEditor.
=> Fix in editor check for card links (versioning)

docs/playground-runner.html
Since we don't host mp3 files properly in /docs. 
Avoid the problem for now.
=> Turn off playground sounds

docs/playground-runner.html
Turns out the flag is sounds not sound, this is also broken else but has no sideeffects, will on the next Blockly push.
It's sounds not sound.
=> Fix playground sound option

pxteditor/shell.ts
?readonly=1 when in controller mode puts the editor in readonly
Could be used for other features in the future.
=> Support readonly views in controller mode.

pxtlib/package.ts, webapp/src/app.tsx, webapp/src/package.ts
Integration of https://github.com/Microsoft/pxt/pull/4427 from v0.
=> better support for interecpting invalid versioned elements

webapp/src/dialogs.tsx
=> fix url encoding in about page

webapp/src/blocks.tsx, webapp/src/toolbox.tsx
When in an iframe and on Safari, 
we're seeing "iframe" or the iframe iD as the name in the flyout. 
This fixes that. 
Screenshot of issue:
=> Fix issue with Safari not showing the right flyout heading labels.

pxtlib/service.ts
Only for V0
Fixes https://github.com/Microsoft/pxt-adafruit/issues/743
=> Match parsing of escapes in master

pxtlib/browserutils.ts, pxtlib/main.ts
Whenever we assign a new apptarget (this happen once on load and every time we load a new board), we apply the patching logic.
Fixes lost images in maker extensions dialog.
=> patch apptarget when setting variants

cli/cli.ts, cli/hid.ts, cli/nodeutil.ts, cli/serial.ts, cli/server.ts, docs/cli/hidserial.md, package-lock.json, package.json
Most of our native dependencies are not needed for compilation or other tasks. They do create a ton of warnings or fail the installation -- or simply fails in OS like Windows 7 when precompiled images are not available.
=> Lazy load native dependencies

pxtcompiler/emitter/decompiler.ts
Seems like Blockly is picky about where the variables get declared.
=> Variables must be emitted at the top of a blocks file

cli/nodeutil.ts
This check is too strict -- just fail and ignore the dependency.
=> remove lazy dependency check

common-docs/offline.md
Start of a discussion on what to add for this:
* Reconnect is sometimes necessary when packages are added?
* The 'Native Apps' section, I ditched it. What about Windows 10 apps for certain targets? Have an override section to include a mention of those?
* Are there concerns now about app cache constraints?
* Serving locally, keep this section but make it more friendly?
=> Update the 'offline' page

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/scriptsearch.tsx
for multiboard scenarios. It reuses the Extensions dialog.
Currently boards are mixed with Extensions wich is confusing. Does not appear for editor that do not have multiple boards.
=> Add a "change board" dialog element

theme/blockly-core.less
Make selectors more specific so these rules win in Edge
Fixes https://github.com/Microsoft/pxt-minecraft/issues/594
=> Fix z index of grid picker tooltips on Edge

localtypings/pxtarget.d.ts, theme/home.less, webapp/src/dialogs.ts, webapp/src/projects.tsx
Cherry pick (kinda) the copyright text change to stable3.13 for Lego. 
I say kinda because dialogs have changed in master and I've had to somewhat reimplement it in this stable branch. Not a big change tho
=> Cherry pick copyright text change into stable3.13

pxtlib/browserutils.ts, pxtrunner/runner.ts
Minor fix to doc versioning, failing to add a slash when it's not there.
We should probably write some sort of path joining method and use that instead.
=> Minor fix to doc versioning

docs/static/playground/pxt-common/pxt-helpers.js, pxtlib/docsrender.ts, webapp/src/marked.tsx
Use the same renderer that we use for the docs in the tutorial marked engine. 
This also as a product solves the issue with not having centered images in the tutorial dialogs. 
Fixes https://github.com/Microsoft/pxt-minecraft/issues/582
=> Use the same renderer that we use for the docs in the tutorial marked engine

pxtlib/gallery.ts
The workspace comments don't support markdown rendering so we slurp random wikipedia syntax. Also, layout of code with comments is buggy.
=> no example comment

cli/cli.ts, docs/cli/build.md, docs/cli/serve.md, pxtlib/cpp.ts
This is a shift from favoring local native to cloud native build. The reason is that local builds often fail because of configuration issue. We do have a cloud which makes the experience much more seamless (and slower). New flag --local to force local build.
Better log output of failed builds.
Fixed some incorrect caching of promises.
=> pxt serve uses cloud by default

cli/cli.ts
This change allows a target build script to build a simulator sim.js outside of PXT. Why?
Well in my case I'm going a bit rogue and creating my own shim .d.ts files and going from there. Given my heavy use of npm packages etc. it just makes more sense to go this route so I can use whatever browser-ify toolchain I choose vs. the PXT route.
This build path does lose,
- PXT generated shim .d.ts files for the simulator.
- PXT generated sim-strings .json file for `lf()` based localization.
Other TSC project builds are still performed by PXT, e.g. cmds/, fieldeditors/, editor/, libs/ etc.
Changes are,
- Don't skip the already optional 'sim' build step if there is a sim/public/ even though no sim/tsconfig.json exists.
- In the simulator shim creation look for sim/tsconfig.tson else bail. This …
=> Support a /sim directory with no TSC but /sim/public content.

pxtblocks/blocklyloader.ts, pxtlib/toolbox.ts, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/toolbox.tsx
Match TS behaviour by not converting namespace to lowercase in the toolbox.
Fixes https://github.com/Microsoft/pxt-adafruit/issues/782
Fixes https://github.com/Microsoft/pxt-microbit/issues/879
When I re-did the toolbox, I made the assumption that TS merged all namespace names regardless of case, but that's not true. This change allows two categories with different cases to appear in different toolbox categories (just like TS).
=> Toolbox namespace casing

cli/cli.ts, localtypings/pxtpackage.d.ts, webapp/src/codecard.tsx, webapp/src/projects.tsx
Support for project tags in home screen, like so: 
- Supports multiple tags
- You can choose a color associated with the tag label (it must be one of the semantic colors). 
Example of the authoring: 
```
"tags": [{ "label": "Beginner" }],
```
```
"tags": [{ "label": "Beginner", "color": "blue" }],
```
```
"tags": [{ "label": "Beginner", "color": "blue" }, { "label": "Fun", "color": "green" }],
```
Note: tags don't appear in the docs, just in the home screen.
=> Support project tags in home screen.

webapp/src/dialogs.tsx
Fix about dialog double encoding html
We don't need html escape if we're using react jsx
=> Fix about dialog

docfiles/style.css, theme/docs.less, theme/print.less, theme/pxt.less, webapp/src/app.tsx
Support multi-page print in the editor as well as the docs. Moving print CSS to semantic.css
Checked in at the same time as https://github.com/Microsoft/pxt-deployment-config/pull/61
=> Fix print feature: multi-page print

webapp/src/toolboxeditor.tsx
Noticed I missed this when I did the namespace casing PR: https://github.com/Microsoft/pxt/pull/4505
=> Don't lowercase namespace when searching for blocks

docs/static/playground/samples/all.js, docs/static/playground/samples/basic/variable-names/sample.js, pxtcompiler/emitter/decompiler.ts, pxtlib/blocks.ts, pxtlib/service.ts, tests/blocklycompiler-test/commentparsing.spec.ts
We never really had a good way to set the default name for the variable shadow blocks that show up in the toolbox. This adds a little bit of syntax for doing so:
```TypeScript
//% block="%argument=variables_get(someName)"
function whatever(argument: number) {
}
```
That parentheses trick also works for "this" arguments so now we can change a default value without breaking the block definition. Previously we used whatever was in the block string to name the input in the Blockly XML so changing it was a breaking change.
For `blockCombine` blocks you can set the name using the `blockSetVariable` attribute.
This is not a breaking change.
=> Variable name defaults in block definition

localtypings/pxtpackage.d.ts, pxteditor/editor.ts, pxtlib/main.ts, webapp/src/app.tsx, webapp/src/codecard.tsx, webapp/src/projects.tsx
This adds a dialog when the user presses the "Download" button. The dialog currently appears one per session - we might want to store the setting and add some way of changing this.
The save button still saves a PNG.
=> Choose hardware dialog

pxtlib/docsrender.ts
We had a closure variable capturing bug in our logic to render docs links
On [line 461](https://github.com/Microsoft/pxt/blob/master/pxtlib/docsrender.ts#L461) we initialize the `link()` function in a way that captures the state of the `d` object and keeps it forever. Subsequent calls to the `link` function do **not** use the updated `d` object that we set on [line 446](https://github.com/Microsoft/pxt/blob/master/pxtlib/docsrender.ts#L446), but rather the one from the function's closure
Fix is to re-assign the `renderer.link()` function every time, so it always uses the updated `d` object (and the updated `d.versionPath` value to correctly update the `href`s).
=> Fix docs link rendering

localtypings/pxtarget.d.ts, pxtcompiler/emitter/driver.ts, pxtcompiler/emitter/service.ts, pxtlib/service.ts, webapp/src/compiler.ts, webapp/src/monaco.tsx, webapp/src/monacoSnippets.ts
This is a (long overdue) feature for targets that lets them exclude certain categories from appearing in blocks. For example, we recently were adding blocks for some image APIs and that accidentally caused them to appear in the EV3 editor where we didn't want them. Now you can just add "image" to this list instead of doing the complicated "file override dance" that we usually do.
This PR also fixes an unrelated bug where typing any string into the search bar in JavaScript that matched certain blocks in the Math namespace would cause the entire webpage to disappear (I kid you not).
Note: banned categories will not only be removed from the toolbox but their blocks will cease to be loaded by BlocklyLoader, so adding a name to the list in a target is a breaking change
=> Let targets remove categories from blocks

pxtcompiler/emitter/service.ts
You can't compare enums to numbers in blocks because Blockly only lets you compare two blocks with matching "checks" on their outputs. We just assign the return type of a function to the check so functions that return enum values have their check set to "WhateverEnumIsNamed" instead of "Number" which is what you usually want.
=> Treat enums as numbers in blocks

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/enum_user_defined_with_var.blocks, tests/decompile-test/cases/enum_user_defined_with_var.ts
Some TS statements will only be decompiled if they are top-level (like enum declarations). This fixes a bug where the decompiler would treat any statements after a variable declaration list as not-top-level.
That bug might sound bad but it only really affected enums because events and function declarations are special-cased by the decompiler.
=> Handle top level blocks after a variable declaration list

cli/cli.ts
When running "pxt buildsprites", generate meta.json if missing.
=> generate meta.json if missing

pxtlib/util.ts
For some reason in v0 we hardcode live localizations to true, even if pxtarget.json disables them. This prevents package authors from testing their package translations.
This change has no impact on production websites, because we never use the `disableLiveTranslations` flag in pxtarget.json. That setting is mostly meant for local serve.
Note that in master, this has already been fixed
=> Honor the disableLiveTranslations pxtarget setting

cli/cli.ts
For some reason `staticpkg` removes the link from the partner logo
=> Don't remove the logo URL

cli/cli.ts, pxtlib/browserutils.ts
For Maker builds takes minutes (native build of all boards) - `pxt rebundle` now just quickly rebuilds `target.json` based on files in `libs/*`
This also fixes the problem where `pxt buildtarget` would generate `target.json` where images don't work on localhost.
=> Add 'pxt rebundle' for quickly rebuilding target.json
