microsoft/pxt

pxtblocks/blocklycompiler.ts
=> Fix for issue 183: extractNumber doesn't parse negative numbers

pxtblocks/blocklyloader.ts
PR Fixes Microsoft/pxt-microbit#132
=> Fixes (pxt-microbit) issue 132: For loop does not have associated help

pxtlib/github.ts, webapp/src/app.tsx
=> Enable ability to open project through a url (issue 124)

webapp/src/app.tsx
=> Fixes issue when clicking main.blocks when main.ts has errors results in data loss without warning

webapp/src/ace.tsx, webapp/src/app.tsx, webapp/src/core.ts
=> when TS->Blocks conversation fails, suggest remove blocks file

webapp/src/app.tsx
=> Deleting project pops up the Add package dialog instead of the Open project dialog

pxtblocks/blocklycompiler.ts
Fixes #291. @pelikhan mind taking a look?
=> Fixing assertion error when compiling "not" blocks

pxtlib/emitter/decompiler.ts
Fixes #283 
References to variables with object types, like those used by the "game" blocks, generate declarations that initialize the variables to `null`. Because we emit nothing for `null`, assignments to `null` decompile to invalid assignment blocks that recompile down to invalid typescript (type annotations are removed and you get a "no implicit any" error).
This change reports an error when trying to decompile statements that assign `null` to a variable unless they are variable declarations in the global scope (e.g. like the ones the compiler generates).
=> Do not emit null initializers

webapp/src/app.tsx
Trivial fix to the error message dialog.
=> Incorrect error message when incompatible package is added

pxtlib/browserutils.ts
Resolves https://github.com/Microsoft/pxt/issues/342
=> Force browser version

webapp/src/blocks.tsx
=> Remove the option to disable blocks

cli/cli.ts, cli/server.ts, localtypings/pxtarget.d.ts, pxtlib/cpp.ts, pxtlib/github.ts, pxtlib/main.ts, pxtrunner/runner.ts, webapp/src/app.tsx, webapp/src/fileworkspace.ts, webapp/src/package.ts, webapp/src/pxtjson.tsx, webapp/src/workspace.ts
- store target version in .hex and .pxt files
- travis upload va.b if tag is va.b.c
=> Storing version number in generate files

pxtlib/emitter/decompiler.ts, pxtlib/emitter/emitter.ts, tests/decompile-test/baselines/functions_outputs_as_statements.blocks, tests/decompile-test/functions_outputs_as_statements.ts
=> Properly handle call expressions with return types used as statements

webapp/src/app.tsx
To test: 
http://localhost:3232/index.html#project:XQAAgAD6CQAAAAAAAAA9goAXHC4MqgeNHgoIMpsTCTurzyZquKQOb1TCv3qwnSSNmLVmmhapbG3CLd9v/08vze9hGTbDvJuezBtxMPKVl6ei4La9oRmzGt8Mcqu0D0ZWAwKz0KsiEnUUKpcvC0egU+pyasVnD4mu25erlB4lXSBN7CpRJB7UEID70DSvOlb9S4H+ltYvoiJVC5tt0WNCh4PrX1pd6AxrSyJSYY1WgNR2XAQ+Xq7EpJHnpmA+94UZm+bwRDbP40CEgP7pzpJui19PcQThnSDF6lWGjf24fegIEMj9jYxxUC9th5mYloxwar+kmWX+XmUcIcZdzXH7uw115gX9hmjp8QE+7Rm5Bkq54nfLhvC+XnN9hJ8gLfjPWgaZzy9lWFMj8h5JJAaD19FEGRPjPevdUvuPCdni7ka3SidRLI2WilDLZ9x0kjaBYIlDA0kwD9UK/t46dg4ceVPyVQgWoOhT9CEQ9KLITWvfC8Qj0XlZTT4NeR1/udHZTap+889HuwmOnSw2DAG0Otg2ReG69uIp9N2UWf4HX33wV+/JI+XQu6O5va+92TUp/9ww9ssofeYv+k9zeznGx3cZMCIZCelTKiXkYh2Nnga88RB0Xw3605taPyYgeh1z+dCQO+TDw/DMjbTdWEyPJ0isKHrz1z3Q6DSgtRAqKo+8SmY5E0b9vs/FTMM5r0wi7utTUVtpAIRKYZOApIOJ8+A6sVgYPiiaUQ6rc4tgxovYa …
=> sharing: through a project url (encoding file contents in url)

pxtlib/docsrender.ts, webapp/src/app.tsx
sharing: by default allow file encoded sharing for screenshots and editor. if publishing is enabled, allow cloud sharing.
=> sharing: file encoded uri sharing by default, cloud sharing if publishing is enabled

webapp/public/custom.css
=> styling the blockly toolbox

Jakefile.js, README.md
Just a small quality of life improvement. Let's you serve without switching to pxt-microbit
=> Adding jake serve

webapp/public/index.html
=> avoid self-closing elements in html. fix for #473

pxtblocks/blocklyloader.ts
=> use parentNode instead of parentElement when manipulating XML dom.

webapp/src/app.tsx, webapp/src/monaco.tsx
=> adding global edit / typescript edit ticks

localtypings/pxtarget.d.ts, pxtlib/main.ts, webapp/src/app.tsx, webapp/src/compiler.ts
=> Reopen shared projects in the editor they were written in / preferred editor

pxtblocks/blocklyloader.ts
=> Create shadow blocks for APIs with boolean parameters

webapp/public/custom.css
=> Fixing subcategory styling on small screens

Jakefile.js, cli/cli.ts, pxtlib/crowdin.ts, pxtlib/emitter/util.ts
- add command to CLI to upload file to crowdin project
- automatically upload strings.json from travis build on master
=> Automated strings upload to crowdin

pxtlib/cpp.ts
Supports uint16_t and other aliases in C++.
=> support for generating numeric types in shims.d.ts

cli/cli.ts, pxtlib/crowdin.ts
Goes through the files in crowdin and update bundle packages.
=> Adding option to download loc files for target

webapp/public/custom.css, webapp/src/app.tsx
Updates the "open in..." button in sandbox to the flat style.
=> fixing "open in" button

webapp/src/app.tsx
- adding space between logo and project name
- project name available in sandbox mode as well
=> navigation menu updates

pxtsim/libgeneric.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/186
=> Fixing string ref count issues with fromCharCode & substr

pxtsim/runtime.ts
=> Fixing reference counting of event handlers in the simulator runtime

Jakefile.js, cli/cli.ts, cli/server.ts
@microsoftsam would you mind adding the OSX locations for Firefox and Safari?
=> Adding flag to pxt serve to pick a browser

docs/about.md, docs/docs.md, docs/translate.md, pxtlib/emitter/util.ts, pxtrunner/runner.ts, webapp/src/app.tsx
See https://github.com/Microsoft/pxt/issues/589
=> support for loading live translations from strings.json

cli/cli.ts, webapp/public/release.manifest
This is untested, as it requires a merge + upload to test.
=> Added strings and hex files to app manifest

docfiles/docs.js, docfiles/head.html, pxtrunner/runner.ts
Fixes https://github.com/Microsoft/pxt/issues/584
=> support for rel-0 for youtube videos

cli/cli.ts, cli/nodeutil.ts
Allow to extract all .hex files within a folder.
=> pxt extract support folder of .hex files

cli/cli.ts
Added "pxt logout" to clear token.
=> adding logout command

pxtblocks/blocklyloader.ts
=> Fix localization of boolean shadow blocks

pxtblocks/blocklyloader.ts
Fixes https://github.com/Microsoft/pxt/issues/601
=> Fixing duplicate More category caused by over-zealous localization

pxtblocks/blocklyloader.ts, pxtlib/blocks.ts, webapp/src/compiler.ts
Localized block description may  accedientally break the block functionality. This change enforces that the localized string has the same structure as the original.
=> Validate blocks translations

Jakefile.js, cli/cli.ts, docs/translate.md, pxtlib/blocks.ts, pxtlib/crowdin.ts, pxtlib/emitter/util.ts, pxtlib/main.ts, webapp/src/compiler.ts
- Uploading package docs when pushing changes to master
- Extending live mode to package locs
- More checking and validation for block locs
=> Live package docs

webapp/src/blocks.tsx
=> Fixes issue in deselecting the help card when clicking on a category

theme/themes/pxt/globals/site.overrides, theme/themes/pxt/globals/site.variables, webapp/public/custom.css
=> Center and color the toolbox trash icon.

localtypings/pxtarget.d.ts, pxtrunner/runner.ts, webapp/src/app.tsx
- Do not load 'getting-started' on startup
- Load docs iframe lazily
=> Lazy sidedocs

localtypings/pxtarget.d.ts, pxteditor/monaco.ts
=> Adding support for using the dark theme in monaco.

cli/cli.ts, cli/nodeutil.ts, pxtlib/crowdin.ts
Updated target docs upload command to upload /docs folder as well.
=> support for uploading docs in crowin

cli/cli.ts, cli/uploader.ts, docfiles/appmeta.html, docfiles/meta.html, localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, webapp/public/index.html, webapp/src/app.tsx
- expand applogo and cardlogo from disk in pxtarget.json
=> expand applogo / cardlogo with blob locations

cli/server.ts, docfiles/appmeta.html
Avoid double escape title and description while expanding HTML.
=> Meta title and descrption

webapp/src/app.tsx
buttons tend to popup on a touch screen
=> don't use css tooltip on mobile buttons

cli/cli.ts
=> support for running gendocs from target

theme/themes/pxt/collections/menu.overrides, webapp/public/custom.css
- Sets the fixed menubar size on the .menu item 
- Leaves a little more room down the bottom for the organization logo, so it appears vertically centered
=> Menu bar margin fixes

theme/pxt.less
=> Fix for scrolling past end of code moves the simulator

pxtlib/cpp.ts
=> Fix hex null crash

localtypings/pxtarget.d.ts, pxtlib/github.ts, webapp/src/app.tsx, webapp/src/data.ts
Loads a package filtering policity from targetconfig.json via the config API in the cloud:
https://www.pxt.io/api/config/microbvit/targetconfig.json
then applies filtering policy to github search results: approved orgs and approved repos are allow.
=> Filter packages

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/github.ts, pxtlib/main.ts, webapp/src/app.tsx, webapp/src/data.ts, webapp/src/package.ts
- allow to specify banned orgs/repos
- when loading approved repo, use proxy to avoid github throttling
- surface repo to UI to allow special handling (like warning message)
=> banned github repo

webapp/src/app.tsx
Simple fix to address https://github.com/Microsoft/pxt/issues/675
=> Open project dialog shows github packages

localtypings/pxtpackage.d.ts, package.json, pxtlib/main.ts
Add "targetVersion" to pxt.json
=> Pxt targetVersion

package.json
=> specifiying dependencies on node/npm

pxtlib/github.ts
- drop banned repos
- filter on search
=> always proxy github repos

pxtsim/state/filesystem.ts
Allows to simulator file system operations.
=> state for filesystem

theme/pxt.less
=> Fix for sidebar bottom scroll margin, and not scrolling in Safari.

webapp/src/blocks.tsx
=> Fix for Poping up sidedocs does not resize editor. 

cli/cli.ts, pxtlib/github.ts, pxtlib/main.ts, webapp/src/workspace.ts
When download github package, compare against current approved / dissaproved list of partners
=> validate download github packages

webapp/src/monaco.tsx
Simple fix to address https://github.com/Microsoft/pxt/issues/711
=> Back to Code button appears in all the files

webapp/src/app.tsx, webapp/src/pxtjson.tsx
Moving "delete project" from project settings to nav menu.
=> move delete project to nav menu

cli/cli.ts, webapp/src/app.tsx
=> filter out template projects out of bundled

localtypings/pxtarget.d.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/simulator.ts
Was made for maker.js, not a scenario anymore.
=> Clean out onCompile message

localtypings/pxtpackage.d.ts, webapp/src/app.tsx
when a student reloads a project, the activity details should be reloaded so that he can continue the activity
=> retain the project/doc url in project

pxtlib/emitter/service.ts
Enum members were not captured in the loc files.
=> properly capture enum members block and jsdoc

pxt-cli/cli.js
the check should possibly be done elsewhere as to many checks create a problem with maintenance
=> out of date node version check

cli/cli.ts
When downloading translations for target, auto patch pxt.json
=> auto-update on translations

webapp/src/app.tsx
Add tile in "Open Project" dialog instead of menu item under hamburger.
=> move "new project" tile under "open project"

cli/server.ts
Compiler server.js from cmds/server.ts than load in target.
=> load server.js from built folder

cli/cli.ts, package.json
Store password in a secure way on the client
=> store passwords using keytar

cli/server.ts, pxtlib/emitter/cloud.ts
Makes the sidedoc load from localhost if possible
=> loading sidedocs markdown from localhost if possible

localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts, theme/pxt.less, theme/themes/pxt/globals/site.variables, webapp/public/custom.css, webapp/src/app.tsx
- Wide / Portrait organization logos (useful for using different logos for dark menu theme vs light footer)
- Getting started button theming
- Re-organizing main layout and organisation css into less
- Using less variables for grid breakpoints.
=> Wide / Portrait organization logo support, getting started button theming, extra theming support

pxtblocks/blocklyloader.ts
Populates boolean parameter with true/false drop down
=> shadow values for boolean values, fix for #838

pxtblocks/blocklycompiler.ts
Fixes #847 
Sorts the top-level blocks before emitting so that blocks with callbacks are emitted before any blocking code.
=> Event handlers in blocks should be emitted first

localtypings/pxtpackage.d.ts, pxtblocks/blocklyloader.ts, pxtrunner/codecardrenderer.ts, pxtrunner/renderer.ts, webapp/src/codecard.tsx
- fix ordering of namespaces / elements in reference
- support for function name only on code cards (namespace is overkill)
=> Rendered docs tweaks

docfiles/docs.html, theme/pxt.less, theme/themes/pxt/globals/site.variables, webapp/public/docs.html
Adding docsPageFont and docsHeaderFont to set a different font for the docs page and sidedocs.
=> Support for different docs font then main page font.

cli/cli.ts, pxtlib/emitter/decompiler.ts, pxtlib/emitter/driver.ts, tests/decompile-test/baselines/functions_optional_parameters.blocks, tests/decompile-test/errors/optional_parameters.ts, tests/decompile-test/functions_optional_parameters.ts, tests/decompile-test/testBlocks/basic.ts
=> Error out in decompiler when using optional parameters

theme/pxt.less, webapp/public/custom.css, webapp/src/app.tsx
=> Fix simulator missing scrollbar issue on Edge / IE

pxtlib/cpp.ts
The cache maybe have corrupted elements (file got corrupted, etc...). Always check that parsing is successful.
=> validate that cache entries are valid JSON

.vscode/launch.json, localtypings/pxtarget.d.ts, pxtlib/main.ts
New upgrade rule that scans "main.ts" for APIs whose package is missing: radio, game, bluetooth, etc...
=> Missing package upgrade

theme/pxt.less, theme/themes/pxt/globals/site.variables
Fix for https://github.com/Microsoft/pxt/issues/894
=> using LESS variable for "tall" breakpoint

webapp/src/app.tsx
The "loading" dialog was not hidden properly
=> fixing incorrect call to hideLoading

webapp/src/app.tsx
To match code.org button terminology
=> renamed button start -> run

localtypings/pxtarget.d.ts, webapp/src/app.tsx
Allows a target to automatically stop the simulator when a change is detected.
=> Stop on change

cli/server.ts, pxteditor/workspace.ts, pxtlib/main.ts, pxtsim/embed.ts, webapp/src/app.tsx, webapp/src/fileworkspace.ts, webapp/src/screenshot.ts, webapp/src/workspace.ts
Support for storing screenshots provided by simulator in localhost
=> Screenshot

webapp/public/custom.css
=> Fix for context menu blockly scroll issue. 

theme/pxt.less, webapp/src/monaco.tsx
=> Toolbox sort

cli/cli.ts, localtypings/vscode-debug-protocol.d.ts, pxtlib/emitter/driver.ts, pxtlib/emitter/emitter.ts, pxtrunner/debugRunner.ts, pxtrunner/runner.ts, pxtsim/debugProtocol.ts, pxtsim/debugger.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, pxtsim/utils.ts, webapp/public/run.html, webapp/src/compiler.ts
This PR updates the debug protocol that the simulator uses to something a bit more usable. This is still very much a work in progress.
=> Updating debugprotocol for simulator

webapp/src/app.tsx, webapp/src/package.ts
=> immediately save changes when removing/adding dependency

cli/cli.ts, cli/server.ts, pxtlib/main.ts, webapp/src/app.tsx, webapp/src/electron.ts, webapp/src/hwdbg.ts
=> Can now specify websocket server port when doing pxt serve

pxtblocks/blocklyloader.ts
Format Code applies a "Flow" layout
=> adding "format code" in blocks

webapp/src/toolbox.ts
=> removing if elseif elseif else case

electron/src/webview/index.ts
=> Help URLs now open in the default browser

webapp/src/monaco.tsx
=> Format code before checking for changes

webapp/src/blocks.tsx
=> Telemetry PR

theme/pxt.less, theme/themes/pxt/collections/menu.overrides, webapp/src/app.tsx
=> Make the block / javascript menu items look like a toggle.

pxtblocks/blocklyloader.ts
=> Execute search when the search box is clicked or touched

pxtblocks/blocklyloader.ts, pxtlib/emitter/util.ts, theme/pxt.less, webapp/public/custom.css, webapp/src/monaco.tsx, webapp/src/toolbox.ts
Block icons are applied for an entire namespace, rather than individual blocks.
=> Namespace icons

pxtblocks/blocklyloader.ts, theme/pxt.less
hiding toolbox labels in mobile, bigger icon
adding icon for search in toolbox
=> Hiding toolbox labels in mobile

pxtlib/emitter/service.ts
Better relevance in search results.
=> Searchscore

pxtblocks/blocklycompiler.ts
Fixing conversion problem in blockly.
Fixes #963
=> Fixes to the blockly compiler

docs/writing-docs.md, pxteditor/workspace.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, theme/pxt.less, webapp/src/app.tsx, webapp/src/cloudworkspace.ts, webapp/src/fileworkspace.ts
- support for inline button rendering
- support for temporary projects
- replace gearwheel with ... in Advanced section
- don't render blocks buttons in tutorial
=> Doc updates for tutorials

Jakefile.js, THIRD-PARTY-NOTICES.txt, package.json, pxtlib/emitter/service.ts, typings.json, webapp/src/worker.ts
Fixes #1013
@pelikhan could you please check the searching algo, see if you're happy with the weightings
=> Use fuse.js for block search

pxtlib/main.ts, pxtsim/instructions.ts, pxtsim/runtime.ts, pxtsim/svg.ts
=> Headphone image not correctly displayed in IE11 

pxtlib/emitter/emitter.ts
=> EmptyStatement not supported

pxtlib/emitter/decompiler.ts
Fix for https://github.com/Microsoft/pxt/issues/1073
=> ensure that image has correct amount of dot when reloading.

pxtsim/simlib.ts
=> Fix for music jack image in firefox

webapp/src/cmds.ts
=> Respect the forcehexDownload flag

cli/cli.ts
Support for "pxt bump --upload"
Running tests before upload target manually
=> add "upload" option to "bump"

pxtblocks/blocklyloader.ts, pxtsim/simdriver.ts, theme/pxt.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/simulator.ts
1. Anchoring download button on the editor toolbox 
2. Adding restart simulator button 
3. Only showing simulator toolbar on hover 
4. Transition animation when hiding the simulator 
5. Simulator collapse in the same spot
Fixes #1064
=> New UI Changes

cli/hid.ts
Don't crash when node-hid fails to load.
=> better handling on missing "node-hid"

theme/pxt.less, webapp/src/app.tsx, webapp/src/simulator.ts
=> Simulator Fullscreen Mode

webapp/src/app.tsx, webapp/src/monaco.tsx, webapp/src/pxtjson.tsx, webapp/src/srceditor.tsx
Changing rename to project settings in "More" dropdown menu 
- adding save button in settings
- adding delete button in settings
- disabling auto save
=> Project settings

localtypings/blockly.d.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/srceditor.tsx
=> Undo / Redo buttons grey out if the undo / redo stack is empty.

webapp/src/app.tsx
=> removing project loaded notification

webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/srceditor.tsx
Only load the monaco editor when pxt is trying to open the file
Before (Memory usage): 
After (Memory usage):
Fixes #242
=> Lazy load the monaco editor

webapp/src/core.ts
Remove modal element from DOM.
=> fix memory leak in modal dialogs

cli/cli.ts, localtypings/pxtarget.d.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/core.ts
Dramatic simplification of the upload dialog.
- current design brings a lot of information and user have been confused by the accordion layout
- memory overhead of loading images
New design is just much simpler.
=> Simplified upload dialog

pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/defaultInstance.blocks, tests/decompile-test/defaultInstance.ts, tests/decompile-test/testBlocks/basic.ts
Not sure if this should go to master or develop.
=> Fix index error when counting default instance args

pxtblocks/blocklycompiler.ts
Not sure how to repro the crash, so I haven't tested this fix
=> Fix crash reported by app insights

pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/functions_optional_parameters.blocks, tests/decompile-test/errors/optional_parameters.ts, tests/decompile-test/functions_optional_parameters.ts, tests/decompile-test/testBlocks/basic.ts
Fixing decompilation for OO apis.
=> Fix decompilation of optional arguments in OO

cli/cli.ts
Gives the `pxt init` command a flag to prevent it from prompting for input. Only affects the CLI
=> Adding usedefaults tag for init command

theme/pxtsemantic.less, theme/style.less
Reduced from 
1,278,007 bytes (1.3 MB)
to 
1,012,816 bytes (1 MB)
=> Optimisation: Reduce the semantic ui footprint by removing unused components.

tests/decompile-test/baselines/images.blocks, tests/decompile-test/errors/image_too_large.ts, tests/decompile-test/images.ts, tests/decompile-test/testBlocks/mb.ts, tests/decompile-test/testBlocks/pxt.json
Fixes https://github.com/Microsoft/pxt/issues/1073
Or rather, adds test cases for the existing fix.
=> Image literal test cases

webapp/src/app.tsx
Fixes https://github.com/Microsoft/pxt/issues/1190
=> Don't load sample projects in IE11

pxtblocks/blocklyloader.ts
Rely on "blockHidden" instead.
=> Do not use TD_ID to decide to hide block from toolbox

pxtlib/browserutils.ts, theme/pxt.less, webapp/src/app.tsx
=> Don't hover simulator when on a touch enabled device.

pxtblocks/blocklycompiler.ts
Fixes #1227
All that is actually necessary to fix the bug is the extra call to `removePlaceholders()` but I've taken the liberty of removing the hack altogether.
=> Remove placeholders when compiling single blocks

webapp/src/app.tsx
=> Added polyfill for Uint8Array.slice()

pxtlib/browserutils.ts
URL flags to force various download strategies for mobile testing.
=> Download flags

pxtblocks/blocklyloader.ts
=> Cache search blocks and increase search debounce time

Jakefile.js, cli/cli.ts, pxtlib/main.ts, webapp/src/app.tsx
Fixes #441
Fixes #905
Fixes #1119
Fixes #1159
Fixes #1232
Fixes #1236
=> Don't auto add packages if they cause conflicts; Prompt for conflicts BEFORE adding a package

Jakefile.js
Will investigate and re-enable
=> Disable tests that make travis build crash

Jakefile.js, cli/cli.ts, pxtlib/main.ts, webapp/src/app.tsx
Changes were merged to develop; now merging to master
=> Merge package conflict changes to master

pxtblocks/blocklyloader.ts
=> Fix for Custom trash icon not appearing on touch devices. 

webapp/src/app.tsx
=> Change string to clarify there is no undo

theme/pxt.less
=> Make simtoolbar always visible.

cli/cli.ts, docfiles/appmeta.html, docfiles/head.html, theme/pxt.less, webapp/public/custom.css, webapp/public/index.html
=> Cross Plat and Mobile UI fixes

pxtrunner/debugRunner.ts, pxtsim/debugger.ts
Like the title says. Poll the websocket periodically to make sure its still up and attempt to reconnect to the server if it is not.
=> Try to reconnect after lost connection in pxt runner

THIRD-PARTY-NOTICES.txt, cli/cli.ts, package.json
recursively deletes 'built' folders
=> adding clean command

pxtlib/emitter/util.ts, webapp/src/app.d.ts, webapp/src/app.tsx, webapp/src/monaco.tsx, webapp/src/package.ts, webapp/src/share.tsx, webapp/src/srceditor.tsx
(no ready)
Moving IProjectView and related to definition files, splitting app.tsx in pieces.
=> App cleanup

THIRD-PARTY-NOTICES.txt, cli/cli.ts
refreshes THIRD-PARTY-NOTICES automatically
=> added pxt thirdpartynotices command

webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/filelist.tsx, webapp/src/scriptsearch.tsx
Moving FileList, ScriptSearch, DocsMenu and SideDocs out.
=> More app refactor

webapp/src/share.tsx, webapp/src/sui.tsx
Simplify dialog, still needs skinning.
=> hiding advanced sharing options

docfiles/abuse.html, docfiles/script.html
Simplified script landing page (still needs skinning)
=> Scriptpage

localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts, theme/pxt.less, webapp/src/app.d.ts, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/editortoolbar.tsx, webapp/src/monaco.tsx, webapp/src/scriptsearch.tsx
hide the menu bar under a flag 
don't show the add package button when packages are not supported
=> Hide the menu bar using a flag

webapp/src/app.d.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx
Force editor into readonly mode in iframe mode.
=> Readonlyiframe

pxteditor/localStorage.ts, pxteditor/shell.ts, webapp/src/app.d.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/container.tsx, webapp/src/editortoolbar.tsx, webapp/src/monaco.tsx, webapp/src/scriptsearch.tsx, webapp/src/workspace.ts
Bail out to in-memory storage when unavailable
Disable local storage in standbox mode
=> Shared storage

pxtsim/embed.ts, pxtsim/utils.ts, webapp/src/app.tsx
=> added polyfill for UInt8Array.fill

pxteditor/localStorage.ts, pxteditor/shell.ts, webapp/src/app.tsx
Users can block all 3rd party cookies and storage
=> handle blocked local storage by CSP policies

theme/pxt.less, webapp/public/index.html, webapp/src/app.tsx, webapp/src/core.ts, webapp/src/editortoolbar.tsx
- fix position of cookie message
- add space for legal bar
=> Embed view fixes

pxtblocks/blocklyloader.ts, webapp/src/monaco.tsx
Fix for drag issues in monaco toolbox
=> Monaco drag

localtypings/pxtarget.d.ts, webapp/src/share.tsx, webapp/src/sui.tsx
=> UI rework of sharing dialog

localtypings/pxtarget.d.ts, webapp/src/app.tsx, webapp/src/gallery.ts, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx, webapp/src/share.tsx, webapp/src/sui.tsx
Structure revision of the projects tab. Minimal changes, more work required to completely polish the experience.
- support for "examples" tab.
=> Refactoring projects dialog

webapp/src/toolbox.ts
=> moving lists under advanced

pxtlib/emitter/emitter.ts
Simple fix to the issue https://github.com/Microsoft/pxt/issues/951
=> Conditional operator was not saving the temporary value

pxtsim/simdriver.ts, webapp/src/app.tsx
support for electron ipcrenderer-style messaging
=> Iframe proxy

pxteditor/editorcontroller.ts, webapp/public/controller.html
new message "newproject" to remote create project
=> added new project message

webapp/src/app.tsx
Fixing blocks import from microbit.co.uk
=> fixing blocks import

webapp/src/app.tsx, webapp/src/monaco.tsx
when opening script/project from TD, open JavaScript editor first to load monaco
=> fix TD import

package.json
@riknoll please test fix went through fine
=> Updating version of the monaco typescript language service

webapp/public/custom.css, webapp/src/sui.tsx
Added semantic ui react code attribution (MIT)
Also remove close icon text.
=> semantic-ui-react attribution

webapp/src/scriptsearch.tsx, webapp/src/sui.tsx
=> Adding a package freezes the editor

theme/pxt.less, webapp/public/custom.css, webapp/src/projects.tsx
=> Remove header in projects dialog

theme/pxt.less, webapp/public/custom.css, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/projects.tsx
=> Fix: Getting started overrides previous project 

pxteditor/monaco.ts, webapp/src/monaco.tsx
Fixes #1388 
This shouldn't be merged until https://github.com/Microsoft/pxt-monaco-typescript/pull/4 gets merged.
=> Display fixed instance shim APIs in monaco toolbox

THIRD-PARTY-NOTICES.txt, package.json
'request' needs to be a full dependency.
https://github.com/Microsoft/pxt/commit/2a98acdda04e455454bebcf8c90983a253ac4fa2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R86
=> moving request as main dependency

webapp/src/app.tsx
Close fullscreen on escape key
Fixes #1126
=> Close fullscreen on escape key

pxtblocks/blocklyloader.ts, pxtlib/blocks.ts, pxtlib/emitter/service.ts
=> delay load blocks help resources to take language into account

pxtlib/emitter/util.ts
=> restore lang iso code normalization

localtypings/pxtarget.d.ts, webapp/src/app.tsx
Simple flag to remove the blocks / javascript toggle (for blocks only workspaces). 
To test: 
in pxtarget set ``appTheme.blocksOnly`` to ``true``
=> Blocks only workspace

pxteditor/shell.ts
=> reanable sandbox mode

webapp/src/app.tsx
Don't show cookie dialog in Electron hosted app.
=> Electron cookie

webapp/src/share.tsx, webapp/src/sui.tsx
Add share option to get embedded editor.
=> Share Editor

webapp/src/app.tsx
Added #newjavascript route that creates a new project and opens it in javascript mode.
=> Newjavascript

webapp/src/projects.tsx, webapp/src/sui.tsx
Removed Create new title.
Disabling blurring on low end devices.
Fixes #1449
=> Projects dialog fixes

pxtlib/browserutils.ts, webapp/src/cmds.ts
For iOS client, do not open download dialog
=> don't pop up dialog when using custom protocol

pxtblocks/blocklyloader.ts
=> Fix blockly checks for array types

webapp/src/projects.tsx, webapp/src/scriptsearch.tsx, webapp/src/share.tsx
Removing blurring from projects, share, and scriptsearch modal dialog.
Fixes #1461
=> Removing blurring

webapp/src/blocks.tsx, webapp/src/monaco.tsx
Fixes #1459 
Wasn't using the same loc key to compare the Add package button click.
=> Add package localization button fix. 

webapp/src/app.tsx
=> Clear side docs when creating a new project

pxtlib/emitter/decompiler.ts
=> Fixing type error in decompiler

webapp/src/projects.tsx, webapp/src/scriptsearch.tsx, webapp/src/share.tsx, webapp/src/sui.tsx
Fixes #1491 
P1 bug in release
Was calling setPosition on component mount. Not doing that anymore and instead am leaving the state controlled by the component, and passing in the open props.
=> Fixing infinite setState error in projects dialog new project button

cli/cli.ts, cli/commandparser.ts, cli/nodeutil.ts, cli/server.ts, docs/cli.md, docs/cli/staticpkg.md, pxtlib/emitter/cloud.ts
Adds ``pxt staticpkg`` which packages the PXT web site into a flat list of HTML files.
=> Static web

cli/cli.ts, docs/cli/staticpkg.md
=> Staticpkg output option

cli/cli.ts
* adding cherry command
* comment
=> Cherry pick cli command (#1515)

webapp/src/blocks.tsx
Fix: loss of workspace data when switching between toolbox category
Fixes #1480
=> Step 7 of getting started guide clears workspace

localtypings/pxtarget.d.ts, pxtlib/cpp.ts
Allows to define target specific C++ defines.
=> support for specifying target sepific yotta parameters

theme/pxt.less
=> Apply faded colour to disabled blocks. 

webapp/src/sui.tsx
=> Fix no scroll issue in projects dialog on IE. 

docfiles/style.css, pxtblocks/blocklylayout.ts, webapp/public/docs.html
=> Fix font size in screenshot. 

pxtsim/simdriver.ts
=> Collapse simulator when no frames exists. 

webapp/src/app.tsx
* make org clickable to org url
* analytics + popout
=> Make the organization logo clickable, opens org url (#1585)

cli/cli.ts, cli/nodeutil.ts
Makes ``pxt update`` and ``pxt bump`` aware of ``pxt-common-packages`` dependency.
=> support for auto-bumping pxt-common-packages

cli/cli.ts, pxtlib/semver.ts
require that major version update are done manually
=> avoid automatic major bump

package.json, pxteditor/editorcontroller.ts, tests/host.html
Adding pxteditor.d.ts to nom package. 
Adding noresponse flag for ignoring ack response in sim messages.
=> Controller fixes

webapp/public/custom.css, webapp/src/monaco.tsx
=> Stop monaco editor from being pushed down by the toolbox

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/crowdin.ts, webapp/src/app.tsx
Support for uploading/downloading strings from a Crowdin branch. Specified in pxtarget.json. The branch names should follow the major version, e.g. ``v0``.
=> Crowdin branch

pxtlib/emitter/cloud.ts
Adds ``?targetVersion=...`` in ``/api/md`` requests
=> add target version when requesting markdown in side docs

Jakefile.js, cli/cli.ts, docfiles/docs.html, docfiles/header.html, docfiles/macros.html, docfiles/style.css, docfiles/toc.html, docfiles/tocheader.html, localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, theme/pxt.less, theme/pxtsemantic.less
Table of contents is authored in SUMMARY.md file under docs, like so:
```md
* [Projects](/projects.md)
* [Games]()
* [Flashing Heart](/projects/flashing-heart.md)
* [Smiley Buttons](/projects/smiley-buttons.md)
* [Love Meter](/projects/love-meter.md)
* [Rock Paper Scissors](/projects/rock-paper-scissors.md)
* [Magic Button Trick](/projects/magic-button-trick.md)
* [Music]()
* [Hack your headphones](/projects/hack-your-headphones.md)
* [Banana Keyboard](/projects/banana-keyboard.md)
* [Guitar](/projects/guitar.md)
* [Fashion]()
* [Duct Tape Wallet](/projects/wallet.md)
* [Watch](/projects/watch.md)
* [Toys]()
* [Inchworm](/projects/inchworm.md)
* [More]()
* [Timing Gates](/projects/timing-gates.md)
* [Compass](/projects/compass.md)
* [Telegraph](/projects/telegraph.md)
* …
```
=> New docs UI with Table of Contents

webapp/src/sui.tsx
=> Fix unspecified error in ie11 on new projects dialog

cli/cli.ts
Upload docs to travis when building a tagged release of target or v\d+ builds.
=> Travis upload of docs

localtypings/pxtarget.d.ts, pxtblocks/blocklyimporter.ts
Fix for https://github.com/Microsoft/pxt/issues/1646
=> support for patching block value names

cli/cli.ts, cli/commandparser.ts, common-docs/javascript/variables.md, docs/cli.md, docs/docs.md, docs/simshim.md
Fixing checkdocs and snippets CLI commands
=> Checkdocsfix

theme/pxt.less
Fix css issue with hidemenubar in mobile view
=> Hide menubar fix in mobile

pxteditor/editorcontroller.ts, pxteditor/workspace.ts, webapp/public/controller.html, webapp/src/app.tsx, webapp/src/iframeworkspace.ts, webapp/src/memoryworkspace.ts, webapp/src/workspace.ts
In-memory script storage with hosting window sync via iframe messages.
=> support for workspace synchronized with hosting window

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/pxtjson.tsx
=> Switch to previous editor after save in Settings dialog

pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/dont_rename_non_variables.blocks, tests/decompile-test/dont_rename_non_variables.ts
=> Don't rename any variables except declared ones

webapp/src/app.tsx, webapp/src/sui.tsx
Fixes #1616 
Making sure all menu items have a title, 
and all buttons have aria labels.
=> Accessibility fixes.

cli/cli.ts, common-docs/blocks/custom.md, common-docs/packages.md, webapp/src/scriptsearch.tsx
Allow shared project urls to be added as dependent packages .
=> Add package with shared project url

docfiles/toc.html, docfiles/tocheader.html
=> Support search on search icon click in TOC.

cli/cli.ts
When running ``pxt init`` make sure README.md content is properly written.
=> fix generation of readme.md in pxt init

pxtblocks/blocklymutators.ts, pxtlib/emitter/emitter.ts
Only appears when the callback has arguments.
=> Add optional prefix to destructuring mutator

docfiles/script.html, pxtlib/docsrender.ts, pxtrunner/renderer.ts, webapp/src/container.tsx, webapp/src/tutorial.tsx
add allow-forms in the sandbox field to allow searching in docs using the form
Fixes #1692
=> sandbox allow-forms

docfiles/docs.html, docfiles/footer.html, docfiles/header.html, docfiles/macros.html, docfiles/style.css, docfiles/toc.html, docfiles/tocheader.html, pxtrunner/renderer.ts, theme/pxt.less
- hide chrome
- larger margins
- constant font size
- print url
(there are still issues but this is a good increment)
=> Print support for docs

pxtlib/browserutils.ts
No version available when the web site is pinned.
=> ignore version number for safari pinned web sites

pxtsim/logs.ts, pxtsim/runtime.ts
Fix for https://github.com/Microsoft/pxt/issues/1737
=> flush serial data into a log entry when too long

cli/cli.ts
Fixing the logic to auto-commit a bump
=> fixing bumping

pxtlib/main.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, webapp/src/app.tsx
Display "edit" button in rendered doc snippets.
=> Edit button in docs

pxtrunner/renderer.ts, theme/common.less
More compact rendering of inline buttons / blocks
=> smaller buttons for inline blocks

pxtlib/docsrender.ts
Automatically mine the first image in a doc page for the twitter card
=> mine first image as image for twitter card

cli/cli.ts, docs/cli/deploy.md
=> launch serial after 'pxt deploy'

pxtlib/docsrender.ts
Mine first image or youtube movie to extract image used in twitter card
=> updated regex to extract twitter card

pxtlib/browserutils.ts, pxtlib/cmds.ts, pxtlib/emitter/driver.ts, webapp/src/app.tsx, webapp/src/cmds.ts
Fix for the iOS download experience to handle the case where the user presses cancel...
=> Download user context window

docfiles/appmeta.html, docfiles/meta.html, localtypings/pxtarget.d.ts, pxtlib/docsrender.ts
Inject iOS meta information to display app callout
=> App store meta

pxtblocks/blocklyloader.ts
=> Search advanced blocks even when collapsed

pxtblocks/blocklylayout.ts, pxtrunner/renderer.ts
Fix for  https://github.com/Microsoft/pxt/issues/1750
=> "download screenshot" hd

cli/cli.ts, common-docs/packages.md, pxtlib/github.ts, theme/common.less, webapp/src/codecard.tsx, webapp/src/scriptsearch.tsx
Support for displaying icons for packages
=> Package icon

cli/cli.ts, cli/server.ts, common-docs/packages.md, docfiles/package.html, localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, pxtlib/github.ts
=> Rendering of GH packages on website

webapp/src/core.ts, webapp/src/projects.tsx, webapp/src/simulator.ts
Support for specifying tutorial URL in projects.md
=> Hashtutorial

cli/server.ts, pxtlib/docsrender.ts
Automatically add a reference to the current package when rendering package docs
=> Package docs

theme/tutorial.less
=> Fix download area in editor toolbar in tutorial mode, fixes #1846

pxteditor/workspace.ts, webapp/src/app.tsx
@pelikhan I've added the filters to the project Header?
saves us from piping filters all around the place. Do you think that's a good idea?
=> filters to workspace sync responses

Jakefile.js, package.json, webapp/src/monaco.tsx
Fix issue in monaco editor error surfacing, fixes #1724. 
New version of the language service that fixes intellisense, fixes #1511
pxt-monaco-typescript 2.1.6
=> Monaco lang fixes

pxtblocks/blocklyloader.ts
=> Fix variables category in tutorials

cli/cli.ts, package.json, pxtlib/emitter/util.ts, theme/common.less, webapp/public/index.html, webapp/src/app.tsx
@pelikhan need to do some sort of server re-write to the semantic.css to switch it over to rtlsemantic.css when using an rtl language.
=> Better rtl support using rtlcss

pxteditor/editor.ts, theme/tutorial.less, webapp/src/app.tsx, webapp/src/projects.tsx, webapp/src/tutorial.tsx
=> Show options to keep coding, return to previous project or explore more tutorials

pxtblocks/blocklyrenderer.ts, pxtlib/emitter/util.ts, webapp/public/index.html, webapp/public/release.manifest, webapp/src/app.tsx, webapp/src/blocks.tsx
Change the ``href`` on semantic.css to the rtlsemantic.css file
=> hot swap to rtl css on demand

docs/blog/one-chip-to-flash-them-all.md
and note other boards are upcoming.
=> Add link to Feather M0 Express

pxtlib/emitter/decompiler.ts, tests/decompile-test/baselines/allblocks.blocks, tests/decompile-test/baselines/block_for.blocks, tests/decompile-test/baselines/block_repeat.blocks
=> Compile repeat correctly 

localtypings/pxtarget.d.ts, pxtlib/emitter/cloud.ts, webapp/src/share.tsx, webapp/src/workspace.ts
=> using shortid when sharing

localtypings/pxtarget.d.ts, pxtlib/emitter/util.ts, pxtlib/main.ts, pxtrunner/runner.ts, webapp/src/app.tsx
Allows specifying crowdin branches for pxt / target files.
=> use branch information in pxttarget

pxtlib/browserutils.ts, pxtlib/cpp.ts, webapp/public/index.html
Load lzma on demand.
Don't load editor.main.css eagerly
=> lazy loading lzma

cli/cli.ts, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtlib/main.ts, pxtrunner/runner.ts, webapp/src/app.tsx
For UI, use crowdinBranch info from PXT instead of target info.
=> Use crowdin branch info from pxt

webapp/src/app.tsx
=> Explicitly save the project name when saving a file.. 

pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts, pxtlib/browserutils.ts, webapp/src/screenshot.ts
Images reference by URL must be loaded and inlined as data uris.
=> support for rendering referenced images

pxtcompiler/emitter/backjs.ts, pxtsim/runtime.ts, theme/common.less, webapp/src/app.tsx, webapp/src/editortoolbar.tsx, webapp/src/simulator.ts
Also slows the execution speed and only pauses for user code (i.e. code in main or `main.ts`)
=> Execution trace ui

cli/cli.ts, pxtlib/emitter/cloud.ts, webapp/src/app.tsx, webapp/src/projects.tsx
=> added disclaimer on import url page

theme/common.less, theme/pxt.less, theme/sidedoc.less, theme/themes/pxt/globals/site.variables, webapp/src/app.tsx, webapp/src/container.tsx
New side docs supporting all views: 
On Hover, the icon changes to show that you can pull it out.
Popout:
=> New side docs, supporting all views.

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/monaco.tsx
=> Fix sidedocs JS / blocks load logic (on load). 

theme/common.less
=> Fix avatar image in side doc not showing.

pxtblocks/blocklylayout.ts, pxtblocks/blocklyrenderer.ts, pxteditor/editor.ts, pxteditor/editorcontroller.ts, pxtrunner/runner.ts, webapp/public/controller.html, webapp/src/app.tsx, webapp/src/compiler.ts
Support for 'renderblocks' message sent to editor.
=> Renderblocks msg

webapp/src/container.tsx
Fix for https://github.com/Microsoft/pxt/issues/1916
=> Handle deep link in docs menu

localtypings/pxtarget.d.ts, pxtlib/browserutils.ts, webapp/src/app.tsx
Properly redirect editor when browser version is not supported.
=> fixing browser check

webapp/src/container.tsx
Only hide the side docs in light / mobile mode on first load.
=> Hide side docs only on first load

pxteditor/editorcontroller.ts, webapp/src/app.tsx
Transfer ticks upstream to editor container.
=> Container ticks

pxtcompiler/emitter/service.ts, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/tdlegacy.ts
=> Fix td import. 

localtypings/pxtarget.d.ts, pxteditor/editor.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, pxtsim/visuals/boardhost.ts, webapp/src/app.tsx, webapp/src/simulator.ts
Communicated to simulator who can also handle it.
=> Support for "High contrast" mode in editor

webapp/src/app.tsx, webapp/src/core.ts, webapp/src/projects.tsx
=> prompt user before saving

webapp/src/tutorial.tsx
=> Tutorial modal scrolling issues.

svgicons/turtle.svg, webapp/src/app.tsx, webapp/src/editortoolbar.tsx
=> Using custom snail icon instead of the bug for execution trace.

pxtblocks/blocklycompiler.ts
=> Fix source interval mapping for blocks with multiple handlers

pxtlib/util.ts, webapp/src/app.tsx
Removing dead code and associated strings
=> removing project adjectives

pxtlib/browserutils.ts
=> allow search bots to load web site

cli/cli.ts, webapp/src/app.tsx, webapp/src/lang.tsx
=> Now clears language in the URL hash when selecting a new language in the UI

localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts
=> Support disabling block icons

cli/cli.ts, cli/pyconv.ts
When installing python3 on windows, the "py" command is registered.
=> run "py" on windows

localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts, webapp/src/monaco.tsx, webapp/src/monacoSnippets.ts
Support ability for targets to alter built in namespace colors in pxtarget.
=> Customize built in colors in target

pxtblocks/blocklyloader.ts
=> Remove the use of :scope selector

cli/cli.ts
=> Disable C++ when building docs

pxtsim/state/neopixel.ts
@pelikhan any idea why this stuff was here? it is just wrong
=> Clean up some random type casting

libs/pxt-common/pxt-core.d.ts
Accidental breaking change introduced in the array changes
=> Changing string names back

localtypings/pxtpackage.d.ts, pxtblocks/codecardrenderer.ts, webapp/src/codecard.tsx, webapp/src/projects.tsx
Allow to attach youtube id to a code card to pretify the display of projects.
=> Youtubepreview

docfiles/docs.js
This fixes the docs loading issue.
=> Setup field editors in docs

localtypings/pxtarget.d.ts, webapp/src/app.tsx
=> Add beta tag if target has a beta URL.

pxtblocks/blocklycompiler.ts
Found a bug as soon as I did a release :smile:
=> Prevent infinite recursion in array type checking

pxteditor/editor.ts, pxtrunner/runner.ts, pxtsim/embed.ts, theme/tutorial.less, webapp/src/app.tsx, webapp/src/tutorial.tsx
Support fullscreen mode in certain steps. 
Next / Prev button hidden in lightbox
Better line height for text in tutorial hint
=> Better getting started experience

pxtcompiler/emitter/emitter.ts
=> Emit breakpoints for loop conditionals

localtypings/blockly.d.ts, localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts, pxtlib/service.ts, theme/tutorial.less, webapp/src/editortoolbar.tsx
Support for undeletable blocks through annotations: 
//% undeletable=true
Additionally: Added onStartUnDeletable: true in the runtime to set the undeletable state of onstart.
=> Support undetectable blocks

cli/hid.ts, cli/server.ts, pxtlib/hf2.ts, pxtlib/webusb.ts, webapp/src/hidbridge.ts
We used to reset the device on hiddmesg, now we can just disconnect the HID
=> Add disconnect method to HID IO interface and use it in 'pxt hiddmesg'

webapp/src/blocks.tsx
Fix for Blockly confirm callback having a switched response. 
Fixes #2003
=> Blockly confirm callback fix

cli/cli.ts
Because building it always is a bad idea.
=> Don't build common sim, just copy the files

webapp/src/blocks.tsx
Fixing a dumb mistake on my part.
=> Fix minor mistake in scroll blocks pr

webapp/src/blocks.tsx
=> Scroll the workspace to the top leftmost block on first load (#2202)

cli/cli.ts
Fixes `pxt buildtarget` and `pxt serve`.
=> Build common sim in case of a local clean

webapp/src/app.tsx, webapp/src/appcache.ts
Just getting a build before merging.
=> Cherry pick "Preserve embedded pages across reloads (#2210)" into v0

pxtrunner/runner.ts, webapp/src/app.tsx
Hide the sidedocs when we choose to popout the content into a new tab.
=> Hide the sidedocs when we popout

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/always_enums5.blocks, tests/decompile-test/baselines/enum_assignment.blocks, tests/decompile-test/cases/always_enums5.ts, tests/decompile-test/cases/enum_assignment.ts
Fixes #2241 
We were being too permissive in our checking of enums.
=> Fixes to enum decompilation and parenthesized function arguments

cli/cli.ts, common-docs/javascript/call.md
Support for additional file path in docs testing
=> Checkdocscommon

webapp/src/monaco.tsx
=> Fix not including the namespace for methods injected into builtin categories

cli/hid.ts
Fixing hid serial on mac for detecting the micro:bit. 
Fixes #2259
=> Fix HID serial on mac

pxtcompiler/emitter/emitter.ts
=> support for hex formatter enumval litterals

localtypings/pxtarget.d.ts, webapp/src/data.ts, webapp/src/lang.tsx, webapp/src/scriptsearch.tsx
* load prefered repo list from targetconfig
* moving lang picker to use data for access target config
* updated cache policy
=> Load partner repos from target config (#2285)

common-docs/blocks/variables/assign.md, common-docs/blocks/variables/change.md, common-docs/blocks/variables/var.md
Expand some of the text and add examples.
=> Update the 'variable' topics.

pxtlib/docsrender.ts, pxtrunner/renderer.ts, webapp/public/docs.html
Also removes rendering on the server which did not seem to work anyway.
=> Run highlight js on the client + nice typescript rendering.

localtypings/pxtarget.d.ts, pxteditor/editor.ts, theme/common.less, webapp/src/app.tsx, webapp/src/notification.tsx
=> Add support for target notifications

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/notification.tsx
Moving out the state modifications from the render loop.
=> do not mutate state in render loop

pxtblocks/blocklyloader.ts, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/monacoSnippets.ts, webapp/src/toolbox.ts
Unfortunately you need to provide definitions for both because we aren't that unified in how we generate the toolboxes. Currently we don't have a localization story... @pelikhan any ideas?
=> Allow targets to override the toolbox

common-docs/blocks/math.md
Assuming _Math.PI_ gets included soon. Suggest maybe adding something like this to the **Math** namespace:
```   
namespace Math {
/**
* Approximation of PI.
*/
export const PI = 3.1415926535897932384626433832795;
/**
* Convert degrees to radians.
* @param degrees The number degrees to convert to radians.
*/
export function rad(degrees: number): number {
        return degrees * PI / 180;
}
 
/**
* Convert radians to degrees.
* @param radians The number radians to convert to degrees.
*/
export function deg(radians: number): number {
        return radians * 180 / PI;
}
}
```
=> Expand math topic with trig updates.

common-docs/reference/math/random-range.md, common-docs/reference/math/random.md, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts, package.json, pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtcompiler/emitter/decompiler.ts, pxtlib/blocks.ts, pxtsim/libgeneric.ts, pxtsim/runtime.ts, tests/blocklycompiler-test/baselines/math_library.ts, tests/blocklycompiler-test/cases/math_library.blocks, tests/decompile-test/cases/testBlocks/core.ts, webapp/src/toolbox.ts
=> Moving to JavaScript random

pxtblocks/blocklyloader.ts
=> Fixes #2352

pxteditor/editor.ts, webapp/src/monaco.tsx, webapp/src/monacoSnippets.ts
- Support functions category in extending the monaco toolbox.
- Support appending blocks instead of replacing them. 
- Support removing categories.
=> More flexibility in extending the toolbox

pxtlib/cmds.ts, webapp/src/app.tsx, webapp/src/cmds.ts
Exposing a new `commands.saveOnlyAsync()` function, which will be needed for winrt
=> "Save only" now works properly

docs/blog/microbit/v0.12.35.md
Feel free to reject this pull request and/or correct the error through other means if desired.
=> Correct minor spelling error

pxtblocks/blocklyloader.ts
Fixes #2398 
This is a regression we had at some point.
=> Fix blockly checks for array inputs and return types

pxteditor/editor.ts, pxteditor/editorcontroller.ts, webapp/public/controller.html, webapp/src/app.tsx
Surface toggle trace event to the controller. 
- optional intervalSpeed parameter to alter execution trace speed.
=> Surface toggle trace event to the controller

docfiles/macros.html, pxtlib/docsrender.ts
Just waiting for the build to go through
=> Cherry picking toc fix to v0

webapp/src/scriptsearch.tsx
Needed for eventual UWP app testing
=> Added a secret way to navigate to /beta

pxtwinrt/hiddeploy.ts, webapp/src/app.tsx
Fixes https://github.com/Microsoft/pxt-adafruit/issues/239
=> Better message when no HID device found

localtypings/pxtarget.d.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/driver.ts, webapp/src/compiler.ts, webapp/src/simulator.ts
Cherry picking #2448 and #2449
=> Cherry pick into fresh coat

docfiles/editorcards.html, docfiles/footer.html, docs/index.html
Passing all Keros tests. (With the exception of the Youtube player stuff)
=> Make the makecode.com website accessible

pxtlib/emitter/cloud.ts, webapp/src/app.tsx, webapp/src/share.tsx, webapp/src/sui.tsx
Displays an appropriate error
Fixes https://github.com/Microsoft/pxt-adafruit/issues/243
=> Handle sharing when offline

docfiles/tracking.html
Adding telemetry for windows app detection.
=> detecting windows app

pxtblocks/blocklylayout.ts, pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/data.ts, webapp/src/projects.tsx
- Fixes https://github.com/Microsoft/pxt-adafruit/issues/242
- Fixes https://github.com/Microsoft/pxt-adafruit/issues/241
- Also adds a temporary fix for https://github.com/Microsoft/pxt-adafruit/issues/233
=> Error handling for offline tutorials and getting started

common-docs/blocks.md, common-docs/blocks/math.md
Change of API from random to randomRange in docs
=> RandomRange API change

common-docs/blocks/loops.md, pxtrunner/renderer.ts
* add 'ForOfStatement' to renderer.ts
* add card for the 'for of' statement.
=> Add rendering of the 'for of' statement.

pxtsim/libgeneric.ts
=> Fix array pop logic

pxtsim/accessibility.ts, pxtsim/svg.ts, webapp/src/app.tsx, webapp/src/editortoolbar.tsx
- Added a set of helpers usable in the simulator to make it accessible.
- Fixed a few details that were considered as failures by Keros.
This PR is linked to another one : [https://github.com/Microsoft/pxt-microbit/pull/463](https://github.com/Microsoft/pxt-microbit/pull/463)
=> [Accessibility] Set of changes to make the simulator accessible

docfiles/tracking.html, webapp/src/logview.tsx
Couple of simple changes
- Adding referral URL to the telemetry so we can see where the link originates. 
- Removing the target specific tittle from the analyze data.
=> Adding referral URL 

common-docs/blocks/arrays/index-of.md, common-docs/blocks/arrays/indexof.md, common-docs/blocks/arrays/insert-at.md, common-docs/blocks/arrays/insertat.md, common-docs/blocks/arrays/pop.md, common-docs/blocks/arrays/push.md, common-docs/blocks/arrays/remove-at.md, common-docs/blocks/arrays/removeat.md, common-docs/blocks/arrays/reverse.md, common-docs/blocks/arrays/shift.md, common-docs/blocks/arrays/unshift.md
Card pages not included in this PR.
=> Fill in array topics.

theme/_theme/theme.config, theme/common.less, theme/theme.config, theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/globals/site.variables, theme/themes/pxt/views/card.overrides, theme/themes/pxt/views/card.variables, webapp/src/app.tsx, webapp/src/codecard.tsx
New Blocks/JS Toggle, plus minor UI fixes. (Mostly for mobile and toolbox)
pxt-microbit accompanying changes: https://github.com/Microsoft/pxt-microbit/pull/467
=> New Blocks/JS Toggle

pxtblocks/fields/field_note.ts, webapp/src/app.tsx
Same as https://github.com/Microsoft/pxt/pull/2590 but for master branch.
=> Bug 2516 fix master

pxtlib/blocks.ts, pxtlib/service.ts
* normalize localized blocks
* refuse localized strings with extra spaces
* validate localize block value
=> Normalizing and validating loc strings (#2640)

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/mutator_object_destructuring2.blocks, tests/decompile-test/cases/mutator_object_destructuring2.ts
=> Fixing edge case with object destructuring mutator decompilation

docfiles/editorcards.html, docfiles/footer.html, docs/index.html
Fixes #2628, Fixes #2598, Fixes #2537
=> Accessibility fixes for makecode.com.

docs/writing-docs/tutorials.md
Ok, here's a stab at updating the _writing_tutorials_ page. Let me know if I should say something more or if there's something incorrect.
Addresses https://github.com/Microsoft/pxt/issues/2651.
=> Expand the 'tutorials' doc page.

webapp/src/blocks.tsx, webapp/src/simulator.ts
=> Fix issue in rendering of the editor on Firefox android

docs/writing-docs/tutorials.md, pxtblocks/blocklyloader.ts, pxtrunner/renderer.ts, theme/tutorial.less
=> Colour tutorial and doc inline blocks with the respective ns color

docs/index.html
Add a focusable accessibility menu to skip to content at the first focus of the page. 
Fix sidebar accessibility (mobile view)
For accessibility issue: #2567
=> Skip to Content on makecode homepage

cli/cli.ts, docs/translate.md, localtypings/pxtarget.d.ts, pxtlib/util.ts, pxtrunner/runner.ts, webapp/src/app.tsx, webapp/src/container.tsx
Support for extracting target specific strings and saving them in "target-strings.json" file, that gets uploaded to crowdin
=> Target strings

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/array_get.blocks, tests/decompile-test/baselines/block_logic_operators.blocks, tests/decompile-test/baselines/block_text.blocks, tests/decompile-test/baselines/default_declarations.blocks, tests/decompile-test/baselines/functions_output.blocks, tests/decompile-test/baselines/number_with_enum_shadow.blocks, tests/decompile-test/cases/number_with_enum_shadow.ts, tests/decompile-test/testBlocks/basic.ts
Not a very clean merge, because V0 doesn't have the field editor changes in. Fixes https://github.com/Microsoft/pxt/issues/2637
=> V0 Cherry pick #2573

Jakefile.js, cli/cli.ts, docfiles/head.html, pxtblocks/blocklylayout.ts, pxtlib/browserutils.ts, pxtrunner/renderer.ts, theme/blockly-core.less, theme/blockly.less, theme/common.less, webapp/public/docs.html, webapp/public/index.html, webapp/public/release.manifest, webapp/public/runnertest.html, webapp/public/transfer.html, webapp/src/app.tsx
Split out blockly.css and append it's contents when creating a screenshot.
Fixes #2689, Fixes #2222, Fixes #2694
=> Split out blockly css into blockly.css

theme/blockly-core.less, theme/common.less, theme/themes/pxt/globals/site.variables, webapp/src/app.tsx
=> Reverting JS toggle UI changes for v0

theme/themes/pxt/globals/site.variables
Related issue : [https://github.com/Microsoft/pxt/issues/2608](https://github.com/Microsoft/pxt/issues/2608)
=> [Accessibility] Fixed the issue related to "pick a name" text input placeholder.

docfiles/style.css, theme/blockly-core.less, theme/themes/pxt/globals/site.variables, theme/tutorial.less
Standardizing on 12pt point font
=> Standardizing on 12pt point font [master]

package.json
Use pxt-monaco-typescript v2.2.6 that contains fixed for #2715
=> Point to latest monaco typescript language service.

theme/highcontrast.less
Support of the high contrast for the tutorial. This PR is additional to [https://github.com/Microsoft/pxt/pull/2682](https://github.com/Microsoft/pxt/pull/2682) and requires the changes of this PR to work.
=> [Accessibility] Tutorial (High contrast)

pxtlib/cpp.ts, pxtlib/package.ts, webapp/src/scriptsearch.tsx
Porting the v0 fix to master
This was reviewed here: https://github.com/Microsoft/pxt/pull/2730
=> Add package now checks version conflicts

pxtsim/libgeneric.ts
Fixing the Math.imul algorithm
=> fixing intIMul algorithm issue

localtypings/pxtarget.d.ts, webapp/src/appcache.ts
No easy way to test this, but I'm pretty sure I did it right.
=> Adding flag to disable reload on app cache download

docs/index.html
Attempt to fix #2595
Use html5 version of youtube's embed player which is meant to be accessible.
=> Youtube embed accessibility

theme/sidedoc.less, webapp/src/container.tsx
Fixes #2735 
Tested on Mac and IOS.
@riknoll tested on Windows
=> Improve sidebar structure for better scrolling on IOS. 

cli/cli.ts, common-docs/SUMMARY.md, common-docs/blocks/arrays.md, common-docs/blocks/arrays/pop.md, common-docs/blocks/arrays/shift.md, common-docs/javascript/call.md, common-docs/types/array.md
- Fixes some issues with ``pxt checkdocs --snippets``
- Fails build when issues in docs detected
=> Various doc fixes

pxtcompiler/emitter/emitter.ts
Fixes https://github.com/Microsoft/pxt/issues/2749
This is a V0 PR, so don't merge.
=> V0 Don't break compilation on whitespace in image literals

README.md
=> Adding gitter badge to the README

pxtblocks/blocklyloader.ts
Made the search bar of the Blocky toolbox accessible.
Related issue : [https://github.com/Microsoft/pxt/issues/2627](https://github.com/Microsoft/pxt/issues/2627)
=> [Accessibility] Search bar in Blocky toolbox is not accessible.

webapp/src/blocks.tsx
=> Add OK button for the Blockly alert

cli/cli.ts, common-docs/browsers.md, common-docs/browsers/technical.md, package.json, webapp/public/index.html, webapp/src/app.tsx
Minify CSS using postcss (cssnano)
- adding autoprefixer
- and rtlcss for blockly.css
=> Minify CSS

webapp/src/sui.tsx, webapp/src/tutorial.tsx
Fixed an issue where the focus was not initialized correctly in the tutorial, and set the first focused item to the OK button.
=> [Accessibility] Fixed an issue related to the focus in the tutorial.

libs/pxt-common/pxt-core.d.ts
Related to https://github.com/Microsoft/pxt/issues/2760.
=> Match help paths to topic names for 'Arrays' docs.

localtypings/pxtarget.d.ts, pxteditor/editor.ts, pxteditor/editorcontroller.ts, webapp/src/app.tsx, webapp/src/extensionManager.ts, webapp/src/extensions.tsx
This is a PR against the packageextension branch. Just connecting my code and Sam's code.
=> Tying together UI and extension manager

pxtcompiler/emitter/service.ts
Related to #2778 
(master change)
Also fixing adafruit int32 issue and initializer issue:
=> Add quotes around string literals when compiling the default parameter

THIRD-PARTY-NOTICES.txt, cli/cli.ts
New packages: 
- uglify-js @riknoll 
- postcss @microsoftsam
- rtlcss  @microsoftsam
- cssnano @microsoftsam
- chai @riknoll 
- karma @riknoll 
- karma-chai @riknoll 
- karma-chrome-launcher @riknoll 
- karma-mocha @riknoll 
- mocha @riknoll 
All MIT. 
@abchatra Please review.
=> Refreshing third party notices.

pxtblocks/codecardrenderer.ts, pxtrunner/renderer.ts
Related issue : [https://github.com/Microsoft/pxt/issues/2802](https://github.com/Microsoft/pxt/issues/2802)
=> [Accessibility] Fixed the accessibility of code cards in the documentation.

docfiles/docs.js, webapp/src/sui.tsx
Fixed the right to left reading way for the tab panel.
Related issue : [https://github.com/Microsoft/pxt/issues/2813](https://github.com/Microsoft/pxt/issues/2813)
=> [Accessibility] Support of the Right to Left reading way.

docs/index.html
Fixed an issue where the narrator was not announcing correctly the sections in makecode.com
Related issue : [https://github.com/Microsoft/pxt/issues/2628](https://github.com/Microsoft/pxt/issues/2628)
=> [Accessibility] Fixed an issue where sections were not announced correctly.

docfiles/style.css, docfiles/toc.html, docfiles/tocheader.html, docs/SUMMARY.md
- Moved the Published by Microsoft at the bottom of the sidebar.
- Made the sidebar black all the way.
- Fixed the blank link.
Related issue : [https://github.com/Microsoft/pxt/issues/2789](https://github.com/Microsoft/pxt/issues/2789)
=> Minor fixes in the blog's sidebar

common-docs/javascript/operators.md, common-docs/javascript/sequence.md, common-docs/javascript/statements.md, docs/blog.md
Related issue : [https://github.com/Microsoft/pxt/issues/2647](https://github.com/Microsoft/pxt/issues/2647)
=> [Accessibility] Fixed not descriptive enough link.

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/string_length.blocks, tests/decompile-test/cases/string_length.ts
Fixes #2833 
Not sure how this went unnoticed for so long.
=> Decompile string length

theme/accessibility.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/tutorial.tsx
- Fixed an issue where the focus outline was not displayed anymore on IE.
- Fixed the padding of the JavaScript editor in tutorial mode.
- Fixed an issue where the user was not able to do a Shift+Tab after clicking the OK button of a step of the tutorial very quickly after it was displayed.
- Fixed an issue where the Enter key was not supported on IE in the tutorial.
=> [Accessibility] Fixed a set of issues detected during the team test.

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/array_default_declaration.blocks, tests/decompile-test/cases/array_default_declaration.ts
Fixes https://github.com/Microsoft/pxt/issues/2811
=> Don't decompile default array declarations

common-docs/javascript/types.md
'null' and 'undefined' aren't allowed as types so only a small discussion about setting as values.
=> Add 'null' and 'undefined' to JS types doc.

localtypings/pxtarget.d.ts, webapp/src/share.tsx
Theme option to hide advanced embed options
=> support for hiding embed options

pxtblocks/blocklycompiler.ts
Fixes #2899 
This should catch all of those annoying too big or too small errors.
=> Catch block errors

cli/cli.ts
Was causing all of the docs to fail in Adafruit.
=> Check docs using blocksprj not core

docs/SUMMARY.md, docs/telemetry.md, pxtlib/docsrender.ts
Adding telemetry doc to the makecode docs
=> adding telemetry doc

docs/blog.md
Related issue : [https://github.com/Microsoft/pxt/issues/2647](https://github.com/Microsoft/pxt/issues/2647)
This change affect only the blog of PXT. Because of that, I did the changes on a branch based directly on master.
=> [Accessibility] Fixed not descriptive enough link in the blog

pxtrunner/runner.ts
Don't show the "hint" image when there is no hint
=> no hint bubble in tutorial

docfiles/tracking.html, package-lock.json
Reverting the change until we have the right cookie banner
=> Change to disable application insight cookie

common-docs/blocks/on-start.md
* Insert event order note tagging.
* Change name of replacement tag.
=> Cherry-pick to #2972 to v0, 'on-start' note.

common-docs/reference/arrays/create.md, common-docs/reference/arrays/get.md, common-docs/reference/arrays/set.md, common-docs/reference/math/from-char-code.md, common-docs/reference/text/join.md, common-docs/reference/text/length.md, libs/pxt-common/pxt-core.d.ts, pxtlib/blocks.ts
A set of picks from ``v0`` into ``master`` for cached block fixes/updates.
=> Cached block doc updates - picks from v0.

cli/cli.ts
As part of the build, renegerate all log string files. (add ?w=1 for no whitespace diff)
=> generate loc strings as part of build

pxtrunner/runner.ts
Remaining code to fix the old tutorial authoring
=> Support old tutorial authoring

pxtblocks/blocklyloader.ts
Fixes issues in tutorial mode where group labels were added for sections that were all hidden
=> Filter blocks before adding group labels

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/projects.tsx
Tutorial title was just ignored when creating a new project
=> propagate tutorial title from tutorial menu -- or -- format tutorial id

pxtblocks/blocklyloader.ts
Special casing the computation of visible sub-blocks for categories (since this category is dynamic). Fixes variable support in tutorials
=> custom visible children computation for variables

pxtblocks/blocklyloader.ts
Support for variables in tutorials
=> special filtering of variable blocks in tutorials

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/projects.tsx
Also fixed an error in sandbox view.
=> New import dialog. 

theme/home.less, theme/themes/pxt/views/card.overrides, webapp/src/app.tsx, webapp/src/core.ts, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx, webapp/src/share.tsx, webapp/src/sui.tsx
=> Save and Exit dialog.

theme/home.less, theme/themes/pxt/modules/modal.overrides, theme/themes/pxt/views/card.overrides, webapp/public/index.html
- Fixed issue with the custom content div appearing above the workspace and blocking interaction
- More UI fixes
=> Fix custom content div

pxtblocks/blocklyloader.ts
=> Fix TS (gray) blocks, making them multi-lined

pxtblocks/fields/field_gridpicker.ts
https://github.com/Microsoft/pxt-minecraft/issues/353
=> Add 300ms debounce to minecraft search

theme/home.less
Keeps the nav div in place when disabled. Just hides it.
=> Fix accidental project click when clicking the nav buttons

pxtblocks/fields/field_gridpicker.ts
Demo: no mouse involved! ![demo](https://user-images.githubusercontent.com/16658549/30720791-d1f25e90-9edd-11e7-848e-9161c405553f.gif)
=> Select first block when hit "enter" in gridpicker search bar

theme/sidedoc.less
=> Fix the sidedoc toggle in mobile view

docfiles/editorcards.html, docs/index.html
Tick is named as wonder in the target, makes it easier to correlate
=> changing the tick target name from wonderworkshop to wonder

webapp/src/carousel.tsx
Fixes the margin for the last carousel item and fixes the behavior when you are at the last item and the browser width grows
=> Fix carousel position for last item and on resizes

cli/buildengine.ts, cli/cli.ts, cli/gdb.ts, docs/defining-blocks.md, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtcompiler/emitter/elf.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/thumb.ts, pxtlib/cpp.ts, pxtlib/main.ts, pxtlib/service.ts, pxtrunner/renderer.ts, pxtwinrt/deploy.ts, webapp/src/app.tsx, webapp/src/cmds.ts
This is backport of the "codal" build engine
=> V0 codalbuild

webapp/src/projects.tsx
=> Grey offline alert boxes rather than red

cli/cli.ts, pxtlib/crowdin.ts
Compare list of files on disk and in Crowdin to detect "dead files" -- files that have been removed or renamed.
=> listing dead files in crowdin

cli/cli.ts, pxtlib/crowdin.ts
CLI command to find files in crowdin that are not on disk anymore.
```
pxt crowdin clean docs
```
=> List dead files in crowin

webapp/src/projects.tsx
Fix issue with react key not being unique enough, and getting flatten children warnings
=> Fix react MyStuff key

pxtsim/libgeneric.ts
Cherry-picking https://github.com/Microsoft/pxt/commit/e4108289165197a2319960b69a0f93db07d23eda
=> Cherry-pick Array shift fix into v0

theme/blockly-core.less, webapp/src/projects.tsx
- Add ticks for when a user renames their project in the save and exit dialog 
- Tick for when a user cancels 
- Renamed tick for getting-started button
=> Home screen ticks

localtypings/pxtarget.d.ts, theme/serial.less, webapp/src/serial.tsx
=> UI changes. added graph background theming support

webapp/src/app.tsx
Special 404 when user tries to report an missing script id. It seems that we have conflicting tslint versions that add/remove white spaces at the end of lines.
=> handle report abuse on missing script

pxtblocks/fields/field_gridpicker.ts
Fixes https://github.com/Microsoft/pxt-minecraft/issues/387
=> Bug 387 fix

webapp/src/container.tsx
FIx for https://github.com/Microsoft/pxt/issues/3056. These two got swapped somehow when merging.
=> Restoring menus

webapp/src/projects.tsx
Fix for https://github.com/Microsoft/pxt-minecraft/issues/414
=> stop simulator before entering home

webapp/src/app.tsx, webapp/src/appcache.ts, webapp/src/lang.tsx
If editor is open with project, reload into that project instead of going to homescreen.
=> reload in editor if editing on appcache update

pxtblocks/fields/field_gridpicker.ts, webapp/src/simulator.ts
Fixes https://github.com/Microsoft/pxt-minecraft/issues/412
=> Bug 412 fix

common-docs/reference/arrays/create.md
Pick changes from #3063 to ``v0``.
=> Fix 'create.md' for arrays. (#3063)

webapp/src/core.ts
=> Only submit the dialog window on enter key. Not space.

webapp/src/app.tsx
Fix issue where having the side doc loaded interferes with the getting started section of the home screen
=> Fix sidedoc loaded + home screen get started bug

docs/writing-docs/tutorials.md
Update _tutorials.md_ to include a section for ```@fullscreen```.
RE: https://github.com/Microsoft/pxt/issues/3068.
=> Put in a section for @fullscreen in tutorials.md

docs/cli.md, docs/packages/getting-started.md
I discussed this with Peli de Halleux on the #pxt Slack channel. I acknowledge that I am just now reading CONTRIBUTING.md, and have not followed that process. I should have known better...
https://microbit-community.slack.com/archives/C226FGXQX/p1506613598000756
I've made edits to two files, cli.md and getting-started.md. I explain the reasoning behind the edits in the commit messages. The overall reason for the suggestions is that I found the process of creating a new package to be confusing as it was originally explained, and I believe these edits would clarify the process for me if I were able to go back in time and start again.
=> Documentation updates to cli.md and getting-started.md

webapp/src/projects.tsx, webapp/src/sui.tsx
The classic JavaScript bug of not checking for undefined.
=> Fix the input when the value is empty and changing dialog wording

pxtblocks/fields/field_toggle.ts, theme/fieldeditors.less
=> Add ON / OFF description text onto the field toggle

docfiles/style.css
Fix issue with navigation buttons overlapping the body text making it hard to select the text. (#3105)
=> [master] cherrypick navigation button overlapping issue from v0

webapp/public/release.manifest, webapp/src/serial.tsx
- use regex to filter data lines
- fix "Export Data" button rendering
- pause recording when hiding editor view
- adding smoothie charts to manifest
=> Various serial items

webapp/public/index.html, webapp/public/release.manifest
=> use compressed version of smoothie

localtypings/smoothie.d.ts, webapp/src/serial.tsx
- card to export to CSV
- click on chart exports to CSV
- some cleanup
=> CSV support in logs

webapp/src/app.tsx, webapp/src/package.ts
- delay serial cleaning after compilation
- don't typecheck when showing serial editor
- don't show serial stuff if not supported.
=> Fixing race conditions with simulator start + serial output

webapp/src/scriptsearch.tsx
Cherry-pick hide download package loading when done downloading fix from v0
=> Downloading package loading fix [cherry-pick]

theme/home.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/views/card.overrides, webapp/src/app.tsx, webapp/src/projects.tsx
Update home screen with better button placement. 
Finishing a tutorial lands a user in the editor.
=> Home screen updates

docs/targets/pxtarget.md, docs/targets/theming.md, localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts
Seen https://github.com/Microsoft/pxt/issues/3145
=> removing block icon support

docs/targets/theming.md, localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts
See https://github.com/Microsoft/pxt/issues/3145
=> removing javascript rendering in blocks tooltips

pxtblocks/fields/field_toggle.ts, theme/fieldeditors.less
Fix field toggle to work when not in a shadow block, and can be in a square on block field.
=> Square field toggle

localtypings/pxtpackage.d.ts, pxtblocks/codecardrenderer.ts, webapp/src/codecard.tsx, webapp/src/projects.tsx
Authoring PR: https://github.com/Microsoft/pxt-minecraft/pull/453
=> Support labels and labelClass in home screen carousel.

webapp/src/app.tsx
better handling of invalid file type as well
=> fix drag and drop in home scree

pxtlib/util.ts, webapp/src/app.tsx
When serving a en-US browser, don't go through the cloud translations.
=> do not try to download translations for sim for english locale

theme/themes/pxt/views/card.overrides, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/projects.tsx
Close flout when switching editors or fullscreen mode.
Fixes this issue:
=> Close flyout on switch

pxtblocks/fields/field_toggle.ts, pxtblocks/fields/field_utils.ts
classList not available in SVG elements in IE11. Fix for Chibitronics IE11
=> special handling of svg.classList

docs/blog/chibitronics/v0.1.40.md
Seems confusing otherwise. Does this look ok?
=> Renaming wheel to slider

cli/cli.ts
Adding gallery titles to target-strings to allow localization
=> add gallery titles to locs

pxtsim/runtime.ts, pxtsim/simlib.ts
Support for running time in micro seconds https://github.com/Microsoft/pxt/issues/3198
=> support for microseconds running time

docfiles/head.html
The batch download screenshot feature looks for a "blocklycss" style item.
=> fixing download screenshot feature

localtypings/pxtarget.d.ts, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxtcompiler/emitter/ir.ts, pxtcompiler/emitter/thumb.ts, pxtcompiler/emitter/vm.ts, pxtlib/cpp.ts, pxtlib/emitter/assembler.ts, pxtlib/main.ts, pxtlib/service.ts
This implements codegen for VM running on AVR.
It additionally adds support for some recent codal build changes.
=> VM code generation

pxtlib/service.ts
Convert blockHidden to a boolean value to allow for false and true values.
=> BlockHidden bool

webapp/src/blocks.tsx, webapp/src/toolbox.ts
Fix https://github.com/Microsoft/pxt/issues/3174
=> Translate 'More' of 'Math' category

cli/cli.ts, pxtcompiler/emitter/service.ts, webapp/src/toolbox.ts
=> Fix for loc generation

pxtlib/util.ts
Fix for https://github.com/Microsoft/pxt/issues/3237
Also adds caching of downloaded translations.
=> Rendering on-start properly in docs

pxtlib/cmds.ts, pxtwinrt/deploy.ts, webapp/src/app.tsx
Goes with https://github.com/Microsoft/pxt-microbit/pull/553
=> UWP save()

theme/serial.less, webapp/src/serial.tsx
=> Serial tweaks

cli/cli.ts, pxtcompiler/emitter/service.ts, webapp/src/toolbox.ts
Integration doc generation fix from v0.
=> merging fix locs

theme/serial.less, webapp/src/serial.tsx
- move export button on top
- don't show console until there is something in it
=> Serialt weaks 2

pxtsim/langsupport.ts, pxtsim/libgeneric.ts
(Commenting them out so as to use them when debugging)
=> Remove lang useless console messages.

pxtlib/util.ts, pxtwinrt/serial.ts, theme/serial.less, webapp/src/app.tsx, webapp/src/serial.tsx
Add buffers to ensure that only complete serial messages are sent to the editor.
This will need to go into master as well.
=> More serial

pxtsim/runtime.ts, webapp/public/run.html
When simulator app cache is ready, reload.
=> force reload of simulator frame when ready

webapp/src/scriptsearch.tsx
https://github.com/Microsoft/pxt/pull/3296
=> Log github package names (master cherrypick)

pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/hexfile.ts, pxtcompiler/emitter/service.ts, pxtcompiler/emitter/vm.ts
Add plumbing suggested by @riknoll
=> get compile for VM path working on web worker

theme/serial.less, theme/themes/pxt/globals/site.variables, webapp/src/serial.tsx
Goes with https://github.com/Microsoft/pxt-adafruit/pull/413
=> Theming for close-editor button

pxtblocks/blocklyloader.ts, webapp/src/app.tsx
Fix drag issues described in: https://github.com/Microsoft/pxt/pull/3318
Microsoft/pxt-adafruit#401, and Microsoft/pxt-adafruit#355
apply to v0 as well.
=> Fix a couple of drag issues. Integrate from master

pxtblocks/blocklyloader.ts
Integrate https://github.com/Microsoft/pxt/pull/3302 to master
=> Integrate delete variable confirmation fix to master.

pxtlib/package.ts
Just lower verbosity of some upgrade messages
=> reduce verbosity of upgrade log messages

cli/cli.ts
Nicer error message for this error.
=> handle missing gallery in docs check

libs/pxt-common/pxt-core.d.ts
Fixes https://github.com/Microsoft/pxt-adafruit/issues/421
=> Move textFromCharCode to the Text category

theme/serial.less, theme/themes/pxt/globals/site.variables, webapp/src/serial.tsx, webapp/src/serialindicator.tsx
Fixes many of the issues in https://github.com/Microsoft/pxt/issues/3287.
=> Serial UI improvements

theme/serial.less
=> Change console border to @serialGraphBackground

common-docs/SUMMARY.md, common-docs/blocks-embed.md, common-docs/share.md, pxtblocks/blocklylayout.ts, pxtlib/browserutils.ts, pxtrunner/runner.ts, pxtsim/embed.ts, webapp/public/docs.html, webapp/public/rendertest.html, webapp/src/app.tsx
Cherry picking support for lightweight 3rd party docs rendering.
=> support for docs embed

webapp/src/serial.tsx
Cherry-picking multi-chart support in v0
=> multichart support

docfiles/tracking.html
Tested on all the windows browsers
=> Remove share id from ai urls

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/editortoolbar.tsx
Fixes https://github.com/Microsoft/pxt/issues/3373
=> Add isSaving state and save dialog

pxtblocks/blocklylayout.ts, pxtlib/browserutils.ts
Fixes https://github.com/Microsoft/pxt/issues/3372
=> Disable screenshot option on UWP edge

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/fixed_instance_args.blocks, tests/decompile-test/baselines/fixed_instance_calls.blocks, tests/decompile-test/cases/fixed_instance_args.ts, tests/decompile-test/cases/fixed_instance_calls.ts, tests/decompile-test/cases/testBlocks/fixedInstance.ts, tests/decompile-test/cases/testBlocks/pxt.json
Fixes https://github.com/Microsoft/pxt-adafruit/issues/431
=> Fix decompilation of fixed instances used as parameters

webapp/src/app.tsx
Fixes https://github.com/Microsoft/pxt-adafruit/issues/423
=> Error message update from upload to download

theme/common.less
Fix flickering issue when in between scrolling and non-scrolling states.
Fixes #3398
=> Fix flickering issue

webapp/src/app.tsx
Fixes https://github.com/Microsoft/pxt-chibitronics/issues/118
=> Typo in project loading id causing the loading spinner to not disappear

webapp/src/app.tsx, webapp/src/projects.tsx
Fix home screen re-load issue. and update terminology used for home screen actions
Fixes https://github.com/Microsoft/pxt-adafruit/issues/448
=> Home screen fixes

theme/monaco.less, webapp/src/monaco.tsx
=> Add instance variable name for monaco snippets

docfiles/tracking.html
=> V0 Remove share id from ai urls (#3392)

webapp/src/share.tsx
Fixes https://github.com/Microsoft/pxt-adafruit/issues/476#event-1328609395
=> Don't show social buttons on UWP Edge

webapp/src/projects.tsx
Open docs in new page rather than the side docs.
=> Open docs in new tab

pxtsim/libgeneric.ts
implement BufferMethods.toHex in sim
=> Implement toHex in lib generic

webapp/src/app.tsx
Add two new events for when the home is loaded, and when the editor is loaded.
=> Home / Editor tick event

cli/cli.ts, pxtlib/docsrender.ts
Scanning .html files under /docs to capture localization files from landing page.
=> scan .html pages under docfiles and docs

localtypings/pxtarget.d.ts, webapp/src/projects.tsx
Allows provide or replace galleries based on the user locale
=> support for localized galleries based on user-language

webapp/src/app.tsx, webapp/src/serial.tsx, webapp/src/srceditor.tsx
Fix for https://github.com/Microsoft/pxt-adafruit/issues/503
=> do not add entries for console editor in editor history

docfiles/editorcards.html
Removing beta label from makecode.com site for adafruit
=> Removing beta label from adafruit

pxteditor/extension.ts, webapp/public/extension.html, webapp/src/extensionManager.ts, webapp/src/extensions.tsx
=> Console output streaming for extensions

webapp/src/core.ts
Add core.ts dialogOpen close icon option.
Needed by https://github.com/Microsoft/pxt-adafruit/pull/525
=> Add modal close icon option in core.ts

pxtlib/emitter/cloud.ts, pxtlib/util.ts, webapp/src/db.ts
=> Offline locs for v0

pxtlib/util.ts, webapp/src/db.ts
Back porting v0 improvements to the localization cache.
=> in memory translation cache by default

webapp/src/serial.tsx
Fixes https://github.com/Microsoft/pxt-adafruit/issues/523
=> Don't filter stale charts while recording is paused

docs/blog/seeed/v0.2.10.md
Sorry I missed the review on #3475. Here are a few edits if you like. Otherwise, the current one will work.
=> Minor edits to Grove0 blog

docfiles/footer.html, docs/index.html
Tweets:
https://twitter.com/ribbweb/status/913502439487262721
https://twitter.com/morrill_rob/status/915347407428239360
https://twitter.com/deidrehonea1/status/926588738628669440
https://twitter.com/stephaniecodes/status/929486022072823808
https://twitter.com/katjaborregaard/status/925291348370051072
https://twitter.com/ynsmrclk/status/929783265812205569
=> updated footer

theme/highcontrast.less
Fixes https://github.com/Microsoft/pxt/issues/3415
=> White text on preview button in hc mode

docs/targets/samd21targets.md
=> Updating samd21 target docs

docs/targets/samd21targets.md
=> A few edits to the SAMD21 target page

pxtcompiler/emitter/emitter.ts
Fixes compiler bug uncovered in https://github.com/Microsoft/pxt-common-packages/pull/182
=> Fix emit of boolean expressions

docs/packages/extensions.md, webapp/src/extensions.tsx
Notifiy extension when shown/hidden
=> Extevents extshown / exthidden

package.json
Cherry pick webfonts-generator package update to v0
=> webfonts-generator package update

theme/common.less, theme/themes/pxt/globals/site.variables, webapp/src/notification.tsx
Fixes https://github.com/Microsoft/pxt-adafruit/issues/546
- Link text is bold, blue, and underlined
- Clicking on middle of banner does nothing; cursor is arrow, not pointer
=> Banner fixes

common-docs/blocks/variables/var.md
Do some tutorial text for 'variable'. This is in response to the loc issue:
https://crowdin.com/translate/kindscript/735/en-da#49798
=> Improve description/definition for 'variable'

cli/cli.ts, pxtlib/crowdin.ts
Better stats for crowdin data.
=> Crowdinstats2

cli/cli.ts
For bundled package YYY, the build automatically adds the blob location of /docs/static/libs/YYY.[png/jpg] in the pxt.json:icon file. It then shows up in the package selection dialog.
=> support for icons of bundled packages

webapp/src/appcache.ts
=> Add a tick event for reloads

webapp/src/serialindicator.tsx
=> Move event listener addition/deletion to React lifecycle methods

webapp/src/compiler.ts
Fixes https://github.com/Microsoft/pxt/issues/3519
=> Don't tree-shake on decompiling; fixes #2632

pxtlib/cmds.ts, webapp/src/app.tsx
Pop a dialog when download to a device fails from an app.
=> Nodevicedialog

common-docs/javascript.md, common-docs/javascript/call.md, common-docs/javascript/classes.md, common-docs/javascript/operators.md, common-docs/javascript/sequence.md, common-docs/javascript/statements.md, common-docs/javascript/types.md
Some minor edits after looking at #3539. Probably should revisit the TS/JavaScript topics to consider retargeting to a student/teacher audience.
=> Minor edits to the TS topics

pxtlib/browserutils.ts
=> patching project icon when loading bundled pkgs

pxtsim/visuals/microservo.ts
Fix for https://github.com/Microsoft/pxt/issues/3518
=> Servo opposite anglefix

localtypings/pxtarget.d.ts, webapp/src/notificationbanner.tsx
Cherry pick https://github.com/Microsoft/pxt/pull/3569
=> Move windows store link to targetconfig

theme/themes/pxt/modules/modal.overrides, webapp/src/app.tsx, webapp/src/core.ts
=> Add close icon option for core dialogAsync

webapp/src/app.tsx
Cherry-pick https://github.com/Microsoft/pxt/pull/3568.
Verified that it works in IE.
=> Port dimmer fix from v0

theme/highcontrast.less, webapp/src/serial.tsx
Fixes https://github.com/Microsoft/pxt/issues/3573
=> High contrast mode for serial editor

localtypings/pxtarget.d.ts, theme/highcontrast.less, webapp/src/serial.tsx
Cherry-pick https://github.com/Microsoft/pxt/pull/3579
=> Port high contrast theme from master

theme/common.less
Fixes https://github.com/Microsoft/pxt/issues/3571
=> Hide serial preview button in fullscreen mode

webapp/src/app.tsx
Make the troubleshoot button a link instead of a button, and link directly to the troubleshoot page. Adding tick event in the middle
=> Make the troubleshoot button a link instead of a button

webapp/src/serial.tsx
Same as https://github.com/Microsoft/pxt/pull/3587
=> No chart fill

webapp/src/cmds.ts
=> Iosdownload

cli/cli.ts, pxtlib/browserutils.ts, pxtsim/libgeneric.ts, webapp/src/app.tsx, webapp/src/cmds.ts
Migrating iOS download fix to master
=> Ios11 download master

pxtlib/emitter/cloud.ts
=> Guard around webconfig

cli/cli.ts
Better out of the box experience for extracted projects.
=> Undusting 'pxt extract'

cli/cli.ts
* refresh generated tasks
* undusting extract
* adding travis file
=> Undusting 'pxt extract' (#3604)

webapp/src/serial.tsx
Localizable CSV separator for master
Fix for https://github.com/Microsoft/pxt/issues/3619
=> Serial loc master

pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/emitter.ts, pxtsim/libgeneric.ts
This fixes memory leak in play melody.
=>  Fix ref-counting in switch (fixes mem. leak in #2107)

cli/cli.ts, localtypings/pxtarget.d.ts
Flag to ignore docs errors in v0 based editors.
=> Ignore docs errors - v0

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/gallery.ts
Allow examples relying on github packages to be loaded as well.
=> support for "package" macro in examples

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/gallery.ts
=> support for examples with dependencies

cli/cli.ts
=> Allow for logging a request that goes to the cloud builder 

docfiles/labscards.html, docs/static/targets/holiday/left-back.svg
Link takes you to: https://microsoftsam.github.io/pxt-holidays/controller.html
=> Add link to the holiday experimental target

pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/backthumb.ts
Optimization changes broke stack alignment. Should be fixed here.
=> Stack alignment fixes

pxtblocks/blocklylayout.ts, pxtlib/util.ts, pxtrunner/runner.ts, webapp/public/rendertest.html
Fix for IE to embed generated block SVGs
Fix logic to detect that locales need to be downloaded
Live test: https://makecode.microbit.org/app/729f69643caa647c16392b0c966ae8ee4e37a60f-ed1ef88c74
=> Embed docs ie 11

webapp/src/cmds.ts
=> Add 'done' button to 'download completed' dialog

pxtblocks/blocklyloader.ts, pxtlib/service.ts, webapp/src/monaco.tsx
Support icons on group labels 
Minor fix to labelWidth set to 0 issue as well.
=> Support icons on group labels.

pxtsim/simlib.ts
Add the enter equivalents of pointer, touch and move events.
=> Add pointer events for on enter.

pxtblocks/blocklylayout.ts
Integrate https://github.com/Microsoft/pxt/pull/3666/files to master (nbsp all Safari rendering issue)
=> Fix nbsp issue to replace all globally [master]

package.json, pxtsim/embed.ts
Support for "buffer" packet type in microbit
=> Radiobufferv0

pxtcompiler/emitter/emitter.ts, pxtsim/langsupport.ts, pxtsim/libgeneric.ts
=> Use Math.pow instead of numops.exps

cli/cli.ts, pxtcompiler/simshim.ts
=> Simshim fixes for move from TS 1.* to TS 2.*

package.json
=> bump marked version

docfiles/labscards.html
Update Holiday card link to: 
https://samelhusseini.github.io/pxt-holidays/controller.html
=> Update Holiday card link

package-lock.json
Updating package lock with an update to marked dependency
=> Update npm packagelock

webapp/src/monaco.tsx
add null check to monaco toolbox drag logic.
=> minor monaco toolbox bug

pxtlib/util.ts, webapp/src/app.tsx, webapp/src/serial.tsx
When a text file is dropped in the editor, interpret it as a console raw dump and import it into the editor.
=> Import console logs

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
A template codecard removes all the dependencies of the template project and injects the code/packages in there. Need for multi-board support
=> Board template code card

pxtsim/embed.ts, pxtsim/instructions.ts, pxtsim/simdriver.ts, pxtsim/simlib.ts, webapp/public/siminstructions.html, webapp/src/make.ts, webapp/src/simtoolbar.tsx
=> Fix make instructions

theme/highcontrast.less
=> Fixing main menu / download area in high contrast

docs/blog/microbit/csintro-japanese.md
A few edits to the English part if you want to take them.
RE: #3764
=> micro:bit japanese translate blog edits

pxtblocks/fields/field_toggle_updown.ts, pxtblocks/fields/field_tsexpression.ts
Allow to invert up/down mapping to true/false for specific case.s
=> allow inverting the "up" "down" logic

pxtblocks/blocklycustomeditor.ts, pxtblocks/fields/field_toggle_highlow.ts
Support for high-low field editor
=> high low custom field editor

pxtlib/cpp.ts, webapp/src/app.tsx, webapp/src/core.ts
@samelhusseini fixing a bug in the show/hide logic w.r.t. to calling multiple show with the same key.
=> show a compile message while waiting for cloud image

package-lock.json, pxtsim/svg.ts
Cleanup old code to hook pointer events and use latest fixed version.
=> fixing pointer events in sim

localtypings/pxtarget.d.ts, package-lock.json, pxtlib/github.ts, webapp/src/core.ts, webapp/src/data.ts
Cherrry-picking github proxying into v0.
The issue was reported by partners trying to use NeoPixel in schools.
=> Githubproxyv0

common-docs/reference/text/join.md
Fixes https://github.com/Microsoft/pxt/issues/3783.
=> Fix 'text.join' example in api topic

cli/gdb.ts
Use gdb shipped with Arduino (just like openocd) and set terminal flags correctly
=> Make pxt gdb work in Windows

localtypings/pxtarget.d.ts, webapp/src/container.tsx
Support for specifying different images for high contrast
=> support for highcontrast logos

package-lock.json, package.json
Vulnerability detected in 2.2.4
=> upgrading to jquery ^3.0.0

pxtblocks/blocklylayout.ts, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxtlib/browserutils.ts, pxtlib/cpp.ts, pxtlib/package.ts, pxtlib/service.ts, pxtlib/util.ts, pxtrunner/renderer.ts, pxtsim/simlib.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/worker.ts
It turns out that our polyfill for atob was btoa.
=> Atob or not atob!

webapp/src/carousel.tsx
Did not like when a child was undefined.
=> handle undefined children in carousel

pxtwinrt/hiddeploy.ts, pxtwinrt/winrt.ts
Disconnect on suspend and reconnect on resume in WinRT.
=> support for suspend/resuming events

webapp/src/serial.tsx
* removing chart dropper
store data for longer
* adding separator header
* storing a few more points
=> Serial view improvements v0

webapp/src/notification.tsx
@riknoll you can lump this one in the v0 cookie work.
=> don't show windows notification when cookies is up

docfiles/abuse.html, docs/certificates.html, webapp/public/transfer.html, webapp/src/app.tsx, webapp/src/simulator.ts
Fix for https://github.com/Microsoft/pxt/issues/3821 . See https://jquery.com/upgrade-guide/3.0/#feature-jquery-ready-promise-is-formally-supported
=> various jquery 2->3 fixes

.travis.yml, THIRD-PARTY-NOTICES.txt, cli/serial.ts, package-lock.json, package.json
Upgrading to serialport 6.x requires also to run node 8.x in travis.
v3 - https://github.com/Microsoft/pxt/pull/3826
=> Serialport 6 - v0

.travis.yml, README.md, THIRD-PARTY-NOTICES.txt, cli/serial.ts, package-lock.json, package.json
=> upgrading to serialport 6

pxteditor/editor.ts, pxtlib/hf2.ts, pxtlib/webusb.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/container.tsx
* align with latest WebUSB spec
* add "Pair device" menu item; needs to be done once per device it seems
* fixes in auto-reconnect; this might affect HID as well
=> WebUSB support

pxtlib/cmds.ts, pxtwinrt/deploy.ts, webapp/src/app.tsx
=> [UWP App] Offer to download when device not found

common-docs/blocks/custom.md, common-docs/blocks/javascript-blocks.md, common-docs/blocks/logic/boolean.md, common-docs/blocks/variables/assign.md, common-docs/blocks/variables/change.md, common-docs/browsers/technical.md, common-docs/cli.md, common-docs/support.md
=> Typo fixes picked to v0

pxtcompiler/emitter/driver.ts
=> adding tick to track compile time

cli/cli.ts
Fixing some CLI warnings reported by node 8
=> Fswritefilesync

libs/pxt-common/pxt-core.d.ts
Just rearranging the array blocks
=> rearranging array blocks

cli/cli.ts
It mostly does not worry and generates a ton of warnings.
=> don't try to build docs for individual packages

cli/buildengine.ts
I guess no one is building locally?
=> Add ".cmd" to npm invocation on Windows

webapp/public/transfer.html
There was an extra semantic.css include in transfer.html
=> removed extra doccdn in transfer.html

common-docs/blocks/math.md, common-docs/reference/math.md
Add a section for the new ``**`` operator in the math topic.
RE: #3717, #3704
=> Add exponent operator section in math doc

localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
Support for opening docs in side bar
=> support for sidedocs card again

cli/cli.ts
Display target and pxt version in CLI outputs
=> show version in cli output

README.md, pxt-cli/cli.js, pxt-cli/package.json
We'll have to publish this manually since it's in the JS cli and not `cli.ts`
=> Adding PXT link command to the pxt cli

pxtwinrt/deploy.ts, webapp/src/serial.tsx
to ensure Excel opens the file. Tested in Chrome, Windows 10 app.
=> Generate new name when saving data.csv

pxtcompiler/emitter/emitter.ts
This aligns with the `screen` branch in common packages. Otherwise, the `@f4` feature was not used anywhere else, so should be safe to merge.
=> Fixes in @f4 literal support

docfiles/apptracking.html, docfiles/tracking.html
Appisights enabling local storage when cookie is enabled.
=> Enabling local storage when cookie is enabled

docfiles/apptracking.html, docfiles/tracking.html
=> Enabling localstorage for application insights when cookie is enabled

docfiles/apptracking.html, docfiles/tracking.html
Porting to stable3.3 from master
=> Enabling local storage when cookie is enabled (#3888)

theme/sidedoc.less
Fix for https://github.com/Microsoft/pxt-microbit/issues/643
=> fix sidedocs z-index issue

pxtlib/main.ts
Guarantees single call per client
=> Cache promise for targetconfig query

webapp/src/scriptsearch.tsx
Support for marking 'devices' as beta in microbit
=> support for 'beta' flag on bundled projects

pxtlib/main.ts, webapp/src/scriptsearch.tsx
=> cache target config promise

pxtrunner/renderer.ts, pxtrunner/runner.ts
Switch to portrait vs landscape layout of blocks based on the window size.
=> Adapt block rendering ratio based on window size

docfiles/macros.html, pxtblocks/codecardrenderer.ts, pxtrunner/runner.ts, webapp/src/codecard.tsx, webapp/src/projects.tsx
Some of our YouTube inserts have broken screenshots. It seems that maxresdefault.jpg is not guaranteed to exist in youtube. We should really be handling those more gracefully (since yt is blocked in many districts).
=> maxresdefault.jpg is not guaranteed to exist. 0.jpg seems more stable.

theme/sidedoc.less, theme/themes/pxt/globals/site.variables
Try it at https://makecode.legoeducation.com/app/df00299f182b5751aebf181a891d161c0c0a4c3a-e9d8a598ec
=> enlarge sidedocs in large monitor / fix mobile resize rendering issue

docs/targets/board.md, localtypings/pxtparts.d.ts, pxtsim/instructions.ts, pxtsim/visuals/boardhost.ts, pxtsim/visuals/wiring.ts
- support for specifying pinstyle on dalboard pins
=> Upgrading wiring engine

docfiles/macros.html, pxtrunner/renderer.ts, pxtrunner/runner.ts, theme/sidedoc.less, theme/themes/pxt/globals/site.variables
- large sidedocs in large screen
- better youtube preview file
- better block ratio
=> Cherry-pick side docs improvement in v0

pxtwinrt/hiddeploy.ts, pxtwinrt/serial.ts, pxtwinrt/winrt.ts, webapp/src/app.tsx, webapp/src/lang.tsx, webapp/src/scriptsearch.tsx
Cherrypicking 56a5061ea078722f0c5b1031d0c862a38d0d0b3d + fixing conflicts
=> Port v0 changes: disconnect all winrt devices on reload

theme/common.less, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/sui.tsx
Diff without formatting: https://github.com/Microsoft/pxt/pull/3924/files?w=1
=> Mobile apps fixes

pxtsim/runtime.ts
Without it the following program will print stuff:
```
forever(() => {
console.log("foo")
})
let x = 0
while (true) {
x++
// loops.pause(10); // without this line there should be no interleaving
}
```
=> Make sure non-yielding threads don't interleave

pxtblocks/blocklymutators.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/671
=> Fix clashses between radio mutator and serial namespace

tests/blocklycompiler-test/test.spec.ts, theme/common.less, theme/sidedoc.less, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/sui.tsx
=> Mobile fixes v0

localtypings/pxtpackage.d.ts, pxtblocks/codecardrenderer.ts, pxtlib/github.ts, pxtrunner/renderer.ts
For package cards, check that package is approved and display icon if so. Use in https://makecode.microbit.org/packages .
=> Display package icon in package cards

pxtblocks/composablemutations.ts
Fixes three bugs:
1. The event listeners that the expandable blocks were registering on the workspace were not being removed
2. The plus button on the block was always rendering in the docs even when hidden
3. I was calling `render()` during block drag which caused some inputs to appear misaligned
I don't know if that memory leak was causing any real issues; I just happened to notice it while debugging. It could definitely be bad on large projects or if you open/close the toolbox several times.
=> Fixes a memory leak and some UI bugs for expandable blocks

cli/cli.ts, pxt-cli/cli.js
A couple more remove jake install dependency fixes.
=> more remove jake install dependency fixes.

docfiles/apptracking.html, docfiles/tracking.html
Fixes the leaky key issue
Add cookie information.
=> Fixing the leak key (Port from master)

pxtlib/github.ts
Cherry-pick of https://github.com/Microsoft/pxt/pull/3944
=> only pick tags that look like vxx.xx.xx

package-lock.json, pxtcompiler/emitter/emitter.ts, pxtsim/langsupport.ts, pxtsim/libgeneric.ts
In a JS target, also store key names.
=> store key names in refmap for js targest

pxtsim/embed.ts, webapp/src/app.tsx, webapp/src/editortoolbar.tsx
=> Save as png updates

theme/serial.less, webapp/src/serial.tsx
=> Support for CSV in serial [v0]

webapp/src/serial.tsx
=> use copy icon for console button

docfiles/pxtweb/cookieCompliance.ts
=> Revert "Re-add electron check"

pxtsim/runtime.ts
Fixes https://github.com/Microsoft/pxt-32/issues/5
=> Avoid stack overflow when there's lots of callbacks

pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
Needed to implement high score
=> pass pkg version to simulator

pxtblocks/blocklyloader.ts
All tests run and passed.
Resolves issue [3981](https://github.com/Microsoft/pxt/issues/3981).
=> Support blocks that return extended types as output.

pxtblocks/blocklyloader.ts
=> Fix function flout label value.

cli/cli.ts
Call lessc with no IE8 compat flag to allow font sizes / data-uri greater than the IE8 limit of 32 KB.
=> Call lessc with no IE8 compat flag to allow font sizes greater than 32 KB

pxteditor/editor.ts, webapp/src/cmds.ts
Pass preferred download file to host
=> pass name to host

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/cmds.ts
Support for iOS/Android hosted scenarios. @guillaumejenkins we could also use this interface to send message to Electron for download/save.
=> support for native host messages

webapp/src/filelist.tsx, webapp/src/package.ts
Display error count of package in explorer view
Diff no spaces: https://github.com/Microsoft/pxt/pull/4001/files?w=1
=> display error count recursively

libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
Cherry pick of missing array fuctions (forEach, some, join, every)
=> Arrayfunctions v0

cli/cli.ts
More logging and suppor simple "foo.png" slurping.
=> more logging in buildjres

pxtrunner/runner.ts, webapp/src/app.tsx, webapp/src/filelist.tsx, webapp/src/package.ts
- book loader
- error display in explorer
=> Cherry picking to v0

webapp/src/container.tsx
Port accessibility fix to v0.
Add title for help menu link items.
Fixes https://github.com/Microsoft/pxt/issues/3991
=> [v0] Accessibility fix for #3991

webapp/src/container.tsx
Add title on help menu link items.
=> Accessibility fix for #3991

webapp/src/monaco.tsx, webapp/src/monacoSnippets.ts
Fix for issue [4022](https://github.com/Microsoft/pxt/issues/4022).
=> Fix Monaco editor sorting to match Blockly editor sorting.

webapp/src/app.tsx
Enable light mode when multiple typechecks are slower than 10sec + tick
=> auto light mode

docfiles/style.css, pxteditor/editor.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, webapp/public/docs.html, webapp/public/runnertest.html, webapp/src/app.tsx, webapp/src/container.tsx
Added "print code" in settings dialog.
=> Print code

docfiles/pxtweb/cookieCompliance.ts
I am still testing this and will update in case I find issues
=> Removing cookie from share page

pxtlib/analytics.ts, webapp/src/notification.tsx
Banner does not show currently.
=> check if cookies are enabled when showing windows app banner

pxteditor/monaco.ts, webapp/src/monaco.tsx
Fix monaco hex block borders bug. 
and don't allow scroll with a mouse in monaco
Fixes https://github.com/Microsoft/pxt/issues/3896
=> Fix monaco toolbox hex blocks

cli/cli.ts, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, package.json, pxtblocks/blocklyloader.ts, pxtblocks/fields/field_colour.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/service.ts, pxtlib/package.ts
See https://github.com/Microsoft/pxt-32/commit/fc7681e6e4b968fb228898d961856647ad70724f for usage
=> Add 'pxt buildsprites'

pxtsim/runtime.ts, pxtsim/simlib.ts
It would have been nice to just convert,
```typescript
export class EventQueue {
```
to 
```typescript
export class EventQueue<T = number> {
```
but TypeScript's obligatory compile time type inferencing didn't allow the generic assignment of a default value such as 0 in,
```typescript
queue(id: number | string, evid: number | string, value: T = ????) {
```
Hence the derived class and method override from `EventQueueGeneric<T>`.
Existing code will have exactly the same behavior, including the 0 default value. Ran unit tests, lint and tested `pxt-adafruit` and my client against the new pxt-core.
Usage is in the client simulator code is like this,
```typescript
export class Mouse {
constructor(public x: number, public y: number) {}
} 
export class MyBoard {
private static _eventsMouse: …
```
=> Let simulator clients send event values other than the number type.

webapp/src/core.ts
Currently all modal button actions have to have icons. Make the icon field optional.
=> Make core modal actions have optional icons.

package.json
New file needs to be added to the package.json. Fixes https://github.com/Microsoft/pxt/issues/4072
=> Add gitfs to package.json

.travis.yml, Jakefile.js, package.json
Use the production version of react on prod builds (travis)
As per https://reactjs.org/docs/optimizing-performance.html#use-the-production-build
=> Use prod react

pxtblocks/fields/field_images.ts
An option to support sorting the options in the list (for FieldImages field editor)
=> Support sorting option for FieldImages

docfiles/docs.js, pxtrunner/renderer.ts
``typescript-ignore`` typically don't build so it's pointless to try to display a simulator. See ``/javascript/sequence`` page.
=> don't show run button for ignored snippets

pxtrunner/renderer.ts, pxtrunner/runner.ts, pxtsim/embed.ts, webapp/src/app.tsx
=> better print support

cli/cli.ts
``keytar`` is now using promises for their API so a bunch of related changes to that.
=> keytar 4 is using promises

pxtblocks/blocklyloader.ts, theme/blockly-core.less
=> Updates to the variable flyout button UI.

common-docs/blocks/math.md, common-docs/reference/math.md, common-docs/reference/math/constrain.md, common-docs/reference/math/map.md
=> Update to 'math' docs

webapp/src/app.tsx
Revert simulator being the default embed view
Reverting https://github.com/Microsoft/pxt/pull/4027/files
=> Revert embed sim default

webapp/public/index.html, webapp/src/serial.tsx
Load smoothie javascript library when user devices to see console view.
=> delay load smoothie charts

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/lang.tsx
Always reload into the home screen.
If we had to choose between one and the other, home screen is safest.
Fixes https://github.com/Microsoft/pxt/issues/3459
=> Always reload into home screen.

webapp/src/container.tsx
Minor merge issue with the Blockly delay loading change
=> Fix right Logo

cli/cli.ts
Build before deploying to the cloud through staticpkg or upload target.
It's important that we build so that we update the target.js (json) because it's most likely different on our local build than what we need for a staticpkg or uploadtarget. 
I also added the cloud option for both, so that we can build (with the cloud) as we upload.
=> Build before uploadtarget

pxtlib/browserutils.ts, webapp/public/index.html
=> Lazy blockly.css

cli/cli.ts, webapp/public/docs.html, webapp/public/index.html, webapp/public/release.manifest, webapp/public/siminstructions.html
Bundle custom pxt icons into semantic.css which is also minified.
one less web request, minified with semantic.css
=> Bundle custom pxt icons

pxtlib/browserutils.ts, pxtlib/cpp.ts, pxtlib/package.ts
Add 'async=false' on script element to ensure execution.
=> more logging around dynamic script loading

Jakefile.js, webapp/public/index.html, webapp/public/release.manifest
Bundles various pxt libraries used in the editor into a single file.
=> Bundle pxt*

theme/themes/pxt/elements/button.overrides
Accidentally removed one important css when removing custom.css
=> Add back missing custom css.

webapp/src/app.tsx, webapp/src/notification.tsx
=> don't change the title based on script

Jakefile.js, webapp/public/release.manifest, webapp/src/worker.ts
worker.js gets rewritten so "@cdnUrl@ gets expanded. Unbundling.
=> unbundling worker.js

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/class_handler_parameter.blocks, tests/decompile-test/cases/class_handler_parameter.ts, tests/decompile-test/cases/testBlocks/classHandlerParameter.ts, tests/decompile-test/cases/testBlocks/pxt.json
=> Fix decompilation of handler parameters for instance methods

cli/cli.ts
A new command ``pxt testghpkgs`` automates the search, clone, build of **approved** packages.
=> Batch testing of approved packages [v0]

pxtblocks/fields/field_imagedropdown.ts
Make onHide a class function rather than a field function for image dropdown.
Easier extensibility
=> Image dropdown field changes

cli/cli.ts
Broken by https://github.com/Microsoft/pxt/pull/3861 . We haven't been generating _locales files since then.
=> restore generation of _locales files

pxteditor/editor.ts, pxtlib/cmds.ts, pxtlib/package.ts, webapp/src/app.tsx
Allow extensions to override "saveOnlYAsync"
=> support to extend "saveOnlyAsync"

pxtsim/simdriver.ts, pxtsim/utils.ts
querySelectorAll does not support forEach is IE.
=> IE fix for querySelectorAll

webapp/src/blocks.tsx
Only move when breakpoint info is available.
=> center on breakpoint only

pxtblocks/blocklylayout.ts
Fix download screenshot after all the blocklycss load changes
=> Fix download screenshot

docs/blocks-embed.md, docs/packages/extensions.md, docs/packages/getting-started/objects-instances.md, docs/packages/getting-started/ref-docs.md, docs/simshim.md
Various small edits from an eyeball scan.
=> Some edits to dev docs

webapp/src/projects.tsx
Bottom version number opens about dialog.
=> open about dialog when clicking on version

webapp/src/app.tsx, webapp/src/sui.tsx
Make light box closable on click.
=> Make light box closable

cli/cli.ts, docfiles/appmeta.html, localtypings/pxtarget.d.ts
=> refresh web manifest generation

webapp/src/core.ts, webapp/src/projects.tsx, webapp/src/sui.tsx
Most browsers support it: https://caniuse.com/#feat=autofocus
IOS doesn't but that's okay in this case.
=> Auto focus inputs on prompts

webapp/src/projects.tsx
Move to Async methods on all dialog functions, missed one.
=> Fix about dialog in projects

.vscode/launch.json, cli/cli.ts, cli/pyconv.ts
=> Tweaks to pyconv

webapp/src/appcache.ts
Editor gets stuck in infinite reload loop as the appcache updateready event triggers but the status is idle (1)
=> check status before reloading appcache

pxtblocks/blocklycompiler.ts, pxtblocks/fields/field_breakpoint.ts, pxteditor/editor.ts, pxtlib/toolbox.ts, theme/fieldeditors.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/debugger.tsx, webapp/src/srceditor.tsx, webapp/src/sui.tsx
=> Adding "breakpoint" button in debugger toolbar

pxtsim/embed.ts, webapp/public/run.html
Handle incorrect app cache event in firefox in sim
=> handle appcache firefox issue in sim

webapp/src/app.tsx
Show a warning when an orphan exception (not source available) is found.
=> show warning on orphan exceptions

webapp/src/marked.tsx, webapp/src/tutorial.tsx
Ensures no conflicts between different tutorial steps. Wrap tutorial steps in separate code blocks.
=> Wrap tutorial steps in separate code blocks.

cli/cli.ts, docs/cli.md, docs/cli/buildsprites.md
@mmoskal can you braindump docs about this command in the .md?
=> adding argument checking + docs skeleton

cli/cli.ts, package-lock.json, pxtlib/package.ts
=> Build core packages

localtypings/pxtarget.d.ts, webapp/src/package.ts
The regex is specific in the target pxtarget.json file.
=> Ability to provide a regex to restrict generated filenames.

docs/packages/getting-started.md
Link for "custom blocks feature" in follwing page is broken.
https://makecode.com/packages/getting-started
=> fix broken link

webapp/src/blocks.tsx
Fixes https://github.com/Microsoft/pxt/issues/4294
=> Fix issue with shadow XMLs

webapp/src/app.tsx, webapp/src/core.ts, webapp/src/coretsx.tsx, webapp/src/dialogs.tsx
Use JSX for dialogs instead of html. (slowly getting rid of all those dialogs using htmlBody). 
Most importantly, we need to use JSX for inputs with autoFocus, otherwise react won't auto focus them on modal load. The browser will only autofocus the first time they appear. 
Fixes https://github.com/Microsoft/pxt/issues/4271
=> autofocus dialog inputs properly

theme/greenscreen.less, webapp/src/container.tsx, webapp/src/dialogs.tsx, webapp/src/greenscreen.tsx, webapp/src/projects.tsx
+ try/catch fixes for green screen.
=> Moving TOS/Privacy to About

webapp/src/app.tsx
Reverting testing changes with version check (wrong way...)
=> fix version check

docs/SUMMARY.md, docs/packages/localization.md
See translation ``Step 1`` to make sure it's correct. Thx.
=> Package localization doc edit

pxtblocks/blocklyimporter.ts, pxteditor/editor.ts, pxtlib/package.ts, pxtlib/patch.ts, webapp/src/app.tsx, webapp/src/monaco.tsx, webapp/src/package.ts
Added callback to patch blockly provided by extensions
Cleaning up patching story by moving logic in patch.ts
=> Support for extension patches

theme/highcontrast.less, theme/tutorial.less, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx
Fix a number of editor accessibility issues.
Fixes https://github.com/Microsoft/pxt/issues/3229
Fixes https://github.com/Microsoft/pxt/issues/2966
Fix for https://github.com/Microsoft/pxt/issues/2535
=> Fix a number of accessibility issues

docfiles/footer.html
Update footer to resolve issue with removed Microsoft image. 
Fix issue with hidden image in the footer (accessibility) Fix for #2803
=> Fix issue with hidden image in the footer 

docfiles/footer.html
master fix for issue with hidden image in the footer (accessibility) Fix for #2803
=> [master] PR of #4319

webapp/src/share.tsx
=> always include major version in embeddeable html

cli/cli.ts, common-docs/share.md, pxtlib/docsrender.ts
=> Better checkdocs

webapp/src/make.ts
Eventually need to rewrite this in React... but not today.
=> show cancel in make dialog

pxtsim/simdriver.ts
Fixes https://github.com/Microsoft/pxt/issues/4300
=> Remove redundant allow fullscreen in sim driver

common-docs/javascript/functions.md
Merge changes from https://github.com/Microsoft/pxt/pull/4345
=> Pick changes from e2ed641

.vscode/launch.json, cli/cli.ts, cli/pyconv.ts, docs/packages/pxtJson.md, localtypings/pxtpackage.d.ts, pxtlib/package.ts, pxtsim/embed.ts
Allow additional dependencies when compiling tests.
=> Test dependencies

pxtblocks/fields/field_images.ts, theme/fieldeditors.less
=> Add option for label in field images

pxtblocks/blocklycustomeditor.ts, pxtblocks/fields/field_speed.ts, pxtblocks/fields/field_turnratio.ts
Migrating speed, turnratio editors.
=> adding speed, turnratio editors

theme/home.less, theme/pxt.less, theme/scriptsearch.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/modules/modal.overrides, theme/themes/pxt/modules/modal.variables, theme/themes/pxt/views/card.overrides, webapp/src/extensions.tsx, webapp/src/scriptsearch.tsx, webapp/src/sui.tsx
=> New Extensions UI

pxtlib/cpp.ts, pxtsim/embed.ts, webapp/public/controller.html, webapp/src/app.tsx
An iframe host can send a "importfile" message to load a file, similar to a drag and drop event.
Also, added "type" annotation to various messages in the sim.
=> support for iframe message to import file
