cli/cli.ts
Will use to determine more precisely where the `cannot autolaunch d-bus without x11 $display` error happens
=> Extra logging during release to debug CI builds

docs/index-ref.json
Skip a redirect step by adding www
=> Add www to microsoft.com redirect

cli/pyconv.ts
Recover when failing to convert a single FunctionDef or ClassDef.
=> recorver from unknown definitions in pyconv

docs/playground.html, docs/playground/playground-runner.html, docs/static/playground/samples/all.js, docs/static/playground/samples/field-editors/color/sample.js
- Add analytics
- Inject field editors properly
- Add color field sample to playground
=> Add a color field sample to the playground

pxtlib/util.ts, webapp/src/app.tsx, webapp/src/lang.tsx
=> Don't reload if already in the selected language

pxtsim/libgeneric.ts, webapp/src/serial.tsx
Fix for https://github.com/Microsoft/pxt-microbit/issues/839
=> Serial notation

docfiles/playground-apptrackingweb.html, docs/playground.html
=> Fix playground app tracking

pxtrunner/runner.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/841
=> Add the doc version to the doc path if it exists.

docs/static/playground/samples/README.md
Add stuff to the playground sample README, re: #4421.
=> Playground sample README update

theme/home.less
Fixes https://github.com/Microsoft/pxt-microbit/issues/857
Fixes https://github.com/Microsoft/pxt-ev3/issues/606
Fixes https://github.com/Microsoft/pxt-ev3/issues/651
=> Fix home screen close CSS so it works on light or dark images.

pxtlib/main.ts, webapp/src/app.tsx, webapp/src/package.ts
Fix for https://github.com/Microsoft/pxt-microbit/issues/845
=> Handle package load issues [v0]

pxtblocks/blocklyloader.ts, pxtcompiler/emitter/decompiler.ts
If type block for a shadowType is not found, just don't use it!!!
@riknoll can we get this in master too?
=> Check shadow type on load

docs/static/playground/playground.js
Only autorun playground with flag.
=> Only autorun playground with flag.

pxtblocks/fields/field_note.ts
Fix note field editor when it's on it's own.
Fixes https://github.com/Microsoft/pxt-adafruit/issues/598
=> Fix note field editor when it's on it's own.

docs/static/playground/samples/all.js, docs/static/playground/samples/field-editors/protractor/sample.js, pxtblocks/blocklycustomeditor.ts, pxtblocks/fields/field_protractor.ts
This field editor is specifically good for servos.
=> Protractor field editor

localtypings/pxtarget.d.ts, pxtlib/cmds.ts, webapp/src/app.tsx, webapp/src/cmds.ts
=> Troubleshoot dialog when UWP app download fails

docs/static/playground/pxt-common/pxt-helpers.js, docs/static/playground/samples/all.js, docs/static/playground/samples/basic/groups/sample.js, docs/static/playground/samples/basic/hello-world/sample.js, docs/static/playground/samples/basic/inline/sample.js, docs/static/playground/samples/basic/ordering/sample.js, docs/static/playground/samples/field-editors/color/sample.js, docs/static/playground/samples/field-editors/dropdowns/sample.js, docs/static/playground/samples/field-editors/protractor/sample.js, docs/static/playground/samples/field-editors/speed/sample.js, docs/static/playground/samples/field-editors/toggle/sample.js, docs/static/playground/samples/field-editors/turnratio/sample.js, docs/static/playground/samples/language/classes/sample.js, docs/static/playground/samples/language/create-enums/sample.js, docs/static/playground/samples/language/events/sample.js, docs/static/playground/samples/language/factories/sample.js, docs/static/playground/samples/language/functions/sample.js, libs/pxt-common/pxt-helpers.ts
Moving a bunch of field editors in common packages.
=> More samples + built-in field editors

.vscode/launch.json, cli/hid.ts, cli/nodeutil.ts
Add the target node_modules folder to the paths resolution list to fix loading node-hid, serialport.
=> native module resolution fix

docfiles/docs.html, docfiles/footer.html, docfiles/header.html, docfiles/style.css, docfiles/toc.html, docfiles/tocheader.html, docfiles/vs.css, pxtblocks/blocklyloader.ts, theme/common.less, theme/docs.less, theme/pxt.less, theme/themes/pxt/globals/site.variables
v0 cherry pick of https://github.com/Microsoft/pxt/pull/4470
=> [cherry pick] Update documentation with scrolling / print fixes

docfiles/docs.html, docfiles/footer.html, docfiles/header.html, docfiles/style.css, docfiles/toc.html, docfiles/tocheader.html, docfiles/vs.css, pxtblocks/blocklyloader.ts, pxtrunner/renderer.ts, theme/common.less, theme/docs.less, theme/themes/pxt/globals/site.variables, theme/tutorial.less, webapp/public/run.html
Updates to the documentation page fixing: 
- Scrolling issue on touch devices
- Scrolling using the scroll bar (hard to scroll), decided to stick with the browser scroll bar instead for editor and doc pages (rather than maintaining a custom scrollbar).
- Unable to print more than one page, Fixes https://github.com/Microsoft/pxt/issues/4466
- Fix IE simulator load issue
- Fix mailto not loading a new tab
- Minor styling updates
- Remove "Published By Microsoft" at bottom of page, there's already a "Powered by Microsoft MakeCode"
Tested on: 
- Edge 
- IE
- Chrome Windows and MAc
- Safari
=> Documentation page updates

docfiles/style.css
Very minor doc fix avoiding stacking navigations icons in mobile view.
=> Minor doc fix

webapp/src/notification.tsx
@abchatra we should review the efficiency of the windows banner and tone it down accordingly.
=> Windows banner tweaks

theme/home.less, theme/themes/pxt/globals/site.variables
Make the home screen close icon background a variable for EV3
=> Make the home screen close icon background a variable

.vscode/launch.json, cli/cli.ts, cli/hid.ts, cli/nodeutil.ts, cli/serial.ts, cli/server.ts, common-docs/cli.md, docs/SUMMARY.md, docs/cli.md, docs/cli/console.md
"pxt console" listens to serial / hid.
=> CLI console

webapp/src/blocks.tsx
Fixes https://github.com/playi/pxt-wonder/issues/282
=> Hide dropdown and flyout popouts when undo'ing / redo'ing

cli/cli.ts, localtypings/pxtarget.d.ts, pxtcompiler/emitter/hexfile.ts, pxtcompiler/emitter/thumb.ts, pxtlib/cpp.ts, pxtlib/emitter/assembler.ts
* add support for calling from the generated Thumb mode code into ARM mode runtime
* fix setting build engine when `variants` are used
=> Support for ARM mode runtime

pxtsim/runtime.ts, pxtsim/simlib.ts
Port over a bunch of runtime / sim support for micro:bit v1
- running time in nano seconds 
- last event value and last event time
=> Extra runtime support (ported from v0)

docs/target-creation.md, docs/targets/home-screen.md
Some basic docs on setting up home screen
=> home screen docs

cli/gdb.ts
PR: https://github.com/Microsoft/pxt/pull/4484
=> Use the local installation of openocd in place of the old one of the arduino package #4483

docs/targets/home-screen.md
=> A few edits for the home screen doc

cli/cli.ts, cli/commandparser.ts, docs/cli/checkdocs.md
Simplifying our CLI, always run with --snippets
=> remove --snippets, always do it

pxtsim/embed.ts, pxtsim/simdriver.ts
Support for simulating multiple boards with BLE
=> support for BLE packet

theme/docs.less, webapp/public/docs.html, webapp/src/container.tsx
Since the only way to reach that file is through Explorer, it always end up to JavaScript.
=> always show markdown in blocks mode

theme/blockly-core.less, theme/spriteeditor.less
=> moving css for sprite editor in pxt

pxtblocks/fields/sprite/grid.ts, pxtblocks/fields/sprite/palette.ts
=> added a max cell grid option

cli/cli.ts, pxtblocks/blocklyloader.ts, pxtlib/package.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/182
=> various pxt buildsprites fixes

pxtcompiler/emitter/emitter.ts, pxtlib/github.ts
https://github.com/Microsoft/pxt-microbit/issues/991
Never is for showRainbow
Github fix was discovered accidently
=> Fixes for neopixel in microbit v1

docs/blog/microbit/v1-beta.md
Thoughts on this clarification?
=> Clarify microbit v1 project migration

pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1019
Tested on the micro:bit and seems to work fine
=> Handle bool default parameters in shims

pxtblocks/blocklylayout.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/882
=> Fixing overlapping blocks in layout

pxtblocks/fields/field_imagedropdown.ts
maxRows option was ignored, this enforces it
=> Respect maxRows in imagedropdown

docs/defining-blocks.md
Fixes https://github.com/Microsoft/pxt-microbit/issues/1051
=> Document groups feature

webapp/src/serial.tsx
Fixes https://github.com/Microsoft/pxt-microbit/issues/675
=> Don't export data if there is none

webapp/src/app.tsx, webapp/src/core.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/625
=> Don't save the file if you cancel during project rename

webapp/src/scriptsearch.tsx
Fixes https://github.com/Microsoft/pxt-microbit/issues/1056
=> Packages -> extensions terminology

pxtblocks/blocklylayout.ts
Edge has a bug where the `drawImage()` API for canvases does not like to include embedded SVG files. Blockly uses embedded SVGs for icons so the screenshots ended up [looking weird](https://github.com/Microsoft/pxt-microbit/issues/951). As a workaround I have tried converting the embedded images into PNGs prior to the parent SVG conversion which fixed the issue for dropdown arrows but not the + - icons that appear on if/else and array blocks.
Well, I did everything I could to get those darn + and - icons to show up and nothing worked (they are defined [here](https://github.com/Microsoft/pxt-blockly/blob/develop/blocks/extensions.js) for reference). I tried unencoding them, optimizing them, etc. to no avail. The weird thing is they are very uncomplicated (circle and two rectangles) so I …
=> Fix dropdown arrows in edge screenshots

cli/cli.ts, cli/server.ts, localtypings/pxtarget.d.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxteditor/editor.ts, pxtlib/cmds.ts, pxtlib/gdbserver.ts, pxtlib/main.ts, pxtlib/service.ts, webapp/src/app.tsx, webapp/src/socketbridge.ts
* add `addCommands` callback in `cmds.ts` plugin
* support strings arguments in `//% trackArgs=...`
* add `patchCompileResultAsync` callback in editor extensions
* add `appTarget.compile.postProcessSymbols` to compute used symbols (eg to be used in `patchCompileResultAsync`)
* add TCP socket forwarding in the `pxt serve`
* add basic support for `gdbserver` (just starting the program now, but generic protocol supported)
=> support for an embedded Linux target

webapp/src/app.tsx
=> IFrame workspace fixes

webapp/src/app.tsx, webapp/src/dialogs.tsx
Fixes https://github.com/Microsoft/pxt-microbit/issues/1086
Reject promise for invalid URLs, resolve with undefined for cancel
=> Don't show error when cancel import

common-docs/faq.md
See https://github.com/Microsoft/pxt-microbit/issues/877
=> Add github.com to FAQ whitelist section

webapp/src/cmds.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1106
=> Change notif message for native host save

webapp/src/toolbox.tsx
Fixes https://github.com/Microsoft/pxt-microbit/issues/978
=> Resize editor when toolbox item is selected

pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtblocks/roundingOperations.ts, pxtcompiler/emitter/decompiler.ts, pxtlib/blocks.ts, tests/decompile-test/baselines/math_rounding.blocks, tests/decompile-test/cases/math_ops.ts, tests/decompile-test/cases/math_rounding.ts, webapp/src/blocksSnippets.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1014
=> Move rounding operations to their own block

common-docs/reference/math/random.md, webapp/src/toolbox.tsx
Fixes https://github.com/Microsoft/pxt-microbit/issues/984
=> Fix color of inline math blocks

pxtrunner/runner.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1107
Make links into not-links for printing pages or something along those lines
=> Fixing print links

pxtblocks/fields/field_imagedropdown.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1089
I hate adding browser specific code paths but here we are.
=> Removing horizontal scrolbar in Firefox

pxtlib/emitter/cloud.ts, pxtlib/github.ts
Depends on deployment of https://github.com/Microsoft/pxt-backend/pull/128
=> Use proxied /api/ghsearch

pxtlib/emitter/cloud.ts, pxtlib/github.ts
Port https://github.com/Microsoft/pxt/pull/4604 to v0
=> Port search proxy to v0

pxtlib/package.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1118
=> Use our own startsWith, which works on IE

webapp/public/controller.html
This PR fixes #4624 by making the following changes to controller.html to make it better align with the DOM:
1. Corrected a typo in the start tag of the import hex button (`buttom` --> `button`)
2. Added back the end tag of `iframe`, which is [not omissible](https://www.w3.org/TR/html/semantics-embedded-content.html#the-iframe-element)
3. Changed `&` to `&amp;`
4. Moved the `style` and `script` blocks between `head` and `body` to `head`
5. Fixed the inconsistency in how self-closing elements are closed (now all closed with `/>`)
=> HTML fixes in controller.html

pxtlib/cpp.ts, pxtlib/package.ts, pxtrunner/runner.ts, webapp/src/app.tsx, webapp/src/dialogs.tsx, webapp/src/filelist.tsx, webapp/src/workspace.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1123
=> Forgot some package -> extension terminology in some places

webapp/src/container.tsx
Fixes https://github.com/Microsoft/pxt-microbit/issues/1096
=> Open sidedocs when URL changes

webapp/src/cmds.ts
Looks like I forgot to merge this
=> Add a timeout when UWP flashing takes too long

theme/common.less
Tested on FF, IE, Edge & Chrome
Fixes https://github.com/Microsoft/pxt-microbit/issues/1113
Before / After:
=> Reduce height of editor tools on mobile

pxtrunner/runner.ts, theme/docs.less, webapp/public/docs.html
Fixes https://github.com/Microsoft/pxt-microbit/issues/954
=> Adding back button to the sidedocs

webapp/src/serial.tsx
Fix for https://github.com/Microsoft/pxt-microbit/issues/1076
=> utf8 encode CSV before downloading

pxtblocks/blocklyloader.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1029
=> Add context menu option to rename loop variable

pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, tests/blocklycompiler-test/baselines/action_event.ts, tests/blocklycompiler-test/cases/action_event.blocks, tests/blocklycompiler-test/test-library/actionEvent.ts, tests/blocklycompiler-test/test-library/pxt.json, tests/blocklycompiler-test/test.spec.ts, tests/decompile-test/baselines/action_event.blocks, tests/decompile-test/cases/action_event.ts, tests/decompile-test/cases/testBlocks/basic.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1178
and I added tests to the decompiler/compiler so that we don't break it again.
=> Bringing back support for handlers using the Action type

common-docs/reference/text/parse-float.md, common-docs/reference/text/parse-int.md
RE: #4644 
Add a bit to the _parseInt_ and _parseFloat_ pages.
=> Update the parse int/float pages

cli/cli.ts
- reuse downloaded github repoes
- use github token to avoid throtling
- detect invalid tags
- uses (brute force) regex to detect division operator
=> Various optimizations to testghpkgs command

webapp/src/toolbox.tsx
Ensure "Search..." term is translated. Fix for https://github.com/Microsoft/pxt-microbit/issues/980
=> fix untranslated search term

cli/cli.ts
=> Fix localDir in staticpkg

pxtsim/embed.ts, webapp/public/run.html, webapp/src/appcache.ts
Fix for https://github.com/Microsoft/pxt-microbit/issues/1177
=> check for appcache availability

pxtcompiler/emitter/service.ts
main.ts is missing in packages
=> Fixed main.ts lookup in allDiag 

pxtlib/gallery.ts, webapp/src/app.tsx, webapp/src/tutorial.tsx
This allows tutorials to reference github packages.
=> Tutorialwithpackages

pxtrunner/renderer.ts
See http://localhost:3232/reference/radio - cards are in order again.
=> don't reverse cards when rendering links

webapp/src/serial.tsx
Support for radio.writeReceivedPacketToSerial
=> parse {t:...,v:...} types of messages in console output

pxtblocks/blocklylayout.ts
When generating a block screenshot, reduce size of screenshot until it gets < 1Mb.
Fix for https://github.com/Microsoft/pxt-microbit/issues/1203
=> reduce screenshot size until reasonably small image is generated

package-lock.json, package.json, pxtlib/browserutils.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/db.ts, webapp/src/extensions.tsx
- Fixed parsing of UserAgent and browser version to enable WKWebview on Mac OS desktop
- Removed redundant `sandbox` attribute assignment on our iframes, which was illegal in WKWebview
- **Note:** I tested this in IE, Edge, Chrome, FF and iOS Safari, and the Sim iframe still works fine
- Sim no longer stops / resumes on visibility change if we're in an app
=> Various fixes for being embedded inside WKWebview

webapp/src/workspace.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1248
=> If a header doesn't have a target version assume it's old

docs/targets/home-screen.md
Isn't ``--snippets`` needed here too?
=> Subcategory for card types

cli/cli.ts, pxtrunner/runner.ts
The `--route` needs to be `/` not `./` as it was to get paths to css right
=> Fixes for docs in staticpkg

webapp/src/appcache.ts
Test appcache status before reloading editor
=> Avoid reload cycle (v0)

common-docs/about/editor-features.md
Add an "Explorer" section, re: https://github.com/Microsoft/pxt-ev3/issues/774
=> Add 'Explorer' section to editor features page

common-docs/javascript/operators.md, docfiles/macros.html, docfiles/style.css, docfiles/toc.html, docfiles/tocheader.html, docs/language.md, localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, theme/common.less, theme/docs.less, theme/home.less, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/projects.tsx
Required to support LEGO TOC. Probably requires refreshing pxt-backend bits
https://github.com/Microsoft/pxt-ev3/pull/786
=> Wide log and light TOC theme

webapp/src/iframeworkspace.ts, webapp/src/memoryworkspace.ts
Same as https://github.com/Microsoft/pxt/pull/4705 but to the stable branch
=> Iframe save patch to 3.22

docfiles/macros.html, docfiles/toc.html, docfiles/tocheader.html
Replace "inverted" with "tocclass" in TOC/TocHeader
=> Tocclass changes

common-docs/release-tests.md, common-docs/release-tests/extensions.md
Adding extensions test to release tests
=> adding extension to list of tests

webapp/src/worker.ts
Worker missed the Array.prototype.fill polyfill as well.
=> Adding polyfill for worker as well

common-docs/about/editor-features.md, common-docs/faq.md
RE: https://github.com/Microsoft/pxt-ev3/issues/790
=> Include notes about filename vs. project name

theme/greenscreen.less
2 small issues: flip horizontally the video stream, remove image in filelist if present
=> flip video horizontally for typically webcam scenario

webapp/src/projects.tsx
When an unknown language is displayed, the world icon really helps finding the "Language" button.
=> language icon displayed always

cli/cli.ts
Adding an array of standalone sprites (sprites in a file by themselves) and support for space between the individual sprites
=> Adding some options to build sprites

webapp/src/scriptsearch.tsx
Ooops, it's polluting the Extensions dialog.
=> don't show experiments in extensions mode

webapp/src/scriptsearch.tsx
=> Filtering --- from bundled packages

localtypings/pxtarget.d.ts, webapp/src/container.tsx
=> Enable support for hiding partner logo from the menubar while coding

pxtlib/cpp.ts
After discussion with Joe, i have changed the main.cpp template to better use fiber resources + logging various intermediate build files to console.debug
=> fixed main.cpp

webapp/src/filelist.tsx
Helps identifying versioning issues. Only present for github packages.
=> display github packge version number in explorer

webapp/src/scriptsearch.tsx
Learn more opens the package readme page.
=> show docs page in extension dialog

webapp/src/scriptsearch.tsx
=> always show all boards

webapp/src/workspace.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1345
Looks like a long standing bug that the new upgrade logic uncovered
=> Fix the removal of targetversion when importing shared projects

localtypings/pxtparts.d.ts, package-lock.json, pxtsim/allocator.ts
Allow various APIs to instantiate the same part. Need to support microbit / servos.
=> Support for multiple instantions of part

pxtsim/simlib.ts
Modifying our iframe code is not worth supporting webmidi.
=> Don't use WebMIDI

pxtsim/runtime.ts
Just a helpder to restart the simulator (adds a 500ms delay to avoid issue when reseting in a loop)
=> helper to restart runtime

webapp/src/projects.tsx
Don't rename project is empty.
=> handle empty project name

theme/home.less, theme/themes/pxt/views/card.overrides
(reduce size of cards and font)
=> Optimize mobile view space

Jakefile.js, docfiles/apptracking.html, docfiles/tracking.html, package-lock.json, package.json, webapp/public/release.manifest
Load ai.0.js from same domain to avoid ad blockers. Also fixes update issues when ai.0.js is blocked. Requires adding ai.0.js to doccdn + testing.
=> loading ai hosted on makecode.com

theme/greenscreen.less
Show web cam in the back of the full screen simulator...
=> Full green screen

localtypings/pxtarget.d.ts, package-lock.json, package.json, pxteditor/experiments.ts, pxtlib/tsconfig.json, pxtlib/webble.ts, webapp/src/cmds.ts, webapp/src/container.tsx
Allows to pair to a device via WebBLE and proxy UART message into the console.
=> WebBLE UART

webapp/src/app.tsx
If we're in an app, don't worry about page visibility check.
=> Fix page visibility check in app.

webapp/src/editortoolbar.tsx, webapp/src/simtoolbar.tsx
This is a preparation of the pairing button. It is a UI change that should be shipped with micro:bit - pairing button will come later.
* only impacts "computer" size
=> move minimize simulator button under simulator

docs/extensions/versioning.md
A start on adding a note for extension upgrades as related to #4723.
Not really sure what the total scenarios are here so comments welcome.
=> Extension version upgrade note

pxtblocks/fields/field_ledmatrix.ts
Update led matrix field editor so it works on touch devices.
The main idea here is instead of registering a mouseenter event for each led and toggle it to the state of the initial mousedown led, we set a handler on the entire area and use document. elementFromPoint to the current target of our X Y position. If we get a hit, we apply our logic. 
Tested on Desktop (Chrome, Safari, Firefox, IE and Edge), IOS and Android.
=> Update led matrix field editor so it works on touch devices

theme/toolbox.less, webapp/src/toolbox.tsx
=> Fix up RTL support in the monaco and blockly toolboxes

pxteditor/editor.ts, webapp/src/app.tsx
Add helper to show a simple dialog (for extensions)
=> Show modal dialog

webapp/src/filelist.tsx
Fix for https://github.com/Microsoft/pxt-microbit/issues/1421
=> don't show more than 7 character of github tag

theme/blockly-core.less
so it doesn't affect other minecraft menus.
=> Make context menu changes limited to the context menu and not all menus

cli/cli.ts
Update checkdocs to scan nested summary files.
=> scan for all summaries

webapp/src/app.tsx
Was guarded by enableTrace rather debugger.
=> bring back debug toolbar

theme/print.less, webapp/src/app.tsx
=> fix for toggle print

webapp/src/compiler.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1449
=> Load Blockly before trying upgrades

webapp/src/carousel.tsx
Fixes https://github.com/Microsoft/pxt-microbit/issues/1426
Tested in Edge, Firefox, Chrome, and IE
=> Fixing the carousel in RTL languages

webapp/public/siminstructions.html, webapp/src/make.tsx
=> use tsx for the make dialog

localtypings/pxtpackage.d.ts, pxtlib/package.ts, webapp/src/scriptsearch.tsx
Sort by: 1 core, 2 beta, 3 weight for core packages.
=> Better sorting of packages in search

common-docs/blocks-embed.md, webapp/src/marked.tsx
Don't render the "package" fenced code area
=> remove "package" fenced code section

theme/toolbox.less
- Bring back the search bar in the mobile view. 
- Fix issue with horizontal toolbox scrollbars on Firefox and Safari.
=> Toolbox CSS fixes

webapp/public/codeembed.html
Use config info when available.
=> use config to load iframe renderer

webapp/src/app.tsx
=> Don't create a new project when the share page reloads (#4889)

webapp/public/codeembed.html
Porting codeembed fix: https://github.com/Microsoft/pxt/pull/4887
to stable4.1 branch
=> Port fix for codeembed to stable4.1

webapp/src/notificationbanner.tsx
=> Updating the banner to reflect october 26th

webapp/src/app.tsx
Fixes https://github.com/Microsoft/pxt-arcade/issues/239
=> Show the choose hardware dialog in the share page

pxtrunner/runner.ts
* Fix blocksembed, null exception
Cherrypick into master: https://github.com/Microsoft/pxt/pull/4909
=> Fix blocksembed (#4909)

docs/extensions/versioning.md
Is 'freeze' and 'lock to' the same idea?
=> Few edits to freeze note

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/github.ts
Cherry pick pinned releases support
=> V0 pinned releases

cli/cli.ts, pxtlib/github.ts, pxtlib/semver.ts
=> testghpkgs improvement

pxtlib/initprj.ts, webapp/src/projects.tsx
( also added .header.json in template .gitignore )
=> Improved emojis animation

pxtlib/blocks.ts
=> Fixed the typo as raised in #4919

cli/cli.ts, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, webapp/src/codecard.tsx, webapp/src/projects.tsx
Let's keep discussing this one. 
* do we ever want to show tags on the cards?
* do we need special tags for number values like "duration", "age", etc..
=> Tags in card details

pxtlib/commonutil.ts
=> gard rlf/lf

cli/cli.ts
lf strings are not picked up in target editor/fieldeditors sections
=> scan editor/fieldeditors in target for strings

package-lock.json, package.json, pxtlib/webble.ts
=> BLE HF2 service

docs/targets/home-screen.md, docs/writing-docs/tutorials.md
Undust to match latest pxt system
=> Tutorial docs update

package-lock.json, pxtrunner/renderer.ts
Render logic had a promise that never returns, causing infinite spin of sidedoc
=> Fix promise never returning in render logic

docs/targets/home-screen.md, docs/writing-docs/tutorials.md
Some edits for the tutorials page.
RE: #4935
=> Edits for authoring tutorials page changes

cli/cli.ts
See https://github.com/Microsoft/pxt-microbit/issues/1558
=> pxt-core@latest now points to latest master (#4952)

docs/blog.md
Add CS ED Week post back into main blog page.
RE: https://github.com/Microsoft/pxt/issues/4891#issuecomment-434434394
=> Unhide CSEdWeek blogpost

theme/greenscreen.less, webapp/src/greenscreen.tsx
=> flip webcam stream depending on cam position

webapp/src/scriptsearch.tsx
We may enable this scenario later.
=> don't allow local github projects as core packages

webapp/src/editortoolbar.tsx, webapp/src/projects.tsx, webapp/src/pxtjson.tsx, webapp/src/scriptsearch.tsx, webapp/src/share.tsx, webapp/src/sui.tsx, webapp/src/toolbox.tsx
Disable autoComplete, autoCorrect, autoCapitalize and spell check for all search and file name input fields.
=> Disable autocomplete for search and name fields

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/scriptsearch.tsx
Move "closeIcon" as a state variable in scriptsearch.
=> add explicity closeIcon state

localtypings/pxtparts.d.ts, pxtsim/visuals/genericboard.ts, webapp/public/boarddesigner.html
Makes it easier to genreate a board.json. Just copy paste the fritzing SVG.
=> Board designer

webapp/public/boarddesigner.html, webapp/src/carousel.tsx
=> board designer improvements

webapp/src/db.ts
Ignore 409 errors coming from PouchDb.
=> handle409 specially

cli/cli.ts, common-docs/release-tests/extensions.md, docs/cli/login.md
Doesn't seem to work anymore and makes less sense now anyways.
=> Removing "pxt login pxt"

webapp/src/editortoolbar.tsx
Just going with - / + which seems to be the norm.
=> swap zoom buttons

cli/buildengine.ts, pxtsim/runtime.ts, pxtsim/simlib.ts
This allows for multi-channel sounds in the sim
=> Add AudioContextManager.playInstructionsAsync

cli/cli.ts
Much faster pxt serve for maker
=> support for ``pxt serve --rebundle``

pxtsim/runtime.ts
Fixes https://github.com/Microsoft/pxt-adafruit/issues/863
=> Allow for recursive invocation of runtime loop

cli/cli.ts, cli/gdb.ts, docs/cli/gdb.md
Arduino folder is now "Arduino15" on Windows.
=> gdb add search path for windows

pxtsim/embed.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts
Add a special simulator message that needs to be broadcasted between simulator frames.
=> Broadcast msg between simulators

pxtsim/allocator.ts, pxtsim/visuals/boardhost.ts, pxtsim/visuals/breadboard.ts, webapp/src/simulator.ts
+ better handling of invalid parts definitions. Fixes for maker.
=> Better positioning of round pins

webapp/src/greenscreen.tsx
Integration of https://github.com/Microsoft/pxt/pull/5045
=> ios greenscreen (master)

pxtblocks/blocklylayout.ts, pxtrunner/runner.ts
Fix for https://github.com/Microsoft/pxt-microbit/issues/1683
=> Fix for printing local packages

cli/cli.ts, cli/gdb.ts
It shows some info on console and also creates a JSON file - this is to be processed with some tools later.
=> Add pxt heapdump command

pxtsim/instructions.ts, pxtsim/visuals/boardhost.ts, pxtsim/visuals/genericboard.ts
Use the gpiomap to lookup pins in breadboarding.
=> Pin lookup fix

cli/gdb.ts
Double click on dump.dgml to visualize.
=> add DGML output

docs/extensions/github-authoring.md
@abchatra we have github in all editors now, right?
=> Update the roll-out section

cli/gdb.ts, pxtcompiler/emitter/backbase.ts
This is in support of https://github.com/Microsoft/pxt-common-packages/pull/540
* update `gdb.ts` heap dumping with new layouts
* update lambda trampoline code
=> use GC heap for almost all allocations

cli/cli.ts, pxtlib/github.ts
It was a nice experiement but it hasn't materialized as useful.
=> remove support for gists in cli

cli/cli.ts
Also rebundled before "builddaldts"
=> add --clean support in build

cli/cli.ts, pxteditor/editorcontroller.ts, pxtlib/analytics.ts, pxtlib/main.ts, pxtlib/service.ts
Reports any localization issue through app insight so that we get visibility on this. Needs cherry-picking into micro:bit as hot fix.
Reports a single event where individual translation strings are metrics. @abchatra we need a dashboard for this.
=> Report localization errors

pxtlib/browserutils.ts, webapp/src/share.tsx, webapp/src/sui.tsx
Move popup into browser utils and make it center the popup in the window.
=> Improve popup placement

pxtsim/utils.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/432
=> polyfill for UInt*Array.reverse

pxtblocks/fields/sprite/sidebar.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/247
=> set title on palette rects

pxtblocks/blocklycustomeditor.ts, pxtblocks/fields/field_position.ts, theme/fieldeditors.less
Needs to be in pxt as sprite apis are in common.
=> Field position to support sprites

pxtblocks/fields/field_position.ts
=> don't put lines beyond canvas

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
Just another JS default api mssing
=> support for array.find

pxtblocks/fields/field_position.ts, theme/fieldeditors.less
Added an icon for the going into the crosshair mode. 
Added a slider with screen width / height ranges.
Note: only show the crosshair when the simulator is around.
=> Fix up the field position with a slider

webapp/src/monaco.tsx
Fixes https://github.com/Microsoft/pxt-arcade/issues/458
=> Fix exception when folding nothing

pxtblocks/fields/field_position.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/465
=> Fixing unbind event in position picker

pxtblocks/blocklyloader.ts, pxtblocks/composablemutations.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/358
Fixes https://github.com/Microsoft/pxt-arcade/issues/357
Fixes https://github.com/Microsoft/pxt-ev3/issues/739
Fixes https://github.com/Microsoft/pxt-ev3/issues/694
Fixes https://github.com/Microsoft/pxt-ev3/issues/693
=> Various expandable blocks fixes

pxtblocks/blocklyloader.ts
I forgot to add this to the reporters PR
=> Set reporters to correct color

localtypings/pxtarget.d.ts, pxtlib/main.ts, tests/format-test/formatrunner.ts, webapp/src/projects.tsx, webapp/src/workspace.ts
=> pre-caching of bundledsvg expensive in maker

pxtsim/allocator.ts, pxtsim/instructions.ts, pxtsim/visuals/boardhost.ts, pxtsim/visuals/wiring.ts
More error handling on invalid pin mappings.
=> hardening of breadboard wiring

theme/serial.less
Hide console preview button in share full sim page.
=> hide serial preview button in full sim

cli/cli.ts
=> rebuild sim in rebundle

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
Our support for string/array is rather spotty. Here is split.
=> String.split

localtypings/pxtparts.d.ts
Support for on-board buttons in simulator
=> Buttons parts

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/516
=> array.fill support

pxtsim/visuals/boardhost.ts
=> keep breadboard when forced

pxtblocks/fields/field_position.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/521
=> Clear position picker selectorDiv after close

cli/cli.ts
I have never gotten the C++ build to work correctly for arcade (cloud or local), so I use the rebundle flag pretty heavily to avoid the issue. However, the rebundle flag only builds the bare minimum of the target and the simulator; it skips all editor extensions, common-sim, etc.
In practice, that means you can only use rebundle after a succesful native build or else the editor will break because the other files are missing. I'm uniting the logic a bit so that all the rebundle flag does in pxt serve is prevent the C++ build.
=> Fixing arcade build for those who can't build the C++

webapp/src/editortoolbar.tsx, webapp/src/simtoolbar.tsx
Fixes https://github.com/Microsoft/pxt-arcade/issues/493
=> Fixing reversed run button tooltips

webapp/src/app.tsx
Fix for https://github.com/Microsoft/pxt-maker/issues/136
=> check editorstate is present

pxtblocks/blocklyimporter.ts
Meta comment in typescript allow to highlight block at decompilation time. Allows to highlight blocks in tutorial steps:
````
// @highlight
game.onUpdate(function () {
})
````
=> // @highlight highlights block

localtypings/pxtarget.d.ts, package-lock.json, pxtblocks/blocklyloader.ts, pxteditor/editor.ts, pxtlib/browserutils.ts, pxtlib/main.ts, pxtsim/embed.ts, webapp/src/app.tsx, webapp/src/screenshot.ts, webapp/src/simtoolbar.tsx
This PR adds a "screenshot" button in the sim toolbox (enabled for arcade), which uses the PNG encoding feature.
=> PNG Phoenix

webapp/src/app.tsx, webapp/src/dialogs.tsx
The current chrome of the screenshot is white so it blends into the dialog. It'll be fixed with a new chrome.
* this opens after saving
* specify all supported extensions in import + hint to teach users about drag and drop
=> basic dialog when saving

theme/sidedoc.less
Fixes https://github.com/Microsoft/pxt-arcade/issues/524
=> Fix issue with sidedoc css

pxtlib/sprite-editor/tools.ts
Interpolate between touch/mouse drag events for a smoother painting experience in the sprite editor. 
Reason for changes: when painting an image, if you press and drag it's likely to run into the issue where not enough drag events are triggered to set each pixel that you drag the brush over.
In order to account for this, we interpolate between the xy coordinated of subsequent drag events. 
See previous and new screen grabs: (Painting a "square")
Previous: 
New:
=> Interpolate for smoother painting experience

pxtlib/service.ts, webapp/src/scriptmanager.tsx, webapp/src/workspace.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/572
=> Fix duplicate/delete script manager when searching

pxtcompiler/emitter/emitter.ts, tests/compile-test/lang-test0/13actions.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/535
=> Clear loop variables on each iteration

webapp/src/projects.tsx
Better support for links in HW dialog.
=> bring back links in hw selection screen

localtypings/pxtarget.d.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/simulator.ts
By default, autoRun does not apply to light mode anymore. Can be overriden by autoRunLight.
=> diable autorun in light mode + flag to force

pxtcompiler/emitter/emitter.ts
=> Try to avoid stack overflow

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/tagged_templates_args_with_shadow.blocks, tests/decompile-test/cases/tagged_templates_args_with_shadow.ts, tests/decompile-test/cases/testBlocks/templateStrings.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/488
=> Respect shadow block setting for tagged templates

localtypings/pxtarget.d.ts, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/share.tsx, webapp/src/simtoolbar.tsx
Support for keyboard shortcut for screenshots + hint in share dialog (P key in arcade, configured in pxtarget) + Edge fix.
=> Screenshot shortcut

pxtsim/simdriver.ts, webapp/src/app.tsx
fix for https://github.com/Microsoft/pxt-arcade/issues/637
fix for https://github.com/Microsoft/pxt-arcade/issues/634
=> fast path for reset button

theme/common.less
Fix for https://github.com/Microsoft/pxt-arcade/issues/650
=> fix corners on simulator

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
=> compliant array slice

pxtlib/sprite-editor/canvasGrid.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/567
Broke it when I redid the touch events for the Monaco field editor.
=> Fixing touch event regression in sprite editor iOS

webapp/src/projects.tsx
It's getting crowded in the hardware dialog.
=> use large dialog for picking hardware

webapp/src/simtoolbar.tsx
Disable button when simulator is not running.
=> Allow screenshot if simulator is running

webapp/src/workspace.ts
Make sure to have a description so that discourse.org renders our link.
=> Default description og

docs/blog/arcade/01-18-2019.md
=> adding links to guides

docs/labs.md
labs page is referenced by Microsoft site.
=> Moving maker to the top

webapp/src/app.tsx
Return to main.js from serial view.
=> check that there's a "main.blocks" before returning

pxteditor/experiments.ts, pxtsim/visuals/boardhost.ts, webapp/src/app.tsx
Mostly a refactoring of the screenshot feature to benefit other editors.
=> Breadboard sim support

pxtsim/libgeneric.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1803
Thank you @xuefengedu for reporting and investigating the issue!
Note, once this PR is merged I need to cherry-pick this over to the micro:bit stable branch
=> Fix Math.idiv in the simulator

pxtlib/sprite-editor/bitmap.ts, pxtlib/sprite-editor/canvasGrid.ts, pxtlib/sprite-editor/spriteEditor.ts, theme/spriteeditor.less
Fixes https://github.com/Microsoft/pxt-arcade/issues/665
Fixes https://github.com/Microsoft/pxt-arcade/issues/664
Fixes https://github.com/Microsoft/pxt-arcade/issues/565
Fixes https://github.com/Microsoft/pxt-arcade/issues/557
=> A few sprite editor fixes

webapp/src/screenshot.ts
Render logo in stead of blue frownie face.
=> use logo if possible if failing to render screenshot

pxtlib/main.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/container.tsx, webapp/src/hidbridge.ts, webapp/src/share.tsx
Required fixes to use saveAsPNG in maker, without hw variants.
=> check that hw variants is active

cli/cli.ts, pxteditor/editor.ts, theme/serial.less, webapp/src/app.tsx, webapp/src/package.ts, webapp/src/serial.tsx
When switching to console view, don't stop the simulator.
=> Console view should not stop

cli/cli.ts, pxtsim/allocator.ts, pxtsim/visuals/boardhost.ts, pxtsim/visuals/wiring.ts
Better not show the part that showing incomplete wiring.
=> Don't show breadboard parts if all wires cannot be routed

localtypings/pxtarget.d.ts, pxtcompiler/emitter/emitter.ts, pxtlib/hf2.ts
Microbit has different images.
=> Support different tag on Image objects for microbit

theme/functionsdialog.less, webapp/src/createFunction.tsx
Fixes https://github.com/Microsoft/pxt-arcade/issues/739
Fixes https://github.com/Microsoft/pxt-arcade/issues/743
Fixes https://github.com/Microsoft/pxt-arcade/issues/744
=> New function editor layout

docs/defining-blocks.md
=> Add more sections to 'Defining blocks'

common-docs/javascript/types.md
Integration of doc fix in v4.
* Document floating point support
* add a few small edits
* spell notation
=> Document floating point support (#5228)

cli/cli.ts
Handles partial urls, youtube videos, learn more, buy, etc...
=> better auto generation of summaries

pxtblocks/codecardrenderer.ts, pxtlib/service.ts
When imageUrl is available, ignore youtube thumbnail image.
=> Youtube thumbnails in cards

common-docs/offline.md
RE: https://github.com/Microsoft/pxt-microbit/pull/1853
=> Update 'offline' page

pxtcompiler/emitter/emitter.ts, tests/compile-test/lang-test0/50indexedtypes.ts, tests/compile-test/lang-test0/pxt.json
Fixes https://github.com/Microsoft/pxt-microbit/issues/1848
=> Allow type index declarations

pxtsim/runtime.ts
=> make post screenshot arg optional

cli/cli.ts, localtypings/pxtarget.d.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/thumb.ts, pxtlib/emitter/assembler.ts, webapp/src/compiler.ts
WIP
@riknoll any clue if caching type on Node is a good idea? `(node as any).typeOverride = r`
=> Compiler perf improvements

pxteditor/experiments.ts, pxtlib/main.ts
Ensure that target theme gets reloaded after setting experiment values.
=> ensure that experiments reload the apptarget theme

cli/cli.ts, pxtlib/package.ts, pxtlib/util.ts, pxtrunner/runner.ts, webapp/src/compiler.ts, webapp/src/filelist.tsx, webapp/src/package.ts, webapp/src/workspace.ts
Add some resiliency when loading projects with broken pxt.json or invalid dependencies.
=> Resilient loader

webapp/src/simtoolbar.tsx
Fix for https://github.com/Microsoft/pxt-adafruit/issues/748
=> show mute even in tutoriial mode

theme/pxt.less, theme/webusb.less, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/coretsx.tsx, webapp/src/scriptmanager.tsx, webapp/src/webusb.tsx
=> move usb pairing dialogs to tsx

localtypings/pxtarget.d.ts, pxteditor/experiments.ts, webapp/src/cmds.ts
Make automatic webusb download an experiment.
=> Webusb download experiment

webapp/src/pxtjson.tsx
In the project settings, collect all optionalConfig (e.g. BLE pairing profiles --> C++ defines) from dependencies when checking if a config is enable (this is what happens in the build).
Also, don't render pxtjson.tsx view when not visible.
=> properly handle optional configs

docs/static/playground/playground.js
Looks like monaco.Promise is no more.
=> fix for playground

webapp/src/app.tsx
Fixes: https://github.com/Microsoft/pxt-microbit/issues/1560
=> Show error if hex file cannot be read

pxtlib/browserutils.ts
=> Revert "Fix browser detection of Firefox on Mac"

webapp/src/app.tsx, webapp/src/core.ts, webapp/src/coretsx.tsx
We are now use React for all our modal dialogs.
=> removing ability to use htmlBody

cli/cli.ts
This fixes the broken generation of dal.d.ts
=> fixing leaked promise

webapp/src/container.tsx
Print to PDF does not work in IE.
Fix for https://github.com/Microsoft/pxt/pull/5378
=> hide print in IE

webapp/src/app.tsx
When autoRun is false, respect it and don't run the simulator at least once.
=> respect autorun flag

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/mb_play_note.blocks, tests/decompile-test/cases/mb_play_note.ts, tests/decompile-test/cases/testBlocks/mb.ts
The curse of the enum returns!
Fixes https://github.com/Microsoft/pxt-microbit/issues/1900
=> Make sure an argument is of an enum type before making it a field

localtypings/pxtarget.d.ts, pxtblocks/fields/field_sprite.ts, pxteditor/editor.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/monacoFieldEditor.ts, pxtlib/sprite-editor/bitmap.ts, webapp/src/app.tsx, webapp/src/monaco.tsx, webapp/src/monacoFieldEditorHost.ts
Support for monaco field editors in ptyon
=> Py field editors

webapp/src/share.tsx
Adding check for thumbnail
cherry-pick from stable5.5
=> Don't run simulator if thumbnail is not requested (#5386)

docfiles/pxtweb/cookieCompliance.ts
* Don't show the cookie banner when noCookieBanner=1 is passed
* Check that we're also in an iframe
=> Don't show the cookie banner when noCookieBanner=1 is passed (#5211)

webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/simtoolbar.tsx, webapp/src/srceditor.tsx
This goes into the python branch but could be integrated somewhere else.
=> Debug from python

pxtsim/simdriver.ts, svgicons/videoplay.svg, theme/common.less
Cherry pick of https://github.com/Microsoft/pxt/pull/5404 for arcade release
=> Improving the stopped overlay for the simulator (#5404)

pxtsim/langsupport.ts
Needed for arcade release. Thanks @jwunderl
=> ability to set keys in simulator (#5403)

webapp/src/simtoolbar.tsx
Enabling debug mode button when autorun is disabled
=> fixing dbg button behaviour with autorun disabled

webapp/src/simtoolbar.tsx
=> fixing dbg button behaviour with autorun enabled

localtypings/pxtarget.d.ts, pxteditor/workspace.ts, webapp/src/app.tsx, webapp/src/codecard.tsx, webapp/src/projects.tsx
(not final design, but small fixes to current story)
=> use icons instead of text

webapp/src/carousel.tsx
Fix carousel bug from Microsoft/pxt-microbit/issues/1901
=> Fix bug with carousel skipping projects on scroll

cli/cli.ts
Prepend files in /editor/prepend automatically. This fixes the microbit editor extension build which did not bundle dapjs.js.
=> automatically prepend files in /editor/prepend

pxtsim/runtime.ts
Fixes https://github.com/Microsoft/pxt-microbit/issues/1973
=> Fixing slowmo

docs/blog/microbit/2019-beta.md
Convert to string to Convert to Text
=> Update the API reference in blog

tests/blocklycompiler-test/baselines/logic_non_numeric.ts, tests/blocklycompiler-test/cases/logic_non_numeric.blocks, tests/blocklycompiler-test/test.spec.ts, tests/decompile-test/baselines/logic_string_comparisons.blocks, tests/decompile-test/cases/logic_string_comparisons.ts
Was requested right after https://github.com/Microsoft/pxt/pull/5443 got merged
=> Add some compile / decompile tests for string comparisons

localtypings/pxtarget.d.ts, theme/common.less, webapp/src/share.tsx
Add optional "share to forum" button on share page. Probably need a better icon and text.
Used with https://github.com/Microsoft/pxt-arcade/pull/880
=> Share to discourse

pxtpy/ast.ts, pxtpy/converter.ts, tests/python/game.py
```python
def player_damage(sprite, other_sprite):
scene.camera_shake(4, 500)
other_sprite.destroy(effects.disintegrate)
sprite.start_effect(effects.fire, 200)
info.change_life_by(-1)
sprites.on_overlap(SpriteKind.Player, SpriteKind.Enemy, player_damage)
if False:
player_damage(ship, ship)
def enemy_damage(sprite:Sprite, other_sprite:Sprite):
sprite.destroy()
other_sprite.destroy(effects.disintegrate)
info.change_score_by(1)
sprites.on_overlap(SpriteKind.Projectile, SpriteKind.Enemy, enemy_damage)
def shoot():
projectile = sprites.create_projectile_from_sprite(sprites.food.small_apple, ship, 0, -140)
projectile.start_effect(effects.cool_radial, 100)
controller.A.on_event(ControllerButtonEvent.PRESSED, shoot)
def spawn_enemy():
projectile = …
```
=> py2ts: inline callback definitions when possible

webapp/src/share.tsx
=> shared project: hide "forum", use smaller image

pxtlib/sprite-editor/spriteEditor.ts
fixes https://github.com/Microsoft/pxt-arcade/issues/863
=> Change default color in sprite editor

webapp/src/monaco.tsx
Fix for https://github.com/Microsoft/pxt-microbit/issues/2008 . This was introduced with javascript tutorials.
=> fix monacto toolbox when no filters

common-docs/faq.md, docs/translate.md
Add a core file summary and a couple of other notes.
RE: #5477
=> Add a file summary to 'translate' page

common-docs/translate.md
Update common translate page with override sections for targets.
=> Update common translate page

localtypings/pxtarget.d.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/service.ts, pxtlib/service.ts
=> Don't treate eg.:... as default parameters

pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/TODO_callback_num_args.ts, tests/runtime-trace-tests/cases/callback_names.ts, tests/runtime-trace-tests/cases/callback_num_args.ts
From the tutsize branch until we merge.
=> Integrating python changes to master

docfiles/offline-app-template.html
Refactored to load version information from targetconfig. (no impact on microbit)
=> Offline app template

localtypings/pxtarget.d.ts, pxteditor/experiments.ts, webapp/src/app.tsx, webapp/src/compiler.ts, webapp/src/debuggerCallStack.tsx, webapp/src/debuggerToolbar.tsx, webapp/src/monaco.tsx, webapp/src/monacoDebugger.ts
Adding an experiment for debugging extensions and libs! Only for TypeScript of course.
@jamesadevine you might find this useful...
=> Monaco debugger part 4 (libs debugging)

pxtcompiler/emitter/service.ts, theme/common.less, theme/docs.less, theme/monaco.less, theme/themes/pxt/globals/zindex.variables, webapp/src/marked.tsx, webapp/src/simtoolbar.tsx, webapp/src/tutorial.tsx
Various tutorial unrelated fixes.
=> Fixes from tutorial branch (unrelated to UI changes)

cli/pyconv.ts
Collect missing language construct in our compilers
=> collect todo in python code

cli/gdb.ts, pxtsim/simlib.ts
Add queuePlayInstructions to audio context manager
Also, fixes for gdb on Windows
=> Add queuePlayInstructions to audio context manager

cli/cli.ts
Sometimes the build is broken but still need a private build.
=> support rebundle only for upload

pxtpy/converter.ts, pxtpy/pydecompiler.ts
Every missing feature in the py2ts, ts2py should be logged.
=> adding python.todo in online editor

pxtcompiler/emitter/emitter.ts
=> Support for | and + in namespace config { ... }

docs/extensions/naming-conventions.md
Add some edits to the 'Naming Conventions` page.
=> Edits for ext naming conventions

pxtsim/simlib.ts
Start idling when someone listen on idle event.
=> Idle sim fix

pxtcompiler/emitter/backbase.ts
fixes https://github.com/microsoft/pxt-arcade/issues/968
=> Fix arr[undefined]

webapp/src/monaco.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/205
=> Don't scroll monaco editor while scrolling flyout

cli/cli.ts, pxtlib/initprj.ts, webapp/src/workspace.ts
Ensure that all the auxilliary files (like .gitignore) are put in the generated github repo.
=> Generate all files for 'github create'

theme/common.less, webapp/src/tutorial.tsx
Update dark theme CSS for tutorial 'See More' and simulator collapse
=> Update dark theme CSS for tutorial 'See More' and simulator collapse

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts, pxtsim/libgeneric.ts
Adds the previously unimplemented String.isEmpty function and block to ts
Fixes microsoft/pxt-microbit#2048
=> Added isEmpty for strings

Jakefile.js
Don't copy media folder to playground on jake
=> Don't copy media folder to playground on jake

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, theme/tutorial.less, webapp/src/app.tsx, webapp/src/tutorial.tsx
Latest: https://makecode.adafruit.com/app/b65df62c3b3e2df682137ed0503b7e7bb21edae9-052b95a621
=> Update tutorial hint display

pxtsim/utils.ts, webapp/src/worker.ts
=> polyfills for Object.assign

cli/cli.ts, docfiles/style.css, docs/writing-docs/macros.md, pxtlib/tutorial.ts, pxtrunner/renderer.ts, webapp/public/docs.html
Support for a "ghost" code snippet. It is not visible but the blocks are still used in the static analysis of the tutorial.
=> Tutorial hiddencode

docs/writing-docs/macros.md
Do some updates to the 'macros' page.
=> Update edits to the 'macros' page

cli/cli.ts
Don't try to bundle .hex file with SKIP content.
=> Skip SKIP hex

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/cpp.ts, pxtlib/package.ts
This is for https://github.com/microsoft/pxt-vm-built
=> Add 'pxt exportcpp'

package.json
Fixes an issue running buildsprites command.
=> Upgrade pngjs to 3.4.0

pxtlib/package.ts, pxtrunner/runner.ts, webapp/public/run.html
test build https://arcade.makecode.com/app/29d27961ccb3131e9610b34135e425c8d5f198e6-b794a1b51f
=> VM support in run.html + small fixes

webapp/src/app.tsx, webapp/src/carousel.tsx, webapp/src/container.tsx
Switches the left right chevrons when an RTL language is being used.
Fixes Microsoft/pxt-microbit#2095
=> Rtl carousel

webapp/src/container.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/1707
Electron doesn't have the UI to support webusb: https://github.com/electron/electron/issues/14545
=> Don't show pair device in electron

pxtcompiler/emitter/backvm.ts, pxtlib/cpp.ts
supports https://github.com/microsoft/pxt-common-packages/pull/856
=> support 32 bit machines in VM

theme/highcontrast.less
Ensure "MyProject" is still visible on hover + high contrast.
=> fix for https://github.com/microsoft/pxt-microbit/issues/1891

theme/tutorial.less, webapp/src/tutorial.tsx
microsoft/pxt-microbit/issues/2080
microsoft/pxt-microbit/issues/2086
microsoft/pxt-adafruit/issues/1056
=> Tutorial overflow, event listener fixes

pxtblocks/blocklycompiler.ts, pxtlib/service.ts
Two things:
* Fixing the logging for translation errors.
* Adding more information to the top exception (@abchatra qualified name and filename should be fine to log right?)
=> Telemetry fixes

webapp/src/app.tsx
cherry picking https://github.com/microsoft/pxt/pull/5624 to master
=> do not issue error when cancelling github import dialogue (#5624)

pxteditor/editor.ts, pxtlib/util.ts, pxtrunner/runner.ts, pxtsim/embed.ts, theme/tooltips.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/hinttooltip.tsx, webapp/src/tutorial.tsx
- Timer resets on blockly events (block moved, etc)
- Avatar and tooltip click will open the hint
- Tooltip stays visible for two seconds, then hides
https://makecode.microbit.org/app/bb1c11d932bf519575143f3bfef42c2c2aa1a844-11baa0cb0c
=> Tutorial tooltip appears & animates after 30 seconds of inactivity

pxtsim/allocator.ts, pxtsim/visuals/boardhost.ts
Fix for https://github.com/microsoft/pxt-microbit/issues/2088
=> restore logic to hide breadboard

common-docs/blocks/math.md
Include more description for negative numbers in **round**, **ceil**, **floor**, and **trunc**.
RE: #5638
=> Add some negativity to the math value descriptions

pxtlib/tutorial.ts, webapp/src/app.tsx, webapp/src/tutorial.tsx
Use all text up to first line of code/image as tutorial card text, use everything after as 'hint'.
https://makecode.microbit.org/app/3597c77c8a08a96063ac0b4d20a4f5ba008eea1a-605de7d11d
=> Use all text up to first line of code/image as tutorial card

pxtsim/utils.ts, webapp/src/worker.ts
Fix for https://github.com/microsoft/pxt-microbit/issues/2151
=> startsWith withpolyfill

pxtlib/tutorial.ts, theme/tutorial.less, webapp/src/tutorial.tsx
+ small CSS fix for tooltip
microsoft/pxt-microbit/issues/2148
microsoft/pxt-microbit/issues/2116
=> Edge click fix, regex update

webapp/src/tutorial.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/2170
=> make sure hintOnClick gets removed from document

webapp/public/run.html, webapp/src/tutorial.tsx
https://makecode.microbit.org/app/6d71e491e0407cd432fef4612c37e05c2a25332c-45c8af98a8
Addresses:
microsoft/pxt-microbit/issues/2168
microsoft/pxt-microbit/issues/2169
=> Tutorial hint state cleanup for unplugged, reset state at each step

pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/plaintsc.ts, pxtcompiler/emitter/vm.ts, pxtcompiler/simpledriver.ts, pxtlib/cpp.ts
* store name and time in vm images
* apply TS patches in simpledriver
* small bugfixes for vm
=> update vm output format to support image caching

theme/tutorial.less, webapp/src/tutorial.tsx
=> Hide avatar in mobile tutorial

scripts/optimize-images.sh
Tweak image processing script.
=> jpeg -> jpg

webapp/src/app.tsx, webapp/src/draganddrop.ts
Fix for https://github.com/microsoft/pxt-arcade/issues/1038
=> Support for PNG uri drag and drop

pxtsim/allocator.ts
Removes this benign but annoying message
=> reduce verbosity of breadboard messages

common-docs/faq.md
Add info about offline apps to the FAQ entry about offline use. Comes by way of the fine suggestion from @microbit-rosslowe.
RE: https://github.com/microsoft/pxt-microbit/issues/2180
=> Note availabilty of offline apps in FAQ

theme/print.less
Print only prints the first page. This fixes it.
=> fix single page print

cli/cli.ts, docs/cli/login.md, package.json
=> Keytar RIP

webapp/src/container.tsx, webapp/src/greenscreen.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/2198.
-  don't try to use web cams in electron/uwp
- use green screen when no web cams available (including in IE11)
=> Green screen offline

webapp/src/app.tsx
microsoft/pxt-microbit/issues/2184
=> Update collapse icon tooltip with state

docfiles/script.html
We want edit button to from v1 & v2 both go to the live website. v0 goes to live already.
=> Fixing share page to point to live always

common-docs/faq.md, common-docs/offline.md
More details on offline extensions
=> additional notes on offline extensions

cli/gdb.ts
this can go on master, either now or later
=> Fix gdb path for docker build with DAL

pxtlib/browserutils.ts, pxtsim/runtime.ts
Should fix https://github.com/microsoft/pxt-arcade/issues/1061, but I'd love it if anyone could verify that as I don't currently have a windows machine to validate that
=> Fix ie crash

localtypings/pxtarget.d.ts, pxteditor/experiments.ts, webapp/src/app.tsx
Use theme flag to turn on "check hw with webusb"
=> Checkhwvariantwebusb flag

localtypings/pxtarget.d.ts, pxtlib/browserutils.ts
Not styled, just using our current redirect to '/browsers' functionality
=> Add list of unsupported browsers to pxttarget json

webapp/src/app.tsx
Fix for https://github.com/microsoft/pxt-arcade/issues/1087
=> make sure to stop the simulator if compilation failed

docfiles/offline-app-body.html, docfiles/offline-app-head.html
Use boardname for rendering "micro:bit"
=> fix electron rendering of license

theme/tutorial.less
https://github.com/microsoft/pxt-arcade/issues/1069
https://github.com/microsoft/pxt-arcade/issues/1086
=> Small tutorial CSS fixes

cli/buildengine.ts, cli/cli.ts
* specify hwvariant from CLI
* allow to install as part of build steps
* fix some WSL2 issues
=> better CLI support for hwvariants

theme/blockly-core.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/799
=> Comment rendering fix for iOS/Safari

webapp/src/discourse.ts
=> don't rely on featured link to extract program url from discourse post

docs/touchdevelop.md
Here it is. Don't merge until we have the redirect in place. @mmoskal is investigating best way to get this done.
=> shutdown message for TD

theme/common.less, webapp/src/simtoolbar.tsx
microsoft/pxt-minecraft/issues/853
microsoft/pxt-microbit/issues/2155
=> Small css fixes for minecraft editor toolbar

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, webapp/src/app.tsx
Looks for single '#' and text, otherwise defaults to file name (as before)
=> Use first 'heading 1' of tutorial as title

pxtlib/github.ts
raw.githubusercontent.com doesn't accept token auth (neither header nor argument) so use regular api if raw fails
=> Fix cloning of private GH repos

docs/blog/teams/teams-assignments.md
The blog video was edited and this is the link to the new one.
=> Update YouTube link in Team Assignments blog

theme/common.less, webapp/src/editortoolbar.tsx
Fixes microsoft/pxt-minecraft/issues/914
=> Fix editor toolbar overlap with workspace

webapp/src/toolboxeditor.tsx
Show function drawer in toolbox if function blocks found in tutorial markdown
=> Show new function blocks in tutorial filtering

pxtpy/converter.ts, tests/runtime-trace-tests/cases/str.ts
I tried to find a cleaner way to do this, but this is the best I could come up with. It's already hard-coded in the other direction (TS -> PY)
=> Handle python str function

cli/buildengine.ts
this speeds up macOS docker build
=> Add :delegated to docker mounts on macOS

package.json
Needed to bump request a few and add types for it to work
Nothing seems to have been listed as a breaking change between the two versions: https://github.com/request/request/blob/master/CHANGELOG.md
=> Fix travis

package.json, pxtpy/converter.ts
cherry picking https://github.com/microsoft/pxt/pull/5758 to fix https://github.com/microsoft/pxt-microbit/issues/2237
=> stable5.15: un-lexically nest function

docs/static/tutorial-tool/tutorial.js, docs/static/tutorial-tool/tutorial.ts
Adding matching `pxt.json` with the nether package
=> Fixing minecraft tutorials in tutorial tool

cli/cli.ts
Allows to write
pxt install --hw rpi
=> pxt install/build support for hw

pxtcompiler/emitter/emitter.ts, tests/compile-test/lang-test0/07stringcollections.ts
fixes https://github.com/microsoft/pxt-microbit/issues/2243
=> recognize unions of numbers as 'number-like'

docfiles/docs.html, docfiles/macros.html, docs/accessibility.md, pxtlib/docsrender.ts, theme/common.less, theme/docs.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/views/card.overrides, webapp/src/app.tsx, webapp/src/codecard.tsx, webapp/src/components/searchInput.tsx, webapp/src/dialogs.tsx, webapp/src/editortoolbar.tsx, webapp/src/monaco.tsx, webapp/src/projects.tsx, webapp/src/scriptmanager.tsx, webapp/src/scriptsearch.tsx, webapp/src/simtoolbar.tsx, webapp/src/sui.tsx, webapp/src/toolbox.tsx
bunch of small fixes for accessibility issues; each commit lists the issue it fixes (although at least once or twice there was a typo / minor update to a fix that I re-fixed slightly in a later commit).
There are a couple of minor changes in docfiles that I would love a double check on (as those are the scary files to modify)
Also have https://github.com/microsoft/pxt/tree/accFixes, which is just the same fixes cherry-picked to the microbit stable branch, in case this should go to microbit beta
One other thing that should be fixed is the tutorial orange, which also shows up on the home page code cards for the partially completed tutorial; the contrast is pretty poor everywhere it is used, but any higher contrast variant looks significantly different so i think that should wait until we …
=> Accessibility issue fixes

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
=> string.toLowerCase

docs/writing-docs/tutorials.md, localtypings/pxtarget.d.ts, pxtlib/tutorial.ts
Tutorial engine side of new hint/activity syntax
=> Update activity/step and hint syntax for tutorial parsing

theme/tutorial.less, webapp/src/container.tsx, webapp/src/tutorial.tsx
Updates per minecraft design meeting
- Remove dropdown/random access of activities
- CSS updates
=> Tutorial updates

webapp/src/projects.tsx
Ensure enough space for double-button on how screen details view.
=> update layout of buttons

theme/common.less
@abchatra here's the fix you've been waiting for.
=> Fixing icons reposition error in safari

pxtlib/tutorial.ts, tests/tutorial-test/baselines/explicitHints.json, tests/tutorial-test/baselines/ghost.json, tests/tutorial-test/baselines/template.json, tests/tutorial-test/cases/explicitHints.md, theme/common.less
=> Cherry5.19

pxtlib/commonutil.ts, theme/common.less, webapp/src/app.tsx, webapp/src/container.tsx
=> Dropdown in toggle for languages

pxtlib/sprite-editor/buttons.ts, pxtlib/sprite-editor/reporterBar.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1184
=> add tool tips for undo, redo, and size toggle

common-docs/javascript/types.md
Needed for the pxt-adafruit release
=> Cherry pick color rename

cli/gitfs.ts
Fixes a critical bug in pxt uploadrefs and provides documentation and TODOs to better understand the purpose and gotchas of this command.
=> Fixes "pxt uploadrefs"

pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts
In support of: https://github.com/microsoft/pxt-common-packages/pull/930
=> Support for big image encoding

docs/SUMMARY.md, docs/develop/hw-debugging.md
Adds public documentation on how to HW debug CPX with GDB and edit .cpp
=> add docs on HW debugging CPX

pxtblocks/fields/field_melodySandbox.ts, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-adafruit/issues/1093
=> Stop simulator when the melody editor is open

pxtcompiler/emitter/backthumb.ts, tests/compile-test/lang-test0/02numbers.ts
=> Implement bit shifts in assembly

theme/common.less, webapp/src/scriptsearch.tsx
bring #5835 to adafruit stable
=> [stable5.20] use textColor less var for 'learn more' link

cli/cli.ts, pxtlib/imageConverter.ts, pxtlib/sprite-editor/gallery.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1267
=> Make sprite editor handle new image format.

webapp/src/app.tsx, webapp/src/cloudsync.ts
Logic was duplicated in a few places
=> Unite the places that reload the editor

pxteditor/editorcontroller.ts, webapp/public/controller.html, webapp/src/app.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/2319#event-2604053395
=> Controller actions

webapp/src/app.tsx
Fix navigation for errors in libs
=> fix nav in lib errors

cli/server.ts, localtypings/pxtarget.d.ts, pxtcompiler/simpledriver.ts, pxtlib/emitter/cloud.ts, pxtlib/package.ts, scripts/simpledriver.js
This allows for local testing of cloud-compiled share page. Related Arcade PR coming.
=> Improve simple compile driver and add local testing

webapp/src/projects.tsx
As requested, removing cancel button.
=> Remove Cancel button from new project name dialog

pxtcompiler/emitter/emitter.ts, tests/compile-test/lang-test0/30null.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1113
=> Return undefined from functions w/o return

pxteditor/monaco.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/simtoolbar.tsx, webapp/src/simulator.ts
Fix for https://github.com/microsoft/pxt-arcade/issues/1281
=> Autorun blocks, no autorun js

localtypings/pxtarget.d.ts, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/share.tsx
Automatically share script after sharing (target option)
=> option to share on finished tutorial

docfiles/thin-footer.html, docs/playground.html, docs/static/tutorial-tool/tutorial.css, docs/static/tutorial-tool/tutorial.js, docs/tutorial-tool.html
Adding a tidbit of polish to the tutorial-tool so that it can be used in "microbit LIVE".
=> Tutorial-tool polish

theme/highcontrast.less
fixes https://github.com/microsoft/pxt-microbit/issues/756 and fixes microsoft/pxt-microbit#922, but also just cleans up a lot of things that weren't using less vars, and makes lots of things that weren't matching the colors match the colors.
~marking as a draft to start because I gotta work on other things today and want to sanity check everything real quick later tonight, as there's a decent number of minor changes and I want to make sure I didn't miss things.~ checked over everything, but at this point the pr is rather large and not particularly time sensitive.
current:
lots of colors getting swapped / inconsistencies
new:
=> Fix high contrast mode aesthetic

webapp/src/share.tsx
Fix for https://github.com/microsoft/pxt-arcade/issues/862
=> move message under sim area if available

pxtblocks/blocklycompiler.ts, pxtlib/jsoutput.ts, tests/blocklycompiler-test/baselines/to_string_arg.ts
Fixes microsoft/pxt-microbit#2399
Fixes microsoft/pxt-microbit#2345
=> Parenthesized expression fix

webapp/src/app.tsx, webapp/src/filelist.tsx
Can't open files under built that have errors.
=> Open built files with errors

webapp/src/app.tsx, webapp/src/filelist.tsx
* handle built files with errors as well
* better handling of built/ files
* remove fix
=> Open built files with errors (#5878) -> stable 5.21

docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-helpers.ts
Path animation it is better to play for longer than shorter
=> Adding 5sec option to the timer field

docs/static/tutorial-tool/tutorial.js, docs/tutorial-tool.html
=> Tutorial tool share

common-docs/extensions/approval.md, docs/extensions/approval.md
A bit more details on approval steps
=> updated approval checklist

.travis.yml, common-docs/blocks/loops.md, common-docs/blocks/loops/break.md, common-docs/blocks/loops/continue.md, pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtcompiler/emitter/decompiler.ts, pxtlib/service.ts, pxtrunner/renderer.ts, tests/decompile-test/baselines/break_continue.blocks, tests/decompile-test/cases/break_continue.ts, webapp/src/blocksSnippets.ts
Cherry-pick of https://github.com/microsoft/pxt/pull/5908. break and continue is commonly requested in FLL forums.
=> cherry-pick break/continue in stable4.0 branch (EV3)

localtypings/pxtarget.d.ts, pxtlib/github.ts, webapp/src/app.tsx, webapp/src/dialogs.tsx, webapp/src/filelist.tsx, webapp/src/gitjson.tsx, webapp/src/sui.tsx
=> Github explorer PR feedback

docs/language.md, pxtcompiler/emitter/emitter.ts, pxtsim/langsupport.ts, tests/compile-test/lang-test0/22lambdas.ts, tests/compile-test/lang-test0/37objectliterals.ts, tests/compile-test/lang-test0/tsconfig.json, tests/errors-test/cases/delete.ts, tests/errors-test/cases/function-hoisting.ts, tests/errors-test/cases/generics.ts, tests/errors-test/cases/shorthand.ts
See changes to language.md for description.
Also fixes https://github.com/microsoft/pxt-arcade/issues/1062
fixes #4021 
fixes #5895
=> support for delete, shorthand and computed properties, and functions at the end of function

pxtsim/runtime.ts
@tballmsft this should fix the problem with Tile Sprites, could you test it at https://arcade.makecode.com/app/b43bfe0e74b689e3843574119b11ba26c9e8182c-7c04fdd3e7
=> Fix interaction between exceptions and maybeYield()

pxtcompiler/emitter/emitter.ts, tests/errors-test/cases/delete.ts
=> Throw error when deleting an array element using the delete operator

webapp/src/blocks.tsx, webapp/src/toolboxeditor.tsx, webapp/src/tutorial.tsx
Build: https://minecraft.makecode.com/app/16a847ed1f296a6e6697f06e19a83586e5dd8bb6-e532db8929
| Before | After |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/34112083/65470637-e2637780-de20-11e9-9101-a849419dac26.png) | ![image](https://user-images.githubusercontent.com/34112083/65470663-f7d8a180-de20-11e9-9388-ff505dcb80b4.png) |
| ![image](https://user-images.githubusercontent.com/34112083/65470786-877e5000-de21-11e9-8563-5526bd11a381.png) | ![image](https://user-images.githubusercontent.com/34112083/65470830-ada3f000-de21-11e9-8698-1c7cee926691.png) |
=> Hide shadow blocks in tutorial toolbox

pxtcompiler/emitter/emitter.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2440
=> Avoid crash on synthetic symbol access

.github/lock.yml
Here is the app: https://github.com/apps/lock/
=> Adding lock to old issues

pxtlib/crowdin.ts
Fix for https://travis-ci.org/microsoft/pxt-microbit/builds/589452330#L1795
Concurrent builds might overcrowd crowdin.
=> Crowdin crowded

docfiles/toc.html
@riknoll , should this test the new fix from you and Michal?
=> adds meaningless doc change for the purpose of testing our docs versioning

common-docs/github.md, common-docs/github/diff.md, common-docs/github/release.md, common-docs/github/token.md
A cursory pass on the pages from #5934.
=> Some edits for 'GitHub' pages

cli/cli.ts, pxtlib/crowdin.ts
=> Crowdin stats upgrade

pxtcompiler/emitter/emitter.ts, tests/compile-test/bare/basic.ts, tests/compile-test/lang-test0/19forof.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1363
=> Fix for-of variable capture

docs/writing-docs/tutorials.md, localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, pxtlib/tutorial.ts, tests/tutorial-test/baselines/flyoutOnly.json, tests/tutorial-test/baselines/hideIteration.json, tests/tutorial-test/cases/flyoutOnly.md, tests/tutorial-test/cases/hideIteration.md, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/container.tsx, webapp/src/editortoolbar.tsx, webapp/src/simtoolbar.tsx, webapp/src/tutorial.tsx
For Minecraft hour of code tutorials.
=> Add 'flyout only' and 'hide iteration' options to tutorial metadata

pxtlib/hf2.ts
just for clarity - keep in sync with common-pkgs
=> Add MMap type

pxtblocks/blocklycompiler.ts, tests/blocklycompiler-test/baselines/loops.ts, tests/blocklycompiler-test/baselines/loops_local_variables.ts
Porting over the variable name fix for repeat blocks (#5967)
=> Cherry pick #5967 to stable5.15

pxtblocks/fields/field_turnratio.ts
Not sure why it ended in pxt but this needs to be updated.
=> field turn ratio upgrade

webapp/src/blocks.tsx
Not sure how this fits in with the new React/Redux editors.
=> make sure blockly field editors are commited

docs/writing-docs/user-tutorials.md, pxtlib/github.ts, webapp/src/app.tsx
=> Multiple tutorials per repo

webapp/src/core.ts, webapp/src/coretsx.tsx, webapp/src/filelist.tsx, webapp/src/gitjson.tsx
=> dialog improvements in github

common-docs/translate.md, webapp/src/app.tsx
Importing a user tutorial should load the package info (reported at microbit live)
=> mine package from markdown when loading tutorial

theme/common.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/editortoolbar.tsx, webapp/src/tutorial.tsx
Also move "Play" button back to bottom left corner for Minecraft HOC ("hideIteration"), just enlarged
=> CSS updates for hideIteration, make 'See More' button smaller, centered

webapp/src/monaco.tsx
If you navigate to main.ts, then README.md, you will have a monaco toolbox. The reason is that the logic to hide/show is done in two location and it is different. This PR does a bit of cleanup to ensure we have 1 way of deciding to show/hide.
=> refactor logic to show/hide monaco toolbox

docs/js/profiling.md, localtypings/pxtarget.d.ts, pxtcompiler/emitter/backjs.ts, pxtsim/langsupport.ts, pxtsim/libgeneric.ts, pxtsim/runtime.ts
This (and related pxt-c-p PR) adds `control.heapSnapshot()` API. See `profiling.md` for description.
=> memory leak tracking 

docfiles/docs.html, docfiles/docs.js, docfiles/tocheader.html, pxtlib/docsrender.ts
=> Docs mobile

pxtcompiler/emitter/backjs.ts, pxtcompiler/emitter/ir.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1367
=> Allow for empty hex literals

docfiles/style.css
lets you scroll to the bottom of the sidebar
\/ can't get down to telemetry
\/ now can get down to telemetry
=> let sidebar scroll all the way to the bottom

docfiles/docs.js
Use background image instead of img
current:
fixed:
=> Fix YouTube preview size

docs/playground-runner.html
The API changed so the playground has been broken for a bit. This at least fixes it for local serve.
=> Fix API info call in playground runner

docfiles/apptracking.html, docfiles/tracking.html
pxtConfig can be undefined or null (localhost).
=> pxtconfig is null

docfiles/macros.html, docfiles/tocheader.html, pxtlib/docsrender.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2339
Fix roles for sidebar and header bar, so screenreaders can parse it properly.
=> Fix sidebar roles

pxtcompiler/emitter/emitter.ts
Otherwise state is left undefined. Fixes https://github.com/microsoft/pxt-arcade/issues/1387
(see diff without whitespace)
=> Run emit also when there are errors

package.json, pxtblocks/fields/field_position.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1379
=> Bump pxt-blockly to 2.1.7

docs/translate.md
Include a video explaining the process to sign up an join as a translator. The video is here:
[crowdin-signup.mp4](https://microsoft-my.sharepoint.com/:v:/p/v-gani/EWzP5jPlRA5ClITnzh0aPSsB5-QXHE4rDJ9E1lQK6jwI0w?e=lcuEoB)
=> Add Crowdin signup video to translate page

docs/writing-docs/tutorials.md
Add some info for the additional block section types.
RE: https://github.com/microsoft/pxt-minecraft/issues/1254
=> Update 'tutorials' page for new block sections

theme/github.less, theme/themes/pxt/globals/site.variables, webapp/src/app.tsx, webapp/src/gitjson.tsx
Could probably be polished but it's much better than the current inverted style. Dark mode github anyone?
=> fixing github view for inverted editors

webapp/src/gitjson.tsx
=> don't return undefined in react

pxtlib/github.ts
Only ignore start/end of line spaces in git diffs
=> don't ignore while space changes within a line

pxtblocks/blocklylayout.ts
Fixes https://github.com/microsoft/pxt/issues/6090
=> Use updated blockly rect with screenshot feature

docs/extensions/getting-started/vscode.md
Fix doc path for 'simple-extension' page.
=> fix link to simple-extension

cli/crowdin.ts, pxtblocks/blocklyloader.ts, pxtlib/blocks.ts, webapp/src/dialogs.tsx
Most blocks in loops,vars,maths supported (even multi-part blocs) + better stats output
=> Better in-context coverage of built-in blocks

localtypings/pxtpackage.d.ts, theme/snippet-builder.less, webapp/src/snippetBuilder.tsx, webapp/src/snippetBuilderInputHandler.tsx, webapp/src/snippetBuilderSpriteEditor.tsx
https://youtu.be/QmGW2JsBax8
Changes:
- Lot of fixes to spacing and padding/margins
- Remove elevated question shadow box
- Add "graph paper" behind code blocks
- Better responsive window behavior
- Adds "Yes No" input option (used by "Should this sprite use controls")
- Nicer font
- Pairs with: https://github.com/microsoft/pxt-arcade/pull/1403
=> Snippet builder tweaks for v1 beta launch

webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/toolDefinitions.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1420 and a few other related bugs
=> Fix floating layer rendering when cursor leaves canvas

pxtsim/embed.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, webapp/src/app.tsx
To allow minecraft to pass "#ipc=1" using the hash instead of question mark
=> Pass hash parameters to simulator board on entering editor

webapp/public/docs.html
cherry picking https://github.com/microsoft/pxt/pull/6120 to stable
=> [stable5.26] Fix side docs background color

pxtlib/service.ts
Wait for promises before continuing.
=> toolbox loc

cli/cli.ts, webapp/src/pxtjson.tsx
Reported in crowdin. Fix allows to localize these strings.
=> localizable user config

cli/cli.ts
Ensure that check docs verifies that local image files exist.
=> checkdocs properly check image links

docs/about.md, docs/contact.md
=> remove reference to discord

webapp/src/container.tsx, webapp/src/editortoolbar.tsx, webapp/src/githubbutton.tsx, webapp/src/projects.tsx
=> restore home icon

webapp/src/cloudsync.ts, webapp/src/githubprovider.tsx
Bug fix: don't try to get user info if token is missing. Avoid inital 401 code.
=> github: don't try to update user if missing token

theme/github.less, webapp/src/gitjson.tsx
Ability to see whitespace changes.
=> show whitespace button

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/array_get.blocks, tests/decompile-test/cases/array_get.ts
Fixes microsoft/pxt-microbit#2507
=> Decompile element access in conditional expression to blocks

cli/cli.ts
This PR https://github.com/microsoft/pxt/pull/6179 caused an issue in Arcade where the colors didn't match up on a few of the categories. Fixing that!
=> Ignore core package dependencies in the API info

docfiles/package.html
=> Undust package page

docs/extensions/codecard.md, localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
Added an Option to set custom Text for the Button in CodeCards.
e.g.:
"buttonLabel": "Open Forum"
=> Option for Custom Button-Labels in CodeCards

webapp/src/projects.tsx
Use rlf to pick localizations of button automatically
=> localized button label

pxtblocks/blocklyimporter.ts, pxtblocks/blocklylayout.ts, pxtblocks/blocklyrenderer.ts, pxteditor/editor.ts, pxtlib/github.ts, pxtlib/initprj.ts, webapp/src/app.tsx, webapp/src/gitjson.tsx, webapp/src/workspace.ts
Add diff screenshot when creating a commit in github + cleanup some incorrect typings
Demo see comment on https://github.com/pelikhan/pxt-untitled-21/commit/6572b0de8fd860d32081e75ceba564714f235cab
=> Blocks screenshot

webapp/src/tutorial.tsx
Looks like below (with empty tutorial card):
| Hour of Code | General Tutorial  |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/34112083/68713159-15d59f00-0552-11ea-86a5-07fc67b53e57.png) | ![image](https://user-images.githubusercontent.com/34112083/68713270-51706900-0552-11ea-969a-7be02eec4c7d.png) |
=> Only render unplugged step in modal (remove from tutorial card)

pxtlib/github.ts, webapp/src/gitjson.tsx, webapp/src/workspace.ts
Before doing a commit, pull changes and merge. If conflicts, bail out. This should take care of most conflict issues and we should never have to resort to creating a PR to handle conflicts.
=> Pull merge push

cli/cli.ts, pxtlib/main.ts
Fixes microsoft/pxt-arcade#1457
Fixes microsoft/pxt-arcade#1455
Fixes microsoft/pxt-arcade#1456
=> Fixes for apiInfo compression

webapp/src/app.tsx
Missed check for optional opts in https://github.com/microsoft/pxt/commit/653a4d9bba92d2f5a3128b33f9b2846b9536e12e
=> Fix focus call

cli/cli.ts, pxtlib/main.ts
Fix on radio * blocks in microbit. Fix for https://github.com/microsoft/pxt-microbit/issues/2523
+ also drops compressed API.json to file
=> Don't loose handlerParameters

cli/buildengine.ts
Detect any CODAL tag with v\d+ as versioned tag.
=> more lenient about detecting versioned tags in codal

localtypings/pxtarget.d.ts, pxtlib/cpp.ts
Generate defines that will accross yotta and CODAL.
=> cross compat yotta / codal

cli/cli.ts, localtypings/pxtarget.d.ts
Disable uploading to crowdin while still using translations. Useful for a dev branch.
``disableCrowdinUpload``
=> add flag to disable translation upload

cli/cli.ts, pxtlib/crowdin.ts
Syntax error in api call. This code does not get run on PR so it went through.
=> fix crowdin api call

pxtlib/initprj.ts, webapp/src/cloudsync.ts, webapp/src/container.tsx, webapp/src/gitjson.tsx, webapp/src/workspace.ts
=> github polish fixes

pxtlib/spriteutils.ts, webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/ImageEditor/Timeline.tsx, webapp/src/components/ImageEditor/TimelineFrame.tsx, webapp/src/components/ImageEditor/store/imageReducer.ts, webapp/src/components/ImageEditor/tilemap/Minimap.tsx, webapp/src/components/ImageEditor/toolDefinitions.ts, webapp/src/components/ImageEditor/util.ts
Update floating layer to be interface of base layer + overlay layers
=> Marquee fixes, apply marquee to all layers

cli/cli.ts, package.json, tests/blocks-test/karma.conf.js
Support running karma in github actions
=> Github actions support for karma

webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1488
- Consolidate the core hint hide/show logic in TutorialCard
- Clean up document event listeners on new step, add back in if necessary
Build: https://arcade.makecode.com/app/8a0a42f6ed1fd82cc8c4aaa02e6b5b5aa3927947-6a180526f4
=> Tutorial hint flow cleanup

common-docs/github.md, common-docs/github/token.md
Refreshing the GitHub docs with latest UI updates
=> updating GitHub docs

common-docs/github.md, common-docs/github/fork.md, common-docs/github/token.md
Throw in a few edits to the GitHub integration pages.
RE: #6278
=> Edits to the GitHub integration pages

common-docs/reference/arrays/push.md, common-docs/reference/arrays/remove-at.md, docs/writing-docs/tutorials.md
Fix some typos found by translators in Crowdin:
* https://crowdin.com/translate/kindscript/1431/en-de#784451
* https://crowdin.com/translate/kindscript/1909/en-de#69063
* https://crowdin.com/translate/kindscript/1629/en-de#60129
=> Fix typos found thru Crowdin - 12052019

pxtlib/main.ts, webapp/src/simulator.ts
Fixes: https://github.com/microsoft/pxt/issues/6294
=> Only report performance to console once

pxtpy/pydecompiler.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1130
=> fix python for-in-range conversion to be more conservative around <=

webapp/src/monaco.tsx
Partially fixes: https://github.com/microsoft/pxt-minecraft/issues/1490
=> Fix indentation problems for single-line snippet auto-complete

common-docs/github.md, common-docs/github/classroom.md, webapp/src/dialogs.tsx, webapp/src/githubbutton.tsx, webapp/src/gitjson.tsx
=> GitHub view improvements

webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1495
Before:
After this PR it just completes to "mobs.spawn(...)"
=> fix python auto-complete for member completion (past the first ".")

webapp/src/share.tsx
Fix for https://github.com/microsoft/pxt-arcade/issues/1497
=> enable screenshot in light mode

common-docs/github/classroom.md, pxtlib/github.ts
Fixing logic to find the local changes marker.
=> fixing conflict merging in github view

pxtlib/github.ts, webapp/src/githubbutton.tsx, webapp/src/gitjson.tsx, webapp/src/workspace.ts
When a user merged a PR in github, notify in editor that user needs to switch branch back to master.
=> Notify user that the branch has been deleted in github

theme/image-editor/imageEditor.less, webapp/src/blocklyFieldView.tsx, webapp/src/components/ImageEditor/BottomBar.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx
=> Move done button to bottom bar

pxtlib/github.ts, pxtlib/initprj.ts, webapp/src/gitjson.tsx, webapp/src/package.ts
In a later PR, will be more aggressive about moving the user back to master.
no pr
pr creation
known pr
=> Pull request support in makecode

common-docs/github-grader.html, docfiles/docs.js
A speed grader page for github projects.
=> Github grader

webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1540
=> Fix cursor preview for tilemap

pxteditor/editor.ts, pxtlib/apptarget.ts, pxtlib/main.ts, theme/common.less, theme/themes/pxt/modules/dropdown.overrides, webapp/src/app.tsx, webapp/src/editortoolbar.tsx, webapp/src/projects.tsx, webapp/src/sui.tsx
https://arcade.makecode.com/app/765ff5b298254fce996908797fb97cbad3fe4876-324c7d13f0
=> Hardware select dropdown next to download button

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtblocks/fields/field_colour.ts, pxtlib/package.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1517
Fixes https://github.com/microsoft/pxt-arcade/issues/1536
=> Read color names from pxt.json if present

docs/github-grader.html
=> Grader polish

docs/github-explorer.html, webapp/src/filelist.tsx, webapp/src/workspace.ts
Ensure editor is readly in github explorer
=> Explorer read only

common-docs/github/classroom.md, common-docs/teachers.md, docs/github-explorer.html
Better error handling + linking in docs
=> error handling + links to repo

theme/image-editor/timeline.less, webapp/src/components/ImageEditor/Timeline.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1560
=> Fix animation frames in Edge

docs/github-explorer.html
=> Display selected item in github explorer

docs/github-explorer.html
=> Explorer cookie

theme/image-editor/imageEditor.less, webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1492
Fixes https://github.com/microsoft/pxt-arcade/issues/1495
Fixes https://github.com/microsoft/pxt-arcade/issues/1498
=> Ipad fixes for image/animation/tilemap editor

pxtlib/service.ts
Fix for https://github.com/microsoft/pxt-arcade/issues/1597
No translations available yet but the service has access to them.
=> Localize built-in properties

webapp/src/components/ImageEditor/tilemap/TilePalette.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1565
=> Fixing tile palette on old ios safari

theme/common.less
Fixes https://github.com/microsoft/pxt-arcade/issues/1500
=> Fix logo height

theme/common.less, theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-arcade/issues/1608
Partially addresses https://github.com/microsoft/pxt-arcade/issues/1610#issuecomment-567091303 (overlap issue)
=> Fix hardware button high contrast, hide tooltip in mobile

pxtsim/libgeneric.ts
Also adds checks that will fire when the hardware would have crashed on writing a read-only buffer
=> Add isReadOnly method on Buffer

pxtsim/libgeneric.ts
Part of the fix for https://github.com/microsoft/pxt-arcade/issues/1625
=> Cherry pick #6377 to stable 5.30

docs/github-explorer.html, webapp/src/app.tsx
=> Explorer feedback

theme/themes/pxt/globals/zindex.variables, theme/tutorial.less, webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/994
https://arcade.makecode.com/app/3780f61c3fd492f9489884691f568865ed090f94-e65c1b6316
=> Add mask for closing tutorial hint on iOS

cli/cli.ts
This is to fix the build for https://github.com/microsoft/pxt-arcade/pull/1623
For tutorials with namespaces, test each step individually to avoid clashes.
=> Handle namespace declarations in tutorials for checkdoc

webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes: https://github.com/microsoft/pxt-arcade/issues/1478
By keeping track of whether or not the user has interacted, and if they haven't keep the zoom centered.
It's kind of hacky since really there shouldn't be any state changes that cause the center to drift without the user doing something.
https://arcade.makecode.com/app/25d10b208659a66bb96555e217d0cf4ea0640686-0e08bdf0d0
=> Fix Sprite editor is not centered correctly in small screen

cli/cli.ts
This is needed to fix the build for tutorials that use the tilemap editor. Only affects checkdocs
=> Handle namespace declarations in tutorials for checkdoc (#6385)

theme/themes/pxt/globals/site.variables, theme/tutorial.less, webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1632
=> Separate less variable for tutorial button color

pxtcompiler/emitter/emitter.ts, pxtlib/package.ts, pxtsim/langsupport.ts, tests/compile-test/lang-test0/37objectliterals.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2513
=> Convert x to string in delete o[x]

webapp/src/projects.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1642
=> Update high contrast state in home screen setting menu

pxtblocks/fields/field_position.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1654
=> Check type of field value when setting position picker XY

theme/common.less, theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/1475
=> Toggle dropdown fixes for high contrast, mobile/tablet views

webapp/src/githubbutton.tsx
Explains the state of the arrows on the github button.
=> Better tooltip on the github button

common-docs/faq.md
Add a target specific override section to the FAQ.
=> Add a target specific section to FAQ

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1493
=> Stay in Python if code has error

pxtpy/converter.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1023
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1464
=> Raise errors for unsupported language features instead of returning TODO into the user code

theme/keymap.less, webapp/src/keymap.tsx
Always keep white background, add lf wrapper
Addresses localization of this https://github.com/microsoft/pxt/issues/6414
=> Keymap localization + small css tweak

pxtsim/runtime.ts
A handy interface for the simulator (need to refactor radio sim code to common packages)
=> EventBusBoard interface

pxtpy/converter.ts, pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/ONLY_loop_continue_break.ts, tests/runtime-trace-tests/cases/loop_continue_break.py
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1563
=> add support for break and continue

pxtlib/initprj.ts
Tell GitHub Pages to serve the assets folders.
=> add missing jekyll include

webapp/src/workspace.ts
Add a ``version.txt`` file in the assets folder to support automated itch.io push.
=> Add version.txt file when creating a release

webapp/src/compiler.ts, webapp/src/workspace.ts
=> store version and target verison in js

common-docs/github.md, common-docs/github/SUMMARY.md, common-docs/github/pages.md, localtypings/pxtarget.d.ts, pxteditor/experiments.ts, webapp/src/gitjson.tsx, webapp/src/workspace.ts
=> Commit binary.js experiment

theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-arcade/issues/1705
=> Fix high contrast chevron for toggle dropdown

theme/home.less, theme/themes/pxt/globals/site.variables, webapp/src/projects.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1593
Fixes https://github.com/microsoft/pxt-minecraft/issues/1594
https://minecraft.makecode.com/app/cfe9df24ca50acab0f4ef8fb75beb3f6278ee06a-1be109dbab
TODO: animate video in selected card (will do after immediate Minecraft/Python stuff is done)
=> Text for detail actions, CSS updates for mobile cards

pxtpy/converter.ts, tests/pyconverter-test/baselines/dictionary.ts, tests/pyconverter-test/cases/dictionary.py
Fixes https://github.com/microsoft/pxt-minecraft/issues/1038
=> Support for python dictinary literals

pxtrunner/renderer.ts, theme/print.less, theme/tutorial.less, webapp/src/marked.tsx
Support for highlighting individual lines of code. Comment with ``@highlight`` makes a line to be highlithed
=> Support for @highlight macro in python/js tutorails

theme/home.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/1606
=> Ignore pointer events on detail card title

pxtcompiler/emitter/service.ts
Fix for https://github.com/microsoft/pxt-minecraft/issues/1571
=> python built-in snippets completion

theme/monaco.less, theme/themes/pxt/globals/zindex.variables
We changed the zindex for signatures, but not suggestion list.
=> ensure suggestion list is above signature help list

pxtcompiler/emitter/service.ts
=> show any type in param help

pxtcompiler/emitter/service.ts, webapp/src/monaco.tsx
Those function are blocks artifacts.
=> Hide TD_ID function from toolbox/completion

cli/cli.ts
Python snippets are handled step-by-step (using namespace/spritekind codepath) since there is no global tutorial.code, and Python event handler names would clash anyway
Fixes https://github.com/microsoft/pxt-minecraft/issues/1612
=> Pass otherActions urls through checkdocs, handling of Python snippets

pxtlib/github.ts, theme/common.less, webapp/src/app.tsx, webapp/src/githubbutton.tsx, webapp/src/gitjson.tsx, webapp/src/package.ts, webapp/src/sui.tsx
=> Various github fixes

webapp/src/app.tsx
Support for ``#tutorial:py:tutorialid`` route
=> tutorial editor language route

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1653
=> Apply tutorial card max-height to editor offset

localtypings/pxtarget.d.ts, pxteditor/experiments.ts, webapp/src/blocks.tsx
=> added blocks collapse experiement

common-docs/blocks/logic/boolean.md, common-docs/github/faq.md
String bugs found by translators.
=> String bugs found by translators - 01242020

theme/themes/pxt/modules/dropdown.overrides, webapp/src/dialogs.tsx, webapp/src/gitjson.tsx, webapp/src/sui.tsx
=> Inverted theme fixes for github

pxtcompiler/emitter/service.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1588
=> favor top-level symbols in auto-complete

cli/cli.ts, cli/crowdin.ts, docs/targets/pxtarget.md, localtypings/pxtarget.d.ts
Allows to specify a regex to match the branch name to upload api strings.
=> add flag to control api string upload branch

localtypings/pxtarget.d.ts, pxtlib/github.ts, pxtlib/initprj.ts, webapp/src/compiler.ts, webapp/src/gitjson.tsx, webapp/src/workspace.ts
In order to trigger the "release" workflow, workflow then compiles all binaries for arcade game
=> use proper api to create a release in github

pxtlib/crowdin.ts
Sometimes crowdin reports 500, but the payload says upload success
https://travis-ci.org/microsoft/pxt-arcade/builds/643441439#L1988
https://travis-ci.org/microsoft/pxt-arcade/builds/643456118#L2073
=> crowdin code 500 + success

webapp/src/githubprovider.tsx, webapp/src/projects.tsx
=> Github logout

pxtlib/browserutils.ts, pxtlib/main.ts, theme/highcontrast.less, theme/monaco.less, theme/themes/pxt/globals/site.variables, theme/toolbox.less, webapp/src/carousel.tsx, webapp/src/monaco.tsx, webapp/src/monacoFlyout.tsx, webapp/src/toolbox.tsx, webapp/src/toolboxeditor.tsx
- Move Monaco flyout into separate react component
- Add parameters to toolbox block
- Display parameter info on click
- Drag-and-drop behavior enabled for iOS/mobile
Build: https://minecraft.makecode.com/app/963bb0104ccea6485704df569d9ec7679280c62e-a705a6159a
=> React component for Monaco flyout, updated flyout UI

webapp/src/editortoolbar.tsx, webapp/src/githubbutton.tsx
=> Github project name

webapp/src/toolboxeditor.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2594
=> Cache toolbox groups according to name + subnamespace

gulpfile.js
Should fix the build in https://github.com/microsoft/pxt-microbit/pull/2597
I forgot to port this line over from the jakefile
=> Adding runner from blocks tests back to the build

pxtcompiler/emitter/hexfile.ts, pxtlib/cpp.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/1631
=> Embed sources in .hex using 0x0E record

docs/github-explorer.html
=> Don't use access_token in github-explorer

gulpfile.js
=> lint before build

webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1711
=> Fix intelli-sense enter not working b/c insert next is undefined

localtypings/pxtarget.d.ts, pxtcompiler/emitter/driver.ts, pxtcompiler/emitter/service.ts, pxtcompiler/emitter/transpile.ts, pxtlib/service.ts, pxtpy/converter.ts, webapp/src/compiler.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1709
=> Fix duplicate identifier names when using toolbox snippets

pxtsim/instructions.ts, pxtsim/runtime.ts
Fix instructions rendering in maker
=> Instructions fix

docs/github-explorer.html
=> Use GitHub GraphQL in github-explorer

theme/monaco.less, webapp/src/monacoFlyout.tsx, webapp/src/toolbox.tsx
- blockdef in colored toolbox description
- qName in expanded API
- Help icon to docs page, opens in new window
https://minecraft.makecode.com/app/78f566e60e69d66530ce36bacbf0a444835b98ae-ed9a0d2082
=> Use blockdef in toolbox

pxtcompiler/emitter/service.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1737
=> Elide "num1" "num2" "num3" args from on_chat

README.md, gulpfile.js
watchCli compiles less stuff to work on compiler side of the house
=> gulp watch cli

webapp/src/monacoSnippets.ts
=> Four-space indent for built in python snippets

theme/tutorial.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/1747
=> Unset width for tutorial dots

webapp/src/monacoFlyout.tsx
Clicking on "sprites" crashes on arcade.
=> don't crash on missing params

pxtcompiler/emitter/service.ts
I'm just marking this as a draft because I haven't tested it fully but I think it's good to go.
=> Fixing completions for TypeScript outside of call expressions

pxtcompiler/emitter/service.ts, pxtcompiler/emitter/transpile.ts, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1718
=> Skip transpile caching on code hover

pxtcompiler/emitter/service.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/1725
Also adds an improvement to the sorting of parameter completions where the parameter value is a property access expression. Now we check the return type of the completion entry and weight it higher if it matches.
=> Fixing autocomplete for TS and improving sorting of completions

cli/gdb.ts
https://github.com/adafruit/Adafruit_nRF52_Bootloader/pull/110
=> Add bootloader constants for nrf52 for GDB

pxtlib/github.ts, pxtlib/package.ts
Check if pxt.json is present, look at "supportedTargets" or README for legacy projects.
=> Fix logic to filter out user repoes

webapp/src/app.tsx, webapp/src/compiler.ts, webapp/src/scriptmanager.tsx, webapp/src/workspace.ts
=> don't check lock when deleting scripts

pxtlib/initprj.ts
Fix for https://github.com/microsoft/pxt/issues/6605
=> pxt init: check that webconfig exists

theme/common.less
cherry pick https://github.com/microsoft/pxt/pull/6613 for minecraft
=> [stable5.33] fix share page in one-language & headless mode

webapp/src/workspace.ts
=> Fixing logic when loading github project with local references

webapp/src/projects.tsx
cherry pick https://github.com/microsoft/pxt/pull/6620 for minecraft patch
=> [stable5.33] add selected language restriction to tick for new project dialog

webapp/src/editortoolbar.tsx
=> Correct tooltip for big run button

common-docs/faq.md, common-docs/github/SUMMARY.md, common-docs/github/history.md, gulpfile.js, pxtlib/github.ts, webapp/src/data.ts, webapp/src/gitjson.tsx, webapp/src/marked.tsx, webapp/src/workspace.ts
Ability to restore any existing commit.
=> github history: restore any commit

common-docs/browsers.md
Fixing some of the existing information and restricting list to what we can test.
=> Updating the browsers with the edge download link

common-docs/faq.md
Add a note to telling how to enable the "ask first before downloading" setting in browsers.
Closes #6639
=> Add a download location note to the "FAQ"

cli/gdb.ts, docs/cli/gdb.md
Allows for flashing without bootloader with openocd
Also remove reset on gdb detach
=> Add 'pxt gdb flash'

pxtcompiler/emitter/service.ts
Old legacy hardcoded support for show_leds.
=> fix expansion of "show_leds"

cli/cli.ts
=> Community.md update script fixes

common-docs/github.md, common-docs/github/SUMMARY.md, common-docs/github/classroom.md, common-docs/github/commit.md, common-docs/github/faq.md, common-docs/github/getting-started.md, common-docs/github/private-assignments.md, common-docs/github/public-assignments.md, common-docs/github/token.md
Doing another round of edits on the github guidance docs.
=> Github docs improvement

pxtpy/converter.ts, tests/pyconverter-test/baselines/calls.ts, tests/pyconverter-test/cases/calls.py, tests/pydecompile-test/baselines/calls.py
Fix for https://github.com/microsoft/pxt-microbit/issues/2632
=> don't emit value if initializer has one

docs/writing-docs/user-tutorials.md, webapp/src/app.tsx, webapp/src/filelist.tsx, webapp/src/gitjson.tsx
=> github history UI design feedback

pxtblocks/blocklycompiler.ts, pxtlib/blocks.ts, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2634
=> Only use edit amendments if the API has a handler

webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2638
=> Handle member completions for non-namespaces in python

docs/home-screen.md, docs/targets/home-screen.md
Add a section for gallery shuffle in the home screen config page.
RE: #6654
=> Include 'gallery shuffle' in home screen doc

webapp/src/filelist.tsx
One more icon to get the final shareable link to a tutorial.
=> Adding a preview/share button for tutorials in markdown

webapp/src/coretsx.tsx, webapp/src/sui.tsx
=> Fix copyable

webapp/src/workspace.ts
Handle case when local dependency project was deleted.
=> Header null fix

cli/cli.ts
=> disable crowdin upload for stable5.15

cli/cli.ts
=> disable crowdin upload for stable5.20

cli/cli.ts
=> disable crowdin upload for stable5.33

cli/cli.ts
=> disable crowdin upload for stable4.0

cli/cli.ts
=> disable crowdin upload for stable5.32

cli/cli.ts
=> disable crowdin upload for stable5.30

cli/cli.ts
=> disable crowdin upload for stable3.15

cli/cli.ts
I think I got very confused about the curly braces the first time around. Now it will *actually* only upload on tagged commits on master.
=> Fix the upload logic for crowdin

pxtrunner/runner.ts
=> Delete the duplicate line

pxtcompiler/emitter/backjs.ts
=> Remove duplicates

common-docs/SUMMARY.md
Include the Python pages in the SUMMARY.
=> Add Python pages to the base SUMMARY

docfiles/style.css, docs/blog/online-learning.md, theme/docs.less
close https://github.com/microsoft/pxt/issues/6715
~noticed a few minor styling bugs (tables go offscreen in phone size with a different background color)~ fixed in separate pr ~and that hint headers aren't showing up (should be able to just have the header after the hint and have it show up properly next to the icon); will take a look at those real quick (makecode.com/docs files update either immediately with merge or after a bump, so no big release needed)~ fixed in this pr 
Also wrote up short descriptions for each stream, if we could double check those :)
(sorry for huge / 8mb gif, using desktop and haven't nailed gif recorder settings yet)
(see https://github.com/microsoft/pxt/pull/6717#issuecomment-600366559 below for new version with proper headers)
worth noting that view is …
=> table for online learning post

docfiles/footer.html, docfiles/script-page.css, docfiles/script.html, docfiles/scripthead.html, docs/playground.html
Integrating https://github.com/microsoft/pxt/pull/6719 into microbit stable branch stable5.15
=> Script template stable5.15

docfiles/script.html, docfiles/thin-footer.html, docs/github-explorer.html
=> update some copyright years

theme/common.less
cherry pick https://github.com/microsoft/pxt/pull/6729 for mbit release
=> [stable5.15] no mini view when in sandbox

webapp/src/projects.tsx
When opening a youtube video, use the youtube logo
=> use youtube link when playing avideo

webapp/src/projects.tsx
=> Double youtube button fix

webapp/src/app.tsx, webapp/src/share.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/2252
=> fix double loading of share dialog

webapp/src/filelist.tsx
=> guard header access

webapp/src/monaco.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2611
=> localize 'more' in monaco toolbox

webapp/src/workspace.ts
When duplicating a script, remove github information.
=> delete github data when duplicating

docs/online-learning.html, docs/static/online-learning/online-learning.css
=> Online mixer iframe

pxteditor/monaco.ts, webapp/src/compiler.ts, webapp/src/monaco.tsx, webapp/src/monacoDebugger.ts, webapp/src/package.ts
Adding support for Python files in the debugger. I have not tested multi-file python projects.
=> Python debugger

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/scriptmanager.tsx
Just open a new tab with new tab. Don't do the special dependent window flag.
=> open a regular editor when opening new tab

pxtcompiler/emitter/backjs.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/monaco.tsx, webapp/src/simulator.ts
Changing either option will restart your simulator. Still no python support.
=> Tracing and debugging at the same time

theme/home.less
changing size / weight / etc ends up looking a bit wonky so just an underline
=> add hover underline for View All btn

gulpfile.js
VSCode decided to reformat it too. No undo possible.
run to start build watch
gulp online-learning
=> add gulp command to build online learning page

pxtrunner/renderer.ts
- sort symbols
- fix divided typo
- hide helper functions without docs
Test
https://maker.makecode.com/apis
=> apis fix rendering tweaks

theme/print.less
Fix regression detected while building apis .
=> few fixes to blockly printing

pxtlib/crowdin.ts
We should really send the original payload, not the answer from crowdin.
=> don't upload response json in crowdin

docs/online-learning.html, docs/static/online-learning/schedule.js, docs/static/online-learning/schedule.ts
Remove the Steve Issacs stream listing from the Available Streams. Throw in headings for Stream Schedule and Available Streams.
Image assets remain in case the stream is added back later.
Closes #6749
=> Remove Steve Issacs stream listing

docs/writing-docs/tutorials.md, localtypings/pxtarget.d.ts, pxtlib/tutorial.ts
Add pxttarget flag to turn on text diffs
document noDiffs metadtta
=> use flag to control text diffs

pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_tilemap.ts, theme/blockly-core.less, theme/monaco.less
Fixes for https://github.com/microsoft/pxt-microbit/issues/2678
Partial fix for https://github.com/microsoft/pxt-microbit/issues/2703
=> Css fixes for sprite/tilemap fill, monaco toolbox drag block

theme/highcontrast.less
fix https://github.com/microsoft/pxt-microbit/issues/2752
=> fix share dialog consent text in high contrast mode

webapp/src/marked.tsx
Update markdown render to open external links in new tabs
=> bounce out any external links in app

webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2710
=> Fix breakpoint on return block

pxtblocks/blocklyloader.ts, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2716
=> Add the return block to the search results

pxtlib/webusb.ts, webapp/src/cmds.ts, webapp/src/container.tsx, webapp/src/data.ts, webapp/src/editortoolbar.tsx
Display "pair device" in ... dialog when webusb is enabled.
=> "Pair device" menu in dialog window.

webapp/src/projects.tsx, webapp/src/scriptsearch.tsx
=> Fix extension search issues

pxtblocks/blocklycompiler.ts, tests/blocklycompiler-test/baselines/function_bad_recursion.ts, tests/blocklycompiler-test/cases/function_bad_recursion.blocks, tests/blocklycompiler-test/test.spec.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2758
I meant to go back and fix this before opening the initial PR but totally forgot. Probably should mark these things with a TODO 😄
=> Fixing call stack overflow in blockly compiler

docs/online-learning.html, docs/static/online-learning/online-learning.css, docs/static/online-learning/schedule.js, docs/static/online-learning/schedule.ts
Put in @Jaqster 's news div to announce the Digital All-Stars stream.
RE: #6804, #6749
=> Include a News div for new streams on OLP

theme/common.less, theme/highcontrast.less, theme/home.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2772
Fixes https://github.com/microsoft/pxt-microbit/issues/2732
Fixes https://github.com/microsoft/pxt-microbit/issues/2734
=> CSS fixes for details icon, high contrast, toggle dropdown

webapp/src/createFunction.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2774
No screenshot but I trust you can imagine it 🙂
=> Use close icon instead of cancel in create function dialog

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2778
=> Don't auto-start sim when debugging or tracing

pxtlib/initprj.ts
Can't have a new line before front matter
=> no new line before front mater

webapp/src/webusb.tsx
=> invalid check for usb pairing dialog

docs/static/online-learning/schedule.js, docs/static/online-learning/schedule.ts
Update the Online Learning page new flash for this week's Digital All-Star:
"This week, join [Kevin Byard](https://twitter.com/KB31_Era) from the Tennessee Titans as he helps you build your very own game with Microsoft MakeCode Arcade!"
=> OLP new flash for Digital All-Stars

webapp/src/cmds.ts
=> fix browser download with auto-webusb

pxtblocks/blocklyloader.ts, webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2792
Fixes https://github.com/microsoft/pxt-microbit/issues/2809
=> Fix z-index, only enable collapse/expand all when appropriate

pxtrunner/renderer.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2724
=> Clear references to rendering workspace after disposing in renderer

pxteditor/experiments.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2815
=> Add feedback url for accessible blocks

cli/cli.ts, webapp/src/createFunction.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2176
@pelikhan can you check and make sure I did this right?
=> Localize types and variables in the function create dialog

webapp/src/app.tsx, webapp/src/cmds.ts
Move some deploy dialog into cmds.
=> Refactor dialogs out of app.tsx

localtypings/pxtarget.d.ts, pxteditor/experiments.ts, webapp/src/cmds.ts
Experiment closed. https://github.com/microsoft/pxt/issues/5344
=> removing outdated experiment

webapp/src/errorList.tsx, webapp/src/monaco.tsx
from: https://github.com/microsoft/pxt/pull/6852
=> Remove debug logging mistakenly left in

pxtcompiler/emitter/service.ts, pxtpy/pydecompiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2816
=> Better support for array mappings in py decompiler

webapp/src/app.tsx
For https://github.com/microsoft/pxt-microbit/issues/2179
I'm unable to repro whatever error caused the spinning, but manually throwing an error after we set the react state but before the compiler call simulates the behavior, as the react state is never restored. We should always try to recover from errors, so this resets the state so users can at least attempt to download again.
=> Add try-catch for errors in compile to rest UI state

theme/home.less, webapp/src/projects.tsx
slightly smaller, triple margin. Also quick fix so that focus shows up on view all, instead of `My Projects` (which did not have a visible change on focus)
=> fixes for view all button from design meeting

pxtblocks/blocklyloader.ts
Fix for https://github.com/microsoft/pxt-microbit/issues/2845
=> collapse but don't format

pxtlib/github.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2615
=> Don't use github token for extension search

theme/sidedoc.less
fix https://github.com/microsoft/pxt-microbit/issues/2827
=> no double bkgd on sidedocs code snippets

webapp/src/gitjson.tsx
Move collab button under "github url" button to simplify view
=> Hide collab

theme/fieldeditors.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2877
=> Update gridpicker text CSS

cli/cli.ts
Lessen a bit the noise of the cli
=> lower api caching log messages

theme/errorList.less, webapp/src/errorList.tsx
Displays a message when there are no errors. Basic functionality. 
fixes: microsoft/pxt-microbit#2832
=> added a simple message when there are no errors

cli/youtube.ts, webapp/src/webusb.tsx
=> Webusb disconnet

cli/cli.ts, common-docs/release-tests/extensions.md
=> Handle throttling / github actionify testghpkgs

cli/cli.ts
Assume cli is installed. Current strategy does not work with layout created by "pxt target microbit"
=> run pxt directly in testghpkgs

theme/home.less, theme/themes/pxt/globals/site.variables, webapp/src/projects.tsx
didn't include the video thumbnail because i couldn't figure out how to make it look good
=> Details view recolor, move youtube button

pxtblocks/blocklycompiler.ts, pxtblocks/fields/field_tsexpression.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2840
=> Fix for TS_OUTPUT block rendering and compilation

pxtlib/github.ts, webapp/src/githubprovider.tsx
If github returns 401, invalidate token.
=> automatically retry on github 401 call

webapp/src/cmds.ts
=> Check for serial property on appTarget

cli/youtube.ts, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtlib/youtube.ts, webapp/src/projects.tsx
=> youtube playlist support in home screen

pxtblocks/blocklyloader.ts
Somehow lost the PR with the flow.
=> don't flow after expand all

pxtcompiler/emitter/service.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2838
Adds recursion to our snippet generation. I added a maximum depth of 3 so that we don't get into any loops
=> Snippet recursion

cli/cli.ts
Include target id and version when compilig projects with testghpkgs/
=> stronger hash key for success build of testghpkgs

cli/cli.ts, localtypings/pxtarget.d.ts, pxtcompiler/emitter/hexfile.ts, pxtlib/github.ts, pxtlib/main.ts, pxtlib/package.ts, webapp/src/app.tsx, webapp/src/workspace.ts
Also improvements to compile switches and variants
=> Add package upgrade rules

pxteditor/editor.ts, pxtlib/webusb.ts, theme/common.less, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/editortoolbar.tsx
=> Disconnect dialog

webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2896
=> Don't allow text selection on hints in tutorials

theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2914
=> Apply HC language dropdown style to 'selected' and not 'active' item

libs/blocksprj/pxt.json, pxtlib/package.ts
Ensure config is loaded. Fix for https://github.com/microsoft/pxt-microbit/issues/2930
=> fix sidedocs

theme/errorList.less, webapp/src/errorList.tsx
Added scrolling to the error list on overflow
=> error list scrolls when overflowed

pxtlib/packetio.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/container.tsx, webapp/src/notification.tsx, webapp/src/projects.tsx
=> Packetio sim

webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2913
=> Show monaco debugger in non-main files

pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts, pxtblocks/fields/field_melodySandbox.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2947
Fixes https://github.com/microsoft/pxt-microbit/issues/2946
=> Delete connection indicators in cleanup, remove setText

theme/debugger.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2945
=> Better css for debugger in tablet size

pxtblocks/fields/field_melodySandbox.ts, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2952
Fixes https://github.com/microsoft/pxt-microbit/issues/2950
=> Fix focus issues in toolbox search and melody editor

pxtlib/webusb.ts, webapp/src/cmds.ts
Support for WebUSB when using the /multi view
=> Webusb multi

pxtsim/libgeneric.ts
Render buffer to hex in debugger variables view
=> implement debug string for buffer

theme/highcontrast.less
fix https://github.com/microsoft/pxt-microbit/issues/2960 
(was purple)
=> fix homescreen high contrast bugs

webapp/src/monacoEditAmendments.ts, webapp/src/monacopyhelper.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2905
Adapting the indentation fixes so that we can use the same logic on edit amendments
=> Apply indentation fixes to edit ammendments

cli/youtube.ts, pxtlib/youtube.ts
=> Download playlist fixes

pxtblocks/blocklycompiler.ts, webapp/src/blocks.tsx
=> Highlight collapsed block when in slowmo/trace

theme/errorList.less, theme/themes/pxt/globals/site.variables, webapp/src/errorList.tsx, webapp/src/monaco.tsx
Error messages are now clickable and lead to the corresponding error
=> jump to error when the message is clicked

pxtblocks/fields/field_imagedropdown.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2847
=> Unset max-height on image dropdown close

pxtlib/github.ts, webapp/src/githubprovider.tsx, webapp/src/gitjson.tsx, webapp/src/package.ts
Does not handle conflict/merge yet. Eventually we should always merge ourselves too.
=> Support for happy-path PR merge

pxtpy/converter.ts
fixes https://github.com/microsoft/pxt-microbit/issues/2653
are there any python tests running on build?
=> Correct is-module check

webapp/src/gitjson.tsx
Add confirm dialog when merging branch
=> Confirm merge button

cli/cli.ts
Add multi.html in the list of files to write to get pxtConfig
=> rewrite multi.html

theme/errorList.less, theme/themes/pxt/globals/site.variables, webapp/src/errorList.tsx, webapp/src/monaco.tsx
Added the suggestions given
- zebra stripe
- lead with line number
- red notification color
- reduced padding around header
- go to end of error with cursor
=> error list design meeting changes 2

pxtlib/github.ts, webapp/src/app.tsx, webapp/src/coretsx.tsx, webapp/src/dialogs.tsx, webapp/src/githubprovider.tsx, webapp/src/gitjson.tsx, webapp/src/projects.tsx, webapp/src/workspace.ts
=> UI improvments to merge

webapp/src/app.tsx
=> fix routing to python tutorials

docs/multi.html, webapp/public/multi.html
Allows starting 2 different tutorials, split the hash a ``:|:`` and send each part to the each iframe.
=> multi route hash to both frames

theme/errorList.less, webapp/src/errorList.tsx
error list now collapses when clicking anywhere in the header
fixes microsoft/pxt-microbit#3004
=> error list now collapses when clicking anywhere on header

pxtcompiler/emitter/driver.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2978
Check out the conversation in https://github.com/microsoft/pxt-microbit/issues/2978 for more info.
=> Disable incremental semantic diagnostics call

webapp/src/serviceworker.ts
Maybe this will fix https://github.com/microsoft/pxt-microbit/issues/2760? No real way to tell without releasing. Should be safe either way! I checked to make sure that uglify doesn't "fix" this too.
=> Thwart uglify's attempt to be clever and remove my workaround

webapp/src/errorList.tsx, webapp/src/monaco.tsx
fixed the issue where the first or last few lines of code would be unreachable when scrolling
fixes microsoft/pxt-microbit#2824
=> can scroll to last few lines of text editor when error list is open

cli/cli.ts
Need to make sure the child processes also force using github proxy
=> CLI env var to force github proxy

cli/cli.ts, cli/nodeutil.ts, pxtlib/util.ts
In fast, mode the testghpkgs is not checking the extension tag number and simply looking at the status file directly.
=> fast mode for testghpkgs

webapp/src/githubprovider.tsx, webapp/src/gitjson.tsx
=> fork dialog

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/3049
=> resend breakpoints for python

webapp/src/monacopyhelper.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3041
=> Don't treat newlines as indents

localtypings/pxtpackage.d.ts, webapp/src/app.tsx, webapp/src/container.tsx
=> Markdown rendering
