localtypings/pxtarget.d.ts
package-lock.json
webapp/src/browserworkspace.ts
webapp/src/db.ts

Allows side by side of projects from different major versions
First time a user goes to a major version for which there are no scripts, we check if there are projects from the previous major version. If there are, the scripts are copied as-is using a new DB key that has a prefix (specified in pxtarget.json). From that point on we use the prefixed IDs for all project-related local storage operations, meaning projects from the previous version are unaffected. If we detect projects with prefixed IDs, then we assume the migration has already happened and don't migrate again.
This essentially forks all user projects from a previous major version, into new projects on the current major version. Projects are completely independent from that point on.

Support localstorage prefixes for different major versions

---

cli/cli.ts
pxtwinrt/deploy.ts
pxtwinrt/winrtworkspace.ts
webapp/src/cmds.ts

- Fix the v1 build logic to support our `prepend` property, which was in v0
- dap.js was being omitted from the v1 micro:bit build because of that
- Minor fix to the WinRT workspace to be compatible with the workspace revamp
- Fix UWP file saving for micro:bit v1

Tweaks to UWP app to support microbit v1

---

package-lock.json
pxtcompiler/emitter/service.ts
pxtlib/package.ts
webapp/src/blocks.tsx
webapp/src/monaco.tsx
webapp/src/toolbox.tsx
webapp/src/toolboxeditor.tsx

- Extract subcategories strings
- Copy groups and subcategories translations to the main editor translations so they can be used
- Fix React duplicate key bug with subcategories
- Fix flyout headers of subcategories by showing only the localized subcategory name
- Previously, it was showing the non-translated category, followed by the non-translated subcategory
Fixes https://github.com/Microsoft/pxt-microbit/issues/958

Make groups and subcategories localizable

---

theme/common.less

Note this is a v0 pull request! @abchatra and I made a change to support the notification banner in V0 and it ended up affecting the cookie banner as well. This fixes that issue along with a another I found while testing (the simulator was positioned incorrectly when the notification banner shows on tablet/mobile view)
Fixes https://github.com/Microsoft/pxt-microbit/issues/1000
Fixes https://github.com/Microsoft/pxt-microbit/issues/997

Fixing CSS for notification and cookie banners

---

pxtblocks/fields/field_note.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/931
Updating the logic for the piano field editor so that it matches its color with whatever block it is nested in. If a block has only one field then it also doesn't have a color because single-field blocks render just the field edge-to-edge. In that case we need to get the color from the parent block or else it ends up looking arbitrary.

Fixing the color of the piano editor when not a shadow block

---

webapp/src/projects.tsx

Removes the sanitization logic of generating project name from an example, because:
1. micro:bit v0 didn't have it and we never had an issue
2. It wasn't completely working (having more than 1 space, or weird characters, would still slip through)
3. It should be up to consumers of the project name to do proper sanitization for their needs (e.g. file workspace converting it to a name suitable for the file system)
Fixes https://github.com/Microsoft/pxt-microbit/issues/870

Fix project names from examples

---

webapp/src/package.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/906
There was an extra `\s` at the end of the regex which meant that special characters had to be followed by a space in order to be successfully sanitized. I got rid of that `\s`.
I also took the opportunity to add a bunch of characters we want to sanitize.

Fix sanitize regex and add several forbidden characters

---

webapp/src/app.tsx
webapp/src/core.ts
webapp/src/coretsx.tsx

Fixes https://github.com/Microsoft/pxt-microbit/issues/1044
Also, the input option that was being passed to the confirm modal before had no way of getting the result (probably lost in some refactor somewhere) so I removed it. It was duplicating the functionality of the `promptAsync` anyhow.

Fix save dialog

---

theme/tutorial.less

Fixes https://github.com/Microsoft/pxt-microbit/issues/932
`50vh === 50% of viewport height`

Adding max-height for tutorial hint previews

---

pxtlib/browserutils.ts
webapp/src/dialogs.tsx

Fixes https://github.com/Microsoft/pxt-microbit/issues/1063
Looks like it was originally [removed](https://github.com/Microsoft/pxt/pull/4436) because the link was wrong. I've brought it back and fixed that issue. Also, I'm now using the service ID in place of "C++" so instead of reading `C++ runtime version` it now reads `microbit runtime version`. 
@mmoskal can you take a quick look and let me know if I'm using the correct fields from pxtarget?

Bring back the C++ runtime version in the about dialog

---

pxtlib/service.ts
webapp/src/app.tsx

Required to port UWP app flashing timeout popup to v0

Expose confirmAsync to extensions' deployCore method

---

pxtblocks/mathOperations.ts
pxtcompiler/emitter/decompiler.ts
pxtlib/blocks.ts
tests/decompile-test/baselines/math_infix_ops.blocks
tests/decompile-test/cases/math_infix_ops.ts

We are getting to the point where it might make sense to add some code to filter what appears in this block so it can be controlled per-target
Part of https://github.com/Microsoft/pxt-microbit/issues/1062

Adding idiv and imul to the math operation block

---

cli/buildengine.ts
pxtlib/cpp.ts

This enables docker build if `appTarget.compileService.dockerImage` is set - no need to install `cmake` or ARM toolchain. Works for CPX and microbit

Enable local build in a docker container

---

common-docs/faq.md

Typo in the 'can't find question' section heading.

Fix `question not found` section

---

pxtcompiler/emitter/service.ts
webapp/src/monaco.tsx

Fixes https://github.com/Microsoft/pxt-microbit/issues/925
This PR fixes three issues:
1. Enum arguments were always being replaced as 0 or null (now we grab the first declared member)
2. Fixed instances of types with qualified names exported from a namespace (e.g. `input.Button` rather than top-level `Button`) were generating weird snippets with the namespace showing up twice
3. The Monaco toolbox was ignoring default values for variable blocks. This was affecting a few of the changes I recently made in pxt-microbit for the image and game blocks

Fixing monaco snippets for fixed instances, enums, and block definitions

---

pxtlib/service.ts
tests/blocklycompiler-test/commentparsing.spec.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/1090
Makes the block definition parser no longer error out if the definition is incorrect. Style marks still cannot go across any boundary that causes a new input to be added to the block (e.g. a parameter or a pipe) but now we'll leave in the old text and continue on instead of returning undefined.

Making the block definition parser a bit more forgiving

---

cli/buildengine.ts
cli/cli.ts
cli/gdb.ts
pxtcompiler/emitter/emitter.ts

Also:
* use a pipe instead of a socket to invoke gdb; now tested on mac and win
* allow setting `PXT_NODOCKER` to force non-docker build
* bugfix for compilation failure in Adafruit (neopixel init)

 Add 'pxt dumplog' to dump codal's log

---

theme/common.less

Microsoft logo is missing https://github.com/playi/pxt-wonder/issues/302
Root Cause:
Microsoft made a change to only show the 'Powered by Microsoft' logo when a certain variable is set. (Microsoft@65b8393#diff-9cebd1b4c653e57f52e3047257bc1adf)
However, in the 'poweredbylogo' .less classes that adjust the logo for various media, the @poweredBySmall and @poweredByLarge variables that set the background-image links are still set to be 'none'. To set these variables to actual urls based on the 'includePoweredByLogos' value, we need to call the .includePoweredByLogos() in each style block.
(FYI. I tried having the .includePoweredByLogos() outside of each specific poweredbylogo class, calling that function immediately after defining it in pxt code site.variables file, and calling that function …

Microsoft logo is missing even when setting @includePoweredByLogos

---

pxtblocks/fields/field_ledmatrix.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/1095
The issue was that the event that ended the touch gesture in iOS was incorrect (we were subscribing to `mouseup` instead of `touchend`).
Tested in Edge, IE, Chrome, Firefox, Safari, and mobile Safari (via the simulator, not a real device).

Fixing iOS touch events for matrix field

---

pxtblocks/blocklyloader.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/1050
Removes the type bumping behavior of the Blockly comparison block.
Where once there was this:
Now there is this:
The weird outline bug is unrelated

Allow any two types to be compared in blocks

---

pxteditor/editor.ts
pxteditor/editorcontroller.ts
webapp/public/controller.html
webapp/src/app.tsx

Adding a pxt controller command for setting the trace state in the editor (the only one that was surfaced was a toggle).
Also fixes a race condition with binding the editor messages and a bug where any target that had `allowParentController` set to true can only be served in an iFrame. Previously you could serve both in and out of an iFrame but the new iFrame workspace provider blocks on a message from the host.
I probably should have done this in separate commits...
@dragonx

Fixing some bugs with iframe controller scenario and adding settracestate

---

pxtcompiler/emitter/service.ts
pxtlib/service.ts

Needed for https://github.com/Microsoft/pxt-microbit/issues/907 and other scenarios where we deprecate APIs and replace them with different APIs that have the same block definition. This lets us leverage existing translations.
Note that this partially undoes https://github.com/Microsoft/pxt-microbit/issues/907, but it wasn't clear why we stopped extracting deprecated API strings, as those blocks can still appear in user projects. Maybe @pelikhan can explain when he's back?

Allow reusing translations of other APIs

---

theme/scriptsearch.less
webapp/src/data.ts
webapp/src/scriptsearch.tsx

Adds a spinner for search. This is especially important with our backend now indexing and caching packages, since it can take up to 8 seconds to perform a search (for the unlucky user that hits our backend cache reset, happens once every 5min).
Current experience:
With this change:
Some notes:
- With this change, the search bar and button are disabled while a search is in progress
- For both the current experience and this change, subsequent searches are very fast
Fixes https://github.com/Microsoft/pxt-microbit/issues/1121

Ext search spinner

---

Jakefile.js

We generate a font for the icons included in the `svgicons/` directory and they get assigned random codepoints in alphabetical order. Usually that's fine because we create a css file and it has classes that hide you from having to know the codepoint (just like what semantic does for fontawesome). However, it turns out we reference the codepoint directly in the Blockly toolbox so when I recently added an icon it changed the function category's icon into something else.
This change sets the codepoints for all of the icons that we reference in that manner. The values are pretty arbitrary and all of the other icons will still get random codepoints based on alphabetic order.

Fix function category icon

---

tests/blocklycompiler-test/test.spec.ts

We've had a bunch of timeouts in Travis builds that have been fixed by restarting the build, so let's just bump the timeout a bit

Increase compile test timeout to 5000

---

pxtcompiler/emitter/emitter.ts

This is part of the fix for https://github.com/Microsoft/pxt-microbit/issues/628
Another part of the fix needs to go on the micro:bit side

Emit 255 for lit pixels in image literals

---

pxtcompiler/emitter/emitter.ts
tests/compile-test/compilerunner.ts
tests/compile-test/lang-test0/45enumtostring.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/1156
Here's a snippet that shows the issue:
```typescript
enum Switch {
On,
Off
}
let x = Math.randomBoolean() ? Switch.On : Switch.Off;
basic.showString(`${x}`)
```
The Typescript compiler interprets the type of x as `Switch.On | Switch.Off`

Handle to string for union types

---

pxtcompiler/emitter/decompiler.ts

This fixes two tutorial issues:
1. The first pass by the decompiler (which pulls out functions and enums) wasn't running for tutorial snippets because we put each snippet in a code block to prevent name collisions
2. Reference errors were being thrown because not every symbol in the snippet code was making it into the API info passed to the decompiler (the API info is created with the user's code, not the snippet code). Usually we shove in fake comment attributes for these symbols so I replicated that behavior here.

Changes to decompiler to support tutorials

---

common-docs/reference/math/from-char-code.md
common-docs/reference/string.md
common-docs/reference/text.md
common-docs/reference/text/parse-float.md
common-docs/reference/text/parse-int.md
docs/static/playground/pxt-common/pxt-core.d.js
docs/static/playground/pxt-common/pxt-helpers.js
libs/pxt-common/pxt-core.d.ts
libs/pxt-common/pxt-helpers.ts
pxtsim/libgeneric.ts

Fix for https://github.com/Microsoft/pxt-microbit/issues/1028
Adds support for "parseFloat" (which is renamed to "parse to number"  in blocks). Currently, parseInt does not fully follow the JS semantic, i.e. parseInt("1e1") in JS is 1 while it would be 10 in MakeCode. Our simulator and C++ have the same behavior so I assume this is fine.
The String_::toNumber function in MakeCode microbit v1 already actually parses floating point numbers (https://github.com/Microsoft/pxt-microbit/blob/v1/libs/core/core.cpp#L251)

support for parse-float / parse to number

---

webapp/src/monaco.tsx

With this change, the monaco toolbox only shows up for main.ts.

Don't show monaco for package files

---

theme/print.less

Render blocks in bw to maximize readability in low-res printers.

render block as bw outlines

---

pxtcompiler/emitter/decompiler.ts
pxtcompiler/emitter/emitter.ts
tests/decompile-test/baselines/string_append.blocks
tests/decompile-test/cases/string_append.ts

Handle += operator for strings in script ==> blocks conversion. Fixes #4634.
converts
```ts
let out = "hello ";
out += "world";
```
to the blocks for
```ts
let out = "hello ";
out = out + "world";
```
(previously assumed the values being +='d were numbers, so it would pass the check step and then fail to decompile for anything besides appending a number to the string)

Handle string += operator in decompiler

---

localtypings/pxtarget.d.ts
webapp/src/container.tsx
webapp/src/editortoolbar.tsx

Requested by LEGO. Flag "saveInMenu" hides the save icon.

Add option to hide "save" in gearwheel

---

pxtlib/package.ts

The field should never be present in `pxt.json` - it's temporary.
The `|| "\n"` didn't make any sense either - `JSON.stringify` never returns `null` or `""`

Remove additionalFilePaths field when saving config (Fixes #4666)

---

localtypings/blockly.d.ts
pxtblocks/blocklylayout.ts
pxtblocks/blocklyrenderer.ts
pxtrunner/renderer.ts
theme/print.less
theme/tutorial.less

Tested in Edge, IE, Chrome, FF / Windows.
This PR does not solve the "sidedocs" printing issue introduced by the "go back" button.

print fixes

---

pxtblocks/blocklylayout.ts
webapp/src/app.tsx

Fixes https://github.com/Microsoft/pxt-microbit/issues/1249 (kinda)
Fixing a couple of exceptions for IE in tutorials. The first one was caused by a change I made to fix screenshots in Edge. IE throws an exception but it can be safely ignored.
The second bug causes the site to freeze when exiting a tutorial and loading the editor. The browser crashes on a call to `Date.now()` saying that `Date` is undefined. @abchatra and I spent a while debugging but it sure looks like this is an IE bug. Instead of devoting more time to a proper fix we decided to just avoid the codepath in IE and go to the home screen instead of opening the editor.

Working around some browser exceptions in IE that break tutorials

---

docfiles/style.css
pxtblocks/blocklylayout.ts
pxtblocks/blocklyrenderer.ts
pxtblocks/codecardrenderer.ts
pxtrunner/renderer.ts
pxtrunner/runner.ts
theme/print.less
webapp/public/docs.html
webapp/src/app.tsx

Various blocks docs/print optimizations. Tested in Edge, IE, Chrome, FF on Windows. It fix most of the print issues of game of life.

Print code fix

---

webapp/src/container.tsx
webapp/src/greenscreen.tsx

```
On iPhone, <video playsinline> elements will now be allowed to play inline, and will not automatically enter fullscreen mode when playback begins.
<video> elements without playsinline attributes will continue to require fullscreen mode for playback on iPhone.
When exiting fullscreen with a pinch gesture, <video> elements without playsinline will continue to play inline.
```

Green screen update.

---

theme/tutorial.less

When using inline blocks, the padding and border can make the block overlap the adjacent lines.

Smaller inline blocks to avoid overlapping other text

---

pxtlib/util.ts
pxtrunner/runner.ts
webapp/src/app.tsx

Docs pages only load sim strings which breaks translations of snippets. Simplify logic. FIx for https://github.com/Microsoft/pxt-ev3/issues/765

Always load translations

---

webapp/src/package.ts
webapp/src/workspace.ts

workspace.computePath strips out all non-ascii character so for script languages, nothing is left. We need a better fix in the future.

Unicode names

---

webapp/src/iframeworkspace.ts
webapp/src/memoryworkspace.ts

In the workspace refactor there were a few accidental breaking changes in the `workspacesync` message. This restores the old behavior.
I will also open this PR against stable 3.22

Fixing some iframe workspace bugs

---

webapp/src/coretsx.tsx
webapp/src/simulator.ts

We are hitting a bug in Edge when the simulator is revealed while a dialog is open. It repros about 50% of the time but I've managed to hit it several times on accident and I know @abchatra and @Jaqster have as well. Here is a gif of the bug:
The only workaround I've been able to find is forcing the document to redraw by quickly blinking the page. It's definitely noticeable but I think it's acceptable given that I've guarded the code so that it only happens in a pretty specific scenario:
BTW this isn't micro:bit specific; you can repro it in all of our editors in Edge.

Workaround for edge render bug on simulator reveal

---

package-lock.json
pxtlib/emitter/cloud.ts

Adjust downloadMarkdown logic to account for the changes in https://github.com/Microsoft/pxt/pull/4689, which writes links as `docs/foo` rather than `/docs/foo` (we were testing for the leading slash)
Fixes https://github.com/Microsoft/pxt/issues/4700

Fix downloadMarkdown regex for staticpkg

---

pxtlib/commonutil.ts
pxtlib/emitter/cloud.ts
pxtlib/util.ts
webapp/src/db.ts

The translations are stored in a db, along with the ETag. There is a 5 minute expiration in the db after which the ETag might be tested again. ETag is only checked once per browser sessions (once per 24h) to avoid requesting it multiple times during a single sesion.
This should not impact the cloud.

use same domain /api for translations / caching

---

pxtlib/commonutil.ts
pxtlib/emitter/cloud.ts
pxtlib/gallery.ts
pxtrunner/runner.ts
webapp/src/app.tsx

Uses translation database to cache Markdown sources in indexeddb. This is shared between editor and sidedocs.

Markdown caching

---

pxtsim/utils.ts

Fixes https://github.com/Microsoft/pxt-ev3/issues/794 and https://github.com/Microsoft/pxt-ev3/issues/795

Adding array.prototype.find as a polyfill for ie11

---

pxtcompiler/emitter/backthumb.ts

writing to `r3` clobbers a parameter

Don't use r3 for stack alignment

---

pxtlib/emitter/cloud.ts
pxtlib/util.ts

Right now, `pxt serve` and `pxt staticpkg` are broken for all targets

Fix serve and staticpkg

---

webapp/src/blocks.tsx

This is in order to account for changes in the rendering between v0 and v1 that makes the block sizes bigger (for larger touch targets) and in turn the perceived font size is smaller. 
To account for these changes, I'm tweaking the default zoom level a tad.
These are the microbit defaults side by side: 
Fixes https://github.com/Microsoft/pxt-microbit/issues/1230

Increase the default zoom level

---

localtypings/blockly.d.ts
pxtblocks/fields/field_ledmatrix.ts

Determine the OFF colour of leds based on the parent block's primary colour.
Instead of having a static default colour, this change uses the block's primary colour and lighten's it by 60% in order to determine the LED matrix's OFF colour. 
Here's an example: 
Notice how the colours of the leds are different when the parent block's colour is blue vs purple. 
https://github.com/Microsoft/pxt-microbit/issues/1317

Determine the OFF colour of leds based on the parent block's primary colour.

---

theme/blockly-core.less
theme/themes/pxt/globals/site.variables

Add a less variable for the blockly flyout button color for targets to possible change.
By default the flyout button uses the primary color as the stroke color, this is still the case, but now it's behind a variable that can be altered by targets. 
Eg:

less variable for the blockly flyout button color

---

cli/cli.ts

This is the current message being generated:
Been bugging me for some time

Remove trailing comma in commit message of pxt bump

---

localtypings/pxtarget.d.ts
pxteditor/editor.ts
webapp/src/accessibility.tsx
webapp/src/app.tsx
webapp/src/projects.tsx

After creating a new empty project, pop up the "change board" dialog to pick which board to use. Small change, good reuse of existing UI. It only happens when the user creates new project, not when starting tutorials or other occurences. Turned on by a flag.

popup boards dialog after create project

---

docs/defining-blocks.md
docs/static/playground/samples/basic/inline/sample.js
docs/static/playground/samples/field-editors/color/sample.js
docs/static/playground/samples/field-editors/dropdowns/sample.js
docs/static/playground/samples/field-editors/note/sample.js
docs/static/playground/samples/field-editors/protractor/sample.js
docs/static/playground/samples/field-editors/speed/sample.js
docs/static/playground/samples/field-editors/toggle/sample.js
docs/static/playground/samples/field-editors/turnratio/sample.js
docs/static/playground/samples/language/create-enums/sample.js
pxtlib/service.ts
tests/blocklycompiler-test/commentparsing.spec.ts

Adding some syntax for setting shadow block ids outside of the block string. Hopefully this will make changing shadow blocks without breaking localizations a bit easier. The new syntax overrides the old syntax and I would say the old syntax should be considered "deprecated".
The proposed syntax:
```typescript
//% block="whatever $param=oldShadow"
//% param.shadow="newShadow"
```
Related: https://github.com/Microsoft/pxt/issues/4757

New syntax for setting shadow values

---

docfiles/style.css
theme/docs.less

Added CSS styles for tables that better defines cells with grid lines. Also, changes the background color of every other row.
Before:
After
I wasn't sure what the pxt color scheme was, so I just went with what I thought looked best.

added css styles for tables

---

common-docs/blocks-embed.md

Sectioned the process, added more description text, and included an example HTML document.

Update the 'blocks-embed' page

---

package-lock.json
pxtcompiler/emitter/emitter.ts

We were retrieving the contextual type for a new expression... which made the following code fail:
```
export const P0: PwmPin = new MicrobitPin(DigitalPin.P0);
```
because PwmPin is an interface implemented by the class MicrobitPin. Obviously, you can't new on an interface. The fix is to use the type of the new expression rather than the contextual type.

incorrect type retrieved for new expression

---

webapp/public/run.html

https://github.com/PierBover/ios-iframe-fix
Tested in Chrome, Firefox, Edge, IE, and iOS Safari. Also tested the micro:bit embed to make sure I didn't break it, and everything seems fine. I didn't test that on iOS because I didn't have the dev environment set up for pxt-microbit.

Fix embedded --run iframe on iOS

---

pxtblocks/fields/field_ledmatrix.ts

Change led Matrix from red to white for fill with the block's tertiary color as the OFF color.
This fixes the Red Blue optical illusion issue we have described here: https://github.com/Microsoft/pxt-microbit/issues/1349
Here's what it looks like: 
Fixes https://github.com/Microsoft/pxt-microbit/issues/1349

Updates to LED matrix fill color

---

pxtsim/embed.ts

Using "eventbus" instead of "event" which is way overloaded in our messages.

consistent naming of simulator eventbus message

---

cli/cli.ts

Noticed that image entries had dups in manifest.
```
https://pxt.azureedge.net/blob/ef119c4a79521b684911845e2db6574a1dfeac18/static/logo.svg
https://pxt.azureedge.net/blob/0f4500e3a481806886a11950e844bfe379a30019/static/logo.square.svg
https://pxt.azureedge.net/blob/0f4500e3a481806886a11950e844bfe379a30019/static/logo.square.svg
https://pxt.azureedge.net/blob/0f4500e3a481806886a11950e844bfe379a30019/static/logo.square.svg
https://pxt.azureedge.net/blob/ba8bdfefe4e4e94286a85b2bc83c62452a745bc0/static/icons/android-chrome-192x192.png
https://pxt.azureedge.net/blob/ba8bdfefe4e4e94286a85b2bc83c62452a745bc0/static/icons/android-chrome-192x192.png
https://pxt.azureedge.net/blob/f5f83b8c33d027642954f4f833432de810768249/static/Microsoft-logo_rgb_c-gray-square.png …
```

Ensure unique target images in manifest

---

webapp/src/scriptsearch.tsx

Extensions help using ``"/boards"`` due to missing ``mode`` check for ``helpPath``. Check for ``mode`` added.
RE: https://github.com/Microsoft/pxt-microbit/issues/1362

Add mode check to scriptsearch helpPath

---

pxtblocks/fields/field_ledmatrix.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/1317#issuecomment-428014581

Use opacity for OFF led fill so that it works when the block is disabled

---

webapp/src/projects.tsx

Feedback from the designer.
- If the intent is for name the project, say so in the dialog
- Give only one option Done
- Close (x) should still go back to the previous state
New
Old

Changing the exit dialog to give just one option

---

webapp/src/serial.tsx

Turns out that the serial.editorTheme.lineColors entry of pxtarget was ignore by the serial editor.
Fix for https://github.com/Microsoft/pxt-microbit/issues/1380

fixing theme colors for serial charts

---

pxtlib/webble.ts

Try to send a packet transfer reset message until the partial flashing service actually request a new packet (or disconection ,etc..). Turns out that this one fails too.
* better handling of restart
* analytics

better transfer check daemon

---

pxtblocks/fields/field_imagedropdown.ts
pxtblocks/fields/field_images.ts
pxtblocks/fields/sprite/gallery.ts
theme/common.less

Touch fixes for the image dropdown picker and a few other pickers on IOS and Android.
Fixing issues with scrolling these pickers on many skews.
Tested locally and on IOS (iPhone and iPad) as well as Android.

Touch fixes for image pickers

---

theme/blockly-core.less

Update the style of the Blockly context menu to match menus in semantic css.

Blockly context menu style

---

common-docs/blocks-embed.md

Use `@homeUrl@` macro to base the URL in the example.
Re: https://github.com/Microsoft/pxt/pull/4813

Use URL macro in 'blocks-embed' example

---

pxtrunner/renderer.ts

Previously, snippets as typescript-ignore wouldn't be styled. This makes it so that highlight.js renders them as it would typescript without breaking the travis build.
Fixes Microsoft/pxt-arcade#274

Added syntax highlighting for typescript-ignore snippets

---

localtypings/blockly.d.ts
pxtblocks/blocklyloader.ts

Blockly build: https://github.com/Microsoft/pxt/pull/4842 pulled in changes that should've fixed the flickering issue when hovering on the border of a block in the flyout. Turns out we monkey patch some code that overwrites the fix. 
Tested on Chrome, Safari, Edge and IE.

Fix hover flickering issue

---

localtypings/pxtarget.d.ts
pxteditor/workspace.ts
pxtlib/main.ts
tests/format-test/formatrunner.ts
theme/themes/pxt/views/card.overrides
webapp/src/codecard.tsx
webapp/src/projects.tsx
webapp/src/workspace.ts

When multi board are enabled and a visual is available, use that image instead of stock svg.

Display board image in multi-board target

---

docs/accessibility.md
webapp/src/monaco.tsx

Someone pointed out that Ctrl+Left / Right arrows were already used in the monaco editor to jump around the code which is true. I was using that as a shortcut to get into the monaco toolbox. 
I'm changing the shortcut to jump to the toolbox to Ctrl/Cmd + Alt + T instead.
Updated the accessibility documentation to reflect that.
Fixes https://github.com/Microsoft/pxt-microbit/issues/1461

Change jump to toolbox accessibility shortcut

---

webapp/src/projects.tsx

I feel that the emoji that is shown when users are told that their project has no name is a little too sad. It makes me feel really bad when I forget to name my project before going to the homepage.
This changes the emoji when the user enters a name other than "" and "Untitled".
I also think this could be a fun way to add easter eggs into PXT. Like saving your project as certain names causes certain emojis to appear.

Made the emoji change when the user names their project

---

pxtblocks/fields/field_imagedropdown.ts
pxtblocks/fields/field_images.ts

The field images field editor supports showing text labels for each of the images. This PR fixes the issue when clicking on the label to select an item it uses the text as the value which cases problems in the generated Javascript. 
Fixes https://github.com/Microsoft/pxt-microbit/issues/1458

Fix gesture field selection

---

pxtblocks/blocklyloader.ts
webapp/src/blocks.tsx

Fixes Microsoft/pxt-arcade#249
Only include the set block (for a block with blockSetVariable) if the requested block is not a shadow block

fix display of shadow blocks with blockSetVariable

---

pxtblocks/blocklyloader.ts

Update set and change variable blocks to show the most recent variable created instead of using the top most alphabetical item.
Do not merge this change till after the micro:bit release.

Update set/change variable blocks to show most recent variable used

---

docs/writing-docs/macros.md
localtypings/pxtpackage.d.ts
pxteditor/editor.ts
pxtlib/gallery.ts
pxtrunner/renderer.ts
webapp/src/accessibility.tsx
webapp/src/app.tsx
webapp/src/compiler.ts
webapp/src/container.tsx
webapp/src/marked.tsx
webapp/src/projects.tsx
webapp/src/scriptsearch.tsx

* A board package can declare a set of supported features (pinsled)
* A tutorial/example markdown can declare a set of required board features (blinky needs pinsled)
* If multi board, allow to select compatible boards when opening a tutorial/example based on features
* compiler.newProject -> compiler.newProjectAsync (this function is async)
* moved a few "hideLoading" to .finally clause to always close up
(github does not seem to update this PR)

Board features

---

pxtblocks/fields/sprite/sidebar.ts
pxtblocks/fields/sprite/spriteEditor.ts
pxtblocks/fields/sprite/spriteFieldEditor.ts
pxtblocks/fields/sprite/tools.ts

This adds the ability to use circle and line tools in the sprite editor. By holding down shift, the pencil tool turns into the line tool, and by holding down control, the rectangle tool becomes the circle tool.
Also fixes the following bugs:
* Pencil tool not showing as selected after color is chosen while eraser tool is selected
* Tool width not showing selected on opening the editor
* Circles were previously more pointy. Changed algorithm to better reflect the Midpoint Circle Algorithm
The main bits that I think need to be discussed is which keys should change which tools and also whether or not the first click should set the circles center rather than the upper-left of the circle.
I think it should be the upper-left of the circle because that allows for future implementations of ovals …

Added circle and line tools to the sprite editor

---

pxtlib/docsrender.ts

Fix next/prev navigation links in the docs when were in a versioned editor.
Fixes https://github.com/Microsoft/pxt-microbit/issues/1490

Fix next/prev navigation links

---

webapp/src/app.tsx

When we push an editor release, the share page reloads and shows a blank project. I cannot find the issue anymore but you know the one I'm talking about.

Don't create a new project when the share page reloads

---

webapp/public/codeembed.html
webapp/public/extension.html

Don't use template literals in html and JS files as IE 11 doesn't support them.

Don't use template literals in HTML files

---

pxtblocks/blocklyloader.ts
pxtblocks/fields/sprite/buttons.ts

Fixes the buttons in the sprite editor.
Also fixes the blurry images in the gallery by scaling small images in Edge and IE. A factor of three seemed to be the lowest that still looked decent; I didn't do it for monochrome sprites because those seem to render fine without it 🤷‍♂️. This also fixes the previews in the image dropdown.

Some fixes for the sprite editor in edge

---

pxtblocks/fields/sprite/spriteEditor.ts

This switches the key used to activate circles from control to shift. Previously, it was control which has issues with Mac as control+left click is equivalent to right click.
Behavior is similar as the icon and tool stay the same while the mouse is down (i.e. drawing a circle or a line). The only difference is that since they both mapped to shift, if the shift key is let up while drawing, the tool or tools not being used will switch back.

Switched key to activate circle mode to shift

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/banned_category.blocks
tests/decompile-test/cases/banned_category.ts
tests/decompile-test/cases/testBlocks/banned.ts
tests/decompile-test/cases/testBlocks/pxt.json
tests/decompile-test/decompilerunner.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/212

Decompiler shouldn't decompile banned categories

---

pxtblocks/fields/sprite/buttons.ts
pxtblocks/fields/sprite/canvasGrid.ts
pxtblocks/fields/sprite/spriteEditor.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/204
Fixes the sprite editor icons and mouse/touch events in Safari.
My other fix for IE and Edge meant that I could just delete the whole dom-test hack. I tested this in Safari and Chrome, but not on mobile.

Fixing events and icons of sprite editor in safari

---

pxtrunner/runner.ts

Options isn't guaranteed to be passed in. 
Create a new object in that case.
Fixes https://github.com/Microsoft/pxt-microbit/issues/1511
Note: cherry pick to master once integrated

Fix blocksembed

---

pxtlib/browserutils.ts
webapp/src/app.tsx

Resize the editor again after 1 second on IOS as the order of resize events doesn't always give us the correct height / width bounds. 
We resize again to be sure.
Fixes https://github.com/Microsoft/pxt-minecraft/issues/709

Resize editor again on IOS

---

pxteditor/editor.ts
pxtsim/embed.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/editortoolbar.tsx
webapp/src/simulator.ts

Add a way to tell if the simulator is running from the project view. ``isSimulatorRunning``
Surface the projectView to targets that extend the editor.
Don't autorun unless the simulator is configured to autorun
Pipe whether or not the simulator was started with a click trigger or not to the simulator itself.

Surface simulator methods to targets

---

localtypings/pxtarget.d.ts
theme/common.less
theme/themes/pxt/elements/button.overrides
webapp/src/app.tsx
webapp/src/container.tsx
webapp/src/editortoolbar.tsx

Add temporary / internal flags to configure the toolbar to: 
- move the sim collapse view to the settings menu
- hide the project rename input
- show the run button on the right
- show a transparent editor toolbar
Note: these flags might change once we get a chance to cleanup. I've added a comment to note that they're internal.

More toolbar config

---

docfiles/style.css
pxtrunner/renderer.ts
pxtrunner/runner.ts
webapp/public/docs.html

Performance audits are very confused by our page but I'm not seeing a massive fail. It looks like most of the time is spent loading a ton of JS

Docs faster

---

webapp/src/monaco.tsx

We were assuming the block namespace is the same as the category name when inserting a snippet. 
This is particularly problematic for the new "Basic" category, but also for any blocks that use blockNamespace to specify a different namespace than the one they're under.
https://github.com/Microsoft/pxt-minecraft/issues/728

Don't assume that the block namespace is the same as the category name.

---

theme/fieldeditors.less

Bring back change to make each item a table-row to evenly distribute grid picker items
Revert https://github.com/Microsoft/pxt/pull/4899
Otherwise this happens:

Evenly distribute grid picker items

---

pxtblocks/fields/field_gridpicker.ts

400px is too wide for a default. micro:bit uses a number of grid picker for advanced blocks that don't set the width.

Use a better default for grid picker width

---

Jakefile.js
scripts/README.md
scripts/link-pxtblockly.sh
scripts/unlink-pxtblockly.sh
webapp/public/blockly.html

I've added a couple of scripts that link pxt-blockly and closure-library under built/web. 
Once blockly is linked, I've created blockly.html which uses the uncompressed blockly files instead of our version that is both compressed and built into pxtblockly.js. 
This means we can debug Blockly in the same way that we do using the Blockly playground but in PXT. 
@riknoll @guillaumejenkins @pelikhan FYI (I know you guys have asked for this over and over again, so thought I'd finally do it ha). 
@pelikhan is there any issue with hosting that blockly.html file, or should I place it somewhere else. This is only for local debugging.

Make debugging pxt-blockly in PXT easier.

---

docs/writing-docs/macros.md
pxtrunner/renderer.ts
theme/docs.less

There have been a few times writing course curriculum in which it is helpful to show bad code or code that doesn't work. I fear that students may skim through code examples and mistake bad code for code that they should copy and learn from. 
Some sort of distinction was requested in Microsoft/pxt-arcade#316
This emphasizes what bad and good code is by setting the background color to red or green (I used the same palette as GitHub). 
To use these snippets, the \```typescript-invalid and \```typescript-valid languages are specified in markdown.
The markdown used to create the sample above is as follows:
\# Valid and Invalid code snippets
\## Normal Code Snippet
\```typescript
// Normal Code
function printMessage() {
&nbsp;&nbsp;&nbsp;&nbsp;console.log("This is what a normal code snippet …
```

Valid and invalid code snippets

---

common-docs/experiments.md

Make a base page for 'experiments' as the help link destination for the experiments dialog.
RE: https://github.com/Microsoft/pxt-microbit/pull/1550#issuecomment-433787557

Move 'experiments' page to common-docs

---

theme/tutorial.less
webapp/src/editortoolbar.tsx

Always show zoom controls.
Fixes https://github.com/Microsoft/pxt/issues/4885
Don't hide the editor toolbar in tutorial mode. 
Fixes https://github.com/Microsoft/pxt-minecraft/issues/538

Add zoom controls and don't hide the editor toolbar in tutorial mode

---

theme/common.less

Fixes https://github.com/Microsoft/pxt-minecraft/issues/737
Lower the zindex of the transparent editor tools so that we can get to all toolbox items.

Fix z-index issue with transparent editor tools

---

webapp/src/toolbox.tsx

Fixes https://github.com/Microsoft/pxt-minecraft/issues/749

Don't show top blocks in tutorial mode

---

cli/cli.ts

Fix 1 of 2 for https://github.com/Microsoft/pxt-microbit/issues/1558
(Other fix here: https://github.com/Microsoft/pxt/pull/4952)
We've decided that:
- v0 will take tag `_v0` (a tag can't start with "v" or a number)
- master will take default tag `latest`

pxt-core@v0 now uses npm tag _v0

---

cli/cli.ts

Fix 2 of 2 for Microsoft/pxt-microbit#1558
(Other fix here: https://github.com/Microsoft/pxt/pull/4951)
We've decided that:
- v0 will take tag `_v0` (a tag can't start with "v" or a number)
- master will take default tag `latest`

pxt-core@latest now points to latest master

---

cli/cli.ts
cli/commandparser.ts

Finally got annoyed one too many time by this. 
```
$ pxt suaifdadsuif
Using target microbit with build engine yotta
target: v1.2.3 C:\gh\pxt-microbit
pxt-core: v4.3.1 C:\gh\pxt
error: Command 'suaifdadsuif' not found, use "pxt help all" to see available commands.
```

No ugly stacktrace from CLI on missing command

---

localtypings/pxtarget.d.ts
webapp/src/app.tsx

Add a pxtarget flag to not suspend the editor on visibility change.

dontSuspend pxtarget flag

---

webapp/src/projects.tsx

Use hrefs for youtube and external links, instead of a button with window.open.
No reason to use window.open in this case, we know that it's a youtube or external link when we create the button. 
This also resolves part of this issue: https://github.com/Microsoft/pxt-minecraft/issues/753

Use hrefs for youtube and external links

---

pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/simulator.ts

This PR does three things: 
- Stop the simulator when we invalidate (no need to run code that is invalidated) @pelikhan FYI
- Adds another state for the simulator called suspended, suspended is more or less the same as stop except it differentiates between a user action stop and a code (compiler / runtime error) stop. ie: if we fix the code, we will run again if the simulator is in the suspended state. Unlike if the user hits the stop button, we will continue to be stopped regardless of what changes.
Explanation:
When we hit an exception, we stop the simulator (which is equivalent to a user hitting the stop button) this means that we don't restart the simulator when a change is made and the "exception" is fixed. 
This change creates a new simulator state "Suspended" which means that the …

Suspend simulator

---

docfiles/script.html
webapp/src/app.tsx

Edit button in the share page is pointing to v0. If I have shared a page a while ago, I still would like to go to the latest instead of v0. There is a link to go to the old editor if needed.  I see most of the traffic to v0 is through this edit button. Changing the default behavior.

Default edit button in v0 will point to live

---

webapp/src/editortoolbar.tsx

Show collapsed toolbar view for headless mode in tutorial.
We always show the non-collapsed view in tutorial mode, but in the case of headless mode, collapsed view is the default and so we should show that in tutorial mode. 
Fixes https://github.com/Microsoft/pxt-minecraft/issues/746

Collapsed toolbar view for headless tutorial mode

---

webapp/src/toolbox.tsx

Fixes https://github.com/Microsoft/pxt/issues/4940
We used to have this behaviour in Blockly but when we took over the toolbox we lost it. 
Handy for kids that struggle with left / right click. Any of them should open the flyout if clicked on a category.

Handle toolbox category right click

---

cli/server.ts
pxtlib/emitter/cloud.ts

We are currently requesting the lastest targetconfig for our v0 editors, which means it's fetching the targetconfig that's in master. 
This makes it request the version in the target and if it's v0, it will go to the v0 branch to fetch that targetconfig.
Fixes https://github.com/Microsoft/pxt-microbit/issues/1525

Request a versioned targetconfig rather than latest

---

pxtlib/browserutils.ts
pxtrunner/runner.ts

The side docs in v0 don't use the version in the URL to navigate to the correct versioned docs.
Porting over this fix from master. 
This fixes the issue with v0 side docs pointing to the latest docs instead of v0 docs.
Fixes https://github.com/Microsoft/pxt-microbit/issues/1544

Point to versioned docs in side docs (v0)

---

webapp/src/simulator.ts

Only suspend the simulator if we're running.
We don't want to end up in a suspended state if we're stopped or paused.

Only suspend if we're running.

---

localtypings/pxtarget.d.ts
webapp/src/container.tsx
webapp/src/editortoolbar.tsx
webapp/src/projects.tsx

Disable explicit import and save of files in Mac and iOs, enabled now through the inGame=1 for Minecraft

Disable import and save in iOS & Mac in browser view

---

webapp/src/scriptsearch.tsx
webapp/src/sui.tsx

Hide the "go back" option in scriptsearch when the dialog is waiting on a promise resolve. This is used when a user picks up a board after opening a script or a tutorial.

add option to hide "go back" button

---

pxteditor/editor.ts
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/monaco.tsx

Fixes issue where the last line of the text editor is inaccessible when we have a powered by MS logo at the bottom. 
Fixes https://github.com/playi/pxt-wonder/issues/335

Fix text editor bottom alignment when a powered by logo exists

---

pxtlib/analytics.ts
pxtrunner/renderer.ts

I've noticed that we do not get reports when our documentation pages fail to render snippets. In fact, we don't get any analytics at all because AI is not properly initialized.
@abchatra i don't think this will mess up your stats but please double check.

enable analytics in docs / send error reports in docs

---

webapp/src/carousel.tsx

Locks dragging into vertical or horizontal mode. This fixes dragging of categories on iOS.
Tested on Edge, IE, FF, Chrome + touch. Note that FF horizontal drag is broken both in this version and released.
Try https://makecode.microbit.org/app/84911728429fc7e65b5e87bf1253d7448bcd63ef-86a1f41ea8

locks dragging into vertical or horiztonal mode

---

pxtblocks/blocklyloader.ts

PXT is in charge of disabling, we shouldn't trigger record undo when disabling a block. 
PR is into stable, will cherry-pick to master once it's in.

We don't need to trigger an undo when the editor disables a block

---

pxtblocks/blocklyloader.ts
pxtlib/toolbox.ts
webapp/src/monaco.tsx

When we did the delay loading work for Blockly https://github.com/Microsoft/pxt/pull/4976/files
we stopped supporting HSV values as a color value for namespace / block colors. 
This brings back that support. 
Fixes https://github.com/Microsoft/pxt-microbit/issues/1604

Support HSV colors

---

webapp/src/blocks.tsx

Use the group id as an identifier instead of the help callback content. 
Fixes issue run into when using the helpcallback authoring of "true" as described in this sample: 
https://github.com/playi/pxt-wonder/pull/351
Related https://github.com/playi/pxt-wonder/pull/355
Note: this is going into stable4.5 and will cherry-pick to master.

Fix group help callback identifier

---

cli/cli.ts

@pelikhan Just removing the require for keytar on stable4.5 so that it builds for WW.
This is a hack, and we should go through the CLI and remove keytar properly, but this gets the build working on Node 6.

Get build working on Node 6 for WW

---

theme/blockly-core.less

There's an issue on Edge where if the blockFlyoutButton image has a fill of none. It doesn't attach clicks to it, so clicking on it doesn't work. Making the fill transparent instead. 
I've tested this on WW and micro:bit.
This doesn't seem to current flyout buttons as they have content inside of them whereas the help button only has an image tag instead of it.
Note: cherry pick to master.

Fix help button callback click on Edge

---

localtypings/blockly.d.ts
pxtblocks/fields/field_note.ts

This change makes it so the note picker on touch devices doesn't focus on the text field and instead makes it readonly. ie: we're only able to edit the note picker using the field editor.

Fix note picker editing on Android

---

webapp/public/controller.html
webapp/src/app.tsx

There were issues reported regarding updating filters with our editor controller command "importproject".
We were merging any filters sent through importproject with the current ones set in the state. This isn't quite the desired behaviour here as what we want is any new filters to replace the current onces. 
I've added the logic to do that instead.
I've made a fix to the controller.html to make testing filters easier. 
https://github.com/playi/pxt-wonder/issues/352

Fix import project filters

---

localtypings/pxtparts.d.ts
pxtsim/visuals/genericboard.ts

Use circle instead of square for round pin connectors

use round pins when croc clips are needed

---

package-lock.json
pxtblocks/blocklyimporter.ts
pxtblocks/blocklyloader.ts
pxtblocks/blocklyrenderer.ts
tests/blocklycompiler-test/test.spec.ts
webapp/src/blocks.tsx
webapp/src/compiler.ts

Disable events while converting DOM into blockly workspace to avoid polluting data with "automatically" generated events.
* disable during load (generate create events)
* disable during clear (generates delete events)
* Tested that `create` event

disable events while loading blockly DOMs

---

pxtlib/browserutils.ts

Only rely on ratio to decide to cleanup the translation data.

less aggressive about quota cleanup

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/custom_field_editors.blocks
tests/decompile-test/cases/custom_field_editors.ts
tests/decompile-test/cases/testBlocks/basic.ts

Not sure how we haven't noticed this but we never did the work to decompile a number parameter that has min and max defined into a math_number_minmax (ie: a block with a slider field). 
If you try out any shared script that has a block with a slider, it won't work. You'll decompile to number without the slider field. 
Same for typescript to block conversion with any slider field. 
This fixes that, decompiles a number parameter where min and max are defined into a math_number_minmax and sets the correct mutation on that shadow. 
Also added / fixed decompile tests.
Ran decompilation tests and they're all passing. Verified locally with Typescript to Blocks conversion.

Fix decompilation of numbers with sliders.

---

webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/core.ts
webapp/src/coretsx.tsx
webapp/src/filelist.tsx
webapp/src/sui.tsx

This applies to prompt such as "Make a Variable" and "Make a Function".
Refactor coretsx to handle it's own input and call handlers for when the input is changed. (more React like). 
- When in a prompt, disable the ok button if no input is entered. 
- In Blockly prompts use the default value as the initial value rather than a placeholder. see: https://github.com/Microsoft/pxt-adafruit/issues/869
@Jaqster as requested.

Disable ok button when no text is entered in prompt

---

pxtlib/toolbox.ts
pxtrunner/renderer.ts

Fixes Microsoft/pxt-arcade#355
This removes images color from the toolbox colors. From what I can tell, it shouldn't be there since it isn't a default category, doesn't even have an icon, and is always defined elsewhere if used (micro:bit and arcade). Also, having it in here and defining it elsewhere was creating 2 conflicting css classes for inline blocks
This also changes the default category blocks to check what color they should be instead of just setting their value to their default color.

Fixed inline blocks coloring to reflect updated/overwritten colors

---

webapp/src/blocks.tsx

WW pointed out that if a user drags a block onto the workspace from the flyout and then immediately drags the workspace, we don't save. 
This is because we're marking the blocks editor as incomplete when a user is dragging, but that should only be the case if the user is dragging a block not the workspace. 
This adds a check for that instead. 
The code is a little ugly, I can add helper methods to check for is block dragging on the workspace in blockly later, but for now this works :)
https://github.com/playi/pxt-wonder/issues/359
note: Needs to be integrated to master.

Don't mark the workspace as incomplete if the workspace is being dragged

---

docs/blog/github-packages.md
docs/extensions/github-authoring.md

RE: https://github.com/Microsoft/pxt/pull/5032#issuecomment-440902158

Add redirect note for github auth blog

---

pxtcompiler/emitter/backthumb.ts
pxtcompiler/emitter/emitter.ts

The main fix here is  to push arguments of arithmetic boxed operation on the stack, to make sure they stay alive. Not sure if this was ever a problem, but better safe than sorry.

Make sure operator args are not GCed

---

pxtcompiler/emitter/hexfile.ts
pxtlib/polyfill.ts
webapp/src/worker.ts

We recently had an issue where Math.imul was breaking decompilation of any multiplication on IE. This issue was fixed in the worker by polyfilling Math.imul. 
Unfortunately, that wasn't the entire fix. The runner (for docs / tutorials) also calls decompilation and needs the polyfill. 
I'm moving the polyfill into pxtlib. Currently adding it at the bottom of the hexfile.ts (the file which uses the method). I don't like this, and am open to recommendations of where to place it. I didn't see any other logical place to put it in pxtlib. 
@pelikhan 
Note: this is going into stable5.1 so we can release a patch fix, but will have cherry-picked to master once it's in.
Fixes https://github.com/Microsoft/pxt-adafruit/issues/856
Tested on Chrome and IE.

Move polyfil into pxtlib so it’s part of the runner.

---

pxteditor/editorcontroller.ts
webapp/src/app.tsx

https://github.com/Microsoft/pxt/pull/4614 introduced a regression in async message passing when we're hosted in an iframe. The promise resolves (done) before it's had a chance to complete its async functionality.
This fixes up the promise chain. 
I've also fixed the editor controller "renderblocks" message which was returning the promise xml rather than completing the promise and returning the xml. 
note: this is going into stable4.5 (WW branch), will integrate into master once the PR is in.

Fix editor controller async message passing

---

pxtblocks/blocklylayout.ts

Unclear why this works without the paranthesis, but adding them just to be precise.

Instantiate DOMParser instance

---

webapp/src/blocksSnippets.ts

They are pretty low in weight and come at the bottom.

Empty array block

---

webapp/src/extensions.tsx

The consent screen for third party package extensions is broken as the full screen size doesn't support actions. (Maybe we should) but I think it's more appropriate that we show a smaller modal for that consent dialog.

Fix consent screen for third party package extensions

---

webapp/src/greenscreen.tsx

iOS requires "autoplay" on the video element to allow webcam streaming.

ios greenscreen (stable4.4)

---

pxteditor/extension.ts
webapp/src/extensionManager.ts
webapp/src/extensions.tsx

Send the target id with every package extension event.
Also send a loaded event when the frame is loaded.

Sent target id to package extensions

---

common-docs/reference/arrays/remove-at.md
common-docs/reference/arrays/reverse.md
common-docs/reference/arrays/set.md
webapp/src/projects.tsx

Fixing typos noted in Crowdin comments:
* https://crowdin.com/translate/kindscript/32/en-da#151872
* https://crowdin.com/translate/kindscript/1938/en-fr#71831
* https://crowdin.com/translate/kindscript/1938/en-fr#71836
* https://crowdin.com/translate/kindscript/1937/en-fr#71812
* https://crowdin.com/translate/kindscript/1939/en-fr#72919

Fix some typos found by translators

---

cli/buildengine.ts
cli/cli.ts
localtypings/pxtpackage.d.ts

A project can specify a "corePackage" value in pxt.json so the dal.d.ts file is generate over there. Also pxt builddaldts can be run from the target folder.

dal.d.ts generation for target

---

pxtlib/docsrender.ts

Fixes Microsoft/pxt#4534
This makes it so that if link in the docs starts with a '#', meaning it is an anchor link to the same page, it will open in the same tab instead of a separate tab.

Links that start with '#' appear on the same page instead of a new tab

---

webapp/src/projects.tsx
webapp/src/share.tsx

Share dialog allows you to name the project before sharing: 
and the exit dialog: 
Note: this only shows if the user has an untitled project, in both cases.

Name the project before sharing

---

docfiles/docs.html
docfiles/style.css
localtypings/pxtarget.d.ts
pxtlib/docsrender.ts

There's a consensus that the left/right arrows in the docs are confusing. This PR removes them.

remove left/right arrows

---

pxtblocks/blocklycompiler.ts
pxtblocks/fields/field_userenum.ts
pxtlib/commonutil.ts
pxtlib/service.ts
tests/blocklycompiler-test/fieldUserEnum.spec.ts
tests/blocklycompiler-test/test-library/enums.ts
tests/decompile-test/cases/testBlocks/enums.ts

Adds a new enum modifier flag, ``EnumIsHash`` that forces MakeCode to generate the enum values as the hash16 of the name. This is particularly useful for radio-broadcast or any other named based broadcast API where users might want to write different programs talking the same protocol.

Enum isHash

---

pxtlib/analytics.ts

Currently passing tickEvent props that are not string or numbers causes issues where it tries to send it as a measure, and app insights only accepts measures of type number, which makes it drop the event. 
This PR makes it so that we pass any string as a property. Any number as a measure.
And anything else get's stringifed and passed in as a property.

Fix tickEvent props when an object is passed in

---

docs/static/playground/pxt-common/pxt-core.d.js
docs/static/playground/pxt-common/pxt-helpers.js
libs/pxt-common/pxt-core.d.ts
libs/pxt-common/pxt-helpers.ts

This adds the ability to concatenate arrays. 
Only works with JavaScript as Blocks had issues detecting the type.
Also doesn't use rest parameters like the original JavaScript function. Only supports concatenation of two arrays at a time.

Added Array Concatenation

---

webapp/src/blocks.tsx

The following situation was fairly common when testing arcade
This was very confusing, because it looks like nothing is happening after they input - there is no indication that you have to click outside of the editor or press enter for the code to 'count' and be reflected on the screen.
This makes it so the simulator is reloaded when values are changed.

Reload simulator on changes

---

webapp/src/container.tsx
webapp/src/sui.tsx

Re-write dropdown menu sui component with better handling of blur and focus events in a more “React” way.
The dropdown component had a bunch of hangover code from a more Jquery approach to writing components, this introduces a race with blur / focus events that would sometimes block the a click on a menu item. 
I've re-written the component in a more react friendly way using the state to handle focus of the dropdown. 
The component now handles tabIndex internally so no need to set that on any child components. It will set the tabindex to it's children when it opens.
This also improves the accessibility of the dropdown menu allowing you to both use the up / down keys to navigate but also use tab navigation. 
It compiles with approach 2 in …

Re-write dropdown menu component

---

webapp/src/toolbox.tsx

Fix null color issue when no namespace color is set in an inverted toolbox setting.
Fixes https://github.com/samelhusseini/pxt-holidays/issues/7

Use metaColor instead of color for inverted toolboxes

---

Jakefile.js

During development it's handy to use source maps rather than the compiled JS.
source maps won't be included in prod.
This'll be a huge time saver!

Add inline source maps (in development)

---

theme/highcontrast.less

use 3px stroke-width in high contrast on blocks

---

localtypings/pxtpackage.d.ts
webapp/src/projects.tsx

The lesson code cards on the Arcade Homepage don't open as links because they have a cardType set to "lesson". This makes it so that if a code card has this specific cardType, it will open as a link just like those without cardTypes set.
Fixes Microsoft/pxt-arcade#374
An alternative would also be to remove the cardType from these lessons. 
The way this commit does it however allows for more flexibility in the future since it allows for being more descriptive about the cards and distinguish between lessons from links.

Made lesson code cards link to external pages

---

webapp/src/scriptsearch.tsx

Wrap in array as needed.
Fix for https://github.com/Microsoft/pxt-arcade/issues/342

urldata may come back as object instead of array

---

webapp/src/blocks.tsx

When dragging a "create sprite" block variable, automatically rev the variable name so that it generates a new variable in the workspace. This is a simple solution to avoid aliasing of variables in a block program.

when dragging create sprite, rev variable number

---

webapp/src/app.tsx
webapp/src/monaco.tsx

Fix for https://github.com/Microsoft/pxt-arcade/issues/359
This is a race that is exposed in Arcade because the editor significantly slower there. The repro is very easy: you just need to button-smash "javascript" in the toggle to loose the code. This happens because both editor are trying to transition and the code hasn't been migrated yet.
There was a flag that track that we were transitioning but it wasn't used. So that fixed it. Also turning off simulator during transition to speed it up.
Overall, state management in the editor is scatered and could use a cleanup.

Wait till transition is over before changing editor again

---

webapp/src/app.tsx

We stop the sim to free resources while converting to tS or back. Don't restart when autoRun or it leads to a double restart.
Reduce verbosity of log messages

When switching between blocks and typescript, don't double restart sim

---

pxtblocks/fields/field_sprite.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/451
I must have refactored some code and broken this with the Monaco field editor.

Don't allow invalid bitmaps in image editor

---

theme/common.less

Fix subtle Minecraft bug with z-index clash between Blockly flyout and transparent toolbar.

Fix transparent background Zindex issue with the flyout

---

theme/home.less
theme/themes/pxt/modules/modal.overrides

Does the same fix as Microsoft/pxt#5102, but for all closing icons.
Also makes the three icons, (home page, modal, and sprite editor) more consistent with each other with the same heights/widths and border-shadows.

Fixed centering for all closing icons

---

theme/common.less
webapp/src/container.tsx
webapp/src/simtoolbar.tsx

I know that GIF shows the full screen button in the sim toolbar, but after I recorded it I removed that button and was too lazy to redo it. It's redundant in the triple-toggle mode.
Tested in Chrome, Edge, IE, and Firefox.
All of the tests were done with arcade, not sure if that matters.

Use the triple-toggle view in all sandbox embeds

---

pxtblocks/blocklyimporter.ts

Blocks upgrade uses `domToWorkspace()`, which requires all blocks definition to have been registered.

Inject blocks before upgrading

---

pxtblocks/blocklyloader.ts

Blue color is impossible to identify as a variable block
Changing back to red

Changing reporter color back to red

---

docfiles/docs.js
docfiles/head.html
webapp/public/embed.js

Early semantic init

---

pxtblocks/fields/field_sprite.ts

If an image has dimensions that were not found by default (e.g. made a different sized sprite in typescript and decompiled), add those dimension to the possible resize options so that the user can cycle back to the same size with the resize button. 
(also serves as a temporary patch for microsoft/pxt-arcade#488, as then they can cycle back to 64x64 or whatever size they had instead of just losing a portion of their sprite)
(thanks @ikeras for pointing out issue)
(and excuse the wonky css in the gif, I hadn't rebuilt css since the monaco field editor update)

(image editor ) add current image dimensions to preset if non-standard

---

pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/carousel.tsx
webapp/src/codecard.tsx
webapp/src/projects.tsx

Landmarks:
Only show home landmarks when in home, only show editor landmarks when in editor. 
Added landmarks for each of the carousels on the home screen such that it's made up of: 
-banner
-main
-regions for each carousel
Editor landmarks are: 
-banner
-main
-complementary for editor toolbar, and sim toolbar
-region for the simulator iframe
Added labels for the next / previous buttons in the home screen (See more, and See previous)

Fix some accessibility bugs found using Keros

---

webapp/src/pxtjson.tsx

added back button on project settings view

---

webapp/src/app.tsx
webapp/src/share.tsx

Fix project name loading when the editor is publishing.
Only commit project new name when we hit publish.
Fixes https://github.com/Microsoft/pxt-arcade/issues/507

Share modal fixes

---

pxtsim/simlib.ts

Was trying to make snare drums with the new noise support and realized the envelopes don't work in the simulator. Looks like the AudioContext uses seconds instead of milliseconds.

Audiocontext uses seconds not milliseconds

---

pxtcompiler/emitter/service.ts
webapp/src/compiler.ts
webapp/src/data.ts
webapp/src/scriptmanager.tsx
webapp/src/workspace.ts

Fix issues reported with project duplicates. Found that we were returning the old header instead of the new header when duplicating which created some unexpected behaviour when deleting a duplicated project. 
Fixed issue where the sort order wasn't accounted for in the internal model which meant that we were interacting with a different order of scripts for deleting / duplication / editing.
Better duplication algorithm that uses the pound sign as an indicator of a project number and increments that number. 
Invalidate search header scripts when headers are invalidated, such that duplicating / deleting a project refreshes the search set.

Script manager duplication fixes

---

webapp/src/monaco.tsx

Fixes https://github.com/Microsoft/pxt-arcade/issues/469
Fixes https://github.com/Microsoft/pxt-arcade/issues/447
Changes the folded sections to two lines instead of one (uglier, but less buggy). Also respect when the editor is read only.

Monaco field editor fixes

---

theme/common.less

When trasitioning between the 3 views, feels weird to have the menu go dark.

keep menu visible when simulator is up

---

pxtblocks/blocklylayout.ts
pxtlib/svgUtil.ts
webapp/src/tutorial.tsx

Tutorial mobile / iOS

---

cli/gitfs.ts
localtypings/pxtarget.d.ts
pxteditor/editor.ts
pxtsim/embed.ts
webapp/src/app.tsx
webapp/src/screenshot.ts
webapp/src/share.tsx
webapp/src/workspace.ts

* new option in cloud to enable uploading screenshots along with published script.
* renders chrome around screenshot if saveAsPNG enabled. Chrome is rendered on the fly based on pxtarget info, no customization.
* share dialog display published screenshot
Note that there is still a few issues around having the simulator stopped and not having a screenshot to save into but it will be part of a different PR.

Upload screenshot with script

---

webapp/src/app.tsx
webapp/src/container.tsx
webapp/src/projects.tsx

Fix for https://github.com/Microsoft/pxt-arcade/issues/539, move variants atop dialog.

use choose hw variant dialog when applicable

---

docs/static/playground/pxt-common/pxt-helpers.js
libs/pxt-common/pxt-helpers.ts
pxtblocks/blocklycustomeditor.ts
pxtblocks/fields/field_toggle_winlose.ts

If this gets merged before https://github.com/Microsoft/pxt-common-packages/pull/634 I'll update that PR to use this, or just add another one later

win / lose toggle for game over

---

localtypings/pxtarget.d.ts
pxteditor/editor.ts
pxtsim/embed.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/container.tsx
webapp/src/share.tsx
webapp/src/simulator.ts
webapp/src/sui.tsx

2 changes: simulator in share dialog + no-autorun mode with clear icons on simulator.
When an editor supports screenshots for the simulator, host the simulator in the sharing dialog and allow use to snap the right screenshot. It increases the quality of the shared scrips since it has more changes to have a good screenshot. Tested in Chrome, IE, Firefox (Edge untestable right now).
**ps:** we should consider disabling autoRun on slow machines for micro:bit as well.
**pss:** we need a quantitative analysis of compile times in the wild
Using the embed lightbox rendering to clearly display what's going on with the simulator.
Test: https://arcade.makecode.com/app/6947d73e04dfb5a9c38493e483656230cdca3168-7e1ebf74e5

Embedded simulator with screenshots in share dialog + no auto-run

---

webapp/src/app.tsx
webapp/src/share.tsx

Don't restart simulator when hosting in sharing dialog.
Fixing "shouldstartsimulator" to avoid starting simulator when already running or starting.

Faster sharing

---

pxtsim/simdriver.ts
theme/common.less
webapp/src/projects.tsx
webapp/src/share.tsx
webapp/src/sui.tsx

Share dialog fixes for Edge

---

pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/screenshot.ts

If the simulator is still loading, no PNG is available. Yet, we should still save something.
https://github.com/Microsoft/pxt-arcade/issues/578

Save png when no png

---

pxtsim/simdriver.ts
webapp/src/app.tsx

Since our load time is pretty bad, we end having a simulator pane empty for 10sec. This change "preloads" an empty simulator that will be spinning until the first compile arrives. Also fix the box resize in arcade (see other PR)
Tested on Chrome, IE, Edge, FF,
https://arcade.makecode.com/app/e23b69695f19549a992c4a2c85930b495c5cf64f-7dd67bf480

preload simulaor iframe to avoid blank hole for long

---

theme/common.less
webapp/src/app.tsx
webapp/src/simtoolbar.tsx

Support fullscreensim in all views. Toggle happens by clicking simulator in smaller views. Tested Chrome, Edge, IE, FF
https://arcade.makecode.com/app/273004070eb4db74833e3728e03d1939a8e06784-21300a2dc9

Tablet fullscreen

---

webapp/src/share.tsx

Screenshot triggers a props update which overrides the local name. Keep a flag to track if the project name has been changed locally.
Fix for https://github.com/Microsoft/pxt-arcade/issues/641

don't allow props to override name if local changes

---

pxtsim/simdriver.ts

Make sure _currentRuntime is ready before starting a frame, as it may have started faster than the compiler. The fix guards the startFrame function against missing runtime.
Fix for https://github.com/Microsoft/pxt-arcade/pull/656#issuecomment-455402398
Fix verified.

guard from missing runtime

---

package-lock.json
pxtblocks/blocklyrenderer.ts
pxtblocks/codecardrenderer.ts
pxtrunner/renderer.ts
pxtrunner/runner.ts
theme/themes/pxt/views/card.overrides

Adding "forceCompilation" flag for editors like micro:bit where we produce a .hex file (we should really generate it lazily instead)

Namespace rendering + cards fix

---

cli/cli.ts
docs/extensions/pxt-json.md
localtypings/pxtpackage.d.ts
pxtlib/cpp.ts
pxtlib/package.ts
webapp/src/package.ts
webapp/src/scriptsearch.tsx

This brings down maker build time down to earth (5x probably).
This works by reusing the same C++ image for all boards with the same MCU (by including a bit more C++ than strictly needed). From docs:
> Dependencies under `cppDependencies` are only considered when generating code for the C++ compiler. Usually, one would list all optional packages which contain C++ code in `cppDependencies` of your core package. Then, when user actually adds any of these optional packages, the C++ code doesn't change and re-compilation (and thus cloud round-trip) is not required.
@abchatra this should not affect Arcade, but I guess can wait until after release

faster maker build

---

docfiles/pxtweb/cookieCompliance.ts

Don't show the cookie banner when noCookieBanner=1 is passed.
Note: this still drops a cookie but it's used for editor controllers to not show the cookie banner when we're embedded in an iframe.
Tested locally.

Don't show the cookie banner when noCookieBanner=1 is passed

---

pxtblocks/blocklycompiler.ts

Thanks to @RoboErikG for finally nailing down a repro for this bug!
To reproduce the bug in arcade.makecode.com:
1. Drag out the `set list to number[]` block from the arrays category
1. Drag out the `for value of list` block from the loops category
1. Drag out the `set sprite list to array of sprites of kind` block from the arrays category
1. Change the list variable in the for-of block to the `sprite list`
1. Observe as we try to turn everything into a number array
That's one way to do it, but the bug was actually that we were leaking type information between block compiles so I have a feeling it showed up in other places as well.

Fixing arrray inference bug

---

pxtlib/sprite-editor/buttons.ts
pxtlib/sprite-editor/header.ts
pxtlib/sprite-editor/reporterBar.ts
pxtlib/sprite-editor/spriteEditor.ts
theme/spriteeditor.less
webapp/src/monaco.tsx
webapp/src/monacoFieldEditorHost.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/470
More specifically:
1. Fixes toggle layout when created off-screen
1. Fixes the font, cursor, and select behavior of text when the field editor is in Monaco
1. Fixes the toggle behavior of the gutter decoration in Monaco
1. Fixes a bug where the Field Editor persists if you switch to blocks before closing it
1. Adds a feature so that Monaco scrolls to a field editor when it opens

Fixing sprite editor styling, toggle, and scrolling in monaco

---

localtypings/blockly.d.ts
pxtblocks/composablemutations.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/648
When re-expanding a block, fields would not react properly to changes.

Fixes pxt-arcade/#648

---

cli/cli.ts
cli/hid.ts
docs/cli/deploy.md

test webusb support

---

theme/greenscreen.less
theme/themes/pxt/globals/site.variables

Loops get erased as they are "too green". Adds a green replacement in greenscreen mode. Needs LESS overrides in target than change the loops color.

tweak green color in green screen

---

pxtsim/libgeneric.ts

Cherry picking the fix from https://github.com/Microsoft/pxt/pull/5233
Original issue:
https://github.com/Microsoft/pxt-microbit/issues/1803

Fix Math.idiv in the simulator (#5233)

---

pxtlib/main.ts
webapp/src/app.tsx
webapp/src/cmds.ts
webapp/src/projects.tsx

Some variants support WebUSB, some not. We need to re-initialize the command after loading the app target variant to reflect this.
+ filter out cards from "choose hardware dialog" that don't have  a variant.

refresh commands on app target load

---

cli/cli.ts

Fixes the issue where serving pxt-arcade causes a neverending build loop.

Don't watch the simulator's built folder when serving

---

pxtrunner/renderer.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/690
I broke this with https://github.com/Microsoft/pxt/pull/5166
The old logic only added the simulator run button below a snippet if the compile was successful. Now, we don't compile the JS, so we can't check it. I don't think it matters though because we are already checking the snippets at build time.

Removing redundant compile check for snippets

---

pxtlib/package.ts

I'm not sure why we did not more issues with this one. Basically, we patch the pxt.json payload before packaging it into target.json.
https://github.com/Microsoft/pxt/pull/5242/files#diff-3395275f9da491d407273b5a3d768ea1R803
However, we also cycle through the files, read pxt.json and override it.

Additional file path load issue

---

pxtblocks/composablemutations.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/496
Fixes https://github.com/Microsoft/pxt-arcade/issues/496
Blockly doesn't apply mutations before the flyout size is calculated, so we need to add the button in the init function (even though it might get removed once the mutation is applied).

Add the plus input to expandable blocks to fix flyout

---

cli/cli.ts

Skip build if the sim is missing **and** there is a pxt.json, meaning we're inside a package or extension.
A missing sim can mean the sim is an optional dependency that couldn't be installed. We still want to build in that case.
Fixes https://github.com/Microsoft/pxt-arcade/issues/698

Only skip build if inside package or extension

---

cli/cli.ts

Now that we only skip target build when serving from packages and extensions, our server is crashing when running `pxt serve` inside the pxt repo, because we hardcoded watching the `node_modules/pxt-core` folder, which doesn't exist. This simply filters out dirs to watch based on their existence.

Don't watch dirs that don't exist during build

---

docs/defining-blocks.md

Some updates to the 'Defining blocks' page.

Update 'Defining blocks' page a bit

---

docs/SUMMARY.md
docs/writing-docs.md
docs/writing-docs/user-tutorials.md
pxteditor/editor.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/container.tsx
webapp/src/data.ts
webapp/src/dialogs.tsx
webapp/src/workspace.ts

Support for starting a tutorial from a shared script or a github repo.
* URL routes are ``https://[editor url]/#tutorial:[shared url]`` or ``https://[editor url]/#tutorial:[github repo url]``.
* A report abuse button is added in the tutorial UI unless the github repo is approved.

External tutorial support

---

pxtsim/debugger.ts
pxtsim/langsupport.ts

For user-created objects, debugger will no longer show "object object". For Sprites it will show "Sprite", for Images "Image width x height"

Showing Object description in debugger for some objects.

---

pxtblocks/codecardrenderer.ts

Auto link youtube videos in cards when `youTubeId` is present and no other explicit url is given.
RE: #5272

Auto link youtube vids in cards from id

---

pxtblocks/blocklycompiler.ts
tests/blocklycompiler-test/baselines/functions_names.ts
tests/blocklycompiler-test/baselines/lists_length_with_for_of.ts
tests/blocklycompiler-test/baselines/loops_local_variables.ts
tests/blocklycompiler-test/baselines/mc_chat_blocks.ts
tests/blocklycompiler-test/baselines/old_radio_mutator.ts
tests/blocklycompiler-test/baselines/self_reference_vars.ts
tests/blocklycompiler-test/cases/self_reference_vars.blocks
tests/blocklycompiler-test/test.spec.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/752
Fixes https://github.com/Microsoft/pxt-arcade/issues/751
Unfortunately, this undoes a lot of the logic I added to declare variables locally (oh well). The other improvements still apply (fewer renames, combined declarations, etc.).

Keep variables global if assigned to

---

pxtblocks/blocklycompiler.ts
tests/blocklycompiler-test/baselines/function_call_inference.ts
tests/blocklycompiler-test/baselines/functions_v2.ts
tests/blocklycompiler-test/cases/function_call_inference.blocks
tests/blocklycompiler-test/test.spec.ts

Fixes https://github.com/Microsoft/pxt-arcade/issues/748
In addition to the type inference fix, I also fixed another bug I found while testing where functions were getting renamed for no reason (e.g. `doSomething` ->  `doSomething2`). The API info we use to check for name collisions also includes user functions, so functions will collide with themselves after the first compile. My fix for that creates another bug where you can now have collisions with functions defined in `custom.ts`, but I'm not going to fix it since that feature isn't really used that much. I left a comment.
I also "turned on" two test cases for the new functions that I think Guillaume forgot to add to the list of tests.

Fixing function call type inference and name conflicts

---

webapp/src/app.tsx
webapp/src/monaco.tsx

Fixes https://github.com/Microsoft/pxt-arcade/issues/702
Going from text to blocks in our editor is potentially destructive because we don't always decompile when saving changes made in Monaco. This PR does two main things to mitigate some of that risk:
1. Unifies the codepath for decompilation from blocks to TypeScript
2. Unifies the codepath for saving the preferred editor of the project and makes sure that it only gets set when the file is actually loaded
I think that those two changes together take care of most of the bugs where you get user code deleted. Ideally, we would factor all of this logic out of `app.tsx`, but it's all too intertwined to do that right now. Until we have time for a more complete fix, **NEVER** call `this.setFile()` on `main.blocks` in app.tsx. Always call …

Unifying the code path for updating the editor and decompiling

---

localtypings/blockly.d.ts
localtypings/pxtarget.d.ts
localtypings/pxtblockly.d.ts
pxtblocks/blocklycompiler.ts
pxtblocks/blocklyimporter.ts
pxtblocks/blocklylayout.ts
pxtblocks/blocklyloader.ts
pxtblocks/blocklymutators.ts
pxtblocks/blocklyrenderer.ts
pxtblocks/composablemutations.ts
pxtblocks/fields/field_breakpoint.ts
pxtblocks/fields/field_colour.ts
pxtblocks/fields/field_gridpicker.ts
pxtblocks/fields/field_imagedropdown.ts
pxtblocks/fields/field_images.ts
pxtblocks/fields/field_ledmatrix.ts
pxtblocks/fields/field_note.ts
pxtblocks/fields/field_position.ts
pxtblocks/fields/field_sprite.ts
pxtblocks/fields/field_toggle.ts
pxtblocks/fields/field_turnratio.ts
webapp/src/blocks.tsx
webapp/src/createFunction.tsx

In conjunction with https://github.com/Microsoft/pxt-blockly/pull/200. 
Generate blockly.d.ts from sources. Now we have a true holistic view of Blockly in Typescript, and it's maintainable in the future, as it can be simply updated by running a script. 
Changes in PXT revolve around removing any in cases like Blockly.Msg. Since now we have a true idea of what Messages are defined, or in other cases it's using / casting Block to BlockSvg or Workspace to WorkspaceSvg since that's the actual class we use in PXT.
I've also cleaned up a bunch of unused helper methods in blocklyloader.ts that were used by the old toolbox.
I also found a number of issues with our dts interfaces that were previously hidden such as https://github.com/Microsoft/pxt/compare/generatedblocklydts?expand=1#diff-6e6afa1a6 …

Generate the blockly.d.ts from sources

---

package.json

Part of fixing the build for https://github.com/Microsoft/pxt-microbit/pull/1798
I left a file out of package.json that's necessary for running the blocks test in pxt-microbit. We didn't hit it until the GC PR because master of micro:bit was on an old version of PXT.
Once this gets merged I'll bump pxt and update the GC PR.

Adding blocks test runner for targets to pxt.json

---

pxtlib/sprite-editor/buttons.ts
pxtlib/sprite-editor/header.ts
pxtlib/sprite-editor/reporterBar.ts
theme/spriteeditor.less

Pretty self-explanatory; fixes https://github.com/Microsoft/pxt-arcade/issues/761

Changing the x in the sprite editor to a done button

---

pxtblocks/blocklycompiler.ts
tests/blocklycompiler-test/baselines/on_start_with_for_loop.ts
tests/blocklycompiler-test/cases/on_start_with_for_loop.blocks
tests/blocklycompiler-test/test-library/mbit.ts
tests/blocklycompiler-test/test-library/pxt.json
tests/blocklycompiler-test/test.spec.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/1881

Fix blockly compiler bug when a statement handler is on top of onstart

---

webapp/src/share.tsx

Don't show ssimulator in share dialog if screenshots or gif are not eabled.

better flag check for sim in share dialog

---

common-docs/blocks/logic/boolean.md

RE: https://crowdin.com/translate/kindscript/748/en-nl#36528

Fix typo in OR condition description

---

webapp/src/blocks.tsx

Variables with spaces in their name (such as "Text list", which is the default for a block) aren't showing their value in the variable explorer in Debug Mode. This fixes that.

Making variables with spaces in their name show properly in the variable explorer.

---

.vscode/launch.json
pxtlib/package.ts

When building docs in maker, ensure that a single board is referenced for the build.

filter out blocksprj when compiling docs

---

cli/cli.ts

In Maker, project change the global app target based on the compile target. As a result, running tests concurrently leads interference between projects.

don't run test docs concurrently as project may change app target

---

webapp/src/monaco.tsx

I've speed up the toolbox opening / switching by rearranging some of the frequently run code.
We only need to compute extended types on blocks if an exact match isn't found.
Before: 1.33s to open toolbox 
After: 0.34s to open toolbox (still too slow IMO)
Perf numbers are from Chrome's profiler with "6x CPU throttle" enabled. Once I get my ChromeBook I'll get some "real world" slow device numbers :)

Speed up toolbox opening by 4X for monaco blocks

---

docs/targets/board.md
localtypings/pxtparts.d.ts
pxtsim/allocator.ts

Adding support for routing 5V and 3V power lines on breadboard.

5v breadboarding support

---

pxtblocks/blocklycompiler.ts
tests/blocklycompiler-test/baselines/array_type_declaration_in_set.ts
tests/blocklycompiler-test/cases/array_type_declaration_in_set.blocks
tests/blocklycompiler-test/test.spec.ts

Fixes the crashy bird block errors described in https://github.com/Microsoft/pxt-microbit/issues/1866
The new variable declaration logic doesn't emit type declarations when compiling a "set" block, which is usually fine because our Blocks code is pretty strongly typed. However, you can confuse the TypeScript type checker by assigning an empty array in the first reference without a type declaration. Sometimes the language service figures it out using inference, but it's safer to not rely on that behavior.

Fix set declarations where the expression type is generic in blocks

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/array_for_of.blocks

Fixes https://github.com/Microsoft/pxt-microbit/issues/1749
I'm surprised I never noticed this until now :smile:. I don't even remember how long ago we changed the for of block.

Use the new for-of block in the decompiler

---

pxtblocks/fields/field_colour.ts

Fixes https://github.com/Microsoft/pxt-adafruit/issues/880
Not actually a decompiler bug; I think at some point we refactored this field editor and lost the ability to use enums. Adding some code to convert to the new syntax (which the blocks in pxt-adafruit are already using anyways). The color values came from here: https://github.com/Microsoft/pxt-common-packages/blob/master/libs/light/neopixel.ts#L4

Fixing the color picker when an enum value is decompiled

---

pxtlib/util.ts
webapp/src/lang.tsx

Simple fix to allow base language if it available. For example: fall back to "nl" if "nl-NL" is not available. Check was in the front end.

Allow a language if base language is available

---

theme/debugger.less
theme/themes/pxt/globals/site.variables
theme/toolbox.less
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/container.tsx
webapp/src/debugger.tsx
webapp/src/editortoolbar.tsx
webapp/src/simtoolbar.tsx

Moved the button to enter/exit debug mode to the simulator toolbar.
Added some options to exit debug mode:
a) Button in the debugger toolbar.
b) Button in top bar (similar to tutorials one).
Moved variable explorer and debugger toolbar to toolbox. They will
replace the usual toolbox when in debug mode.
Removed unnecessary elements in debug mode: Share, help and more in top bar, save, undo, redo in bottom bar.

Debugger: enter & exit debug mode and variable explorer to toolbox.

---

pxteditor/editor.ts
pxteditor/monaco.ts
pxtrunner/runner.ts
webapp/src/app.tsx
webapp/src/blocks.tsx

When importing a script from the home screen, blockly and field editors might not have been imported yet. As a result, we fail to load the blocks because some of the field editor haven't been registered yet from the target "fieldeditor.js" file. This would explain why some imported scripts open in javascript sometimes. This change ensures that blockly is loaded before importing.
Since loading and registering blockly was scatered all over the place, refactored all entires into a single helper that lives in the pxt-editor -- where it logically should be.

refactor field editor loading to a single helper

---

cli/cli.ts

In arcade, sim-strings.json might not be built anymore.

handle missing sim-strings when uploading to crowdin

---

theme/common.less

Fixes https://github.com/Microsoft/pxt-microbit/issues/1700
Also takes care of a bug on beta where the filelist overlay was showing up when the sim was in sandbox mode, even though the sim is always full screen there.

Handle double sim for radio in tablet and embed when fullscreen

---

localtypings/pxtpackage.d.ts
webapp/src/scriptsearch.tsx

Some package should not be shown to users as they are used purely to support the hardware build.
The "hidden" flag in pxt.json allows to hide them.

specify a flag to hide package from the extension dialog

---

pxtsim/langsupport.ts

Fixes https://github.com/Microsoft/pxt-microbit/issues/1915
I definitely thought this was going to be more complicated. @mmoskal can you confirm I'm not overlooking anything here?
Here's the code I used for testing:
```typescript
function test(x?: any) {
basic.showString(typeof x);
}
test(() => true);
test([]);
test({});
test(1.5);
test("x");
test(true);
test();
```

Adding typeof to sim

---

pxtsim/libgeneric.ts
theme/common.less
theme/debugger.less
theme/toolbox.less
webapp/src/debugger.tsx
webapp/src/simtoolbar.tsx

Rearranging controls toolbar in the toolbox.
Variable explorer:
- Show variables name on hover. Show variables value on hover for
{string, bool, number, array}
- Zebra decoration.
- Background change.
Reduced the amount of green.
Changed color of debug button in the simulator toolbar to be gray/orange for off/on.

Debugger improvements

---

pxtrunner/renderer.ts
theme/common.less
webapp/src/container.tsx

Prevents long translations of "blocks"/"JavaScript" to bleed out of the toggle. We should really fix the sizing of that toggle but this fix prevents out menu bar to be completed destructed.
Also prevents "JavaScript" to be localized.

clip blocks/javascript toggle text for localized languages

---

webapp/src/editortoolbar.tsx
webapp/src/simtoolbar.tsx

Removed it from duplicate places and changed to a friendlier bug.
Changed icon behavior in other simulator toolbar buttons.
Disabled debug mode while in tutorial mode.
Addresses https://github.com/Microsoft/pxt-arcade/issues/801 and https://github.com/Microsoft/pxt-arcade/issues/794

Debugger button

---

pxtlib/browserutils.ts

Firefox was being detected as Safari in https://github.com/Microsoft/pxt-microbit/issues/1295

Fix browser detection of Firefox on Mac

---

webapp/src/blocks.tsx

Before this fix, searching in Arcade would occasionally give you this error due to some invalid blocks xml (separate issue):
When there's a problem with xml block xml, we should still gracefully handle the flyout.

Handle invalid block XML when creating flyout

---

pxtcompiler/emitter/service.ts

Before when searching for "string" you could see errors like this in the console:
This caused problems downstream occasionally (e.g. https://github.com/Microsoft/pxt/pull/5362)
This was because the builtin blocks (e.g. text_length) are supposed to have the "builtinBlock" flag set to true in the SearchInfo type, but this wasn't being correctly set because of an issue in how the builtin and non-builtin search sets where combined (the non-builtin search set included some builtins that overwrote the builtin search set).
After this PR, these errors no longer appear in the console.

Ensure "builtin" flag is correctly set for search results

---

pxtcompiler/emitter/emitter.ts

@mmoskal this is the fix I was talking about; the compiler was erroring out when trying to set `usedAsIface` on shim functions inside `getVTable()`, so I'm just checking to see if a shim exists and ignoring those methods.

Fix vtable emit when methods have shim

---

pxteditor/editor.ts
pxtsim/debugger.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/debugger.tsx
webapp/src/editortoolbar.tsx
webapp/src/simtoolbar.tsx
webapp/src/simulator.ts

Fixing https://github.com/Microsoft/pxt-microbit/issues/1869.

Forcing restart when toggling slow-mo

---

localtypings/pxtparts.d.ts
localtypings/vscode-debug-protocol.d.ts
pxtlib/service.ts
pxtsim/debugger.ts
pxtsim/runtime.ts
pxtsim/simdriver.ts
theme/debugger.less
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/debugger.tsx

We add the ability to run getters in the debugger. 
When sending a variable's children request, now we can specify which ones of the class getters we should call to obtain values.
On the webapp side, we use this api to get getters marked to be displayed in their comment attributes.

 Adding ability to run getters in the debugger.

---

pxtlib/semver.ts

Support parsing "*" as the maximum sermver version. Used to create patches that don't expire: "0.0.0 - *"

Semver star

---

docfiles/docs.js
pxtrunner/renderer.ts
pxtrunner/runner.ts

These were just behind a flag that got turned off or missed at some point, as it previously existed in microbit v0:  https://makecode.microbit.org/v0/examples/turtle-square
Two issues with the current implementation:
* All projects seem to open in typescript, even if set to always send it as a blocks project
* Typescript snippets don't have a decompileResult, so they don't get the edit button. I would imagine that's readily available from the `$js` parameter with the js code in it, but I didn't want to spend too long searching for something that's probably readily known by someone more familiar with this section of the code :)
As a side note, if you test this out locally they won't load in the standard view, as something seems to have changed since that version of pxt; need to explicitly …

Show 'open in editor' button for blocks

---

theme/debugger.less
theme/themes/pxt/collections/menu.overrides
theme/themes/pxt/globals/site.variables
webapp/src/container.tsx
webapp/src/debugger.tsx
webapp/src/simtoolbar.tsx

Removed Blocks/Javascript toggle and added a title instead, centered and
not clickable.
Changed debugMode color to Orange (matching tutorial one).
Disabled Step buttons when simulator not paused on breakpoint.
Disabled Run/Restart button when simulator is loading, and in debug mode.

Improvements to the Debug Mode UI.

---

localtypings/pxtarget.d.ts
pxtsim/simdriver.ts
theme/themes/pxt/modules/embed.variables
webapp/src/app.tsx
webapp/src/compiler.ts

This prevents invocation of the compiler on the first sim run when autoRun is disabled. The simulator runs "empty" program (in arcade this just sets up the screen, otherwise we get mangled controls), and stops. Simulator still takes time to load, but it doesn't trash the CPU so badly anymore. Subsequent run of the program seems quite fast.
Test build here https://arcade.makecode.com/app/86b397e243ccf34dbbaa4956057a22c7242eaf90-f2e951a619
+ removed radial-gradient from embed placeholder

Allow for empty simulator run at page load

---

pxtblocks/blocklyloader.ts
tests/blocklycompiler-test/baselines/draggable_primitive_reporter.ts
tests/blocklycompiler-test/cases/draggable_primitive_reporter.blocks
tests/blocklycompiler-test/test-library/mbit.ts
tests/blocklycompiler-test/test.spec.ts

Fixing the type checks for APIs where `draggableParameters=reporter`. I think only Arcade uses that feature, but this bug doesn't affect those APIs because they use "custom" types (like `Sprite`). The logic was broken for primitive types, arrays, and types that extend other types (like the pins in mbit and cpx).
I also added some comments explaining the logic behind the checks we set.

Fix type checks for events that use the reporter draggable parameters

---

pxtblocks/blocklycompiler.ts

Found this bug while testing. When a block that declares variables (e.g. events, loops, etc.) goes from disabled to not disabled, you get an exception:
We catch the exception so it's not that big of an issue.

Update disabled blocks before compilation

---

localtypings/pxtarget.d.ts
pxtcompiler/emitter/service.ts
pxtlib/service.ts
webapp/src/blocks.tsx
webapp/src/blocksSnippets.ts
webapp/src/compiler.ts
webapp/src/monaco.tsx
webapp/src/monacoSnippets.ts
webapp/src/toolbox.tsx

The display on the monaco toolbox is more basic but the service is now completely lazy. Signatures are generated on demand when a user drags the block for either JS/Py.

Monaco toolbox for python

---

cli/cli.ts
pxtlib/docsrender.ts

This replaces `/docs/static` with `/static` in image URLs. This lets them be rendered by github as well as our backend. It doesn't touch existing syntax, but going forward we can use `/docs/static/...` to allow rendering both in our websites and on github.
For example see here https://github.com/Microsoft/pxt-arcade/blob/dbgconn/docs/hardware/dbg.md

Allow for ![](/docs/static/foo.png) in markdown

---

pxtsim/langsupport.ts

Support for edge connector in arcade. Allows to set a key dyanmically in the simulator (those keys mostly would exist in the bootloader but not in the code)

ability to set keys in simulator

---

pxtsim/langsupport.ts
pxtsim/runtime.ts
pxtsim/simdriver.ts
pxtsim/simlib.ts
webapp/src/debugger.tsx

When hitting a breakpoint, pause all fibers running in the background. After resuming via step or continue, restore all fibers.

Make breakpoints pause countdown and fibers running in the background.

---

pxtsim/simdriver.ts
svgicons/videoplay.svg
theme/common.less

Does the following:
1. Adds a new icon for the play button (I made it in Inkscape)
2. Makes the embed overlay slightly more opaque
3. Changes the hover animation so that it's faster and turns the icon green
**PLEASE NOTE:** I will center the icon on the screen in arcade, it's just not shown in the GIF below because that css needs to go in a separate PR
And here it is in action:
Tested in Edge, Chrome, and Firefox. Also tested in IE, but the icon gets weirdly cropped. I'll open an issue once this gets merged.

Improving the stopped overlay for the simulator

---

localtypings/pxtarget.d.ts
localtypings/pxtpackage.d.ts
pxteditor/editor.ts
pxteditor/workspace.ts
pxtlib/tutorial.ts
webapp/src/app.tsx
webapp/src/codecard.tsx
webapp/src/projects.tsx

Store tutorial information in header to allow restarting. This means that "Exit Tutorial" exits the editor but retains the progress, "finish" has the same behavior as today.
This fixes the download issue in Aracde.

Tutorial tracking

---

docs/static/playground/pxt-common/pxt-core.d.js
libs/pxt-common/pxt-core.d.ts

fixes https://github.com/Microsoft/pxt-microbit/issues/1725
fixes the last part of https://github.com/Microsoft/pxt-microbit/issues/1940 (still outstanding issues there though)
^^
For consistency, this should probably switch to `text` to match the string interface methods declared just above which fixes the issue, but it's probably worth making `blockNamespace` ignore case as well.

Include `String.charCodeAt` in toolbox

---

docs/static/playground/pxt-common/pxt-core.d.js
docs/static/playground/pxt-common/pxt-helpers.js
libs/pxt-common/pxt-core.d.ts
libs/pxt-common/pxt-helpers.ts

split off from #5408 
fixes https://github.com/Microsoft/pxt-arcade/issues/784
fixes https://github.com/Microsoft/pxt/issues/5396
This matches https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join behavior for ``Array.join`` -- separator defaults to ``,``, and only ``undefined`` and ``null`` are replaced with the empty string, not all falsey values. Note that the second part of this won't behave nicely in the simulator without #5408, as 
all values default to 0. That is, 
```typescript
let mySprites: Sprite[] = [];
mySprites[5] = undefined;
console.log(mySprites.join());
```
results in ``0,0,0,0,0,0`` in the simulator and ``,,,,,`` on hardware

Match regular JavaScript for Array.join

---

webapp/src/simtoolbar.tsx

We hide debug mode button in JavaScript until it's implemented.
We also disable it for IE.

Disabling debug mode in JavaScript

---

pxtsim/runtime.ts

Fixing https://github.com/Microsoft/pxt-arcade/issues/846.
This was introduced in https://github.com/Microsoft/pxt/pull/5411 trying to make sure all fibers were being paused on breakpoint.

Making debugger resume properly after breakpoint

---

pxtblocks/blocklyloader.ts

Allow parameters of type ``any`` to accept any reporters as valid input, rather than bouncing away everything besides variable reporters

allow blocks with 'any' inputs to accept any block

---

webapp/src/app.tsx

This makes it so you can specify the hash argument and any other arguments passed through the URL.
This is mostly used for linking to a tutorial or the editor in another language as shown:
[http://makecode.microbit.org/#tutorial:/tutorials/getting-started&lang=fr](http://makecode.microbit.org/#tutorial:/tutorials/getting-started&lang=fr)
Fixes Microsoft/pxt-microbit#1536

Allow for specifying hash arguments and language

---

webapp/src/codecard.tsx

fixes Microsoft/pxt-microbit#1741
Show extra code card content on tablet view and up (rather than only on wide desktops)

Show extra code card content on tablet view and up

---

pxtlib/package.ts

Reproduce some of the legacy preferred editor logic so that legacy scripts are loaded in typescript if needed.
Tested by creating TS scripts in makecode.microbit.org and opening them in https://makecode.microbit.org/app/e6b6aa4222620f4ed2ae5642b0572741b3d87414-fff5e4d998#editor

coarser logic to get preferred editor

---

theme/debugger.less

When toggling debug mode, we should hide the toolbox flyout if it's open.

Hiding toolbox flyout when in debug mode

---

pxtsim/runtime.ts

With https://github.com/Microsoft/pxt-arcade-sim/pull/5, when a breakpoint is hit while a button is pressed, the button will be released after resuming execution.

Allow simulator to reset buttons after breakpoints.

---

theme/scriptsearch.less
webapp/src/codecard.tsx

There are a few cards that we fix the height for: extensions, experiments, and the board selection in maker. This sets the title to be 1 line and uses an ellipsis to show that the title is longer, but couldn't be displayed. This sets a fixed height for the description of each card do that they don't bleed outside of the card. The description height is either set to 2 lines or 10 lines depending on whether or not there is an image present in the card. 
Fixes Microsoft/pxt-microbit#1835
Here is what it looks like before and after:

Trims description for fixed height cards

---

pxtsim/svg.ts

fixes https://github.com/Microsoft/pxt-microbit/issues/1382 (this behavior also applied to the compass heading and light level at a glance; looks like any svg simulator buttons that required x/y positions)
it looks like the accelerometer is also broken on iOS safari, though; it's probably the same type thing as this, will give it a look tomorrow morning

Fix svg cursorPoints for safari in iOS

---

webapp/src/blocksSnippets.ts

fixes https://github.com/Microsoft/pxt-microbit/issues/1050
Adds a new builtin block that is the same as normal comparison, but contains strings by default instead of numbers

Add builtin 'string compare' block

---

pxtcompiler/emitter/service.ts
pxteditor/monaco.ts
webapp/src/monaco.tsx

* localize jsdocs before passing to monaco
* use block string in filter as well
* show indent guides

better localization support in completions

---

pxtwinrt/hiddeploy.ts

This adds a check to see if the HID watchers are activated before starting them.
Starting them while activated causes an error.
Fixes Microsoft/pxt-microbit#1975

Only starts HID watchers when they aren't activated (Win 10 App)

---

pxtblocks/blocklyloader.ts

This adds the ability to use arrays as shadow blocks so that you can author blocks that take arrays of numbers, strings, or booleans, as parameters.
Fixes Microsoft/pxt-microbit#1654

Ability to use arrays as shadow blocks

---

theme/common.less

fixes https://github.com/Microsoft/pxt-microbit/issues/1960
Return the top bar back to normal:
and preserve behavior for debug buttons:
As mentioned in the issue, the alignment definitely feels a bit weird on the top bar, but it does seem to technically be centered; maybe worth spending a minute at a design meeting to figure out how to make it not feel off.

Fix toggle icon alignment issue

---

theme/debugger.less
theme/themes/pxt/globals/site.variables
webapp/src/app.tsx
webapp/src/debugger.tsx

Rolling back from table. Now every row of variable:value will auto adjust width to accommodate variables with long names and/or values.
Aesthetic changes.
Fixing bug in Edge where "Debug Mode" title was not centered.

 Debugger: Improvements to variable explorer

---

pxtlib/commonutil.ts
pxtlib/util.ts

Fix for https://github.com/Microsoft/pxt-arcade/issues/883
Normalize "en-US" to "en" which is the neutral language of makecode (en skips all localization work).

normalize user language + normalize en-US -> en

---

pxtpy/converter.ts

This used to fail:
```python
class SpriteKind(Enum):
Player = 0
Projectile = 1
Enemy = 2
Food = 3
ship = sprites.create(sprites.space.space_red_ship, SpriteKind.Player)
#ship.set_flag(SpriteFlag.STAY_IN_SCREEN, True)
```
and it would work with the last line uncommented.

Fix enum errors in py2ts

---

pxtcompiler/emitter/plaintsc.ts

Microbit build was failing for me (https://github.com/Microsoft/pxt/commit/d8983d2404342dc7a5ab30e1856531d611bdbf6d#r33160766), looks like the issue is when 'file' is defined / explicitly is set to be undefined.

Fix microbit build error

---

webapp/src/projects.tsx

Reorder download dialog to put physical boards first.

move variants after boards

---

webapp/src/simtoolbar.tsx

In tablet mode, clicking on the simulator, acts as going to full screen. We need to be able to escape that mode in a tutorial. Currently, we're stuck.

show fullscren button in tutorial mode

---

cli/cli.ts
localtypings/pxtarget.d.ts
pxtblocks/blocklyloader.ts
pxteditor/editor.ts
pxteditor/editorcontroller.ts
pxtlib/tutorial.ts
theme/tutorial.less
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/compiler.ts
webapp/src/marked.tsx
webapp/src/monaco.tsx
webapp/src/monacoSnippets.ts
webapp/src/srceditor.tsx
webapp/src/tutorial.tsx

Extends the tutorial engine to extract typescript/python code snippets and open the corresponding editor.

Tutorials for JavaScript/Python

---

pxtblocks/blocklyimporter.ts
pxtblocks/blocklyloader.ts

Transform old functions on import (bug: Microsoft/pxt-microbit/issues/1987), remove extra call to setSourceBlock (source already set in appendField)

Transform old functions on import

---

webapp/src/compiler.ts

Data will allow us to determine which errors are common.

report count of diagnostic errors

---

pxtlib/github.ts

Add checks to see if the GitHub extension exists before processing it as an extension.
Fixes Microsoft/pxt-arcade#777

Fix crashing when GitHub extension doesn't exist

---

pxteditor/editor.ts
pxtsim/embed.ts
pxtsim/simdriver.ts
pxtsim/simlib.ts
webapp/src/app.tsx
webapp/src/simtoolbar.tsx

Fixes https://github.com/Microsoft/pxt-arcade/issues/626, where the audio wouldn't start until the user actively pressed the start / restart icons on iOS
Mute audio on iOS on page load, and require the user to unmute it themselves. This is directly triggered by the user, and enables the audio for the session.
Also fixes a bug that triggers semi - randomly cross browsers (that I hadn't seen before as it's weird and minor). It looks like the change to allow a quick restart caused the simulator to occasionally use old options due to ``SimulatorDriver._currentRuntime`` not getting updated, which would lead to the simulator being in an incorrect state after restarting the game (i.e. ``simtoolbar`` has it muted, but the sim was just unmuted, or vice-versa). I don't have a consistent way to …

Fix simulator audio on iOS

---

pxtlib/main.ts
pxtlib/package.ts
pxtrunner/renderer.ts
pxtrunner/runner.ts
webapp/public/run.html

At the moment, simulators in the docs cannot use extensions as noted in Microsoft/pxt-arcade#242.
However, there is a way to include external packages for blocks rendering using the \```package macro.
This uses those packages and sends them to the embedded simulator through the url like the code is sent.
Once received, when generating the initial files for the project, this adds those dependencies to the pxt.json so it loads them just like a normal project.
fixes Microsoft/pxt-arcade#242

Add ability to use extensions in docs

---

localtypings/pxtparts.d.ts
pxtcompiler/emitter/backjs.ts
pxtlib/hwdbg.ts
pxtlib/service.ts
pxtsim/debugger.ts
pxtsim/langsupport.ts
pxtsim/runtime.ts
webapp/src/blocks.tsx
webapp/src/debugger.tsx
webapp/src/monaco.tsx
webapp/src/monacoDebugger.ts
webapp/src/package.ts

Fixes https://github.com/Microsoft/pxt-adafruit/issues/998
This PR adds support for local variables, function arguments, and "this" in the debugger. It also fixes a few bugs:
1. Fixes a crash when the app receives breakpoints before Monaco is loaded
2. Fixes a crash where the code for evaluating getters was yielding (via `maybeYield`) and causing an exception in the simulator. You can see it if you open/close sprites 6 times in the variable list
3. Fixes the issue where the Monaco debugger is not visible if you have been to Blockly at least once.
4. Fixes a lot of places in debugger.tsx where we were mutating the component state directly instead of treating it as immutable
Also includes a lot of refactoring in the debugger to support multi-file debugging, which I will finish up in a …

Monaco debug part 2

---

pxtpy/pydecompiler.ts

Snakify the right hand side of . operator
```
def a_pressed():
pass
controller.a.on_event(ControllerButtonEvent.PRESSED, a_pressed)
```

Snakify call

---

webapp/src/app.tsx

Seems to be fixed reload of autoRun tutorial https://github.com/Microsoft/pxt-adafruit/issues/1002. I could not trace the exact root cause of the bug but with these fixes I could not reproduce the race anymore. @riknoll maybe you can take a second peek.

Exit tutorial cleanup

---

webapp/src/cmds.ts

fixes https://github.com/Microsoft/pxt-arcade/issues/510
With the name on the button, some students were getting confused and thinking they had to press it to download, which ends up with them double-downloading the file. Took the wording from the download screenshot section, which is a bit more clear:
Could also just switch it to be a link; a decent number of websites do that and it does make it something you seek out rather than click immediately because it's a big green button:
I personally like the button as is, but can switch if that's preferred

Download button in the download dialog

---

webapp/src/dialogs.tsx

I find it frustrating that i dont' know if the elecron app is updating or not. Add some info about online version availability in electron.
* not online -> please connect to internet to update
* online, updated -> you're up to date
* online, outdated, an update is avilable

display version info when running in electron

---

pxtcompiler/emitter/annotate.ts
pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/global_variables.blocks
tests/decompile-test/cases/global_variables.ts
tests/decompile-test/cases/testBlocks/globals.ts
tests/decompile-test/cases/testBlocks/pxt.json

Checks to see if a variable is declared in another file before recompiling it as a block.
If an identifier is defined in another file, it is flagged as a global and will fail decompilation.
Fixes Microsoft/pxt-arcade#554

Don't decompile globals

---

theme/common.less
webapp/public/run.html
webapp/src/app.tsx
webapp/src/share.tsx

Fixes https://github.com/Microsoft/pxt-arcade/issues/849
CSS wasn't applying appropriately to simulator in the share dialogue as it didn't have the same ID as the normal simulator.

Specify simulator by class instead of id for css

---

localtypings/pxtarget.d.ts
pxteditor/editor.ts
pxteditor/experiments.ts
pxtlib/package.ts
pxtwinrt/winrt.ts
webapp/src/app.tsx
webapp/src/dialogs.tsx
webapp/src/package.ts
webapp/src/scriptsearch.tsx

To better support offline scenario, this change allows to import project **files** (.hex, .uf2, .png) as extension in a project.
The full source of the project is stored in a file in the project (say ``donut.json`` for the ``donut`` extension file) and the dependecies has a new protocol ``pkg:donut.json``.
This solves the problem of supporting 3rd party extensions in the web and/or offline app. Also shared scripts will correctly load or reload etc...
In the extension dialog, we have a new card:

Import extension as file

---

theme/common.less
webapp/src/editortoolbar.tsx
webapp/src/simtoolbar.tsx

Move undo/redo, zoom, collapse, and save buttons into shared functions for the editor toolbar. Remove the simulator toolbar buttons (play, refresh) except in headless rendering.

Refactor shared buttons in editor toolbar

---

theme/common.less
webapp/src/app.tsx
webapp/src/editortoolbar.tsx
webapp/src/simtoolbar.tsx

Remove run/restart buttons from editor toolbar, additional cleanup

Remove run/restart buttons from editor toolbar

---

pxtcompiler/emitter/service.ts
pxteditor/monaco.ts
pxtpy/pydecompiler.ts

Until we figure out how to configure monaco to insert tabs, we need to use spaces.

always use space for python

---

docs/js/python.md

This goes under https://makecode.com/js/python (which isn't the most fortunate URL, but will do for now)

Add some docs about technical side of Python support

---

pxtcompiler/emitter/emitter.ts
tests/compile-test/lang-test0/17classes.ts

Fix support for optional args in .ctors
```
class C {
constructor(a? : any) {
}
}
```

support optional args in .ctor

---

pxtcompiler/emitter/annotate.ts

fixes https://github.com/Microsoft/pxt-arcade/issues/780, fixes part of https://github.com/Microsoft/pxt-arcade/issues/915 (found another case on the forum where it is still broken so I'm still looking into that, but the linked example and a handful more work now that didn't before)
Issue for those was the existence of a ``main.ts`` in an extension, which was being used instead of the actual ``main.ts``. This caused the annotations to be missing for most of the file, resulting in a generic error message with almost every line of code highlighted as errors
(notably, this makes it so the arcade space fight example decompiles properly, so that can be changed to be a blocks game eventually)

Fix annotations when using extensions containing a `main.ts`

---

pxtpy/converter.ts
webapp/src/monaco.tsx

fix parameter hints in python intellisense

---

webapp/src/app.tsx
webapp/src/cmds.ts
webapp/src/webusb.tsx

The logic was broken when we moved the "Always use web USB" stuff into an experiment. With this change, here's the pairing experience:
1, If you never pair the device, we always download
2. If a paired device is connected, we try to use webUSB
3. If the paired device is disconnected, the user gets an error dialog and we go back to downloading until it gets reconnected

Use Web USB after pairing

---

theme/common.less

Fix simulator width for tablet+mobile in Edge

Fix simulator width for tablet+mobile in Edge

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/almost_too_large.blocks
tests/decompile-test/cases/almost_too_large.ts

fixes https://github.com/Microsoft/pxt-arcade/issues/915 (there seems to be a blockly related issue in the last one linked there still, but that seems unrelated)
Ties the block count to the number of ``<blocks>`` created, so that it maps directly to the number of blocks listed in the ``Delete all {num} blocks`` dialogue:
For example, ``Delete all blocks`` on Falling Duck says it has 77 blocks, but currently ends up with ``emittedBlocks`` at 150; from the users perspective there is no real way to tell what they're at until it gives the error.
(Also arbitrarily bumped ``MAX_BLOCKS`` to just more than the largest arcade game I've seen that was built in blocks, but can revert that if preferred)
Making this a draft PR as I'll have to add a test still, but the one in …

Only count blocks, not other pieces of the XML, towards MAX_BLOCKS

---

docs/target-creation.md

pxt-sample uses [`window.applicationCache`](https://developer.mozilla.org/en-US/docs/Web/API/Window/applicationCache). On chrome window.applicationCache is null when using non-secure url. This prevents the website from loading

Use https to open pxt-sample

---

docs/extensions/naming-conventions.md

Hyphenated names are syntax errors anyway so it's not really valid to include them when discussing suggested names.

Hyphens in names are syntax errors anyway

---

pxtsim/runtime.ts
pxtsim/simlib.ts

REquires https://github.com/Microsoft/pxt-common-packages/pull/806

support for "idling"

---

pxtcompiler/emitter/decompiler.ts
pxtcompiler/emitter/emitter.ts
tests/decompile-test/baselines/non_boolean_conditionals.blocks
tests/decompile-test/cases/non_boolean_conditionals.ts

fixes https://github.com/Microsoft/pxt-arcade/issues/911
(https://github.com/Microsoft/pxt-arcade/issues/946 is related-ish and still causes failures for some expressions, but not fixed with this change)
Emits gray blocks instead of failing to decompile for non-boolean conditions
decompilation test output:

Fix decompilation of non-boolean conditions

---

localtypings/pxtpackage.d.ts
webapp/src/projects.tsx

Make forum links say 'Open in Forum' instead of 'Show Instructions'

Add 'Open in Forum' display for forum links

---

pxtsim/embed.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/simulator.ts

Fixes https://github.com/microsoft/pxt-arcade/issues/256
Sends a 'stop sound' message whenever the user ends an instance of the sim running, so that the sound doesn't continue for a few moments into the next game / with no game running. (I think for it to work fully with tones it needs the recent common packages changes to mixer, but I'm not certain / didn't see a reason to roll back the common packages bump to check)
For an example of what this fixes, try stopping or restarting [this game](https://makecode.com/_McfaJVTafC8m) after the sound starts - it will continue momentarily after you press the button. A bit worse when playing with a version with a working ringTone as well

Stop sound when user restarts or stops sim

---

cli/buildengine.ts
cli/cli.ts
package.json
webapp/src/cmds.ts

Since webusb fails on the second flash (internal caching issue on the node.js webusb module), disable and just do file copy for now for deployments.

bail out to copy strategy of hid fails

---

pxtblocks/blocklyloader.ts
pxtblocks/fields/field_sprite.ts
pxtlib/sprite-editor/spriteEditor.ts

closes https://github.com/microsoft/pxt-arcade/issues/955
Not added to monaco editor with this, as it doesn't seem like there's necessarily a place to persist that stacks there

Persist image editor undo/redo in blocks editor

---

theme/common.less
theme/sidedoc.less
webapp/src/app.tsx
webapp/src/container.tsx
webapp/src/editortoolbar.tsx
webapp/src/simtoolbar.tsx

- Move simulator collapse button (update desktop, tablet, mobile styles)
- Small updates to sidedocs toggle (no "docs" symbol on hover, smaller chevron)
- Update tutorial button styles to match (remove text, move out of tutorial card)
Demo: https://makecode.microbit.org/app/357d62b063de9f7e133ae176f93d541572922dd9-1ffda62afe

Move simulator collapse button out of editor toolbar, CSS updates

---

webapp/src/discourse.ts
webapp/src/projects.tsx

It is quite dreadful to open a community project at the moment: go to forum, open shared link (wait), click Open Code (wait) click "Edit" (wait).
This change sniffs the project url using the Discourse API and display a "Open In Editor" option.
**requires to deploy support for "forumUrl" card types*

Open forum from home

---

pxtblocks/blocklyloader.ts

If a block is in the namespace ```__internal```, this ignores it's tooltip.
This goes for all functions defined here: [https://github.com/microsoft/pxt/blob/32b9b2393542819a471d2c6ef13e76fd672a3f75/libs/pxt-common/pxt-helpers.ts#L364](https://github.com/microsoft/pxt/blob/32b9b2393542819a471d2c6ef13e76fd672a3f75/libs/pxt-common/pxt-helpers.ts#L364)
Fixes Microsoft/pxt-arcade#494

Ignore tooltips for internal functions

---

webapp/src/lang.tsx

We have more context information in /translate to help translator that just dumping them on crowdin.

point to /translate instead of crowdin

---

pxtrunner/renderer.ts
webapp/public/run.html

The ```src``` attribute has an obtainable character limit when writing large programs. The ~~```name```~~ ```data-code``` attribute doesn't seem to have as strict limitations. 
This switches to send the code of a program to the docs simulator using the ~~```name```~~ ```data-code``` attribute so that larger programs can run on Edge and IE.
Fixes Microsoft/pxt-arcade#943

Send code through data-code attribute instead of src

---

pxtlib/sprite-editor/gallery.ts

fixes https://github.com/microsoft/pxt-arcade/issues/957

Don't scroll background when using mouse wheel in gallery

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/non_block_combined_fields.blocks
tests/decompile-test/cases/non_block_combined_fields.ts
tests/decompile-test/cases/testBlocks/blockCombine.ts

fixes https://github.com/microsoft/pxt-arcade/issues/966
```typescript
let a = bc.createTest()
a.data = 5
testNamespace.numberArgument(a.data)
```
goes to
(Fixes decompilation of https://forum.makecode.com/t/combo-attack-and-button-combination-extension/169, decompiles successfully to mostly gray blocks)

Fix decompilation of non-block combined fields

---

cli/buildengine.ts
cli/cli.ts
cli/hid.ts

The WebUSB / HID deployment has issues. It mostly does not work on arcade. This flag disables it by default and default to MSD deployment. can be turned off once we get webusb back on its feet.

disabling HID from CLi

---

cli/buildengine.ts

When the local server deploys a compiled file, don't rely on the current target config which might have the wrong variant.
Fix for https://github.com/microsoft/pxt-maker/issues/229

server deploy for correct app variant

---

pxtlib/sprite-editor/canvasGrid.ts

Fixes https://github.com/microsoft/pxt-arcade/issues/671
Apparently iOS takes a downward motion to inherently be a scroll (even if nothing moves), so the bounding rect top was changing position as you dragged down. This takes into account the scroll offset so that it behaves nicely
broken:
new:

Fix ios image editor offset

---

docs/translate.md

I've noticed that some people are working under ``v0`` in Crowdin. Is this still considered an active target? I added a section to direct translators to work under "active" projects.

Note which targets are active for translation

---

pxtlib/browserutils.ts

Fixes https://github.com/microsoft/pxt-arcade/issues/379
Would be good to test on chromebook and physical android device / windows with touchscreen with a target build of arcade
Issue is that the browsers were using the pointer events when they should have been using touch events.
Broken / current:
Fixed:
testing:
* ~[ ] chrome - touchscreen on chromebook~ don't have a touchscreen chromebook but should match android?

Prefer touch events to pointer events (fix android image editor)

---

pxtcompiler/emitter/emitter.ts
pxtlib/package.ts

This includes only font glyphs which are used in string

Add support for font subsetting from JRES

---

theme/monaco.less

fixes https://github.com/microsoft/pxt-microbit/issues/2050
There's a separate `monaco-scrollable-element` to make the scroll bar nicer - this div having any 'scrolling' makes the scroll bar show up on top of the one we actually use

Remove duplicate scroll bar in vs editor

---

pxtlib/sprite-editor/spriteEditor.ts

Adds alternate behavior while holding shift for the rectangle and circle tools, that matches the behavior of the line tool. These ones are likely a bit lesson common to use than the line tool, but can be fun to use

Shift actions for rectangle, circle tools

---

pxtlib/browserutils.ts
theme/spriteeditor.less

Fixes sprite editor mouse interactions on some machines, while still allowing touchscreen input

Handle pointer events in sprite editor more appropriately

---

pxtcompiler/emitter/service.ts
pxtpy/converter.ts
pxtpy/pydecompiler.ts

Fixes microsoft/pxt-minecraft/issues/858, and max/min/randint conversion between Python and TS.

Bidirectional builtin function map, override pyQname for special cases

---

webapp/src/projects.tsx

fix missing green buttons on adafruit beta

return green button for home page links

---

pxtcompiler/emitter/backbase.ts

Without this, this fails to compile for native:
```
mySprite.say("你好世界,让我们来数苹果吧")
```

Fix UTF8 literal string generation

---

pxtsim/simlib.ts

This is the simulator implementation of ramping the frequencies of sounds. Needs to be merged in conjunction with microsoft/pxt-common-packages#841

Add ability to ramp frequencies of sounds

---

pxtblocks/fields/field_colour.ts

fixes https://github.com/microsoft/pxt-arcade/issues/988 (field editor bug, not decompiler)
Also:
* doesn't fail on invalid indices / super big numbers
* allows shortcut hex codes to decompile as expected when decompiling (e.g. ``0xfff``)
This does have slightly weird behaviors in some cases, though - for example, the ``set background color`` block in arcade will not match the hex inputs, but if you decompile to blocks it will behave as you would normally expect:
https://makecode.com/_UawYdtFWWhsA
The same would apply in adafruit (shortcut syntax doesn't work in typescript but decompiling makes it work). ~Maybe we could add a helper function to parse the input and make the behavior consistent for all the functions that use this field editor?~ I suppose there isn't really too much to do …

Fix color parsing in field_colour

---

pxtcompiler/emitter/backbase.ts
pxtcompiler/emitter/emitter.ts

* we had a bug where field access in classes over 127 bytes wouldn't be emitted correctly
* static fields used to be included in every instance of a class
@abchatra  After some testing on `dev` you may want this on `master`.

fixes for large classes and static fields

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/ts_block_as_conditional.blocks
tests/decompile-test/cases/ts_block_as_conditional.ts

Fixes https://github.com/microsoft/pxt-microbit/issues/2079
Issue was having a user function in a gray block return a boolean; in this case, the CallExpression itself had a ``.callInfo`` property because it was already a gray block, rather than having it on the expression itself

Fix decompilation for microbit game of life example

---

webapp/src/workspace.ts

fixes https://github.com/microsoft/pxt-arcade/issues/1011
Package all the files into the second 'Auto-initialized' commit instead of separating each one out as 10 separate commits
current behavior: https://github.com/jwunderl/pxt-buncha-commits-test/commits/master
this change: https://github.com/jwunderl/pxt-test-fixes/commits/master

[gh-integration] make 'Auto-initialized' contain all necessary files

---

docs/blog/microbit/2019-beta.md

Added it using the new ``reminder`` block. I can move it to the very top of the post for more immediate effect if you like that.
Also, I've changed "into production" to "live" as the general reader base my not be as familiar with that terminology.
Closes #5439

Include release date for mbit Summer Beta

---

pxtlib/sprite-editor/spriteEditor.ts
pxtlib/sprite-editor/tools.ts

- "m" shortcut
- don't stack overflow on close

Sprite markee fixes

---

webapp/src/dialogs.tsx

Puts a line break between the two sentences in this dialog
Fixes microsoft/pxt-adafruit#1042

Added line break to fix typo

---

webapp/src/app.tsx

fixes https://github.com/microsoft/pxt-microbit/issues/2107
The other error I mentioned in the issue, an exception that gets through whenever you create a new extension, is coming from the call in line 668 here:
https://github.com/microsoft/pxt/blob/20595b015c9ba303c24cfe67dedef0061bcec76d/webapp/src/workspace.ts#L667-L679
It gets propagated to the console before the catch handles it, presumably due to the restructuring of async / await functions to make them cross platform. I suppose it could be rewrittten to just use promises instead, but that seems like a bit much just to suppress an error in the console

do not issue error when cancelling github import dialogue

---

theme/common.less

microsoft/pxt-adafruit/issues/1046

Fix simulator toggle on IE11, dual chevron

---

cli/cli.ts
cli/server.ts
pxteditor/editor.ts
pxtlib/cmds.ts
webapp/src/app.tsx
webapp/src/cmds.ts

Fixes WebUSB in microbit. The issue is that we set a "deployCoreAsync" function in pxt-core which can be overridden by the target (microbit may be the only one that does this) and we were reverting the target override after USB pairing. Likely introduced by https://github.com/microsoft/pxt/pull/5517.
The fix was to keep the pxt-core deploy function selection separate from the target's deploy function override and then always prefer the target's override if it exists at the callsite.
related: https://github.com/microsoft/pxt-microbit/pull/2115
fixes: https://github.com/microsoft/pxt-microbit/issues/2089
https://makecode.microbit.org/app/fc71444bb8dcd5f94c4ac4f8ca9c1ba0f0342c34-93265192c2
TODO:

Fix webusb for microbit

---

docs/static/playground/pxt-common/pxt-core.d.js
libs/pxt-common/pxt-core.d.ts

Add blocks for indexOf, includes, split.
Fix for https://github.com/microsoft/pxt-microbit/issues/1990

string.indexOf block

---

pxtrunner/runner.ts
pxtsim/embed.ts
webapp/src/app.tsx

Switches docs to open from the editor frame rather than the side doc frame
When the editor frame messages the side docs frame to open the page in a new tab, instead of the side docs frame opening the tab and sending a completion message, this sends back the url to be opened and the editor frame opens the tab instead.
Fixes Microsoft/pxt-microbit#2103

Open doc pages from editor frame

---

theme/tutorial.less
webapp/src/tutorial.tsx

Border when tutorial card focused, bottom margin on card, positioning of avatar, adjust event handlers to fix Edge close-on-click issue
microsoft/pxt-microbit/issues/2116
microsoft/pxt-microbit/issues/2092
microsoft/pxt-adafruit/issues/1045

Small tutorial CSS cleanup, Edge event fix

---

pxtlib/cpp.ts
webapp/src/pxtjson.tsx

The current setup for configs is to allow for dependencies to set the config values. If there is a field defined in a dependency but not the pxt.json, then it will take the dependency's value. 
PXT also currently strips out all fields set to null in the config. This becomes problematic with the pairing options for Microbit because a couple of the user config options contain null values. [See here](https://github.com/microsoft/pxt-microbit/blob/65a05bf2d5064ff8ee3d5207a01bd01510ed5a91/libs/core/pxt.json#L77). Without the value being set, the dependency's value will be used instead making the combination of these values being invalid and not aligning to a single option.
This change simply removes the code in which we strip out those fields that are set to null.
I'm not 100% why it was used …

Allow for config values to be null

---

common-docs/blocks/math.md

Add sections for ``round``, ``ceiling``, ``floor``, and ``truncate`` to the _blocks/math_ doc.
Fixes https://github.com/microsoft/pxt-microbit/issues/2117

Add Math 'value functions' doc sections

---

common-docs/blocks/math.md
pxtlib/cpp.ts
pxtsim/allocator.ts
pxtsim/visuals/boardhost.ts
theme/tutorial.less
webapp/src/pxtjson.tsx
webapp/src/tutorial.tsx

Restore modal for @unplugged steps
CSS fixes from design: remove tooltip hover, update chevron color
Modal addresses:
microsoft/pxt-microbit/issues/2118
microsoft/pxt-microbit/issues/2116 (issue 1)

 Restore modal for @unplugged steps, CSS fixes

---

pxtblocks/blocklyloader.ts

If an enum value block is set to be hidden, don't show it in the drop-down. The only way the enum value is accessible is if previous programs included it or if the value is specified in the typescript.
Needed for https://github.com/microsoft/pxt-microbit/pull/2138

Don't show Enum values in the drop-down if they are hidden

---

webapp/src/cmds.ts
webapp/src/electron.ts

Fixes https://github.com/microsoft/pxt-microbit/issues/2114
That error is thrown when a micro:bit is not connected to the app, so no need to report it to the cloud.
Also fixes the electron deploy (requires https://github.com/microsoft/pxt-microbit/pull/2142)

Give electron deploy priority

---

pxtlib/initprj.ts

The 'license' part in the readme is a bit misleading, as it being a header with nothing in it makes me think it's where I'm supposed to paste the license. This removes that, and adds a step to the todo list to create a license (not sure on the wording - e.g. should it actually say to use mit license).
Also fixes the spacing in the generated tsconfig, which was indented improperly
Current: https://github.com/jwunderl/pxt-test-fixes
this change: https://github.com/jwunderl/pxt-new-default
For what it's worth, here's the process for generating a license on github:

add step for selecting license, remove 'license' from readme

---

webapp/src/tutorial.tsx

don't show close icon in tutorial modals

---

webapp/src/app.tsx
webapp/src/tutorial.tsx

Fix for https://github.com/microsoft/pxt-microbit/issues/2172

Don't double toggle

---

webapp/public/run.html

Adds a check to see if window has access to same origin features like frameElement before trying to use them.
Fixes https://github.com/microsoft/pxt-microbit/issues/2152

Add check to see if frameElement exists

---

pxtblocks/blocklyloader.ts

Make it possible to translate the two newly(?) introduced Blockly strings.
* New variable...
* Rename all '%1' variables to:

Fix Untranslatable Blockly Strings

---

pxtlib/sprite-editor/bitmap.ts
pxtlib/sprite-editor/canvasGrid.ts
pxtlib/sprite-editor/spriteEditor.ts
pxtlib/sprite-editor/tools.ts

Fixes a variety of Sprite Editor bugs
Fixes https://github.com/microsoft/pxt-arcade/issues/1029
Fixes https://github.com/microsoft/pxt-arcade/issues/1031
If the whole screen is selected, there is currently no way to deselect the selection. This change makes it so a single click, inside or outside of the selection deselects.
The top left of the rectangle that is being drawn is set to the center of the preview. This makes the cursor inaccurate. It should be the top left of the rectangle is the top left of the cursor. This way if a user is using a wider tool, all pixels shown colored in cursor are actually painted.
The circle tool should show as 1x1 pixel for all tool width until other widths are supported.

Sprite editor fixes

---

pxtlib/tutorial.ts

fixes https://github.com/microsoft/pxt-arcade/issues/1071
Package snippets are used to load the extensions for the other snippets on the page, and shouldn't be shown as hints

don't show hints for package snippets in tutorials

---

pxtlib/sprite-editor/spriteEditor.ts

fixes issue that I noticed here https://github.com/microsoft/pxt/pull/5618#discussion_r289266523 and then immediately forgot about. Now just deletes the section like it was intended to rather than deleting the entire block
current:
this change:
Also made it so the marquee tool shortcuts keyboard trigger even if you have another tool selected, as the layer itself is still visible at that point - can revert that portion if it's preferred to keep them just to when the marquee tool is selected, though

Fix backspace to delete selected area on marquee tool

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/always_enums.blocks
tests/decompile-test/baselines/block_repeat.blocks
tests/decompile-test/baselines/for_loop_upper_bound.blocks
tests/decompile-test/cases/for_loop_upper_bound.ts

fixes https://github.com/microsoft/pxt-arcade/issues/1034
Doesn't currently handle prefix unary expressions; can add the handling for that, but it seems really niche to add special handling for - negatives will always basically result in a no-op anyway, and having a unary + in front of a numeric literal is not something that I think I've ever seen :)
current behavior: test decompiles to these blocks:
new: test decompiles to these blocks:

Clean for loop decompilation with numeric literal upper bounds

---

pxtsim/embed.ts
pxtsim/runtime.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/monaco.tsx
webapp/src/simulator.ts
webapp/src/srceditor.tsx

Fixes https://github.com/microsoft/pxt-arcade/issues/1068
We had a race condition where the simulator would start running before the webapp had a chance to send the breakpoints to the runtime. As a result, top level breakpoints (e.g. those in "on start") would sometimes not hit.
This PR fixes that by making the simulator pause on the first statement so that the webapp can send the breakpoints (and tell it to continue). Shouldn't be any change for users.

Fix race condition that prevented top-level breakpoints from hitting

---

webapp/public/run.html

IE and Edge can throw an exception when checking if a frameElement exists. This adds a check to see if that exception is thrown.
Fixes https://github.com/microsoft/pxt-microbit/issues/2218

Fix for IE and Edge Embed

---

pxtlib/browserutils.ts
pxtsim/runtime.ts

… at once
Kim noticed that this one wasn't working with multiple classes at once like add / remove class helpers do, so this fixes that.
Also remove some now unnecessary casts now that string is explicitly cast for the IE fix

make element.containsClass helper allow for checking multiple classes

---

pxtblocks/codecardrenderer.ts

Home screen vs docs page used a different format for youtube links ([noted here](https://github.com/microsoft/pxt-arcade/pull/1089#issuecomment-504147809)), which aren't interchangeable when defining a start time. This makes it so they use the same format link
e.g. currently the homescreen has
https://youtu.be/llgKiQGPb0k?t=438s for Re-MakeCode racing games (bottom row)
and https://www.youtube.com/watch?v=mZeyxi75Kyo?t=405s from the link in https://arcade.makecode.com/john-parks-workshop, causing the timestamp being ignored. (passing as `&t=405s` isn't an option as the homescreen will 404 off of that)

use short youtube link so links are same from home screen and docs

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/inferred_boolean_conditionals.blocks
tests/decompile-test/cases/inferred_boolean_conditionals.ts
tests/decompile-test/cases/testBlocks/basic.ts

fixes https://github.com/microsoft/pxt-arcade/issues/1091
turns out ``callinfo.decl.type`` only includes explicit types (``: boolean``) and shouldn't be used directly, so this was requiring the type to be explicitly specified to decompile. Using the inferred types instead fixes the issue.
results of test:

base type check off of inferred type rather than explicit typing

---

pxtsim/runtime.ts

Fixes the issue where the debugger sometimes doesn't resume after hitting a breakpoint.
To arrive at this fix, I basically resorted to logging all of the timeouts that were being resumed and noticed that it consistently hangs IFF the time remaining is set to 0. I have no clue why this fixes the issue, but I tested it pretty thoroughly and I can no longer reproduce it.
My best guess is that somewhere else in this same execution context, setTimeout is being called with an argument of 0 and the function that's being passed needs to be executed before the scheduled timeouts run. I haven't been able to confirm that theory yet so I'll keep digging

Fixing runtime hang when resuming after breakpoints

---

webapp/src/app.tsx

fixes https://github.com/microsoft/pxt-arcade/issues/993 (in most cases)
issue was mainly just that the debounce timeout was so long that it basically never triggered.
This one doesn't fully fix the issue, as you can still escape without the rename saving if you keep typing while clicking close, but that seems like a bit of a rabbit hole to poll for the most up to date name everywhere it is saved - wanted to put up the 'easy fix' that fixes it in most cases before doing that.
Maybe worth lowering the debounce timeout down to 250ms? 500 ms seems to fix the most common case for me at least (click into textbox, type type type, move mouse to go to home screen, click out)

shorten debounce so save actually occurs after typing

---

pxtsim/simlib.ts

Simulator support for removing the metallic waveform. 
Waveform 4 no longer maps to anything

Remove metallic waveform

---

webapp/src/app.tsx

fixes issue noted here https://github.com/microsoft/pxt/issues/5646#issuecomment-504637038 -- recipes were being treated like normal tutorials cause the flag wasn't propagating.
the history doesn't show this happening at all? it was added with the recipes PR [here](https://github.com/microsoft/pxt/pull/5633/files#diff-325ec83a257a791d33bd4484fd67fb24R2744), but blame shows the last change as [this](https://github.com/microsoft/pxt/pull/5674/files#diff-325ec83a257a791d33bd4484fd67fb24R2734) as if that line was never changed (and it shows it last being modified like 2 years before this change [here](https://github.com/microsoft/pxt/pull/3076) ). Not sure how that happened?

fix recipes (flag not propagating)

---

common-docs/blocks-embed.md
docs/blocks-embed.md
docs/extensions/extensions.md
pxtcompiler/emitter/decompiler.ts
pxtrunner/runner.ts
pxtsim/embed.ts
webapp/src/monaco.tsx

As a side effect, decompilation never fails, it just becomes a big gray block.

Bug fixes in client docs rendering

---

webapp/src/monaco.tsx
webapp/src/monacoSnippets.ts

microsoft/pxt-minecraft/issues/884
+ small fix for randint python snippet & name (microsoft/pxt-minecraft/issues/850)

Displaying python snippets in monaco flyout for 'snippetsOnly' blocks

---

webapp/src/app.tsx

We're seeing some difficult to repro issues around deployment like this: https://github.com/microsoft/pxt-microbit/issues/2179
This PR adds tick events to help us understand how widespread the issue(s) are and hopefully we can compare failures to determine likely causes.

Adds tick events for tracking deploy completion time and success/fail stats

---

pxtcompiler/emitter/emitter.ts

This makes `checkType()` into a no-op. @riknoll (and others) any reason this should fail? given that we already handle `any` there is no reason not to handle union/intersection etc (as `any`).
Removal of `typeCheckSubtoSup` is just cleanup as it was disabled anyways.

Remove type restrictions

---

webapp/src/workspace.ts

This fixes https://github.com/microsoft/pxt-arcade/issues/1108 by adding the error message where it detects the 404 error. 
Problem
Fix

Adds error notification to Github 404

---

cli/gdb.ts

This command only works on original BMP and isn't really needed

remove tpwr command from BMP backend of GDB

---

pxtcompiler/emitter/emitter.ts

Without this patch we get:
```typescript
JSON.stringify({ "foo": 1, bar: 2 }) == '{"\"foo\"":1,"bar":2}'
```

Fix emit of object literals

---

docs/writing-docs/tutorials.md
localtypings/pxtarget.d.ts
pxteditor/editor.ts
pxtlib/cmds.ts
pxtlib/tutorial.ts
webapp/src/app.tsx

This lets MakeCode targets register a callback to run whenever a tutorial is completed. The callback only runs on steps with the `@tutorialCompleted` tag, it won't run on any tutorials that do not have that annotation. I tried to make that clear in the documentation but if anyone has a less confusing way of putting it, I'm open to suggestions!

Adding a @tutorialCompleted macro and editor extension

---

localtypings/pxtarget.d.ts
webapp/src/container.tsx
webapp/src/tutorial.tsx

Create 'nether' mode, where the editor doesn't include the default navigation to the homescreen / org url within the editor area. Within a tutorial, it also removes the ``finish`` button on the last step.

lockedEditor apptheme to remove default links

---

webapp/src/app.tsx

fixes https://github.com/microsoft/pxt/issues/5723
With slow internet connection blockly wouldn't be loaded until after it calls ``overrideBlocksFile``, which ends up calling ``pxt.blocks.saveWorkspaceXml`` and breaks in that case. I can get it to repro reliably when using the chrome debugger's ``fast 3g`` throttle setting.

always load blockly before trying to decompile examples

---

pxtpy/lexer.ts
pxtpy/parser.ts
tests/runtime-trace-tests/cases/semicolon_separator.py

fixes https://github.com/microsoft/pxt-minecraft/issues/855
Turns out this was only failing for expressions without ops (typically call expressions) - 
```python
x = 0;print(x + "")
```
succeeds because it grabs the `=` as an operator, but
```python
print(1 + "");print(2 + "")
```
and
```python
x = 0;print(x + "");
```
booth failed because when it tried to grab the operator it grabbed the `;` and didn't recognize it.

Allow semicolons python

---

pxtpy/ast.ts
pxtpy/converter.ts

The TypeScript compiler already handles most of these cases already since TypeScript does not allow duplicate function implementations. However, when we inline functions passed as arguments the name is lost in the transition. 
In other words, this was legal:
```python
def on_update():
pass
game.on_update(on_update)
def on_update():
pass
game.on_update(on_update)
```
while this was not:
```python
def on_update():
pass
def on_update():
pass
```
and now they both show up as errors.

Prevent duplicate function declarations in Python

---

pxtpy/converter.ts
webapp/src/monacoSnippets.ts

https://github.com/microsoft/pxt-minecraft/issues/850
- Fix for charAt, substr. TODO: parseInt, concat of string + any (require str() / int() casting which monaco currently thinks is an error, have not looked too deeply into it)
- Small fix for len(str) erroring in monaco

Fix python toolbox snippets for text, remove switch block

---

docs/writing-docs/tutorials.md
localtypings/pxtarget.d.ts
pxtlib/tutorial.ts
webapp/src/tutorial.tsx

Expects 2-column table in key-value format at the start of markdown file, and hint in  comment syntax
Fixes microsoft/pxt-minecraft/issues/842

Parsing metadata table, use hint comment syntax for v2

---

pxtsim/langsupport.ts

fixes https://github.com/microsoft/pxt-arcade/issues/1134

make optional members of object literals default to undefined

---

pxtcompiler/emitter/service.ts
webapp/src/monacoSnippets.ts

Text toolbox snippets except "compare" should work
https://github.com/microsoft/pxt-minecraft/issues/850

int() casting for python

---

pxtcompiler/emitter/backjs.ts

Not sure this is the right fix as I haven't interacted with this part of the code much at all / don't have full context on it, but it works in the cases I've looked at / was fun to look through. I believe that cases where it would cause things to succeed inappropriately should all be handled as tsc errors already?
fixes https://github.com/microsoft/pxt-arcade/issues/1136, so that it succeeds in the sim like it does on hw

potential fix for crash on access of optional params of interface

---

localtypings/pxtarget.d.ts
pxtcompiler/emitter/service.ts
pxtpy/pydecompiler.ts
tests/runtime-trace-tests/tracerunner.ts
webapp/src/monaco.tsx

Moves the emitType function (takes ts type, emits py) to services.ts so we can populate a python type string on function parameters. Replaces the Python "Callable[[arg1, arg2], ret]" syntax with "(arg1, arg2) -> ret", which is more readable and matches Python's method signature syntax.
Fixes microsoft/pxt-minecraft/issues/885

Display method signature help (types, etc) for python

---

pxtpy/converter.ts

Fixes https://github.com/microsoft/pxt-minecraft/issues/1002; will now convert to just be normal variables in typescript:
```typescript
let A = 5
A = 10
```

don't automatically make capitalized variables constants in python

---

pxtpy/converter.ts

Lexically nested functions are not allowed in strict mode in old safari (I'm personally very surprised they're allowed in any strict modes)
should fix https://github.com/microsoft/pxt-microbit/issues/2237, although I haven't yet tested this patch on the current microbit build (not sure which branches to use) - but this fixes it at the point it was first broken, and I don't think this is a common paradigm

un-lexically nest function

---

webapp/src/monaco.tsx
webapp/src/monacopyhelper.ts

Simple Python formatting provider (called on snippet insertion, paste, etc--same as Typescript formatter). 
Currently formats in two cases:
- If the previous line ends with a colon, indents one space
- If the previous and next lines have matching indents (and the current line is not the start of a code block), matches current indent to previous
TODO: experimenting with some additional rules for pasted blocks and using the next line, but I suspect fewer rules/more straightforward processing might be better here.

Add formatting provider for Python

---

pxtlib/browserutils.ts
webapp/src/app.tsx

ipcRenderer is only used in Minecraft/Code Connection, and we want to fetch the live translations for those (instead of treating as Electron app)

Fetch live translations for all minecraft apps

---

cli/cli.ts
cli/nodeutil.ts
pxtcompiler/emitter/annotate.ts
pxtcompiler/emitter/backbase.ts
pxtcompiler/emitter/backjs.ts
pxtcompiler/emitter/backthumb.ts
pxtcompiler/emitter/backvm.ts
pxtcompiler/emitter/decompiler.ts
pxtcompiler/emitter/driver.ts
pxtcompiler/emitter/emitter.ts
pxtcompiler/emitter/hexfile.ts
pxtcompiler/emitter/ir.ts
pxtcompiler/emitter/thumb.ts
pxtlib/util.ts
pxtrunner/renderer.ts
pxtsim/langsupport.ts
pxtsim/libgeneric.ts
pxtsim/runtime.ts

This improves "compileBinary" by ~25%, and overall compilation by ~15%.
TS compiler is now about half of compilation time (on jumpy platformer). I think further gains will have to come from some sort of incremental compilation.
This also removes support for non-GC build (which I'm 100% sure were broken before, but now it's really gone).

compilation speedup and ref-counting removal

---

pxtcompiler/emitter/emitter.ts

also move `usedDecls` to PxtNode
without this, the following fails, unless `new Foo()` is present somewhere
```typescript
class Foo {
bar = 1;
constructor() { }
}
```

Fix unused classes with field assignments

---

localtypings/pxtarget.d.ts
pxtlib/tutorial.ts
theme/tutorial.less
webapp/src/app.tsx
webapp/src/container.tsx
webapp/src/sui.tsx
webapp/src/tutorial.tsx

Initial components for circle display for tutorial with activity dropdown. The circle is always displayed if activities are present, and if the tutorial has 8+ steps it is displayed on mobile screen sizes.
Currently uses the H1 (#) tag as the divider for each activity, so it's backward-compatible with the current tutorials and activity segments can easily be added to existing tutorials by inserting H1 tags.
We could also use ## for activities, and ### for steps, using the version metadata to determine what kind of parsing to use, but that will make conversions a little more involved.
Will also bring this to the design meeting next week for additional CSS/style iteration

Tutorial progress circle component

---

docs/language.md
pxtcompiler/emitter/backbase.ts
pxtcompiler/emitter/backjs.ts
pxtcompiler/emitter/backvm.ts
pxtcompiler/emitter/emitter.ts
pxtcompiler/emitter/hexfile.ts
pxtcompiler/emitter/ir.ts
pxtcompiler/emitter/vm.ts
pxtsim/runtime.ts
tests/compile-test/lang-test0/51exceptions.ts
tests/compile-test/lang-test0/pxt.json

This is the last big JS language feature missing. Yay!
Depends on https://github.com/microsoft/pxt-common-packages/pull/900
Notes:
* it's supported in ARM, VM and JS (all targets)
* entering/leaving `try` block has a small runtime cost (~one allocation)
* `throw` is very cheap, and independent of call stack depth
* any value can be thrown (including strings, classes, `null`, numbers, `undefined`)
* exceptions currently do not contain stack traces; it would be relatively easy to add in JS, but rather hard in hardware
* we need to think if and how we use this in APIs
* runtime should possibly throw an exceptions in some places instead of panic'ing
* debugger should have an option to stop on exception thrown and unhandled/handled (should be easy to distinguish - just check …

support for throw, try, catch, finally

---

docs/static/tutorial-tool/tutorial.js
docs/static/tutorial-tool/tutorial.ts
pxteditor/editor.ts
pxteditor/editorcontroller.ts
pxtlib/tutorial.ts
webapp/src/app.tsx

In v1 of the tutorial tool I just duplicated the tutorial parsing code because I didn't want to make changes to pxt. Now that it's shipped, I'm removing the duplication and adding an editorcontroller message that imports a tutorial from just the markdown.
This will temporarily break the tutorial tool for all targets until they get bumped. We should do a bump of mc with these changes ASAP once this is merged, so I'm putting the "DO NOT MERGE" label on it

Getting rid of tutorial parsing duplication

---

webapp/src/scriptsearch.tsx

Allows for better sorting of packages in extension dialog by really using the weights in ``pxt.json``.

use weights for all packages

---

docfiles/package.html
docfiles/script.html

Adding analytics to share page. 
Share key is scrubbed in the analytics appInsights.trackPageView event

Adding analytics to share page

---

localtypings/pxtarget.d.ts
localtypings/pxtpackage.d.ts
pxtcompiler/emitter/driver.ts
pxtcompiler/emitter/service.ts
pxtlib/package.ts
pxtlib/service.ts
webapp/src/compiler.ts
webapp/src/package.ts

In Arcade, the feather and edge-connector packages rely heavily on the "pins" category. This category is hidden by default in Arcade through the global setting in pxtarget.json
This change allows an extension to require a block category, in which case it is not hidden anymore.

Allow extensions to display banned block categories

---

pxtcompiler/emitter/backjs.ts

fixes:
```
building /Users/michal/src/pxt-32/libs/hw---samd51
device.d.ts(1,1): error TS9200: Cannot read property 'label' of undefined
```
in arcade build (which were ignored and mostly harmless)

Fix crash in jsEmit when there's no code to run

---

pxtcompiler/emitter/emitter.ts

introduced in https://github.com/microsoft/pxt/pull/5763 ; not sure why we're only seeing it now

Fix crash on m[x] = null

---

localtypings/pxtarget.d.ts
theme/tutorial.less
webapp/src/app.tsx
webapp/src/srceditor.tsx
webapp/src/sui.tsx
webapp/src/tutorial.tsx

- set tutorial card expanded height to match content height
- autoexpand card if there is overflow (still displaying 'less' button)
- save card expand state per tutorial
- small css/accessibility updates

Set tutorial card expanded height to match content, autoexpand

---

theme/themes/pxt/globals/zindex.variables

Fixes microsoft/pxt-minecraft/issues/1104

Set tutorial card z index above block fields

---

docs/defining-blocks.md
pxtblocks/blocklyloader.ts
pxtlib/blocks.ts

Lets you specify the *inner* shadow block for array shadow blocks. For example, in the animation API that @dannytech and @dharinirajah have been making the default value in the array should be images:
To use this, all you need to do is set the `defl` for the parameter on the API to the block ID of the shadow. For example,
```typescript
//% blockId=run_image_animation
//% block="%sprite=variables_get(mySprite) animate frames %frames=lists_create_with with interval %frameInterval=timePicker ms"
//% group="Animate"
//% frames.defl=screen_image_picker
export function runImageAnimation(sprite: Sprite, frames: Image[], frameInterval?: number): void {
}
```
(note the `frames.defl` line)

Array default values with shadow blocks

---

pxtblocks/fields/field_melodySandbox.ts
pxtlib/melody-editor/melodyArray.ts

Fixes https://github.com/microsoft/pxt-arcade/issues/1200
Cleaning up a few things:
* Adds block change events so that we recompile on change and undo/redo works
* Refactors the grid drawing into one function
* Fixes `setText()` so that it no longer gets confused if called after `init()`
* Adds localization to error message

Cleaning up melody editor and adding events

---

pxtblocks/blocklycompiler.ts
webapp/src/blocks.tsx

This PR aims to ease the pain a little bit on Arcade's most common error! Now, if a variable is referenced but never assigned (eg. you dragged out a Sprite block but forgot to change the dropdown) it gets flagged as an error. This only applies to user-declared variables, not locals or function arguments.
Note that this doesn't do any fancy control flow analysis or anything; if I were to drop the set block *after* the first reference it would also remove the error. Hopefully this will catch 90% of the issues and we can decide to do something more complete later.
Also, this error does not stop your game from compiling/running; it's basically linting.

Warn when a variable is never assigned in blocks

---

common-docs/javascript/types.md

The new color package in pxt-common-packages has a namespace named `color`, which unfortunately conflicts with any global variables named color. This was causing checkdocs to fail on pxt-adafruit when I updated to the latest common packages. Not sure if the color package has shipped yet, but we might want to reconsider the name.
In the meantime, I'm fixing it here so that I can get a build of pxt-adafruit going.

Need to change variable name because it conflicts with color namespace

---

cli/server.ts
pxtcompiler/emitter/backjs.ts
pxtcompiler/emitter/emitter.ts
pxtcompiler/emitter/hexfile.ts
pxtlib/main.ts
pxtsim/embed.ts
pxtsim/langsupport.ts
pxtsim/runtime.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/package.ts
webapp/src/simulator.ts

This adds a hidden `.simstate.json` file to project, which can be updated by the simulator code using `board().setStoredState()` API. This is used for `settings` namespace in https://github.com/microsoft/pxt-common-packages/pull/923
This also adds support for storing project name in generated native code and accessing it from the program using `control.programName()`.

support for .simstate.json

---

localtypings/pxtarget.d.ts
pxtcompiler/emitter/backbase.ts
pxtcompiler/emitter/emitter.ts
pxtcompiler/emitter/service.ts
webapp/src/app.tsx

Also adds `?compile=noIncr` to disable incremental compilation
Also we used to restart the simulator on first Download (but not subsequent ones) - fixed that

Fix incremental compiler on hardware

---

cli/cli.ts
localtypings/pxtarget.d.ts

Currently will be used in minecraft as they add new tutorials

Add checkdocsdirs property to appTarget for blanket run of checkdocs

---

localtypings/pxtarget.d.ts
pxtcompiler/emitter/backbase.ts
pxtcompiler/emitter/backjs.ts
pxtcompiler/emitter/backvm.ts
pxtcompiler/emitter/emitter.ts
pxtcompiler/emitter/ir.ts
pxtlib/cpp.ts
pxtlib/service.ts

Normally, a call to `//% shim=...` function that takes a Buffer, Image, or Array will panic when passed `null` or `undefined`. With `//% argsNullable` the function will be passed `NULL` instead.
So far there only seems to be one instance in our library where this makes sense - spi.transfer(buffer, buffer), where one of the buffers can be `null`, but @jwunderl is adding image.equals.

 Add argsNullable comment attribute

---

cli/cli.ts

Read from /docs to match existing checkdocs search pattern

Fix path parsing in checkdocsdir

---

pxtcompiler/emitter/emitter.ts
tests/compile-test/lang-test0/44toplevelcode.ts

Fixes `Cannot read property 'storeByRef' of null` in arcade build.
Introduced in incremental compilation PR https://github.com/microsoft/pxt/pull/5791

Fix crash with top-level for-of

---

pxtblocks/fields/field_melodySandbox.ts
theme/melodyeditor.less

Fixes microsoft/pxt-adafruit/issues/1083, updates melody editor background, "Done", gallery toggle to match parent block color.

Update color setting of melody editor, fix tempo on dark theme

---

localtypings/pxtarget.d.ts
webapp/src/container.tsx

Fixes https://github.com/microsoft/pxt-adafruit/issues/1082
In all of our editors besides micro:bit, the project settings is only a fancy text box where you can rename the project (which you can also do in the main editor). If you are unlucky enough to click on the "edit settings as text", there is a good chance you'll break your project completely. This PR hides the project settings from the cogwheel. They are still accessible via the file explorer (just click on `pxt.json` in the user project).
In micro:bit, the radio pairing options are in that editor so I'm turning it on:
https://github.com/microsoft/pxt-microbit/pull/2401

Hide project settings by default

---

pxtcompiler/emitter/backbase.ts

We're hitting this now with the ControlledSprite class, when you don't control any sprites.

Don't fail on type check of class that is never instantiated

---

webapp/src/app.tsx
webapp/src/idbworkspace.ts
webapp/src/workspace.ts

We use indexdb (idbworkspace) in the webkit embed view of minecraft, but use pouchdb (browserworkspace) for chrome embed. There are issues in the wild due to pouchdb crashes.
See https://github.com/microsoft/pxt-minecraft/issues/1144
This change moves the chrome embed to use indexdb as well.  Old projects are imported first time (a.k.a when indexdb is empty).

Moving to indexdb for chrome embedview in minecraft

---

webapp/src/dialogs.tsx

fixes the error listed in the screenshot in https://github.com/microsoft/pxt-microbit/issues/2379; when I read it before I found a different error and fixed that, but just noticed that there was a screenshot describing this specific error.

Hide user icon on import url dialog

---

webapp/src/app.tsx

fix issue noted in https://github.com/microsoft/pxt-microbit/pull/2409; high contrast mode wasn't being toggled in the sim because this call to restart was just doing the fast restart, not updating the theme / state.

restart sim on contrast change

---

common-docs/browsers.md
common-docs/browsers/linux.md
common-docs/browsers/technical.md
common-docs/browsers/windows.md

We will still support IE11 on microbit for at least this school year. This removes reference to IE11 as supported browsers to discourage users. Also updates some of the chrome versions.

Remove reference to IE11 from docs as a supported browsers

---

webapp/src/app.tsx
webapp/src/blocks.tsx

If you are on a slow machine and you make a change right before you open the melody editor, the debounced compile callback will cause the simulator to start anyways. Changing the logic so that the simulator won't start if a dropdown is open in blockly (i.e. you are actively changing something).

Don't start the simulator if melody editor is visible

---

Jakefile.js

Without this, running jake without any changes rebuilds the web app.

Avoid unncessary rebuilding when running 'jake'

---

docs/writing-docs/user-tutorials.md

I've created a video showing how to make a shared user tutorial. If it's seems ok, maybe someone can put it up to YouTube and I can add it to the 'User Tutorials' page:
https://microsoft-my.sharepoint.com/:v:/p/v-gani/EY1k6lxsbhlPubBRsWt1R04BZTfb0BnQoCIyWLiUy06MIw?e=7kcpdz

Add a video to `User Tutorials` page

---

cli/cli.ts
docs/cli/buildsprites.md
localtypings/pxtarget.d.ts
pxtblocks/fields/field_sprite.ts
pxtlib/sprite-editor/gallery.ts
pxtlib/sprite-editor/spriteEditor.ts

Just on a per image editor type basis for now, can add search or user filtering later but probably needs some ui design / feels a bit separate
related prs:
* https://github.com/microsoft/pxt-common-packages/pull/953
* https://github.com/microsoft/pxt-arcade/pull/1271
makes it so you can filter things into or out of the image editor gallery based off tags:
Couple questions;
If we want to use these tags for some sort of search eventually, would need to extract them for localization; it seems like having these as commentAttributes as they are here would allow for that, but just want to confirm
I haven't document the format for the new fields in the docs, but for now its:
* **filter**: a string containing a series of tags, where tags beginning with "!" mean to exclude images with that tag and …

Add image tags and gallery filter

---

pxtsim/simdriver.ts
webapp/src/app.tsx

no bad double click necessary anymore
second commit also makes simtoolbar start and restart buttons focus on sim as well

auto focus on sim after clicking play button

---

pxtrunner/renderer.ts

fix https://github.com/microsoft/pxt-microbit/issues/948; make snippet buttons so they work with keyboard navigation
Implementation is just copied from https://github.com/microsoft/pxt/blob/922fac34bc6fc9e9d0b9858e9e440933aba69291/webapp/src/sui.tsx#L48

make snippet buttons fire event on keyboard action

---

docs/static/playground/pxt-common/pxt-helpers.js
libs/pxt-common/pxt-helpers.ts

fixes https://github.com/microsoft/pxt-microbit/issues/2072
fixes https://github.com/microsoft/pxt-arcade/issues/782
matches javascript at least? Sorting number arrays isn't generally useful in javascript without adding the callback, but at least it will do something.

add default array.sort behavior for numbers and strings

---

localtypings/pxtarget.d.ts
pxteditor/editor.ts
webapp/src/app.tsx
webapp/src/projects.tsx

This adds a dialog that pops up when a new project is created using the big button in the home screen. We've discussed that with David a few months back. This is controlled by appTheme option (to be enabled for Arcade).
With the new `settings` namespace, the storage resets when the name changes, and also stays on device when the name is the same on two programs. Because of that it's more important now to name projects.
If you hit "Create!" with no name, you get "Untitled".

Add target option to name project when created

---

pxtcompiler/emitter/thumb.ts
webapp/src/compiler.ts

Fixes https://github.com/microsoft/pxt-arcade/issues/1118
Gotta love JavaScript!
The second change is logging output.txt when there are errors to JS console, since this is usually where more advanced people would be looking.

Emit ldlit in Thumb in the correct order

---

pxtblocks/blocklyloader.ts

fix checks for blocks with params that have intersection types
Nice to support in general, but the case I'd be using it for is https://github.com/microsoft/pxt-arcade/issues/1254, as it's rejecting because it doesn't recognize sprite as a structural subtype of ParticleAnchor, and easiest fix without potentially breaking existing scripts / ability to remove from any ParticleAnchor is to make the type for the ``Sprite | ParticleAnchor``.
quick test / example:
```typescript
namespace info {
//% block="test string int number $myInput"
export function testBlock(myInput: string | number) { }
//% block="test sprite int sprite[] $myInput"
export function testBlock2(myInput: Sprite | Sprite[]) { }
}
```
Can't think of a place to add tests for this immediately, but if possible that seems like it …

allow intersection types in blocks

---

localtypings/pxtpackage.d.ts
pxtblocks/blocklytraverse.ts
webapp/src/package.ts
webapp/src/snippetBuilder.tsx

Helps me prototype the mod-a-game experience and they're generally useful improvements for the SnippetBuilder.
- Allow SnippetBuilder to emit many top-level blocks
- Add support for external .ts files that has snippet content (much easier authoring experience for large snippets)
- Auto-format if <2 existing blocks
- Adds "replace" output mode that replaces all old blocks
The implementation isn't perfect yet since it cannot distinguish on event parameters (on_game_update 500ms vs 1000ms) but it's already more useful for a few scenarios. TODO included in code.
Tested using this custom package: https://github.com/darzu/ModGame

Snippet Builder improvements

---

pxtsim/embed.ts

Pass tickEvent out of iframe for simulator playtime logging. Uses https://github.com/microsoft/pxt-arcade-sim/pull/15

Post message from iframe for simulator focus and blur

---

common-docs/blocks/loops/break.md
common-docs/blocks/loops/continue.md
docs/playground-runner.html
localtypings/pxtarget.d.ts
pxtblocks/blocklyloader.ts
pxtcompiler/emitter/decompiler.ts
pxtlib/blocks.ts
tests/common/testUtils.ts

Same as pauseUntil, enabled in pxtarget.json. ``break`` is generally useful to break out of loops without having to declare a variable.

adding options for break / continue

---

webapp/src/blocksSnippets.ts

Fix for https://github.com/microsoft/pxt/issues/5913
Don't add break/continue to cache block list unless they are enable on the target

make sure break/continue are optional

---

localtypings/pxtarget.d.ts
pxtblocks/blocklyloader.ts
pxtcompiler/emitter/decompiler.ts
tests/common/testUtils.ts

Break and continue blocks should always be defined in case the user decide to decompile TS code with those keywords.
The service does not have pxtarget information to properly filter those out at compile time... so it's a way to get the blocks.
The pxttarget flags breakBlock and continueBlock decide wheter they are visible in the loops category.
Fix for https://github.com/microsoft/pxt/issues/5922
@FranklinWhale

Fix missing break/continue statement

---

webapp/src/app.tsx
webapp/src/dialogs.tsx
webapp/src/gitjson.tsx

github improvements

---

pxtlib/browserutils.ts
pxtlib/webble.ts
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/compiler.ts
webapp/src/lang.tsx

This removes all the dynamic properties as  part of our telemetry
What we used to emit
EntityName : activity
PropertyName  :  blocks.create.forever
PropertyValue : 25
New telemetry
EntityName : block.create
PropertyName  :  block
PropertyValue : "blocks.create.forever"
Individual events are sent as part of count. We could add separate count PropertyName to the existing blocks.create as well.

Telemetry fix

---

theme/github.less
theme/themes/pxt/globals/site.variables
webapp/src/gitjson.tsx

This also removes hover highlight. Github doesn't do it, and it seem too much together with inline diff markers.
The inline diff only kicks in for single-line changes (that a single line is updated, with at least one unchanged line above and below).

Implement inline-diff for single line changes

---

pxtsim/langsupport.ts
pxtsim/runtime.ts

* pause(0) just hangs forever in current implementation; now it will yield to other threads
* there was also a memory leak in timeout implementation (`filter` doesn't modify the list)
Fixes https://github.com/microsoft/pxt-arcade/issues/1098

Fix pause(0) and memory leak

---

pxtcompiler/emitter/emitter.ts
tests/compile-test/lang-test0/44toplevelcode.ts

fixes https://github.com/microsoft/pxt/issues/2251

Treat globals defined inside loops as locals

---

pxteditor/editor.ts
webapp/src/app.tsx
webapp/src/blocks.tsx

Commit field editors (stable4.0)

---

docs/translate.md

I made a video that gives an general overview of the localization process. This is one of maybe three videos to help people work on translation. I'm thinking of doing one for signing up to translate and another that talks about the translation tasks/activities.
[Localization video](https://microsoft-my.sharepoint.com/:v:/p/v-gani/EdA9BnEtYEhCrBc23fGFncgB7UJEbLoLy8qYNm-Dlcrn6Q?e=5tXoZM)

Add 'Localization Overview' video to the translate page

---

webapp/src/scriptmanager.tsx

fix https://github.com/microsoft/pxt/issues/5941
fix https://github.com/microsoft/pxt-arcade/issues/1334
as a side note, the project manager view gets slooooooooow when you have a lot of projects here. admittedly this is with >1500 projects on my local serve, but still, slooooooooow

fix dropdowns in project view high contrast mode

---

pxtrunner/runner.ts

fix https://github.com/microsoft/pxt-microbit/issues/2342; element just needs to be properly labeled as disabled

disable / enable backButton in sidedocs view

---

pxtblocks/blocklycompiler.ts
tests/blocklycompiler-test/baselines/loops.ts
tests/blocklycompiler-test/baselines/loops_local_variables.ts

Fixes https://github.com/microsoft/pxt-microbit/issues/2453
Also renames the variable we emit from `i` to `index` to better match our other for-loop blocks

Variable names for repeat blocks shouldn't conflict with user variables

---

webapp/src/coretsx.tsx

fixes https://github.com/microsoft/pxt-microbit/issues/2332; prompts that used this dialog (this one, duplicate in project list view, blockly create a variable, etc - anything using promptAsync) all had this bug. Change in here was just adding the aria-label, rest is just splitting up the line as it was long / getting hard to parse.

add aria label for text input boxes

---

theme/themes/pxt/globals/site.variables

Not sure why we would want Times New Roman. Looks bad and everyone's first instinct is that something broke:
after:
maybe I'm missing something

remove Times New Roman

---

theme/docs.less

closes https://github.com/microsoft/pxt/issues/5985
I went with about 1/4 the white space around the divider as it felt pretty aggressive to me

divider line above headers

---

docfiles/style.css
pxtlib/docsrender.ts

closes https://github.com/microsoft/pxt/issues/5986
Align all docs content to the left:

align docs content left

---

webapp/src/projects.tsx
webapp/src/scriptmanager.tsx

Refactor logic that selects icon (mk logo/github/board) into component.

refactor icon logic for home screen/project manager

---

webapp/src/blocks.tsx
webapp/src/compiler.ts

Clear compiler caches when opening blocks file in order to force toolbox refresh. This is needed when going from custom.ts to blocks; otherwise the toolbox does not refresh.

Refresh custom blocks

---

cli/server.ts
docfiles/docs.html
docfiles/docs.js
localtypings/pxtarget.d.ts
pxtblocks/blocklyloader.ts
pxtlib/blocks.ts
pxtlib/commonutil.ts
pxtlib/crowdin.ts
pxtlib/docsrender.ts
pxtlib/package.ts
pxtlib/service.ts
pxtrunner/runner.ts
pxtsim/runtime.ts
webapp/public/index.html
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/dialogs.tsx
webapp/src/lang.tsx

Integration of the Crowdin In Context support in MakeCode. 
* not supported on ie
* live test (gearwheel -> language -> translate the editor): https://makecode.microbit.org/app/eafdb91f42807c21c8fe0214992be13211550d26-f42e68aeb6
Add a menu item in blocks context menu to translate.
Crowdin has a nifty web widget that hooks into the DOM mutation events to provide live translation. It uses a fake language (code pxt) that contains guid strings; when crowding sees one of the guid added to the DOM tree, it swaps it with the current translation + button to edit.
Things get a bit more tricker for our blocs -- because we parse the translated string. Obviously parsing the GUID does not work. To work around this, MakeCode first add each block string into the DOM tree, let's crowdin modify it and …

Translations in context in editor

---

docs/static/playground/pxt-common/pxt-core.d.js
libs/pxt-common/pxt-core.d.ts
localtypings/pxtarget.d.ts
pxtcompiler/emitter/driver.ts
pxteditor/editor.ts
pxtlib/docsrender.ts
webapp/src/app.tsx

For the hour of code, the Minecraft team wants to be able to send a command when the code in "onStart" starts, and when it ends. This generates codeStart/codeStop files for a tutorial project & inserts them before and after main.ts. The files call "onCodeStart"/"onCodeStop", which are implemented by the target.

Add lifecycle functions before and after tutorial code

---

localtypings/blockly.d.ts
package.json
pxtblocks/blocklyloader.ts
theme/toolbox.less
webapp/src/blocks.tsx

Changes for:
- Context menu options (fixes https://github.com/microsoft/pxt/issues/6001)
- Scroll wheel binding to "move" instead of "zoom"/improved zoom parameters
- Trash icon for flyoutOnly block drag
- Variable XML generation
- Console warnings
Requires https://github.com/microsoft/pxt-blockly/pull/250, https://github.com/microsoft/pxt-blockly/pull/251

Blockly fixes for context menu, flyout trash icon, workspace scroll

---

pxtblocks/fields/field_colorwheel.ts
pxtblocks/fields/field_position.ts
pxtblocks/fields/field_protractor.ts
pxtblocks/fields/field_speed.ts
pxtblocks/fields/field_turnratio.ts

Crashing because the precision field is not optional anymore. All sliders are still broken becaseu parseFloat(minValue) evaluates to 0, the min = -infinity.
https://github.com/microsoft/pxt-blockly/blob/55ac033fcc974ae82a476b9516dabd95d7ec0811/core/field_slider.js#L47
might be good to bump minor too.

precision not so optional anymore

---

pxtcompiler/emitter/emitter.ts

Fix for https://github.com/microsoft/pxt-maker/issues/255

don't crash on missing node

---

pxtlib/tutorial.ts
tests/tutorial-test/baselines/legacySteps.json
tests/tutorial-test/baselines/singleStep.json
tests/tutorial-test/cases/legacySteps.md
tests/tutorial-test/cases/singleStep.md

Stripping metadata to ensure parsing of legacy tutorials (### Step) is supported

Allow one step tutorials, strip metadata before parsing, tests

---

webapp/src/projects.tsx

LEGO has a category of cards without names. It generates react key clashes.

handle case when project gallery item name is undefined

---

pxtrunner/renderer.ts

sig macro also shows translation string for block

sig translate

---

docs/defining-blocks.md
localtypings/pxtarget.d.ts
pxtlib/service.ts
tests/blocklycompiler-test/commentparsing.spec.ts

It's just much easier for extension writers to inline all the translations.

support for loc strings in attribute

---

webapp/src/blocklyFieldView.tsx

The old sprite editor could go down to ~500px of viewport height and still be usable. The new sprite editor is taller, so the minimum viewport height it needs before the palette starts getting cut off is about ~800px.
This tweak drops that minimum height to about ~600px. If the workspace is too narrow, it will break the bounds of the editor and overlay the header/footer.
I think this should cover most reasonable screen sizes (including chromebooks)

Better resize logic for the sprite editor in narrow windows

---

pxtcompiler/emitter/decompiler.ts
tests/decompile-test/baselines/nested_enums.blocks
tests/decompile-test/cases/nested_enums.ts
tests/decompile-test/cases/testBlocks/enums.ts

Fixes the issue where the "stop all animations" block in arcade doesn't decompile. I couldn't find an issue for it.

Support decompiling enums inside of namespaces

---

docfiles/docs.js
docfiles/macros.html
pxtlib/docsrender.ts

There was a change to pxtlib/docsrender that relied on docfiles macros being updated, which can't be applied until all targets have the new & improved macros in their docfiles - that is, until all targets are bumped to a version of pxt containing that PR.
this should fix TOC for now in both situations, with some TODOs to clean it up later

fix toc for now

---

docfiles/macros.html
pxtlib/docsrender.ts

The drop downs where appearing blank:
Now this is fixed by this PR in two ways:
1. if docsrenderer is updated:
we handle the menus correctly
2. if docsrenderer is not updated:
we hide the menus (there is no way to show them correctly without updates to docsrenderer.ts)
So this PR is safe and backwards compatible with both modes. When the docrenderer change hits the backend, we'll see (1) but if macros.html reaches targets before it's updated we'll see (2)

TOC menu fixes

---

docfiles/footer.html
docfiles/style.css
theme/docs.less

just adds back in support for a light theme to docs; it's actually easy enough to support when you're otherwise just changing the hue. Can add light coloring to the ToC if we want too I suppose?

fix maker colors / docs light theme

---

docfiles/docs.html
docfiles/docs.js
docfiles/footer.html

Update docs html to support corwdin in context translation. 
(note: I have not ported the localhost server changes to test this locally to keep the patch small).
This fix is needed to enable in-context translations in micro:bit.

[stable5.15] integrate translation of docs

---

pxtlib/util.ts

https://support.crowdin.com/api/language-codes/
Minecraft sends us nb-no and should be handled with "nb" here

Adding support for nb as defined in crowdin

---

package.json
pxtlib/toolbox.ts

- Hex parsing fix
- Decimal/negative number fix

Bump pxt-blockly to 2.1.6, update color parsing

---

pxtrunner/renderer.ts

leave them left aligned like everything else. This is for ```sim snippets

don't center sim view for docs 2.0

---

package.json

Strips old xml namespaces from imported projects

Bump pxt-blockly to 2.1.8

---

docs/contact.md

Add the forum link to the page. Also, include EV3 in the editor's contacts., a few formatting adjustments.
Closes #6074

Update the contact page with forum link

---

theme/tutorial.less

Previously images were getting the center class from in docsrender.ts, but with docs2.0 being left aligned that changed.

recenter images in tutorial hints

---

theme/tutorial.less
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/toolbox.tsx
webapp/src/tutorial.tsx

- Adds labels if "flyoutOnly" is specified in tutorial markdown
- Fixes issues with block centering for flyoutOnly
- Centers trash icon based on flyout size in flyoutOnly view
- Fixes microsoft/pxt-arcade#1402

Add workspace labels for flyoutOnly view

---

webapp/src/app.tsx

Before (~22s to load tutorial from homepage on localhost, throttling to "Fast 3G"):
After (~ 9ms, localhost, fast 3G):
Starts loading pxtblockly.js after the homepage has been loaded, so it shouldn't affect homepage interactivity. This won't make the initial minecraft tutorial load faster (they enter directly into the tutorial) but should be useful generally... unless anyone sees any pitfalls? I profiled the homepage a couple times and it didn't seem to make a noticeable dent.

Start blockly load on homepage to speed up new tutorial/project load

---

package.json

Fixes "Create new variable" in variable dropdown

Bump pxt-blockly to 2.1.10

---

theme/blockly-core.less

Fixes https://github.com/microsoft/pxt-minecraft/issues/1292

Override semantic to always display tooltip

---

localtypings/pxtpackage.d.ts
pxtlib/package.ts
webapp/src/blocks.tsx
webapp/src/monaco.tsx
webapp/src/scriptsearch.tsx
webapp/src/toolboxeditor.tsx

We keep a cache of the resolved version of a package in pxt.json. This is bad since it modifies program content and potential disastrous in the context of co-authoring and merging.
This change moves installedVersion to the package itself. Everything seems to work.
Note: not systematically cleaning on load as it would modify scripts and have some unintentional results.

moved installedVersion to package

---

pxtsim/runtime.ts

Fixes https://github.com/microsoft/pxt/issues/6091
Fixes https://github.com/microsoft/pxt-arcade/issues/1400
I think this was just an oversight, all of the rest of the calls to loop() looked good...

Fix debug resume frame exception

---

cli/cli.ts
pxtlib/initprj.ts
webapp/src/app.tsx
webapp/src/workspace.ts

A few updates to the logic to populate a github project; to align better with classroom. This PR fixes the following flow:
* teacher creates github classroom assignment with empty repo
* student gets assgiment and generates empty repo
* student imports empty repo in makecode (missing token handled)
* empty project populate landing on blocks
Todos:

updated logic to init project for github

---

pxtblocks/blocklycompiler.ts
tests/blocklycompiler-test/baselines/empty_array_inference.ts
tests/blocklycompiler-test/cases/empty_array_inference.blocks
tests/blocklycompiler-test/test.spec.ts

Fixes https://github.com/microsoft/pxt-arcade/issues/1341

Fixing array inference bug when arrays are assigned to empty

---

pxtblocks/fields/field_position.ts

Fixes the issue where the handle position in the slider of the position picker is in the wrong place. There isn't a bug filed, but here's a demonstration:

Fix slider position in the position picker

---

webapp/src/app.tsx

Minecraft autorun issue https://github.com/microsoft/pxt-minecraft/issues/1280
Minecraft autorun is disabled and hence the play button should never change to pause button.

Fixing autorun issue for Minecraft

---

cli/cli.ts
cli/nodeutil.ts
docs/cli/checkdocs.md
localtypings/pxtarget.d.ts

Don't allow files > 5Mb in docs, flag any file > 1Mb.

checking for file sizes in docs

---

webapp/public/docs.html

one of my docs2.0 coloring changes accidentally also applied to sidedocs in a weird way (current arcade beta):
fixes that / makes the background white again
edit:
ahh, this applies to minecraft/beta too, might want to take this @abchatra:

don't make sidedocs purple (/ docs color)

---

localtypings/pxtarget.d.ts
webapp/src/share.tsx

Fixes https://github.com/microsoft/pxt-arcade/issues/1397
There were two issues here:
1. The keyboard shortcuts only worked if the simulator had focus
1. The shortcut for capturing a screenshot never worked because it required you to press the button first

Fix keyboard shortcuts in the share dialog on arcade

---

pxtblocks/blocklycompiler.ts

Fixes https://github.com/microsoft/pxt-arcade/issues/1131
In the Blockly compiler we declare a bunch of points for the primitive types (string, boolean, etc). The union logic was occasionally assigning those points a parent type which would then get leaked to other projects. This fixes that logic and also removes a useless line in the for-of logic.

Fixing leaked state in Blockly type inference

---

package.json
webapp/src/projects.tsx
webapp/src/snippetBuilderInputHandler.tsx
webapp/src/sui.tsx

fixes https://github.com/microsoft/pxt-minecraft/issues/1304
just use an anchor tag for links, and manually handle focus for the links.
needed to get a ref to the element, so this pulls in the newest @types for react that is supported for the current typescript so we can use createRef (added in 16.3). There were a few quick fixes from that bump (explicitly converting to string / number)

Fix minecraft EE homepage links on ios

---

webapp/src/projects.tsx

accidentally dropped this from https://github.com/microsoft/pxt/pull/6127 when i was getting the focus to propagate correctly for links, and didn't notice until after that got merged.

add back autofocus for buttons on home screen

---

docs/writing-docs/tutorials.md

Add in a section describing use and recommendations for images in the tutorial steps.

Include an 'Images' section on the tutorial page

---

theme/github.less
theme/themes/pxt/elements/segment.overrides
theme/themes/pxt/modules/dropdown.overrides
webapp/src/app.tsx
webapp/src/cloud.tsx
webapp/src/cloudsync.ts
webapp/src/editortoolbar.tsx
webapp/src/filelist.tsx
webapp/src/githubbutton.tsx
webapp/src/githubprovider.tsx
webapp/src/gitjson.tsx
webapp/src/projects.tsx

Round 2 on github signin.
Test build: https://arcade.makecode.com/app/9e6ac0d23e6cbde4d6a341a2c8979cb96a8c15d9-1db5da5931

Github experience

---

theme/docs.less

default sui makes .ui.grids have `margin: -1em`, so it's slightly offset from the left line everything else follows:
fixes that:
(can do just margin-left, but it looks kind of cramped to me when there is text just below in the current version as well)

don't give videos negative margins in docs

---

pxtpy/converter.ts
pxtpy/pydecompiler.ts
tests/runtime-trace-tests/tracerunner.ts

Fixed three issues:
- `skipLibCheck` is necessary for plain TS compilation (sometimes, depending on NPM installs it seems)
- fix writing an object ([object Object]) instead of typescript code in test case due to "any" type usage
- fix how we py decompile built-ins like "console.log"
now "jake testtraces" works again

Fix python<->typescript runtime trace tests

---

webapp/src/blocks.tsx
webapp/src/editortoolbar.tsx

Fixes https://github.com/microsoft/pxt-minecraft/issues/1336, where "undo" is disabled by default and the editor buttons don't re-render on workspace drag. Rather than forcing a re-render, we just enable the undo button when the user has no actions. It will be disabled as usual if the user has performed actions & reached the end of the undo stack.

Enable undo button on project load

---

package.json

Allows custom image URL as Blockly workspace background (Minecraft HOC)

Bump pxt-blockly to 2.1.12

---

.travis.yml
Jakefile.js
tests/runtime-trace-tests/tracerunner.ts

Enables the Python<->STS "runtime trace tests" which are our main correctness tests for Python<->STS in Travis CI.

run tracetests as part of travis

---

webapp/src/fileworkspace.ts

makes deleting a project in the electron app on mac actually delete the project
Issue was that https://github.com/microsoft/pxt/blob/7a2f76aee965c687813743ea09ea6fffb1ca2c85/webapp/src/app.tsx#L1079 was setting the text to a new instance of {}, which is not equal to ``delText``.
``delText`` was added in a rather large pr for cloud sync (https://github.com/microsoft/pxt/pull/4550/files#diff-b91ea3a494edc6744e928a35b7b150b5R42); if there does need to be distinction between `h.isDeleted` and `pkg.isDeleted` for cloud sync, I could just make it read from ``pkg.header.isDeleted`` on the electron app side instead

fix delete in electron app on mac

---

localtypings/pxtarget.d.ts

quick patch to fix typings for electron app; pxtc is an alias for ts.pxtc created in pxtlib/commonutil which everything else includes, but the electron app just copies this typings folder over without that alias-ing so it got upset when trying to compile.

fix typings for electron app

---

pxtblocks/blocklycompiler.ts
tests/blocklycompiler-test/baselines/just_empty_array.ts
tests/blocklycompiler-test/cases/just_empty_array.blocks
tests/blocklycompiler-test/test.spec.ts

Fixes https://github.com/microsoft/pxt-microbit/issues/2508
Fixes https://github.com/microsoft/pxt-arcade/issues/1444
This was regressed by https://github.com/microsoft/pxt/pull/6112. Our blockly compiler tries to make any variable that doesn't have a narrowed type into a number. I'm adding a hack to fix this very specific case of assigning a variable to an empty array and nothing else. We can't narrow the type based on the empty array, but we need to use number[] and not number.

Fix array inference regression when vars are only assigned []

---

webapp/src/compiler.ts

Adds caching for external packages as well. I key the database on the package name, which should be fine unless you have multiple projects with different versions of the package installed. Seems like a small scenario. Most the db code is based off of @pelikhan's translation work

Cache API info for external packages in indexeddb

---

cli/cli.ts
webapp/src/compiler.ts

I'm getting a crash on rebundle because it hits the `null` path and tries to destructure null

don't crash on --rebundle

---

cli/cli.ts
webapp/src/compiler.ts

1. In Minecraft we have a package that overrides APIs in the core package, so tweaking the cache logic so that it will override the APIs if they are different. Nothing changes for GitHub packages
1. Fixes the `custom.ts` scenario for exporting blocks from the user project

Fixing two API cache bugs

---

cli/cli.ts
pxtlib/cpp.ts
pxtlib/github.ts
pxtlib/initprj.ts
pxtlib/main.ts
pxtlib/package.ts
pxtrunner/runner.ts
webapp/src/app.tsx
webapp/src/gitjson.tsx
webapp/src/package.ts
webapp/src/pxtjson.tsx
webapp/src/scriptmanager.tsx
webapp/src/workspace.ts

We need to consistently add a newline after JSON.stringify because github does add it when manually editing the pxt.json file. Otherwise it leads to weird "whitespace only changes" situations with github integration.
Adding a helper class and consistently using it to serialize.

Unify pxt.json stringifycation

---

cli/cli.ts

Reduce the size of the generated targetlight.json, move api-cache to temp folder.

delete api info from targetlight

---

pxtlib/cpp.ts

Generally, headers need to be processed before sources, as they contain definitions (in particular of enums, which are needed to decide if we're doing conversions for function arguments). This can still fail if one header uses another and they are listed in invalid order...

Order .h files before .cpp/.c etc when parsing

---

pxtlib/browserutils.ts

This used to 24 hours ahead of current time (Date.now). But indexdb stored just the current time. 
This means once cached in the MemTranslationDb the cache never expires for that session. 
It is unclear how this is better, when the time stamp just should match the existing timestamp. Caller of the getAsync decides how to expire the cache.

Changing the MemTranslationDb time entry

---

webapp/src/app.tsx

Kind of an edge case, but if the tutorial is loading and the window refreshes before the #editor is added (pretty hard to hit in the wild, but can repro consistently with a throttled connection + timed refreshing), it will load the home screen. Only comes up in Minecraft, because they are heavily using the #tutorial hash command and often have to work on a slow connection, I guess.

Stay in editor after loading tutorial from hash

---

theme/home.less
webapp/src/projects.tsx

We serve a large amount of large .gifs that could be 5x smaller as .mp4s.

support for setting large image as .mp4

---

docfiles/tocheader.html
localtypings/pxtarget.d.ts
pxtlib/docsrender.ts

In theory should fix header name when combined with adding a docsHeader, eg https://github.com/microsoft/pxt-maker/pull/258
--->

add doc header field to apptheme

---

cli/cli.ts

fixes https://github.com/microsoft/pxt-arcade/issues/1357
Almost none of the /reference docs in arcade were available in the electron app while offline, because they typically live with the code; e.g. https://github.com/microsoft/pxt-arcade/tree/master/libs/device/docs/reference/game and https://github.com/microsoft/pxt-common-packages/tree/master/libs/game/docs. This change packages up the docs from bundleddirs.
worth noting, in `getPackageDocs`, I'm recursing first to the additionalFilePath (typically where the package actually lives e.g. in common packages), then to any dependencies listed, and only after all that is done pushing the docs of the package to the render queue, so that the docs 'closest' to the repo get applied last / overwrite any previous ones. Intention here is that if …

Include docs in bundledDirs in static package

---

pxtblocks/blocklycompiler.ts
pxtblocks/blocklydiff.ts
pxtlib/github.ts
pxtlib/service.ts
tests/blocklycompiler-test/baselines/draggable_primitive_reporter.ts
tests/blocklycompiler-test/baselines/functions_v2.ts
tests/blocklycompiler-test/baselines/mc_old_chat_blocks.ts
webapp/src/app.tsx
webapp/src/gitjson.tsx
webapp/src/workspace.ts

This change mostly ensures that no corruption occurs if merge errors happen in a blocks file. The merging of blocks relies on merged TS -> blocks. The current logic works as follows: 
* if the merge is trivial (unmodified A or B, just grab the B or A)
* clear the .blocks file to force a TS -> blocks decompilation path
* ensure that no conflicts were found in TS merges

Blockly merge (part 1)

---

cli/cli.ts
pxtlib/main.ts

Could you take a look if this makes sense? It seems to work for me.
It cuts the size of the API info from 31M to 11M and compressed size from 2.6M to 2.0M (1.2M of the compressed size is sources of our packages).
In future we could use the same scheme for cached API info in indexdb.

Add defaults when loading api cache, and remove them when saving

---

theme/common.less

The fix for Minecraft ( https://github.com/microsoft/pxt/pull/5738 ) seems to have unwanted sideeffects for other editors. This fix restricts that fix to the transparentEditor scenario.
On a small view with editor toolbar collapsed, the buttons are misplaced.

Fix alignment of icons in non-transparent editor toolbad

---

cli/cli.ts
cli/nodeutil.ts

fixes https://github.com/microsoft/pxt-microbit/issues/2514, and a few small bugs I saw along the way (e.g. `.html` files were being converted to ``.h.html`` files).
this was failing because`resolveMD` was failing to locate the files listed as dependencies of bundleddirs (e.g. http://localhost:3232/device/usb/troubleshooting goes to not found even though https://makecode.microbit.org/device/usb/troubleshooting works) -- so I fixed that by including the dependencies in those look ups in the same way https://github.com/microsoft/pxt/pull/6196 did.
Also, building a staticpkg is the only place that we already have the md file readily available when calling it so it seems better to just pass that along anyways.
Also did a quick pass at trying to clean things up a little bit to ideally make it …

Fix micro bit static pkg / local serve pathing

---

webapp/src/share.tsx

Currently in arcade/beta any time you press the R key it screenshots, which is really annoying. This fixes that

only fire share screen record when share screen visible

---

package.json

This pulls in https://github.com/microsoft/pxt-monaco-typescript/pull/9, which fixed completions for functions that have callbacks with parameters in namespaces: fixes https://github.com/microsoft/pxt-arcade/issues/1435 and I suppose https://github.com/microsoft/pxt-microbit/issues/1110. I think I might have had another issue in arcade for it too at some point but I can't find it right away

use qualified names in completions for monaco

---

webapp/src/app.tsx

When user clicks ``fullscreen`` button in sim toolbar, focus on simulator automatically.
Also adds a guard for startStopSimulator so that it only grabs focus to the simulator if the user has clicked on something to trigger it - I believe there was some interaction with auto run changes that made it take focus improperly at times, and we only ever want it to redirect focus when the buttons were explicitly pressed.

focus on full screen, only focus when simulator states changes from user action

---

cli/crowdin.ts

re: https://github.com/microsoft/pxt/pull/6204, it looks like these were just pushing / pulling the translations for the bundledDirs themselves, not dependencies of those packages.
I believe this *should* fix that, but I have no clue how to test this / if I'm even able to at the moment :)

Crowdin bundled deps

---

pxtsim/simlib.ts

fix https://github.com/microsoft/pxt-arcade/issues/1439 (though we'll probably want to play with it a bit more?)
easiest example of this being problematic is pressing `a` / `b` in https://makecode.com/_56E9mRCtHhyb vs a random youtube video (you probably want to put your volume down pretty low); the default volume in arcade (which is 128 out of 256) is *significantly* louder than youtube videos at max volume (e.g. https://www.youtube.com/watch?v=svYp2cqKoUQ or https://www.youtube.com/watch?v=zGP6zk7jcrQ, music videos seem to be a bit louder but nowhere near our volume) - with headphones in at min system volume on my mac, the square wave almost hurts my ears.
This scales down all volume to 1/4 the current volume in the sim. From a quick sample (@darzu and I), the perceived volume with this …

Make simulator sounds quieter

---

theme/common.less
webapp/src/lang.tsx

Make the lang picker on the home page match the one added to the docs in https://github.com/microsoft/pxt/pull/6064
old -> new (new has colored headers for each code card, hard to tell since it loops)

Make lang pickers match

---

cli/cli.ts

when using buildsprites, ignore empty frames - right now it can be annoying to put in animation frames or tiles that don't have explicit names, as you have to densely pack them into the image, and then name each frame if it's not fully filled in - e.g. in https://github.com/microsoft/pxt-arcade/blob/master/libs/device/dungeon/purple.png, I had to list out names for each frame in the json file or else it would add 3 empty images into the gallery, and in https://github.com/microsoft/pxt-arcade/blob/master/libs/device/builtin/villager4.png I had to smush one frame from the last animation into the previous line (and also list out frame names again)

buildsprites: ignore empty sprites

---

pxtlib/package.ts

We should normalize the languages as they are case sensitive in package _locale folder.
Only fall back to baselang if the full lang is not available

Fixing language code for packages

---

cli/cli.ts
localtypings/pxtarget.d.ts
pxtlib/main.ts
webapp/src/app.tsx
webapp/src/compiler.ts

Includes:
#6163 
#6174 
#6178 
#6179 
#6195 
#6200 
#6208

Cherry pick api cache to stable 5.26

---

webapp/src/workspace.ts

When an existing github project is imported, it might contain markdown files (.md) but no typescript file. We want to make sure that the project has at least 1 ts file.

Try to fix imported project with no TS files

---

theme/common.less
theme/github.less
webapp/src/editortoolbar.tsx
webapp/src/githubbutton.tsx
webapp/src/gitjson.tsx

Display github button in table + collapsed

---

theme/home.less

Tighter placement of galleries on mobile (vs tablet) by reducing margin to 20px in mobile.

better placement of galleries on mobile

---

theme/common.less
webapp/src/app.tsx

The editor toolbar is visible in table/mobile for editor that hide it (console, github)
This fixes the issue.

don't show bottom editor toolbar for editor that don't need it

---

cli/cli.ts

And they are back!!!
Fix for https://github.com/microsoft/pxt-arcade/issues/1462

missing draggable blocks fix

---

webapp/src/compiler.ts

Fixing localization of cached API info

---

cli/server.ts
pxtlib/github.ts
pxtlib/initprj.ts
webapp/src/app.tsx
webapp/src/workspace.ts

When MakeCode tries to import an existing repository, it scan the existing files for pxt.json. 
If pxt.json is missing, it will ask the user if the project can be initialized. This happens when user creates repo with README.md for example.

Ask use to prepare repo when importing non-empty repo

---

localtypings/pxtpackage.d.ts
webapp/src/snippetBuilderInputHandler.tsx

Leave text alone, properly escape var name.

adding "variableName" option in snippet builder

---

pxtlib/package.ts
webapp/src/package.ts

Fix for https://github.com/microsoft/pxt/issues/6193
With this change, we mark as invalid a workspace dependency that got deleted. The user can fix it in the explorer view.

don't crash when a reference project is missing

---

cli/cli.ts
cli/crowdin.ts
localtypings/pxtarget.d.ts
pxtlib/crowdin.ts

Instead of always uploading, a "uploadDocs: true" has to be present in pxtarget.json as well. This allows to selectively enable branches to upload to crowdin.

inclusive build flag to upload docs

---

theme/highcontrast.less
theme/tutorial.less

fix https://github.com/microsoft/pxt-arcade/issues/1470
(also makes the faded next button show up as white instead of black)

fix tutorial colors in high contrast mode

---

Jakefile.js
cli/cli.ts
cli/nodeutil.ts
webapp/src/compiler.ts

Includes the following changes:
1. Remove the redundant JRES from the cached API info; this shrinks `target.js` in minecraft back to its pre-api-cache size
1. Minify ALL production JavaScript instead of just `main.js` (speeds up load by about ~5 seconds in Chrome with fast 3g network throttling)
1. Stop pretty printing built target files for no reason in production builds

More minification (API Info and JavaScript)

---

theme/common.less
webapp/src/core.ts
webapp/src/githubprovider.tsx
webapp/src/gitjson.tsx

Confirm that the user wants to sign in with github before redirecting to the oauth page. Unifies sign in dialog for token/oauth scenarios.

GitHub Oauth confirmation dialog

---

webapp/src/githubprovider.tsx

Fix crash when inputing dev token in github dialog.

query input element after dialog

---

docfiles/pxtweb/cookieCompliance.ts
pxtlib/analytics.ts
pxtlib/main.ts
pxtlib/workeriface.ts
pxtsim/simdriver.ts
webapp/src/app.tsx
webapp/src/blocks.tsx
webapp/src/compiler.ts
webapp/src/core.ts
webapp/src/simulator.ts
webapp/src/workspace.ts

Record & report (to the console for now) key performance metrics including:
- how long it took to reach certain milestones (from browser nav start; like: DOM loaded, tutorial load done, simulator ready, ...)
- the duration of certain long functions like: loadBlockly, createProjectAsync, refreshToolbox
The point of this isn't for us as developers to analyze performance (use Chrome devtools for that), it's to have something easy that users can send us from wherever they are (e.g. China schools) so we can see what they're experiencing (instead of just "it loads really slow").
Here's an example report (Macbook w/ 6x CPU throttle):
```
performance report:
first JS running @ 941ms
DOM loaded @ 3s203ms
workspace init finished @ 3s738ms
loading started #tutorial @ 4s905ms
loading done …
```

Record & console log performance metrics

---

Jakefile.js
cli/cli.ts
webapp/src/compiler.ts

Porting over the code minification and JRES de-duplication to stable 5.26. This is not a cherry pick because we didn't want to take the compress API info change.

Porting over minify and jres fixes to stable

---

cli/cli.ts

So that StaticPkg can have the benefit introduced in #6244 automatically, unless `PXT_ENV` is already set.

Set PXT_ENV to production when minify is set in StaticPkg

---

webapp/src/gitjson.tsx
webapp/src/workspace.ts

Fix spacing on `no local changes` dialog
fix crash on importing repos with deps on other github repos in arcade/beta (happening consistently when trying to import jwunderl/pxt-kickoff which had a dep on jwunderl/pxt-color, for example, as there are no files in there when it first is run)

Minor github fixes

---

webapp/src/monaco.tsx

Python auto-indent after ":"

---

pxtcompiler/emitter/emitter.ts

Give proper error on super() when no parent ctor

---

webapp/src/projects.tsx

CDN must require ranges to serve mp4 in Safari.

disable mp4 on landing page for safari

---

cli/cli.ts
localtypings/pxtpackage.d.ts

Annotate packages as "partial" so that we ignore build errors in the CLI. Allows to remove spurious warnings for "base"-like packages.
+ fix a bug in api shrinking.

Partial projects

---

cli/cli.ts
localtypings/pxtpackage.d.ts
webapp/src/projects.tsx

Introduce separate fields to hold potential .mp4 file location. Since the file location are expanded into blob location, file name extension mangling does not work to switch between .gif or .mp4s.
.mp4 are a much better alternative to .gif (heavy); unfortunately, Safari requires ranges which are not supported by the CDN / Electron does not ship a decoder. Hence the need to support both formats.

Video URL in cards

---

cli/cli.ts
localtypings/pxtarget.d.ts
pxtcompiler/emitter/driver.ts
pxtcompiler/emitter/emitter.ts

Example extension, tsconfig.json and foobar.ts in compiler/ folder in a target.
```json
{
"compilerOptions": {
"target": "es5",
"noImplicitAny": true,
"noImplicitReturns": true,
"noImplicitThis": true,
"declaration": true,
"out": "../built/compiler.js",
"newLine": "LF",
"sourceMap": false
}
}
```
```typescript
/// <reference path="../node_modules/pxt-core/built/pxtcompiler.d.ts"/>
namespace ts.pxtc.extension {
pxtc.compilerHooks.preBinary = (program: Program, opts: CompileOptions, res: CompileResult) => {
pxt.log("pre binary")
}
pxtc.compilerHooks.postBinary = (program: Program, opts: CompileOptions, res: CompileResult) => {
pxt.log("post binary")
}
}
```

Add compiler hooks common to CLI, cloud and web

---

webapp/src/projects.tsx

Following the fix for .mp4 in CDN, it works in Safari.

reenable .mp4 in safari

---

webapp/src/app.tsx
webapp/src/cloudsync.ts
webapp/src/container.tsx
webapp/src/githubprovider.tsx
webapp/src/gitjson.tsx
webapp/src/onedrive.ts
webapp/src/projects.tsx

Scenario: GitHub button -> create repo -> OAuth sign in -> reload script -> create repository -> success

Support routing back to create repository from oauth flow

---

localtypings/pxtarget.d.ts
pxteditor/experiments.ts
webapp/src/monaco.tsx

Puts the toolbox behind an experiment flag. 
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1476

disable Python toolbox but add an experiment to re-enable

---

webapp/src/app.tsx

Fixes: https://github.com/microsoft/pxt-minecraft/issues/1472
When switching to Python, we were assuming that main.py always existed. This was causing crashes.

Fix assumption that main.py always exists when switching to python

---

pxtcompiler/emitter/service.ts

Fixes: https://github.com/microsoft/pxt-minecraft/issues/1481
Also adds a TODO about future TS support

Fix syntaxinfo so it doesnt crash on non-python projects

---

cli/cli.ts
pxtpy/converter.ts

- Rename "pycheck" to "pyStrictSyntaxCheck" in "pxt checkdocs" CLI command because we DO check python without that flag, we just don't do the full-blown round-trip syntax comparison (which is very brittle)
- Change a throw that's better done as an assert

Small python-related cleanup: var rename & throw->assert

---

pxtcompiler/emitter/backbase.ts
tests/compile-test/lang-test0/29lazyreferences.ts

fixes https://github.com/microsoft/pxt-arcade/issues/1519

Don't clobber r1 register in clearStack()

---

pxteditor/monaco-fields/field_react.ts
pxteditor/monaco-fields/field_sprite.ts

As the name suggests, I refactored the interface for the react field editors in the tilemap pr but forgot to do this one.
Fixes https://github.com/microsoft/pxt-arcade/issues/1523

Fixing monaco sprite editor after tile map refactor

---

pxtpy/pydecompiler.ts

"emitBody" already indents the statement so the "indent1" was unnecessary in emitWhileStmt.
While loop was the only case of this I found.
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1471

Fix double indent on python while loop decompile

---

pxtblocks/blocklycustomeditor.ts
pxtblocks/fields/field_tilemap.ts
pxtblocks/fields/field_tileset.ts
pxtblocks/fields/field_utils.ts
pxtlib/spriteutils.ts
webapp/src/components/ImageEditor/ImageEditor.tsx
webapp/src/components/ImageEditor/actions/dispatch.ts
webapp/src/components/ImageEditor/store/imageReducer.ts
webapp/src/components/ImageEditor/tilemap/TilePalette.tsx

This is the field editor for referencing tiles; it's based on the image dropdown and contains all tiles that are referenced in your current project.
In order to prevent students from breaking their own code, you can't delete any tile from your tilemap that is referenced by one of these field editors. Right now it just silently refuses to do it; I'll be adding an actual warning message in a different PR.

Tileset field editor

---

webapp/src/app.tsx

Just ignore the request to restart (because we change the current editor) when opening the console view.
Fix for https://github.com/microsoft/pxt-arcade/issues/1509

don't restart when opening console editor

---

webapp/src/data.ts
webapp/src/githubbutton.tsx
webapp/src/gitjson.tsx
webapp/src/package.ts

Pull status as cached data

---

cli/server.ts
pxtlib/emitter/cloud.ts
pxtlib/gallery.ts
pxtrunner/runner.ts
pxtsim/embed.ts
webapp/src/app.tsx

Consistently use userLanguage() and localeLive to pick up the correct locale in the editor.
Fix for https://github.com/microsoft/pxt-arcade/issues/1507

clean up language options settings

---

pxtlib/service.ts

Make sure {id:...} are gone from translations. Fix for https://github.com/microsoft/pxt-arcade/issues/1458
Duplicate PR of https://github.com/microsoft/pxt/pull/6303

cleanup locs identifier

---

pxtblocks/blocklycompiler.ts

It turns out that we treat disabled blocks as events and sort them in the compiler. To create a call key for the block we compile each variable which blows up because the context has not been set.
> This change modifies the blocky compiler to sort events **after** disabled blocks have been filtered out. The only impact I can see here is that the decision to disable a bloc is now dependent on their positions rather than their naming -- **which might be a breaking change**.
Fixed. It uses the previous sorting.
@riknoll @abchatra careful review here
Fix for https://github.com/microsoft/pxt-arcade/issues/1485

Fix compilation with disabled blocks

---

theme/image-editor/imageEditor.less
webapp/src/components/ImageEditor/ImageCanvas.tsx
webapp/src/components/ImageEditor/ImageEditor.tsx
webapp/src/components/ImageEditor/tilemap/Minimap.tsx

Fixing the tilemap editor in Edge. This fixes three bugs:
1. The minmap was very blurry
2. The tilemap canvas was drawing the tiles at native resolution while scaling the canvas size so the tiles were too small to actually see
3. The tile editor (for creating new tiles, not the field editor) was not rendering correctly when overlaying the tilemap editor

Fixing tile editor and blurriness in Microsoft Edge

---

localtypings/pxtarget.d.ts
pxtcompiler/emitter/hexfile.ts
pxtlib/main.ts

This is useful when you want to compile something and place it directly on the SD card, or when you want to scp it to a Linux box (eg Pocket Beagle)

Allow for ?compile=rawELF to skip UF2 on RPi

---

webapp/src/blocks.tsx

Fix for https://github.com/microsoft/pxt-arcade/issues/1481. This impacts **all** blockly prompts: new variable, etc...

use close icon instead of cancel

---

pxtlib/github.ts
theme/github.less
webapp/src/app.tsx
webapp/src/githubbutton.tsx
webapp/src/gitjson.tsx
webapp/src/workspace.ts

Just mention that we can't find it.
Only branch from master
Add buttons in error messages
Clear git pr/pull status on visibilitychange (coming back from the github tab)

Wording on missing branch

---

theme/common.less

Arcade logo wasn't rendering because its height was 0 for unclear reasons. This fixes that. There will still be a max-height of 1.6rem enforced by CSS.
Part of: https://github.com/microsoft/pxt-arcade/issues/1500

Fix arcade logo on Chrome by ensure it has a height

---

theme/image-editor/imageEditor.less

Fixes: https://github.com/microsoft/pxt-arcade/issues/1480
Gallery items are limited to 120px wide.
There will always be a minimum of 5 rows/columns, but as screen space allows the number of columns will grow endlessly.
Example after this fix:

Add max size to gallery items and allow more columns on large screens

---

package.json

Fixes https://github.com/microsoft/pxt-arcade/issues/1482

Bump pxt-blockly to 2.1.13

---

webapp/src/monaco.tsx

Fixes https://github.com/microsoft/pxt-arcade/issues/1572

Fixing blocklyFieldView size in monaco

---

pxtblocks/fields/field_tileset.ts

Half of the fix for https://github.com/microsoft/pxt-arcade/issues/1575 (the other half is https://github.com/microsoft/pxt-common-packages/pull/1039)
Three things:
1. Tileset editor preview is now smaller (32x32 instead of 50x50)
2. Transparency now has a checkerboard image (see below)
3. Transparency now always compiles to `myTiles.tile0` instead of `null`

Fix transparency in tileset editor and give it a preview

---

theme/fieldeditors.less

Fixes: https://github.com/microsoft/pxt-arcade/issues/1490
Old:
New:
New simulator:

Change position picker theme to reflect new simulator

---

webapp/src/serial.tsx

Need someone with a Windows 8 machine to test this.
https://github.com/microsoft/pxt-arcade/issues/1241
Test: make sure the exported console text opens in notepad / windows 8.
```
forever(function () {
console.logValue("x", 0)
})
```

Use \r\n new lines on Windows < 10

---

webapp/src/container.tsx
webapp/src/projects.tsx

In Project
In Home
Rationale: 
All project\hardware related at the top
Global editor settings next 
Meta at the bottom (Reset is meta in the sense - reset everything about this editor including settings)

Rearranging items in the menu

---

common-docs/javascript/interfaces.md

Name to example mismatch. Found by a Crowdin translator.
RE: https://crowdin.com/translate/kindscript/1390/en-tr#55145

Match interface name to example in "Interface" page

---

theme/image-editor/imageEditor.less
theme/image-editor/sideBar.less

Fixes https://github.com/microsoft/pxt-arcade/issues/1552

Add border to selected image editor button, larger green done button

---

webapp/src/components/ImageEditor/ImageEditor.tsx
webapp/src/components/ImageEditor/store/imageReducer.ts

Fixes: https://github.com/microsoft/pxt-arcade/issues/1562

fix animation editor crash when opening right after tilemap edit

---

theme/common.less
theme/image-editor/imageEditor.less
webapp/src/editortoolbar.tsx
webapp/src/projects.tsx

Fix:
- Hardware menu "Download to device"
- D5, F4, Pi0 options in hardware menu
- Shorten strings for mobile HW dropdown to reduce overlap (partial fix)
- CSS for tilemap done button hover, download button "loading"
Fixes https://github.com/microsoft/pxt-arcade/issues/1587
Fixes https://github.com/microsoft/pxt-arcade/issues/1589

Fixes for hardware menu, select D5/F4/Pi0, CSS

---

cli/crowdin.ts

Don't crash when credentials are undefined (needs to return a promise)
fix crash on `pxt staticpkg --locs` when you haven't stored a crowdin key, which is part of the electron build

don't crash when crowdin credentials are undefined

---

webapp/src/components/ImageEditor/ImageCanvas.tsx

I'm not sure if this was introduced by my cursor PR or something else, but this fixes an exception in the image canvas that I just noticed while testing.
The bug repros if you create a tilemap in a project with no tiles and click on the canvas.

Fixing draw cursor bug
