microsoft/pxt

pxtcompiler/emitter/service.ts, tests/decompile-test/baselines/draggable_parameters_reporters.blocks
Fixes https://github.com/microsoft/pxt-arcade/issues/1566
=> Use qualified name for handler argument types

webapp/src/components/ImageFieldEditor.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1605
=> Sprite editor defaults to 16x16 if either dimension is zero

pxtsim/runtime.ts, tests/compile-test/lang-test0/35lambdaparameters.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1617
For release
=> Clear last argument after shifting lambda parameters

webapp/src/components/ImageEditor/tilemap/TilePalette.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1628
Fixes placement of create new tile '+' icon on pages 2+
=> Bump index of first selected tilemap color, fix my tiles '+'

cli/cli.ts
currently failing like this: https://travis-ci.org/microsoft/pxt-arcade/builds/627920185#L515 when a tutorial a) uses an extension and b) has a tilemap
=> include packages when compiling tutorial steps in checkdocs

cli/cli.ts
checkdocs fix for arcade release
=> [stable5.30] include packages when compiling tutorial steps in checkdocs (#6393)

pxtcompiler/emitter/hexfile.ts
This just does the patching up to 4 times per hex line.
This bug only triggers with particular binary layouts, essentially due to "randomness" in object binary layout
=> Fix patching of @PXT@ in hex files

pxtcompiler/emitter/emitter.ts, tests/compile-test/lang-test0/02numbers.ts, tests/compile-test/lang-test0/18enums.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/774
=> Allow for unary operators on any type, including enums

pxtcompiler/emitter/emitter.ts, tests/compile-test/lang-test0/27accessors.ts, tests/errors-test/cases/classes.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/491
This emits a proper error when there's a setter without getter (there are vtable layout issues with this one and it's a corner case).
It also allows getter and setter to come in any order.
=> Allow set to come before get

localtypings/pxtarget.d.ts, pxteditor/editor.ts, theme/keymap.less, theme/pxt.less, webapp/src/app.tsx, webapp/src/keymap.tsx, webapp/src/simtoolbar.tsx
Adds keymap button to simulator toolbar if "keymap" is set to true in pxtarget.
https://arcade.makecode.com/app/132d1e744bf5722d9f36607e688f0dbadeda3518-3ad4bed648
=> Keymap button in simulator toolbar on wide monitors/full screen

pxtrunner/runner.ts
This speeds up the load time of docs pages with a lot of snippets. I used this page for testing: https://arcade.makecode.com/concepts/star-field
On my local machine it took ~6 seconds to fire the onLoad event before my changes and ~3.7 seconds after my changes.
We could improve this even more by using the same API info that the editor stores in the indexed db, but I didn't think it was worth duplicating all of that code in the embed frame. I might try to refactor it out later.
=> Don't rebuild the API info for each snippet in docs

cli/cli.ts
`TF_BUILD` environment variable from https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
=> Return Travis info for Azure pipelines (Minecraft) build as well

cli/cli.ts, docs/writing-docs/tutorials.md, localtypings/pxtarget.d.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, webapp/src/projects.tsx
See also: https://github.com/microsoft/pxt-minecraft/pull/1518
Part of: https://github.com/microsoft/pxt-minecraft/issues/1461
This is needed to unblock writing Python content.
TODO:
Enables the ```python tag for writting Python-specific tutorials.
We only show the "Python" carousel if the Python experiment is enabled.
Without experiment:
With experiment:
This lets us iterate on Python content work without impacting our users.
=> enable ```python code directive and clarify how highlighting & decompilation works

localtypings/pxtarget.d.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/service.ts, pxtpy/converter.ts, webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1479
- In SyntaxInfo, keep a seperate list of global symbols for all types of requests so that we can ensure uniqueness for member completion or identifier completion
- Update py2ts to return these
- Update getCompletions and getSnippet to account for existing symbols
- remove dead code, improve comments, rename a few variables
=> Ensure names generated by auto-complete are unique

pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/adv_operators.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1031
=> support advanced python operators & throw error instead of returning comment

common-docs/blocks-embed.md, docs/blocks-embed.md, pxtlib/github.ts, pxtlib/initprj.ts, theme/home.less, webapp/src/dialogs.tsx, webapp/src/workspace.ts
GitHub pages allow to have blocks rendered on the repository homage in a user friendly way.
=> Enable GitHub pages on github project

pxtrunner/renderer.ts, pxtrunner/runner.ts
fix snippet edit button -- fixes https://github.com/microsoft/pxt-arcade/issues/1667, and I'm pretty sure I remember there being at least one other issue for this but I can't find it right away.
Looks the ``decompileResult`` is getting mutated / reused for each snippet (https://github.com/microsoft/pxt/blob/master/pxtrunner/runner.ts#L150), so it was always just picking an arbitrary snippet from the page / the last one that gets compiled. I think it would be preferable to avoid doing this, but I haven't taken a look at how large of a task that would be / if it's worth doing at the moment.
=> fix snippet edit button loading correct project

pxtpy/parser.ts
fix https://github.com/microsoft/pxt-minecraft/issues/1325
Show errors in the correct spots for indentation errors (e.g. on the start of the line that should be indented / unindented, not on the preceding `<nl>`), and don't output spurious errors that stem from the original errors
current:
after this:
=> fix python indent errors

pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/for_of_loop.ts
Extends ExpRes to have an array of expressions, breaks up long array literals and function calls.
Fixes https://github.com/microsoft/pxt-minecraft/issues/915
Fixes https://github.com/microsoft/pxt-minecraft/issues/1523
=>  Line breaks in long lists and function calls for Python

docs/targets/pxtarget.md, pxtlib/initprj.ts
Allows target to redefine built-in template files (to be used by arcade to provide full screen simulator support in github pages web site)
=> Custom template files

docs/defining-blocks.md, localtypings/pxtarget.d.ts, pxtblocks/blocklycompiler.ts, pxtcompiler/emitter/annotate.ts, pxtcompiler/emitter/decompiler.ts, tests/blocklycompiler-test/baselines/enum_constants.ts, tests/blocklycompiler-test/cases/enum_constants.blocks, tests/blocklycompiler-test/test-library/enums.ts, tests/blocklycompiler-test/test.spec.ts, tests/decompile-test/baselines/enum_constants.blocks, tests/decompile-test/cases/enum_constants.ts, tests/decompile-test/cases/testBlocks/constantShim.ts
This is adding a feature to have some enums compile to constants when the `emitAsConstant` attribute is set. To use this feature:
On the enum, set `emitAsConstant` to true:
```typescript
//% emitAsConstant
enum Item {
//% block="Iron"
Iron = 1
}
```
and then declare a constant for that enum member like so:
```typescript
//% enumIdentity="Item.Iron"
const IRON = Item.Iron;
```
If the enum has a shim function, you can also set `blockIdentity` just like you can for enum members:
```typescript
//% emitAsConstant
enum Item {
//% block="Iron" blockIdentity="blocks.item"
Iron = 1
}
namespace blocks {
//% shim=TD_ID
//% blockId=minecraftItem 
//% block="item %item"
function item(item: Item): number;
}
//% enumIdentity="Item.Iron" blockIdentity="blocks.item"
const IRON = Item.Iron;
```
and the …
=> Adding emitAsConstant for emitting enums as constants

docs/language.md
Lists out supported, partially supported, unstable support, and not supported python language features.
@mmoskal , can you sanity check what I wrote below? I was a little conservative (I think) and listed somethings that might work well as unstable or partially supported. In general I'd like to be conservative to reduce what we have to test thoroughly for this release.
=> list supported & unsupported python features

pxtrunner/renderer.ts, pxtrunner/runner.ts
cherry pick #6410 for arcade; make edit button load right snippet from page, and open in correct editor (typically blocks)
=> [stable5.30] fix snippet edit button loading correct project 

pxtblocks/fields/field_sprite.ts, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/ImageFieldEditor.tsx
So that you can have a fixed width and height for an API. I already added this functionality for the tilemap editor and am just surfacing it now.
=> Adding a field option to disable resizing of sprite editor

pxtcompiler/emitter/service.ts
Every instance of the snakify function in pxt calls `toLowerCase()` on the result (except on enum members which are always uppercase). This PR moves that `toLowerCase()` call into the snakify function and tweaks the result so that if a name is in all uppercase we preserve it.
Constants in python should be all caps according to [PEP 8](https://www.python.org/dev/peps/pep-0008/#constants)
=> Preserve constant names when transitioning to python

pxtrunner/runner.ts, theme/docs.less, theme/sidedoc.less, webapp/public/docs.html, webapp/public/highlight.js/styles/vs2015.css, webapp/src/app.tsx
Some fixes for https://github.com/microsoft/pxt-minecraft/issues/1521
Sidedocs take up 50% of the screen in text (py/js), unchanged in blocks
=> Larger sidedocs in Monaco, shrink font & no wrap for python

pxtpy/converter.ts, pxtpy/pydecompiler.ts, tests/pyconverter-test/baselines/function_parameters.ts, tests/pyconverter-test/cases/function_parameters.py
In our TS, type annotations are required. This fixes two bugs where they were not being emitted when going from python to TS
1. Type annotations for builtin types (e.g. number) were ignored
1. If we couldn't infer a type for a parameter, we didn't emit any annotation. Now we emit `any`
Because of the second change, I also did a fix to make sure that a parameter declaration with the type `any` is omitted when going from TS to python. Previously it compiled to something like this:
```python
def on_chat5(num: (TODO: Unknown TypeNode kind: 1234)):
pass
```
=> Always emit type annotations for parameter declaration

pxtlib/blocks.ts
Fix for https://github.com/microsoft/pxt-arcade/issues/1691
=> don't lower case block names

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/always_decompile_renames_expressions.blocks, tests/decompile-test/baselines/always_for_loop_bad_conditional.blocks, tests/decompile-test/baselines/always_for_loop_bad_incrementor.blocks, tests/decompile-test/baselines/always_for_loop_bad_initializer.blocks, tests/decompile-test/baselines/always_null_and_undefined.blocks, tests/decompile-test/baselines/always_unsupported_operators.blocks, tests/decompile-test/baselines/name_collision_1.blocks, tests/decompile-test/baselines/name_collision_4.blocks, tests/decompile-test/baselines/name_collision_6.blocks, tests/decompile-test/baselines/name_collision_7.blocks, tests/decompile-test/baselines/name_collision_8.blocks
We do a lot of variable renaming when going from TS to blocks to avoid variable names clashing when they become globals. Part of our renaming algorithm is to switch single letter variables names to the next available single letter. That was to make decompiling for-loops better because it's common to have several variables named `i` throughout the project.
This seemed like a good idea at the time, but I realize now that some single-letter variable names have specific meanings in our targets, like x, y, and z. Are there any others that folks can think of? Should we cut this feature entirely?
=> Don't rename x, y, and z when decompiling

docfiles/style.css, pxtlib/commonutil.ts, theme/common.less, webapp/src/container.tsx, webapp/src/workspace.ts
- Hide simulator if "headless" in sandbox mode
- Inverted CSS for share page footer (Minecraft theme)
- Fix toggle CSS
- Set editor language preference (js/py) based on imported project editor state (jsprj/pyprj)
=> Hide simulator on headless share page, CSS tweaks

pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtblocks/fields/field_tsexpression.ts, webapp/src/blocks.tsx
If Python is set as your editor language preference, don't render TypeScript code in gray blocks. Instead, we render `<python code>` for statements and `<python expression>` for expressions. This is more of a placeholder until we have time to do something more comparable to TS.
Here is a GIF that loops perfectly:
=> Python gray blocks

pxtblocks/blocklycompiler.ts
I was using the `emitAsConstant` feature I added a few weeks back and noticed that it wasn't working for any event blocks. Turns out, in the BlocklyCompiler we had two functions for compiling function arguments (`compileArg` and `compileArgument`) and it looks like we've only been porting features to one of them. I'm deleting the event-specific one.
=> Make compileEvent use the same logic as compileStdCall in blocks

theme/common.less, webapp/src/container.tsx
fix https://github.com/microsoft/pxt-minecraft/issues/1430; fix spacing issue when multiple doc items are there, handle outside links correctly, and show all of the snippets
Just noticed you guys said to just drop it instead so if you actively don't want it I can remove the ``renderDocItems(this.props.parent, "ui mobile only inherit", docItems)}`` from settings menu, but it all works now so ¯\\_(ツ)_/¯
=> Fix docs in menu

localtypings/pxtarget.d.ts, pxtcompiler/emitter/service.ts
Introduces a generic "alias" annotation; emit FORWARD instead of SixDirection.Forward
Before:
After:
=> don't put member of emit as constant

pxtpy/ast.ts, pxtpy/converter.ts, tests/pyconverter-test/baselines/for_hoisting.ts, tests/pyconverter-test/cases/for_hoisting.py
fixes https://github.com/microsoft/pxt-minecraft/issues/1557
Loop variables in python are function scope (like all other variables). With this PR we scope them to the for loop if they are only ever used inside that for loop.
=> Hoist for variables when required

pxtlib/browserutils.ts
Fixes issue where setting lang in a nested docs page (/courses/csintro) would set a cookie with path `/courses` that would not be respected in the homepage/editor
=> Set path of language cookie to prevent multiple cookie from docs

pxtblocks/blocklyloader.ts
currently, adding a default value for https://github.com/microsoft/pxt-common-packages/blob/master/libs/base/console.ts#L57 (or in my case making ``player.say`` allow `any` in minecraft) will just get dropped and show up as the empty string, because it doesn't convert the field name from 'text' to 'TEXT' and the value is silently ignored.
This is annoying when using it to give a default for `any` or complex types (e.g. union types involving strings), for example adding an ``e.g.`` default for https://github.com/microsoft/pxt-common-packages/blob/master/libs/base/console.ts#L57 (or in my case making ``player.say`` allow `any` in minecraft) doesn't work currently.
=> handle defaults with param.shadow=text

theme/tutorial.less
Handle long text in flyoutOnly headers, for https://github.com/microsoft/pxt-minecraft/issues/1453
=> Ellipsis truncation for toolbox header in flyoutOnly mode

pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, tests/blocklycompiler-test/baselines/for_each_string.ts, tests/blocklycompiler-test/cases/for_each_string.blocks, tests/blocklycompiler-test/test.spec.ts, tests/decompile-test/baselines/array_for_of_string.blocks, tests/decompile-test/cases/array_for_of_string.ts
fix https://github.com/microsoft/pxt-minecraft/issues/1553 by allowing strings in for each statements, so
```typescript
for (let i of "hello") {
console.log(i)
}
```
goes to
(and you can make that in blocks too, of course)
The issue itself is really minor (as far as I can tell, it's been there since arrays in blocks were first implemented and no one's noticed), and this does touch the array type inference code in blocklycompiler to fix two issues that came up due to the change, so it doesn't seem like a thing to rush to get in / probably better to let in bake in a /beta for a bit? Mainly just did this while thinking about how to structure things in an unrelated change
changes in blocklycompiler:
* in some cases ``getConcreteType`` would emit the type minus the last two letters if it …
=> Fix decompilation of `for ( ... of "abc")`

pxtpy/converter.ts, tests/runtime-trace-tests/cases/for_of_loop.ts
support string iteration with `for i of "abc"` in python; fixes https://github.com/microsoft/pxt-minecraft/issues/1499
```python
for letter in 'abcdef':
print(letter)
```
converts to 
```typescript
for (let letter of "abcdef") {
console.log(letter)
}
```
(and back, of course)
just noticed that that typescript does actually fail to decompile to blocks at the moment, will file an issue for that
sidenote: I did get confused why nothing was changing when I was changing the stmtmap, and it took a few to realize that I was changing the one in cli/pyconv and not pxtpy/converter; is that used for anything at this point?
=> support py `for i in "abc"`

webapp/src/app.tsx, webapp/src/githubprovider.tsx, webapp/src/workspace.ts
Support for GitHub classroom routing:
``#github:owner/repo`` imports the repo into MakeCode, **requires sign in**.
``#github:create-repository:headerid`` exports a project into GitHub repo
=> Github route

pxtrunner/renderer.ts
In docs, when clicking on "python" button, need to scroll the text into view.
=> scroll python/js snip into view

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtlib/tutorial.ts, theme/code.less, theme/pxt.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/marked.tsx, webapp/src/projects.tsx, webapp/src/tutorial.tsx
=> Support for python/ts step-by-step tutorials

pxtpy/pydecompiler.ts
We use many "invisible" helper function, marked as "shim=TD_ID" that should not be emitted when doing JS->Py.
=> don't emit function marked as TD_ID

pxtpy/pydecompiler.ts, pxtrunner/renderer.ts, tests/decompile-test/baselines/alias.blocks, tests/decompile-test/cases/alias.ts, tests/decompile-test/cases/testBlocks/basic.ts, tests/pydecompile-test/baselines/alias.py
Use "alias" info, e.g. short name if possible when decompiling -- otherwise we end up with ugly code if we come from TS/blocks.
Note: the py decompilation looks trashed.
=> Use alias when avaiable in py decompiler

pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/while_loop.ts
Accidental regression from: https://github.com/microsoft/pxt/pull/6426/files
I checked for other regressions but didn't see any. Might be worth another look @shakao
=> Fix while loops py decompile (missing colon regression)

docs/writing-docs/tutorials.md, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/monacoSnippets.ts, webapp/src/projects.tsx
Support for loading tutorials in typescript or python. The approach is simple: if the preferred editor is speficied, regex/replace "```spy" into "```typescript" and vice-versa; then push through tutorial engine.
Allows to use same markdown in python or javascript.
Note: Direct python tutorials not supported for this feature.
=> Dual tutorials

docs/writing-docs/tutorials.md, pxtlib/gallery.ts
Short hand to auto-populate otherActions: empty array means populate otherActions as best as can.
Allows to avoid copy-pasting tons of markdown and URL path errors.
This currently applies to tutorials only but next step will be support for auto multi-editor examples. See https://github.com/microsoft/pxt-maker/pull/276
=> auto-populate other actions

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
noticed we didn't have string.replace in https://github.com/microsoft/pxt-common-packages/pull/1062
`string.prototype.replaceAll` isn't technically part of es yet, but it's stage 3: https://github.com/tc39/proposal-string-replaceall . It's extremely useful for us, though, as we can't use regexes to make string.replace useful for many of the cases you want to use it (as it only replaces the first instance of the input str, unless the input value to replace is a regex with the 'g' flag) -- from the discussions linked on the repo it looks like the main reason it wasn't advanced to stage 4 / accepted was a disagreement on the expected behavior when it was passed a regex without the 'g' flag, and that's been decided on the repo
I ran into a TON of issues with file caching on this PR, seems …
=> add string.replace and string.replaceAll

theme/highcontrast.less, theme/home.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/views/card.overrides
Fixes:
- High contrast details banner
- Dark theme details banner
- Preview card should not overlap details banner (Chrome on Mac)
- Green action button sizing for shorter text
high contrast:
dark theme:
Fixes https://github.com/microsoft/pxt-minecraft/issues/1607
Fixes https://github.com/microsoft/pxt-minecraft/issues/1620
Fixes https://github.com/microsoft/pxt-minecraft/issues/1619
Fixes https://github.com/microsoft/pxt-arcade/issues/1712
=> CSS updates for details view cards

theme/tutorial.less, webapp/src/tutorial.tsx
- Keep tutorial hint in DOM
- Shift "see more" button to right for text-based tutorials
Fixes https://github.com/microsoft/pxt-minecraft/issues/1648
=> Tutorial CSS and modal fixes

pxtlib/gallery.ts, webapp/src/app.tsx
Ability to load an example in Blocks/TS/Python from the same markdown.
=> Support for multi-language examples

webapp/src/gitjson.tsx, webapp/src/workspace.ts
To avoid the first empty commit, add block ids as we are exporting to github.
=> add block ids before exporting to github

localtypings/pxtarget.d.ts, webapp/src/projects.tsx
Reenable rendering background videos/large image on details page + flag to disable this behavior. Note that the "imageUrl" data is not used anymore so a user can decide to hide the video/image by simply not populating the largeImageUrl/videoUrl flags. IMO, this is a more flexible setting and allows content author to control the video inclusion behavior.
=> render video or large image if available

webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1671
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1667
=> indent snippets correctly and remove superfluous empty lines

docs/targets/pxtarget.md, docs/targets/theming.md, localtypings/pxtarget.d.ts, webapp/src/container.tsx, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx
=> display beta editor card

pxtlib/github.ts, webapp/src/compiler.ts
When compiling js for github page, encode repo name
=> encode repo into metadata

pxtblocks/blocklycompiler.ts, pxtcompiler/emitter/driver.ts, pxtcompiler/emitter/service.ts, pxtcompiler/emitter/transpile.ts, pxtlib/jsoutput.ts, pxtlib/service.ts, pxtpy/converter.ts, webapp/src/compiler.ts
Needed for correct error messages, future debugger support, and possibly better intellisense.
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1614
Related: https://github.com/microsoft/pxt-minecraft/issues/1673
TODO:
Now:
Whereas before we saw no error. (Note that the TurnDirection vs SixDirection confusion is still very confusing)
https://minecraft.makecode.com/app/c16ae7fa3eeabd09f4440341c0da58afc2f1a1e1-f4abc06a71
=> Track source mappings through PY->TS

webapp/src/projects.tsx, webapp/src/sui.tsx
when hiding the code options section, reset the language restriction; make it an escape hatch if you select the wrong option and randomly click to try to 'get out'
fixes https://github.com/microsoft/pxt-minecraft/issues/1689
(wow my gif tool made the colors awful there..)
=> lang restriction picker: reset state on hide

theme/tutorial.less
Adjusting to remove space between number label and progress circle
=> Small CSS cleanup for tutorial circle

pxtlib/github.ts, webapp/src/workspace.ts
The repo pages might have not been enabled, or the URL is missing. Check those conditions and reenable as needed, or put back the url in repo description.
=> Enable pages when creating a release if needed

pxtblocks/blocklydiff.ts, webapp/src/gitjson.tsx, webapp/src/marked.tsx
When we try to diff blocks that were roundtripped, use text-based diff instead since all ids have been trashed.
=> Handle diff of reconstructed blockly xml payloads

theme/github.less
Fix diff color scheme for inverted editors
=> fix for diff rendering in inverted mode

common-docs/blocks-embed.md, pxtrunner/runner.ts, webapp/public/rendertest.html
Detect that renderblocks is sending XML, and render as blockly xml payload instead of decompiling.
Required for microbit.org support.
@abchatra this will need to be integrated in the microbit branch and deployed.
=> support for rendering xml directly

pxtcompiler/emitter/driver.ts, pxtcompiler/emitter/service.ts, pxtcompiler/emitter/transpile.ts, pxtlib/jsoutput.ts, pxtlib/service.ts, webapp/src/compiler.ts, webapp/src/monaco.tsx
Hopefully much better auto-complete for parameters of functions, especially enums.
Before:
After:
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1673
Also a lot of refactoring was done in this PR that is necessary for: https://github.com/microsoft/pxt-minecraft/issues/1699
but that issue is not yet solved. Needs another PR.
Additionally, a number of improvements were made to the TS<->PY source map infrastructure to make working with the source mapping much easier from many places.
This doesn't fix everything with auto-complete/intellisense. For example:
- Statement level auto-complete is still pretty bad (too many options, not what the user wants)
- No auto-complete for loops
- Expressions other than function args (or args that are themselves nested expressions) do not …
=> Better auto-complete for Python and refactor necessary for TS lang service change

theme/home.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/views/card.overrides, webapp/src/projects.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1627
Other icon changes (Github, board, etc) take precedence, otherwise display language.
=> Display language type in card icon on home screen

docs/extensions/pxt-json.md, pxtlib/package.ts
When authoring an extension, we need the testDepencies to load the appropriate project (e.g. "circui-playground" in adafruit). Those can be different in editor so ignoring testDependencies that can't be resolved.
=> multi-target support for testDepencies

docfiles/pxtweb/cookieCompliance.ts
We were getting errors in the backend where the locale was being passed the empty string so adding a default of "en"
=> Add default locale for cookie banner request

docs/translate.md
Add a FAQ section in the translate page to quickly answer common questions.
=> Add a FAQ section to translate page

README.md, cli/cli.ts, gulpfile.js
Adding a "gulp watch" task to the gulpfile and removing that functionality from `pxt serve`.
The new workflow for developing PXT is to run `gulp watch` in one terminal and `pxt serve` in another. Serve watches for changes to the target and gulp watches for changes to core. This has a number of improvements over the old way:
1. Incremental compilation! No more full rebuilds on changes!
2. Better file watching! No more rebuilds triggered by running `git status` in pxt!
3. Faster `pxt serve`! No more waiting for pxt to build when you only made changes in the target!
Note that `pxt serve` no longer builds pxt core *at all*, so make sure you run gulp before starting the server.
=> Adding gulp watch task

pxtcompiler/emitter/service.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1706
=> Fix auto-complete of certain global shortcuts like pos and world

pxtcompiler/emitter/service.ts
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1708
pt 2
=> Fix confusing method snippets by adding my_ prefix

webapp/src/container.tsx
Move language help out of pxtarget and into web app. I'll update to each target to remove these language items from the docsMenu
=> Always show appropriate language reference in help menu

webapp/src/blocks.tsx
Fixes: https://github.com/microsoft/pxt-minecraft/issues/1664
What happened was that before the default position of blocks seemed to be (10,10) and we were checking if a non-start block was in this default position. Now the default position seems to be (10,-6) so this code never triggered. Instead I'm now checking to see if multiple blocks have the exact same top-left position and if so, do a reflow.
=> Fix block reflow coming from text issue by checking for blocks being placed exactly on top of eachother

cli/cli.ts, pxtlib/main.ts
Display correct API names in Python toolbox (on_player_chat vs onPlayerChat)
Fixes https://github.com/microsoft/pxt-minecraft/issues/1657
=> Store pyQName in compressed API info if differing from qName

theme/common.less, theme/home.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/views/card.overrides, webapp/src/app.tsx
- Fix horizontal scroll for details view with three cards
- Fix homescreen gradient menubar height
- Fix card alignment on Safari
- Fix tutorial card overlapping workspace
- Purple icons
Fixes https://github.com/microsoft/pxt-minecraft/issues/1738
Fixes https://github.com/microsoft/pxt-minecraft/issues/1727
Fixes https://github.com/microsoft/pxt-minecraft/issues/1719
Fixes https://github.com/microsoft/pxt-minecraft/issues/1716
=> Home screen, tutorial UI fixes

webapp/src/monacoFlyout.tsx, webapp/src/toolboxeditor.tsx
\+ don't render group headers if all blocks are filtered out
Fixes https://github.com/microsoft/pxt-minecraft/issues/1728
=> Don't cache filtered snippet groups

webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1743
Safari in ios automatically convert single quotes and double quotes into their directional variants which makes typing strings impossible. This scans each edit for one of those quotes and converts them to their ASCII counterparts.
Tested in the iPad simulator
=> Replace those weird unicode quotes with normal ones in monaco

pxtblocks/blocklycompiler.ts, pxtblocks/blocklydiff.ts, webapp/src/blocks.tsx
the blocksdiff stuff is based off of char position, where many of the other ranges are based no line positions; fixes  breakpoints in debugger and error ranges in blocks.
fixes https://github.com/microsoft/pxt-minecraft/issues/1740, and also debugger that I just noticed was broken while fixing this:
=> split findblock to by line and by pos; fix error ranges, debugger

pxtlib/tutorial.ts
The text diffing was controlled by the blocks diffing flag.
=> enable auto-diffs on text tutorials

pxteditor/monaco.ts
Fixes:  https://github.com/microsoft/pxt-minecraft/issues/1721
For whatever reason I never quite got to the bottom of, Monaco computes the height and placement of the signature help incorrectly. This is a workaround that tells it to use a different algorithm that works a lot better.
=> Fix signature help overlapping the user  text

pxtlib/diff.ts, pxtrunner/renderer.ts, webapp/src/marked.tsx
re: https://github.com/microsoft/pxt-minecraft/issues/1744, the diffs renderer wasn't passing in `ignoreWhitespace`
see comment about seemingly minor diff algorithm change \\/
didn't look at the issue about it not rendering diffspy in the docs page, but it looks like that's just https://github.com/Microsoft/pxt/blob/master/pxtrunner/renderer.ts not having handling for  spydiffs  like /marked.tsx does?
=> tut / docs diffs ignore whitespace, show fileB content on no-diff

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, webapp/src/marked.tsx, webapp/src/tutorial.tsx
The content displayed in the tutorial changes sizes as it gets resized. This change notifies the tutorial engine to run the computation again when it is done.
Not the cleanest React way to do this, suggestions welcome.
=> MarkedContent update

theme/monaco.less, webapp/src/monaco.tsx, webapp/src/monacoFlyout.tsx, webapp/src/toolbox.tsx
- Fixes TouchEvent event listeners (when PointerEvents are not present)
- Fixes flyout scroll on iOS
- Fixes React warnings for toolbox
- Fixes small vertical scroll on page for inGame Monaco view
- Displays Python qName in expanded toolbox and dragged API snippet
https://minecraft.makecode.com/app/cf78239e71f67f95ce966e2060ab408ec83adf40-f94313c5bc
Fixes https://github.com/microsoft/pxt-minecraft/issues/1735
Fixes https://github.com/microsoft/pxt-minecraft/issues/1457
=> iOS/TouchEvent fixes for the Monaco flyout

pxtlib/github.ts, webapp/src/app.tsx, webapp/src/dialogs.tsx, webapp/src/projects.tsx
GraphQL query also returns pxt.json from reopes which allows to parse the supported target precisely. No more loading microbit repoes in arcade editor...
=> list user repoes using graphql

cli/cli.ts, localtypings/pxtarget.d.ts, pxtblocks/blocklycompiler.ts, webapp/src/compiler.ts
fix https://github.com/microsoft/pxt-minecraft/issues/1663 (variables conflicting with the new shorthand / alias constants in minecraft, like `LEFT`), as well as other variable conflicts (e.g. namespaces: `console`) that were broken due to the pkg being dropped from the cached api info.
=> handle variables matching top level constants, namespaces

webapp/src/monaco.tsx
It's very common to end a line with a comma in TypeScript, and the completion gets committed when you hit enter. Some common examples:
```typescript
let x = [
1,
2
];
someFunction(
"arg1",
"arg2"
);
let y = {
a: 0,
b: 1
}
enum Whatever {
A,
B,
}
let a = 0,
b = 1,
c = 2;
```
=> Dont show completions on commas

theme/monaco.less, webapp/src/monacoFlyout.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1758
Fixes https://github.com/microsoft/pxt-minecraft/issues/1759
Also fixes issue with drag handle overflow when it's scrolled out of the toolbox
=> Break long API calls, don't wrap dragged block

webapp/src/container.tsx, webapp/src/projects.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1765 as well as editor settings menu, in Minecraft case (no language menu option)
=> Only show menu divider if items above it are present

cli/cli.ts, pxtlib/package.ts, theme/diff.less, webapp/src/editortoolbar.tsx, webapp/src/projects.tsx, webapp/src/workspace.ts
Required to create a project called ".menu".
Don't enforce naming unless project starts with ``pxt-``, we assume it is an extension and we keep that name in sync with the repo. Otherwise, allow any names.
=> Allow renaming of project for github

pxtlib/diff.ts
=> Always show diffs between steps when auto-diffing; remove exception for if all lines change

pxtcompiler/emitter/decompiler.ts
=> Do not emit workspace comments that are empty

webapp/src/marked.tsx, webapp/src/tutorial.tsx
Hints only contain a single code snippets (they could have more but they shouldn't). We waste space by wrapping the snippet in a segment that adds padding. Don't wrap snippets when rendering tutorial hint.
before:
after:
=> unbox snippets when rendering in tip

theme/common.less
fix https://github.com/microsoft/pxt-minecraft/issues/1780
(I had the not headless selecting on the wrong element, but it didn't matter too much as the styling would have still been broken :))
add a rule for headless mode, and maintain the current rule for !headless mode
=> fix share page in one-language & headless mode

webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/srceditor.tsx, webapp/src/toolboxeditor.tsx
Attempt to extensively clear caches in the editors and compiler between header reload to avoid unexpected caching bugs (hard to find and repro). I probably missed caches that could be flushed. The goal is to make the editor more deterministic because there is a an entire space of bugs that requires loading/unloading various programs to be triggered.
=> Clear caches on header load

webapp/src/projects.tsx
add the selected language restriction to the tick for new projects. Currently that will be `"" | "python-only" | "javascript-only" | "no-blocks"`
=> add selected language restriction to tick for new project dialog

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/githubbutton.tsx, webapp/src/projects.tsx, webapp/src/share.tsx
When someone fails to share a game, we can suggest to use github instead. Instead of an arcane error.
=> When a shared project is too big, suggest github

Makefile, pxtsim/runtime.ts
Also, add `make cli` target to rebuilt what's needed for `pxt.js`
=> Add control.dmesg/__log to 'pxt run'

theme/highcontrast.less, webapp/src/monacoFlyout.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2271
The namespace colors on the text portion is fixed for now due to new monaco dropping that form of highlighting; this change just makes the toolbox snippets themselves meet color guidelines in high contrast mode by changing the background to be a border:
=> high contrast accessible monaco toolbox

theme/home.less, theme/themes/pxt/views/card.overrides
Mobile view not modified otherwise, should title over multiple lines. Btw, we don't have any limitation of size on the title...
=> use more space of the card to display script title

docfiles/pxtweb/browserRedirect.ts, pxtarget.json, pxtlib/browserutils.ts, webapp/src/app.tsx
Hardcoded IE redirect in separate script, restore previous redirect behavior (message in loading dimmer) for all other unsupported browsers.
=> Force redirect to /browsers from IE11 regardless of pxtarget

theme/tutorial.less
Meant to include this in https://github.com/microsoft/pxt/pull/6611, but I must have fallen asleep without committing it and didn't notice till today. Makes it so you can customize the glow at runtime instead of being stuck adjusting less vars
=> use css variables for glow animation

localtypings/pxtelectron.d.ts, webapp/src/electron.ts
currently the electron app sends the same state for 'no update is available and everything is fine' as it does for 'downloading non-mandatory update' (`Ok`) , which is a bit misleading
No functional difference currently (the default also just returns), but clears up a misleading comment (`No update available; nothing to do` while downloading update) / can maybe add a 'downloading update' toast. More useful for now in that keeping the states separate helps dedup some info in the update logic of the electron app.
=> add update available state to indicate electron app will try to download update in bkgd

localtypings/pxtarget.d.ts, pxteditor/experiments.ts, webapp/src/monaco.tsx
The python toolbox is stable and should be always enabled (1 less flag!)
=> remove the pythonToolbox flag

localtypings/pxtarget.d.ts, webapp/src/projects.tsx
```
"Community Games": {
"url": "community",
"shuffle": "daily"
},
```
=> Shuffle gallery

pxtcompiler/emitter/service.ts, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1808
Provides hovers for symbols in TypeScript. Not as good as the old TS language service which also gives signature help, but better than nothing!
=> Add basic hover to the TS language service

theme/github.less, theme/themes/pxt/globals/site.variables, webapp/src/gitjson.tsx
A few LESS fixes to ensure the inverted mode is not broke n.
=> Github inverted for minecraft

docs/writing-docs/user-tutorials.md, theme/github.less, webapp/src/app.tsx, webapp/src/gitjson.tsx
Allows to test github tutorial locally without having to publish to github -- which creates tons of caching issues.
=> add route to load tutorial locally

theme/common.less, webapp/src/app.tsx, webapp/src/editortoolbar.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2377 for now
When the view is very very tiny (e.g. zoomed in 400% +), the toggle gets knocked out of view as the expanded toolbar fills the screen. This drops the 'hide' button to the bottom of the screen when in a thin view to make it so you can get out. (the 450px is fairly arbitrary, but does correspond to the default phones in chrome debugger showing the toggle on top in portrait mode (current behavor) and at the bottom in landscape)
mobile views
=> when view is very tiny, bump down toggle closed view

pxtcompiler/emitter/displayString.ts, pxtcompiler/emitter/service.ts, webapp/src/monaco.tsx
Revamping the symbol preview text used by the hover provider in Monaco. I based it off of the stock TypeScript language service, but the implementation is my own. I also have some basic support for Python; it's not as pretty as it is for TypeScript but it's much better than the current behavior.
Here's me hovering over some random examples in TypeScript:
=> Moving hover markdown text into the language service

webapp/src/filelist.tsx, webapp/src/gitjson.tsx, webapp/src/package.ts
When the user is in a different locale than the default locale, the explorer view contains a button to add a localized version of markdown files (language icon)
In the example below, README.md does not have a fr files, so the icon is visible; test.md already have a fr version so the icon is not visible and _locales/fr/test.md does not have the locale or preview button.
=> Support for adding localized versions of markdown files

pxtcompiler/emitter/transpile.ts, webapp/src/app.tsx, webapp/src/dialogs.tsx, webapp/src/filelist.tsx, webapp/src/workspace.ts
Tutorial repos should be able to delete all code.
=> Allow delete main.ts in GitHub mode

webapp/src/app.tsx
NormalizeLanguageCode en-IN  will return ["en-IN", "en"] and nb will be returned as ["nb"]
We need to search the full lang and then the base lang. 
There search is done for something like en-IN-en and then en-IN. This won't succeed if there is only base lang is specified.
=> Langcode bug fix

webapp/src/marked.tsx
This change removes script tag before rendering markdown for tutorials. this is purely cosmetic. The markdown engine still runs with ``sanitize: true``.
It takes care of the javascript we add to markdown pages to render blocks in GitHub Pages.
=> escape script tags in marked.tsx before markdown rendering

docs/targets/home-screen.md, docs/writing-docs/user-tutorials.md, pxteditor/editor.ts, pxtlib/gallery.ts, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/projects.tsx
=> unify parsing of "tutorial", "example", "recipe" routes

gulpfile.js, pxtcompiler/emitter/service.ts, tests/language-service/cases/completions_namespace.ts, tests/language-service/cases/completions_stringliteral.ts, tests/language-service/languageservicerunner.ts, tests/language-service/test-package/namespaces.ts, tests/language-service/test-package/pxt.json, tests/language-service/tsconfig.json
Fixes https://github.com/microsoft/pxt-microbit/issues/2640
The issue wasn't actually overloads, we just completely bail out and return all symbols whenever we can't find the symbol for the left hand side of a property access expression. This adds logic to use the type instead of just the symbol.
Also adds a test suite for the language service. There aren't many tests right now; I'll be adding more as I do fixes. My plan is to expand this to include hover and any other monaco features we implement as well.
=> Adding language service tests and improving completions for literals

webapp/src/components/ImageEditor/keyboardShortcuts.ts, webapp/src/components/ImageEditor/store/imageReducer.ts
fix https://github.com/microsoft/pxt-arcade/issues/1777 (unless there are other blockly shortcuts to prevent, but I couldn't think of any right away) and fix https://github.com/microsoft/pxt-arcade/issues/1778
had the shortcuts for colors already in the old editor (https://github.com/microsoft/pxt/pull/5549), but never used them as much so I never noticed they were gone in the new one
=> Image Editor: keybindings for colors, suppress delete key

pxtcompiler/emitter/service.ts, tests/language-service/cases/completions_ignore_tokens.ts, tests/language-service/languageservicerunner.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2641
Also another minor fix to ignore tokens when searching for the node before the dot
=> Fix completions in non-main ts and py files

cli/cli.ts
Right now we upload the ide strings for any tagged release and any commit on master. This tweaks that logic so that we now only upload on tagged commits that are on master (and not untagged commits).
We run two builds for every `pxt bump`; one on master and one on the tag that's created. This will only upload strings on the former, the tagged release will skip that step.
I tested my `checkIfTaggedCommitAsync()` locally but can't really test the full scenario. Should be safe to merge and then test out.
=> Only upload ide strings to crowdin if on tagged release on master

pxtcompiler/emitter/service.ts, webapp/src/monaco.tsx
Calling `editor.setValue()` trashes the undo stack in monaco. We had a very annoying hack to handle empty files where we replaced the contents of main.ts with a single space if there was no text. I tracked down the real bug which was a truthiness check in the language service compiler host.
I also fixed the logic that replaces special quotes (the ones macOS and iOS like to insert for you) to not call `setValue` directly. Now the evil quotes will show up on your undo/redo stack but that's better than trashing the whole thing.
Fixes https://github.com/microsoft/pxt-microbit/issues/2648
Fixes https://github.com/microsoft/pxt-minecraft/issues/988
=> Fix a couple places where we trash the undo/redo stack in Monaco

docfiles/docs.js, docfiles/footer.html, docfiles/tocheader.html, webapp/src/sui.tsx
re: https://github.com/microsoft/pxt-microbit/issues/2370
makes the modals work a bit better with narrator in scan mode in latest firefox, chrome; docs seems to work properly, but some of the dialogs (in the editor itself) still end up escaping to background / do not properly refocus while in scan mode. Looks like https://github.com/OfficeDev/office-ui-fabric-react/pull/6884 has the same basic problem, with the same attempt at a solution and the rest being left to future narrator updates (also nice write up on the associated issue: https://github.com/OfficeDev/office-ui-fabric-react/issues/6422#issuecomment-430331471).
does not currently work as well in latest (chromium) edge, which seems... weird as it should be consistent with chrome - but the behavior is similar to what I saw in chrome …
=> Slightly better support for screen reader modals

docfiles/style.css
looking at https://github.com/microsoft/pxt/issues/6715 and wanted to use relative links to make things fit into the table easier, but the top bar offsets them annoyingly and makes it hard to follow. This makes the link account for the header bar by offsetting the 'beginning' of the anchor on the page. (I saw the approach on stack overflow a while ago and remembered it, can find it again I'm sure if we want to link it for reference)
e.g., make https://makecode.com/blog/online-learning#09-00am-est-monday-arcade-by-steve-isaacs-https-twitter-com-mr_isaacs- position properly:
current:
with change:
=> account for top bar height in anchor links

docfiles/style.css
re: table issue in https://github.com/microsoft/pxt/pull/6717
make tables scrollable if too wide to fit on screen; better than scrolling the entire page.
=> make docs tables scrollable iff too wide

docfiles/script-page.css, docfiles/script.html, docfiles/scripthead.html
Removed the early loading of simulator. This PR needs to be integrated in stable branches.
=> Apply share page style from Arcade

common-docs/python/classes.md, common-docs/python/functions.md, common-docs/python/sequence.md, common-docs/python/variables.md
Not all illustrative, general language examples will compile properly. Sacrifice syntax highlighting and set snippets to `python-ignore`.
Closes #6720
=> Use ignore snippets in Python lang docs

localtypings/pxtarget.d.ts, webapp/src/cloudsync.ts, webapp/src/projects.tsx
Before displaying a category, test that a particular domain is reachable. e.g. try to download the youtube favicon.ico file before showing a row of videos.
```
"Tutorials": {
"url": "tutorials",
"testUrl": "https://www.google.com/favicon.ico"
}
```
=> ping a url before loading a gallery

theme/common.less
seems to have been broken for any window size < 1200
fix https://github.com/microsoft/pxt-arcade/issues/1769
don't use the css for the mini sim from the toolbar when in sandbox mode (sim, etc)
=> no tiny sim view when in sandbox

pxtrunner/renderer.ts
use the same signatures that are shown in tooltips for the `sig` in docs, and show python sig as well. Notably this adds the namespace to the signature (instead of just the fn / method name)
saw an email that this was missing; this matches the format shown for the tooltip in the editor. A bit redundant with the js, but it's only ever a single line of code per snippet; either way we'd eventually need the format with a language selector in docs / etc
also would close https://github.com/microsoft/pxt-arcade/issues/301 by making the displayed name actually map to what needs to be typed in
=> Make sig macro match editor tooltip, and show py

cli/cli.ts, cli/gdb.ts
This is useful if you have both BMP and CMSIS-DAP connected and want to talk to CMSIS-DAP (eg BMP is used to program non-makecode jacdac device and CMSIS-DAP talks to a makecode device)
=> Add PXT_IGNORE_BMP flag

webapp/src/codecard.tsx, webapp/src/projects.tsx
When a tutorial/example card has a youTubeId entry, display an additional action card to start stream. This allows to surface videos "near" the tutorial.
This change is backward compatible: it will be ignored by older makecode instances.
=> Youtube card on examplers/tutorials

common-docs/reference/math.md, docs/translate.md, docs/writing-docs/user-tutorials.md
Include the sections for math operations from `./blocks/math.md` in `./reference/math.md`.
RE: https://github.com/microsoft/pxt-microbit/issues/2674
=> Sync math ops sections between 'blocks' and 'reference'

pxtrunner/runner.ts
Fix for https://github.com/microsoft/pxt-microbit/issues/2581
=> add missing hints to sidedocs

webapp/src/dialogs.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2111#issuecomment-602622766
@pelikhan I fixed this flag on `sui.Input` a while ago for other accessibility bugs, **should** work across all supported browsers now
=> add autofocus flag to repo name field

pxtcompiler/emitter/service.ts
Fix for https://github.com/microsoft/pxt-microbit/issues/2649
Prepend "on_" to generate function that are arguments in toolbox.
=> generate proper name

webapp/src/app.tsx, webapp/src/editortoolbar.tsx
Allow to fold the simulator in arcade: blocks tend to be extremely long in arcade and we really need forking.
Test build: https://arcade.makecode.com/app/cfc70ba5eb587dfc0b3e0e5afe46cd6e3e10d6b6-6f860889b2
=> Foldtutorial. in stable5.30

webapp/src/dialogs.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2106
also noticed this and the import file both still had cancel instead of the close button; changed that here as I believe we're moving over all but a few special cases to use the close button? can change back if needed.
=> Submit on enter for import url dialog

docs/static/online-learning/online-learning.css
Style resource links with a rollover to jazz them up...
=> Add "hot" rollover for resources links

theme/home.less, webapp/src/projects.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2418 (well, not remembering home page, but that would be a feature that comes with identity)
Went with the primary color to start, as the link blue has issues against the background (it's mostly used against pure white backgrounds like the lang picker, where microbit's home page has a slight blue tint that would make it < 4.5); should be as accessible as the rest of the home page, and it feels like it matches the the projects that way to me.
changed from the sui grid layout for the headers to flexbox as grid wasn't working for small screen sizes (bumping out to new lines unnecessarily, etc) and flexbox handles that properly.
=> View all button instead of > to get to script manager

theme/monaco.less, theme/toolbox.less, webapp/src/monacoFlyout.tsx, webapp/src/toolbox.tsx
- Small animation on toolbox drawers when entering monaco
- Display handle on flyout hover to indicate draggable elements
Build: https://makecode.microbit.org/app/dd487eba2ea31ef83f2e2d03e651a5bb200f24d2-1a20e6fcd0
=> Toolbox visibility: animate drawers, hover effect on flyout

pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts, theme/light.less, theme/print.less, webapp/src/toolbox.tsx
- Right-click context menu opens sidedocs
- Fix printing bugs (black text field in function/colored fields)
- Faster toolbox animation
- Turn off animation in light mode
Fixes https://github.com/microsoft/pxt-minecraft/issues/1855
Fixes for https://github.com/microsoft/pxt-microbit/issues/2678
=> CSS/style fixes for blockly, toolbox animation

cli/cli.ts, pxtlib/tutorial.ts
It turns out that markdown is merciful and eats white. spaces between back tick and the fence code session name eg. If the user makes this mistake our tutorial parsing completely breaks.
```      python
x = 1
```
is valid.
Test both:
```python
while True:
pass
```
with space
``` python
while True:
pass
```
=> Tutorialparsefix

localtypings/pxtarget.d.ts, pxtcompiler/emitter/transpile.ts, webapp/src/app.tsx, webapp/src/compiler.ts, webapp/src/monaco.tsx
This fixes the scenario where you go from a non-python language to python and start debugging or tracing. I added a flag to the compile options to force-update the transpile cache. We should still do something about the transpile cache, but this is a hold-over fix.
=> Fix sourcemap for python when debugging/tracing

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/appcache.ts, webapp/src/cmds.ts
App init is called after loading a variant and forgets about the editor extension command overrides.
In maker, we loose the custom "download dialog".
=> Reapply extension command overrides after app init

pxtlib/github.ts
fix https://github.com/microsoft/pxt-microbit/issues/2715
the helper function created in https://github.com/microsoft/pxt/pull/6760 (`proxyRepoAsync`) was using the status created at the beginning of `repoAsync`. This wouldn't have ever made it through the compiler, except for the fact that that `window.*` properties are unpacked into globals; so there's a global `parent` variable, and in this case, a global `status` variable (that was evaluating to "")
bug came from https://github.com/microsoft/pxt/pull/6760, but I'm going to instead choose to blame javascript as a whole. ~There's gotta be a compiler flag or linter rule to prevent using those, right? Haven't checked but will. I can't imagine a case where I would ever intentionally use `parent` over `window.parent`.~ I forgot that's just …
=> fix approved repos in extensions page

docfiles/style.css
Don't think there was a bug yet, but for example https://arcade.makecode.com/courses; if you have a tallish window footer won't be stuck to the bottom. (or if you zoom out a bunch)
big zoom out pictures:
current:
with this:
=> make docs at least take up full window, footer stays at bottom

pxtcompiler/emitter/service.ts, pxtpy/pydecompiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2701
I wanted to unite the code paths entirely, but it's really tough to factor out the name hint function from the pydecompiler. Instead I tweaked both of them so that they match. The following changed:
1. Snippets from the toolbox now have enum arguments appended to the end
2. Snippets from the pydecompiler now always begin with `on_`
=> Make the function names for python snippets match the pydeompiler

pxtlib/cpp.ts
I'm hitting compile size limits now; this fixes in it for now.
Backend PR pending.
=> Remove leading whitespace in C++ files

package.json
Fixes last "P1" bug from https://github.com/microsoft/pxt-microbit/issues/2678
Fixes https://github.com/microsoft/pxt-microbit/issues/1565
Fixes https://github.com/microsoft/pxt-microbit/issues/2726
=> Bump pxt-blockly to 3.0.5

pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts
In my arcade streams, the size of the blocks quickly becomes unbearable. A collapse all and format options just shrinks everything and make it easier to scale large programs.
=> collapse all option

pxtlib/github.ts, pxtlib/initprj.ts
Front matter ensures jekyll renders the page in github pages + don't fail on updating homepage of repo.
This change allows to use the README.md as the "manual" page for a game automaitcally. Otherwise, jekyll does not render it. Also, only admins have the right to update the homepage of a project so we should not be failing on updating homepage.
=> add empty front-matter and ignore homepage update fails

theme/toolbox.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2718
=> Set no-select for monaco toolbox icons (old Edge fix)

theme/debugger.less, webapp/src/debuggerTable.tsx, webapp/src/debuggerVariables.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2777
Fixes https://github.com/microsoft/pxt-microbit/issues/2738
This PR contains three changes
1. If the code is running, we now show a message instead of the variables from the last stack frame
2. If there are no variables visible at the current breakpoint, we now show a message instead of an empty toolbox
3. Exception messages are now displayed at the top of the variable pane when paused on an exception
And here's a GIF showing all of that off:
Probably needs a UI review
=> Debugger variable view improvements

pxteditor/experiments.ts, webapp/src/accessibleblocks.tsx, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/container.tsx
- Rename experiment to 'Accessible Blocks' for consistency
- Change behavior so experiment enables settings menu item (Accessible Blocks On) which defaults to off
- Add information dialog when toggling accessible blocks on, to explain keyboard commands
Fixes https://github.com/microsoft/pxt-microbit/issues/2779
=> Rename experiment to Accessible Blocks, default to off, add info dialog

webapp/src/cloudsync.ts, webapp/src/scriptmanager.tsx, webapp/src/workspace.ts
fix https://github.com/microsoft/pxt-microbit/issues/2450
the cfg for the original file was being mutated - `getTextAsync` returns the actual object in memory, not a clone, which feels not ideal as it will arbitrarily persist or not depending on if the page gets refreshed or some other save gets applied first? It's not used a ton so can look at making it readonly if we want so we don't accidentally bypass save paths?
Anyway it looked okay till you loaded it up without refreshing & the `header.name` got overrided by `pxt.json`'s config. that is stored in memory and not invalidated
=> Fix script manager duplicate renaming

package.json
- Only draw accessibility cursor if mode is enabled (https://github.com/microsoft/pxt-blockly/pull/283)
- Adding go to definition and removing edit function from calls (https://github.com/microsoft/pxt-blockly/pull/282)
- Fixing exception on disabled breakpoints (https://github.com/microsoft/pxt-blockly/pull/281)
- Add EDGE_OR_IE useragent for flyout button (https://github.com/microsoft/pxt-blockly/pull/280)
=> Bump pxt-blockly to 3.0.6

pxtblocks/blocklycompiler.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/transpile.ts, tests/decompile-test/baselines/comments.blocks
Fixes https://github.com/microsoft/pxt-microbit/issues/2723
This is a few tiny bugs:
1. Decompiler was adding extra newlines to comments
2. BlocklyCompiler was still using the old comment logic that also added extra newlines
3. The transpiler was calling getText() instead of getFullText() when going from python to typescript which strips leading comments
=> Removing extra newlines in comments and fixing transpiler bug

webapp/src/toolbox.tsx
https://makecode.microbit.org/app/4d050dbac3a24db5fe489aa2c98d8cb491c201bd-e0a8de7603
Leaves toolbox "..." submenu open for last selected category
Fixes https://github.com/microsoft/pxt-microbit/issues/2143
=> Don't collapse submenu when clearing toolbox selection

webapp/src/components/ImageEditor/keyboardShortcuts.ts
fix https://github.com/microsoft/pxt-arcade/issues/1834
I thought the event ordering would have handled this but I was mistaken; we don't need the prevent default anyways as stopPropagation is enough to prevent the event from bubbling to blockly.
=> Fix backspace in image editor text fields

pxtpy/pydecompiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2751
=> Fix emit order of comments in pydecompiler

pxtlib/package.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2251
The id of the package is the id it was assigned inside of the parent package's pxt.json. I think this bug went undiscovered because it usually always matches but technically we don't require them to match.
=> Use config name instead of id when checking for localization files

docs/static/playground/pxt-common/pxt-core.d.js, docs/static/playground/pxt-common/pxt-helpers.js, libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2676
Fixes https://github.com/microsoft/pxt-microbit/issues/2797
Switching the help command in monaco to use the language service instead of constructing a help URL from whatever happens to be in the editor. Also adding the help URLs for the builtin math functions. @ganicke you might want to do a pass on the APIs in `libs/pxt-common`, I just added the ones I saw pages for.
=> Use language service to fetch help info

pxtcompiler/emitter/service.ts, pxtlib/service.ts
The user reads the default parameter values when they scan the block in the toolbox so it makes sense to add them to the block string for search. Also adds a field for param jsdoc, but weighted much lighter.
Fixes https://github.com/microsoft/pxt-microbit/issues/2467
=> Fill default values into blockdef for search, add param jsdoc

pxtpy/pydecompiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2805
=> Fixing trailing comma on function calls with long string arguments

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxteditor/editor.ts, pxteditor/editorcontroller.ts, pxtlib/cmds.ts, pxtlib/webusb.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/container.tsx, webapp/src/core.ts, webapp/src/editortoolbar.tsx, webapp/src/sui.tsx, webapp/src/webusb.tsx
WebUSB cleanup round 2. We have a bunch of logic around download dialogs that is duplicated in microbit, pxt and arcade. Unifying.
I will do another further PR to optimize the double pairing in Arcade.
=> Unifiying dialogs for webusb/download

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/blocks.tsx
Preserves Blockly undo stack for "editors" that use the "Go Back" button (serial, github view, etc). 
Fixes https://github.com/microsoft/pxt-microbit/issues/697
=> Preserve undo stack when going from serial->blocks

pxtrunner/renderer.ts
fix https://github.com/microsoft/pxt-microbit/issues/2729
firefox, chrome, edge all scroll nicely with smooth set:
safari ends up in the same spot, but ignores smooth / just snaps there
=> Scroll snippets into view in docs

theme/common.less
Old | New
-- | --
Darken the hover state for all buttons, remove logo on mobile view.
Fixes https://github.com/microsoft/pxt-microbit/issues/2746
Fixes https://github.com/microsoft/pxt-microbit/issues/2677
=> Hide logo on mobile, darken button hover/focus

webapp/src/share.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2154
There's no real way to test this except by deploying it to beta.
For context, the webConfig URLs are patched by the backend but the three ones I reference here should look like this:
```typescript
export interface WebConfig {
relprefix: string; // "/beta---",
runUrl?: string; // "/beta---run",
verprefix?: string; // "v1"
}
```
=> Don't use the relprefix in embed urls

localtypings/pxtarget.d.ts, pxtcompiler/emitter/service.ts, pxtcompiler/emitter/transpile.ts, webapp/src/app.tsx, webapp/src/compiler.ts, webapp/src/monaco.tsx, webapp/src/package.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2649
As we discussed offline, this PR removes the transpile cache from the language service and puts it into the webapp. Specifically, I'm now storing transpile results on the EditorPackage for the project.
There are two main differences between this and the old cache:
1. Transpile results are only cached when the user hits the toggle to switch languages. All other conversions are not cached
2. The transpile cache is only read from when the user hits the toggle to switch languages. All other conversions for compiling, syntaxInfo, snippets, etc. go through the language service
I left the roundtrip checks intact because they still serve a purpose if you reload the project in between conversions. The transpile cache is not saved with the …
=> Moving transpile cache into webapp and fixing snippet bug

pxtcompiler/emitter/service.ts
We now use the typescript language service to get symbols in scope and surface those in auto-complete.
Before, PY had an advantage b/c the py converter kept track of more local info.
Before:
After:
=> Improve auto-complete in JS for local variables

pxtlib/initprj.ts
Fix for https://github.com/microsoft/pxt-microbit/issues/2849
Use _config.yml to force jekyll to always render README.md - with or without front matter.
=> force render of README using _config.yml

pxtcompiler/emitter/emitter.ts, tests/errors-test/cases/enums.ts
here is a proposed fix for issue https://github.com/microsoft/pxt/issues/6873. Results in the following error message:
main.ts(8,9): error TS9210: Cannot compute enum value
=> proposed fix for enum bug

localtypings/pxtparts.d.ts, pxtsim/debugger.ts, pxtsim/runtime.ts, webapp/src/debuggerVariables.tsx
Surface hidden state in debugger by allowing simulator to register "environment globals". Essentially a new set of` ``Variables`` that gets sent to the debugger.
=> injecting envornment globals in debugger

webapp/src/app.tsx
this stuck out a bit when watching https://youtu.be/iEWkWQAXNx0
currently no spacing between sentences, and breaks in the middle of the second one: 
add a break to clean up a little:
=> add line break in png save dialogue

webapp/src/cloudsync.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2693
does not error when loading in the Edge console but does when we do it in code....
=> Can't use query parameters in favicon loading on Edge

webapp/src/cmds.ts, webapp/src/core.ts
Fix for https://github.com/microsoft/pxt-microbit/issues/2858
=> webusb: better error handling during download

theme/highcontrast.less, webapp/src/scriptmanager.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2731
the reason the selectors look redundant is because sui has rules matching ` .ui.menu .ui.dropdown .menu` that unnecessarily override a bunch of things with `!important`, so it gets into a selectivity fight.
Dropdowns without the extra selectors at the beginning (e.g. editor toolbar and this one) don't have that same problem
=> fix script manager sort button size, loosen hc dropdown selectors selectivity

docs/writing-docs/macros.md, docs/writing-docs/tutorials.md, localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, tests/tutorial-test/baselines/activities.json, tests/tutorial-test/baselines/explicitHints.json, tests/tutorial-test/baselines/flyoutOnly.json, tests/tutorial-test/baselines/ghost.json, tests/tutorial-test/baselines/hideIteration.json, tests/tutorial-test/baselines/legacySteps.json, tests/tutorial-test/baselines/python.json, tests/tutorial-test/baselines/singleStep.json, tests/tutorial-test/baselines/steps.json, tests/tutorial-test/baselines/template.json, tests/tutorial-test/cases/activities.md, tests/tutorial-test/cases/button.md, tests/tutorial-test/cases/description.md, tests/tutorial-test/cases/explicitHints.md, tests/tutorial-test/cases/flyoutOnly.md, tests/tutorial-test/cases/ghost.md, tests/tutorial-test/cases/hideIteration.md, tests/tutorial-test/cases/legacySteps.md, tests/tutorial-test/cases/python.md, tests/tutorial-test/cases/singleStep.md, tests/tutorial-test/cases/steps.md, tests/tutorial-test/cases/template.md, tests/tutorial-test/cases/tutorialCompleted.md
Use ```### @diffs true/false`` to enable/disable diffs in tutorials, so that they can be turned on even if the target does not have them on by default. Deprecating noDiffs.
=> noDiffs -> diffs

pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxtlib/cpp.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2823
The problem was that if we hit "Download" twice we get slightly different literal sequence numbers in the assembly. The resulting code is exactly the same though, so we now compute hash of the machine code, not assembly code.
=> Compute program hash at the binary, not asm, level

theme/home.less, webapp/src/blocks.tsx, webapp/src/projects.tsx, webapp/src/toolbox.tsx
Also only pass linkRef to items that are autofocused.
Fixes https://github.com/microsoft/pxt-microbit/issues/2844
Fixes https://github.com/microsoft/pxt-microbit/issues/2846
=> Fix detail card focus, clear toolbox expanded item when unloaded

localtypings/pxtparts.d.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
Always send a full "breakpoint" info while tracing. This allows to see the state changing while running the code. I merged the TraceMessage into a breakpoint message (different subtype), there may be cleaner types to do this.
=> display state while tracing

package.json
- Make the string field width narrower for empty string (https://github.com/microsoft/pxt-blockly/pull/285)
- Hide "Add Comment" on draggable param (https://github.com/microsoft/pxt-blockly/pull/286)
- Fix shadow arg renaming (https://github.com/microsoft/pxt-blockly/pull/286)
=> Bump pxt-blockly to 3.0.7

pxtlib/spriteutils.ts, webapp/src/components/ImageEditor/tilemap/TilePalette.tsx
We hardcoded the tilemap categories, which was a bad decision! This adds the ability to add extra categories.
To add a category, give a tile a tag of the form `category-<name>` (no angle brackets) and it will be placed in a new category with that name. Those names can be localized if you add a localization file with a key like this: `{id:tilecategory}name`.
=> Adding the ability to expand the tilemap categories

localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts, pxtblocks/fields/field_ledmatrix.ts
Automatically scale led matrix buttons based on the size of the matrix. Allow allows it to be parameteriszed. Fix for https://github.com/microsoft/pxt-microbit/issues/2891
=> Scaleledmatrix

package.json, pxtblocks/blocklylayout.ts
- Reindeer connection indicator (https://github.com/microsoft/pxt-blockly/pull/287)
- add pxt-renderer class to preview to apply relevant CSS (hiding connection indicator in sidedocs)
=> Update blockly to 3.0.8, add renderer class to preview SVG

cli/cli.ts, cli/hid.ts, pxtlib/hf2.ts, pxtlib/hwdbg.ts, pxtlib/packetio.ts, pxtlib/webusb.ts, pxtwinrt/hiddeploy.ts, theme/common.less, webapp/src/cmds.ts, webapp/src/editortoolbar.tsx, webapp/src/hidbridge.ts
+ a couple fixes for testGithubpackages in the cli.
=> Lazy reconnect

pxtblocks/blocklycompiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2850
=> Don't let on-start overwrite the block ids in the sourcemap

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_userenum.ts, theme/blockly-core.less
Fix for https://github.com/microsoft/pxt-arcade/issues/1872
\+ small CSS fixes for new animation editor block
=> Blockly upgrade for legacy animation enum blocks

webapp/src/monacopyhelper.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2869
The indent logic in the python formatter assumes that the pasted text starts at the beginning of the line, which isn't always the case.
=> Fixing indent rules for python formatter

cli/cli.ts
To review results more easily, dump markdown formatted errors into a separate file.
=> Write error file in testghpkgs

pxtblocks/fields/field_tsexpression.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2897
=> Don't use deprecated setText in python grey blocks

localtypings/pxtarget.d.ts, theme/debugger.less, webapp/src/debuggerToolbar.tsx, webapp/src/editortoolbar.tsx, webapp/src/simtoolbar.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2857
The trace button is moving to the debugger toolbar! Here's a GIF of monaco and blocks:
=> Move trace to be part of the debugger

theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2925
Turns out we never did any high contrast css for the debugger, so adding some now.
=> Adding high contrast css for debugger

webapp/src/monacoFlyout.tsx, webapp/src/monacoSnippets.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2900
- Add handler params to toolbox snippet
- Use pySnippetName for python
- Add pySnippetName for variable declaration
=> Add handler params to monaco toolbox, fix python snippets

theme/blockly-core.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2928
Rely on Blockly's pxt-renderer for CSS as much as possible
=> Use built-in blockly CSS for font weight

webapp/src/app.tsx
A tiny fix for https://github.com/microsoft/pxt/pull/6939
If tracing is enabled, only use it when the debugger is shown.
=> Don't trace unless the debugger is shown

package.json, webapp/src/blocks.tsx
Pulling in pxt-blockly changes:
- Yellow connection line (https://github.com/microsoft/pxt-blockly/pull/292)
- Reposition widget div when block resizes (https://github.com/microsoft/pxt-blockly/pull/289)
- Fix breakpoint click events (https://github.com/microsoft/pxt-blockly/pull/291)
- Restore "New variable..." option to variable dropdown (https://github.com/microsoft/pxt-blockly/pull/290)
\+ Call reposition functions on workspace resize (simulator collapse/expand). Fixes https://github.com/microsoft/pxt-microbit/issues/2903
=> Bump pxt-blockly to 3.0.9

webapp/src/app.tsx, webapp/src/blocks.tsx
resize is called pretty frequently so i'm firing a manual resize event (which triggers the default blockly logic of hiding the widget div) instead of repositioning it inside our resize call.
Fixes https://github.com/microsoft/pxt-microbit/issues/2932
=> Fire resize event instead of repositioning widget divs

theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-microbit/issues/2961
=> Fix flyout buttons in high contrast

pxtpy/converter.ts, tests/pyconverter-test/baselines/array_generics.ts, tests/pyconverter-test/cases/array_generics.py, webapp/src/compiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2825
We don't handle generics in our python converter. I'm not sure when this regressed exactly, but i remember it working at some point. In any case I am not adding generic support because it should probably be left to the TypeScript compiler. 
While fixing this bug I also figured out the issue that was causing TS errors to only sometimes show up in python programs. The check we were doing in setDiagnostics wasn't accounting for the "built" package and so it always failed after the first run of the project.
=> Bail out on generics in python type inference

theme/errorList.less, webapp/src/errorList.tsx
- made the header sticky when scrolling and show on collapse, fixes: microsoft/pxt-microbit#2938
- changed to collapse chevron
- border slightly thicker
- start collapsed, fixes: microsoft/pxt-microbit#2953
- changed wording to problems
- switched to just using line numbers
- hide error list when there are no errors
- display number of errors in bubble
- sizing change to accommodate header, fixes: microsoft/pxt-microbit#2895
=> Added some of the suggestions made at the design meeting on 4/29

package.json, pxtrunner/renderer.ts
re: https://github.com/microsoft/pxt/pull/6944
Spent a bit looking at docs / sidedocs / etc and this was the only regression I saw; either they removed ability to use self closing `<i>`'s, or it was undefined behavior in the first place. The js / python words were being parsed as children of the icon element instead of being siblings of the icons.
=> bump jquery to 3.5.0

common-docs/reference/math/randint.md, docs/static/playground/pxt-common/pxt-core.d.js, libs/pxt-common/pxt-core.d.ts, pxtcompiler/emitter/service.ts, webapp/src/monacoSnippets.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2894
Fixes https://github.com/microsoft/pxt-microbit/issues/2955
This deprecates `Math.randomRange(0, 1)` in favor of `randint(0, 1)`.
The reasoning for this change is that we already made up the nonstandard API of `Math.randomRange()` and we need to support `randint()` for python so we might as well unify the two. I'm using our usual strategy of leaving the API accessible in TypeScript but hiding the block from the toolbox.
All existing projects should be unaffected. No upgrade rules required!
=> Deprecating Math.randomRange in favor of randint

webapp/src/app.tsx, webapp/src/hinttooltip.tsx, webapp/src/tutorial.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2907
Increases the time before the hint bubble gets popped, and stop the timer between steps (e.g. drag a block and click next step, won't pop till you move a block again); the latter one is the one that I was running into most consistently.
Also got annoyed that it was showing the hint bubble behind unplugged steps, so don't show that
=> Longer wait for hint flash, don't pop on new steps

pxtblocks/blocklycompiler.ts, tests/blocklycompiler-test/baselines/draggable_parameters.ts, tests/blocklycompiler-test/baselines/mc_chat_blocks.ts, tests/blocklycompiler-test/baselines/mc_old_chat_blocks.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/2976
Fixes https://github.com/microsoft/pxt-arcade/issues/1879
We generate a "key" for all events on the workspace so that we can determine if there are any duplicates and disable them. This runs as the first step in the blockly compiler, because we need to know what blocks are disabled before we can start tracking variables, inferring types, etc.
The old way of generating a key was to just compile the arguments, but that led to a chicken-and-egg problem where we needed the variable/type info to compile the argument. Instead I've removed that dependency by only basing the key off of the blocks and not the compiled result.
As a side effect, the keys are now different than they used to be and so our emit order has changed slightly. It …
=> redo callkeys in blocklycompiler to not use compile

webapp/src/app.tsx
fix https://github.com/microsoft/pxt-microbit/issues/2965 so it shows a message like with other transition failures:
also move the editor pref assignment to be after the successful py decompile, so that we're sure it's a valid transition (fix the other bug I added as a comment on the issue)
=> give notification when pydecompile failed and don't switch preferred editor

pxtlib/blocks.ts
Required for https://github.com/microsoft/pxt-microbit/issues/2984
Right now you can't change the name of "this" without breaking localizations and changing the block string.
=> Get the various ways of setting default values on this

package.json, pxtblocks/blocklyloader.ts, pxtblocks/fields/field_imagedropdown.ts
- Re-create workspace comment option
- Use position by field instead of position by block for image dropdown
- Separate input indicators for empty inputs (https://github.com/microsoft/pxt-blockly/pull/293)
- Only reposition widget and dropdown divs when visible (https://github.com/microsoft/pxt-blockly/pull/297)
Fixes https://github.com/microsoft/pxt-microbit/issues/2969
Fixes https://github.com/microsoft/pxt-microbit/issues/2987
Fixes https://github.com/microsoft/pxt-microbit/issues/2933
=> Bump pxt-blockly to 3.0.10

cli/cli.ts, localtypings/pxtpackage.d.ts, pxtlib/cpp.ts, pxtlib/package.ts
When target has utf8 disabled, pxt.json of any package can enable it with `"utf8": true`
Also adds some docs on env variables
Fixes https://github.com/microsoft/pxt-microbit/issues/2372
=> Add pxt.json "utf8" option

theme/debugger.less, webapp/src/debuggerTable.tsx, webapp/src/debuggerVariables.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/2979
The preview disappears when it loses focus. It also selects the text contents when it appears so that you can copy with ctrl-c
=> Adding preview for debugger variable values

webapp/src/share.tsx
Clicking on the QR code expands/collapse it (similar to flipgrid). It makes it easier to scan it when projected.
=> toggle expansion on qrcode

webapp/src/blocks.tsx
prevents unnecessary jumping around the screen
=> Debugger slow-mo center on collapsed parent instead of hidden child

pxtpy/converter.ts, tests/runtime-trace-tests/cases/slice_str_types.py, tests/runtime-trace-tests/readme.md
Fixes https://github.com/microsoft/pxt-microbit/issues/2931
Additional type unification, fixes the following (previously errored on the call to "len"):
```
c = [[2,3], [4,5,6], [7]]
a = c[1]
b = len(a)
```
```
a = "test"[1:2]
b = len(a)
```
```
a = str(45)
b = len(a)
```
=> Unify types on calls to slice, str

pxtsim/debugger.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3016
We already fix the variable names in the webapp, so we don't need to do it in the simulator. Otherwise we might overwrite two variables in the same scope with the same name (which I think is only possible with for-loops). AFAIK the debugger is the only consumer of the breakpoint message stack frame so I think this change shouldn't break anything.
Ideally we should only show the variable that is currently visible instead of two entries with the same name, but we don't really have a way of checking that. This at least makes the behavior the same as it is for other shadowed variables (which also get duplicate entries)
=> Don't fix variable names in breakpoint message

pxtpy/converter.ts, tests/pyconverter-test/baselines/variable_declared_in_main.ts, tests/pyconverter-test/cases/variable_declared_in_main.py
Fixes https://github.com/microsoft/pxt-microbit/issues/2944
We don't need to hoist variables if we are already in the top-level scope.
=> Don't hoist variables that are first assigned in top level scope

pxtblocks/blocklylayout.ts
Scrolls blocks to the top left corner of the workspace after format/flow which I think is reasonable/expected behavior. You can load the test program into /beta and see the current behavior, which changes based on where in the workspace you are (eg try scrolling to the top-right corner and format).
Test program: https://makecode.microbit.org/_Dkw2emRfjKRk
Build: https://makecode.microbit.org/app/e3d66d88919b640778708d582fb76001a12b2085-c5005c49da
Fixes https://github.com/microsoft/pxt-microbit/issues/3007
=> Scroll formatted code to top left corner of workspace

pxtlib/github.ts, webapp/src/githubprovider.tsx, webapp/src/gitjson.tsx
When failing to write to an org repo, also suggest to authorize app.
This is a common scenario for github classroom, where the teacher might have forgotten to authorize our app. Use special prompt flag to force showing the authorization page in the login flow.
=> GitHub write issues handling of orgs

pxtlib/initprj.ts, pxtlib/main.ts, webapp/src/workspace.ts
When creating a repo in classroom/github, the user has the option to add a dummy README/.gitignore. This changes allows us to deal with this.
=> Append README content instead of ignoring

theme/debugger.less
Fixes https://github.com/microsoft/pxt-microbit/issues/3017
I eventually resorted to doing a manual diff of the css between the live site and master and found the selector that was causing the bug. This restores the old behavior of only showing the breakpoint you're hovering over.
=> Override codicon css for monaco breakpoints

webapp/src/errorList.tsx, webapp/src/monaco.tsx
There was an issue with the errors given while using javascript that would send to line 1
fixes: microsoft/pxt-microbit#3005
=> fixed issue where clicking on error sends to line 1

pxtlib/packetio.ts, webapp/src/app.tsx, webapp/src/cmds.ts
Always disconnect all webusb devices when switching tabs. This prevents a rogue tab to keep a lock with a device and disable other tabs. It may have some annoying side effect, like you can't leave an editor logging in the background, but it minimize locking issues when people have lots of tabs.
fix for https://github.com/microsoft/pxt-microbit/issues/3034
fix for https://github.com/microsoft/pxt-microbit/issues/3033
note that different browsers (chrome/edge) will still be able to lock a device
=> webusb: disconnect recoonect between tabs

webapp/src/app.tsx
classrooom -> #github: link -> oauth dance -> #github:link success.
When a student arrives in MakeCode from a github classroom link and is not signed in, we need to first signin, then import the repo.
=> fix github import route

pxtcompiler/emitter/backjs.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3012
We were getting interleaved evals that were consuming each other's resumes. Fixed by checking to make sure that the runtime embedded in the binary matches the global one.
=> Check that runtime id is still current

pxtcompiler/emitter/hexfile.ts
=> Fix typo in flash checksum replacement

webapp/src/app.tsx
Support snapping to releases for loading tutorials + caching.
=> Versioned tutorials

theme/tutorial.less
adjust width now that we hide the entire hint bubble on steps with no hint
removes gap:
=> Set tutorial card width for steps with no hint

pxtlib/github.ts, webapp/src/app.tsx, webapp/src/githubprovider.tsx
It seems that GitHub is expeiring OAuth tokens (maybe there is a limit of clients) or the user might just invalidate it too. SInce any github request may fail, we handle this at the request level and simply erase the token from the browser.
This change also guarantees that loading a tutorial does **not**rely on a token since that token might be bogus.
This fix is not bullet proof, i should really be wrapping every github call with a retry without token that goes through the proxy.
Added tick for errors to track them.
=> Handling invalid github token

pxtpy/parser.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3044
Not sure how to add a test for this. This is the snippet i used while debugging:
```py
def on_forever2():
for x in range(5):
basic.forever(on_forever2)
```
That snippet has nine errors, but many of them are duplicates. Seems wrong to create an error test case that expects those duplicates to exist.
=> Don't infinite loop on parse error near EOF

webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/3015
Basically, we pass the filter text to the completion provider so that completions work better in localized languages, but monaco will not dismiss the suggest widget if the current word exists inside the filtertext for an item! In this case the word was " " (space)
I'll have you know I had to read the vscode source and debug the stock monaco typescript service in the playground to figure this one out!
=> Strip whitespace from monaco filter text

pxtcompiler/emitter/service.ts, tests/language-service/cases/completions_global.py, tests/language-service/cases/completions_global.ts, tests/language-service/cases/completions_local_param.ts, tests/language-service/languageservicerunner.ts, tests/language-service/test-package/namespaces.ts, webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-microbit/issues/2893
Fixes: https://github.com/microsoft/pxt-microbit/issues/2707
Fixes: https://github.com/microsoft/pxt-microbit/issues/2736
Fixes: https://github.com/microsoft/pxt-microbit/issues/2977
Fixes: https://github.com/microsoft/pxt-microbit/issues/3056
Lots of miscellaneous auto-complete improvements.
We better handle member completion and don't show bogus symbols when we can tell the type  we're completing on.
We make sure we at minimum can complete global symbols in Python.
We fix the ordering on some completions, like putting local variables higher.
We more correctly identify where a completion snippet should start (if it's qualified).
We correctly handle showing local variables after a parenthesis.
We recompute auto-complete after a …
=> More intellisense fixes

webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-microbit/issues/3066
This is a regression introduced by: https://github.com/microsoft/pxt/pull/7032
In most cases we don't want auto-complete to trigger on semi-colon. Instead when the user starts typing an identifier or type name, auto-complete will trigger naturally.
This was introduced as a fix for a different issue (part of https://github.com/microsoft/pxt-microbit/issues/2707) but actually this other PR fixed that part better: https://github.com/microsoft/pxt/pull/7034
=> Remove ":" as auto-complete trigger

theme/tutorial.less
fix mobile width, the change to the selector made the normal one overpower the mobile only one
curr:
fixed:
=> fix width of tutorial message on mobile

pxtlib/github.ts, pxtlib/util.ts, webapp/src/githubprovider.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/3075
=> unify error handling in github

webapp/src/monaco.tsx
Checks insertion snippet (set from toolbox) and does not return hover if it is set 
Fixes https://github.com/microsoft/pxt-microbit/issues/2703
=> Disable tooltip hover when dragging block from toolbox

docs/github-explorer.html, webapp/src/filelist.tsx
A few glitch found while using github-explorer (readonly mode)
=> Readonly fixes

webapp/src/lang.tsx
In-context translation requires a crowdin translator account. Adding a dialog to explain process. "Register" takes the user to the crowdin project, also links to translation help.
=> Solve chicken egg issue in translation

webapp/src/simtoolbar.tsx
Just noticed I forgot to add hidefullscreen on these, so these two were also showing up mobile fullscreen view
=> hide mobile expand / hide sim button on mobile fullscreen

localtypings/pxtarget.d.ts, pxtcompiler/emitter/service.ts
when generating snippets for auto-complete  or toolbox, track when we introduce new definitions so that we can make sure we regenerate those snippets when names might have changed.
I believe this regression was introduced as a side effect of better caching of symbol info between intellisense calls. Really snippets are very stateful and so we need extra info to know when to invalidate them.
Fixes: https://github.com/microsoft/pxt-microbit/issues/3068
Fixes: https://github.com/microsoft/pxt-microbit/issues/3074
=> Ensure name uniqueness for auto-complete and toolbox snippets

theme/common.less, webapp/src/simtoolbar.tsx
quick changes we discussed on teams:
move fullscreen button to top in tablet mode, make the collapse / expand show up in same color as other editor tools, and a little space around download button in tablet view
=> use editor tools colors instead of red / green, padding in tablet view

webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/toolDefinitions.ts
This PR adds support for copy/paste for marquee selections in image/sprite editors:
https://github.com/microsoft/pxt-arcade/issues/1835
This PR also puts the `` img`…` `` formatted data on the clipboard as `text/plain` enabling copy in the sprite editor and pasting into JavaScript:
This functionality isn't required and would be easy to turn off if it's too "cute".
Some implementation discussion over here https://github.com/microsoft/pxt-arcade/issues/1896 and also on a previous PR https://github.com/microsoft/pxt/pull/6990
Currently tilemaps are not supported; it looks like the serialization format I'd want to use for a partial selection of tilemap data is implemented by a non-exported function: https://github.com/microsoft/pxt/blob/c002848a42fdbb7a3a9e118db8e3fe0ee7741222/pxtlib/spriteuti …
=> Add copy/paste support for marquee selections.

common-docs/javascript/functions.md, common-docs/javascript/operators.md, common-docs/javascript/statements.md
The links to `devdocs.io` pages have equivalent pages at `https://developer.mozilla.org`. Those page links are replaced with the MDN page links. If linking to MDN is not appropriate, then we'll have to figure something else out.
Closes #7058
=> Replace 'devdocs' JS links

libs/pxt-python/pxt-python-helpers.ts, pxtcompiler/emitter/service.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3104
This adds an implementation for `range()`. It does not change anything about for-loops, they still get mapped the same way and they still can only take one argument in the call to `range()`.
Requires https://github.com/microsoft/pxt-microbit/pull/3109
=> Adding range function for python

pxtlib/browserutils.ts
Should fix https://github.com/microsoft/pxt-microbit/issues/2601
I can't really test it locally but this is the same check we use in monaco for determining if we're on an ipad. I tested that it does return true in the ios 13.3 ipad simulator.
=> Adding detection for ios 13 ipads

webapp/src/blocks.tsx
fix https://github.com/microsoft/pxt-microbit/issues/3096
I tested this with the random-range deprecated block, and the radio.receiveString() because they seem to be deprecated in different ways?
=> Show deprecated blocks if they're being used in a tutorial

pxtcompiler/emitter/service.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3046
We don't treat `range()` as a symbol when it's in a for-loop because we convert it to the TS style of for-loops (not a function call). Adding a special case to the language service to make sure that you get the same hover text in a for-loop as you do in standalone calls to `range()`
=> Special case range in for-loops for symbol info

theme/common.less, webapp/src/simtoolbar.tsx
fix https://github.com/microsoft/pxt-microbit/issues/3128
=> swap restart button for fullscreen on mobile simtoolbar

pxtcompiler/emitter/plaintsc.ts
I was trying to figure out why we did not get file names in compilation errors for common-sim.
Bug introduced 14 months ago. https://github.com/microsoft/pxt/commit/df519380dd03d67317ac61f4cb88e620c00d035d
=> any is evil

webapp/src/gitjson.tsx
Blocks is not quite ready for collaboration so hiding that button for now.
=> Invite button

libs/pxt-python/pxt-python-helpers.ts, pxtpy/converter.ts, tests/pyconverter-test/baselines/slice_step.ts, tests/pyconverter-test/cases/slice_step.py
Fixes https://github.com/microsoft/pxt-microbit/issues/3153
In python, slices can take three arguments:
```python
"hello"[start:stop:step]
```
Currently, we ignore the step part. This adds support for that in the form of some python helper functions. This only goes one way (py -> ts) because this is not an API that is accessible from blocks (the conversion will still work in the other direction, it just won't be pretty).
I added two functions, one for strings and one for arrays.
=> Support the "step" argument in python's slice syntax

theme/errorList.less, webapp/src/app.tsx
Changed the debounce time to 2 seconds to prevent the aggressiveness of error warnings. Could be further increased if needed
fixes: microsoft/pxt-microbit#3123
=> increased debounce time for errors

webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/cmds.ts, webapp/src/core.ts, webapp/src/dialogs.tsx, webapp/src/filelist.tsx, webapp/src/githubprovider.tsx, webapp/src/gitjson.tsx, webapp/src/lang.tsx, webapp/src/make.tsx, webapp/src/webusb.tsx, webapp/src/workspace.ts
fix https://github.com/microsoft/pxt-microbit/issues/3105
Did a quick pass over all the calls to the core modals in pxt and the one in the issue was the only one that seemed like it needed to be switched to a close button. Also went ahead and cleaned up a bit by making the `hasCloseIcon ⇒ hideCancel` consistent across all the modal methods / clearing out the redundant options.
=> quick pass updating modals to use close icon where needed

package.json, webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3132
I'm pulling in the new pxt-blockly and adding the zoom option to enable pinch zoom
=> Enable pinch zoom in editor

docfiles/pxtweb/cookieCompliance.ts
Haven't tested this on iOS (no BrowserStack access yet), but this only runs the performance measurements if performance.mark is defined. mark/measure/getEntriesByName are all enabled from iOS 11+
Fixes https://github.com/microsoft/pxt-microbit/issues/3038
=> Disable performance reporting if APIs not found

pxteditor/monaco.ts, pxtlib/browserutils.ts, theme/monaco.less, webapp/src/monaco.tsx
fix https://github.com/microsoft/pxt-microbit/issues/3170 / a handful of issues on (devices claiming to be) android. (I'll file an issue for actually fixing android autocomplete)
- disable accessibility support on android; this setting causes this awful bug where every letter you type after a period doubles the contents of the line:
Full fix for that seems like it's in vscode / monaco-editor
- disable auto complete on android; even with the previous fix it is not consistently applying the correct autocomplete (or at least fixing it). Note the css hiding it, as it's not actually an option to completely disable intellisense with just the options passed in (still triggers on periods, etc - ([more info](https://github.com/microsoft/monaco-editor/issues/1681)). 
- The lagging textarea thing is …
=> Android monaco fixes

pxteditor/editor.ts, theme/common.less, webapp/src/app.tsx, webapp/src/errorList.tsx, webapp/src/monaco.tsx
fix https://github.com/microsoft/pxt-microbit/issues/3106
Few notes on errors I was thinking about while doing this (@hristoramirez maybe interesting?)
* we'll need to think about this for minecraft (transparent editor tools) as well; could just apply the same extra padding to the editor tools when they're transparent easily enough, but that'll need a design meeting so I left it out of this PR, maybe outside scope of internship as it wouldn't ship for a while?
* the 2 second debounce feels alright to me when adding the error (longer than I would personally like but I agree it's probably better for kids), but it's pretty painful when you fix an error as it feels like you're doing wrong / 2 seconds is long enough to second guess yourself. Maybe if we could keep the squiggle after .5 …
=> account for error list in portrait simulator positioning

webapp/src/app.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/3027
Treat a header reload as a new project, and deep clean cache state of compiler.
=> deep clean compiler on reload

docs/blog/microbit/2020-beta.md
Put in a note for the date of the general micro:bit 2020 release.
=> Blog note for micro:bit 2020 release

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/toolboxeditor.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3198#event-3389041242
related to https://github.com/microsoft/pxt/commit/2e9fde5a3a9f6900d652442d4c031b1995e0344f
Show the deprecated blocks if we're in a tutorial in Python or JS
=> Show deprecated blocks in Python/JS tutorial

docfiles/package.html
The current message just says:
`"The content below is provided by partner."`
Here, I've **only** added the **"a"** as a minimum to update the message.
`"The content below is provided by a partner."`
However, the ask from https://github.com/microsoft/pxt-microbit/issues/3207 is to have something more like:
This could be done through use of a macro like `@approver@` or something like that.
```
<div class="content">
<h3 class="header">
Approved content
</h3>
<p>
The content below is provided by a partner and approved by the @approver@.
</p>
</div>
```
=> Update partner approval message

webapp/src/editortoolbar.tsx, webapp/src/projects.tsx
In Windows 10 app, 
Fix for https://github.com/microsoft/pxt-microbit/issues/3213
=> hide github button, github import in winrt app

webapp/src/monacoFlyout.tsx
Handle case when handler arg is in the block def as well as when it's not
Fixes https://github.com/microsoft/pxt-arcade/issues/1801
=> Check if handler arg is in block def before adding to monaco toolbox

theme/common.less, webapp/src/simtoolbar.tsx
close https://github.com/microsoft/pxt-microbit/issues/3200
Starting as a draft as adding back fullscreen button in mobile was a request when it was fullscreen & restart; I think showing debug button is more important, just want to confirm.
=> hide fullscreen button in mobile view instead of debug btn

cli/hid.ts, pxtlib/browserutils.ts, pxtlib/hf2.ts, pxtlib/packetio.ts, pxtlib/webusb.ts, pxtwinrt/deploy.ts, pxtwinrt/hiddeploy.ts, pxtwinrt/serial.ts, pxtwinrt/winrt.ts, pxtwinrt/winrtworkspace.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/editortoolbar.tsx, webapp/src/hidbridge.ts
This PR fixes download in Windows10 app. Tested also that webusb still works. The heart of the issue was that we running cmds.init before configurating DAPLink.
=> Fix WindowsRT download

webapp/src/githubprovider.tsx, webapp/src/lang.tsx
disable oauth in pxt electron for now (I'll fix it later, but have a few other issues that are more pressing / it's not the typical scenario for the offline build to need oauth)
I guess question if we should disable these in minecraft too? Haven't tested if they work but I don't think they will?
=> disable oauth in pxt electron

webapp/src/app.tsx, webapp/src/editortoolbar.tsx, webapp/src/projects.tsx
Disabling for now re: https://github.com/microsoft/pxt/pull/7130#issuecomment-639077631
Question, do we want any special behavior for if the user passes in a github url to `import url` ? e.g. importing https://github.com/jwunderl/untitled-testasdf will import the repo as a github extension with a slightly off ui. I don't think I saw any special handling for the gh extension so I'm guessing it just does nothing or errors; should I just pop an error in both for now?
=> disable entry points to gh integration in pxt electron

pxtblocks/blocklycompiler.ts, webapp/src/blocks.tsx
Partial fix for https://github.com/microsoft/pxt-arcade/issues/1692
This prevents the warnings that pop up on disabled blocks. Real cause of the issue is when a big stack of blocks with many warnings overlaps another one, it triggers a chain of calls to bumpNeighbours that bumps the stack way down into the right corner. 
The other part of the fix will be on the blockly end to either tweak the bump functionality or just disable it in some cases--in general I feel it's better to have overlapping blocks than to move blocks that the user did not drag.
\+ small update to remove unnecessary getTopLevelParent function
=> Set enabled/disabled on child blocks, prevent unnecessary warnings

package.json
- Save block-level comment position in XML (https://github.com/microsoft/pxt-blockly/pull/311)
- Pass extra options object to Blockly.prompt (https://github.com/microsoft/pxt-blockly/pull/312)
Fixes https://github.com/microsoft/pxt-arcade/issues/1867
Options object is for https://github.com/microsoft/pxt-arcade/issues/1797 (will make separate PR with pxt changes)
=> Bump pxt-blockly to 3.0.18

webapp/src/carousel.tsx
I happened to notice that the carousel resize event handlers were never unsubscribed:
=> Clean up carousel resize event subscriptions on unmount

theme/home.less
Fixes https://github.com/microsoft/pxt-microbit/issues/3227
=> Use outline without scale to differentiate details card focus and hover

pxtlib/emitter/cloud.ts, pxtlib/github.ts
Fix extension search in electron app (and normal staticpkg, I would assume?)
it was hitting `/gh/owner/repo` instead of `/api/gh/owner/repo` in the electron app as it was using `relprefix`
=> fix extension search in electron app

webapp/src/debuggerVariables.tsx
Noticed this when debugging a thing in electron app (Only shows up when using dev build of react):
Only the extra row for the exception message was missing the key, so it rarely pops up ~
=> add key for debugger variables list error message

theme/errorList.less, webapp/src/errorList.tsx, webapp/src/monaco.tsx
Made each individual stackframe clickable
Also removed workaround with creating the error click function in render
fixes: microsoft/pxt-microbit#2996
=> added clickable stackframes to error list

pxtblocks/blocklylayout.ts
Missed this CSS because it's separately injected
Fixes https://github.com/microsoft/pxt-microbit/issues/3232
=> Add Blockly injected CSS to screenshot SVG

common-docs/reference/string.md, common-docs/reference/text/is-empty.md, common-docs/reference/text/split.md
Put in missing Text reference pages for `isEmpty()` and `split()`.
Fixes #7113
=> Add the Text ref pages for 'isEmpty' and 'split'

pxtblocks/fields/field_tileset.ts, pxtlib/spriteutils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1738
Support image literals that are passed to the tileset field. This will preserve the value, but the field will look like the transparent image is selected instead of whatever you passed. Doesn't seem worth it to change the rendering since we are extending the existing field and this is a corner case.
Originally I wanted to prevent this by changing the decompiler, but I couldn't because of this fix:
https://github.com/microsoft/pxt-arcade/issues/488
...which was a good change.
=> Handle image literals being passed to the tileset field

docs/streamer.html
Show hardware video fulil screen when enable on "start soon" screen.
=> streamer: show hardware on land screen if enabled

docs/streamer/script.js, pxteditor/editor.ts, pxteditor/editorcontroller.ts, webapp/public/controller.html, webapp/src/app.tsx
Allows streamer to set editor in full screen mode when swithing between multi editors.
=> add controller message to set/unset simulator full screen

cli/cli.ts
Removing the local-dev API cache that was causing lots of problems.
Warning: this makes repeat serves for arcade much slower if you aren't using the `--rebundle` flag. We pretty much always use that for development so I think it's fine.
=> Remove development API cache

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/3257
Not sure if there's a reason we had it as a trailing debounce instead of immediate? I tested toggling quickly between various languages and also refreshing the page, and it seems to all work.
=> Save/typecheck immediately on change, then debounce

webapp/src/app.tsx
Loads readme in sidedocs (if not a github repo).
Fix for https://github.com/microsoft/pxt-microbit/issues/3269
=> load markdown on tutorials

webapp/src/app.tsx
Build: https://makecode.microbit.org/app/8a48e8bac428aefbbc9ef60ea441e3f564a9313e-cf060f4d40
Leading edge debounce behaves incorrectly for autorun (blockly sends a sequence of events and we attempt to autorun after the first block dragged event rather than after the user is done editing).
This preserves the error debounce behavior (2s delay) but reduces the save/editor change handler debounce. I tested intellisense/hover in monaco and they seem to behave as expected even with the slightly longer typecheck debounce.
Separately, I think we should force a save any time the editor unloads (changing language) or the user hits download, but probably a different PR.
Fixes https://github.com/microsoft/pxt-microbit/issues/3257
=> Set editor change debounce back to .5s, increase typecheck debounce

pxtlib/docsrender.ts
Crowdin returns list headings with extra whitespace at the end (eg `* [따라해보기](/tutorials)`); the regex doesn't match this and so all localized TOC headings are empty. I'm modifying the regex so it doesn't match start/end of line but making the .* groups nongreedy, which I think should be pretty safe. It should still always match the first link of `[text](path)` format. 
I've tested this locally by calling buildTOC manually on an input string I copied from Crowdin, but haven't been able to deploy to staging to test there.
Fixes https://github.com/microsoft/pxt-microbit/issues/3263
=> Relax table of contents parsing regex for docs TOC localization

theme/debugger.less
fixes https://github.com/microsoft/pxt-arcade/issues/1972
Here's what it looks like!
=> Sticky the debug toolbar

webapp/src/cmds.ts
The webusb changes have the electron app trying to use Hid; this ends up failing due this [this](https://github.com/microsoft/pxt/blob/master/webapp/src/hidbridge.ts#L47) bailing out of initializing iface and then gives an NPE [here](https://github.com/microsoft/pxt/blob/master/webapp/src/hidbridge.ts#L156). Not a big deal, it just ends up in a failed promise without a visible effect on the app, but it does end up flooding the console a bit in the electron app / makes pinpointing other errors a bit harder.
Eventually I'll have to get webusb working in the electron app (should be able to get away without even popping up the selection dialog), but fixing all the build pipeline / signing errors in the electron app took too much time to look at that for this release.
=> don't try hid on electron app

webapp/src/cmds.ts
Cherry pick https://github.com/microsoft/pxt/pull/7245 for electron release
Not strictly needed / doesn't have a behavioral change, but this prevents the very noisey exception I mentioned before in electron; we don't currently use the hid or web usb path for downloading there (it's separately handled with the drive deploy logic), and the hid init fails with a scary looking error message every time a project is loaded / refreshed which drowns out other potentially important errors
=> [stable6.0] don't try hid on electron app (#7245)

docs/static/shared/iframeeditor.css
fix view on current safari re: https://github.com/microsoft/pxt/issues/7248 (was there another issue for this?)
It's possible there's an issue on much older versions of safari (as there are a few 'still used but old' versions that don't support some es5 functions), but if there is we'd probably need browserstack to get them; oldest safari I can get access to on my device is ios 10.3.1 and with this change it works there ~
=> fix playground / tutorial-tool on safari

docs/editors.json, docs/static/playground/playground.js, docs/static/playground/playground.ts, docs/static/streamer/script.js
- Remove target list from playground, use editors.json
- Add "unsupported" array with endpoint names + read this in playground/streamer
- Added new endpoints for playground
I looked into updating the tutorial tool as well but the share code would require some changes to the editor.json structure and it grew to be a slightly larger change so I'm leaving it as-is for now.
=> Use editors.json in playground, additional editors + "unsupported" flag

pxtblocks/codecardrenderer.ts
fix https://github.com/microsoft/pxt-arcade/issues/2018
This part of the code could probably use a round of cleanup, but figured it was best to do the fix separate.
re: dropping the `a` function, the only use was in the condition I dropped below, which had the condition `url && !link`, which is `url && !!!url`, or more specifically `url && !url`, so shouldn't be any behavioral change besides fixing the links
=> fix code card links in side docs

pxtcompiler/emitter/service.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2023
For image APIs, we check both the source file and the generated shim file for attribute strings. I think in general we do still want to check the generated shims and the source files for APIs, so I'm adding a check here to just avoid duplicating the sources if one is fully contained in another.
=> Check if symbol attribute source is duplicated before concat

webapp/src/dialogs.tsx
Pretty minor / wouldn't ever be seen by end users, but felt like it was worth checking the code in case there was an actual issue there / might as well fix while there
When you have a build of an electron app that does not yet have a release, it pops up this message in the about dialog:
Which is obviously wrong. Issue is that the targetconfig stored by the electron app gets stamped with `.electronManifest.timestamp`, so it trivially has an electronManifest, even if there is no release yet (and `pxt.semver.strcmp("v0.0.1", undefined)` returns -1)
=> fix update message when no latest electron build is set

webapp/src/components/ImageEditor/ImageCanvas.tsx
Enable pasting into image editor from elsewhere if the plain text looks roughly like an image literal. Also see https://forum.makecode.com/t/copying-makecode-image-data-from-another-application/2656
re: @jacobcarpenter tried to add you as a reviewer too but it didn't let me :(
=> allow pasting image literals from text into image editor

pxtcompiler/emitter/service.ts, tests/language-service/cases/completions_local_param.ts
Depends on: https://github.com/microsoft/pxt/pull/7277
Fixes: https://github.com/microsoft/pxt-arcade/issues/2069
Before:
After:
=> Fix parameter defaults for javascript/python snippets and auto-complete for fixed instances

pxtlib/jsoutput.ts
This improves compilation speed for large projects. Testing with the game mentioned in https://github.com/microsoft/pxt-arcade/issues/1928, cumulative time spent in the `getCurrentLine` method:
* Before: ~30s
* After: ~2s
=> Optimize use of regex in hotpath

pxtpy/pydecompiler.ts
- Indents the inner part of template literals
- Updates the getCommaSep to handle multiline elements (skip indent for first line, not entire first element)
- Updates indent function to indent every line, instead of just the first
Fixes https://github.com/microsoft/pxt-arcade/issues/2036
=> Update indent to handle multiline strings

pxtcompiler/emitter/service.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2068
Is there a way to add snippet tests?
=> Fix snippets for shim=TD_ID parameters

pxtcompiler/emitter/service.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1945
fixes https://github.com/microsoft/pxt-arcade/issues/1929
The way the img snippets were being resolved before was by checking the default value for parameters. However, now that we're recursing on resolving snippets, we don't have that special case to see if there's a snippet already provided. Images seem to be the only type of block that we've defined that has the snippet provided though, so I don't feel suuper good about adding more code for such a special case
I have two questions for this mainly:
1. I saw that there was a TODO to pull out the 'getParameterDefault' function out of getSnippet for general use - maybe I should refactor a bit and try to reuse the getDefault code? Do we not have to get the default for non parameter …
=> Check for provided snippets

webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/ImageEditor/keyboardShortcuts.ts
Two bugs:
- We were always dispatching keyboard shortcut events to "mainStore", even when the nested image editor had a separate store
- We were unbinding events on component unmount, which removed the event binding for the tilemap below as well
=> Fix keyboard shortcuts in nested image editor

pxtlib/jsoutput.ts
This is another attempt to squeeze perf out of `compileAsync`. Previous attempt here: https://github.com/microsoft/pxt/pull/7283, which brought it from 20s to 6s. That was a nice improvement, but still noticeably slow. Getting better results this time:
Time spent in `compileAsync`:
| Before | After |
|---|---|
| 6s | 500ms |
Testing with this project: https://arcade.makecode.com/74548-67333-76127-33508
Related: https://github.com/microsoft/pxt-arcade/issues/1928
=> Compiler perf: Count line numbers progressively

pxtpy/pydecompiler.ts
We were previously concatenating the entire qname which resulted in controller.combos.attachCombo -> combos_controller.combos.attach_combo during the recursion.
Tested: Warehouese, Jumping Mateo, HackMan, Raptor Run
Fixes Warehouse and Jumping Mateo from https://github.com/microsoft/pxt-arcade/issues/2083
=> Use rightmost part for python callback naming

pxteditor/monaco-fields/field_sprite.ts, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2079
Three changes:
1. Emit the python syntax and not typescript when we are editing python
2. Made the regex a little more robust
3. Register the folding range provider for python (this is what actually makes the icon show up)
=> Fix the monaco sprite editor for python

cli/cli.ts
Part of the fix for https://github.com/microsoft/pxt-arcade/issues/2103
Used to build https://github.com/microsoft/pxt-arcade/pull/2109
@jwunderl any other forms of the tags I should know about?
=> Handle the other format of the tile tag in sprite meta json

pxteditor/monaco-fields/field_tilemap.ts, webapp/src/filelist.tsx, webapp/src/package.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2098
Also fixes part of the issue https://github.com/microsoft/pxt-arcade/issues/2125
And makes it so that the generated tilemap and tileset files can't be deleted
=> A couple tilemap bugs

pxtcompiler/emitter/service.ts
fix https://github.com/microsoft/pxt-arcade/issues/1898
took the kindNamespace resolution (defined kindNamespace >  blockNamespace > namespace) from https://github.com/microsoft/pxt/blob/master/pxtlib/service.ts#L512
I wasn't completely sure where in `getBlocksInfo` to include this check, but this seemed like a reasonable spot to start with.
Side note, looks like block kinds still don't allow default values; that is, adding
```typescript
//% kind.defl=SpriteKind.Player
//% otherKind.defl=SpriteKind.Enemy
```
here https://github.com/microsoft/pxt-common-packages/blob/master/libs/game/spriteevents.ts#L51 doesn't cause `otherKind` to start off as `Enemy` in blocks. (It does in the js/py completions / snippets though)
Maybe something to try and fix, I can give it a look? I guess depends on …
=> Fixes sprite kinds completion / toolbox snippet

webapp/src/errorList.tsx, webapp/tsconfig.json
Duplicate compiler errors are grouped, and a count bubble is shown (if count > 1).
Before:
After:
(screenshots not taken from the same project, so total error count is different)
Fixes: https://github.com/microsoft/pxt-arcade/issues/2105
=> Group errors by line number and show count

theme/github.less, webapp/src/gitjson.tsx, webapp/src/package.ts, webapp/src/workspace.ts
* revert all button
* revert sibling generated files
fix for https://github.com/microsoft/pxt-arcade/issues/1964
=> github: revert all + support for generated files

localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
This is to let us have homepage cards with just a share url, immediate purpose is for (potential) game jam carousel row, could be used for later blocks/js games, etc
=> Add 'sharedExample' detail card to support shared/github urls in carousel

pxtcompiler/emitter/emitter.ts, tests/compile-test/lang-test0/17classes.ts
This should fix load failure of https://github.com/microsoft/pxt-jacdac-services in web editor
=> Fix for classes in backward order compiled in test mode

pxtcompiler/emitter/service.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/2071
We hadn't implemented finding the current call expression and current argument for signature help in Typescript using our own language service, so I fixed that and did a little refactoring as well.
After:
And a bonus fix for an unfiled bug.
Before:
After:
=> Fix signature help for Typescript

pxtcompiler/emitter/service.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/2070
Fixes the way we were sorting completion symbols that match the type of the current parameter. Also deprioritized keywords by default since we only have them in the completion list so that we don't accidently auto complete a symbol when someone types "if".
After:
=> Auto-complete: Rank symbols matching current parameter type higher; rank keywords lower

package.json
bumping pxt-blockly to include a fix to my recent changes to that repo.
Looks like the pxt-blockly npm package is automatically published for new tags, cool!
=> bump pxt-blockly

libs/pxt-common/pxt-core.d.ts
Before this change the following code would pass the type checker:
```typescript
const foobar = 1
foobar()
```
This was problematic because people were using `sprite.x()` or something, which would kind of work, except the return type would be `any`.
Note that this may break existing scripts, but I would rather take it and have people fix the scripts. The current behavior is non-standard, confusing, and bug-prone.
Fixes https://github.com/microsoft/pxt-arcade/issues/2019
=> Objects should not be assignable to Function type

pxtblocks/blocklycompiler.ts, pxtlib/jsoutput.ts
Matches line breaks for function calls (breaks based on block shape)
For https://github.com/microsoft/pxt-arcade/issues/2143
=> Line break arrays if blocks have external inputs

webapp/src/app.tsx
We don't collect that actual size of the document in our analytics; so we don't know how much space is lost with toolbars, etc...
=> collect client size

theme/image-editor/imageCanvas.less, webapp/src/components/ImageEditor/ImageCanvas.tsx
closes microsoft/pxt-arcade#2093
This PR adds shortcuts for the following actions in the sprite/tile/background image editor:
* `Cmd-A`/`Ctrl-A`: Select all
* `Esc`: Cancel selection
* `Backspace`/`Delete`: Delete selection
=> Add select all, delete, and cancel selection to sprite editor

pxtlib/cpp.ts
should fix (important part of) https://github.com/microsoft/pxt-arcade/issues/2127 -- the sha was changing because the package's dependencies would change the topo sort order of the files, even though the set of c++ files wasn't changing. Michal mentioned the order doesn't really matter for these c++ / that making alphabetical is fine. (I'll see about fixing the message in a separate PR)
Tested with a trivial arcade program and it worked (&& worked when reversing the sort order as well, so should be good)
=> alpha-sort deps for c++ compilation to avoid missing valid hex files

pxtcompiler/emitter/service.ts
fixes https://github.com/microsoft/pxt-arcade/issues/2078
Two issues:
1. I'm a Javascript beginner, so lemme know if there are better ways to check for all these cases. 
2. Also I only tested for the sprite.say string changes. Are there other blocks I should test with?
=> Try to parse 'any' values when emitting snippets

webapp/src/app.tsx
fix https://github.com/microsoft/pxt-arcade/issues/2127 (the other error re: not getting the right hex file was fixed in https://github.com/microsoft/pxt/pull/7320)
Propagate the error message from https://github.com/microsoft/pxt/blob/master/pxtcompiler/emitter/emitter.ts#L967 in the toast
=> Show 'hex file is not available' error when offline

pxtlib/emitter/cloud.ts
fix https://github.com/microsoft/pxt-arcade/issues/2155
was waiting on arcade build so I figured I'd fix this one, didn't realize till after that it was assigned, oops
=> fix importing share url for stable versions (v0, v1, ...)

localtypings/pxtarget.d.ts, pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts, webapp/src/gitjson.tsx
Sample magic PNG:
Build: https://arcade.makecode.com/app/bc01e1b035506c04dd75e400027dce02bf91ea4e-d1be7e138a
Same as before, right-click -> Snapshot to generate PNG, drag into editor to load snippet
=> Remove save icon on snapshot PNGs

pxtblocks/blocklycompiler.ts
Fixes TS image literal indentation https://github.com/microsoft/pxt-arcade/issues/2143
=> Set canIndentInside to true for multiline arguments

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_tilemap.ts
Reduce vertical padding around img blocks back down to what it is on live site:
live site:
/beta:
after this change:
Not certain why this behavior changed; this code hasn't changed for ~2 years, so it seems like it must have been being compressed vertically in blockly and that got changed with the new renderer? I could look around if we want, but maybe after release
=> bring image blocks size back down to normal (reduce vert padding)

pxtcompiler/emitter/service.ts, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2177
Fixes completions for properties, also adds back in the "(method)", "(property)" preview text in the autocomplete list--easy to remove if it seems cluttered but it felt helpful to me.
=> Only add parenthesis to method and function snippets

pxtcompiler/emitter/emitter.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2190
I'm not sure how this got out of sync, but for some reason the emit order sometimes changes on the program. Make sure main.ts is always last.
=> Fix emit order

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2167
Fixes https://github.com/microsoft/pxt-arcade/issues/2176
Python is pulling from the virtual file system, so it's compiling the last saved version instead of what is currently in the editor. This forces a sync before running py->ts and saving. Swapping the order of the calls to setContentAsync and saveTypeScriptAsync in "saveFileAsync" also works, but I think this is the less intrusive fix... I didn't want to mess up anything with the saveFileAsync code.
=> Update virtual python file before typecheck

pxtblocks/fields/field_sprite.ts, pxtcompiler/emitter/service.ts, pxtlib/spriteutils.ts
Resolves https://github.com/microsoft/pxt-arcade/issues/2169
With this change, when the user types or drags `scene.setBackgroundImage(...`, it creates an image literal the same dimensions as the screen.
**Rough edge**: The resulting snippet is 120-ish lines long, _and isn't automatically collapsed after being inserted_. Which is kind of bad. One fix would be to make snippets optionally foldable, perhaps parameterized from a block comment. That might be a lot of additional code, and seems separate from this change.
Tested with JS and PY.
=> setBackgroundImage snippet improvements

webapp/src/compiler.ts
re: https://github.com/microsoft/pxt-arcade/pull/2197, this fixes blocks upgrades when there's a tilemap.
The issue was that the blocks compile was generating `main.ts` as if `tilemap.g.ts` exists, so it didn't have the namespace at the top. This adds on to the blocks patch logic to copy over the generated files to the patch when we're validating that it creates an okay program. 
This feels like potentially a bit too much tilemap specific logic in the upgrade logic, but not sure where a better fix would be.
=> Fix blocks upgrades with tilemaps

webapp/src/app.tsx, webapp/src/srceditor.tsx
fix https://github.com/microsoft/pxt-arcade/issues/2211
Add back in toast when we get a runtime error. This got dropped when adding support for runtime errors to error list ([here](https://github.com/microsoft/pxt/pull/7048/files#diff-325ec83a257a791d33bd4484fd67fb24R784)); this adds it in as the default behavior for the method that gets overwritten to propagate to the error list, so that it shows the error as a toast when the editor doesn't have error list support.
=> fix runtime error toast

pxtlib/diff.ts, webapp/src/compiler.ts, webapp/src/workspace.ts
re: https://github.com/microsoft/pxt-arcade/pull/2197 not upgrading scripts imported from github
The issue is that we don't store any editor version info in the github repo, and instead just make it apply the current version, so none of the upgrade rules were applying when importing a github script. (Previously loaded ones are fine)
Unfortunately, I don't think there's actually a way to fix this one for the current release, as the information just isn't there; we can't safely pretend like the script is from `0.0.0` and run all the upgrade rules because they don't necessarily work when reapplied (e.g. SpriteKind upgrade rule would break new scripts, etc). This change should make it work for the future as it makes the version number available in pxt.json
if we want to hack in a fix for any …
=> github integration: include version info in pxt.json and use it on import

pxtblocks/blocklyimporter.ts
fix https://github.com/microsoft/pxt-arcade/issues/2173, again
Looks like my branch of pxt was a few commits behind master, so I didn't run into this bug until after everything was merged / beta was bumped. It was still failing to upgrade https://github.com/jwunderl/garden-crop-duster because of this pesky little guy:
notice parameters is null. No reason to fail hard here, we bail out whenever any other value in this function is falsey anyways.
I'm not sure if there are other places where we'd care if .parameters was null / if this is potentially indicative of another bug? I'll look into what caused that, maybe the object assignability fix?
As a side note, it would probably be nice to turn off the last parameter here:
https://github.com/microsoft/pxt/blob/master/webapp/src/compiler.ts#L717 …
=> blocks upgrades: don't crash when symbol.params is null

cli/cli.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/2164
Try yourself here: https://arcade.makecode.com/app/8e0b07b65f911e8dd2a4c14352fe7d87a7c8b56f-8c8b963622#editor
The API cache was including symbols from test.ts files and those symbols were sometimes conflicting with the user's program. The problem was revealed (but not introduced) by: https://github.com/microsoft/pxt/pull/6568 when we actually started checking for collisions between library top-level variables and user variables.
This PR has a targeted fix, but many issues still remain:
1. Even if test symbols are included, the user blocks program should correctly rename conflicting symbols
2. When gathering cached API info, the compiler is keeping around API info state from earlier compiles that might have conflicting build …
=> Don't include symbols from test files in the API cache

webapp/src/app.tsx
Build: https://arcade.makecode.com/app/d4b73124891dd52e049a7878a777f5ef8fc8a13c-0b1a4ef7af
Fixes https://github.com/microsoft/pxt-arcade/issues/2237
Tested general saving, compile in ts/py, intellisense, error display in python--would love extra eyes though!
=> Mark simulator dirty when setting file content

localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
Match previous behavior of "open in editor" text without specifying language. Since forum games are just a share URL, we don't know what language they're in, and this saves us the effort of having to manually check every game.
(Still eventually want to move the extra "open in editor" card to the otherActions field but that change touches more places and requires updating the discourse download script to output the updated format)
Fixes https://github.com/microsoft/pxt-arcade/issues/2229
Also a build: https://arcade.makecode.com/app/52c89c868dd520e607c5abb60364871a26703ea0-6e76a989ff
=> Remove 'Blocks' text for forumUrl card, use pencil icon

docfiles/pxtweb/cookieCompliance.ts, pxtcompiler/emitter/service.ts, tests/language-service/cases/completions_keywords.ts, tests/language-service/languageservicerunner.ts, webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-arcade/issues/2239
Perf improvements:
1. Global symbols pre-filter
When we don't have a specific  set of symbols to return like for member completion, we would return all PXT APIs and allow Monaco to fuzzy filter and sort based on the users input text. However this means we're generating snippets and doing other processing for potentially hundreds or thousands of APIs. So instead we now filter these global symbols to only those who partially match what the user has already entered.
2. Add snippets late
When returning completion results, wait to generate and add completion snippets until all other filtering is done
3. Enforce a total max number of symbols
TODO:
=> performance improvements for intellisense

pxtlib/github.ts
The API to enable pages in github changed slightly breaking the github integration. This fixes it.
https://developer.github.com/v3/repos/pages/#enable-a-pages-site
* catch and report any failure of the api, ignore result
=> handle changes in github apis

pxtlib/github.ts, pxtlib/semver.ts, webapp/src/gitjson.tsx, webapp/src/workspace.ts
Fix for https://github.com/microsoft/pxt-arcade/issues/2288
The min github upgrade rule is too picky about semver parsing and throws when a tag is not provided. Making parsing more resilient to missing tag.
Note: only affects pxt-tilemap, arcade-sprite-data + there is a workaround.
=> github: fix min upgrade rule

pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/ir.ts, pxtlib/cpp.ts, tests/compile-test/lang-test0/22lambdas.ts, tests/compile-test/lang-test0/27accessors.ts
Mostly port of https://github.com/microsoft/pxt/pull/6299 for VM
* there is one aspect still missing - getters that return lambdas cannot be called directly (see comment in `27accessors.ts`); this is somewhat esoteric though
* also disable whitespace squeeze since the cloud compile limit is now higher
=> make VM work again

webapp/src/app.tsx
repro:
* create new project
* switch to TS
* remove README.md
* go back to home
* re-open project
* hang!
Similarly, will hang when opening published projects without readme.
@abchatra this seem to warrant point-fix
=> Fix crash when opening packages with no readme

pxtlib/spriteutils.ts
re: https://github.com/microsoft/pxt-arcade/pull/2299
When emitting images, only add space between characters when image is 'small'; I arbitrarily set it at 300pixels so that 16x16 and slightly larger still get the spaced out format, but not larger images like 32x32 or 160x120.
Beyond not upsetting the word count on crowdin, it seems like it'll be helpful for file sizes when sharing a project / avoiding hitting size limits due to multiple backgrounds - right now I think it's sending an extra 38400 white space characters per background image (120 * 160 * 2 as it'd be in both the blocks and ts file). Also a bit easier to deal with in the editor, as right now adding a background image makes the max line length ~~ 4 screens wide for my laptop which makes navigating a bit harder.
=> trim padding when emitting large images

common-docs/github/pages.md, localtypings/pxtpackage.d.ts, webapp/src/workspace.ts
Flag to disable overriding the generated HTML in github projects.
=> adding settings to disable target template files

pxtlib/github.ts
We fail to import any github url if it has a trailing / . Filtering it out in the parsing process.
=> clean out trailing dash from github url

webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx
@riknoll @livcheerful 
Here's a fix for microsoft/pxt-arcade#2317. I hadn't realized that when editing an individual tile, there were _two_ `ImageCanvas`es being rendered! 😱 😅
I'm also **totally** happy for you to independently solve this one, if you'd prefer.
I haven't actually done much with Redux... perhaps it's unusual to directly pass props to components like I do in ImageEditor line 87.
=> Suppress tilemap shortcut handling when editing a tile.

webapp/src/components/ImageEditor/ImageCanvas.tsx
closes microsoft/pxt-arcade#1561
Enables arrow keys for moving the selection. Movement is capped to "just offscreen" in each direction (I tried to demonstrate this in the gif; not sure if you can tell that's what's going on).
=> Add support for arrow key selection movement in sprite/tilemap/background editor.

pxtblocks/composablemutations.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/1937
We need to re-apply all styles (fill, stroke, etc) when we add a new field to the block
=> Re-initialize block SVG after adding dropdown

theme/errorList.less, theme/themes/pxt/globals/site.variables
fix https://github.com/microsoft/pxt-minecraft/issues/1918, but there's a minor diff in styling for other editors I'll add a note on below; can maintain the same behavior but it'd require a bit of duplication / an extra less var defined for each editor
w/ highlight on error:
=> fix error list colors in inverted-editor

pxtblocks/fields/field_tilemap.ts, pxtblocks/fields/field_tileset.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/legacyTilemap.ts, webapp/src/components/ImageEditor/Alert.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2311 (this is also the issue that Andy's students hit). This issue was caused by creating a tile, editing it, deleting it, and creating a new tile. The deleted tile caused an exception when encoding the tilemap.
Fixes https://github.com/microsoft/pxt-arcade/issues/2315. This issue was an off by one error that I fixed for the parsing of tilemaps (but not the legacy parsing).
Fixes https://github.com/microsoft/pxt-arcade/issues/2281. This issue was caused by the tileset cache being created while the workspace was being loaded. Fixed by invalidating the cache when we detect that something is wrong at render time
=> Tilemap woes and the solutions thereof

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, tests/tutorial-test/baselines/activities.json, tests/tutorial-test/baselines/button.json, tests/tutorial-test/baselines/description.json, tests/tutorial-test/baselines/diff.json, tests/tutorial-test/baselines/explicitHints.json, tests/tutorial-test/baselines/flyoutOnly.json, tests/tutorial-test/baselines/ghost.json, tests/tutorial-test/baselines/hideIteration.json, tests/tutorial-test/baselines/legacySteps.json, tests/tutorial-test/baselines/python.json, tests/tutorial-test/baselines/singleStep.json, tests/tutorial-test/baselines/steps.json, tests/tutorial-test/baselines/template.json, tests/tutorial-test/baselines/tutorialCompleted.json, tests/tutorial-test/cases/python.md, webapp/src/compiler.ts, webapp/src/tutorial.tsx
Main changes: instead of concatenating the code when we parse the tutorial, save an array of snippets. When decompiling to get the used blocks, TS behavior is unchanged (concat snippets, decompile). For Python, each snippet is put in a separate module (file) to convert to TS, then we strip out the "namespace" declarations generated from the modules, concatenate the snippets and decompile.
Long-term, it could be useful to precompute or cache the used blocks; this data only really changes when the tutorial content changes so we probably don't need to generate it every time a tutorial is loaded.
Fixes https://github.com/microsoft/pxt-minecraft/issues/1926
=> Pass tutorial snippets as array, isolate python snippets in modules

theme/monaco.less, webapp/src/monaco.tsx, webapp/src/monacoFieldEditorHost.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2265
Implementing the quick-fix proposed by @soniakandah in https://github.com/microsoft/pxt-arcade/issues/2265
The gutter icon bobs on the selected line:
=> Adding bobbing animation to gutter icons on selected line

pxtblocks/blocklyloader.ts
fix https://github.com/microsoft/pxt-minecraft/issues/1911
I guess minor question, is there value in it specifying duplicate *comment*? Could just use the same duplicate as we use for DUPLICATE_BLOCK if we want, but maybe specifying it is a comment is valuable for students.
=> Allow duplicate comment to be translated

common-docs/browsers/technical.md, common-docs/javascript/interfaces.md, common-docs/javascript/sts.md, docs/packages/getting-started.md
A few typos found by Crowdin translators.
=> Fix some typos in the v0 docs

pxtblocks/fields/field_tilemap.ts, pxteditor/monaco-fields/field_tilemap.ts, webapp/src/components/ImageEditor/Dropdown.tsx, webapp/src/components/ImageEditor/tilemap/TilePalette.tsx
This fixes a long-standing regression where we lost the ability to use different widths for tilemap tiles when we shipped the new tilemap editor. This PR has no UI changes, it just adds a field option to the tilemap field that lets you give an alternate tilewidth (8, 16, or 32). This way we can ship an extension that adds blocks for 8x8 and 32x32 tiles.
Also adds a way to do it in Monaco, but it isn't the prettiest. Basically, you can type `tilemap8`, `tilemap16`, or `tilemap32` when creating a tilemap and this will hint to the editor that it should create a tilemap with that tile width. If a tilemap with the same name already exists, then it will ignore the tile width and just open the existing one. I have a PR upcoming for common packages that adds those alternate APIs.
=> Support multiple tilewidths for tilemaps

pxtblocks/fields/field_tilemap.ts, pxtblocks/fields/field_tileset.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/tilemap.ts
Minor fix for a bug I found after merging this PR: https://github.com/microsoft/pxt/pull/7388
This fixes the tileset picker to include all project tiles and makes it so that the different transparency sizes are visually different.
=> Minor tileset fixes for different tile sizes

webapp/src/app.tsx, webapp/src/package.ts
so we can see where compilations / typechecks are coming from
the `typecheck.complete` tick would get sent a lot, as it triggers every run / every time we need to update typings for monaco, but it seems useful for knowing accurately how often each language is being used.
=> Add preferred editor to compile tick && typecheck tick

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/tutorial.tsx
- Database class based off the api info and translations DBs
- Hashes the code snippets and invalidates the blocks based on those--I think this should functionally sync up with invalidating when the cached markdown invalidates/changes
- Next steps are to get the list of used blocks at build time (like the api info) to also speed up the first load
Build: https://minecraft.makecode.com/app/29d4f5abb6b4e1d67b538a9ed500175b4b1eaa18-87b91c9b85
You can compare with beta or just compare first load vs subsequent loads
=> Cache tutorial usedBlocks in IndexedDb

webapp/src/gitjson.tsx
Do we want to add events so we can complete the quiz? We have a tick for when users click the commit button, but nothing to see if the commit was successful.
=> Add tick event for successful github commit

docs/writing-docs/tutorials.md, localtypings/pxtarget.d.ts, pxtblocks/fields/field_tilemap.ts, pxtlib/package.ts, pxtlib/tilemap.ts, pxtlib/tutorial.ts, webapp/src/app.tsx
Part of a fix for https://github.com/microsoft/pxt-arcade/issues/2250
You can add tilemaps and custom tiles to a tutorial by using a `jres` snippet. Just copy/paste the contents of `tilemap.g.jres` (no need to copy `tilemap.g.ts`). The tiles will also show up in the user project if they are custom.
=> support for jres snippets in tutorials

webapp/src/components/ImageEditor/ImageCanvas.tsx
fix https://github.com/microsoft/pxt-arcade/issues/2343, no more emptiness / all red tile
Maybe should do move https://github.com/microsoft/pxt/blob/master/webapp/src/components/ImageEditor/toolDefinitions.ts#L170-L178 to a general state to layer index helper? Not sure it's necessary quite yet.
=> fix preview for drawing walls

pxteditor/monaco-fields/field_tilemap.ts, webapp/src/blocklyFieldView.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/TilemapFieldEditor.tsx
When you're editing a tile and click outside the editor area, just close / commit tile editor, don't destroy your progress :(
=> don't lose tilemap when clicking outside tile editor

pxtlib/spriteutils.ts
When computing average color, ignore transparent pixels / don't count them as black. e.g. for https://makecode.com/_5yMWc3WTWEyL
Right now if you have a tile that isn't completely colored in (e.g. a sign or a flag) the preview color in the minimap gets darkened a lot / almost completely. (This one's annoying for me as I usually set the background color to green or tan and draw smaller tiles, and then my tilemap preview is all black 😢)
instead of all gunky colors in the top left:
shows up as the actual colors in the tiles:
=> only count non-transparency when computing average color

theme/image-editor/imageEditor.less, theme/image-editor/pivot.less, theme/image-editor/sideBar.less, theme/image-editor/toggle.less, webapp/src/components/ImageEditor/BottomBar.tsx, webapp/src/components/ImageEditor/Button.tsx, webapp/src/components/ImageEditor/Dropdown.tsx, webapp/src/components/ImageEditor/Pivot.tsx
* make the `my tiles` and `gallery` toggles feel like buttons; no select on text, pointer is hand instead of text select
* tab accessible for the buttons where it's simple to add - definitely a lot more work to make it fully accessible, but this has a nice side benefit when e.g. tabbing through image size and not ending up with the accessibility menu right away
=> few fixes for simple tab indices / visual issues in tilemap editor

theme/common.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/1939
=> Hide checkmark for tablet/mobile editor language dropdown

docs/static/streamer/script.js, docs/static/streamer/streamer.ts
720p standard is 1280x720 (16:9) not 1080x720 (3:2)
Google search:
=> Fix 720p size to correct 1280x720 standard

package.json
- Don't allow renaming functions to a blank string (https://github.com/microsoft/pxt-blockly/pull/320)
=> Bump pxt-blockly to 3.0.21

pxtlib/service.ts
re: https://github.com/microsoft/pxt-microbit/issues/3351 and a ton of equivalent errors throughout all targets; when a user translates a block, it's really easy to accidentally break the block. This can be done by change parameter order (with % params), changing a shadow value, dropping a parameter, etc -- in the linked issue it was translating the shadow block from `device_arrow` to `devise_arrow`. This changes makes `localizeApisAsync` ignore translations when the blocks parameters get broken
The code was there to try and check it, but it was basically a noop; `ps` and `locps` were always equal because `pxt.blocks.compileInfo` uses the `._def` that is built and attached to the function's attributes by `updateBlockInfo`, which wasn't run until after the comparison.
Worth noting I left …
=> Check block translations have equivalent parameters

docfiles/offline-app-body.html, docfiles/offline-app-head.html, docfiles/offline-app-trademarks.html, theme/docs.less
align offline app page with docs styling, and clean up a bit of unused imports / rules / etc.
current state is https://arcade.makecode.com/offline-app ; if you want to see what it looks like when expanded need to open console and run:
```javascript
showAgree(); document.querySelector("#no-download-segment").remove();
```
~worth a note I left the generated css / html for the legal stuff  the same for now.~ last two commits update to current legal text; probably easiest to compare https://github.com/microsoft/pxt/pull/7398/files/a7f1279255aa091f83718926bd47975e7d63347e for the main primarily non-generated diffs
Doesn't currently change microbit as that has it's own page set / doesn't use these rules yet https://github.com/microsoft/pxt-microbit/blob/master/docs/offline-app.html (same with …
=> Offline app page updates

webapp/src/projects.tsx
Disable the `open in editor` button re: https://github.com/microsoft/pxt-arcade/issues/2346, until the settings are fixed.
=> disable forum 'open in editor' in electron app due to CORS issue

common-docs/reference/arrays/insert-at.md
Update the reference page for **Array.insertAt()** to include the missing parameter description for **value**.
RE: https://crowdin.com/translate/kindscript/1934/en-ru#q=71774
=> Add missing parm description for 'insertAt()'

cli/cli.ts
fix build https://travis-ci.org/github/microsoft/pxt-arcade/builds/720834034
Issue was that tutorial.code changed from string->array<string> in https://github.com/microsoft/pxt/pull/7382/files#diff-87390c8316b0230db07feb98ebca1fc0L5341, so the portion just above the cli change there was doing `array<string>.indexOf("namespace")` instead of `<string>.indexOf("namespace")` and never hitting the tutorial with namespace path
~still waiting on arcade checkdocs to pass locally (takes a while) in case there are any other issues, but this should be the fix.~ yup all works
(also change to show card name instead of gal.name, as gallery name doesn't give much info when there are tons of things in the category)
=> fix checkdocs for tutorials with namespaces

localtypings/pxtpackage.d.ts, pxtlib/cpp.ts, pxtlib/github.ts
Allow pxt.json to specify additional codal libraries to pull in
This requires codal build system 0.8.0 or later
=> Allow for pxt.json:codal.libraries

pxtcompiler/emitter/snippets.ts, webapp/src/components/ImageFieldEditor.tsx, webapp/src/monaco.tsx, webapp/src/monacoFieldEditorHost.ts, webapp/src/package.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2367
Fixes https://github.com/microsoft/pxt-arcade/issues/2368
Fixes https://github.com/microsoft/pxt-arcade/issues/2366
Fixes https://github.com/microsoft/pxt-arcade/issues/2363
Fixes https://github.com/microsoft/pxt-arcade/issues/2357
Also fixes a longstanding bug with the folding behavior where monaco folds image literals in such a way that it becomes impossible to enter a newline after them. 
For example, here is sprites.create in the current editor:
And here it is with these changes:
In the first picture you would need to unfold the code before you could add another line the document because pressing enter would just edit the image literal and cause it to fold again.
=> Several small arcade bug fixes

pxtrunner/runner.ts
Regression introduced by me in https://github.com/microsoft/pxt/pull/7405
TIL: the typescript compiler lets you specify extra properties in an object literal even if you cast it to an interface type.
=> Fix print code typo

pxtlib/emitter/cloud.ts, pxtlib/github.ts, webapp/src/app.tsx, webapp/src/projects.tsx, webapp/src/workspace.ts
fix https://github.com/microsoft/pxt-arcade/issues/2371; this tries to fetch the github dependencies of the file before installing the header. Happy to look for an alternative approach if this feels wrong, but it seems okay to me as we'll need to fetch those dependencies for the project to actually load any way, and it shouldn't take any longer as the extensions get cached locally during `downloadPackageAsync`
And a few related fixes; quit the loading screen and return home with an error message if you try and load an old project and something prevents the header from being loaded (the second part of that issue), as well as a toast for when it fails to load an example (we didn't run into this in microbit as there are only a few non tutorial/project examples, and none of them had …
=> Confirm github dependencies available before loading packages

webapp/src/compiler.ts
fix issue with api caching of external packages that causes https://minecraft.makecode.com/?ipc=1&inGame=1&noRunOnX=1#tutorial:github:fountainstudios/AIMakecodeMarkdown/testAI to succeed in loading the first time, but fail on any future loads.
Usually a `pkg.EditorPackage`'s `.getPkgId()` is equal to it's configs name, but when https://github.com/fountainstudios/AIMakecodeMarkdown/blob/master/testAI.md loads in https://github.com/fountainstudios/AICustomBlocks, it gives it a name to reference locally (the = part at the beginning / `AIBlocks`) which gets set as it's ID.
When the compiler runs and builds the api info, it attaches the `getPkgId` as the api's `.pkg`, but when we cache that api info we do it based off the config's name. In the section changed in this pr, when the external …
=> fix caching for packages given an alias in md

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/browserutils.ts, webapp/src/tutorial.tsx
- Separate CLI command for collecting blockIds, run on an allowlist of directories specified in pxtarget.json (eg ["hour-of-code", "tutorials"])
- Key on a hash of the tutorial code, pxt version, and target version--only use prebuilt blocks if the hash matches
- Used blocks saved in target.json
=> CLI command for collecting block ids used in tutorial markdown

webapp/src/components/ImageEditor/toolDefinitions.ts
Adjusts fill to be based on a computed value that includes data from the `activeLayer` in addition to the pixel value from the `image` layer.
fixes microsoft/pxt-arcade#2374
=> Consider activeLayer data in addition to image data when filling

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2138
The sequence of events when we load a blocks example looks something like this:
1. Create a project for the example (w/ `main.ts` but not `main.blocks`)
2. Load the Blockly editor
3. Decompile the `main.ts` file to get the `main.blocks` for the new project
4. Load the new `main.blocks` into the workspace
We need to do these things in this order because we rely on the blocks info created in step 2 to do the decompile in step 3.
However, on slow machines there is a chance that between step 2 and step 3 our autosave handler will run. When that happens the current code in the Blockly workspace (which is empty) is compiled and saved over the `main.ts` turning `main.ts` into an empty file. Then when we get to step 3, we decompile that …
=> Fix issue where examples loaded empty workspaces on slow computers

pxtlib/package.ts
This happens during CLI builds
=> appTarget.versions is undefined before target.json is built

pxtlib/emitter/cloud.ts
re: https://github.com/microsoft/pxt/pull/7430
A bit more of a refactor of markdownAsync so it's a hopefully bit easier to follow. The nested promises / etc make it a bit dense currently in my opinion.
=> refactor pxt.Cloud.markdownAsync

webapp/src/components/ImageEditor/store/imageReducer.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2381
This one goes out to @jwunderl
=> Select new tile as foreground when editor closes

theme/blockly-core.less
Fixes https://github.com/microsoft/pxt-arcade/issues/2388
=> Fix overflow issue when scrolling blockly dropdowns

webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2390
When we open a project today we calculate the minimum x and minimum y of each block and center the workspace on that point. That usually works well unless you have your project laid out something like this:
In that case there is a big empty space in the top left so the editor gets centered on nothing and it looks like the workspace is empty.
This changes that behavior so that we now align on whatever block is closest to the origin of the workspace.
=> open workspace on whichever block is closest to the origin

webapp/src/toolbox.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2386
=> Stop toolbox from stealing focus from active dialogs

docs/extensions/github-authoring.md, localtypings/pxtarget.d.ts, pxtlib/browserutils.ts, pxtlib/main.ts, pxtlib/tutorial.ts, theme/themes/pxt/modules/checkbox.overrides, theme/themes/pxt/modules/modal.overrides, webapp/src/app.tsx, webapp/src/gitjson.tsx, webapp/src/tutorial.tsx, webapp/src/workspace.ts
- Adds an "Optimize for tutorials" checkbox to the "Create a release" dialog on the Github page
- If this box is checked, goes through each .md file and computes used blocks + hash of code, saves into `tutorial-info-cache.json`
- On loading a Github tutorial, checks for cached json, loads into IndexedDB--this only loads the cached blocks for the file requested, in case a repository has many tutorials
- The tutorial load path will then check IndexedDb as usual, and if the hash of the code does not match it will recompute, ensuring that the toolbox is always synced even if the json is out of date
=> Add option for caching tutorial info when creating Github release

localtypings/pxtarget.d.ts, pxtcompiler/emitter/hexfile.ts
Integrate hex generation fix for calliope - ad2ee958b48a4eefcab6e3b370dc65eea378527a .
Calliope is in sync with the micro:bit release. This change requires a flag in pxttarget to do anything (no-op in microbit case)
=> Move hex eof [stable6.0]

pxtcompiler/emitter/languageservice.ts, tests/language-service/completion_cases/enum_constants.ts
- Filter completion symbols by parameter type (for call expressions) after adding local variables
- When filtering, enum members and enum constants have return type 'AnimalMob.Chicken', and we are checking against 'AnimalMob', so do some additional parsing
Fixes https://github.com/microsoft/pxt-minecraft/issues/1949
=> Custom completion filtering for enums and enum constants

pxtblocks/blocklyloader.ts, pxtrunner/renderer.ts
A few minor fixes api cards I noticed while testing https://github.com/microsoft/pxt-arcade/pull/2325
* Filter out deprecated, ~`shim=TD_ID`~, and blockAliasFor (e.g. the second version of array.pop as a statement)
* create code card for `.blockBuiltin` (only hits array.length and string.length I believe?)
* use `.blockNamespace` if it exists (make arrays, images, loops show up)
=> minor fixes for api cards

cli/cli.ts
=> Avoid github throttling in CI when caching used blocks

webapp/src/components/ImageEditor/BottomBar.tsx, webapp/src/components/ImageEditor/Button.tsx, webapp/src/components/ImageEditor/Pivot.tsx, webapp/src/components/ImageEditor/util.ts
fix https://github.com/microsoft/pxt-arcade/issues/2424; spacebar has a particular meaning in the image editor, so only fire the click events on enter, not spacebar; effectively the same as
https://github.com/microsoft/pxt/blob/ac96cba14b0198821d67df38e64d96e339ef5f11/webapp/src/sui.tsx#L49-L55
just dropping the spacebar click from triggering it.
=> only allow enter for image editor buttons, as space is overloaded.

pxtblocks/composablemutations.ts
Wrapping this domToBlock in a try-catch to make it safer. For some types of input (eg type="any") we don't have a valid default shadow block, so the correct behavior is just to bail out & leave an empty input.
Fixes https://github.com/microsoft/pxt-microbit/issues/3366
=> Error catching for shadow fields in expandable blocks

pxtrunner/runner.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2426
This adds upgrade rules to pxtembed (docs and share page) and also fixes a bug where package upgrades were not being applied. Package upgrades should have worked already but our host in pxtembed was ignoring all updates to pxt.json.
I can't really test the package upgrades locally because of a bug that prevents localhost serves from fetching targetconfig.json, which is where the package upgrades live. That being said I'm pretty sure this was the issue (I debugged it on the live site).
The ignoring config writes bit goes back to [five years ago](https://github.com/microsoft/pxt/commit/7533ecbf8726cbf5f2006a99232fbc63e0563043#diff-6cc6e6c354361d72c27d7b6b5861eea3R52) and was just there to make sure that config writes didn't cause an …
=> Apply upgrade rules on docs/share and don't ignore config writes

pxtcompiler/emitter/emitter.ts, theme/highcontrast.less, theme/themes/pxt/views/card.overrides
Here are some screenshots, but also, a target! https://minecraft.makecode.com/app/f16ee16d161060d22fb9d9005df5bce0b7f6fda8-783dcb27ba
I haven't tested the other targets to make sure they haven't changed from these edits yet, but I'll do that next. I'll do it for arcade, microbit, and LEGO, but lemme know if this list should be changed
It looks like that it's not possible to have a HC change for the field editors yet/it would need more work than just CSS changes? Tell me if this is wrong :D or if there's a field editor where it's been done before so I can take a look
the corresponding pxt-minecraft PR: https://github.com/microsoft/pxt-minecraft/pull/1992
Blocks:
Homepage:
Monaco:
=> Add high contrast rules for Minecraft/inverted toolbox

cli/cli.ts, cli/crowdin.ts, docs/cli/staticpkg.md
When building a staticpkg, allow user to specify a directory to act as the source of translations, instead of fetching translations from crowdin. Directory needs to have the same set up as our crowdin, i.e. the files should be found like
```
{locs-src}/{lang id}/target-strings.json
{locs-src}/{lang id}/sim-strings.json
{locs-src}/{lang id}/{package id}-strings.json
{locs-src}/{lang id}/{package id}-jsdoc-strings.json
```
I had to split up `downloadTargetTranslations` quite a bit to add the right hook in, so it ended up being easier to asyncify it and separate it out a bit. Ran test builds of arcade electron app with both downloaded translations from `locs` and prebuilt translations from `locs-src` and both worked ~
=> allow using local translations when building staticpkg

pxtcompiler/emitter/service.ts
This change https://github.com/microsoft/pxt/commit/fc8fd4a0feea14cb82401f02bd2f857eb9dee585 exports the Fuse symbols, which creates a dependency on fuse typings. It breaks editor as the pxtcompiler.d.ts now tries to load fuse.d.ts.
Fuse is an internal implementation details and should not be exported.
=> don't export Fuse objects

docs/github-classroom-redirect.html, docs/github-explorer.html, webapp/src/cloudsync.ts, webapp/src/githubprovider.tsx, webapp/src/gitjson.tsx, webapp/src/onedrive.ts
Adds a ``remember me`` checkbox to github login dialogs. Remember me in formation is used to decide to store the token in localstorage or not.
When a user checks ``remember me``, we store the OAuth ``state`` in a new localstorage key, ``oauthRememberState`` when starting the login flow. After redirecting from the OAuth, we check if the ``state`` matches the ``oauthRememberState`` key to determine if ``remember me`` was selected.
Notes:
It's unclear if the onedrive/google auth path are still working with this since they are mostly dead code/untestable.
=> Rembember me

pxtlib/main.ts, webapp/src/app.tsx, webapp/src/compiler.ts
re: last portion of message in https://github.com/microsoft/pxt/pull/7427 and discussion last friday
**[edit]** + a quick fix along the same code path for extension caching when we add in extra built files, like tilemap of code start.
After looking through stuff a bit more I think this is the right way to handle things. I don't think this necessarily needs to go into this release, as it hasn't been run into in arcade yet / is a pretty subtle case
quick context on all the relevant fields;
* `SymbolInfo.pkg` is the package that the api came from. this gets picked from the symbol info we get out of the ts compiler base off the name of the folder the symbol is found in https://github.com/microsoft/pxt/blob/7589ccebd32df24e1cb7ceb8e620eb4e617ab55c/pxtcompiler/emitter/service.ts#L218-L225
* …
=> clean up config.name vs pkg id in package api caching

theme/common.less, theme/monaco.less
fix https://github.com/microsoft/pxt-minecraft/issues/1756 -- the ipad 'show keyboard' button shows up behind editor tools / sometimes mobile sim. Worth noting we already have it in the correct position on some versions of ios due to 
https://github.com/microsoft/pxt/blob/c6531e3fb05a6521cddd0607c1dfa6eafa4fa1cd/webapp/src/monaco.tsx#L2115 but the built in one is the one that we can't easily reposition / the linked code is throw away code next time we update monaco most likely anyways. vscodes top position just places it at 0 anyways: https://github.com/microsoft/vscode/blob/2cb96e9c7a9ad82b9649ea6f3508cd224d64de75/src/vs/editor/browser/viewParts/overlayWidgets/overlayWidgets.ts#L130
also fix positioning issue with the transparent editor tools, just using the positioning variable I added …
=> Minecaft monaco css fixes

libs/pxt-common/pxt-core.d.ts
Add the missing help path for **String.isEmpty()**.
=> Set help path for 'isEmpty()'

pxtcompiler/emitter/languageservice.ts, pxtlib/service.ts, webapp/src/compiler.ts, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/1990
Issue here is the intellisense for call expressions requires our annotated TS AST, which wasn't being computed for Python. I added an additional compile (after the py2ts) to fill in this info.
Fixes https://github.com/microsoft/pxt-minecraft/issues/1989
This is because getCompletions is only called when intellisense initially pops up, and subsequent keystrokes just filter the existing list (eg if you type "PRI" quickly and wait, you'll see "PRIMED_TNT", but if you type "P", wait, then add "RI" you will not). PRIMED_TNT isn't in the initial list because it's a "ProjectileMob" and mobs.spawn is preferencing AnimalMobs. Adding `incomplete: true` will recompute the completions each time.
I also updated our pre-monaco completion …
=> Compute TS AST for Python completions, remove completion list truncation

libs/pxt-common/pxt-core.d.ts
re: https://github.com/microsoft/pxt-microbit/issues/2395#issuecomment-698446759
I had added trim as a side effect when fixing parseInt, and in one of the commits we dropped the block for trim, and I accidentally cut the helper annotation too (which says which function is used to implement this method). Quarter for the 'forgot to call the function' jar!
actual implementation is here:
https://github.com/microsoft/pxt/blob/b587c496504c846d86cd52299b878137465dfceb/libs/pxt-common/pxt-helpers.ts#L469-L479
=> fix string.trim

pxtcompiler/emitter/languageservice.ts
I think the symbol aliases are only used for these enum constants right now but I'm checking the symbol type anyway in case we want to use them for anything else later. Could cause problems later if we decided we wanted to do something like assign "AnimalMob.Turtle" as an alias for "AnimalMob.SeaTurtle"... not quite sure if that's a thing we intend to support with this alias property?
Fixes https://github.com/microsoft/pxt-minecraft/issues/2005
=> Don't use enum aliases for member completions

cli/cli.ts, pxtlib/initprj.ts
And make a PR removing them from the list if they are invalid
close https://github.com/microsoft/pxt-minecraft/issues/1951
Very similar to the one I added for the minecraft content repo, e.g. of the generated pr for that: https://github.com/Mojang/EducationContent/pull/14
made a quick test repo: https://github.com/jwunderl/test-pxt-gh-action-repo/blob/master/.github/workflows/cfg-check.yml but I have that using a separate file because the checkpkgcfg isn't available without this pr
Could limit to just main/master branch, but it works for others too / doesn't seem like there's a reason to wait till the failure is fully merged?
=> Add gh action for extensions to check files exists

pxtsim/simlib.ts
This adds simulator support for the new waveforms added in
https://github.com/microsoft/pxt-common-packages/pull/1177
See
https://forum.makecode.com/t/testing-modifications-to-the-sound-engine/3351
for context and example sound output.
=> Support new waveforms in simulator

libs/pxt-common/pxt-core.d.ts, libs/pxt-common/pxt-helpers.ts
fix https://github.com/microsoft/pxt-microbit/issues/3356
`param.defl` defines a default for the api, not just the block. The `eg: {default}` format for setting default values for blocks is a bit less obvious / more surprising behavior, but does what we want it to (set the default length for blocks without breaking effecting ts code).
Few other edge case bugs bugs too:
* substr: passing length null was getting treated as length 3 on hardware as null was getting coerced
* substr: passing length undefined explicitly was not equivalent to not passing a value (I suppose this might be considered a bug with defl itself as well?)
* slice: passing null gets treated as 0 in js, but was being treated as passing undefined
quick test case to show differences
```
game.consoleOverlay.setVisible(true) …
```
=> fix default length for string.substr

pxtsim/simlib.ts
To avoid confusion, refresh the comments copied from
pxt-common-packages's libs/mixer/melody.h. The sine waveform
no longer needs a lot of space after the merge of
https://github.com/microsoft/pxt-common-packages/pull/1178
=> Delete obsolete "remove it?" SW_SINE comment

pxtlib/util.ts, pxtrunner/runner.ts
Right now, when building a course using `--docs#book`, we fetch all pages at once; when this is done in a language other than english, this means we need to fetch translations for all those files (which is ~~ 40-50+ md files per course). This will result in some of the requests for updating translations getting rejected, and the user getting out of date / possibly no translations for random entries
testing this is a bit tedious as localhost 403s on `/api/md/arcade/courses/...` when trying to build the book locally, so here's a link to a course in a build: https://arcade.makecode.com/app/5be2b998acd9bb6b02c82e20bef342be8d2acc7a-841de5f31f--docs#book:/courses/csintro1/SUMMARY It doesn't appear to be significantly slower than it currently is, as a significant portion of the time is spent …
=> Don't request all files at once when building course book

localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, pxtlib/tutorial.ts, tests/tutorial-test/baselines/activities.json, tests/tutorial-test/baselines/ghost.json, tests/tutorial-test/baselines/legacyFlags.json, tests/tutorial-test/baselines/legacySteps.json, tests/tutorial-test/baselines/python.json, tests/tutorial-test/baselines/singleStep.json, tests/tutorial-test/baselines/steps.json, tests/tutorial-test/baselines/template.json, tests/tutorial-test/cases/activities.md, tests/tutorial-test/cases/ghost.md, tests/tutorial-test/cases/legacyFlags.md, tests/tutorial-test/cases/python.md, tests/tutorial-test/cases/singleStep.md, tests/tutorial-test/cases/steps.md, tests/tutorial-test/cases/template.md, webapp/src/app.tsx, webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2017
- `@unplugged` -> `@showdialog`
- `@fullscreen` -> `@showhint`
Also renaming it in the code to avoid confusion. Old flags will still work as before, just improving the naming for future content creators.
=> Rename 'unplugged' -> 'showdialog' and 'fullscreen' -> 'showhint'

docs/static/playground/samples/language/events/sample.js
Add example to the playground using handlerStatement to make an event you can put inline:
I also made it so each of the examples calls the handlers; something similar to that will need to show up in their block anyways, and someone who's new might not understand how to get the code to actually run / treating a function as a parameter might be non-obvious
This issue did stand out a bit https://github.com/microsoft/pxt-microbit/issues/3303 as it causes the blocks in the toolbox to be reversed from their definitions, which feels odd. I can take a look at what's going on unless we know where / why that happened?
=> add example of using handlerStatement to playground

cli/crowdin.ts, pxtlib/blocks.ts, pxtlib/service.ts
Right now we're getting a ton of errors from these that aren't easily investigated, as it's sending each block id as a separate property in the object, and sending the error in a lot of cases where we actually fix the block. 
two fixes for the errors:
* Send a tick event instead of an error when `normalizeBlock` has modified a block -- this isn't really an error case as we are theoretically fixing these with the replaces, so if it parses properly through the `hasEquivalentParameters` check below then in theory the block is fine / just trivia differences
* changing the shape of the error reporting - I believe these should be easier to investigate, as we can get all the info we need to find the errors from the target, version, & language id as that's enough to load in and view the errors in …
=> fixes for error reporting on block localizations

webapp/src/accessibility.tsx, webapp/src/app.tsx, webapp/src/carousel.tsx, webapp/src/components/ImageEditor/tilemap/TilePalette.tsx, webapp/src/container.tsx, webapp/src/extensions.tsx, webapp/src/filelist.tsx, webapp/src/hinttooltip.tsx, webapp/src/marked.tsx, webapp/src/projects.tsx, webapp/src/share.tsx, webapp/src/sui.tsx, webapp/src/toolbox.tsx, webapp/src/tutorial.tsx
Whenever you load a page on a dev build of react (localhost, uploadtrg), these flood the console with warnings that the methods aren't ideal. This makes it easy to miss other warnings / errors, and it's just not ideal to get used to ignoring warnings :). This should remove all but these two instances of the warning:
as those will require updating our version of `react-modal`, and there have been a number of minor bumps in that package since our current version / would require more testing, where this is just a quick renaming.
These are usually easy enough to fix to use other recommended apis, but generally that require a bit of context / more changes than just a rename, so I figured just swapping them over to start / acknowledge the warning was good.
Worth a note, the `UNSAFE_` prefix is …
=> use react@16.3 unsafe aliases for componentWill(Mount|ReceiveProps|Update)

webapp/src/app.tsx
Current approach is that "finishing" a recipe is the same as loading a new recipe into a project that already has a recipe open. When users are done with the entire chain of recipes, they would hit the "Finish" button which would be a different tick that represents being done with all the recipes in that progression path.
=> Tick event for 'exiting' a recipe

pxtsim/simdriver.ts, webapp/src/githubprovider.tsx
=> don't broadcast random messages to iframes + dev token fix

webapp/src/app.tsx, webapp/src/container.tsx
- `tutorial.start` will have `{ activity: ["tutorial"|"recipe"|"example"], path: "/tutorials/chase-the-pizza", editor: ["blocksprj"|"tsprj"|"pyprj"] }`
- `tutorial.shared` has the script id under "tutorial"
- `tutorial.faileddecompile` (not modified in this PR) has the tutorial name/path under "tutorialId"
@abchatra do we want the "tutorial id" dimension to have the same key in all of our ticks? not sure if it matters
=> Additional telemetry data for various tutorial ticks

webapp/src/app.tsx, webapp/src/blocks.tsx
If we hit an error while loading in the DOMContentLoaded event, right now we just infinite load in the home screen. These aren't necessarily recoverable -- e.g. the case this last came up in was a crash in the targets editor/extension.ts's `initExtensionsAsync` (https://github.com/microsoft/pxt-minecraft/pull/2031), and a failure there will mean editor specific behavior didn't get loaded / something is very wrong.
It uses the same one as when the main app fails to load, which pops this message and tries to refresh once in case the error was just random.
A few small fixes along the way, I'll add a few comments pointing at them
=> Don't infinite load when on error in loading path

pxtsim/runtime.ts
Instead of generating a new board id on each run, keep a stable number. The board id is used to infer the deviceSerialNumber and it reallys annoys JACDAC to have a new device each time MakeCode restarts the simulator.
=> keep stable id for board

pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_utils.ts, pxtlib/tilemap.ts, webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/assetEditor/assetGallery.tsx, webapp/src/components/assetEditor/assetGalleryTab.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/assetTopbar.tsx, webapp/src/components/assetEditor/editor.tsx, webapp/src/components/assetEditor/store/assetEditorReducer.ts
- Hook 'Edit' and 'Create' up to image/tilemap editor
- Add tilemaps to user assets, add preview image for tilemaps (minimap view/same as blocks)
- Add warning modal for delete, asset type selection modal for create
- Small tweak to asset displayName/id generation (strip trailing digits)
TODO:
- CSS pass
- Fix bugs
=>  Add 'Edit', 'Create' asset functionality, tilemap preview

pxtsim/simdriver.ts
This currently logs an error message on localhost as `new URL("/sim/simulator.html")` is invalid. No functional difference, just avoids an unnecessary error 
I suppose it could also just return before adding any of the _allowedOrigins on localhost since they are ignored here anyways https://github.com/microsoft/pxt/blob/981db6465023458f99506bf73be4cb57b8013c40/pxtsim/simdriver.ts#L626-L630 but that feels like a bug waiting to happen if someone wants to add something to the simdriver constructor in the future
edit: I suppose this also closes https://github.com/microsoft/pxt-microbit/issues/3410 now ~
=> don't log spurious sim url error on localhost

pxtsim/simdriver.ts
fix https://github.com/microsoft/pxt-arcade/issues/2459
fix https://github.com/microsoft/pxt-arcade/issues/2460
fix https://github.com/microsoft/pxt-microbit/issues/3413
fix mute button
mostly reverts the change in https://github.com/microsoft/pxt/pull/7509; that prevented sending any messages (besides broadcasts) to the simulator. I'm not sure I understand the case the PR said it was fixing, but it'll definitely need a narrower fix for those / if you want to give me a few examples I can see where to cull them @pelikhan
=> don't ignore sim msgs

webapp/src/db.ts, webapp/src/idbworkspace.ts, webapp/src/workspace.ts
re: https://github.com/microsoft/pxt-minecraft/issues/1936
closes https://github.com/microsoft/pxt-minecraft/issues/1893
Handful of fixes for idb workspaces (I awaitified it in the first commit as I was reading through all the code to make sure I had context on everything).
* If we fail to write in idb workspace, try again after clearing translation / tutorial info caches to clear up some room. This behavior is largely the same as https://github.com/microsoft/pxt/blob/76381d21d3f3574e7bd1bee1459e80af2dea9690/webapp/src/db.ts#L84
* If writing still fails, we're out of space / something is wrong and we can't continue to store stuff. bubble up the error to workspace `saveAsync`, and transition to using the in memory db so it at least works for the session / e.g. you can at least load …
=> fixes for idb workspaces

pxtlib/tilemap.ts, theme/asset-editor.less, webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/assetTopbar.tsx, webapp/src/components/assetEditor/store/assetEditorReducer.ts
Fixes:
- Update sidebar preview after asset edit
- Show asset id if displayName not present
- Default names for new assets
- Restore gallery header to regular image editor
- CSS for button colors, button spacing in modals, overflow for asset name
Todo: 
- CSS for toggle
- Fix/integrate with recent tile changes
=> CSS for asset editor, fix issues with naming

pxtlib/tilemap.ts, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/assetTopbar.tsx
- Previously the only way you could create a tile was from inside the tilemap editor, but now you could be editing a tile from the standalone image editor so I unified the getTile/getImage/getAnimation to return based on asset type
- When updating a tilemap, also iterate over all tiles in the tileset (user may have created new ones or edited existing ones)
- When editing a tile (standalone) also update in all tilemaps if the bitmap has changed
- Show all custom tiles in the tile palette when opening the tilemap editor
=> Fixes for tile creation/edit/update in asset editor view

pxtlib/tilemap.ts, webapp/src/components/assetEditor/assetSidebar.tsx
Trying to prevent any situation where a user could irreparably break their project from the asset editor. Assets cannot be deleted if they are used in any way (referenced in blocks, used in a tilemap, referenced in TS/Python).
=> Remove delete button when asset is referenced anywhere in project

theme/asset-editor.less, webapp/src/components/assetEditor/assetCardList.tsx, webapp/src/components/assetEditor/assetGallery.tsx, webapp/src/components/assetEditor/assetTopbar.tsx
Remove button from top bar, move all asset creation code into gallery component. This button only shows up in "My Assets" view for now, that can be changed after testing/usage if folks want.
=> Square 'Create New' button as first item in asset list

theme/common.less, webapp/src/container.tsx
Here it is in the full editor for normal projects and javascript/python only:
And it's hidden in sandbox
=> Fixing toggle css for asset editor

webapp/src/workspace.ts
We create this file so we always take the local version
=> Ignore merge conflicts in assets.json

pxtblocks/fields/field_asset.ts, pxteditor/monaco-fields/field_tilemap.ts, webapp/src/components/assetEditor/editor.tsx
One more late game fix! Pass used tiles into blockly/monaco/asseteditor ImageEditor so you can't delete them from inside the tilemap editor.
=> Pass referenced tiles into tilemap editor

webapp/src/tutorial.tsx
Add a state for the workspace header so we can rerender when the window size changes. The toolbar won't overlap the toolbox anymore!
=> Resize toolbar when window resizes

theme/asset-editor.less, theme/common.less, webapp/src/app.tsx, webapp/src/components/assetEditor/assetGallery.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/editor.tsx, webapp/src/components/assetEditor/store/assetEditorReducer.ts, webapp/src/package.ts
Stack of small asset editor changes! They are split out by commit:
https://github.com/microsoft/pxt/commit/214b9f9f051b050e49609c52502cd2b220444767 - Display animations along with other assets, open animation editor on "Edit"
https://github.com/microsoft/pxt/commit/a42c4bda509312e450b890466da0eb8636711879 - Adjust asset editor height for editor toolbar (fixes https://github.com/microsoft/pxt-arcade/issues/2500) and add font-weight + margin to asset name (fixes https://github.com/microsoft/pxt-arcade/issues/2487)
https://github.com/microsoft/pxt/commit/548367c2fe746003ba5d2cea2af64cbd8d8a535b - Switch to "My Assets" view any time an asset is duplicated, edited, or deleted (fixes https://github.com/microsoft/pxt-arcade/issues/2485) …
=> Display animations in asset editor, UI/UX fixes

pxtlib/tilemap.ts, webapp/src/app.tsx, webapp/src/components/assetEditor/actions/dispatch.ts, webapp/src/components/assetEditor/assetCard.tsx, webapp/src/components/assetEditor/assetGallery.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/editor.tsx, webapp/src/components/assetEditor/store/assetEditorReducer.ts
https://github.com/microsoft/pxt/commit/85882d28a26143a5f65dd9b2b3d3f3762ae93d09 - Save code before entering assets editor (fixes https://github.com/microsoft/pxt-arcade/issues/2506, fixes https://github.com/microsoft/pxt-arcade/issues/2502)
https://github.com/microsoft/pxt/commit/3d7be698f02d399a52e8ddf415ff9118817e30cf - Hook up window resize listener (fixes https://github.com/microsoft/pxt-arcade/issues/2490)
https://github.com/microsoft/pxt/commit/5facfa89b3960206251d46489faa0396ba5a45d1 - Duplicate should essentially create a new asset with the same image (fixes https://github.com/microsoft/pxt-arcade/issues/2514, partial fix for https://github.com/microsoft/pxt-arcade/issues/2481)
https://github.com/microsoft/pxt/commit/4b25eed12d8f54451d87ff619320960701b88dd2 - Look up selected …
=> Fixes for duplicate and saving assets, resize listener

pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_tileset.ts, pxtlib/tilemap.ts, webapp/src/app.tsx
We were losing references to temporary assets when switching between the asset editor and blocks editor. This fixes that and also makes it so that the source of truth for assets is the block data and not the field value (though that still gets used if the data doesn't exist)
=> Fixing some bugs in temporary assets

theme/melodyeditor.less
fix https://github.com/microsoft/pxt-microbit/issues/3398
(also the rendering on the share page, which is the exact same thing but a more important version of it :P https://makecode.microbit.org/20471-20215-46152-81939)
when rendering through the embed view the blocks are locked as non-editable, so our css has to match that
(could also just drop the `.blocklyEditableText`, but there are a lot of elements matching `.pxt-renderer g`)
here's the example from their post using an uploaded trg and working https://jsfiddle.net/ntoqkdsj/ (maybe worth noting the target includes my bluebird changes)
=> fix embed view for melody editor notes

cli/cli.ts
Just noticed that I had the key:value swapped in https://github.com/microsoft/pxt/pull/7477/files#, as the only examples of this I had seen were ones I made to test after misreading the docs page (it was checking if the condition was a valid file)
=> check keys in fileDeps validation, not values

cli/cli.ts, pxtlib/service.ts, pxtrunner/runner.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
Pass the builtinparts as a separate part of the message, so they're available if needed. Part of fix for micro:bit v2 sim positioning (right now they're getting counted as non-builtin parts, and causing the simulator to get double size
vs with this:
Up for alternative approaches as well, we might need something else to handle cases like using the music blocks (assuming we want them to show as using the onboardspeaker instead of the headphones when other blocks have switched to v2 modes)
=> pass builtinParts as separate field in init message

common-docs/browsers/no-auto-save.md, localtypings/pxtarget.d.ts, theme/common.less, webapp/src/core.ts, webapp/src/coretsx.tsx, webapp/src/db.ts, webapp/src/sui.tsx, webapp/src/workspace.ts
Pop an error message when we transition into an in memory workspace; no issue but some discussion here: https://github.com/microsoft/pxt/pull/7505 and offline
pouch db had a separate form of the in memory db (using pouch dbs apis) -- no reason to split up, so I made it just use the same memoryworkspace as others. also incidentally fixes the minor race condition mentioned in the pr above where we'd potentially make more than one db object
the `disableMemoryWorkspaceWarning` flag is so we can disable this warning in situations like hour of code where we don't really care to notify user we couldn't save.
(I'm not too attached to the wording, and we can always throw in a sad emoji to the header if we want!)
=> Error message on workspace db failure

theme/common.less, webapp/src/container.tsx
Build: https://arcade.makecode.com/app/497f26dff3463a0cb641fec965a062b57bc34850-5ffe727f79
Cleans up the various cases we had and positions the toggle strictly based on the number of children in the toggle and which child is active. Elements after the dropdown are slightly special-cased since the dropdown changes the offset amount. container.tsx changes are mostly just shifting those conditionals around, but I also added base-editormenuitem CSS class.
=> Set toggle position based on number of toggle elements

pxtblocks/fields/field_tileset.ts, pxtblocks/fields/field_utils.ts, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/editor.tsx
https://github.com/microsoft/pxt/commit/026a824a30ff8d5c4041cf0026fa730b593c60b5 - mark simulator as dirty, update main.ts for unnamed/temporary assets since they're emitted as literals in the case of images and animations (second half of fix for https://github.com/microsoft/pxt-arcade/issues/2488)
https://github.com/microsoft/pxt/commit/4a6d4be6d8f2df822b5d63a4f606c073f6d09da1 - null check, emit id directly for gallery tiles (fixes https://github.com/microsoft/pxt-arcade/issues/2512)
=> Update simulator from asset editor view, fix for tileset block

pxtblocks/fields/field_asset.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/main.ts, pxtlib/tilemap.ts, webapp/src/app.tsx, webapp/src/components/assetEditor/editor.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2481 
Also removes "assetprj" entirely, not necessary any more.
=> Add list of IDs to skip when checking if a tile is used

webapp/src/compiler.ts
fixes https://github.com/microsoft/pxt-minecraft/issues/1979
the issue was with these two snippets from the tutorial:
since it gets converted to "export let p = ....", it was hitting an assert in "getExportInfo" in typescript.
This is one way to fix it, Shannon also suggested just stripping out the "export" for export let and export function, but I'm still working on those regexes XD figured I'd put this up so I can get feedback on which way would be better
=> Don't strip out python namespaces when getting used blocks

webapp/src/components/ImageEditor/ImageCanvas.tsx
Added in two minor todo's that are probably easy but I didn't look at yet
=> image editor: clear focus on canvas interaction, only restrict events when focus in input element

pxtlib/hf2.ts, webapp/src/cmds.ts
For the micro:bit, don't disconnect from DAPlink after flashing -- since it stays alive anyway. This reduces the number of disconnect/reconnect.
The responsibility of reconnect is now moved to the reflashAsync function.
Tested v1/v2.
=> move responsability of reconnect to reflashAsync

pxtlib/browserutils.ts, pxtrunner/renderer.ts, webapp/public/run.html, webapp/src/app.tsx, webapp/src/cmds.ts
fix https://github.com/microsoft/pxt-microbit/issues/3417 - the dataurl was just too long for older versions of chrome to handle it. `createObjectURL` is listed as a working draft but browser support is good https://caniuse.com/bloburls
~I added a TODO for it, but will want to look at this a bit more and `revokeObjectUrl` -- as written the blob will persist in memory until refresh most likely~ added handling to revoke url when it goes out of use. Mainly wanted initial thoughts as this part of the code hasn't changed much / in case there is something known that I'm overlooking about `createObjectURL`
here's a build since I'm using it for browserstack anyways https://makecode.microbit.org/app/662dfecbb1be03dc15f0348e51683672c8e02097-64245805e1
=> Fix large hex downloads on chrome <=79

docfiles/macros.html, docfiles/style.css, docs/writing-docs/macros.md, pxtlib/gallery.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts
Backward compatible support for a markdown codecard section.
Our current code card format is cumbersome: it is really easy to create invalid json, it does not integrate well at all in crowdin. I was trying to translate the micro:bit cards... and it's impossible.
```codecard
[{
"name": "A card",
"url": "...."
}, {
"name": "Another card",
"url": "...."
}]
```
Crowdin decides to chunk it randomly.
The new format is based on markdown and guarantees a smooth integration in crowdin (screenshot below).
```
* name: A card
* url: ...
---
* name: Another card
* url: ...
---
* name: Yet another card
* url: ...
```
To support this format, we will also need to update the backend renderer.
=> Markdown format for codecard

localtypings/pxtarget.d.ts, webapp/src/container.tsx, webapp/src/editortoolbar.tsx, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx
workaround for https://github.com/microsoft/pxt-minecraft/issues/1996 
If we're running in minecraft and we're on a chromebook / android device, don't show the option to import from files. it doesn't work!
new target here: https://minecraft.makecode.com/app/3a840092483734d565d7fe3f74da9f2a37939181-da851b6b60?ipc=1&ingame=1
=> don't show import from file if on android

webapp/src/projects.tsx, webapp/src/scriptmanager.tsx, webapp/src/tutorial.tsx
fix https://github.com/microsoft/pxt-minecraft/issues/2051
the hideIteration tutorial flag hides the home button / makes tutorials inescapable. Don't show those under my projects so users can't get stuck.
As an alternative I took a look at doing it with the [temporary header flag](https://github.com/microsoft/pxt/blob/c73b189198b392ab371beab46a57f030c12ca51f/localtypings/projectheader.d.ts#L15) so the project wouldn't just sit around in local storage in perpetuity, but that will lose the project on refresh, and drop you into the normal editor.
I think one better thing we could do would be to change the behavior of the `temporary` flag to make the project have a lifespan of one day instead of not storing it at all, hide them the carousels, and then clear old ones in …
=> Filter out hide iteration tutorials

webapp/src/tutorial.tsx
Since the modal isn't created under the root, it isn't picking up the flyoutOnly stylings. Add this class back for the new HOC design
=> Add flyoutOnly class to modal

localtypings/pxtarget.d.ts, pxtcompiler/emitter/service.ts, webapp/src/compiler.ts
When you load multiple extensions that are in the same namespace, only one extension will have it's namespace API info cached. This means that if you load two such extensions in a project, back-out and create a new project with only one of the extensions (the one you loaded first), you will not find that extension's blocks in the toolbox. No category shows up in the toolbox for that extensions namespace since the namespace API info was not present in the cache for that extension. You can still search for the blocks, just not drag-and-drop them from the toll-box. 
There is already code to resolve when multiple packages define the same API info. If it's not two interface types that collided we usually make sure to either combine their sources or keep one if it contains the other. After that …
=> Cache namespaces that are defined in multiple packages in each of those packages

pxtlib/browserutils.ts
fix https://github.com/microsoft/pxt-microbit/issues/3553
In https://github.com/microsoft/pxt/pull/7557 I didn't notice this old special case https://github.com/microsoft/pxt/pull/646 for fixing datauris in edge. We use this function directly in a few other spots where we generate svgs thoughout the app, so just check that it actually is a datauri before chopping it up for now.
=> only special case edge download if uri is actually a datauri

pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
The host is implemented differently for ios / android / desktop, so loadIpc isn't guaranteed to exist in non-desktop. ipcRenderer will eventually get loaded, so include that in the run msg so we can guarantee the simulator knows it is in game~
=> if in ipcRenderer, send that state in sim msg

pxtsim/embed.ts
fix race condition when starting new runtimes quickly. The outcome seems similar to the issue from shannons last comment in https://github.com/microsoft/pxt-minecraft/issues/2057#issuecomment-719727197, but I haven't been able to repro with those steps so far / have to test a bit more to see if it's actually related.
easiest way to repro the issue is a build of minecraft where you increase the delay in `board.initAsync` from 300ms to ~2.5 seconds. Then, click outside the window to run code, c to open code again immediately, then close again. The first runtimes `initAsync` will complete after the 2.5second delay, and then `runtime.run` will be called on the newer runtime before that one has finished initializing. Whenever the current runtime finishes initializing it crashes on …
=> fix race condition when starting sim runtime

skillmap/src/actions/dispatch.ts, skillmap/src/components/Carousel.tsx, skillmap/src/components/CarouselItem.tsx, skillmap/src/components/CompletionModal.tsx, skillmap/src/components/Modal.tsx, skillmap/src/components/SkillCarousel.tsx, skillmap/src/lib/skillMapUtils.ts, skillmap/src/store/reducer.ts, skillmap/src/styles/skillcard.css
- Small cleanup for generic Carousel/CarouselItem components to remove redux dependencies
- Hook completion modal "Next" button up to next activity
- Push end certificate card (triggers completion modal for entire skill map) if all activities in a map are completed
=> Add certificate 'card' at the end of a carousel after skill map completed

pxteditor/editor.ts, theme/highcontrast.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/createFunction.tsx, webapp/src/extensions.tsx, webapp/src/lang.tsx, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx, webapp/src/share.tsx, webapp/src/sidebarTutorial.tsx, webapp/src/tutorial.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/2076
This fix is two parts:
1. Updating the HC less so that for inverted themed editors, the modal's outline is the text color (white)
2. Make the root's classes accessible so that we can attach them to the modals when we make them
I initially updated all the modals with new classes, but changed it so that only the modals we'll see in Minecraft have the classes. I can add them back tho if you guys think that'd be better
=> Attach root classes to minecraft modals

pxtcompiler/emitter/driver.ts, pxtcompiler/emitter/emitter.ts
hot fix for hour of code tutorials
~I'm fairly confident this will work but waiting for my local build to test real quick, putting up now to get build started~ tested and appears to work, though that's just comparing the generated code / haven't got an easy way to test in game at the moment.
For reference, generated code with current release (important bit is relative position of `pxsim._control._onCodeStop` vs on start / main.ts code):
vs with previous release
and with this change:
=> fix code stop / minecraft hour of code

pxtlib/gallery.ts
Fix rendering of galleries in docs page using JSON format. Was broken by support for markdown format.
=> support for legacy json format of galleries

webapp/src/blocks.tsx
Shannon made minecraft tutorials too fast D:!!
Fix an old race condition in loading tutorials that change the toolbox style, which is currently causing template code to be overwritten in minecraft hour of code.
It looks like `loadingXmlPromise` was intended to be cancelled when `refreshToolbox` was called. However, bluebird promises aren't cancellable by default / without specifying it in the config, so trying to do so would throw a big warning in the console... if we weren't nulling out `loadingXmlPromise` immediately after it was set (maybe to avoid the warning??).
The route a failure here would follow would be approximately:
* `domUpdate` gets called with the initial content (the template code) (I'll call the promise this makes 'loadingXmlPromise1')
* `refreshToolbox` is called before …
=> fix race condition when loading cached flyoutOnly tutorials

pxtcompiler/emitter/service.ts
Porting two monaco fixes:
* Fix snippets for fixedInstances outside block namespace (#7286) 
* Fix snippets for shim=TD_ID parameters (#7284)
fix https://github.com/microsoft/pxt-microbit/issues/3501 (the second commit fixes the onboard speaker block)
=> [stable6.0] Port monaco fixes for v2 music blocks

pxtrunner/renderer.ts, webapp/src/blocks.tsx
Cherry picking for minecraft patch:
*  only show blocks in block gallery (#7605)
* fix race condition when loading cached flyoutOnly tutorials (#7600)
=> [stable6.4] Porting tutorial load and api gallery fix for minecraft patch

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/hinttooltip.tsx, webapp/src/tutorial.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/2080
Keep track of all the hints we've seen so we don't jiggle the hint button if it's already been used.
the path is basically:
**hintManager** is in charge of the wiggling and also keeps track of who has/hasn't been seen
**app** prompts **hintManager** to start the timer to jiggle
**tutorial** tells **app** when we've seen a hint who then passes it along to **hintManager**
This plays nicely with having multiple tutorials
=> Keep track of hints we've seen

webapp/src/cmds.ts
We need to run reconnectAsync after detecting a new device so that we can detect which hardware is connected.
+ increase timeout for winrt deployment.
=> win10 flash: make sure to reconnect dap wrapper

cli/cli.ts, cli/youtube.ts, pxtlib/gallery.ts
CLI tool to migrate JSON-formatted codecard sections into markdown equivalents.
Here is an example: https://github.com/microsoft/pxt-maker/commit/4863e2d7274ca9ae8d07cc4ec506c2055cbb4d8f
```
pxt upgradecards
```
=> Upgrade codecard galleries

localtypings/pxtarget.d.ts, pxtlib/browserutils.ts
re: https://github.com/microsoft/pxt-microbit/issues/3674, will toggle this on with https://github.com/microsoft/pxt-microbit/blob/master/pxtarget.json#L563 (and if needed for iosapp)
=> add apptheme field to use data uri instead of blob object

docfiles/langpicker.html
Always show the translate button now that in-context is supported.
=> always show translate button in docs

localtypings/pxtarget.d.ts, pxtlib/service.ts, webapp/src/compiler.ts
Fix https://github.com/microsoft/pxt-microbit/issues/3655
When the user first loads an extension in non-english (and the extension has translations), it was caching the api info with the translations applied. `localizeApisAsync` doesn't do anything (besides clearing some block definition issues) when set to english, so it wouldn't be translated back to english when loaded (so worth noting this issue only applies when going from another language -> english, going to french from Dutch would still work). Need to clear those before caching.
=> clear translations before caching api info

docfiles/macros.html, docfiles/style.css, docs/writing-docs/macros.md, pxtlib/gallery.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts
- The markdown-based format is optimized for crowdin and make its much easier to localize. 
- The changes are easily testable: if the gallery render in the home screen and on the docs pages; they still work
- We have a CLI too to batch convert all codecards into markdown once this is live.
=> [stable6.0] support for Markdown codecards

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/compiler.ts
- The "clearDB" promises for the TutorialInfo and ApiInfo were never resolving, so resetAsync would never reload the editor. I'm guessing something about the updated CEF changed the behavior of this; I've updated the clear functions to delete the table instead of the entire DB whenever possible.
- The global "hash" variable is not updated when we navigate between activities (page isn't reloaded), so in the Minecraft HoC case reloadEditor will always reload into the first tutorial; I don't know if any parts of our code depend on this behavior so I'm only updating it in the case of a new activity which should be fairly safe.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2093
=> Fix IndexedDB reset/clear, update global hash when loading new activity

pxtcompiler/emitter/snippets.ts
fix https://github.com/microsoft/pxt-minecraft/issues/2094
When a symbol with 'any' type had a default value, this was mutating parameter node / changing it from `any` to the type of the default value. So in minecraft, currently `player.say`'s block can take numbers / any, but if you switch to typescript and happen to get a completion generated for `player.say` the apiInfo will get changed / the block will no longer accept numbers or other values until you refresh.
=> Dont mutate type node during completions of parameters with type 'any'

webapp/src/auth.ts, webapp/src/cloudworkspace.ts, webapp/src/user.tsx, webapp/src/workspace.ts
* Add `CloudWorkspace` provider. Signed in users are switched to this workspace.
* Cache user profile in local storage, and optimistically assume they're logged in on app load.
TODO:
- Handle promotion of locally stored levels to cloud. Review Sam's design.
- Handle eTag conflicts on save.
Although there's more to do, I think this is fine to merge at this stage.
=> Add support for basic cloud save

webapp/src/app.tsx
We carryover filters from the previous editor state in internalLoadHeaderAsync which means if you call newEmptyProject from inside a tutorial, the toolbox filters are not cleared. 
@abchatra can we take this as a patch fix for Minecraft? i think it will help the Prodigy Learning folks with the tutorial thing they're doing
=> Clear editor filters when opening a new empty project

theme/blockly-core.less
almost fixes https://github.com/microsoft/pxt-arcade/issues/2475 there's still a markdown change needed
it will look like this!
=> Use grey background for images in hints

docfiles/script.html, docfiles/targetconfig.html, localtypings/pxtarget.d.ts, webapp/public/run.html
For use with https://github.com/microsoft/pxt-tick-event; adds an allowlist for scripts in targetconfig. Allowlisted scripts will drop the 'not endorsed by microsoft' banner, and listen for ticks from the simulator.
I tested it works locally / not doing anything super fancy, but I'm not certain how we'd test the share page online? Would I have to push it up to staging?
I didn't see a general way to access targetconfig.json in docs, so I added `targetconfig.html` which makes a promise to fetch the targetconfig; seems like something we could clean up with a replacement in the backend (like we do with `var pxtConfig = null;`) but this seems fine to me for now / can always add it later and just make the promise trivial?
I added the portion in script.html to check for approved links / look for …
=> Simulator tick events

webapp/src/workspace.ts
fix https://github.com/microsoft/pxt-arcade/issues/1999
This seems to behave fine to me? Causes the project to load properly (both the one from the issue and the other one I ran into today), and doesn't show the files in the diff. I suppose we'd need to check for utf16 big / little endian BOM as well if we wanted to be fully thorough, but notepad produces UTF-8 + BOM which I believe was the issue here / before as well?
=> try adding UTF-8 BOM on sha miss

skillmap/src/App.tsx, skillmap/src/actions/dispatch.ts, skillmap/src/components/Dropdown.tsx, skillmap/src/components/HeaderBar.tsx, skillmap/src/lib/browserUtils.ts, skillmap/src/store/reducer.ts
- "Report Abuse" goes directly to Github's "Report Content" page
- Only show the link for content whose approval status is "unknown"
=> Update 'Report Abuse' link, hide and show based on repo status

docfiles/tickevent.html
setting up window.appInsights.trackEvent is async, so it's possible for tick events to be fired before that gets loaded; in particular this happens for https://github.com/microsoft/pxt-arcade/blob/master/docfiles/script.html#L174 on my machine.
This queues the events in that case, and checks every second until trackEvent is loaded / fires off all the ticks at that point.
Also updated the tick posting portion so https://github.com/microsoft/pxt-arcade/pull/2587 would be unnecessary (though not really sure if we want cookie = true for sure? Not sure where it landed on whether we should be setting that or not now that when the cookie banner is gone).
=> Dont lose tick events, attach target

cli/gdb.ts
This correctly skips the bootloader on gdb `rst` command on nrf52 boards.
=> Use NVIC_SystemReset() when debugging

webapp/src/projects.tsx
Small optimization, hide dots when there is only 1 item in the gallery.
=> Hero gallery: don't show dots when #cards < 2

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/projects.tsx
fixes issue with losing "example.start" ticks when homescreen examples are opened
=> Use startActivity function when opening gallery examples also

skillmap/src/components/makecodeFrame.tsx, skillmap/src/lib/browserUtils.ts, skillmap/src/lib/skillMap.d.ts
Hopefully fixes https://github.com/microsoft/pxt-arcade/issues/2595 and https://github.com/microsoft/pxt-arcade/issues/2597
I was finally able to repro this by turning on the maximum cpu throttling in Chrome.
The other part of the change is to make it so that we wait until the activity/project is started instead of using the editor load event because when it's slow the editor loads an empty project and *then* loads the actual thing.
=> Don't save non-tutorial headers and wait until load is complete

cli/cli.ts
Fix for https://github.com/microsoft/pxt-arcade/issues/2588 . Github files for **releases** are cached under ``pxt_modules/.githubcache/...`` . This prevents us from downloading multiple times the same repo when building for multiple platforms.
=> Cache downloaded github repoes on disk when building from CLI

skillmap/src/store/reducer.ts
Should fix the saving issues, probably not related to the defaultPath url.
=> Null check for skill map completion state when saving header

skillmap/src/components/makecodeFrame.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2661
Changes it to be the name of the activity
=> Patch header name to match card

pxteditor/shell.ts, skillmap/src/components/makecodeFrame.tsx, webapp/src/app.tsx
Hopefully fixes https://github.com/microsoft/pxt-arcade/issues/2649
Does not create a default blank project when the editor is loaded in controller mode with this flag, instead returns an event (pxt.controller.createproject) so that the controller can choose how to handle it.
Bug is a race condition so a little hard to repro but I can pretty consistently see it in Edge without this change, and I have not seen it with this change. I also have not been able to repro the "no template code" bug with this change, but once it's merged we should probably deploy and do some stress tests.
=> Add noproject=1 flag to open editor in controller mode without default project

skillmap/src/components/makecodeFrame.tsx
Gets rid of the inner cookie banner on the skills map. The outer one will go away once I update pxtweb in the deployment config
=> Remove cookie banner from makecode frame

localtypings/pxtpackage.d.ts, webapp/src/projects.tsx
Small change to support skipping the details view from a homescreen card:
- 'directOpen' property specifies that a card should launch it's primary action directly (open tutorial, show instructions, etc) instead of expanding the details view
- adding "link" CardType--previously our default "Action" was a link (stylized <a> tag) so to support the "CodeCard as a link" I'm adding an extra case to the chgGallery function (set as the onClick for the CodeCard as well as the onClick for the details action)
=> Add code card 'directOpen' property to skip the details view, add 'link' CodeCardType

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/emitter/cloud.ts, pxtlib/service.ts, pxtrunner/runner.ts, webapp/public/run.html, webapp/src/simulator.ts
Add option to use prebuilt js on share page in arcade to speed up loading; this is mainly just an intermediary step towards prebuilding sim js in general (hopefully!)
(also added a quick fix for docs sims, which is crashing off master right now: https://github.com/microsoft/pxt/pull/7681/commits/b534fe7d608177a368f830aab6fa009cd0ddf1a4)
asphodel diff:
time from page load -> first asphodel paint on my work computer:
with this (worth noting this is local serve / loading time may vary):
other notes:
* I'm appending version suffixes so any bump would need to rebuild the source -- this isn't usually necessary except for major releases, but 
* plays a bit weirdly with local host, as we replace `@versionsuff@` with "" there; for testing locally I just renamed the file without the suffix
* I only …
=> Allow prebuilt js in run.html links

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/emitter/cloud.ts, pxtlib/service.ts, pxtrunner/runner.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/public/run.html, webapp/src/simulator.ts
For speeding up asphodel ~
Original prs:
* share page upgrade rules https://github.com/microsoft/pxt/pull/7463 (note there's a 1 line fix to this pr I added to 7681 to fix doc page sims)
* parts change was for microbit v2 sim support, already released there https://github.com/microsoft/pxt/pull/7544 
* fix share page for python projects https://github.com/microsoft/pxt/pull/7555
* prebuilt sim https://github.com/microsoft/pxt/pull/7681
All cherry-picked cleanly / no changes specific to this pr. Most of the code for the other two share page fixes was refactored into a separate function in the prebuilt sim pr, so the green portion is very similar in that vs this.
=> [stable6.2] cherry picks for prebuilt simjs

webapp/public/run.html
Right now it's not getting replaced as run.html is a special cased html page, and `pxtConfig` is just getting '?' for the target version, so just remove the version suffix. For now, drop the `@versionsuff@` and just point to `builtjs/{share-id}.json`, and when we get the next release I'll version it then (as my future change wouldn't require a backend update, as it's not using run.html)
=> remove version suffix from builtsimjsurl

skillmap/src/App.tsx, skillmap/src/components/makecodeFrame.tsx
Looks like we had a timing issue when the editor pauses to load localizations. Switching to the event that Shannon added which should fix the skillmap in localized languages.
=> Fix skillmap for localized languages

pxtlib/github.ts, pxtlib/package.ts, theme/common.less, theme/themes/pxt/globals/site.variables, theme/themes/pxt/globals/zindex.variables, webapp/src/filelist.tsx, webapp/src/gitjson.tsx, webapp/src/projects.tsx, webapp/src/workspace.ts
Handles package version resolution when using interdependent github repositories that are unbound. This happens a lot in mono-repo.
Let's look at a simple example of a root extension with nested extension reference the root.
```
parent/
parent/child <-- reference jacdac
```
When creating a release, all extensions within the repo share the tag, so we should leave the version tag of ``parent`` unbound in the ``child`` dependecy list to avoid versioning conflicts.
If a script references ``child``, when a ``parent`` is resolve, we first check if we've already found a tag for that ``child`` - hence thta repo. We use that tag for ``parent`` as well.
If a script reference ``parent`` and ``child`` is already referenced from the top level script dependency list, we will try to resolve the version …
=> mono-repo 2

cli/server.ts, docfiles/docs.js, docfiles/package.html
Hassan pointed out last night that the `/pkg/{repo slug}` page on local serve was behaving poorly -- since most of our icon urls are defined as relative paths (https://github.com/microsoft/pxt-arcade/blob/1517905b5d614a77a433dd7328b6be1ae92586df/pxtarget.json#L438) they get messed up (in this case, it ended up making requests to github as it was relative under the `/pkg/` endpoint, which causes the local serve to crash.
Fix that and a few other minor issues I noticed along the way
* fix refs to images defined in `pxt/docs/static`
* patch relative links to ./static/ (these get automatically swapped out for the cdn links in the backend anyways)
* Don't error when pulling in docs.js on a page without langpicker
* add langpicker to /pkg/ so the button works (the translations don't work …
=> fix pathing for local serve in docs, issue with lang picker on /pkg

skillmap/src/components/HeaderBar.tsx, skillmap/src/components/SkillCard.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/2640 + couple additional tick events
=> Display 'CONTINUE' text on skill card if activity has been restarted

package.json, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_base.ts, pxtblocks/fields/field_tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2543
Adding DO NOT MERGE because this requires this blockly pr:
https://github.com/microsoft/pxt-blockly/pull/331
=> fix load of asset field editors when set value is called multiple times

pxtrunner/runner.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/public/run.html
With single=1, the sim runner (run.html) never spins up an additional iframe (neighter duplicate or using message packet). Use in JACDAC docs to have better control if frame being spinned up
=> option to run single simulators

pxtblocks/fields/field_position.ts
fixes microsoft/pxt-microbit#3496 
related to https://github.com/microsoft/pxt-blockly/pull/333
We need the event so we can check if it's a touch event or not. If it is, we will show the modal to input text. If not, it'll just be the inline experience.
=> Add event parameter to position picker so it can show the modal input

webapp/src/blocks.tsx
fix https://github.com/microsoft/pxt-arcade/issues/2573
Worth noting this would show the variables with invalid chars escaped:
as that's how they're stored in the simulator; if we want to, we could defer escaping the name till the filter is used https://github.com/microsoft/pxt/blob/d1d8cd45952216d88c79130b4c04bc926586b281/webapp/src/debuggerVariables.tsx#L189 and then use the name in `filters` instead of `updatedGlobals.variables` when displaying the variable? Not sure it's necessary so I left it as the simple fix for now
=> show vars with non-ts-identifier chars in debug view

docs/writing-docs/tutorials/resources.md, localtypings/pxtarget.d.ts, pxtlib/gallery.ts, pxtlib/tutorial.ts, webapp/src/app.tsx
I've added documentation on how to use this to the docs section on tutorials.
This is definitely not ideal, but it will serve as a stopgap until we have time to make a better solution (right now you can't write tutorials with the asset editor at all 😦). @abchatra and I brainstormed a few options earlier today that we'll discuss with the team.
=> Support projects that use assets from the asset editor in tutorials

cli/cli.ts, gulpfile.js, package.json
including the files in the package.json so that they will be uploaded with the next bump! should be the last remaining fix for https://github.com/microsoft/pxt-arcade/issues/2584
=> Include skillmap built files in pxt package.json, clean before build

pxteditor/monaco-fields/field_sprite.ts, pxtlib/tilemap.ts, webapp/src/blocklyFieldView.tsx, webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/assetEditor/editor.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2464
This fixes a few things:
1. Fixes the new asset button in the asset editor which got broken at some point and wouldn't open up the editor after selecting an asset type. The editors also now have the gallery header enabled
2. Removes the "show tile gallery" button which is no longer needed because of https://github.com/microsoft/pxt/pull/7737
3. Fixes exception when closing the image/tilemap editor without making any edits
=> Asset creation fix

pxtblocks/blocklyrenderer.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2755
The temporary assets should be cleaned up when the fields are disposed, but the workspace we use for hints was apparently not always getting cleaned up
=> Make sure the rendering blockly workspace is always cleaned up

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/screenshot.ts, webapp/src/share.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/2600
The issue was that Facebook won't show images if they're too small (less than 200x200 px), so I added an optional scaling factor to converting the screenshot image -> PNG and also when we make the gifs. Are we worried about this taking too much storage?
[edit] I had a screenshot that I forgot to share!
it's a little blurry still, but I think that's on FB's end not liking pixel art. better than having part of the microsoft logo?
=> Scale screenshots / gifs to display on social media better

pxtblocks/fields/field_asset.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2815
Fixes https://github.com/microsoft/pxt-arcade/issues/2809
We store the asset id on the xml of the block. That works well, but when we switch to javascript we delete the asset. This is a problem if we switch back to the blocks with no changes; no decompile happens so the xml is the same and it tries to load the deleted asset. This just checks to make sure it actually exists.
=> Fix reloads of same xml for temporary assets

theme/tutorial.less
fixes https://github.com/microsoft/pxt-arcade/issues/2743
The issue was the `top` rule was being applied when the sidedocs were closed, which pushed everything down. The `sideDocs` class only appears when it's open, so I added it as a rule.
=> Only adjust sidedocs top when it's visible

pxtlib/skillmap.ts, skillmap/src/App.tsx, skillmap/src/components/HeaderBar.tsx, skillmap/src/components/SkillCard.tsx, skillmap/src/components/SkillCarousel.tsx, skillmap/src/components/makecodeFrame.tsx, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/lib/skillMapUtils.ts, skillmap/src/store/reducer.ts
previously mapProgress was a map of carousel name to progress (per activity)--this would cause issues if different pages had the same name for a carousel. adding an extra layer where mapProgress uses the page source URL (same as completedTags, should be unique) to map to individual carousels
also makes the page source URL required (defaults to "default" if one is not found)
=> Store skillmap progress for page source url rather than carousel name

webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/assetEditor/assetSidebar.tsx
- Rename 'Clipboard' -> 'Copy'
- Give duplicated gallery assets a default displayName (parsed from qName)
- Give tiles created in the tilemap a default display name (no such thing as a temporary tile)
Fixes https://github.com/microsoft/pxt-arcade/issues/2818
Fixes https://github.com/microsoft/pxt-arcade/issues/2754
=> Fix gallery asset duplication, tile names

skillmap/src/components/HeaderBar.tsx, skillmap/src/components/SkillCarousel.tsx, skillmap/src/styles/skillcard.css
- Hide "Reset All" option if you are in an activity
- Always display trophy icon (unclickable). After learning path is completed, icon will spin, auto-display the completion modal, and become clickable
Fixes https://github.com/microsoft/pxt-arcade/issues/2791
Fixes https://github.com/microsoft/pxt-arcade/issues/2742
=> Hide skillmap reset option in iframe, show trophy always

pxtblocks/blocklycompiler.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2799
Also fixes the preview, which got broken at some point:
=> Fix grey blocks for tilemap blocks

cli/cli.ts
fix for https://github.com/microsoft/pxt-microbit/issues/3826, currently it's not saving the non default hex files during build / staticpkg so the the offline app is requiring a network request to grab the micro:bit v2 hexfile the first time
=> Save multivariant hexfiles in build

webapp/src/components/ImageEditor/BottomBar.tsx, webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/keyboardShortcuts.ts, webapp/src/components/ImageFieldEditor.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2800
and takes care of an old todo
=> Add system for locking/unlocking keyboard shortcuts in the image editor

pxteditor/monaco-fields/field_sprite.ts, webapp/src/assets.ts
- Replace image literals with `assets.image\`name\`` if the user types a display name into the sprite editor
- Also fixes JS console error that happens if you refresh while in monaco and open the sprite editor and try to rename a sprite (tilemapProject isn't loaded)
Fixes https://github.com/microsoft/pxt-arcade/issues/2813
=> Allow naming of temporary assets (image literals) from monaco field

webapp/src/app.tsx, webapp/src/container.tsx
the "Exit Tutorial" button in the menu bar now takes the user to the homescreen (preserving the tutorial header) in both recipes and tutorials. we got teacher feedback that students were clicking "Exit" in the middle of Shark Attack and it was bumping them out of the recipe entirely. the "Finish" button at the end of the recipe still allows the user to exit while remaining in the editor.
fixes https://github.com/microsoft/pxt-arcade/issues/2676
=> Unify recipe 'Exit Tutorial' behavior with tutorial

skillmap/src/actions/dispatch.ts, skillmap/src/components/makecodeFrame.tsx, skillmap/src/store/reducer.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2789
We now display the last step as 7/7 unless you actually click finish.
Also fixes a race condition when unloading the iframe where we weren't updating the activity progress before the iframe had been unloaded.
=> fix skillmap step race condition and change is completed logic

webapp/src/components/ImageEditor/toolDefinitions.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2853
The magic thing that made it fail was if the tile was in the tilemap data at index 2 (red) which is the same index we use for tiles in the tilemap image.
=> fix fill for walls on the tile in index 2

pxtlib/util.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2802
For some reason, Safari is just reading the gallery png as a buffer full of 0's. Handle that case
=> Fix hang in safari when dragging a png from the gallery

theme/image-editor/bottomBar.less
Fixes https://github.com/microsoft/pxt-arcade/issues/2855
Hide it on mobile phones
=> Remove asset editor name on mobile

pxtlib/util.ts, webapp/src/app.tsx, webapp/src/cloud.ts, webapp/src/workspace.ts
Try loading the latest cloud version when opening a project; skip it if it takes too long
Adds support for partial synchronizations.
The new behavior is:
When opening a cloud project,
Start fetching that project's latest state from the cloud,
If the fetch completes with 1.5 seconds, great, load that,
Else, load the local project and if the sync comes back with changes, refresh the editor
Fixes: https://github.com/microsoft/pxt-arcade/issues/2866
=> Try loading the latest cloud version when opening a project; skip it if it takes too long

pxtblocks/fields/field_asset.ts, webapp/src/tutorial.tsx
so the issue was, for JS/Py tutorials, running `getUsedBlocks` creates a workspace and renders all the blocks (including the assets), which never get cleaned up. this only happens the first time you load the tutorial in a session, because otherwise used blocks are cached. this change disposes of that workspace, and also disposes of the temporary asset when the block is disposed
fixes https://github.com/microsoft/pxt-arcade/issues/2807
=> Always dispose of temporary asset when block is disposed

webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2610
Fixes https://github.com/microsoft/pxt-arcade/issues/2450
I finally figured out a repro for the dreaded https://github.com/microsoft/pxt-arcade/issues/2450! If you *zoom* the canvas and then open the tile editor, then the canvas will hide. You have to zoom first.
=> Zoom fixes for tilemap editor

cli/cli.ts, docfiles/style.css, pxtblocks/blocklyrenderer.ts, pxtlib/tilemap.ts, pxtlib/tutorial.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, webapp/public/run.html
fix https://github.com/microsoft/pxt-arcade/issues/2566 (include the jres when compiling simjs), and also support the \`\`\`assetjson snippets in docs as I noticed that was missing.
(also fix a minor bug where there was still a box where \`\`\`jres snippets used to be, you can see it at the bottom of https://arcade.makecode.com/blocks-games/jumpy-platformer)
~in the test md file I made it looks like images / animations from the jres aren't getting loaded properly into the blocks, will take a look at that (but wanted to put up PR first as I think this will be the majority of the changes / probably just need an extra line in runner.ts somewhere to patch in the images properly)~ ~Fixed images but animations are still showing up as grey blocks for some reason~ fixed all, but could use some …
=> Fix docs sims w jres, support assetjson in docs

pxtlib/discourse.ts, pxtlib/gallery.ts, webapp/src/projects.tsx
right now we manually add a "forumExample" action card ("Open in Editor") to every "forumUrl" card type. this PR changes it so we skip this step if the forumUrl has otherActions present. will do a separate PR with CLI changes to output the featured games markdown in the new format, but that requires some additional tweaks to support the images, and is all run locally to generate the markdown. this should be all that's required for the release.
also makes no assumptions about what editor (blocks/js/py) the sharedExample should be opened in--if nothing is specified, it simply says "Open in Editor"
=> Don't add forumExample card if forumUrl has otherActions

webapp/src/auth.ts
If any authenticated api call returns 401/Unauthorized, logout the user. This indicates the user did something to invalidate their account such as delete their account from another browser or tab.
=> auth: logout if we receive 401/Unauthorized

pxtlib/tilemap.ts, webapp/src/components/ImageEditor/ImageEditor.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/2907
\+ check ID instead of internalID for seeing if a tile asset is being used in a tilemap
=> Set isProjectTile true to tiles returned from asset field editor

webapp/src/projects.tsx
Fix https://github.com/microsoft/pxt-arcade/issues/2404
For some screen sizes these mp4s / video elements break on ios, so just fall back to gif / img instead.
=> fix detail view animations on ios

pxtblocks/blocklycompiler.ts, pxtblocks/fields/field_asset.ts, pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2912
Fixes https://github.com/microsoft/pxt-arcade/issues/2905
Fixes https://github.com/microsoft/pxt-arcade/issues/2894
Fixes https://github.com/microsoft/pxt-arcade/issues/2920
This fixes a host of bugs all related to the same underlying issue. When we save the image-editor fields, we also save the ID of the asset to the block XML. This is so that we can reload the asset when switching back to blocks after making changes elsewhere (like in the asset editor tab). However, we also dispose of temporary assets in a few situations without clearing that ID in the XML. Then when the XML gets loaded again, it leads to some weird behavior because the assets don't exist.
Say we have a project with two temporary assets: `myImages.image1` and …
=> Fix asset transformation bugs

skillmap/src/components/SkillCarousel.tsx, skillmap/src/styles/skillcard.css
we load the markdown before user progress, so maps load in as "incomplete" then become "completed" once the user state is loaded. before, we only added the end trophy once a map was completed so we didn't run into the CSS transition over-triggering; now the DOM element is always present. did a little shifting around of elements to make it so this wasn't the case, and also updated the rendering so it's easier to tell when a map is completed (trophy) vs not (dot):
fixes https://github.com/microsoft/pxt-arcade/issues/2899
=> Only auto-display completion modal once, load Arcade beta from skillmap beta

webapp/src/components/assetEditor/editor.tsx
I removed this when updating the gallery to use shared code but we still need blocksInfo for the tilemap editor
=> Set blocksinfo in asset editor for tilemap/image editor

theme/image-editor/imageEditor.less
=> Align sprite gallery rows to start of container

pxtlib/spriteutils.ts, webapp/src/components/ImageFieldEditor.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/2901
- Added fetching tags for assets
- Added filtering by tags 
I copied the tag filtering from https://github.com/microsoft/pxt/blob/9e24403a17e2df8aa2261572b653662dbc9cbf5d/pxtlib/spriteutils.ts#L414
Also the dialogs gallery looks like this now, I can't remember if that's how it was before or if this is what we want?
=> Filter assets by tag in gallery

webapp/src/assets.ts, webapp/src/components/ImageEditor/BottomBar.tsx, webapp/src/components/ImageEditor/tilemap/TilePalette.tsx, webapp/src/components/assetEditor/assetGallery.tsx
fixes:
- set default interval when creating animation (bug: second animation created in the editor has empty interval)
- copy display name when duplicating a tile INSIDE the tilemap (bug: duplicated tiles in tilemap have no display names and are listed as "temporary asset")
- disable resize for tiles only (bug: editing a tile in the asset editor then opening a tilemap will disable resize for that tilemap)
=> Default animation interval, copy duplicated tile display name, disable resize fix

webapp/src/components/ImageEditor/toolDefinitions.ts
Tiny fix for square marquee selections, which were getting cropped when rotating. Need to check that it's square *and* the full image
=> Fixing rotate logic for square marquee selections

webapp/src/components/ImageEditor/store/imageReducer.ts, webapp/src/components/ImageEditor/toolDefinitions.ts, webapp/src/components/ImageFieldEditor.tsx
Fixes three random bugs:
1. Fixes flip when you make a marquee selection and then clear it (already fixed for rotate, forgot to port it over)
2. Fixes the my assets tab for the tile editor so that it reflects edits made to other tiles in the tilemap editor
3. Fixes some state accidentally being carried over between tilemap editors
=> Last minute fixes

webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/assetEditor/editor.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2963
The "My Assets" tab only really makes sense when you are in a block, because it replaces the current thing you're editing with a reference to the asset you selected. We don't really have a concept of references in the asset editor, so remove the tab altogether. This also removes it when editing a tile in the tilemap editor which has the same issue.
=> Hide my assets option when editing a tile or in asset editor

webapp/src/components/ImageEditor/BottomBar.tsx
fix https://github.com/microsoft/pxt-arcade/issues/2955
I figured this one was probably worth doing as a tiny patch for the release, since it looks like the current behavior is 'silently corrupt the huge tilemap you spent a long time making' which is not great :(
=> limit tilemap editor to 255x255

theme/asset-editor.less, theme/themes/pxt/globals/site.variables
@soniakandah we've gotten some user feedback that the current tab design is a bit confusing; i added some borders as a (hopefully low-impact) fix for the current release, until we get to the full redesign later, happy to make adjustments if you have feedback
fixes https://github.com/microsoft/pxt-arcade/issues/2978
fixes https://github.com/microsoft/pxt-arcade/issues/2879
=> Add border to help distinguish selected/unselected asset tab

theme/image-editor/tilePalette.less
mostly regains space by making the minimap a rectangle, but also shrinks some of the margins. i believe this should cover the chromebook/pixelbook case, here is a build if people want to give it a spin: https://arcade.makecode.com/app/f7f34a6a5fd79e2ad8f383f800bae690b7401b7c-acce3a0707
fixes https://github.com/microsoft/pxt-arcade/issues/2957
fixes https://github.com/microsoft/pxt-arcade/issues/2729
=> Compress tilemap sidebar for smaller screen sizes

pxtblocks/blocklyimporter.ts, pxtblocks/fields/field_utils.ts, pxtlib/legacyTilemap.ts
- move domToWorkspaceNoEvents return statement into `finally` so that it returns
- wrap tilemap upgrade in try/catch so that we always re-enable blockly events after disabling them
- extra null check in decodeTilemap (was causing above error in tilemap upgrade)
fixes https://github.com/microsoft/pxt-arcade/issues/2997
cat jumper 2 works, adventures of sam & nate still doesn't upgrade properly but that looks like a separate bug with the tilemaps extension
=> Fix tilemap upgrade path in compiler

pxtblocks/fields/field_sprite.ts, pxtlib/spriteutils.ts
I doubt this will solve the underlying issue in https://github.com/microsoft/pxt-arcade/issues/2986 (which I cannot repro) but this will at least stop the sprite field editor from destroying the evidence when it occurs.
That bug is caused when we try to read the image literal from the asset string (e.g. ```assets.image`hello` ```) and you end up getting a single line of random pixels. Error out and make it a grey block instead.
=> Be stricter when parsing image literals

pxtlib/tilemap.ts, webapp/src/assets.ts, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/assetEditor/assetGallery.tsx
fix https://github.com/microsoft/pxt-arcade/issues/3026, easy repro in https://github.com/microsoft/pxt-arcade/issues/3026#issuecomment-772104528
Check the shortId as well when generating checking whether a name is taken, to avoid overlapping between shortId & display names
Also changes default display name from `tile` to ~`customTile`~ see comment \\/, to minimize overlapping between displayName & shortId when possible
=> check shortId as well when creating new id

pxtlib/package.ts
When add a new github dependency without a tag, default to existing tag if already reference. Eg if adding "foo/bar", but "foo/bar#0.0.0" is already reference, use "foo/bar#0.0.0".
=> Conflict resolution for loosely versioned dependencies.

webapp/src/cloud.ts
Due to some confusion, we weren't returning version tags from the project list call. So we used the modification time and delete status to check for differences between the local project and the cloud project.
Now thanks to: https://github.com/microsoft/pxt-backend/pull/364
project versions are returned by list and can be used instead.
Because of how this is written, this is backwards compatible so that this PR doesn't need the backend to be updated first. So this is safe to merge.
=> When syncing projects, prefer to use the project version returned from cloud list

pxtblocks/fields/field_asset.ts
When going from temporary asset -> named asset in the image/animation editor, clean up the previous temporary asset. This will delete it from the project but you can get it back using undo/redo if it was a mistake.
Fixes https://github.com/microsoft/pxt-arcade/issues/2987
=> Clean up temporary asset when exiting field editor

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_tilemap.ts, pxtblocks/fields/field_tileset.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/tilemap.ts
Fixes  microsoft/pxt-arcade#2986
Fixes microsoft/pxt-arcade#3018
This unites all of the asset emitting and all of the parsing except in the monaco fields (which have some special behavior around creating new assets if the name does not exist)
@shakao you should be able to close https://github.com/microsoft/pxt/pull/7855
@jwunderl this might conflict with https://github.com/microsoft/pxt/pull/7858 because getShortIDCore can now return undefined.
I think I tested this pretty thoroughly, but please review carefully because it touches some key stuff
=> Unite asset emitting code paths and fix tile parsing

pxtlib/github.ts
Using the wrong API to query if a repo is from an org or a user.
=> proper check of org for github

pxtblocks/blocklyimporter.ts, pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_tilemap.ts, pxtblocks/fields/field_tileset.ts, pxtblocks/fields/field_utils.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/legacyTilemap.ts, pxtlib/spriteutils.ts, pxtlib/tilemap.ts, skillmap/src/App.tsx, theme/asset-editor.less, theme/image-editor/tilePalette.less, theme/themes/pxt/globals/site.variables
- Add border to help distinguish selected/unselected asset tab (#7833)
- Compress tilemap sidebar for smaller screen sizes (#7835)
- Fix tilemap upgrade path in compiler (#7839)
- Be stricter when parsing image literals (#7849)
- Clean up temporary asset when exiting field editor (#7848)
- Unite asset emitting code paths and fix tile parsing (#7489) <- @abchatra this is the one richard was talking about in standup
- Expose more informative skillmap parsing error (#7863)
@riknoll let me know if i missed any!
=> Cherry-pick asset editor fixes, small UI updates to stable6.8

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts
tutorial steps will default to "collapsed" ("Show more...") when the tutorial is first opened. as with current behavior, if a user clicks "Show more/less" we remember that state and will persist it with that project.
to use, add this to the start of a tutorial:
```
```
for https://github.com/microsoft/pxt-arcade/issues/3047
=> Add autoexpandOff metadata option for tutorial testing

pxtlib/package.ts
This project: https://makecode.com/_JKC4gAc2xc0H was not loading in the share page because it had a "pkg:" depenency and was checking for the source in the epkg of the dependency itself. Small change to check the parent package, falling back to current behavior if there is no parent. 
This matches [here](https://github.com/microsoft/pxt/blob/master/webapp/src/package.ts#L686) where it reads the source from mainPkg, but I don't have any other examples of pkg: dependencies in the wild so it'd be great to verify that this is the intended behavior
=> Check in parent package for source of pkg: dependencies

theme/asset-editor.less, webapp/src/components/assetEditor/assetCard.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/store/assetEditorReducer.ts
build: https://arcade.makecode.com/app/ead5a05a47849e1603b61860ea0f340eb0b24e8f-405477fb68
i clicked around the asset editor and sprite/tilemap editor galleries and everything seemed okay to me, but uploading a build just in case anyone else can think of any other edge cases to try
=> Add warning icon for temp assets, update sidebar name display

theme/asset-editor.less, webapp/src/components/assetEditor/assetSidebar.tsx
render delete button as smaller text, hide button if asset is not deletable
=> Updated Delete asset button styling

pxtblocks/fields/field_note.ts
Just before stream we tried to use the block that is the notepicker on it's own and noticed it was messed up; the default color we get for the notepicker when it isn't slotted into another block is white / light gray, which makes it hard to see / very low contrast:
(sometimes as this: 
The music category color is different depending on the color (orange in micro:bit, pink in arcade) -- I can make it try and grab the default but it's a bit tedious, and I kind of like the dark gray electric piano look anyways / the color of the piano changes whenever it's used anyways:
=> set default color for note picker so it's not white notes on offwhite bkgd

pxtlib/github.ts
=> use defaultBranch info, craft better name for reference

pxtlib/docsrender.ts
Looks like checkdocs is failing the docs view of tutorials with the `autoexpandOff` flag: https://github.com/microsoft/pxt-arcade/runs/1884371908#step:6:280 from https://github.com/microsoft/pxt-arcade/pull/3105 ends up getting noted as a broken link https://github.com/microsoft/pxt-arcade/runs/1884371908?check_suite_focus=true#step:6:297 . 
Also noticed the skillmap tutorials aren't currently getting checked during checkdocs; if you want them to be then you'll want to add a summary under docs/skillmap that points to each tutorial, like https://github.com/microsoft/pxt-arcade/blob/master/docs/physics-tests/SUMMARY.md does to all in physics-tests, . That said, we do already have a 30min build for arcade so maybe leaving those off until we speed up the build wouldn't be the worst thing in …
=> fix checkdocs with autoexpandOff flag

theme/asset-editor.less, webapp/src/components/assetEditor/assetCardList.tsx
Don't love doing this in JavaScript but @shakao and I couldn't think of a clever way to do it in css. Originally I tried putting the number of empty cards in the react state but it was pretty buggy.
=> Adding empty card shadows in the asset editor gallery

pxtlib/github.ts, webapp/src/app.tsx
i think the monorepo stuff gets a little weird when loading non-README tutorials (many of these are in folders, etc); this change fixes tutorial loading but i think it also means if you're loading tutorials from a monorepo it'll load the entire repository?
wanted to do a small change to fix this for current arcade since i don't think anyone is using the monorepo functionality for tutorial content yet
=> Use github slug for tutorial project dependency

skillmap/src/lib/browserUtils.ts
skillmap does not have subpackage support, so we use the slug when checking against the list of approved repos (fullName will include the skillmap file itself)
fixes microsoft/pxt-arcade#3077
=> Use base repo when checking for approved/banned status from skillmap

webapp/src/components/ImageEditor/sprite/Palette.tsx
fix https://github.com/microsoft/pxt-arcade/issues/3135
mouse is only huge due to gif maker / it doesn't overlap normally
Took the names from https://arcade.makecode.com/reference/scene/background-color
(I think there's still value in showing the number as it corresponds to shortcut / etc so I just appended the name of the color to the end if present)
There are some node packages that will translate hexcode -> nearest named color, but that seems like a lot for now (the ones that pop up right away include like 28k colors), especially when changing the palette isn't used too much.
=> name the default colors in the image editor for accessibility

localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, theme/asset-editor.less, webapp/src/app.tsx, webapp/src/blocklyFieldView.tsx, webapp/src/components/assetEditor/editor.tsx
the metadata flag is:
```
```
this specifies the default file to open with the tutorial, overriding our inferred editor. i'm not setting the editor in the header because the asset editor is not a real "project type" the way blocks/js/python are (eg wouldn't make sense to have "preferred language" be assets, you can't have an "assets-only" project). this flag just says to open a specific file regardless of the language the tutorial snippets are in.
build loading an example tutorial: https://arcade.makecode.com/app/b415899eacdee5361fa4f112034a8cee240d3776-f4f28bddc2#tutorial:71543-65938-99537-55249
=> Support for tutorial card in asset editor view

pxtlib/tilemap.ts
fixes https://github.com/microsoft/pxt-arcade/issues/3158
=> Fix for decoding odd numbered animation width/height

webapp/src/app.tsx, webapp/src/auth.ts
Disable auth in skillmap until properly supported.
Also in this PR: force editor reloaded only if current project is in the list of synced changes. @darzu tell me if this looks ok.
Fixes: https://github.com/microsoft/pxt-arcade/issues/3138
Fixes: https://github.com/microsoft/pxt-arcade/issues/3150
cc @kiki-lee
=> Disable auth in skillmap

skillmap/src/App.tsx, skillmap/src/components/SkillCard.tsx, skillmap/src/components/SkillCarousel.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/components/SkillGraphNode.tsx, skillmap/src/components/SkillGraphPath.tsx, skillmap/src/lib/skillGraphUtils.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/lib/skillMapUtils.ts, skillmap/src/styles/skillnode.css
Trying to keep things cleanly split between the graph layout algorithm itself and the rendering. The React components only require a "depth" and "offset" per node (depth is distance along a primary axis--theoretically horizontal for desktop, vertical for tablet, offset is distance along the perpendicular axis) and then converts those to SVG units to draw. 
The graph layout is not bulletproof & works best for lower-degree graphs; we also don't handle edge crossings. We render the nodes in the order that the content creator has specified. If it turns out we do need a more robust algorithm to support content, it should be straightforward to swap out the layout function since it's separate from the rest of the implementation.
Basic layout:
- DFS traversal. Place node one unit horizontal (in …
=> Render branching layout for skill maps

package.json, pxtlib/browserutils.ts, theme/common.less, theme/image-editor/imageEditor.less, theme/themes/pxt/globals/site.variables, webapp/src/app.tsx, webapp/tsconfig.json
In certain sizes, our simulators are just at the limit of displaying the scrollbar. At this point, a bunch of resize flickering may happen.
The solution here is to always have a vertical scrollbar, but unhide only when it is needed. So, no more resizing and flickering.
ps: the scrollbar customizations for the image editor impact the whole of PXT.
=> no more simulator flickering

skillmap/src/App.css, skillmap/src/App.tsx, skillmap/src/components/InfoPanel.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/components/SkillGraphContainer.tsx, skillmap/src/components/SkillGraphPath.tsx, skillmap/src/styles/infopanel.css, skillmap/src/styles/skillgraph.css, skillmap/src/styles/skillnode.css
Stubbing out the info panel, general page restructuring to support the branching layout. The orange square is just a placeholder until we have the background image URL in the markdown.
=> Skill map v2 components, basic layout

skillmap/src/App.tsx, skillmap/src/actions/dispatch.ts, skillmap/src/components/ActionButtons.tsx, skillmap/src/components/InfoPanel.tsx, skillmap/src/components/SkillCarousel.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/components/SkillGraphNode.tsx, skillmap/src/store/reducer.ts, skillmap/src/styles/infopanel.css, skillmap/src/styles/skillnode.css
Filling in the info panel: displays activity info if an activity is selected, otherwise defaults to skill map (page-level) info. Right now we only support the title and description.
=> Fill in skill map info panel with selected activity details

webapp/src/auth.ts
I introduced this bug when disabling auth within skillmap. The auth system now starts in a disabled state, but it's fine to always let auth callbacks execute.
Fixes: https://github.com/microsoft/pxt-arcade/issues/3195
=> Unconditionally allow auth callbacks to execute

webapp/src/compiler.ts
re: https://github.com/microsoft/pxt-minecraft/pull/2117, the icons on the blocks are missing. `info.apis.jres` doesn't ever actually get persisted, and this `pkg.mainPkg.getJRes()` is the thing keeping the jres working in other parts of the editors (the apinfo.jres isn't used much, mostly just taken from blocks directly except for in https://github.com/microsoft/pxt/blob/4a6baa87e0df5c3a982264801a6fc1e8e73bd941/pxtblocks/blocklyloader.ts#L2963-L2973)
which is the thing I was using :) It looks like it would be also be pretty easy to just grab mainpkg.getJres() when calling init in blocklyloader and remove it from apiinfo entirely if we want, but there's not much harm in leaving it as far as I can tell
=> fix jres icons missing due to api caching

skillmap/src/App.tsx, skillmap/src/components/GraphNode.tsx, skillmap/src/components/InfoPanel.tsx, skillmap/src/components/SkillCarousel.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/components/makecodeFrame.tsx, skillmap/src/lib/skillGraphUtils.ts, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/lib/skillMapUtils.ts, skillmap/src/store/reducer.ts
Mostly just a refactoring of types/parsing to support different node types in the skillmap graph. I added circular nodes but they currently don't do anything. My test url is
http://localhost:3000/?nolocalhost=1#github:https://github.com/riknoll/skillmap-branch/blob/main/test.md
=> Adding reward/completion nodes

pxtlib/github.ts, pxtsim/embed.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/package.ts, webapp/src/projects.tsx, webapp/src/scriptsearch.tsx
Add a new simulator message that allows adding github extensions to the project.
- Refactors the logic to add a new dependency from the scriptsearch.tsx into classes so that it can be used in other places.
- refactor scriptsearch addDepIfNoConflict into the EditorPackage class (where it belongs)
- refactor downloading github pacakge into github.ts
- (fix minor bugs with herobanner)
=> Support for adding dependencies from messagesimulators.

pxtrunner/runner.ts, pxtsim/embed.ts
Allows to use versions when creating hashes of rendered blocks for caching.
=> return editor versions in renderready callback

webapp/src/workspace.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/3207
What I didn't realize is that our in memory cache in workspace.ts gets wiped rather aggressively by the multi-tab sync code even when there aren't any multi-tab changes.. we should fix that but for now if we just work with the assumption that u might need to rehydrate the cache from disk at any moment, things seem to work again.
=> Fix race condition between multi-tab syncAsync and partialSaveAsync

webapp/src/app.tsx, webapp/src/cloud.ts, webapp/src/editortoolbar.tsx
Fixes: https://github.com/microsoft/pxt-arcade/issues/3118
Fixes: https://github.com/microsoft/pxt-arcade/issues/3167
We use the "cloudCurrent" flag on Headers to determine if work needs to be pushed to the cloud. The problem is that each tab was assuming it should push changes for all headers that have cloudCurrent == false.
The fix was to not bother saving to cloud projects that aren't owned by this tab during the normal save loop.
Also, we were too aggressively reloading the whole editor in multi-tab scenarios. Instead we only need to reload the editor if the specific header we're editing is being edited by another tab.
=> Fix false conflicts when doing multi-tab editting

webapp/src/package.ts, webapp/src/workspace.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/3233
The problem was that the package layer was responsible for keeping the pxt.json changes in sync with the header fields, and they became desync'ed when using the single file save path.
Also there was an issue with diffing previous and new project state for the purpose of determining which changes are worth syncing to the cloud. We were updating the in-memory cache before doing the diff so we had no way to actually compare the header.
=> Fix rename not working w/ cloud save

pxtlib/github.ts, skillmap/src/lib/browserUtils.ts, webapp/src/app.tsx, webapp/src/components/ImageEditor/sprite/Palette.tsx, webapp/src/components/assetEditor/actions/dispatch.ts, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/store/assetEditorReducer.ts
- Fix hash loading of github tutorials with typescript files in the repo (#7890)
- Speed up asset gallery duplication (#7893) 
- Hides report abuse on trusted skillmaps (#7894) 
- Name the default colors in the image editor for accessibility (#7898)
=> [stable6.8] Cherry-pick image editor colors, asset duplication, github slug fixes

pxtblocks/blocklylayout.ts, pxtlib/browserutils.ts, pxtrunner/runner.ts, webapp/public/rendertest.html
Support for generating png in "renderblocks" javascript API.
It turns out that the franken-SVG we generated using "renderblocks" does not work with popular SVG rendering engine like Sharp. This SVG currently bundles the entire semantic.css so it's always at least 1.2Mb thick. This PR also generates PNGs from the iframe process so that all fonts resolved, etc...
To test: run http://localhost:3232/rendertest.html from the microbit target.
=> Render API request render to png

skillmap/src/App.tsx, skillmap/src/components/AppModal.tsx, skillmap/src/components/GraphNode.tsx, skillmap/src/components/InfoPanel.tsx, skillmap/src/components/Modal.tsx, skillmap/src/components/RewardActions.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/lib/skillGraphUtils.ts, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/lib/skillMapUtils.ts, skillmap/src/store/reducer.ts
- Clones all graph nodes before annotation
- Adds "types" for rewards (currently only supports "certificate")
- Auto-display modal the first time a reward is completed
- Properly populate the completion modal with information from that specific node (rather than the map-level completion URL)
- Fill info panel with reward info
- Update code carryover to skip reward nodes when finding previous activities (this only searches one layer down, but I think it's ok to not support the two-rewards-in-a-row scenario for now)
=> Auto-display completion modal, populate info panel for rewards

skillmap/src/lib/skillGraphUtils.ts, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts
per kiki's request for more graph layout customizability, this is a blank node that is used in layout but not actually rendered. defined in markdown as:
```
* name: Blank Node
* kind: layout
```
it's the graph algorithm's responsibility to process the layout nodes however and discard them before emitting edges
=> Add non-rendered 'layout' node for graph control

pxtlib/initprj.ts
fix https://forum.makecode.com/t/error-on-github-actions-for-makecode-arcade/6616/2, it shouldn't be running on tags getting pushed :(
=> cfg-check: do not issue spurious error on tags pushed

skillmap/src/components/GraphNode.tsx, skillmap/src/components/InfoPanel.tsx, skillmap/src/styles/graphnode.css, skillmap/src/styles/infopanel.css
implementing feedback from design office hours. main updates:
- updated "select" style (outline is offset from node)
- exclamation icon for newly unlocked (not started) activities
- hide the info panel image on mobile, small sizing tweaks
=> Skill map CSS updates, some info panel fixes, new activity icon

skillmap/src/components/GraphNode.tsx, skillmap/src/lib/skillMapParser.ts, skillmap/src/store/reducer.ts, skillmap/src/styles/graphnode.css, skillmap/src/styles/infopanel.css
shifting colors around a bit:
- primary: path, locked node 
- secondary: unlocked node
- tertiary: background
- highlight: selected stroke, reward node
exclamation point badge is the color of the reward node (highlight), completed checkmark is the color of the locked nodes (primary)
default settings:
=> Add skillmap highlight color for reward nodes + selected stroke

webapp/src/workspace.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/3232
We used to always sort by "recent use". Instead, we now sort by either the last cloud save time or the modification time.
For non-cloud projects, this is a slight change since we're showing by mod time instead of view time (but I think we agreed on this.)
For cloud projects, the reason we chose the min(lastCloudSave, mod time) is because that is the safest time to show: it'll never show a timestamp beyond when it was last saved so that the user can trust that the timestamp means "it was saved no older than this time".
=> Sort headers consistently when cloud saved
