microsoft/pxt

- webapp/src/container.tsx
- webapp/src/db.ts
> DOn't cache master for github

- pxteditor/monaco.ts
- webapp/src/monaco.tsx
fixes: microsoft/pxt-microbit#3045
> fixed shifting of editor when an error is fixed

- pxtblocks/blocklyloader.ts
- webapp/src/blocksSnippets.ts
fix for https://github.com/microsoft/pxt-microbit/issues/3080
> Change array list default to 0, 1

- webapp/src/app.tsx
- webapp/src/cloudsync.ts
- webapp/src/dialogs.tsx
When user "resets" makecode, redirect to github logout if github token is available.
> logout from github on reset

- pxtcompiler/emitter/service.ts
- pxtlib/service.ts
- webapp/src/monaco.tsx
Fixes: https://github.com/microsoft/pxt-microbit/issues/3055
After:
> Don't auto-complete with unnecessary namespace qualifiers

- localtypings/pxtpackage.d.ts
- webapp/src/app.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/3069
> fix loading sidedocs

- pxtblocks/blocklylayout.ts
- Embed semantic CSS in SVG for icons
- Add pxt-renderer class to generated SVG
We could also strip out the font and include just that in the CSS, but it felt like including the whole thing was better than doing a lot of parsing through the CSS file.
Fixes https://github.com/microsoft/pxt-microbit/issues/3084
> Embed icon font in svgs for screenshots

- webapp/src/app.tsx
> Tutorial load error

- theme/errorList.less
- webapp/src/app.tsx
- webapp/src/errorList.tsx
- webapp/src/monaco.tsx
- webapp/src/srceditor.tsx
Display simple runtime error in the error list
fixes: microsoft/pxt-microbit#3089
> display runtime errors in the error list

- package.json
- Fix breakpoints on detached blocks (https://github.com/microsoft/pxt-blockly/pull/298)
- Prefill variable rename dialog (https://github.com/microsoft/pxt-blockly/pull/300)
- Fix functionid generation when duplicating functions (https://github.com/microsoft/pxt-blockly/pull/299)
> Bump pxt-blockly to 3.0.11

- pxtcompiler/emitter/service.ts
> Removing quotes from copy paste

- webapp/src/gitjson.tsx
> simplify pr merge ui

- theme/errorList.less
- theme/highcontrast.less
fixes: microsoft/pxt-microbit#3082
> added high contrast support for the error list

- docs/extensions/approval.md
Include the LICENSE file requirement in the Extension approval checklist.
Closes #7072
> Extension approval LICENSE file requirement

- docs/editors.json
- docs/streamer.html
> Streamer 2

- docs/editors.json
- docs/streamer.html
> Streamer 3

- docs/streamer.html
Request 4/3 to fix layout with 16:9.
> handle webcam aspect ratio

- package.json
- Fix note picker crash in old Edge (https://github.com/microsoft/pxt-blockly/pull/302)
- New functions appear in middle of view (https://github.com/microsoft/pxt-blockly/pull/303)
- Fix function renaming from function dialog (https://github.com/microsoft/pxt-blockly/pull/304)
- Fix keyboard disappearing on Android (https://github.com/microsoft/pxt-blockly/pull/305)
> Bump pxt-blockly to 3.0.13

- webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/3155
> Hide file explorer in tutorial

- theme/errorList.less
- webapp/src/errorList.tsx
> error list now displays the stacktrace for runtime errors

- docs/streamer.html
> Streamer hardware

- theme/common.less
- webapp/src/simtoolbar.tsx
fix https://github.com/microsoft/pxt-microbit/issues/3173 (both issues, swapping debug and sim showing up in collapsed view on occasion)
> Swap restart and debug buttons on tablet

- docs/streamer.html
Indictae when webcam fails to start.
> Streamererrors

- docs/streamer.html
line, arrow, rectangle, whiteboard, erase
> Add point tools to streamer

- docs/streamer.html
Pass mouse event object to handlers
> streamer - fix buttons

- pxtblocks/fields/field_melodySandbox.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3125
> Fixing blockly upgrade issue in melody editor

- docs/streamer.html
Triggers a approval dialog so that we get the name of the cameras.
> streamer: pick a camera on first load

- docs/streamer.html
> Streamer: single cam

- docs/streamer.html
- docs/streamer/script.js
YouTube does not allow chat embeds anymore.
> streamer removed youtube support

- theme/errorList.less
- theme/themes/pxt/globals/site.variables
- webapp/src/errorList.tsx
- webapp/src/monaco.tsx
Added the debugger suggestion from the design meeting on 5/27
fixes: microsoft/pxt-microbit#3095
> added a debugger suggestion in the error list for runtime errors

- docs/streamer.html
- docs/streamer/script.js
Can't do anything without emojis...
> Streamer, stamp emojis

- pxtlib/packetio.ts
- pxtlib/webusb.ts
> reduce webusb messages

- theme/common.less
live site: 
beta ipad (a bit tiny and squooshed): 
w/ this:
@abchatra maybe this is one to cherry-pick? Pretty minor but ¯\\_(ツ)_/¯ logos
> fix portrait logo sizes

- webapp/src/share.tsx
Skin the qr code as a button, hide more stuff when full screened.
> better qr code button

- webapp/src/filelist.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/3201
> allow adding .json files

- cli/hid.ts
- pxtlib/hf2.ts
- pxtlib/webusb.ts
- pxtwinrt/hiddeploy.ts
- webapp/src/app.tsx
- webapp/src/cmds.ts
- webapp/src/data.ts
- webapp/src/gitjson.tsx
> Github errors

- pxtblocks/fields/field_toggle.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1861
> Fix blockly toggle positioning

- docs/streamer.html
- docs/streamer/script.js
> Streamer: support for facecam/hardware/chat together

- webapp/src/app.tsx
- webapp/src/editortoolbar.tsx
- webapp/src/projects.tsx
cherry pick https://github.com/microsoft/pxt/pull/7131 to stable
> [stable6.0] disable entry points to gh integration in pxt electron

- webapp/src/githubprovider.tsx
- webapp/src/lang.tsx
> [stable6.0] disable oauth in pxt electron

- theme/errorList.less
- theme/highcontrast.less
- theme/themes/pxt/globals/site.variables
- webapp/src/errorList.tsx
fixes: microsoft/pxt-microbit#3139
> added tab navigation for the error list

- docs/streamer.html
Display title on countdown screen.
> position title

- pxtblocks/fields/field_kind.ts
- pxtblocks/fields/field_userenum.ts
- webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1797
Requires pxt-blockly 3.0.18 https://github.com/microsoft/pxt/pull/7141
> Pass prompt hint as placeholder instead of default value

- docfiles/pxtweb/cookieCompliance.ts
- docfiles/tickevent.html
Variable for skipping analytics cookie, used by static docs pages
> Add flag for skipping cookie, shared tickEvent telemetry file

- docs/streamer.html
- docs/streamer/script.js
- Added labels that dissapear after 10s
> Streamer: support for video labels

- docs/streamer.html
- docs/streamer/script.js
support for streaming application as a web cam, e.g. streaming teams meeting into a camera frame
> Streamer: metacam

- package.json
- webapp/src/share.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/1916
> Always take screenshot when share button is clicked

- docs/static/streamer/script.js
- docs/streamer.html
Option to apply chroma key green to background to integrate into OBS.
> streamer: add option for chroma key background

- docs/static/streamer/script.js
- docs/streamer.html
Support for setting background image
> Streamer: bkgimage

- docs/blog.md
- docs/blog/SUMMARY.md
- docs/blog/microbit/2020-release.md
A quick re-post of the 'Beta' post but changed for 'Release'. Suggest some additional header text if desired.
> Blogpost for 2020 micro:bit release

- pxtlib/commonutil.ts
- pxtlib/package.ts
- webapp/src/app.tsx
Correcting for the extension author writing all lower case locales.
Fixes https://github.com/microsoft/pxt-microbit/issues/3265
> Adding all lowercase locale as part of normalization

- docs/editors.json
- docs/github-explorer.html
- docs/multi.html
- docs/static/tutorial-tool/tutorial.js
Use microbit master for most tools
- github-explorer
- multi
- streamer
> Update tools to use release micro:bit

- docs/extensions/localization.md
Add info for case sensitivity in ISO codes.
> Adding case sensitive as part of instruction

- docs/static/streamer/fabric-icons-inline.css
- docs/static/streamer/fabric-icons.json
- docs/static/streamer/script.js
- docs/streamer.html
Closed captioning via speech api
> Streamer: closed captioning

- docs/static/streamer/script.js
- docs/streamer.html
Allows to add start/end branding videos that play automatically in and out of countdown views.
> Streamer: support for intro end video

- docs/static/streamer/script.js
- docs/streamer.html
Allow for swapping hardware/facecam seamlessly
> streamer: swap videos

- docs/streamer.html
better sizing of cameras in chat view
> streamer: optimizing chat view

- docs/static/streamer/script.js
> streamer: accessbility fixes

- docs/static/streamer/script.js
Apply contrast to webgl canvas
> Streamer contrast green screen fix

- docs/extensions/pxt-json.md
- localtypings/pxtpackage.d.ts
- pxtlib/package.ts
See docs
Example https://github.com/microsoft/pxt-jacdac-services/commit/f1bd8bba9708a3641c5d210b14a88d271c31d405
> Add fileDependencies field in pxt.json

- docs/static/streamer/script.js
- docs/streamer.html
use editor as backdrop for streamer
> streamer: add option to show editor in countdown view

- docs/static/streamer/script.js
- docs/streamer.html
Hide the toolbar until needed
Slimmer margins
> Streamer - slimmer, auto-hiding tools

- docs/static/streamer/script.js
Copy-paste error in full screen checkbox.
> streamer: fix checkbox for fullscreen

- docs/static/streamer/script.js
- docs/streamer.html
Keep invisible toolbox at the same location always
more ticks
configurable blur
> Streamer: center toolbox

- docs/static/streamer/script.js
> streamer: improved analytics tracking

- docs/static/streamer/script.js
- docs/streamer.html
> streamer: keep paint tools visible

- docs/tools.md
Can't use codecards under makecode.com
> tools: codecards not support in makecode.com

- docs/static/streamer/script.js
- docs/streamer.html
Support for specifying border, background, box backgroud colors
> Streamer: support for theming.

- docs/static/streamer/script.js
- docs/static/streamer/seriously.chroma.js
- docs/static/streamer/seriously.contour.js
- docs/static/streamer/seriously.edge.js
- docs/streamer.html
> Chroma: add white outline to greenscreened videos

- docs/static/streamer/script.js
- docs/streamer.html
Report errors unhandled in promises
> Streamer: contour config + error logging

- docs/static/streamer/script.js
- docs/streamer.html
Instead of thumbnail as a scene, make it a mode which allows to move left / right, swap cameras.
> streamer: thumbnail mode

- docs/static/streamer/script.js
> Streamer: full undo support for paint tool

- docs/static/streamer/script.js
- docs/streamer.html
> Streamer: options

- docs/static/streamer/script.js
- docs/streamer.html
Refactoring toolbox to be more subtle
> Streamer: toolbarsubtle

- docs/static/streamer/script.js
- docs/streamer.html
Support for painting with touch.
> Streamer: touch support + non 16/9

- cli/youtube.ts
- docs/static/streamer/script.js
- docs/streamer.html
Removing all mixer support for streamer.
> Remove mixer from streamer/gallery

- docs/streamer.html
> streamer: allow popups

- pxtlib/util.ts
- webapp/src/app.tsx
The typecheck is throttled to median of gap between each of the last 10 keystrokes times 2 (and clamped to 300-2000ms). Seems to work fine in my testing
> Throttle typecheck based on speed of typing

- docs/editors.json
Rearranged to 
- Live editors first,
- Beta editors next,
- Other editors at the end.
> Rearranging editors in editors.json

- docs/static/playground/playground.css
- docs/static/shared/iframeeditor.css
- docs/static/tutorial-tool/tutorial.css
- docs/tutorial-tool.html
- Change docs button color, add icon 
- Align share to left edge of iframe, wider share input
- Move run button
> Small CSS updates for tutorial-tool

- docs/static/streamer/script.js
- docs/streamer.html
General purpose importer of embedded snippets by parsing iframe code.
> streamer: embed code import

- .gitignore
- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/static/streamer/tsconfig.json
> Streamer: use typescript

- pxtcompiler/emitter/service.ts
- tests/language-service/cases/completions_local_param.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/2066
> Fix parameter auto-complete in some cases

- webapp/src/errorList.tsx
- webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2084
Partial fix for https://github.com/microsoft/pxt-arcade/issues/2022 (we may still want to do something in the sim itself)
> Auto-expand list for runtime errors, clear list when monaco hidden

- docfiles/docs.html
- theme/docs.less
fixes https://github.com/microsoft/pxt-arcade/issues/1655
push everything down 😡
> Shift docs header when we have cookies

- webapp/src/components/ImageEditor/ImageCanvas.tsx
re: https://github.com/microsoft/pxt/pull/7287#pullrequestreview-445994803, I forgot about python when I added the paste from text portion (https://github.com/microsoft/pxt/pull/7270).
This also loosens the regex a bit so that it allows leading / trailing nonsense; this way it's not soo picky and lets you paste in e.g. a full sprite definition (which is helpful when using something like http://makecode-pixelart-maker.glitch.me/) or an image that had a bit of explanatory text like my elephant from the stream today that we had a bit of a hard time pasting:
```
48x48 elephant img`. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . …
```
> image editor: allow pasting python formatted image and loosen paste regex

- pxtpy/converter.ts
We're not actually using the annotation during assignment type unification, which causes problems for this case:
```
arr: List[Sprite] = []
for s in arr:
s.destroy()  # <- can't find property "destroy"
```
Fixes "Chomper" for https://github.com/microsoft/pxt-arcade/issues/2083
> Use annotation in python type unification

- pxtcompiler/emitter/service.ts
fixes https://github.com/microsoft/pxt-arcade/issues/2067
reapply fix from https://github.com/microsoft/pxt/pull/7250, it got dropped in https://github.com/microsoft/pxt/pull/7291
> reapply img snippet / completion fix

- pxtcompiler/emitter/service.ts
- pxtpy/pydecompiler.ts
- webapp/src/app.tsx
- webapp/src/compiler.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/2131
Show a dialog instead of treating the failure like a user code error.
> Show a nicer error when TS fails to convert to Python

- cli/buildengine.ts
- cli/cli.ts
- cli/gdb.ts
- pxtcompiler/emitter/hexfile.ts
- pxtlib/emitter/assembler.ts
* set build engine before various gdb operations
* support for `PXT_NODOCKER=force`
* support for .bin files in ELF target
> fixes for build engine settings

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
Support for displaying restream chat in stream
> streamer: support for restream

- docs/writing-docs/macros.md
- pxtlib/docsrender.ts
- webapp/src/app.tsx
> Option to disable auto-opening of readme in makecode

- docs/static/streamer/script.js
- docs/static/streamer/seriously.contour.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
Use FHD, 16:9 camera format as it is much more common these days than 4:3
> Streamer: 16/9, hd

- pxteditor/monaco-fields/field_tilemap.ts
- pxtlib/spriteutils.ts
- webapp/src/compiler.ts
- webapp/src/package.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2146
Fixes https://github.com/microsoft/pxt-arcade/issues/2108
> make sure python refreshes API info when tilemaps change

- pxtlib/tutorial.ts
Replace img`........` to img` ` in spy tutorials.
> compact images in tutorials

- pxtsim/langsupport.ts
- tests/compile-test/lang-test0/15references.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1808
@abchatra safe to cherry pick
> Initialize captured mutables to undefined

- localtypings/pxtarget.d.ts
- pxteditor/monaco-fields/field_tilemap.ts
- pxtlib/tilemap.ts
- pxtpy/converter.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2170
Also needs https://github.com/microsoft/pxt-common-packages/pull/1150
> Fix the tilemap literal in python and helper

- webapp/src/share.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/2132
> Hide QR code dialog when clicking close

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
Support for stinger powered by youtube videos
> Streamer: youtube stinger

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
Allow for uploading video overlays for cameras
> streamer: facecam overlay

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
It should be easy to create custom stingers without having to get pro-video software.
> Streamer: support for multi-stringer and green screen

- pxtblocks/fields/field_utils.ts
- pxtlib/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2205
> Adding tiles from project tilemaps to the cached tileset list in blocks

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
> Streamer: race in indexed db load

- pxtlib/tutorial.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2261
> Fixing tutorial issue with python

- pxtlib/github.ts
Port of https://github.com/microsoft/pxt/pull/7359
Tested on localhost.
> github pages fix [stable6.0]

- pxtlib/github.ts
Port of https://github.com/microsoft/pxt/pull/7359
> handle changes in github apis (#7359) [stable6.1]

- docs/static/tutorial-tool/tutorial.js
- docs/static/tutorial-tool/tutorial.ts
- docs/tutorial-tool.html
JS here is entirely regenerated from the updated TS
> Sync tutorial tool TS with JS

- webapp/src/monacoSnippets.ts
fix for builtin snippets https://github.com/microsoft/pxt-minecraft/issues/1879
> Add spaces to monaco for/while snippets

- common-docs/types/function/call.md
- common-docs/types/function/define.md
- common-docs/types/function/return.md
Add a reference page for the function **return** statement.
Closes https://github.com/microsoft/pxt-arcade/issues/2253
> Add a ref page for function 'return'

- pxtlib/tilemap.ts
- pxtrunner/runner.ts
- webapp/src/blocklyFieldView.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2256
> Make sure that pxt.react.getTilemapProject is defined in pxtrunner

- pxtsim/localization.ts
Copied over from commonutil.ts
> Port lf string format to sim localization functions

- docs/writing-docs/user-tutorials.md
Ah sorry, forgot to push the change for your comment on https://github.com/microsoft/pxt/pull/7393 !
> Add explanation of 'recipe' term

- webapp/src/components/ImageEditor/ImageCanvas.tsx
- webapp/src/components/ImageEditor/util.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2353
Fixes https://github.com/microsoft/pxt-arcade/issues/1785
Extends copy/paste support to the tilemap editor! Unlike the image editor there is no nice text representation of the copied data so no pasting into monaco. The copied data includes the floating layer, all tiles within the floating layer, and wall data. If the tiles don't already exist in the destination tilemap then they get added to the project tile palette.
@jacobcarpenter FYI
> Adding copy/paste support for tilemaps

- pxtblocks/composablemutations.ts
- pxtblocks/fields/field_argumentvariable.ts
- pxtblocks/fields/field_variabledropdown.ts
fixes https://github.com/microsoft/pxt-minecraft/issues/657
Subclass of FieldVariable so we can filter out the "Delete" option
> Add new FieldVariableDropdown subclass 

- cli/cli.ts
fix https://github.com/microsoft/pxt-arcade/issues/2365
Issue was it was fetching translations before the _locales ever got generated. We didn't run into this in microbit because those _locales get checked in. This adds a call to gendocs to make sure those get created properly (and converts to async / await as it was getting a bit messy).
I guess side question, should we stop checking those in to pxt-microbit / remove them and https://github.com/microsoft/pxt-arcade/tree/master/sim/public/locales? Peli I think you mentioned before you like them being checked in because it makes it obvious when apis change
> generate _locales files before pulling translations in static pkg

- pxtlib/emitter/cloud.ts
fix https://github.com/microsoft/pxt-arcade/issues/2361
The issue is that we currently always return the markdown from markdownAsync, even if it's weeks / months / years old. In the linked issue, it appears a prior test version of the electron app had been installed a long time ago, so it had a very old / broken homepage until a refresh.
This gives a second tier - if the content is over a week old, ignore the cached content completely and wait for the new content to come in. This helps minimize the chance old content just 404s, or is completely invalid due to e.g. changes in external dependencies. I think this along with the change @livcheerful is working on to invalidate the caches when we get new editor versions should handle most cases of broken links / examples on home page?
I have …
> if cached markdown > a week old, wait for new markdown

- webapp/src/app.tsx
- webapp/src/monaco.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/1761
Not sure if this will affect accessibility or anything?
> Default to focus on monaco loading

- docs/writing-docs/tutorials.md
To merge after Minecraft release
> Document lockedEditor=1 flag for tutorials

- pxtsim/embed.ts
- webapp/public/run.html
- webapp/src/appcache.ts
checking for appache being available.
> Fixing appcache for Chibi in Chrome

- docs/extensions/getting-started.md
Update instructions to sign in to GitHub for extension creators.
Closes https://github.com/microsoft/pxt-microbit/issues/3372
> Update sign in instructions for ext get started

- webapp/src/workspace.ts
Lemme know if we don't want this - I'm adding this for https://github.com/microsoft/pxt-minecraft/issues/1936 , since Sheila expected the Reset button to help her recover, but it didn't
> Clear indexed db on reset

- pxteditor/shell.ts
- pxtlib/commonutil.ts
- pxtlib/webusb.ts
- webapp/src/app.tsx
- webapp/src/blocks.tsx
- webapp/src/cmds.ts
- webapp/src/container.tsx
- webapp/src/toolbox.tsx
- webapp/src/workspace.ts
We should not access localStorage directly as it throws in the wrong security context. Same for webusb.
Impacts micro:bit, will require a hot fix.
> guard localStorage + webusb access

- pxteditor/shell.ts
- pxtlib/commonutil.ts
- pxtlib/webusb.ts
- webapp/src/app.tsx
- webapp/src/blocks.tsx
- webapp/src/cmds.ts
- webapp/src/container.tsx
- webapp/src/toolbox.tsx
- webapp/src/workspace.ts
Guard against WebUSB/localStorage security exceptions. Might need to go in Arcade.
Ported https://github.com/microsoft/pxt/pull/7469 to master.
> apply fixes for webusb/localStorage

- cli/crowdin.ts
I was looking over the output of my translation stuff and noticed some files I didn't expect were listed in crowdin. The issue is that when gathering ignored folders, it was only checking the direct parent dirs of files, so if you have something like
```
|_my-cool-stuff
|_.crowdinignore
|_subfolder1
|_not-uploaded-content.md
|_other-not-uploaded-content.md
|_subfolder2
|_last-file.md
```
all those md files would get uploaded as `/my-cool-stuff/.crowdinignore` didn't get checked -- just `/my-cool-stuff/subfolder1/.crowdinignore` and  `/my-cool-stuff/subfolder2/.crowdinignore`
> handle crowdinignore when dir only contains other subdirs

- common-docs/types/function/define.md
Expand the function 'Define' page to include a parameters section.
Closes https://github.com/microsoft/pxt-microbit/issues/3367
> Add function 'define' parameters section

- package.json
- pxtblocks/blocklyloader.ts
- pxtlib/blocks.ts
Localization for https://github.com/microsoft/pxt-blockly/pull/325 and https://github.com/microsoft/pxt-blockly/pull/322
and bumping blockly.
> Bumping Blockly

- package.json
bump blockly to pick up https://github.com/microsoft/pxt-blockly/pull/327
> bump blockly for mobile num fix

- webapp/src/monacoFlyout.tsx
fix https://github.com/microsoft/pxt-microbit/issues/3394
> translate headers for monaco flyout

- webapp/src/monacoFlyout.tsx
port https://github.com/microsoft/pxt/pull/7482 to microbit stable
> [stable6.0] translate headers for monaco flyout

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
Cache loaded editor iframes to retain state
> streamer: cache loaded editor iframe

- pxtlib/util.ts
- pxtrunner/runner.ts
port https://github.com/microsoft/pxt/pull/7478 to microbit stable
> [stable6.0] Don't request all files at once when building course book (#7478)

- localtypings/pxtarget.d.ts
- pxtlib/emitter/cloud.ts
- pxtlib/util.ts
- webapp/src/app.tsx
- webapp/src/auth.ts
- webapp/src/data.ts
- webapp/src/fileworkspace.ts
- webapp/src/identity.tsx
- webapp/src/projects.tsx
This PR merges my and @darzu's work. It adds an api for authentication, and a nascent "virtual api" for user profile. This virtual api will serve the data source for React components that show user profile state.
> Client API for auth

- pxtsim/simlib.ts
fixes https://github.com/microsoft/pxt-arcade/issues/2441
cc @klausw
> Fix sound frequency sweeps

- common-docs/blocks/custom.md
Because I accidentally deleted mine and couldn't retrieve it so I spent half an hour to search the web until I found a Taiwanese translation that made it possible for me to fit the pieces back together.
> Added custom.ts

- pxtlib/tilemap.ts
- pxtwinrt/winrtworkspace.ts
- webapp/src/app.tsx
- webapp/src/components/ImageEditor/tilemap/TilePalette.tsx
- webapp/src/components/assetEditor/assetSidebar.tsx
- webapp/src/components/assetEditor/assetTopbar.tsx
- webapp/src/components/assetEditor/editor.tsx
- webapp/src/components/assetEditor/store/assetEditorReducer.ts
- webapp/src/container.tsx
Bundle of small fixes, I added comments to identify each. Also unifying the code for updating tiles when exiting the tilemap editor.
> Small asset editor cleanup, fixes

- pxtblocks/fields/field_animation.ts
- pxtlib/spriteutils.ts
- pxtlib/tilemap.ts
- webapp/src/components/ImageFieldEditor.tsx
Aligning with the other asset types.
> Animation encode/decoding and updating animation field editor

- theme/asset-editor.less
- theme/common.less
- webapp/src/components/assetEditor/assetGallery.tsx
- webapp/src/container.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2505
Fixes https://github.com/microsoft/pxt-arcade/issues/2499
CSS pass for https://github.com/microsoft/pxt-arcade/issues/2478
(Darker one is hover behavior)
> Fix toggle language behavior, some CSS updates

- webapp/src/editortoolbar.tsx
- webapp/src/tutorial.tsx
Resize the headers when we scroll with mouse! and touch
The slider will update for the wheel scroll, but not with touch. Do you guys think that's okay?
> Resize headers ALL the time

- pxtrunner/runner.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2444
> Compile API info for projects shared in Python

- theme/tutorial.less
- webapp/src/editortoolbar.tsx
- webapp/src/tutorial.tsx
look how flush!
also more padding below 'Toolbox'
> Increase workspace header height, fix toolbox header alignment issue

- pxteditor/monaco-fields/field_sprite.ts
> Add newlines to monaco sprite editor regex

- cli/server.ts
Was getting "write after end" errors in node v14. Error branch should return.
> missing return after 404 branch

- skillsmap/src/lib/skillMap.d.ts
- skillsmap/src/lib/skillMapParser.ts
- skillsmap/src/lib/skillMapUtils.ts
- skillsmap/src/lib/workspaceProvider.ts
Very simple syntax:
Single # header defines the skills map
Double ## header defines an activity
Key value pairs are just `key: value` and are case insensitive for the keys
For map prerequisites, they can be either skills maps you must have finished or tags
> Parse skills map

- docs/writing-docs/tutorials/control-options.md
feel free to move or anything if this isn't the right place to put this documentation!
> Add documentation for tutorial lockedEditor url flag

- cli/gdb.ts
Add example pointers
@abchatra no need to merge; I don't think anyone besides me is using this
> Fix 'pxt heap' crash on micro:bit

- webapp/src/cmds.ts
The retry is not needed anymore and is a buggy codepath.
> hid: don't retry flash

- skillsmap/src/App.css
- skillsmap/src/App.tsx
- skillsmap/src/components/Banner.tsx
- skillsmap/src/components/HeaderBar.tsx
- skillsmap/src/styles/carousel.css
Just stubbing out the components to fill out the page a bit
> Add banner and header components

- skillsmap/src/components/Carousel.tsx
- skillsmap/src/components/SkillCard.tsx
- skillsmap/src/components/SkillsCarousel.tsx
- skillsmap/src/styles/carousel.css
- skillsmap/src/styles/skillcard.css
> Card flip CSS to display additional activity info

- pxtlib/cpp.ts
This is generic version of https://github.com/microsoft/pxt-microbit/pull/3597 for future use
> Add PXT_TARGET #define in codal

- theme/common.less
- webapp/src/auth.ts
- webapp/src/identity.tsx
- webapp/src/user.tsx
* Remove "Request data" button
* Combine Privacy and Account panels
* Simplify CSS
> Profile page updates

- cli/cli.ts
Fix for https://github.com/microsoft/pxt/issues/7380
> adding more logging in checkdocs for unresolved md

- pxtrunner/renderer.ts
fix https://github.com/microsoft/pxt-minecraft/pull/1945#issuecomment-724883441
> only show blocks in block / api gallery

- pxtlib/emitter/cloud.ts
- pxtlib/util.ts
- webapp/src/auth.ts
- webapp/src/fileworkspace.ts
Reverted changes in:
* cloud.ts
* util.ts
* fileworkspace.ts
Moved `BACKEND` selection to auth.ts. This gives backend devs flexibility to run against localhost or not.
fixes #7602
> fix for #7602, and address feedback

- package.json
Pull in a fix for https://github.com/microsoft/pxt-microbit/issues/3496
> Bump blockly

- webapp/src/dialogs.tsx
Display links to each compile service in multi-variant editors.
> show all links for multivariant editors

- skillmap/src/App.css
- skillmap/src/App.tsx
- skillmap/src/lib/browserUtils.ts
- skillmap/src/styles/carousel.css
- skillmap/src/styles/modal.css
- skillmap/src/styles/skillcard.css
- Scale card on hover, darken color
- Display error message when markdown load/parse failed
- Fix for modal CSS, handle null pxtTargetBundle
> CSS updates, error handling, error message

- skillmap/src/components/AppModal.tsx
- skillmap/src/lib/skillMap.d.ts
- skillmap/src/lib/skillMapParser.ts
For "Certificate" link in completion modal
> Add 'completionurl' property per skill carousel

- docs/translate.md
Updated on the in-context translation page
> shuffle in-context

- cli/cli.ts
- skillmap/src/components/AppModal.tsx
- skillmap/src/components/HeaderBar.tsx
- skillmap/src/components/SkillCard.tsx
- skillmap/src/components/SkillCarousel.tsx
- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/lib/browserUtils.ts
List of events:
skillmap.activity.open - Activity is opened from the skills map ("Start", "Continue", or "View Code" button clicked)
skillmap.activity.loaded - Activity is loaded in the iframe
skillmap.activity.complete - Activity is completed in the iframe
skillmap.activity.back - Back arrow clicked in the iframe
skillmap.activity.restart - Clicks "Restart" in the warning modal
skillmap.activity.next - Not currently hooked up, but clicks "Next" in the completion modal
skillmap.certificate - Clicks "Certificate" in the modal
skillmap.carousel.item - Clicks on a carousel item to view details
skillmap.carousel.endcard -  Clicks on the end card to view completion modal
> Tick events for skill map

- webapp/src/core.ts
- webapp/src/coretsx.tsx
- webapp/src/user.tsx
> Identity: Prompt user to enter name in order to delete account

- webapp/src/app.tsx
Cherry-pick https://github.com/microsoft/pxt/pull/7639
> Clear editor filters when opening a new empty project (#7639)

- pxtlib/tutorial.ts
- skillmap/src/App.tsx
- skillmap/src/index.tsx
- skillmap/src/lib/browserUtils.ts
- webapp/src/app.tsx
Redo of other pr because of merge shenanigans
> Support translated skillmaps

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- package.json
Upgraded and rebuilt streamer for new consent js.
> Use consent in streamer

- docfiles/script.html
- docfiles/targetconfig.html
- localtypings/pxtarget.d.ts
- webapp/public/run.html
> [stable6.2] Simulator tick events (#7644)

- skillmap/public/index.html
> Embed Usabilla widget on skill map page

- docs/writing-docs/tutorials/activities.md
- docs/writing-docs/tutorials/basics.md
Update the tutorial pages for changes to the step modifiers.
RE: #7490
> Update tutorial docs for new step modifiers

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
- package.json
> streamer: shortcut to add a new web site

- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
- docs/streamer.html
> streamer: bigger face

- pxtlib/tutorial.ts
- skillmap/public/index.html
- skillmap/src/App.tsx
- skillmap/src/actions/dispatch.ts
- skillmap/src/components/Dropdown.tsx
- skillmap/src/components/HeaderBar.tsx
- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/index.tsx
- skillmap/src/lib/browserUtils.ts
- skillmap/src/lib/skillMap.d.ts
- skillmap/src/store/reducer.ts
- webapp/src/app.tsx
Cherry picking these PRs to stable 6.2:
#7641
#7648 
#7649 
#7669
> Stable6.2 skillmap update

- webapp/src/filelist.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2576
> Always show plus button if multiple custom files are allowed

- theme/asset-editor.less
- webapp/src/components/assetEditor/assetSidebar.tsx
- webapp/src/sui.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2605
Fixes https://github.com/microsoft/pxt-arcade/issues/2548
> Center asset preview, show disabled delete button

- docfiles/tickevent.html
> [stable6.2] Dont lose tick events, attach target (#7655)

- skillmap/public/index.html
- skillmap/src/App.css
- skillmap/src/components/AppModal.tsx
- skillmap/src/components/SkillCard.tsx
- skillmap/src/styles/dropdown.css
- skillmap/src/styles/makecode-editor.css
- skillmap/src/styles/modal.css
- skillmap/src/styles/skillcard.css
- Move Usabillia widget lower
- Dark purple restart icon
- Slower card flip+ separate card flip transform and hover (scale) transform
- Report abuse dropdown z index
- Tweak restart modal text, page title
> Small skillmap style and wording fixes

- localtypings/pxtarget.d.ts
- skillmap/src/App.tsx
- skillmap/src/lib/browserUtils.ts
Requires corresponding targetconfig change in pxt-arcade https://github.com/microsoft/pxt-arcade/pull/2618
> Move default skillmap URL into targetconfig.json

- docs/blog/.crowdinignore
Disable crowdin for blog folder.
Fix for https://github.com/microsoft/pxt/issues/7673
> disable translations in blog

- skillmap/src/actions/dispatch.ts
- skillmap/src/components/SkillCarousel.tsx
- skillmap/src/lib/browserUtils.ts
- skillmap/src/styles/carousel.css
Fixes https://github.com/microsoft/pxt-arcade/issues/2644
Fixes https://github.com/microsoft/pxt-arcade/issues/2652
> Fix first card animation, allow card deselect

- pxteditor/shell.ts
- skillmap/public/index.html
- skillmap/src/actions/dispatch.ts
- skillmap/src/components/SkillCarousel.tsx
- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/styles/carousel.css
- webapp/src/app.tsx
- Fix for card animation, margins 
- Patch header name to match card
- Add noproject=1 flag to fix issue with loading into iframe without tutorial
- Add thin footer
> Cherry-pick fixes for skillmap to stable6.2

- skillmap/src/App.css
Fixes microsoft/pxt-arcade#2651
Fixes microsoft/pxt-arcade#2667
> Hide outer cookie banner in skillmap

- skillmap/src/App.css
- skillmap/src/components/makecodeFrame.tsx
More skillmap cherry picks
#7702 
#7703
> Stable 6.2picks

- pxtlib/analytics.ts
We are not doing a clone but accumulating the default properties as we go.  Yikes
> Fixing default properties in the analytics

- webapp/src/carousel.tsx
- webapp/src/projects.tsx
> Home ticks

- pxtsim/runtime.ts
> don't dispatch messages on dead runtime

- pxtsim/simdriver.ts
Use the correct origin based on who started the iframe.
> store origin of iframe

- Makefile
- pxtcompiler/simpledriver.ts
This allows the MKC tool https://github.com/microsoft/pxt-mkc use the same package resolution logic as website.
> Allow GH package resolution in SimpleDriver

- pxtblocks/fields/field_asset.ts
- pxtlib/spriteutils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2463
> Fix resolution of transparency when decoding tilemaps

- pxtcompiler/emitter/snippets.ts
- pxtpy/converter.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2503
> Better snippet for tagged templates

- gulpfile.js
- skillmap/package.json
tested on command prompt, git bash, powershell--seems to work! did not test on mac but it's just using default gulp commands so i feel like it should be ok
> Move webpack override/copy code for skillmap build into gulpfile

- skillmap/package.json
Fixes the skillmap local serve
> Specify typescript parser for skillmap eslint

- skillmap/public/index.html
match format of https://github.com/microsoft/pxt/blob/master/webapp/public/index.html#L2 
fixes https://github.com/microsoft/pxt-arcade/issues/2611
> Use locale for HTML lang specification in skillmap

- webapp/src/components/ImageFieldEditor.tsx
- webapp/src/components/assetEditor/store/assetEditorReducer.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2796
> Make sure the asset currently in the editor shows up in the gallery

- webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2785
> Make color select tool respect floating layer

- pxtlib/skillmap.ts
- skillmap/src/App.tsx
- skillmap/src/store/reducer.ts
moving the user version into `pxt.skillmap` and fixing a build error in App.tsx
> Fixing build error in skillmap

- webapp/src/cloud.ts
- webapp/src/workspace.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/2859
Test here: https://arcade.staging.pxt.io/app/ce4a8d4561497ba3c2549746bf98e04b0b80e9ec-6ef86a60c6
> Acquire header session before cloud saving

- webapp/src/app.tsx
- webapp/src/auth.ts
It was checking for "undefined" !== "null" and returning true.
Fixes: https://github.com/microsoft/pxt-arcade/issues/2864
Fixes: https://github.com/microsoft/pxt-arcade/issues/2722
We really should remove the location.reloal() all together.
> Fix infinite reload if language wasnt set; fix setting High Contrast

- webapp/src/dialogs.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2810
> Fixing 0 in about diaglog

- pxtblocks/fields/field_asset.ts
- pxtlib/spriteutils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2787
> fix sprite duplicate

- webapp/src/app.tsx
- webapp/src/cloud.ts
- webapp/src/identity.tsx
- webapp/src/workspace.ts
I believe these tick events can help us answer most anonymous questions about auth and cloud sync. See Identity chat for more discussion.
Fixes: https://github.com/microsoft/pxt-arcade/issues/2884
> Add identity & cloud sync tick events

- pxtpy/converter.ts
- tests/pyconverter-test/baselines/primative_types.ts
- tests/pyconverter-test/cases/primative_types.py
Fixes: https://github.com/microsoft/pxt-arcade/issues/2860
Fixes: https://github.com/microsoft/pxt-arcade/issues/2471
> Fix python boolean array error

- webapp/src/components/ImageFieldEditor.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2902
> Fix bug where assets in my assets tab appear duplicated

- webapp/src/components/assetEditor/actions/dispatch.ts
- webapp/src/components/assetEditor/assetSidebar.tsx
- webapp/src/components/assetEditor/editor.tsx
- webapp/src/components/assetEditor/store/assetEditorReducer.ts
one fix in each commit
fixes https://github.com/microsoft/pxt-arcade/issues/2908
fixes https://github.com/microsoft/pxt-arcade/issues/2900
> Fix asset tooltip, load animations in asset tab gallery

- common-docs/reference/arrays/pick-random.md
- libs/pxt-common/pxt-core.d.ts
Add a ref page for ``Array._pickRandom()``.
RE: https://github.com/microsoft/pxt-arcade/issues/2923
RE: #5972
> Ref page for 'pick Random'

- webapp/src/components/ImageFieldEditor.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/2922
also don't always filter for tags because user assets don't have tags
> Show tile assets if editing a tile

- webapp/src/components/assetEditor/assetGallery.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2931
> Filter temporary assets based on preferred editor

- webapp/src/components/assetEditor/assetGallery.tsx
https://github.com/microsoft/pxt/pull/7814
> Cherry pick #7814 to stable6.8

- webapp/src/components/ImageEditor/store/imageReducer.ts
- webapp/src/components/ImageEditor/toolDefinitions.ts
- webapp/src/components/ImageFieldEditor.tsx
https://github.com/microsoft/pxt/pull/7816
> Last minute cherry pick of https://github.com/microsoft/pxt/pull/7816

- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/lib/browserUtils.ts
Dropped this commit while wrangling the other fixes!
> Skillmap iframe path should match skillmap path

- skillmap/src/store/reducer.ts
fixes https://github.com/microsoft/pxt-arcade/issues/2956
> Check that current activity is about to be completed before showing modal

- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/lib/browserUtils.ts
- skillmap/src/store/reducer.ts
- webapp/src/components/ImageFieldEditor.tsx
- webapp/src/components/assetEditor/editor.tsx
Cherry picking a few PRs to stable 6.8
https://github.com/microsoft/pxt/pull/7820
https://github.com/microsoft/pxt/pull/7821
https://github.com/microsoft/pxt/pull/7822
> Cherry picking a few PRs to stable 6.8

- webapp/src/components/ImageEditor/BottomBar.tsx
> [stable6.8] limit tilemap editor to 255x255 (#7823)

- pxteditor/experiments.ts
Hiding identity experiment for the next release.
> hide identity experiment

- pxteditor/experiments.ts
- webapp/src/auth.ts
- webapp/src/user.tsx
Language updates to clarify profile vs/ account.
Also reverting dev backend to point to staging. That will be a more useful default for most.
> Updates to identity language

- pxtlib/gallery.ts
Fix for https://github.com/microsoft/pxt-arcade/issues/3020#issuecomment-771888706
Try to parse cards HTML as UL/OL tree; and bail out to JSON if failing.
> parse new format first

- webapp/src/core.ts
- webapp/src/coretsx.tsx
- webapp/src/identity.tsx
- webapp/src/sui.tsx
- webapp/src/user.tsx
Cherry-pick #7850 to stable6.8
built and tested locally
> Cherry-pick Update profile delete ux (#7850) to stable6.8

- skillmap/README.md
feel free to suggest changes if any of this is unclear! adding you guys because you are the first ones to have run through the skillmap local build, i think
> Update skillmap README with pxt serve step

- skillmap/src/App.tsx
we have specific errors for parsing ("branching not supported", "activity XYZ missing") we should just pipe them to the user so content creators can debug
> Expose more informative skillmap parsing error

- pxtblocks/composablemutations.ts
Cherry pick https://github.com/microsoft/pxt/pull/7845 for blockly crash
> 🍒Cherry pick

- localtypings/pxtpackage.d.ts
- theme/common.less
- webapp/src/app.tsx
- webapp/src/cloud.ts
- webapp/src/codecard.tsx
- webapp/src/editortoolbar.tsx
- webapp/src/projects.tsx
- webapp/src/scriptmanager.tsx
- webapp/src/workspace.ts
This removes the extra reload after a cloud sync, mitigates infinite reload bugs, and fixes numerous bugs around project deletion.
> [cherry pick] Improve UX for cloud save (#7836)

- webapp/src/app.tsx
- webapp/src/tutorial.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/2109
- Change modal confirmation button from 'Start' -> 'OK'
- Fix workspace creeping on the top toolbar
- Add classes to the modal to only use HOC styling on tutorials with hideIteration used
> Minecraft UI fixes

- webapp/src/keymap.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3097
> Fix keymap bug

- theme/asset-editor.less
- webapp/src/components/assetEditor/assetSidebar.tsx
changes from design office hours
> Small CSS updates for temporary asset warning

- webapp/src/components/assetEditor/actions/dispatch.ts
- webapp/src/components/assetEditor/assetSidebar.tsx
- webapp/src/components/assetEditor/store/assetEditorReducer.ts
fixes microsoft/pxt-arcade#3071
> Speed up asset gallery duplication, combine reducer actions

- common-docs/github/test-extension.md
A request from @microbit-mark to expand this a little more. Do I add info about opening a extension/project using the import feature?
> Reword github extensions test page

- docs/editors.json
- docs/static/streamer/script.js
- docs/static/streamer/streamer.ts
> add arcade skillmap to list of editors

- pxteditor/editorcontroller.ts
- webapp/src/compiler.ts
- webapp/src/simulator.ts
Surface compilation diagnostics through editor interface
> add workspacediagnostics

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpr.yml
- .github/workflows/pxt-buildpush.yml
Probably needs to be ported to stable
Should fix https://github.com/microsoft/pxt-microbit/issues/3875
> Add production flag

- webapp/src/app.tsx
Cleanup React warnings for https://github.com/microsoft/pxt/pull/7926
> fixing react issues in addextensions dialog

- webapp/src/app.tsx
- webapp/src/auth.ts
- webapp/src/workspace.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/3150
> Disable auth in iframe scenarios (e.g. skillmap)

- webapp/src/auth.ts
- webapp/src/cloud.ts
> fix project export on profile delete

- skillmap/src/App.css
- skillmap/src/components/ActivityActions.tsx
- skillmap/src/components/InfoPanel.tsx
- skillmap/src/components/MapActions.tsx
- skillmap/src/styles/infopanel.css
- skillmap/src/styles/skillgraph.css
filling out the info panel with details about the overall map, reset button, small styling updates for tags and label for locked/completed
> Fill out info panel details for map, CSS updates

- cli/cli.ts
- skillmap/README.md
- skillmap/public/index.html
- skillmap/src/App.tsx
- skillmap/src/components/GraphNode.tsx
- skillmap/src/components/InfoPanel.tsx
- skillmap/src/components/SkillGraph.tsx
- skillmap/src/lib/skillMapUtils.ts
- skillmap/src/styles/graphnode.css
> Add completion icons and use block icon for activities in skillgraph

- skillmap/src/App.css
- skillmap/src/components/ActivityActions.tsx
- skillmap/src/components/InfoPanel.tsx
- skillmap/src/components/MapActions.tsx
- skillmap/src/components/RewardActions.tsx
- skillmap/src/components/SkillGraph.tsx
- skillmap/src/styles/infopanel.css
@soniakandah i'm also going to bring all of this to design office hours tomorrow, but just fyi here is where we're at!
> Tablet view for skill map v2

- webapp/src/components/ImageEditor/sprite/Palette.tsx
fix https://github.com/microsoft/pxt-arcade/issues/3242
> tooltip for selected/bkgd color

- docs/multi.html
When add ?beta=1, allow to use micro:bit beta.
> better support for beta in multi

- skillmap/src/components/InfoPanel.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3286
> Fix completed activity count for first map activity

- pxtblocks/blocklylayout.ts
Our current format function just randomly orders them based on the order that blockly returns. This changes that to sort the blocks in this order:
1. on-start (still always top left)
2. events (sorted by type)
3. user functions
4. disabled blocks
5. comments (previously these were always first after on-start)
We still group comments w/ events when decompiling. This order is better for a few reasons: it looks nicer, blocks are logically grouped together, smaller blocks (disabled blocks and comments) are now at the end so they don't break the formatting of other rows.
Here is an example of sorting [tony albatross](https://makecode.com/_MKbcr8hE9YCi)
Current behavior (no sorting):
After changes:
> Improve workspace formatting

- skillmap/src/App.css
- skillmap/src/components/ActivityActions.tsx
- skillmap/src/components/GraphNode.tsx
- skillmap/src/components/HeaderBar.tsx
- skillmap/src/components/InfoPanel.tsx
- skillmap/src/lib/skillMapUtils.ts
- skillmap/src/styles/graphnode.css
1. header title is now the same size as other header text
2. completed activities no longer have a checkmark in the corner, it now replaces the block icon
3. hover on graph nodes inverts the colors
4. "save to my projects" moved from the header to the info panel
> Design feedback

- skillmap/src/components/GraphNode.tsx
> Adding stars instead of circle icons

- localtypings/pxtarget.d.ts
- skillmap/src/App.tsx
- skillmap/src/lib/browserUtils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3281
Marking draft because I need to merge some changes into targetconfig.json to actually test this.
> Adding path aliases for skillmap

- webapp/src/editortoolbar.tsx
Fixes: https://github.com/microsoft/pxt-arcade/issues/3326
> Hide cloud button when signed out / identity isn't enabled

- pxtsim/simlib.ts
Make it less startling: can compare https://arcade.makecode.com/79623-16989-79723-53384 and https://arcade.makecode.com/app/ec5c0258e39de822efe8382124500bd128aff490-58aedfd1f9#pub:79623-16989-79723-53384
> cut sim volume a bit

- docs/writing-docs/tutorials/control-options.md
- docs/writing-docs/tutorials/resources.md
Add/expand some sections to the tutorial docs for Asset support.
RE: #7899
> Update the tutorial docs for 'assets'

- pxtblocks/fields/field_kind.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3363
> Don't allow reserved words in kinds

- pxtlib/service.ts
Small refactor for localizeApisAsync I did while debugging https://github.com/microsoft/pxt/pull/8000, as I wasn't sure where the bug was / having this function be async was easier to step through than promise chains. Only notable change is it doesn't `Util.jsonMergeFrom(loc, apiLocalizationStrings);` for every api anymore if apiLocalizationStrings exists, and await makes it so we don't have to do the empty promise to allow for inContext translation mode to fetch the real strings.
> flatten localizeApisAsync a bit by converting to async

- theme/highcontrast.less
- theme/tutorial.less
fixes https://github.com/microsoft/pxt-arcade/issues/3318
for non-HC mode, it was really hard to see when the button was focused/hovered on. it's better now!
> Make it more obvious when Immersive Reader is focused/hovered on

- pxtlib/tutorial.ts
- theme/highcontrast.less
- theme/tutorial.less
- webapp/src/immersivereader.tsx
- more immersive reader beautification #7986
- More tutorial cleaning for Immersive Reader #8002 
- Make it more obvious when Immersive Reader is focused/hovered on #8011
> [stable6.12] Immersive Reader ports

- webapp/src/cloud.ts
* Adds more identity tick events
* more robust cloud sync error handling
* wrap in Error()
> More robust cloud sync error reporting (#7997)

- pxtlib/emitter/cloud.ts
minecraft port of https://github.com/microsoft/pxt/commit/db148da35097f5fd0df1cf234287052f16e89ed1
> [stable6.4] don't fetch unapproved translations

- pxtlib/tutorial.ts
brings back #7995 which was eaten up by #8002 :(
> Restore snippet matching change

- common-docs/faq.md
- webapp/src/immersivereader.tsx
* Adds the tutorial step and other values to the close tick. I think it would make it possible to see how long people spend in the immersive reader per step?
* Adds the immersive reader url to  https://arcade.makecode.com/faq
> Small Immersive Reader changes

- skillmap/src/App.css
- skillmap/src/components/HeaderBar.tsx
> Add bug button to skillmap header to toggle Usabilla

- pxtblocks/fields/field_animation.ts
- pxtblocks/fields/field_asset.ts
- pxtblocks/fields/field_sprite.ts
- pxtblocks/fields/field_utils.ts
- pxtlib/tilemap.ts
- theme/image-editor/imageEditor.less
- webapp/src/app.tsx
- webapp/src/blocks.tsx
- webapp/src/components/ImageFieldEditor.tsx
- webapp/src/components/assetEditor/assetPreview.tsx
- webapp/src/components/assetEditor/assetSidebar.tsx
- webapp/src/components/assetEditor/store/assetEditorReducer.ts
Cherry picking:
* https://github.com/microsoft/pxt/pull/7998
* https://github.com/microsoft/pxt/pull/8019
* https://github.com/microsoft/pxt/pull/8021
> Cherry pick richard's fixes to stable 6.12

- pxtlib/spriteutils.ts
- pxtlib/tilemap.ts
- skillmap/src/lib/codeCarryover.ts
* Add temporary assets to JRes when doing skillmap carryover
* Loosen regex around field name, null checks
> [stable6.12] Add temporary assets to JRes when doing skillmap carryover (#8032)

- skillmap/src/App.css
- skillmap/src/components/HeaderBar.tsx
adjustments to "feedback" menu button based on design sync
> Add help dropdown with feedback item in skillmap

- cli/server.ts
- webapp/src/githubprovider.tsx
- webapp/src/immersivereader.tsx
* https://github.com/microsoft/pxt/pull/8051 Immersive reader electron fix
* https://github.com/microsoft/pxt/pull/8053 |
* https://github.com/microsoft/pxt/pull/8055 Fix for new github token changes
> [stable6.12] Gh and electron ports

- theme/themes/pxt/collections/form.variables
- theme/themes/pxt/collections/menu.overrides
- theme/themes/pxt/modules/modal.overrides
fixes microsoft/pxt-microbit#3640
from #999999 to #8f8f8f
Before:
After:
fixes microsoft/pxt-microbit#3635, fixes microsoft/pxt-microbit#3593, fixes microsoft/pxt-microbit#3556 
also fixes https://github.com/microsoft/pxt-microbit/issues/3569
Before:
After
Before: (focused)
After:
> Improve contrast for filelist, form inputs

- webapp/src/codecard.tsx
- webapp/src/dialogs.tsx
- webapp/src/pxtjson.tsx
- webapp/src/scriptsearch.tsx
- webapp/src/sui.tsx
each commit lists what it should be fixing
* fix microsoft/pxt-microbit#3689
* fix microsoft/pxt-microbit#3691
* fix microsoft/pxt-microbit#3696
* fix microsoft/pxt-microbit#3756
* fix microsoft/pxt-microbit#3757
* fix microsoft/pxt-microbit#3753
* fix microsoft/pxt-microbit#3754
* fix microsoft/pxt-microbit#3694
* fix microsoft/pxt-microbit#3687
* fix microsoft/pxt-microbit#3758
* fix microsoft/pxt-microbit#3695 (fix for this one was https://github.com/microsoft/pxt/commit/7caae3615a2772eee0cc5be2f7c7469f0e9aed4b, I copied the wrong link in the commit msg)
> micro:bit accessibility fixes (mainly extensions & github modals)

- webapp/src/githubprovider.tsx
cherry pick https://github.com/microsoft/pxt/pull/8053 and https://github.com/microsoft/pxt/pull/8055 to fix dev tokens in micro:bit/stable which broke due to change in format.
> [stable6.0] github token check fixes

- theme/common.less
- webapp/src/editortoolbar.tsx
- webapp/src/gitjson.tsx
- webapp/src/lang.tsx
- webapp/src/toolbox.tsx
fixes microsoft/pxt-microbit#3661
fixes microsoft/pxt-microbit#3652
fixes microsoft/pxt-microbit#3765
fixes microsoft/pxt-microbit#3663 
fixes microsoft/pxt-microbit#3662
fixes microsoft/pxt-microbit#3664
> Accessibility fixes for language selector, editor roles/ids

- theme/github.less
- theme/themes/pxt/globals/site.variables
- webapp/src/githubbutton.tsx
- webapp/src/gitjson.tsx
- webapp/src/pxtjson.tsx
commits list what they fix~
* fix microsoft/pxt-microbit#3761
* fix microsoft/pxt-microbit#3762
* fix microsoft/pxt-microbit#3766
* fix microsoft/pxt-microbit#3759
* fix microsoft/pxt-microbit#3682
> micro:bit accessibility fixes (primarily gh extension view)

- theme/highcontrast.less
- webapp/src/projects.tsx
Don't think there was an issue for this one but I noticed it while testing something else. the icons being listed as buttons can upset screen readers, even though it's only an alternative click point to the button beneath it. Fix the label & add aria label to the button below it so things get read out better.
> fix narrator issues in project detail view

- skillmap/src/lib/skillGraphUtils.ts
- theme/tutorial.less
- fix to skillmap graph layout for kiki's beginner map https://github.com/microsoft/pxt/pull/8101
- enabling the scrollbar on collapsed tutorial cards https://github.com/microsoft/pxt/pull/8097
> [stable6.12] Cherry-pick tutorial scrollbar, skillmap graph fix

- docs/csp.md
Drop in a paragraph for College Board's endorsed provider note.
Closes #8113
> Add note from College Board to CSP page

- webapp/src/app.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3224
> Exit fullscreen simulator when entering debug

- webapp/src/cmds.ts
Made "pair device" primary color and move "download again" as secondary.
See diff without whitespace https://github.com/microsoft/pxt/pull/8117/files?w=1 . What code formatter settings is the team using?
> experiment: simple reshuffling of buttons

- webapp/src/pxtjson.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/2819
> Stay in pxtjson settings editor after item toggled

- webapp/src/filelist.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/4000
> Populate custom ts file with 'custom.ts', add default text

- theme/serial.less
- webapp/src/serial.tsx
changes from design office hours
> Add description text to serial placeholder graph

- docs/blog.md
- docs/blog/SUMMARY.md
- docs/blog/csp/new-free-curriculum.md
Post the announcement of the new AP CSP curriculum.
Closes #8127
> New AP CSP Curriculum blog post

- .gitignore
- gulpfile.js
- skillmap/.gitignore
- skillmap/package-lock.json
checking in package-lock since npm ci requires it, and skillmap packages are relatively stable for now
> Speed up 'npm install' part of skillmap build

- webapp/src/monacopyhelper.ts
previous indent handler was attempting to auto-format pasted python code, but not doing a great job. this scraps that in favor of preserving the user-input indentation.
fixes https://github.com/microsoft/pxt-microbit/issues/3936
> Preserve indentation of pasted Python code

- pxtsim/simlib.ts
Adding simulator support for streaming audio buffers for the micro:bit sound emoji.
Tested in Firefox, Safari, and Chrome on macOS
> Adding audio context function for streaming buffers for sound emoji

- theme/tutorialCodeValidation.less
- webapp/src/tutorial.tsx
- webapp/src/tutorialCodeValidation.tsx
> 5/11 Design Office Hours Changes

- webapp/src/filelist.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3947
> Enable jres file creation from file explorer

- docs/csp.md
Put a note in the CSP page for Educator Materials downloads.
* Note: Duplicate this on the https://microsoft.github.io/makecode-csp/ index page too.
> Reminder note for AP CSP materials download

- pxtblocks/fields/field_asset.ts
- pxtblocks/fields/field_base.ts
Check the PR for context! We've hit this a few times on stream
> Cherry pick #8130 "Fix two undo/redo bugs for assets in the blocks editor"

- skillmap/src/components/GraphNode.tsx
- skillmap/src/components/SkillGraphContainer.tsx
missed some lint things! not sure why the build passed!
> Fix spacing in skillmap files

- skillmap/src/components/GraphNode.tsx
- skillmap/src/components/SkillGraph.tsx
- skillmap/src/components/SkillGraphContainer.tsx
- skillmap/src/lib/skillGraphUtils.ts
- skillmap/src/lib/skillMap.d.ts
- skillmap/src/lib/skillMapParser.ts
- skillmap/src/store/reducer.ts
- skillmap/src/styles/skillgraph.css
for beginner skill map release
- https://github.com/microsoft/pxt/pull/8163
- https://github.com/microsoft/pxt/pull/8160
> [stable6.12] Cherry-pick skill map tweaks (double click, fixed background, completion color)

- webapp/src/tutorial.tsx
- webapp/src/tutorialCodeValidation.tsx
In the case where the user ignores the buttons and corrects their code, the pop-up message will disappear.
> Negative Feedback Pop-Up Disappears Once Code is Valid

- webapp/src/cloud.ts
Add additional null protection to cloud sync codepaths.
Fixes https://github.com/microsoft/pxt-arcade/issues/3548
> cloud sync: more null checks

- webapp/src/tutorial.tsx
After modifying webapp/src/tutorial.tsx from this [pull request](https://github.com/microsoft/pxt/pull/8177), tutorial validation features appears when tutorial validation is turned off. Code is now modified so that tutorial validation features are turned off when tutorial validation flag is turned off.
> Tutorial Validation Features Hidden When Tutorial Validation is Off

- .vscode/tasks.json
Checking in this update that vscode keeps autogenerating for me. Not sure anyone actually uses this.
> Checking in autogenerated tasks.json from vscode

- pxteditor/editor.ts
- webapp/src/scriptsearch.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3967
> Go back to previous editor when adding extension from pxt.json

- theme/highcontrast.less
fixes https://github.com/microsoft/pxt-microbit/issues/4059
> Use HC text color for error count

- pxtblocks/blocklyloader.ts
- pxtlib/service.ts
fix https://github.com/microsoft/pxt-microbit/issues/3942
> fix default block for handler blocks

- skillmap/src/components/InfoPanel.tsx
- skillmap/src/lib/skillMapParser.ts
- skillmap/src/styles/infopanel.css
only allow links to our docs or github, at the moment
@Jaqster @kiki-lee
> Add link to educator info/learning outcomes in skillmap

- skillmap/src/components/InfoPanel.tsx
- skillmap/src/lib/skillMapParser.ts
- skillmap/src/styles/infopanel.css
* Add link to educator info/learning outcomes in skillmap
* Require trailing slash in github URLs
* Move info link below description
> [stable6.12] Cherry-pick "Add link to educator info/learning outcomes in skillmap (#8202)"

- theme/themes/pxt/globals/site.variables
- theme/tutorial.less
See title - made changes from 5/25 Design Office Hours
Note: These colors are for Arcade
> Fixed Next Button Color When Code Is Validated

- docfiles/tocheader.html
- pxtlib/docsrender.ts
- theme/docs.less
> Updated branding on header for documentation pages

- docs/notebook.html
This is for staging.pxt.io/notebook.html testing
> Notebook testing page

- webapp/src/tutorialCodeValidation.tsx
this still doesn't have quite everything from https://github.com/microsoft/pxt/blob/master/webapp/src/blocks.tsx#L1635 but it should be closer than the monaco snippet is!
> Use blocks toolbox instead of monaco snippet to get blocks image

- cli/cli.ts
- docfiles/appmeta.html
Draft PR with a fix for the start URLs in the PWA manifest
> Fix the start URL for PWA manfiest

- pxtlib/tutorialValidator.ts
- theme/tutorialCodeValidation.less
- webapp/src/tutorialCodeValidation.tsx
Adjusted the text size for validation message so that it's more legible from 6/15 Design Office Hours
> Better Legibility for Tutorial Validation Messages

- localtypings/pxtarget.d.ts
- theme/common.less
- webapp/src/cmds.ts
- webapp/src/dialogs.tsx
- webapp/src/webusb.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4169
1. Actually check that we are connected before showing the incompatible hardware dialog
2. Vertically center text in the various download dialogs and fix image css
3. Adds image to the incompatible hardware dialog
> Webusb dialog updates

- pxtsim/simlib.ts
- webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4172
> Mute safari by default

- webapp/src/dialogs.tsx
- webapp/src/webusb.tsx
re: https://github.com/microsoft/pxt/pull/8242#issuecomment-861936194
Wouldn't say it looks great but at least it doesn't look broken!
> handle missing download dialog images

- webapp/src/tsworker.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4187
I also took this opportunity to improve the sorting to also take into account the group, block, and advanced attributes. Check out the comment for an explanation of the sorting.
> Fix position error and match the toolbox sorting better

- theme/themes/pxt/collections/menu.overrides
- webapp/src/headerbar.tsx
small css fixes for header bar:
> Show target logo on home page header bar, center icons

- webapp/src/cmds.ts
- webapp/src/headerbar.tsx
> Add back arrow to header bar for iOS app

- pxtrunner/runner.ts
- skillmap/src/App.tsx
- webapp/src/app.tsx
fix re: https://github.com/microsoft/pxt/pull/8254
> use server translations in localeserve again

- theme/common.less
- webapp/src/headerbar.tsx
based on design feedback
for https://github.com/microsoft/pxt-microbit/issues/4202
> Reduce margin between back arrow and logos

- docfiles/apptracking.html
- docfiles/tracking.html
- webapp/src/compiler.ts
- webapp/src/tutorial.tsx
- webapp/src/workspace.ts
> Cherry pick #8270 to stable6.12

- libs/pxt-common/pxt-core.d.ts
- libs/pxt-common/pxt-helpers.ts
Added string.toUpperCase as there is a project I'm working on that would benefit from it!
> string.toUpperCase

- docs/blog/microbit/2021-release.md
edited date and fixed a broken link
> made small edits to release blog

- webapp/src/components/ImageEditor/keyboardShortcuts.ts
fixes https://github.com/microsoft/pxt-arcade/issues/2122
> Add Ctrl-Shift-Z as redo, not undo

- webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2762
> Fix marquee bounds

- webapp/src/projects.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/2885
> Remove large image and videos in projects detail in high contrast

- skillmap/src/index.tsx
fix loading of github skillmaps from localserve
> Skip setupWebConfig for local skillmap serve

- webapp/src/app.tsx
The rare cherry pick that goes from stable to master!
When we were doing the release last week, I did this fix directly in stable. Forgot to cherry pick it over.
> Handle header format change for tutorial code (#8287)

- webapp/src/app.tsx
this should fix the customts snippet in the tutorial tool
> Wait for customts file to finish saving before returning to tutorial load

- theme/common.less
- webapp/src/headerbar.tsx
- webapp/src/sui.tsx
- https://github.com/microsoft/pxt/pull/8292
- https://github.com/microsoft/pxt/pull/8315
> [stable7.0] Cherry pick small fixes for iOS back button

- cli/cli.ts
- webapp/src/compiler.ts
Cherry pick these two PRs:
#8310 
#8307
> Cherry pick patch fixes to stable7.0

- pxtlib/auth.ts
- pxtlib/localStorage.ts
- webapp/src/app.tsx
- webapp/src/auth.ts
Update auth system to use the pxt server-backed local storage.
> Auth system to use shared local storage

- webapp/src/cloud.ts
Recent regression. Found while verifying https://github.com/microsoft/pxt-arcade/issues/2868
> fix for cloud delete sync

- docs/language.md
Re enabling experiments, I borrowed language from @pelikhan on https://github.com/microsoft/pxt/issues/5390
> update language about static python experimental

- pxtcompiler/emitter/driver.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2746
> Make sure to flatten diagnostic messages

- docs/language.md
re: https://github.com/microsoft/pxt/pull/8309#issuecomment-885242100
> replace unreplaced html entity with unicode char

- pxtblocks/fields/field_tileset.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3188
> Handle tile renames in tileset editor

- pxtlib/tutorial.ts
fixes https://github.com/microsoft/pxt-arcade/issues/2723
> Stricter regex for collapsing images in text tutorial hints

- pxtlib/emitter/cloud.ts
cherry pick https://github.com/microsoft/pxt/pull/8338 to micro:bit stable
> [stable7.0] include lang query parameter when fetching md

- pxtlib/auth.ts
- pxtlib/localStorage.ts
- pxtlib/util.ts
- skillmap/src/App.tsx
- skillmap/src/actions/dispatch.ts
- skillmap/src/lib/authClient.ts
- skillmap/src/lib/workspaceProvider.ts
- webapp/src/auth.ts
- webapp/src/core.ts
- webapp/src/immersivereader.tsx
Sync skillmap progress to cloud. It does this by hooking into the location where the skillmap loads and saves user state and injecting some state from the cloud. I *think* this is a good approach. Would appreciate feedback!
> sync skillmap progression

- webapp/src/scriptmanager.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3676
Check projects by id, not index
> Fix delete project button

- pxtlib/auth.ts
- pxtlib/commonutil.ts
- skillmap/src/components/HeaderBar.tsx
- webapp/src/auth.ts
- webapp/src/cloudsync.ts
- webapp/src/identity.tsx
- webapp/src/user.tsx
Resolves https://github.com/microsoft/pxt-arcade/issues/3727
> Improved user initials handling

- webapp/src/simtoolbar.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3668
> Disable debugger when outside of code editor

- pxteditor/monaco-fields/field_sprite.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2977
> Don't duplicate assets when selecting something from my assets in monaco

- webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3748
Fixes https://github.com/microsoft/pxt-arcade/issues/3745
Fixes https://github.com/microsoft/pxt-arcade/issues/3743
> Disable auth in skillmap editor

- webapp/src/auth.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3753
> after signing out, take user to home screen

- webapp/src/identity.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3760
> Show Sign In modal directly if no Github

- skillmap/src/App.css
- skillmap/src/components/HeaderBar.tsx
- skillmap/src/components/makecodeFrame.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3757
> Skillmap target logo click goes back to skillmap home

- webapp/src/components/assetEditor/assetGallery.tsx
> Use ternary for new asset onclick

- webapp/src/app.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3755
> Load skillmap project in editor after import

- pxtlib/spriteutils.ts
- webapp/src/components/ImageEditor/store/imageReducer.ts
this is mostly to make the blank tilemap editor a little friendlier!
> Select the first forest tile by default for empty tilemaps

- webapp/src/app.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3781
> Null check for header when saving, posting tutorial progress

- docfiles/tracking.html
Regression from https://github.com/microsoft/pxt/pull/8112/files
> Don't use telemetry item before it's declared

- skillmap/src/App.tsx
- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/styles/skillgraph.css
- webapp/src/app.tsx
> [stable7.1] Cherry-pick fixes for skillmap, iframe

- docfiles/tracking.html
- webapp/src/app.tsx
> Cherry pick fixes to stable7.1

- docs/blog.md
> unlist blog post: missed a spot

- docs/blog.md
- docs/blog/SUMMARY.md
Reverts microsoft/pxt#8408
Will merge after Arcade is released.
> Revert "unlist cloud sync blog post"

- webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3800
> Check for deleted flag when importing skillmap project

- theme/tutorial-sidebar.less
- webapp/src/components/tutorial/TutorialContainer.tsx
- webapp/src/components/tutorial/TutorialHint.tsx
hint component! css is pulling from old styling, on the whole
> Add tutorial hint component for new vertical tutorial

- theme/highcontrast.less
- theme/tutorial-sidebar.less
- webapp/src/components/tutorial/TutorialHint.tsx
- high contrast styles
- fix overflow for prev/next buttons
- fix hint positioning on wide desktop
> Small CSS pass for vertical tutorial

- common-docs/identity/cloud-sync.md
- common-docs/identity/sign-in.md
A few adds/changes to the updates in #8419.
RE: https://github.com/microsoft/pxt/pull/8419#pullrequestreview-732300143
> Update to the last update for Identity pages

- skillmap/src/lib/skillGraphUtils.ts
- skillmap/src/lib/skillMapParser.ts
to allow kiki to try the option we talked about at standup today!
> Thow warning instead of error for loop in skillmap graph

- skillmap/src/store/reducer.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3802
> Only reset progress for currently open skillmap

- skillmap/src/index.tsx
- webapp/src/app.tsx
Tiny PR to reenable auth in skillmap.
> reenable auth in skillmap

- pxteditor/editor.ts
- theme/highcontrast.less
- webapp/src/app.tsx
- webapp/src/blocks.tsx
- webapp/src/createFunction.tsx
- webapp/src/extensions.tsx
- webapp/src/lang.tsx
- webapp/src/projects.tsx
- webapp/src/scriptsearch.tsx
- webapp/src/share.tsx
- webapp/src/sidebarTutorial.tsx
- webapp/src/tutorial.tsx
I got https://github.com/microsoft/pxt-minecraft/pull/2115 and https://github.com/microsoft/pxt/pull/7589
> [stable6.4] cherry picks - Minecraft UI fixes (#7876)

- cli/cli.ts
- localtypings/pxtarget.d.ts
Porting https://github.com/microsoft/pxt/pull/8460 to arcade stable
> [stable7.1] allow specifying pkgs to compile hex files for in staticpkg

- webapp/src/app.tsx
- webapp/src/cloud.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3912
> Cleanup console output

- pxtrunner/renderer.ts
- skillmap/src/lib/skillGraphUtils.ts
- skillmap/src/lib/skillMapParser.ts
hoping to get this in with the upcoming skillmap fixes, angel is writing some documentation that uses arrays and this has been causing issues
> [stable7.1] Expand inline blocks regex to allow arrays (#8471)

- skillmap/src/App.css
looks like this now 
before it was like... 
but with the right icons lol
> Align sign in button icon

- skillmap/src/App.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3939
> Sync skillmap tags

- webapp/src/app.tsx
to point to the same URL location as in the extension dialog.
> Update URL to extension in "Add Extension" dialog

- pxtlib/tutorial.ts
- tests/tutorial-test/baselines/activities.json
- tests/tutorial-test/baselines/steps.json
- tests/tutorial-test/baselines/tutorialCompleted.json
- theme/keymap.less
- theme/tutorial-sidebar.less
- webapp/src/app.tsx
- webapp/src/components/tutorial/TutorialContainer.tsx
- webapp/src/keymap.tsx
- webapp/src/sidepanel.tsx
https://github.com/microsoft/pxt/commit/0be19c3056fbd0f1b5a394fae73bcbd6ea2c199b fixes https://github.com/microsoft/pxt-arcade/issues/3933
https://github.com/microsoft/pxt/commit/62634cbeea33b8f46071057ed8767094cb366a03 fixes https://github.com/microsoft/pxt-arcade/issues/3916 (problem was the "currentStep" wasn't updating when we navigated to a new recipe, so if the step was 9 and the recipe only had 7 steps it would error)
https://github.com/microsoft/pxt/commit/47b5246c3ca1ed215305682860ecbb63fd9f1314 fixes https://github.com/microsoft/pxt-arcade/issues/3960
> Fix keymap positioning, modal close button, recipe navigation in new tutorial layout

- webapp/src/app.tsx
- webapp/src/cloud.ts
- webapp/src/workspace.ts
General simplification of the cloud sync code, and fixed a few bugs along the way, notably:
* Code to detect conflicts was itself generating conflicts.
* Cloud sync was getting triggered too frequently.
Fixes https://github.com/microsoft/pxt-arcade/issues/3963
> Fix for spurious cloud conflicts

- theme/common.less
- theme/highcontrast.less
https://github.com/microsoft/pxt/commit/bfa2a6f3227b5adce9850e1a42404b2996db1143 fixes https://github.com/microsoft/pxt-arcade/issues/3941
https://github.com/microsoft/pxt/commit/781a27d835f83296632b8b6eca426ef39a4b433a fixes https://github.com/microsoft/pxt-arcade/issues/3761
https://github.com/microsoft/pxt/commit/3163aa42de688d8ccc36fbe8daaa867a291bc6cc fixes https://github.com/microsoft/pxt-arcade/issues/3245
https://github.com/microsoft/pxt/commit/0c1d790d56605e093f9ba373c0653578a4ba983e sign in button HC, no bug for it
https://github.com/microsoft/pxt/commit/ad95949915dc92c8faeaf56c29d6425335082972 fixes https://github.com/microsoft/pxt-arcade/issues/3751
> Various UI fixes

- pxteditor/editorcontroller.ts
- skillmap/src/components/makecodeFrame.tsx
- theme/common.less
- theme/highcontrast.less
- theme/sidedoc.less
- theme/tutorial-sidebar.less
- webapp/src/app.tsx
- webapp/src/components/tutorial/TutorialContainer.tsx
changes based on sonia's feedback!
- adding a gradient to the bottom of the scrollable markdown, so it isn't a hard cutoff 
- the "Exit Tutorial" button is now visible in skillmap view, this adds an editor message for it so that the skillmap can correctly exit
- handful of small css things (margins, font styles, etc)
> CSS updates to tutorial, add gradient for scroll, skillmap exit message

- theme/common-components.less
- theme/tutorial-sidebar.less
removing the semantic update styles (box shadow, gradient bg) from the tutorial button hover
> Tutorial button hover styles

- pxtsim/simlib.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3958
> Fix fast release times in sim melodies

- webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3909
> Fixing tilemap walls

- webapp/src/marked.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4000
fixes https://github.com/microsoft/pxt-arcade/issues/4005
> Force update DOM when markdown blocks have been rendered

- webapp/src/app.tsx
Fixes the issue that Andrew was reporting! Gotta make sure things exist before using them :)
> Minecraft -- Fix tutorial load

- skillmap/src/App.css
- theme/common.less
- theme/tutorial-sidebar.less
fixes https://github.com/microsoft/pxt-arcade/issues/4052
fixes https://github.com/microsoft/pxt-arcade/issues/4044
fixes https://github.com/microsoft/pxt-arcade/issues/4042
fixes https://github.com/microsoft/pxt-arcade/issues/4018
> Fix sim, Usabilla position, title spacing, Safari gradient

- webapp/src/codecard.tsx
joey you were right this was an array lol
The tags were an array so....this fixes the build so it doesn't get angry.
> Skillmap metadata tags are arrays

- theme/themes/pxt/modules/modal.overrides
hardware select modal is broken (https://forum.makecode.com/t/makecode-aracde-hardware-options-not-working/10228)
> Restore margin styles for scrolling modals

- theme/home.less
Fixes https://github.com/microsoft/pxt-arcade/issues/4080
> Fix padding in home screen details view

- theme/themes/pxt/modules/modal.overrides
fix https://github.com/microsoft/pxt-arcade/issues/4097
> fix scroll in safari microsoft/pxt-arcade#4097

- pxtlib/auth.ts
Our Cosmos backend is getting hammered by calls to the save preferences api right now. This change adds a debounce. Looking at telemetry, this should result in a 3-4x reduction.
> Debounce user preferences save

- webapp/src/app.tsx
for https://github.com/microsoft/pxt/pull/8516#issuecomment-926766742
> Fix null issue in Minecraft

- localtypings/pxtarget.d.ts
- webapp/src/app.tsx
- webapp/src/cmds.ts
> custom apiRoot settings

- skillmap/src/App.css
- skillmap/src/components/AppModal.tsx
- skillmap/src/styles/modal.css
- theme/common.less
- webapp/src/identity.tsx
Reverts select portions of https://github.com/microsoft/pxt/pull/8547
Fixes https://github.com/microsoft/pxt-arcade/issues/4291
> Revert signin modal changes

- gulpfile.js
- react-common/components/profile/BadgeInfo.tsx
- react-common/components/profile/BadgeList.tsx
- react-common/components/profile/UserPane.tsx
- react-common/styles/profile/profile.css
- skillmap/src/App.css
- skillmap/src/App.tsx
- skillmap/src/components/AppModal.tsx
- skillmap/src/components/Modal.tsx
- skillmap/src/lib/skillMapParser.ts
- skillmap/src/styles/modal.css
Fixes https://github.com/microsoft/pxt-arcade/issues/4286
Fixes https://github.com/microsoft/pxt-arcade/issues/4290
Fixes https://github.com/microsoft/pxt-arcade/issues/4295
Also does a ton of css tweaks based on feedback @soniakandah sent me!
> Badge fixes

- react-common/components/profile/UserPane.tsx
- react-common/styles/profile/profile.css
- skillmap/src/components/AppModal.tsx
- skillmap/src/lib/skillMapUtils.ts
- skillmap/src/store/reducer.ts
- theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-arcade/issues/4294
Fixes https://github.com/microsoft/pxt-arcade/issues/4284
Fixes https://github.com/microsoft/pxt-arcade/issues/4292
Fixes https://github.com/microsoft/pxt-arcade/issues/4297
https://github.com/microsoft/pxt-arcade/issues/4292 actually didn't have anything to do with badges, I think it was broken by the recent code carryover change.
> More badge fixes

- skillmap/src/lib/skillMapUtils.ts
Fixing a typo. This one should go into testing tomorrow @abchatra
> Remove extra curly brace

- react-common/components/profile/Badge.tsx
- react-common/components/profile/BadgeInfo.tsx
- react-common/components/profile/BadgeList.tsx
- react-common/styles/profile/profile.css
- skillmap/src/App.tsx
- skillmap/src/components/UserProfile.tsx
- skillmap/src/lib/skillMapUtils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/4336
Fixes https://github.com/microsoft/pxt-arcade/issues/4337
Fixes https://github.com/microsoft/pxt-arcade/issues/4333
Fixes https://github.com/microsoft/pxt-arcade/issues/4325
Fixes https://github.com/microsoft/pxt-arcade/issues/4324
> Badge release fixes

- react-common/components/profile/Badge.tsx
- react-common/components/profile/BadgeInfo.tsx
- react-common/components/profile/BadgeList.tsx
- react-common/styles/profile/profile.css
- skillmap/src/App.tsx
- skillmap/src/components/UserProfile.tsx
- skillmap/src/lib/skillMapUtils.ts
* Safari css fix, make badges look clickable, text tweak
* fix sync of badge preferences
> [Stable 7.3] Badge release fixes (#8594)

- skillmap/src/styles/modal.css
Fixes https://github.com/microsoft/pxt-arcade/issues/4352
will cherry pick
> fix skillmap profile on small screens

- webapp/src/components/ImageEditor/ImageCanvas.tsx
Quick fix for the tilemap cursor
Fixes https://github.com/microsoft/pxt-arcade/issues/4227
@abchatra this is a pretty safe fix, can we add it to the friday release?
> Fix the tilemap wall cursor

- skillmap/src/App.tsx
> [Stable7.3] Include reward node progress when importing local state (#8603)

- skillmap/src/components/UserProfile.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4384
> Check preferences for email on skillmap load

- package.json
- pxtblocks/blocklycompiler.ts
- pxtblocks/blocklydiff.ts
- pxtblocks/blocklyimporter.ts
- pxtblocks/blocklylayout.ts
- pxtblocks/blocklyloader.ts
- pxtblocks/blocklyrenderer.ts
- pxtblocks/fields/field_animation.ts
- pxtblocks/fields/field_asset.ts
- pxtblocks/fields/field_base.ts
- pxtblocks/fields/field_breakpoint.ts
- pxtblocks/fields/field_ledmatrix.ts
- pxtblocks/fields/field_melodySandbox.ts
- pxtblocks/fields/field_note.ts
- pxtblocks/fields/field_procedure.ts
- pxtblocks/fields/field_tileset.ts
- pxtblocks/fields/field_toggle.ts
- pxtblocks/fields/field_turnratio.ts
- theme/blockly-core.less
- theme/melodyeditor.less
- theme/print.less
- theme/toolbox.less
- webapp/src/app.tsx
- webapp/src/blocks.tsx
- webapp/src/toolbox.tsx
- webapp/src/tutorial.tsx
This reverts commit f91d7c63e090de94b6807a305178eae6a4a86c36.
reverting the Blockly update for now! no huge bugs reported (yet), but there are some small ones (velocity slider, etc) and the change is not very thoroughly tested
> Revert "Updates to sync with Blockly changes through July 2021 (#8576)"

- pxtlib/auth.ts
- pxtlib/util.ts
- skillmap/src/lib/authClient.ts
- webapp/src/app.tsx
- webapp/src/auth.ts
* more careful patching of user preferences
* remove variable scoping
> [stable7.3] More careful patching of user preferences (#8607)

- theme/common-components.less
- theme/highcontrast.less
> Blink tutorial tab dot to draw user attention

- theme/common-components.less
- theme/common.less
- theme/highcontrast.less
- theme/tutorial-sidebar.less
- webapp/src/sidepanel.tsx
- https://github.com/microsoft/pxt/pull/8625
- https://github.com/microsoft/pxt/pull/8623
> [stable7.3] Cherry-pick tutorial tab fixes

- pxtblocks/fields/field_melodySandbox.ts
- pxtblocks/fields/field_tsexpression.ts
fixes https://github.com/microsoft/pxt-arcade/issues/4434
> Fix constants access in grey block, melody editor

- webapp/src/components/ImageEditor/ImageCanvas.tsx
I noticed the other day that onionskinning was broken in the animation editor. Bringing it back!
> Fix onionskinning

- theme/asset-editor.less
- webapp/src/components/assetEditor/assetGallery.tsx
- webapp/src/components/assetEditor/assetSidebar.tsx
everything looks mostly the same as it previously did--will do a final CSS pass after i've added the card component to ensure that it matches the current design
> Port asset editor buttons and modals to react-common components

- webapp/src/components/ImageEditor/tilemap/TilePalette.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/4505
> Make clicking the wall tool toggle the wall drawing state

- pxteditor/editor.ts
- pxteditor/editorcontroller.ts
- react-common/styles/controls/Button.less
- react-common/styles/controls/Checkbox.less
- react-common/styles/controls/Input.less
- react-common/styles/controls/MenuDropdown.less
- react-common/styles/controls/Modal.less
- react-common/styles/profile/profile.less
- react-common/styles/react-common-variables.less
- skillmap/src/App.css
- skillmap/src/App.tsx
- skillmap/src/components/GraphPath.tsx
- skillmap/src/components/HeaderBar.tsx
- skillmap/src/components/SkillGraph.tsx
- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/lib/authClient.ts
- skillmap/src/styles/graphnode.css
- skillmap/src/styles/infopanel.css
- skillmap/src/styles/makecode-editor.css
- skillmap/src/styles/modal.css
- skillmap/src/styles/skillgraph.css
- webapp/src/app.tsx
adds high contrast styles, adds settings item to toggle, hooks it up to the main editor high contrast (which is already all nicely piped through the auth service thanks to eric & vivian's work haha)
build: https://arcade.makecode.com/app/4883fe9e2d5a3716f460f3557bf4e7b7eb6fd973-0d61bad887--skillmap
> Enable high contrast styles for skillmap

- theme/highcontrast.less
fixes https://github.com/microsoft/pxt-arcade/issues/4475
fixes https://github.com/microsoft/pxt-arcade/issues/4431
> High contrast fixes for tutorial, details view

- react-common/styles/controls/MenuDropdown.less
- skillmap/src/App.css
- skillmap/src/styles/modal.css
- theme/highcontrast.less
- fix icon color in signin modal (pops up after completing first activity)
- make hyperlinks blue/underlined in high contrast
- adjust padding on the react-common dropdown
> High contrast fixes for icon, dropdown size, hyperlink color

- package.json
Pick up https://github.com/microsoft/pxt-blockly/pull/381, https://github.com/microsoft/pxt-blockly/pull/374
> pxt-blockly 4.0.6->4.0.7

- theme/image-editor/imageEditor.less
Fixes https://github.com/microsoft/pxt-arcade/issues/4407
> Fix text wrapping in image-editor toggle

- webapp/src/components/tutorial/TutorialCallout.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4573
> Capture event when toggling the hint and reset code callouts

- package.json
fixes https://github.com/microsoft/pxt-arcade/issues/4589
> Bump pxt-blockly to 4.0.8

- react-common/components/controls/Modal.tsx
- react-common/components/profile/UserPane.tsx
- react-common/styles/controls/Button.less
- react-common/styles/controls/MenuDropdown.less
- react-common/styles/react-common-variables.less
- skillmap/src/App.tsx
- skillmap/src/components/InfoPanel.tsx
- skillmap/src/styles/infopanel.css
Fixes https://github.com/microsoft/pxt-arcade/issues/4584
Fixes https://github.com/microsoft/pxt-arcade/issues/4591
Fixes https://github.com/microsoft/pxt-arcade/issues/4578
Also fixes two un-filed bugs:
1. Modals were not respecting high-contrast. I moved the high-contrast class up to the document body
2. The sign in button was no longer present when no activity was selected in the skillmap
The commits break down to one fix per commit, so might be easier to review. I also refactored the focus outline less variables a bit because I was getting very confused as to what inverted/not-inverted meant.
> Various skillmap fixes for February release

- react-common/components/controls/Modal.tsx
- react-common/components/profile/UserPane.tsx
- react-common/styles/controls/Button.less
- react-common/styles/controls/MenuDropdown.less
- react-common/styles/react-common-variables.less
- skillmap/src/App.tsx
- skillmap/src/components/InfoPanel.tsx
- skillmap/src/styles/infopanel.css
* Fix sign out button and refactor focus outline
* Fix color of sign in button
* Restore sign in button when no activity is selected
* Fix modal high contrast
* remove high-contrast from app
> [Stable 7.4] Cherry pick Various skillmap fixes for February release (#8697)

- theme/tutorial-sidebar.less
fixes https://github.com/microsoft/pxt-arcade/issues/4595
+ small fix for previous and next button width in simulator pane tablet view
> Fix CSS for hint button in simulator pane

- localtypings/pxtblockly.d.ts
- pxtblocks/blocklyloader.ts
- webapp/src/blocks.tsx
> [stable7.4] Cherry pick fixes for stable

- skillmap/src/components/ActivityActions.tsx
- skillmap/src/components/InfoPanel.tsx
- skillmap/src/styles/infopanel.css
Fixes https://github.com/microsoft/pxt-arcade/issues/4630
> Swapping style of sign-in and start activity buttons

- common-docs/faq.md
- common-docs/translate.md
- docs/translate.md
- docs/translate/files.md
- docs/translate/languages.md
- pxtarget.json
- webapp/public/index.html
Documentation and other changes for prepping name change.
> Chaning the name from kindscript to makecode

- pxtarget.json
- webapp/public/index.html
- webapp/src/marked.tsx
for arcade
Porting non-docs versions of https://github.com/microsoft/pxt/commit/32723c6912405c067eedb7b6b4dc7a89dfd4a6ea to microbit, arcade, minecraft
> [stable7.4] port kindscript->makecode change

- pxtarget.json
- webapp/public/index.html
- webapp/src/marked.tsx
for microbit
Porting non-docs versions of https://github.com/microsoft/pxt/commit/32723c6912405c067eedb7b6b4dc7a89dfd4a6ea to microbit, arcade, minecraft
marked.tsx didn't go in cleanly so I just copied the lint rule change over
> [stable7.0] port kindscript->makecode change

- pxtarget.json
- webapp/public/index.html
for minecraft
Porting non-docs versions of https://github.com/microsoft/pxt/commit/32723c6912405c067eedb7b6b4dc7a89dfd4a6ea to microbit, arcade, minecraft
hopefully build works, looks like this doesn't need the marked.tsx change as it still has tslint?
> [stable6.4] port crowdin kindscript->makecode

- pxtcompiler/emitter/decompiler.ts
- pxtlib/blocks.ts
- tests/decompile-test/baselines/functions_v2_bad_types.blocks
- tests/decompile-test/cases/functions_v2_bad_types.ts
Fixes the issue @Jaqster mentioned here: https://github.com/microsoft/pxt-microbit/issues/4241#issuecomment-867753337
> Fix decompilation for array parameters in user defined functions

- pxtblocks/blocklyloader.ts
fixes https://github.com/microsoft/pxt-microbit/issues/2918
> Move variable change/set blocks to top, add flyout divider

- react-common/components/controls/Link.tsx
- react-common/components/controls/Textarea.tsx
- react-common/styles/controls/Textarea.less
- react-common/styles/react-common-variables.less
- react-common/styles/react-common.less
lightweight link component and textarea (to be used in updated share modal)
> Add Textarea and Link components to react-common

- skillmap/package-lock.json
Fixes
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6720712?typeId=795877
https://devdiv.visualstudio.com/DevDiv/_componentGovernance/119762/alert/6651919?typeId=795877
> Fix component governance alerts

- webapp/public/run.html
Opening as a draft to make sure I'm not conflicting with anything @jwunderl is working on.
This adds a query parameter to the --run.html embed to make it act as a server and wait for a message containing a project to compile/run.
> Adding a command to compile/run projects from source in the run embed

- docs/writing-docs/skillmaps.md
Made the following changes to skillsmaps.md
-Fixed typo in **kind** section of ### Rewards
-Reordered bullets in sample of ### Rewards section for consistency
-Rephrased ## Loading a skillmap for conciseness and clarity
> minor edits to skillmaps.md

- webapp/src/components/tutorial/TutorialContainer.tsx
- webapp/src/sidepanel.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4700
> Hide 'Replace My Code' option for asset tutorials

- docs/screenshot-tool.html
- docs/static/screenshot-tool/screenshot.css
- docs/static/screenshot-tool/screenshot.js
- docs/static/screenshot-tool/screenshot.ts
This is a request we've gotten a few times, so here's a PR adapting the tutorial tool into a tool that lets you generate PNGs of blocks with no other blocks attached.
> Tool for taking screenshots of blocks

- gulpfile.js
- libs/pxt-python/pxt-python-helpers.ts
- tests/helpers-test/bare/basic.ts
- tests/helpers-test/bare/pxt.json
- tests/helpers-test/helperrunner.ts
- tests/helpers-test/pytests/pxt.json
- tests/helpers-test/pytests/pysplit.ts
- tests/helpers-test/pytests/pystrip.ts
- tests/helpers-test/pytests/tsconfig.json
- tests/helpers-test/tsconfig.json
Fixes https://github.com/microsoft/pxt-microbit/issues/4417
Implements the various python strip and split builtin functions. I also added a little test runner to test the implementation of helper functions. I'll implement a few more of the low hanging fruit ones in another PR.
It would be nice if there were some test cases we could pull from somewhere...
> Implement pystrip and pysplit and add helper tests

- pxtlib/blocks.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4312
> Add acos and asin to math operator block

- common-docs/faq.md
Faq missing end markdown for button
> Fixing mardown issue in faq

- pxtblocks/fields/field_sound_effect.ts
- theme/soundeffecteditor.less
Fixes https://github.com/microsoft/pxt-microbit/issues/4513
Fixes https://github.com/microsoft/pxt-microbit/issues/4522
Fixes https://github.com/microsoft/pxt-microbit/issues/4521
Fixes https://github.com/microsoft/pxt-microbit/issues/4533
> Fix sound effect exception and spacing

- theme/soundeffecteditor.less
Fixes https://github.com/microsoft/pxt-microbit/issues/4531
Definitely could do more to improve the responsiveness of this editor, but this at least brings the scroll back.
> Fix scroll on narrow screens

- pxtblocks/blocklyloader.ts
- pxtblocks/fields/field_sound_effect.ts
- react-common/components/controls/DraggableGraph.tsx
- react-common/styles/controls/Dropdown.less
- theme/soundeffecteditor.less
- webapp/src/components/soundEffectEditor/SoundControls.tsx
- webapp/src/components/soundEffectEditor/SoundEffectEditor.tsx
- webapp/src/components/soundEffectEditor/SoundGallery.tsx
- webapp/src/components/soundEffectEditor/SoundPreview.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4532
Fixes https://github.com/microsoft/pxt-microbit/issues/4530
Fixes https://github.com/microsoft/pxt-microbit/issues/4517
Also fixes a couple bugs in the block that I noticed while testing:
1. Field editor preview wasn't updating when sibling blocks had their values changed
2. Dropdown values weren't being saved when reloading the project
> More sound editor bug fixes

- react-common/styles/controls/RadioButtonGroup.less
- theme/soundeffecteditor.less
Fixes https://github.com/microsoft/pxt-microbit/issues/4526
Fixes https://github.com/microsoft/pxt-microbit/issues/4527
Just safari bein' safari
> Safari CSS fixes for sound editor

- theme/common.less
- theme/tutorial-sidebar.less
Just breaking up some of these variables in order to support these two issues:
https://github.com/microsoft/pxt-microbit/issues/4535
https://github.com/microsoft/pxt-microbit/issues/4534
There will be an associated pr in pxt-microbit momentarily
> More granularity for tutorial color scheme variables

- package.json
- skillmap/package-lock.json
Related to https://github.com/microsoft/pxt-backend/issues/587
> Update packages to resolve medium, high, and critical component governance issues

- react-common/components/controls/Button.tsx
- react-common/components/share/ShareInfo.tsx
- react-common/components/share/SocialButton.tsx
- react-common/styles/controls/Button.less
- react-common/styles/controls/EditorToggle.less
- react-common/styles/controls/Input.less
- react-common/styles/react-common-variables.less
- react-common/styles/share/share.less
https://makecode.microbit.org/app/2d53ab608c8370a19300c47ed485d6c25b1bc99d-f7e828fc73
Fixes https://github.com/microsoft/pxt-microbit/issues/4524
Fixes https://github.com/microsoft/pxt-microbit/issues/4504
Fixes https://github.com/microsoft/pxt-microbit/issues/4529
Fixes https://github.com/microsoft/pxt-microbit/issues/4505
> Tweaks to the new share dialog to make it more like the old one

- package.json
Just includes https://github.com/microsoft/pxt-blockly/pull/394
> Bump pxt-blockly to fix tutorial bug

- pxtpy/converter.ts
- tests/pyconverter-test/baselines/for_range.ts
- tests/pyconverter-test/cases/for_range.py
Fixes https://github.com/microsoft/pxt-microbit/issues/4403
> Fix py for-loop conversion when using three range arguments

- webapp/public/run.html
Cherry picking https://github.com/microsoft/pxt/pull/8747 over to stable.
> [stable7.4] Cherry pick embed flag to arcade stable

- theme/common.less
- webapp/src/extensionsBrowser.tsx
* Add search placeholder text
* Add an aria message and paragraph to let the user know there were no search results
* Remove 'Do more with your micro:bit' to match Alex's design
Latest: https://microbit.staging.pxt.io/app/c2a02986df7a1bc570d667e648740413eede93e8-8c6cbca310
Previous:
* https://microbit.staging.pxt.io/app/4ad87889fbd28313f3c8f0ab8dcd02b867c2fbbc-75b1423254
> Add Search Placeholder Text

- theme/common.less
- webapp/src/extensionsBrowser.tsx
* Remove the `installed` extension tab
* Update extension tag colors to match the background
* Update extension tag hover color
Fixes microsoft/pxt-microbit/issues/4574
Fixes microsoft/pxt-microbit/issues/4589 
Fixes microsoft/pxt-microbit/issues/4605
https://microbit.staging.pxt.io/app/225392241fbcb64156dcff9778f2ffb5f4061a46-0782882f6d#editor
> Change extension tag color to match the design

- webapp/src/extensionsBrowser.tsx
Bring back the beta label
Fixes microsoft/pxt-microbit/issues/4607
Build: https://microbit.staging.pxt.io/app/cd11b5fbe1ecc147627e5dc49ff16d85ff081186-f6cc98eace
> Add back beta labels

- docs/writing-docs/user-tutorials.md
Me and my student spent many days trying to figure out why the cache doesn't clear.
I've looked at https://github.com/microsoft/pxt/blob/master/CONTRIBUTING.md and it doesn't provide guidance on small docs PR like this.
Please let me know if I should still create an issue for this.
> Clearify how to force the cloud cache to clear

- localtypings/pxtarget.d.ts
I had to look for a second to find 'variable' for my new block so I figured was worth a quick description
> add short description for inlineInputMode options

- pxtrunner/runner.ts
- pxtsim/simdriver.ts
- webapp/public/run.html
Reverted the hideSimButtons changes since it really just needed to be checked and set in SimulatorDriver's startFrame().
> Update sim button hiding support

- webapp/src/serial.tsx
fix https://github.com/microsoft/pxt-microbit/issues/4316
the output will be something like `microbit-data-2022-05-19T20-38-04-506Z`
> use ISO format for console output file name

- webapp/public/run.html
Adds a case to relay simulator state change messages to parent frames in run.html.
> Add case to relay window messages for simulator state changes

- theme/tutorial-sidebar.less
- theme/tutorial.less
fixes https://github.com/microsoft/pxt-arcade/issues/4643
fixes https://github.com/microsoft/pxt-arcade/issues/4327
fixes padding issues in hints as well as pointer events being captured by blur at bottom of tutorial content
> fix css issues in tutorials

- pxtblocks/fields/field_sound_effect.ts
- theme/soundeffecteditor.less
- webapp/src/components/soundEffectEditor/SoundEffectEditor.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4697
For certain screen heights the size gets a little out of whack. Quick css fix
> Fix awkward in-between size for the sound effect editor

- package.json
> Bump pxt-blockly to 4.0.12

- react-common/styles/react-common-breakpoints.less
- react-common/styles/react-common-variables.less
Adding some css utility classes that are similar to semantic's `hide` and `only` classes. Also breaking all of the screen size breakpoints into their own file.
> Adding conditional hiding/showing classes to react-common

- docs/blog/arcade/intro-cloud-sync.md
Correct the resource links in [Introducing Cloud Sync for MakeCode Arcade](https://makecode.com/blog/arcade/intro-cloud-sync) page.
> Use correct links for 'Identity' info pages in blog

- theme/serial.less
- webapp/src/serial.tsx
> add a bit of padding for serial/csv toggle

- webapp/src/serial.tsx
in https://github.com/microsoft/pxt/pull/8916 I missed this last change to make sure it defaults to serial if nothing has been written at all yet. Just forgot the last git add ~
> default to serial console if nothing has been written in current sim

- theme/serial.less
- webapp/src/serial.tsx
implements / closes https://github.com/microsoft/pxt-microbit/issues/4764
> keep last header in view in csv view

- pxtlib/docsrender.ts
- skillmap/package-lock.json
> two small fixes video pull request

- theme/serial.less
- webapp/src/serial.tsx
fix https://github.com/microsoft/pxt-microbit/issues/4765
looks like this, only shows up when you scroll up and a new row comes in
here's a build https://makecode.microbit.org/app/b5e3dbf24aa840e367366f551d23c58ee2e11251-fbed1b52f6
> add button to view latest csv row when not following

- pxtblocks/blocklycustomeditor.ts
- pxtblocks/fields/field_autocomplete.ts
- pxtblocks/fields/field_utils.ts
I want this for a few extensions... Most notably, this will make arcade-sprite-data way easier to use! See https://github.com/microsoft/pxt/pull/8861 for a demonstration GIF
> [Stable7.4] Cherry pick autocomplete field to arcade stable

- pxtblocks/fields/field_sound_effect.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4779
The title says it all!
> blur duration input on close to force an update

- docs/defining-blocks.md
- theme/blockly-core.less
- theme/toolbox.less
- webapp/src/toolbox.tsx
Porting icon fix (#8937) to the stable branch.
> [stable 8.0] Port Icon Fix #8937

- cli/server.ts
- pxtrunner/runner.ts
- pxtsim/simdriver.ts
- webapp/public/run.html
also an unrelated fix to the cli server
> Add autofocus param to run page

- webapp/src/app.tsx
- webapp/src/package.ts
porting https://github.com/microsoft/pxt/pull/8947 for arcade patch release
> [stable7.4] port cloud save fix

- webapp/src/marked.tsx
Minor renaming to match ts naming conventions~
> minor changes to match naming conventions

- react-common/components/share/ShareInfo.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4795
> Change game to project in share dialog

- pxtlib/browserutils.ts
- react-common/components/controls/EditorToggle.tsx
- react-common/components/share/ShareInfo.tsx
- react-common/styles/controls/EditorToggle.less
- theme/common.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/2210
Fixes https://github.com/microsoft/pxt-minecraft/issues/2184
Fixes https://github.com/microsoft/pxt-minecraft/issues/2208
A couple of css fixes and updating the copy code to be the same as the old code. i can't repro the copy bug in my local dev build, so we'll have to see if it works!
> Fix a few minecraft release bugs

- pxtsim/simdriver.ts
whoops we did this again https://github.com/microsoft/pxt/pull/8946
> dont crash on sim load runoptions

- webapp/src/extensionsBrowser.tsx
* fix special ext search params
* cleaning
* no uwp >:(
> [stable8.1] fix special ext search params (#8964)

- pxtlib/docsrender.ts
- pxtlib/main.ts
- webapp/src/marked.tsx
note: changed endpoint from staging to prod
> include language specification in captioning for youtube videos

- libs/pxt-common/pxt-helpers.ts
I know there is an issue for this *somewhere* but I cannot find it for the life of me! Also reported on the forum [here](https://forum.makecode.com/t/new-version-jacdac-same-color-error/14635)
Edit: thanks @jwunderl fixes https://github.com/microsoft/jacdac/issues/1184
> Fix colorpicker default

- docs/docs.md
- docs/privacy-faq.md
Import, format, etc. the 'Privacy FAQ' page.
Closes #8982
> Privacy FAQ page

- webapp/src/components/ImageEditor/ImageCanvas.tsx
Fix the copy and paste error I have complained about 10,000,000 times on stream
> Merge floating layer when pasting in image editor

- webapp/src/marked.tsx
This supports both YouTube and Azure Media.
> Add tick events for starting a video

- webapp/src/marked.tsx
change player parameters to keep it consistent
> Change ams to azure

- theme/tutorial-sidebar.less
- webapp/src/components/tutorial/TutorialContainer.tsx
- webapp/src/components/tutorial/TutorialStepCounter.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2230
> Improve mobile width for new tutorial

- theme/greenscreen.less
hey claire! wanted to get your opinion on the styling here if the readability is improved..thanks! :)
> update css to improve readability

- gulpfile.js
I was finding it difficult to know when gulp watch was finished processing a change, so I added a simple console log to let the user know when it's done. I'm not super familiar with gulp, but this seems to do the trick?
> Add "Processing Complete" Messages to Gulp Watch

- theme/common.less
- theme/highcontrast.less
- theme/toolbox.less
- theme/tutorial-sidebar.less
- webapp/src/app.tsx
- webapp/src/components/core/TabContent.tsx
- webapp/src/components/core/TabPane.tsx
- webapp/src/components/tutorial/TutorialContainer.tsx
- webapp/src/components/tutorial/TutorialStepCounter.tsx
- webapp/src/headerbar.tsx
- webapp/src/sidepanel.tsx
- webapp/src/simtoolbar.tsx
- webapp/src/toolbox.tsx
This pr is mostly the layout changes, aiming to get in for testing tomorrow. Listed out remaining changes for future pr at the below \\/
build since it's probably better to just play with it than look at screenshots
* editor https://arcade.makecode.com/app/6188de4950eebb0ea0c342708b800c1a6d179d86-50f7e5f8fc
* skillmap: https://arcade.makecode.com/app/6188de4950eebb0ea0c342708b800c1a6d179d86-50f7e5f8fc--skillmap
changes included (few more than I'd like, but a lot of them are interdependent in that you would lose functionality / be in a broken state if they weren't packed together. Or were just two line fixes in separate commits)
* layout -- no sim / tutorial panel split
* take up full left side down to bottom of page for vertical pane view
* sim always in bottom right / playable (button to …
> Tutorial updates for user studies / redesign

- skillmap/src/App.tsx
- skillmap/src/components/makecodeFrame.tsx
- skillmap/src/lib/browserUtils.ts
fix https://github.com/microsoft/pxt-arcade/issues/5000
> propagate forcelang to makecode editor iframe in skillmap

- skillmap/src/App.css
fix https://github.com/microsoft/pxt-arcade/issues/4971
> bump usabilla in skillmap up a little out of the way of the simulator

- pxtlib/emitter/cloud.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/4935
> Fix parsing of persistent share scripts

- pxtlib/crowdin.ts
cherry pick https://github.com/microsoft/pxt/pull/9089
> [stable8.3] cherry-pick crowdin 429 handling 

- webapp/src/components/tutorial/TutorialCallout.tsx
- webapp/src/components/tutorial/TutorialContainer.tsx
cherry pick https://github.com/microsoft/pxt/pull/9091
> [stable8.3] Port tut button acc fix

- theme/highcontrast.less
- theme/tutorial-sidebar.less
- theme/tutorial.less
- webapp/src/components/tutorial/TutorialHint.tsx
cherry pick https://github.com/microsoft/pxt/pull/9085
> [stable8.3] cherry pick hint updates

- theme/highcontrast.less
- theme/tutorial-sidebar.less
port https://github.com/microsoft/pxt/pull/9093
> [stable8.3] fix expandable hints hc, add pointer cursor

- common-docs/identity/sign-in.md
Update this page to include Google account sign-in's.
RE: https://github.com/microsoft/pxt-arcade/issues/5054
> Update identity sign in page - other account types

- multiplayer/src/epics/index.ts
- multiplayer/src/epics/leaveGameAsync.ts
- multiplayer/src/epics/playerJoinedAsync.ts
- multiplayer/src/epics/playerLeftAsync.ts
- multiplayer/src/epics/setUserProfileAsync.ts
- multiplayer/src/epics/userSignedInAsync.ts
- multiplayer/src/services/authClient.ts
- multiplayer/src/services/gameClient.ts
- pxtlib/auth.ts
- Point to staging multiplayer service
- Better separation of concerns in authClient and gameClient -- both call into epics now
> Point to staging endpoint. misc cleanup.

- pxtlib/docsrender.ts
- webapp/src/marked.tsx
> [stable8.3] video pause on hidden, restart at start time

- multiplayer/src/services/gameClient.ts
- multiplayer/src/types/index.ts
* `lookup` call is no longer needed with redis-based message routing
* `heartbeat` message is unnecessary with websockets.
> Remove `lookup` REST call, remove heartbeat

- multiplayer/src/services/gameClient.ts
Wait to resolve the promise until the client is fully joined to the game server
> More precise transition to "connected"

- localtypings/pxtarget.d.ts
> cleanup old keys in the target.config package section

- multiplayer/src/App.tsx
- multiplayer/src/components/AppModal.tsx
- multiplayer/src/components/GamePage.tsx
- multiplayer/src/components/HeaderBar.tsx
- multiplayer/src/components/HostGame.tsx
- multiplayer/src/components/HostLobbyModal.tsx
- multiplayer/src/components/JoinGame.tsx
- multiplayer/src/components/Presence.tsx
- multiplayer/src/components/Reactions.tsx
- multiplayer/src/components/SignedInPage.tsx
- multiplayer/src/epics/setGameModeAsync.ts
- multiplayer/src/state/actions.ts
- multiplayer/src/state/reducer.ts
- multiplayer/src/types/index.ts
- multiplayer/src/types/reactions.ts
No functional changes, but prettier had a lot to say.
> [multiplayer] prettier

- multiplayer/src/epics/index.ts
- multiplayer/src/epics/leaveGameAsync.ts
- multiplayer/src/epics/setGameMetadataAsync.ts
- multiplayer/src/services/gameClient.ts
- multiplayer/src/state/actions.ts
- multiplayer/src/state/reducer.ts
- multiplayer/src/state/state.ts
- multiplayer/src/types/index.ts
When the client joins a game, fetch the game's metadata (title, description, thumbnail) and add it to the app state, where it's available to the UI.
> download game metadata

- multiplayer/src/services/gameClient.ts
Disabling palette sync while I debug it locally.
> disable palette sync, for now

- multiplayer/src/App.tsx
- multiplayer/src/components/AppModal.tsx
- multiplayer/src/components/HeaderBar.tsx
- multiplayer/src/components/JoinGame.tsx
- multiplayer/src/components/SignInPage.tsx
- multiplayer/src/hooks/useAuthDialogMessages.ts
- multiplayer/src/services/gameClient.ts
- multiplayer/src/state/actions.ts
- multiplayer/src/state/reducer.ts
- multiplayer/src/state/state.ts
- multiplayer/src/util/index.ts
- react-common/components/profile/SignInModal.tsx
Deep link to join a game:
`https://arcade.makecode.com/--multiplayer?join=<joinCode>`
Deep link to host a game:
`https://arcade.makecode.com/--multiplayer?host=<shareUrl or shareCode>`
> Pass join code or share url as query param

- multiplayer/src/services/gameClient.ts
these values should probably be derived from webconfig / deploy config eventually but for now this feels like it should be fine to make it so all three environments can work with one commit / build of multiplayer app?
> multiplayer conditionally set GAME_HOST

- multiplayer/src/util/index.ts
Add short link generation based on the runtime environment.
> add short link helpers

- multiplayer/config-overrides.js
- multiplayer/package-lock.json
- multiplayer/package.json
- multiplayer/public/index.html
preserve html comments in production build
> fix telemetry in multiplayer client

- multiplayer/src/App.tsx
- multiplayer/src/components/AppModal.tsx
- multiplayer/src/components/SignInPage.tsx
- multiplayer/src/components/SignedOutPage.tsx
- react-common/components/controls/Modal.tsx
- react-common/components/profile/SignInModal.tsx
- react-common/styles/profile/profile.less
Fixes https://github.com/microsoft/pxt-arcade/issues/5220
> Don't allow signin dialog to be dismissed

- multiplayer/src/components/GamePage.tsx
- multiplayer/src/components/RemixGameButton.tsx
The vertical alignment seems off between the icon and text but after spending several hours trying to fix it, I've decided there may be more important issues to focus on. Open to suggestions!
> Add a Multiplayer Remix Game Button

- multiplayer/src/services/gameClient.ts
I suspect this is the source of the blank screens. Disabling delta compression until we have time to debug it.
Mitigates https://github.com/microsoft/pxt-arcade/issues/5202
> disable screen deltas, for now

- react-common/components/share/ShareInfo.tsx
- react-common/components/share/SocialButton.tsx
Adding ticks for various share features. This got lost in the last update. Please review they are at the right place.
> Adding ticks for share

- multiplayer/src/components/Presence.tsx
- multiplayer/src/epics/gameDisconnected.ts
- multiplayer/src/epics/joinGameAsync.ts
- multiplayer/src/services/gameClient.ts
- multiplayer/src/state/reducer.ts
- multiplayer/src/types/index.ts
* "game full" messaging
* "game not found" messaging
* app state: when going back to "init" state, reset a lot of other fields back to default.
* misc minor tweaks
> Show "game full" when game is full

- multiplayer/src/components/ArcadeSimulator.tsx
Snapping the sim from color to grayscale felt pretty jarring. Added a .25 sec transition.
> add css transition to sim grayscale

- multiplayer/src/components/Reactions.tsx
- multiplayer/src/epics/sendReactionAsync.ts
* add ui hints in reactions to show keyboard buttons
* make throttle per emoji
> Keyboard reactions finishing touches

- multiplayer/src/components/AppModal.tsx
- multiplayer/src/components/HeaderBar.tsx
- multiplayer/src/components/modals/ConfirmModal.tsx
- multiplayer/src/epics/index.ts
- multiplayer/src/epics/sendAbuseReportAsync.ts
> add report abuse dialog

- cli/cli.ts
- localtypings/pxtarget.d.ts
- multiplayer/src/components/HostGameButton.tsx
- multiplayer/src/components/JoinOrHost.tsx
- multiplayer/src/index.tsx
- multiplayer/src/state/actions.ts
- multiplayer/src/state/reducer.ts
- multiplayer/src/state/state.ts
close https://github.com/microsoft/pxt-arcade/issues/5275
can't make a meaningful build till https://github.com/microsoft/pxt-arcade/pull/5301 is in
One thing to note, I currently have it just put you immediately into the hosting game state when you click, do we want a confirmation dialog or anything? I think it's probably fine to merge in for now / for testing tomorrow without the dialog but not sure.
and truncates any long titles:
(something something it's just too perfect to not fit)
> Multiplayer show starter games

- webapp/src/app.tsx
I don't think this exception was actually causing anything bad to happen but @abchatra and I noticed it while debugging the share page.
> Add guard for shareeditor existing

- multiplayer/src/epics/notifyGameDisconnected.ts
- multiplayer/src/services/simHost.ts
- multiplayer/src/types/index.ts
When a game fails to compile kick them back to the lobby with an error msg
here's a test game https://arcade.makecode.com/S53442-66845-63450-74981 and test build https://arcade.makecode.com/app/ec3bc1503ea06af8b35cea5989a15893d50ba80c-6817c2d7b1--multiplayer?host=S53442-66845-63450-74981
> end lobby if game fails to compile

- multiplayer/src/index.tsx
I just copied what webapp does verbatim.
Tested in https://arcade.makecode.com/app/e55c04d3b3edeb69efa078bef1a89345912e1477-2cfa0d2adb, and looks to be sending ticks now.
> enable analytics in multiplayer

- multiplayer/src/components/HeaderBar.tsx
Based on changes in https://github.com/microsoft/pxt/pull/9224
> Fix docs link in header bar

- common-docs/multiplayer.md
This is a follow on to #9224 to restate the multiplayer "Safety" info section.
> Restate multiplayer safety policy

- docs/blog/csed-week/csed-week-2022.md
Fix botched path extension for Minecraft Escape Estate image.
RE: #9229
> Fix image path for csed week 2020 blog post

- pxtlib/service.ts
- webapp/src/extensionsBrowser.tsx
cherry pick https://github.com/microsoft/pxt/pull/9231 for microbit
> [stable8.0]  cherry pick extension search fixes

- webapp/src/extensionsBrowser.tsx
port over https://github.com/microsoft/pxt/pull/9249 for microbit branch
> [stable8.0] fix nested repos direct add

- pxtlib/service.ts
- webapp/src/app.tsx
- webapp/src/extensionsBrowser.tsx
cherry picking to minecraft release branch:
* https://github.com/microsoft/pxt/pull/9243
* https://github.com/microsoft/pxt/pull/9247
* https://github.com/microsoft/pxt/pull/9231
> [stable8.1] minecraft hoc & extensions cherry picks

- webapp/src/app.tsx
cherry picking one more fix: https://github.com/microsoft/pxt/pull/9252
> [stable8.1] Check for flyout only tut option

- package.json
> [stable7.0] Update puppeteer version

- pxtlib/cloud.ts
This got swapped to default to prod in https://github.com/microsoft/pxt/pull/9282, which makes multiplayer get mad when serving locally~
> swap default dev backend back to staging

- theme/tutorial-sidebar.less
- webapp/src/sidepanel.tsx
Reverts a recent css change I made.
Fixes https://github.com/microsoft/pxt-arcade/issues/5506
> fix file explorer justification

- pxtlib/tilemap.ts
- webapp/src/assets.ts
closes https://github.com/microsoft/pxt-arcade/issues/5078
> Sort non-builtin assets at top of gallery

- multiplayer/src/hooks/useAuthDialogMessages.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5204
> Don't use cryptic share code in UI string

- multiplayer/src/components/modals/ConfirmModal.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/5368
> Confirmation should be rightmost button

- multiplayer/src/epics/hostGameAsync.ts
- multiplayer/src/epics/joinGameAsync.ts
- multiplayer/src/epics/setGameMetadataAsync.ts
- multiplayer/src/index.tsx
- multiplayer/src/services/gameClient.ts
- multiplayer/src/services/simHost.ts
- pxtlib/multiplayerUtils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5334
> Put multiplayer debug output behind a flag

- multiplayer/src/components/JoinCodeLabel.tsx
- multiplayer/src/components/KeyboardControlsButton.tsx
- multiplayer/src/components/Popup.tsx
- multiplayer/src/components/Presence.tsx
- multiplayer/src/components/Reactions.tsx
- multiplayer/src/hooks/useClickedOutside.ts
- multiplayer/src/state/actions.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5313
> When a multiplayer popup is expanded, clicking the button again should hide it

- theme/tutorial-sidebar.less
fix https://github.com/microsoft/pxt-arcade/issues/5137
> fix next button getting cut off in spanish

- pxteditor/monaco-fields/field_musiceditor.ts
As the title says, defining a monaco field editor for the music editor.
> Add music editor to monaco

- pxtlib/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5400
just what the title says!
> fix bug where creating an animation doesn't save the project

- multiplayer/src/components/ArcadeSimulator.tsx
- multiplayer/src/epics/playerJoinedAsync.ts
- multiplayer/src/epics/playerLeftAsync.ts
- multiplayer/src/types/index.ts
Hook up player events connected / disconnected events, see https://github.com/microsoft/pxt-common-packages/pull/1407 for common packages event registration
> hook up player join / leave events to multiplayer

- pxtlib/music.ts
- webapp/src/components/musicEditor/MusicEditor.tsx
- webapp/src/components/musicEditor/NoteGroup.tsx
- webapp/src/components/musicEditor/keyboardNavigation.ts
- webapp/src/components/musicEditor/utils.ts
This improves the array of drum sounds that are available.
If you want to hear them, here's an arcade project that has 'em all:
https://arcade.makecode.com/beta#pub:52073-79957-62825-57855
Also it makes it so that you can add drum sounds to the bass clef, so 24 sounds are now available!
> Better drum sounds and add support for bass clef to drums

- webapp/src/simulator.ts
I'm not as good as my niece at counting to 4 apparently :(
> presence bar clear player 4 icon as well

- webapp/src/app.tsx
- webapp/src/components/musicEditor/utils.ts
includes drums fix and serviceworker fix
> [Stable 8.5] Cherry pick richard's fixes

- multiplayer/src/components/ArcadeSimulator.tsx
- multiplayer/src/epics/resumeGameAsync.ts
- multiplayer/src/services/gameClient.ts
- webapp/src/simulator.ts
cherry picking:
* https://github.com/microsoft/pxt/pull/9336
* https://github.com/microsoft/pxt/pull/9335
> [stable8.5] Joey stable8.5 cherry picks

- react-common/components/share/Kiosk.ts
- react-common/components/share/ShareInfo.tsx
Some changes added/made in response to comments left here https://github.com/microsoft/pxt/pull/9323.
For commentary about the telemetry added: https://github.com/microsoft/pxt/pull/9323#discussion_r1089564800
> Kiosk share: added notification for the empty case, added more telemetry

- webapp/src/app.tsx
cherry pick https://github.com/microsoft/pxt/pull/9343
> [stable8.5] fix so presence bar shows up in multiplayer skillmap

- pxtlib/react.ts
- webapp/src/app.tsx
- webapp/src/blocklyFieldView.tsx
- webapp/src/components/musicEditor/MusicEditor.tsx
- webapp/src/components/musicEditor/keyboardNavigation.ts
* Fix copy/paste
* don't start sim if react field view is visible
> [Stable 8.5] Cherry pick music editor hot fix

- pxteditor/editor.ts
- react-common/components/share/Share.tsx
- react-common/components/share/ShareInfo.tsx
- webapp/src/app.tsx
- webapp/src/share.tsx
- webapp/src/sidepanel.tsx
Currently does nothing! Only shows up in JavaScript.
> Add open in vs code button

- react-common/components/palette/ColorPickerField.tsx
Closes https://github.com/microsoft/pxt-arcade/issues/5613
> Color palette: disable first up arrow and last down arrow for moving colors

- docs/writing-docs/tutorials/basics.md
Figured I'd throw something together quickly, just so we have this information down somewhere. If we add more validators/properties in the future, it may be worth pulling this out of "Basics" and into its own file, but I didn't think that was necessary right out of the gate. I don't feel strongly, though, so if people would prefer to put it in its own section, let me know.
> Documentation for Code Validation in Tutorials

- react-common/components/palette/ColorPickerField.tsx
- react-common/styles/palette/ColorPickerField.less
- webapp/src/components/assetEditor/assetPalette.tsx
- https://github.com/microsoft/pxt/pull/9366
- https://github.com/microsoft/pxt/pull/9368
- https://github.com/microsoft/pxt/pull/9370
> [Stable 8.5] Cherry-pick color palette bug fixes

- docs/writing-docs/snippets.md
re: https://github.com/microsoft/pxt/pull/9359#discussion_r1093739108
> Add description on how to use hide, collapsed

- pxtlib/initprj.ts
add a `.vscode/extensions.ts` when initializing a new repo with the github integration. Haven't tested yet since I'm throwing up the uploadtrg right now but it's pretty simple so will attach a build in ~5 minutes when it's up & I've made a sample repo
> in github projects .vscode, recommend makecode vscode extension

- pxtlib/initprj.ts
Up to you if you wanna put out a hotfix for this, but it's nice to have~
porting https://github.com/microsoft/pxt/pull/9375 to arcade stable
> [stable8.5] in github projects .vscode, recommend makecode vscode extension

- pxtlib/initprj.ts
cherry pick https://github.com/microsoft/pxt/pull/9377, https://github.com/microsoft/pxt/pull/9379
> [stable8.5] gitignore .pxt & suppress .pxt / pxt_modules from file explorer

- localtypings/pxtmusic.d.ts
- pxtlib/music.ts
- pxtsim/simlib.ts
- pxtsim/sound/metronome.ts
- pxtsim/sound/sequencer.ts
- pxtsim/sound/song.ts
- webapp/src/components/musicEditor/MusicEditor.tsx
- webapp/src/components/musicEditor/Staff.tsx
- webapp/src/components/musicEditor/keyboardNavigation.ts
- webapp/src/components/musicEditor/playback.ts
Cherry picking for a patch release.
> [Stable 8.5] Refactor song sequencer/playback into pxsim (#9381)

- cli/cli.ts
- webapp/src/marked.tsx
cherry pick
* https://github.com/microsoft/pxt/pull/9383
* https://github.com/microsoft/pxt/pull/9384
> [stable8.5] Fix minify and inline snips

- react-common/components/share/ShareInfo.tsx
Hooking up the "Open in VS Code" that appears in TS so that it actually opens in insiders.
> Have the open in vscode button actually open in vscode

- theme/themes/pxt/globals/site.variables
- theme/tutorial-sidebar.less
We need to be able to set this to a different value for microbit.
> Create a Variable for the Mini-Playable Simulator Margin

- webapp/src/blocklyFieldView.tsx
Fixes the bug I mentioned in standup today.
to repro:
1. Open a project
2. Drag out a sound effect block
3. Open the sound effect editor and close it
4. Note that the sim hangs and won't restart
> Fix sim hang after the sound editor is dismissed

- webapp/src/blocklyFieldView.tsx
Cherry pick of the yet-to-be-merged PR https://github.com/microsoft/pxt/pull/9403
> [Stable 8.5] Fix sim hang after the sound editor is dismissed

- webapp/public/asseteditor.html
- webapp/public/index.html
- webapp/src/assetEditor.tsx
- webapp/src/components/ImageEditor/BottomBar.tsx
- webapp/src/components/ImageEditor/ImageCanvas.tsx
- webapp/src/components/ImageEditor/ImageEditor.tsx
- webapp/src/components/ImageFieldEditor.tsx
- webapp/src/components/MusicFieldEditor.tsx
- webapp/src/components/musicEditor/EditControls.tsx
- webapp/src/components/musicEditor/MusicEditor.tsx
* https://github.com/microsoft/pxt/pull/9378
* https://github.com/microsoft/pxt/pull/9389
* https://github.com/microsoft/pxt/pull/9394
I believe that was all unless you remember any others that would have snuck in a fix @riknoll, and rest will be in vscode extension fixing ref / possibly have to add an option for non-beta in pxt-mkc
> [stable8.5] asset editor paqe ports for vscode ext

- localtypings/pxtpackage.d.ts
- pxtlib/package.ts
- pxtlib/tilemap.ts
cherry pick https://github.com/microsoft/pxt/pull/9411 to arcade release branch
> [stable8.5] Port taggable assets fix

- pxtlib/tilemap.ts
- webapp/src/assetEditor.tsx
- webapp/src/components/ImageEditor/ImageEditor.tsx
Cherry picking the fixes I made for tilemap assets and songs.
All these changes are mostly limited to the asset editor page so this shouldn't really impact arcade much at all.
> [Stable8.5] Cherry pick more tilemap and song fixes

- theme/image-editor/imageEditor.less
- webapp/src/assetEditor.tsx
- webapp/src/components/ImageFieldEditor.tsx
port https://github.com/microsoft/pxt/pull/9423 to stable
> [stable8.5] Fixes for filters in asset editor page 

- webapp/src/assetEditor.tsx
cherry picking https://github.com/microsoft/pxt/pull/9427 over to the hotfix branch so we can sneak it in
> [stable8.5] allow passing display name for createAsset command

- docs/static/tutorial-tool/tutorial.js
Few other changes for consistency.
> adding beta option to microbit

- pxtlib/auth.ts
Client side changes to enable cross-domain login (approved targets and domains only!).
> Client changes for "auth code flow"

- pxtlib/cloud.ts
It always bugs me to see `www` on the url :)
> Tweak DEV_BACKEND_PROD value

- localtypings/pxtarget.d.ts
- localtypings/pxtpackage.d.ts
- pxteditor/editor.ts
- pxtlib/gallery.ts
- pxtlib/tutorial.ts
- pxtrunner/runner.ts
- pxtsim/embed.ts
- pxtsim/simdriver.ts
- webapp/src/app.tsx
- webapp/src/simulator.ts
cherry-pick for hotfix https://github.com/microsoft/pxt/pull/9449
> [stable8.5] Allowing setting a theme for sim (& palette) from tutorial md

- pxtcompiler/emitter/decompiler.ts
- tests/decompile-test/baselines/tagged_template_multiple.blocks
- tests/decompile-test/cases/tagged_template_multiple.ts
- tests/decompile-test/cases/testBlocks/templateStrings.ts
Cherry picking the freshly merged https://github.com/microsoft/pxt/pull/9466
> [Stable8.5] Cherry pick tagged template decompiler fix

- webapp/src/extensionsBrowser.tsx
When we moved to new extensions UI we lost all telemetry points. Adding them back.
> Missing extension telemetry

- webapp/src/cloud.ts
When the client wants to sync a specific subset of cloud projects, it can now pass a list of project IDs to the backend.
> Support partial cloud sync

- webapp/public/index.html
quick one liner change to try and get in context translations working for ev3, ported from https://github.com/microsoft/pxt/pull/8712/files#diff-198afb197d040dc8878f9954f8bfd155ee6c12537603f96af493031b731a06ffR11
> [stable7.2] cherry pick crowdin name inctx fix

- webapp/src/workspace.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5866
> Clear project publish metadata on duplicate

- webapp/src/cmds.ts
- webapp/src/dialogs.tsx
- webapp/src/webusb.tsx
re: https://github.com/microsoft/pxt-microbit/issues/4317, fix a few places where WebUSB was displayed in user facing strings incorrectly
> WebUSB is one word/capitalized

- react-common/styles/share/share.less
fix https://github.com/microsoft/pxt-microbit/issues/4787
> add a highlight to error message on fail to share

- pxtcompiler/emitter/decompiler.ts
- tests/decompile-test/baselines/pauseUntil.blocks
- tests/decompile-test/cases/pauseUntil.ts
fix https://github.com/microsoft/pxt-arcade/issues/5900
> pause until decompile allow identifier

- theme/common.less
- webapp/src/webusb.tsx
Allow slightly larger images in download flow; used it in the build for https://github.com/microsoft/pxt-microbit/pull/5144, might make some more minor adjustments on this branch if we go with that change
> allow large images in webusb dialog

- webapp/src/webusb.tsx
close https://github.com/microsoft/pxt-microbit/issues/5156
with the text changes:
> webusb pairing flow minor wording updates

- react-common/components/share/ThumbnailRecorder.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5154
> Fix undef label in thumbnail recorder

- pxtcompiler/emitter/hexfile.ts
- pxtlib/service.ts
So it can be checked webusb side in case of disabled variants
> include list of variants in compilation result

- webapp/src/coretsx.tsx
- webapp/src/sui.tsx
- webapp/src/webusb.tsx
> [stable9.0] Keep up browser webusb dialog gif while pairAsync

- pxtsim/simdriver.ts
Apparently the first sim never hits the 'start' message, that's only for second+ sim.
fix https://github.com/microsoft/pxt-microbit/issues/5243
build with test program https://makecode.microbit.org/app/236b7dcde6814d1fbd2f8e18abb75020fa5fabae-97e51189ad#pub:S38404-96542-17447-26597
> fix first sim radio

- webapp/src/components/tutorial/TutorialCallout.tsx
Cherry pick of https://github.com/microsoft/pxt/pull/9561
> Fix hint flickering

- pxtlib/auth.ts
Right now MakeCode always prompts the user to select an account when signing in. This is inconvenient in schools, where kids only have one account and there is never a need to select an account. This PR brings in support for silent single-sign-on (SSO), enabling zero-prompt authentication if it is available. SSO can fail if the provider requires user interaction (like getting consent). When this happens we'll fallback to an interactive login.
Additionally, if the user explicitly signs out, the next sign in will be interactive. This is to handle the case where SSO signed in with the wrong account and the user wants to log in with a different account.
> Support for silent SSO

- theme/common.less
Port of https://github.com/microsoft/pxt/pull/9570
> Improve Share Page Sandbox Display on Small Screens (#9570)

- webapp/src/app.tsx
fix for https://github.com/microsoft/pxt-microbit/issues/5291; was starting out as undefined here so it missed the switch cases in https://github.com/microsoft/pxt/pull/9568
edit: adding in build: https://makecode.microbit.org/app/454acd3f97de1e1c69acdbcad7e6d64fef33b0cc-91cc5d8900
> give a default state for mute

- webapp/src/app.tsx
> [stable9.0] give a default state for mute (#9581)

- theme/common.less
- webapp/src/marked.tsx
Port of https://github.com/microsoft/pxt/pull/9570 and https://github.com/microsoft/pxt/pull/9580.
I also had to update `marked.tsx` to fix a build issue...
> Fix small share page layout

- pxtlib/crowdin.ts
for https://github.com/microsoft/pxt-calliope/pull/222; we'll see if I need to do any of the other build fixes that have been needed along the way if the build fails here
> [stable7.0] Port crowdin 429 fix

- pxtblocks/fields/field_kind.ts
Cherry picking the kind rename/delete change to arcade stable.
> [Stable 8.5] Cherry pick "Add option to rename and delete user kinds (#9564)"

- pxtblocks/fields/field_kind.ts
pushing https://github.com/microsoft/pxt/pull/9590 to master, since I made the pr off stable8.5 by accident
> only mutate kinds of the same type on delete / rename

- webapp/src/editortoolbar.tsx
fix https://github.com/microsoft/pxt-microbit/issues/5306
> don't show connect device option in offline app

- webapp/src/editortoolbar.tsx
port https://github.com/microsoft/pxt/pull/9593 for microbit stable
> [stable9.0] don't show connect device option in offline app

- kiosk/src/Components/AddingGame.tsx
- kiosk/src/Components/GameOver.tsx
- kiosk/src/Components/MainMenu.tsx
- kiosk/src/Models/GamepadManager.ts
Made a few minor navigation improvements:
* Added navigation sounds to game over screen.
* Allow B button to exit Adding Game screen.
* Clear keyboard state in a few places. It can get out of sync with actual keyboard state after returning from a game.
> Kiosk: Made a few minor navigation improvements

- gulpfile.js
look i can't be expected to type so many letters i'm a busy guy
> add shorter --no-webapps alias

- webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2343
> don't start sim when switching to high contrast

- webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2358
Another self explanatory fix! I also async/await-ified the code while i was in there.
> Prevent simulator start on the home screen

- kiosk/src/Components/AddingGame.tsx
- kiosk/src/Components/ErrorModal.tsx
- kiosk/src/Components/GameMenu.tsx
- kiosk/src/Components/GameOver.tsx
- kiosk/src/Components/GameSlide.tsx
- kiosk/src/Components/GenericButton.tsx
- kiosk/src/Components/MainMenu.tsx
- kiosk/src/Components/Modal.tsx
- kiosk/src/Components/ScanQR.tsx
- kiosk/src/Hooks/useMakeNavigable.ts
- kiosk/src/Kiosk.css
Swap out kiosk's button control for react-common's.
> kiosk: use button control from react common

- kiosk/package-lock.json
- kiosk/package.json
- kiosk/src/Components/PlayingGame.tsx
- kiosk/src/Services/IndexedDb.ts
- kiosk/src/Services/LocalStorage.ts
- kiosk/src/Services/SimHostService.ts
We were hitting quota limits in local storage. Indexed db is much more forgiving.
> kiosk: store builtjs in indexeddb, not local storage

- webapp/public/run.html
> fix loadingColor regex in run.html

- webapp/src/gitjson.tsx
Forgot to include this change in https://github.com/microsoft/pxt/pull/9742
> Fix Release Zone on Main Branch

- localtypings/pxtarget.d.ts
- webapp/src/timeMachine.tsx
there will be a corresponding pr on pxt-minecraft
> add pxtarget theme for passing query params to time machine

- webapp/src/extensionsBrowser.tsx
Cherry picking https://github.com/microsoft/pxt/pull/9767 for Minecraft hotfix.
> [stable9.2] cherry-pick: added oniconclick to extension search input (#9767)

- theme/themes/pxt/collections/menu.overrides
Remove the scaling of the button to exit debug mode when hover.
https://github.com/microsoft/pxt/issues/9684
> Remove scaling at hover over the button to exit debug mode

- pxtcompiler/emitter/snippets.ts
cherry picking https://github.com/microsoft/pxt/pull/9777
> [stable9.2] Prevent python snippet enums from being snakified (#9777)

- webapp/src/app.tsx
Porting jacdac/robot fix (https://github.com/microsoft/pxt/commit/cf01a8928276296f660539845884b349a993192c) to stable 9.0
> Jacdac message stable9.0

- teachertool/src/components/ActiveRubricDisplay.tsx
- teachertool/src/components/CatalogModal.tsx
- teachertool/src/components/DebugInput.tsx
- teachertool/src/components/RubricWorkspace.tsx
- teachertool/src/components/ShareLinkInput.tsx
- teachertool/src/components/TabGroup.tsx
- teachertool/src/components/TabPanel.tsx
- teachertool/src/components/styling/RubricWorkspace.module.scss
- teachertool/src/components/styling/ShareLinkInput.module.scss
- teachertool/src/components/styling/TabGroup.module.scss
- teachertool/src/components/styling/TabPanel.module.scss
- teachertool/src/components/styling/Toolbar.module.scss
- teachertool/src/global.scss
- teachertool/src/state/actions.ts
- teachertool/src/state/reducer.ts
- teachertool/src/state/state.ts
- teachertool/src/style.overrides/Button.scss
- teachertool/src/transforms/setActiveTab.ts
- teachertool/src/types/index.ts
Adds tabbed view panel.
TODO in a future PR:
- Rubric scrolling needs attention.
- Deferring Home tab until we have an updated design.
> teacher tool: add tabbed view

- localtypings/pxteditor.d.ts
Left a necessary type reference out of the last pr!
> Add missing type reference in pxteditor.d.ts

- teachertool/src/components/CriteriaTable.tsx
- teachertool/src/components/RubricWorkspace.tsx
- teachertool/src/components/Toolbar.tsx
- teachertool/src/constants.ts
This adds a more detailed description for auto-run:
It also contains a fix for https://github.com/microsoft/pxt/pull/9871#discussion_r1499668204
> Teacher Tool: Descriptive Tooltip for Auto-Run

- package.json
- scripts/npm-prepare.js
- scripts/npm-prepare.sh
This approach seems to work better. Not sure why the bash script didn't!
> JS implementation of npm-prepare script

- common-docs/teachertool/catalog-shared.json
- teachertool/src/components/CatalogModal.tsx
- teachertool/src/components/CriteriaTable.tsx
- teachertool/src/components/styling/CatalogModal.module.scss
- teachertool/src/components/styling/CriteriaTable.module.scss
- teachertool/src/global.scss
- theme/themepacks.less
Descriptions are already supported in json, we just need to surface them.
Upload target: https://makecode.microbit.org/app/ecca55176b52d086276a3583f2f15fae73311be6-8bf3bccf62--eval?tc=1
Screenshots:
Relies on https://github.com/microsoft/pxt-microbit/pull/5508
> Show Criteria Descriptions in Catalog and Rubric Views

- common-docs/teachertool/catalog-shared.json
- common-docs/teachertool/test/catalog-shared.json
- common-docs/teachertool/test/validator-plans-shared.json
- common-docs/teachertool/validator-plans-shared.json
Porting common-docs changes to v9 branch (all teacher tool updates for catalog & validator plans).
> Port common-docs changes to v9

- pxtsim/sound/sequencer.ts
Cherry picking this fix to the arcade stable branch! This is for an extension we've been working on in stream. There will also be a common-packages fix
> [Stable8.5] Fix exception when disposing sim sequencers (#9919)

- common-docs/teachertool/catalog-shared.json
- common-docs/teachertool/test/catalog-shared.json
- common-docs/teachertool/test/validator-plans-shared.json
- common-docs/teachertool/validator-plans-shared.json
Release is still at v9 but uploaded targets use v10
> Port Common Docs Changes to v10

- webapp/src/components/tutorial/TutorialContainer.tsx
- webapp/src/immersivereader.tsx
- webapp/src/tutorial.tsx
* Update the immersive reader token (#9952)
> [stable8.5] Cherry-pick immersive reader token

- webapp/src/components/tutorial/TutorialContainer.tsx
- webapp/src/immersivereader.tsx
- webapp/src/tutorial.tsx
* Update the immersive reader token (#9952)
> [stable9.0] Immersive Reader Token Update

- cli/cli.ts
- cli/crowdin.ts
- cli/crowdinApi.ts
Cherry picking https://github.com/microsoft/pxt/pull/9966 to stable so I can test it in ev3
> [Stable9.3] Cherry picking crowdin fix to stable9.3

- docfiles/docs.html
- docfiles/tocheader.html
- gulpfile.js
- pxtblocks/codecardRenderer.ts
- pxtrunner/renderer.ts
- theme/docs.less
- theme/docs/tocheader.less
- theme/home.less
- webapp/public/docs.html
Reverting the revert from yesterday!
> Revert "temporarily revert my docs accessibility fixes (#9975)"

- webapp/src/idbworkspace.ts
Cherry picking two pouch migration fixes to stable.
> [Stable9.2] Cherry pick pouch migration fixes to minecraft stable

- common-docs/teachertool/catalog-shared.json
- teachertool/src/transforms/loadCatalogAsync.ts
Got feedback that we should move these to the top.
@Jaqster FYI
> Teacher Tool: Reorder catalog so copilot and "block used count times" are at the top.

- theme/themes/pxt/modules/modal.overrides
- webapp/src/container.tsx
- webapp/src/projects.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5480
Fixes https://github.com/microsoft/pxt-microbit/issues/5490
Fixes https://github.com/microsoft/pxt-microbit/issues/5451
> Accessibility compliance: settings title and sui modal button focus

- webapp/src/scriptmanager.tsx
- webapp/src/workspace.ts
splitted from https://github.com/microsoft/pxt/pull/10016
> Add rename button in all projects page

- webapp/src/scriptmanager.tsx
- webapp/src/workspace.ts
https://github.com/microsoft/pxt/pull/10017
@riknoll
> [Stable 9.3] Add rename button in all projects page

- docs/github-teacher-verification.md
Switch the video embed link to the old MakeCode flavored render style.
This video replaced the older image in #10027.
Closes #10031
> Format the embed video link for "Teacher Signup"

- common-docs/browsers/mac.md
Fixes https://github.com/microsoft/pxt-microbit/issues/5586
> Updated supported browser documentation

- webapp/src/serviceworker.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5687
When we load the serviceworker for the first time we cache index.html, but that doesn't cover requests that also have a query parameter in the url.
This PR caches responses when a query parameter is present and uses those as a fallback when we're offline. Note that this is only used as a fallback; we will still fetch live whenever possible.
At some point we should probably inventory every possible query parameter we pass on requests to index.html; a lot of them could probably be moved into the URL hash so that they don't bust the service worker cache. For those that we have already shipped (e.g. minecraft) we can create an allowlist that lets us serve the cached index.html sans query parameters if the cache misses. I'll create an …
> Fall back to cache when fetching index.html with a query param

- kiosk/src/Components/PlayingGame.tsx
* now using the config run url if it exists
* use nullish coalescing and relative url paths
> [cherry pick to stable8.5] Kiosk: now using the config run url if it exists (#10048)

- webapp/src/components/soundEffectEditor/soundUtil.ts
Part of the fix for https://github.com/microsoft/pxt-microbit/issues/5569
Reads the DAL constants for the default effect parameters if possible.
> Attempt to read the DAL values for sound effect editor effect constants

- pxtblocks/fields/field_textdropdown.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5437
Correcting the text positioning for RTL blocks.
> Fix RTL text positioning for number dropdown field

- theme/tutorial-sidebar.less
- webapp/src/app.tsx
- webapp/src/sidepanel.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5646
also fixed a line in app.tsx where it seems like someone forgot to call a function.
> Fix sidebar height for tutorials with legacy layout

- cli/crowdin.ts
micro:bit failed on what [seems like a transient issue](https://github.com/microsoft/pxt-arcade/actions/runs/10323211879/job/28580082038) so adding some retry logic.
arcade failed when it [tried to upload an empty file](https://github.com/microsoft/pxt-arcade/actions/runs/10323211879/job/28580082038), so also checking for that.
> Add retries to crowdin file upload and don't upload empty files

- pxtblocks/layout.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5780
This expands our alignBlocks function to also move comments around based on the previous workspace after decompiling.
I also cleaned up the existing code a bit.
> Try to patch comments based on old blockly workspace

- libs/pxt-common/pxt-core.d.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5430
> Adding char code at api to blocks

- localtypings/pxtarget.d.ts
- pxtlib/tutorial.ts
- webapp/src/app.tsx
Cherry picking #10097 over to minecraft's stable
> [stable9.2] Cherry pick python template changes

- pxtblocks/fields/field_ledmatrix.ts
Fixes the led matrix portion of https://github.com/microsoft/pxt-microbit/issues/5759
> make ledmatrix field respect readonly mode

- cli/server.ts
- teachertool/public/index.html
Fixes https://github.com/microsoft/pxt-microbit/issues/5828 (favicon)
Fixes https://github.com/microsoft/pxt-microbit/issues/5818 (page title)
> teacher tool: include appdata.html in page

- teachertool/src/components/MakecodeFrame.tsx
Useful for getting more context when debugging
> Teacher Tool: Pass debug & console tick flags to iframe

- webapp/src/hinttooltip.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5845
fixes https://github.com/microsoft/pxt-microbit/issues/5854
i'm not sure how this broke but fixing this fixes the issue and closing issues is my job not solving mysteries
> don't error when a hint is missing from a tutorial step

- webapp/src/app.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5637
just propagating the same change that fixed https://github.com/microsoft/pxt-microbit/issues/5662
> generate toolbox blocks recursively in iframe handler

- pxtblocks/contextMenu/workspaceItems.ts
- pxtblocks/external.ts
- webapp/src/blocks.tsx
Fixes the problem mentioned here:
https://github.com/microsoft/pxt-microbit/issues/5861#issuecomment-2316312229
> Restore the find option in the workspace context menu

- pxtblocks/plugins/comments/textinput_bubble.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5890
fixes https://github.com/microsoft/pxt-microbit/issues/5884
> fix comment textarea position in firefox/safari

- pxtblocks/plugins/comments/textinput_bubble.ts
Cherry picking the comment fix to stable
> [stable10.2] fix comment textarea position in firefox/safari (#10142)

- teachertool/src/services/backendRequests.ts
Port of https://github.com/microsoft/pxt/pull/10152
> Port Fix AI Response Parsing to Stable10.2

- pxtblocks/contextMenu/blockItems.ts
temporarily set the duplicateOnDrag_ mutation to false
> fix duplicating duplicate on drag blocks

- pxtblocks/contextMenu/blockItems.ts
> [Stable 10.2] fix duplicating duplicate on drag blocks (#10160)

- teachertool/src/components/CatalogOverlay.tsx
- teachertool/src/components/styling/CriteriaInstanceDisplay.module.scss
- teachertool/src/components/styling/EvalResultDisplay.module.scss
- teachertool/src/constants.ts
- teachertool/src/services/backendRequests.ts
This change makes a few small UI fixes:
1. Fixes width of criteria on firefox (webkit not supported)
2. Remove "Max" and display a permanent check instead when the user reaches the max allowed count for a criteria.
3. Fix line wrapping for criteria
Fixes https://github.com/microsoft/pxt-microbit/issues/5927
Fixes https://github.com/microsoft/pxt-microbit/issues/5934
Fixes https://github.com/microsoft/pxt-microbit/issues/5851
Upload target: https://makecode.microbit.org/app/38bf04a7d1443044cd34d10b3a6edd51761140f9-09bd2a25d5--eval
> Teacher Tool: Assorted Small UI Fixes

- webapp/src/container.tsx
close https://github.com/microsoft/pxt-bedrock/issues/15
> show downloadmenuitems in cogwheel if headless

- webapp/src/fileworkspace.ts
one more patch re: version history, wasn't seeing this in local build but installer version seems to show an error sometimes, leaves history without a first entry. will port to microbit stable / rebuild
> fileworkspace: handle fully null case as well

- pxtarget.json
Looks like this has been disabled for a while, so new strings haven't been getting uploaded.
should close https://github.com/microsoft/pxt-microbit/issues/5969, will see after build goes through when merged.
> enable uploadDocs

- webapp/src/greenscreen.tsx
Permission granted via https://github.com/microsoft/pxt-electron/pull/251
> electron now giving permission for user media request

- webapp/src/blocks.tsx
Fixes the exception currently reproduceable on minecraft beta
> wait for render before setting blockly theme

- pxtblocks/plugins/logic/ifElse.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5984
Fixes https://github.com/microsoft/pxt-microbit/issues/5899
this fixes the weird orphaned block issue for the shadow blocks of if/else statements and also fixes a number of unreported problems having to do with undo/redo
> fix shadow blocks of if/else value inputs

- pxtsim/simdriver.ts
The foundation folks identified a case where the simulator extension URL could be incorrect.
cc: @microbit-matt-hillsdon @microbit-robert
> Fix simx path formatting issue

- teachertool/src/components/HeaderBar.tsx
- teachertool/src/components/styling/HeaderBar.module.scss
- teachertool/src/constants.ts
tada:
This was a requirement for the privacy review.
> teacher tool: add gear menu to host privacy links

- pxtlib/package.ts
- webapp/src/idbworkspace.ts
i saw two TypeErrors constantly being thrown in our minecraft telemetry; both were easy to track down. i haven't tried reproducing them but i feel pretty confident that this fix is safe.
> Fix a couple of exceptions seen in minecraft logs

- webapp/src/scriptmanager.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2656
Before:
After:
> Fix Duplicate Rename and Open Icons

- webapp/src/scriptmanager.tsx
Port of https://github.com/microsoft/pxt/pull/10269
> Fix Duplicate Rename and Open Icons (#10269)

- theme/tutorial.less
- webapp/src/marked.tsx
* fix the tabbing for has categories check
* add support for image icons in inline blocks in tutorials
> [stable11.2] port agent icon fix

- webapp/src/extensionsBrowser.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/2669
> hide extension import file button on platforms without file access

- webapp/src/idbworkspace.ts
fixes https://github.com/microsoft/pxt/issues/10279
not sure how we didn't catch this in testing
> handle repopaths with github prefix

- common-docs/types/number.md
- common-docs/types/string.md
A few updates to the the `string` and `number` type reference pages.
RE: https://github.com/microsoft/pxt-microbit/issues/6020
> Slight updates to base type ref pages

- webapp/src/blocks.tsx
Cherry picking https://github.com/microsoft/pxt/pull/10307 to micro-bit stable. Adds the ability to localize blocks help pages
> [Stable11.1] Cherry pick help docs localization to micro:bit stable

- webapp/src/blocks.tsx
cherry picking the fix from @microbit-matt-hillsdon
> [Stable11.1]Fix localisation of help docs for langs like 'fr' (#10310)

- package.json
> Bump patch version after including CDN changes in pxt-core

- tests/blocks-test/karma.conf.js
forgot that we also have another karma config for target tests
> patch blocks test karma config also

- docs/blog.md
- docs/blog/SUMMARY.md
- docs/blog/tools/code-eval-tool.md
Import, format, prepare the blog post introducing the beta of the Code Evaluation Tool.
Closes #10338
> Code Evaluation tool blog post

- react-common/components/controls/Input.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6637
also fixes the react warning about uncontrolled components that appears in the console
> fix measures field in playback controls

- pxtlib/util.ts
English name and localized name from here: https://en.wikipedia.org/wiki/List_of_language_names
> Adding Guarani language

- react-common/components/share/ShareInfo.tsx
we noticed this on stream so quick fix in case we forget
> use non-insiders for open in vscode dev

- react-common/components/controls/Feedback/Feedback.tsx
- react-common/components/controls/Feedback/configs.ts
- skillmap/src/components/HeaderBar.tsx
- webapp/src/container.tsx
- webapp/src/projects.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6794
Also made the configs be returned by functions to ensure that locale and other configuration stuff is loaded before the configs are generated. Thanks @riknoll for the suggestion.
> Ocv tweaks

- webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6815
fixes the paste coordinates for cross-tab copy/pastes and also adds some logic to paste at the context menu location if paste is selected with a right click
> fix cross-tab paste location and use context menu position when available

- react-common/components/share/ShareInfo.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6849
pretty self explanatory! not sure why this regressed though
> fix name input in share info

- pxtblocks/plugins/functions/fields/fieldArgumentEditor.ts
- pxtblocks/workspaceSearch.ts
- theme/blockly-core.less
- theme/color-themes/overrides/high-contrast-overrides.css
- theme/home.less
- theme/semantic-ui-overrides.less
- webapp/src/sidepanel.tsx
1 commit = 1 fix
Fixes https://github.com/microsoft/pxt-arcade/issues/6845
Fixes https://github.com/microsoft/pxt-arcade/issues/6839 (pxt-arcade changes also needed to invert search icons: https://github.com/microsoft/pxt-arcade/pull/6850)
Fixes https://github.com/microsoft/pxt-arcade/issues/6841
Fixes https://github.com/microsoft/pxt-arcade/issues/6840
Fixes https://github.com/microsoft/pxt-arcade/issues/6842
Also, adjust inputs so they don't look disabled. Would appreciate a 2nd pair of eyes on that, since apparently I can't always tell the difference :)
Upload target: https://arcade.makecode.com/app/12e6e4076c77ef009b2b88de734fe6bab000b830-75686f1856
> Some More Assorted Themes Fixes

- pxtblocks/plugins/functions/fields/fieldArgumentEditor.ts
- pxtblocks/workspaceSearch.ts
- skillmap/src/components/makecodeFrame.tsx
- theme/blockly-core.less
- theme/color-themes/overrides/high-contrast-overrides.css
- theme/home.less
- theme/semantic-ui-overrides.less
- webapp/src/auth.ts
- webapp/src/sidepanel.tsx
Port of https://github.com/microsoft/pxt/pull/10448 (https://github.com/microsoft/pxt/commit/425a6e3b30c5ca49272ce08ed9758406c2824648) and https://github.com/microsoft/pxt/pull/10450 (https://github.com/microsoft/pxt/commit/9f1e3348658c06264c91b69ceba3b03ecdd249be)
> Port to Stable: Themes Fixes

- theme/themes/pxt/views/card.overrides
Port of #10455
Fixes the color in the "see all projects" card.
> Port to stable: Fix "See All Projects" Color (#10455)

- pxtblocks/fields/field_tileset.ts
this fixes the issue reported by code ninjas where the tileset field editor was outputting the qualified name of the tile (e.g. myTiles.tile1) even in the case where the tile had a display name
> fix tileset field editor output for qualified names

- localtypings/pxtpackage.d.ts
- webapp/src/projects.tsx
https://github.com/microsoft/pxt/pull/10471
> [Stable11.3] cherry pick home page share url fix

- cli/cli.ts
- gulpfile.js
- pxtblocks/builtins/functions.ts
- pxtblocks/plugins/functions/blocks/functionDeclarationBlock.ts
- pxtblocks/plugins/functions/extensions.ts
- pxtblocks/plugins/functions/utils.ts
- pxtlib/spriteutils.ts
- pxtlib/tilemap.ts
- webapp/src/blocks.tsx
- webapp/src/createFunction.tsx
- webapp/src/workspace.ts
https://github.com/microsoft/pxt/pull/10477
https://github.com/microsoft/pxt/pull/10479
https://github.com/microsoft/pxt/pull/10482
https://github.com/microsoft/pxt/pull/10484
> [Stable11.3] Cherry pick hotfix changes

- react-common/components/share/ShareInfo.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6895
> Fix the dialog for sharing vscode

- skillmap/src/components/makecodeFrame.tsx
Port of https://github.com/microsoft/pxt/pull/10516
> Port to Stable: Remove the loading state set when the iframe load event fires. (#10516)

- webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4944
> Avoid file paste when block paste also happens

- pxtblocks/plugins/duplicateOnDrag/dragStrategy.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5959
just syncing some code with the implementation in blockly, which also happens to fix the above issue.
> sync block drag stratefy with reference implementation

- pxtblocks/layout.ts
- webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6216
this fixes a couple of bugs caused by my recent blockly changes in the code eval tool. both are just null checks
> fix a couple of blockly bugs in the code eval embed

- common-docs/browsers.md
- common-docs/browsers/technical.md
Revise the browser version info pages.
Closes https://github.com/microsoft/pxt-microbit/issues/6239
> Update browser compatibility info pages

- webapp/src/timeMachine.tsx
not really sure why i added this in the first place!
fixes https://github.com/microsoft/pxt-microbit/issues/6080
> remove create portal in time machine dialog

- pxtblocks/plugins/comments/bubble.ts
- pxtblocks/plugins/comments/textinput_bubble.ts
fixes the blocks comment part of https://github.com/microsoft/pxt-microbit/issues/6284
syncing upstream changes from blockly to our blocks comment implementations
> sync blockly bubble changes

- pxtsim/libgeneric.ts
- pxtsim/simlib.ts
in support of https://github.com/microsoft/pxt-microbit/pull/6114
> add sample playback to AudioContextManager

- webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6304
> use new setIsReadonly api

- pxtblocks/plugins/renderer/constants.ts
- pxteditor/monaco.ts
- react-common/styles/profile/profile.less
- theme/monaco.less
- theme/themes/pxt/globals/site.variables
- tutorialtool/src/utils/monaco.ts
- webapp/public/docs.html
fixes https://github.com/microsoft/pxt-microbit/issues/6329
> move consolas to front of font family string

- theme/color-themes/overrides/high-contrast-overrides.css
- theme/greenscreen.less
- theme/home.less
- theme/semantic-ui-overrides.less
- webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/6335 (as requested, enforce default theme when using greenscreen)
Fixes https://github.com/microsoft/pxt-microbit/issues/6355
Fixes https://github.com/microsoft/pxt-microbit/issues/6354
> Microbit Theme Fixes

- webapp/src/onboarding.ts
The pxt-side of the fix for https://github.com/microsoft/pxt-microbit/issues/5037
> Support sign in and user profile sections in the tour

- .vscode/launch.json
- localtypings/pxtarget.d.ts
- pxtcompiler/emitter/driver.ts
I guess I missed a spot (or two) in my first iteration!
> TAKE 2: Add `buildcoredts` cli command

- theme/themes/pxt/modules/modal.overrides
Fixes https://github.com/microsoft/pxt-microbit/issues/6116
> make inner outline black for focus on lighter buttons

- theme/color-themes/overrides/high-contrast-overrides.css
- theme/github.less
- theme/monaco.less
- theme/semantic-ui-overrides.less
- theme/toolbox.less
This change has a bunch of little theme fixes:
1. Fixes https://github.com/microsoft/pxt-microbit/issues/6401
2. Fixes https://github.com/microsoft/pxt-microbit/issues/6394
3. Fixes https://github.com/microsoft/pxt-microbit/issues/6387
4. Fixes https://github.com/microsoft/pxt-microbit/issues/6378
5. Fixes https://github.com/microsoft/pxt-microbit/issues/6383
6. Partially fixes https://github.com/microsoft/pxt-microbit/issues/6400 (rest of the change in microbit: https://github.com/microsoft/pxt-microbit/pull/6410).
Upload target: https://makecode.microbit.org/app/f8bf6b538b454e6144407f99ad856a78ea34955a-43291059e6
> Theme Fixes

- webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/6441
> Filter out all flyout bocks from error helper tour query selector

- webapp/src/shortcut_formatting.ts
Prefer Cmd+Shift+Z to Shift+Cmd+Z.
Simplify to translate last when manipulating shortcuts.
I tried fixing this in Blockly by registering the shortcut in the correct sequence, but I think they must normalise the shortcuts into the less helpful order.
> Fix redo shortcut order

- theme/common.less
- theme/sidedoc.less
Port of https://github.com/microsoft/pxt/commit/247938ec1fe7a7e6428cd52a942ff8e266b13ce5
> Fix sidedocs + experiments banner layout (#10752)

- react-common/styles/controls/DraggableGraph.less
Fixes https://github.com/microsoft/pxt-microbit/issues/6483
It was using stroke to set the color, but we actually want to use the fill property here.
> Fix sound effect editor graph text

- docs/blog/microbit/2025-update.md
Changes requested by the Foundation
> Update Micro:bit 2025 blog post for accuracy

- pxteditor/experiments.ts
- webapp/src/errorList.tsx
> Port to stable: Do not show AI Error Help in offline app (#10795)

- docfiles/offline-app-body.html
- docfiles/offline-app-head.html
port https://github.com/microsoft/pxt/pull/10804 for arm builds
> [stable12.0] port offline app page arm updates 

- common-docs/SUMMARY.md
- common-docs/reset.md
- common-docs/save.md
Add a destination help page for the "Reset" feature.
Kind of light on info in here so far. What else is affected by "Reset"?
Closes #10822
> Reset feature page

- webapp/src/toolboxeditor.tsx
cherry pick https://github.com/microsoft/pxt/pull/10884
> [stable11.3] fix extension button filtering logic
