skillmap/src/components/makecodeFrame.tsx, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/components/assetEditor/editor.tsx, webapp/src/monaco.tsx
We use the tutorial.editorLoaded tick event in the skillmap to indicate when it's safe to show the code carryover dialog. We were firing it a little too early, which meant that if you made a choice in that dialog too quickly you could get an error caused by interleaving the load of two projects. Moving that event to later in the lifecycle to make sure the first load is complete.
I also added it in monaco/asset editor but did not test those.
=> Don't fire editorloaded too early

pxteditor/monaco-fields/field_sprite.ts, webapp/src/components/ImageEditor/BottomBar.tsx
Fixes: https://github.com/microsoft/pxt-arcade/issues/3277
We were allowing assets to be saved with leading and trailing whitespace, which caused problems because our lookup function trims whitespace:
https://github.com/microsoft/pxt/blob/master/pxtlib/tilemap.ts#L1370
Now when we validate, lookup or commit an asset name change, we trim whitespace.
=> Trim asset names during rename

theme/image-editor/imageEditor.less, webapp/src/components/ImageFieldEditor.tsx
the 'X' button will save the user's progress and close. 
it's fine on desktop/tablet:
pretty tight on mobile though. i could hide the x button entirely here, since they still have the done button at the bottom?
=> Add 'x' button to image/tilemap editor top bar, saves & closes

skillmap/src/App.css, skillmap/src/components/HeaderBar.tsx, skillmap/src/styles/graphnode.css, skillmap/src/styles/skillgraph.css
Fixes https://github.com/microsoft/pxt-arcade/issues/3266
Fixes https://github.com/microsoft/pxt-arcade/issues/3267
Requires https://github.com/microsoft/pxt-arcade/pull/3282
Also fixes the skillmap background stretching in Safari (Safari doesn't like it if you put images in flexboxes).
Also includes a bunch of mobile fixes for the header. We still have lots of problems on mobile, but at least the header looks nice now:
=> Small CSS fixes for skillmap

webapp/src/cloud.ts
Our sync algorithm wasn't pushing local changes in all cases.
Also improves our ticks during conflict resolution.
Fixes: https://github.com/microsoft/pxt-arcade/issues/3254
_might_ fix this too: https://github.com/microsoft/pxt-arcade/issues/3228
but since I don't have a consistent repro it's hard to say. Certainly the window for conflicts is larger without this PR since changes are synced less often.
=> Check for "cloudCurrent" field when comparing local vs cloud

skillmap/src/components/AppModal.tsx, skillmap/src/components/InfoPanel.tsx, skillmap/src/lib/codeCarryover.ts, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapUtils.ts, skillmap/src/store/reducer.ts
there's some merge weirdness going on, but here's the carryover pulling from the latest completed activity
fixes https://github.com/microsoft/pxt-arcade/issues/3280
=> Code carries over from most recently completed activity

skillmap/src/App.tsx
Don't read the URL from the targetconfig, so that we can update the default in the targetconfig
=> [stable6.8] Pin stable V1 skillmap default to pxt-skillmap-sample

skillmap/src/components/InfoPanel.tsx
hide the "# rewards" text if there are no rewards present in the map! otherwise the text shows the total number of rewards
fixes https://github.com/microsoft/pxt-arcade/issues/3294
=> Hide reward text if no rewards present

webapp/src/components/ImageFieldEditor.tsx
the main issue was this line: https://github.com/microsoft/pxt/blob/master/webapp/src/components/ImageFieldEditor.tsx#L316 being run for every asset in the gallery, when that filtering really only needs to happen if you are in the "My Assets" view. i also did a little shifting around so the gallery stuff and general filtering in only called in the relevant views, so if you DID have a ton of very large images in my assets, at least the initial editor load will be fast
build here: https://arcade.makecode.com/app/a3691926ebf6e4f7dd0906e42b21a444a61bbce8-288c818e38
fixes https://github.com/microsoft/pxt-arcade/issues/3269
=> Only do necessary filtering on gallery to help image editor perf

package.json, pxtblocks/blocklyloader.ts
Requires https://github.com/microsoft/pxt-blockly/pull/341
Fixes https://github.com/microsoft/pxt-arcade/issues/3220
Removes the remaining context menu edit options and also the "create get 'var'" option on for-loops which does not work and hasn't ever since we switched it to be draggable. I guess we just never noticed.
=> Removing edit options from workspace in debug mode

skillmap/src/components/ActivityActions.tsx, skillmap/src/components/AppModal.tsx, skillmap/src/components/RewardActions.tsx, skillmap/src/components/SkillGraph.tsx
@abchatra @Jaqster Skill map V2 telemetry
`skillmap.sidebar.restart` - Restart button clicked on the sidebar (displays modal -> there's a separate tick for actually restarting)
`skillmap.sidebar.share` - Share button clicked on sidebar (displays modal)
`skillmap.sidebar.reward` - Reward button clicked on sidebar (modal)
`skillmap.reward` - Previously `skillmap.certificate`
`skillmap.share` - "Publish" button clicked in the share dialog
`skillmap.share.copy` - "Copy" button clicked in the share dialog (after publishing)
`skillmap.startfresh` - Start fresh (in the code carryover modal)
`skillmap.keepcode` - Keep code from previous activity
Our previous select/deselect ticks are `skillmap.carousel.item.select` -- I made new ticks for the graph/V2 layout but I can rename these to match the …
=> Skill map V2 instrumentation pass

theme/image-editor/imageEditor.less, webapp/src/components/ImageFieldEditor.tsx
- Add icons to image editor toggle, hide text and use icons in mobile view
- Hide the temp asset warning triangle in the image editor "My Assets" (still visible from asset editor tab) (fixes https://github.com/microsoft/pxt-arcade/issues/3284)
=> Mobile image editor toggle icons, hide temp asset warning

skillmap/src/lib/browserUtils.ts, skillmap/src/lib/skillMapUtils.ts
realized the previous code for migrating user progress from one pageSourceUrl to another assumed that the origin of the progress would always be github. this generalizes to allow docs urls
the expected format of the `alternatesources` field is `docs:/path/to/file` or `github:/user/repo/file`
=> Allow user to specify docs: or github: in skill map progress migration

theme/highcontrast.less, theme/themes/pxt/collections/menu.overrides, theme/tutorial.less, webapp/src/container.tsx, webapp/src/immersivereader.tsx, webapp/src/sui.tsx, webapp/src/tutorial.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3317 tooltip says "Launch Immersive Reader"
uploadtrg! https://arcade.makecode.com/app/2bf8ddd106e873c066702f4ea6e3ee00aca4b2e5-72e4c2c947
skillmap:
recipe:
ALSO fixes this bug, sorry guys >>
=> Add Immersive Reader for skillmap and recipes, add hover text

webapp/src/immersivereader.tsx
My sister-in-law came over so I had her check over chase the pizza in japanese, and these are mainly changes to accommodate / fix that -- had to do a few before hand to get it to to a testable state in japanese as some of the snippets weren't showing up properly. She said the immersive reader experience in japanese was good / made sense ~ (also included one or two small things I noticed while waiting for builds / looking at galga)
Here's a build https://arcade.makecode.com/app/d3e0f1ceb8df0f341f308138eff658bc9052a990-2daf2fa76b
(@livcheerful feel free to change anything or tell me to change anything at your judgement for the replacements~)
* For block snippet replacements, the {} really stood out / didn't make any sense to her. Swapped that with quotation marks, and removed the …
=> more immersive reader beautification

skillmap/src/components/InfoPanel.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3345
=> Display unlocked rewards out of total reward count in skill map

webapp/src/app.tsx
When compiling and deploying, restart the simulator during deployment to speed up experience.
This is particularly important for Jacdac where we rely on a race to determine which device should be in proxy and non-proxy. This is also interresting for Arcade where the simulator becomes responsive again much faster.
=> Fast simulator restart on compile

pxtlib/commonutil.ts, pxtlib/emitter/cloud.ts, pxtlib/package.ts, pxtlib/util.ts, pxtrunner/runner.ts, skillmap/src/App.tsx, webapp/src/app.tsx
Right now we're sending out `live=1` VERY aggressively in our translated markdown requests, and we should not be doing that. It looks like over time two distinct uses of live translations got combined -- updating the translations that are packaged with the editor, and fetching translations that are "live" / not yet approved
The change in `downloadLiveTranslationsAsync->downloadFromCloudAsync` isn't strictly necessary / I was mainly just checking if that needed to be fixed as well, but small enough it seemed like it should be included so those can get fetched appropriately as well?
=> Separate live updates from unapproved translations for md

pxtlib/service.ts
Fix https://github.com/microsoft/pxt-arcade/issues/3110
Make it so blockAliasFor also takes localizations if the other block is translated and this one is not (iff the block has the same definition).
Also make it so blocklAliasFor and useLoc take the localizations for the parameters / jsdoc if available, and support the alternate translation in jsdoc format.
Minor change that this will use the parameters localization even if the regular jsdoc isn't translated; easy to change back but not sure why we would ignore those translations~
=> make useLoc work for jsdoc, also take localizations with blockAliasFor

theme/asset-editor.less, theme/image-editor/sideBar.less, theme/tutorial.less, webapp/src/blocklyFieldView.tsx, webapp/src/components/assetEditor/editor.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3356
Also make the image editor extend over the editor toolbar (clicking it just dismissed the image editor previously, so no real reason to show it) and makes it so that the asset editor sidebar scrolls when needed.
=> Adjust the asset editor sidebar in asset editor-tutorials

pxtlib/tutorial.ts
there was a bug where having an unrecognized snippet (eg `package`) would break all subsequent snippets since the regex matches the trailing \`\`\` . this restricts it to match only on snippets that we know; i don't think we were relying on replacing the untagged snippets anywhere?
=> Only match recognized snippets when parsing tutorial metadata

docs/writing-docs/tutorials/control-options.md, localtypings/pxtarget.d.ts, pxtlib/main.ts, pxtlib/tutorial.ts, webapp/src/app.tsx
proposing a new tutorial snippet type! the `customts` snippet allows you to write some typescript that's added to a hidden file in the tutorial project--essentially this is like adding an extension, but the code lives with the tutorial and works better with the existing `assetjson` snippet
build + example content, the hidden code creates a "camera" sprite that allows the user to pan the game around with the dpad--we want to hide this to make the game code easier to debug:
https://arcade.makecode.com/app/026265abbadd99d99736bf3e271d1a5b621c64d3-f5083f4725#tutorial:49840-40808-29707-30223
=> Add customts snippet type for loading hidden ts into tutorials

docs/translate.md
In https://github.com/microsoft/pxt/pull/7989 we dropped the ability to fetch unapproved translations through the livelang query parameter, so it is now available only through the in context translations feature. Updating documentation to reflect that~
=> remove mention of livelang= from the translation docs

pxtlib/spriteutils.ts
fix https://github.com/microsoft/pxt-arcade/issues/3364
I don't see a reason to support 0x0 bitmaps, but if there's a better location for this fix happy to do it; root of the problem is that https://github.com/microsoft/pxt/blob/5c832a89a7b51e8d8ce4c78f9da36de82142bf4f/pxtlib/spriteutils.ts#L591  is ending up with the empty string and parsing as 0 width / 0 height, could see making that return undefined on empty & handling in monaco-fields/field_sprite (but I do kind of like the behavior it currently has if you have an invalid sprite of crashing / not opening -- could maybe give a toast but at least if you accidentally type a z into the sprite it will crash rather than destroy it)
=> give bitmaps default 16x16 if 0 height / 0 width

pxtlib/emitter/cloud.ts, pxtlib/service.ts, pxtlib/spriteutils.ts
* in context translation fix for some block flyouts breaking https://github.com/microsoft/pxt/pull/8000
* fix translation for the sprite create reporter block https://github.com/microsoft/pxt/pull/7996
* don't fetch unapproved localizations for md -- https://github.com/microsoft/pxt/commit/db148da35097f5fd0df1cf234287052f16e89ed1, pulled out of https://github.com/microsoft/pxt/pull/7989 as a more minimal change for stable branch.
* fix `` img` ` `` in monaco https://github.com/microsoft/pxt/pull/8009
Left out https://github.com/microsoft/pxt/pull/7986 for now to avoid any merge weirdness since vivian has some other changes in the same space that are going to come in later / easier to port those two together~
=> [stable6.12] Arcade stable ports

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_utils.ts, pxtlib/tilemap.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/store/assetEditorReducer.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3296
This PR changes how we store temporary assets a bit. We used to store them in the tilemap project, which was very error prone because it was difficult to keep the tilemap project and blocks file in sync. Now it just stores them in the blocks themselves, and fetches them from the workspace when opening the asset editor and "my assets" tab.
This fixes a lot of undo/redo bugs and probably quite a few other "disappearing asset" cases that we haven't reported. It also should fix the bug we saw on stream the other day where we lost all of our assets when skipping javascript decompile.
From my testing, this seems much more stable than it was before. Still we should make sure we test this before release.
=> Stop storing temporary assets in the tilemap project

docs/writing-docs/tutorials/control-options.md, localtypings/pxtarget.d.ts, pxtblocks/fields/field_kind.ts, pxtlib/main.ts, pxtlib/tutorial.ts, skillmap/src/components/InfoPanel.tsx, theme/asset-editor.less, theme/image-editor/sideBar.less, webapp/src/app.tsx, webapp/src/blocklyFieldView.tsx, webapp/src/components/assetEditor/editor.tsx
Display unlocked rewards out of total reward count in skill map (#7992)
Adjust the asset editor sidebar in asset editor-tutorials (#7999) 
Don't allow reserved words in kinds (#8004)
Only match recognized snippets when parsing tutorial metadata (#7995)
Add customts snippet type for loading hidden ts into tutorials (#7994)
=> Cherrypick skillmap & asset editor fixes

cli/cli.ts, skillmap/.gitignore, skillmap/src/lib/browserUtils.ts
- adds a cli flag for copying local docs into the skillmap directory
- adds a hash parameter for loading from local docs
the updated local testing flow will be something like:
1. make changes in the docs file in the target (eg `pxt-arcade/docs/skillmap/intermediate-skillmap`)
2. run `pxt skillmap --docs skillmap` from pxt-arcade
3. load `http://localhost:3000/?nolocalhost=1#local:skillmap/intermediate-skillmap`
there's no file watching/reload but this should at least allow local testing of files! 
@kiki-lee tagging you for a heads-up, i can sync with you in person on monday or whenever to walk you through the steps
=> Add 'local' flag and update cli for better skillmap testing

pxtpy/converter.ts, tests/pyconverter-test/baselines/string_global_func.ts, tests/pyconverter-test/cases/string_global_func.py
Fixes: https://github.com/microsoft/pxt-microbit/issues/3152
When emitting Name expressions, we shouldn't emit our internal `@type` specifiers.
=> Fix String.fromCharCode py error

theme/image-editor/imageEditor.less
Fixes https://github.com/microsoft/pxt-arcade/issues/3224
Just some weird safari bug
Tested in Safari, Firefox, and Chrome.
=> Fix asset editor size in safari

webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/assetEditor/assetPreview.tsx
Fixing two bugs I found while investigating https://github.com/microsoft/pxt-arcade/issues/3365
1. The "gallery" tab showed up in the tilemap editor when opened from Monaco
2. https://github.com/microsoft/pxt/pull/7998 made it so that temporary assets use their Blockly id as the asset id. That was showing up in the hover text in the "my assets" tab, so removing it and replacing it with "Temporary Asset"
=> Two small image/tilemap editor fixes

docs/csp.md
Include a notice for the upcoming professional development workshops in the CSP page.
This is added as a reminder block at the beginning of the page. It could drop lower and be a section instead if that's preferable.
Closes #8018
=> Workshop notice for CSP page

pxtlib/emitter/cloud.ts
micro:bit port of unapproved translations fix, same as https://github.com/microsoft/pxt/commit/db148da35097f5fd0df1cf234287052f16e89ed1
=> [stable6.0] don't fetch unapproved md translations

skillmap/src/components/makecodeFrame.tsx, skillmap/src/styles/makecode-editor.css
progress bar was a lot more straightforward than i thought it'd be! this is based on the number of events it takes to load a new project (~30); continuing a project requires fewer events but i think it still feels fine to jump from a 2/3 filled bar to the loaded editor
=> Add progress bar to skillmap iframe loader

common-docs/reference/math.md, common-docs/reference/math/trigonometry.md, libs/pxt-common/pxt-core.d.ts
Update the math reference pages for more recent adds to **Math** like `imul`, `idiv`, `tan`, and `axxx`.
Fixes https://github.com/microsoft/pxt-microbit/issues/3097
=> Update math reference pages

theme/tutorial.less, webapp/src/container.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3322
This is the best way I could think of to fix this :\ -> After we render the menu bar, check all the UI elements under the parent and add up the widths. If it's bigger than the screen width, add a class to the menu bar, "shrink", which will hide all elements with the landscape class (like tutorial name, text on the exit button)
One weird thing that's happening that I don't know if it's a result of me not understanding React or this change, is when the MainMenu element rerenders, it keeps the "shrink" class, which makes going from not shrunk -> shrunk a one way street until you refresh the page.
This is a window at (1200x649), which is the dimension of the Pixelbook I have:
And with these changes:
And this shows the one-way street …
=> Don't let the header overlap with each other

pxteditor/monaco-fields/field_sprite.ts, webapp/src/components/ImageFieldEditor.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3384
- don't show the filter button if the filter option isn't there
- add filter to the field editor option for monaco 
The issue is tags weren't being populated in monaco, adding the option fixes it
=> Add filter options to monaco image editor

theme/tutorial.less, webapp/src/components/ImageFieldEditor.tsx, webapp/src/container.tsx
Picks of:
Add filter options to monaco image editor #8042
Don't let the header overlap with each other #8026
which fixes:
microsoft/pxt-arcade#3384
microsoft/pxt-arcade#3322
=> [stable 6.12] Cherry pick gallery filter fix, tutorial header overload fix

.eslintignore, package.json, pxtcompiler/emitter/snippets.ts, pxtsim/runtime.ts, tests/decompile-test/decompilerunner.ts, tests/pyconverter-test/pyconvertrunner.ts, tests/pydecompile-test/pydecompilerunner.ts, webapp/src/blocks.tsx, webapp/src/electron.ts, webapp/src/projects.tsx
Now that we've moved to ESLint (https://github.com/microsoft/pxt/pull/8039), we can now upgrade our Typescript version! Hurray!
Also, this lets us remove the lint exceptions I had to introduce for blocks.tsx and snippetBuilder.tsx because those were crashing eslint due to a typescript bug.
The upgrade went surprisingly smooth... just a few new complaints about void types and removing the "name: void" global by default.
=> Upgrade Typescript from v3.7 to v4.2

webapp/src/greenscreen.tsx
Safari changed it's policy and will not provide label, deviceId on enumerated user media devices until getUserMedia is called, and user consent is given.
Fix for https://github.com/microsoft/pxt-microbit/issues/3633
Tested on Safari MaxOSX, Edge.
=> Green screen safari fix

webapp/src/githubprovider.tsx
github changed their format today so our 'looks kinda like a token' check is failing. New format info: https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/
could trim down the regex a bit more based off the valid token types but I don't see much of a reason to do so, if the user puts in something invalid it will fail a bit further down. (Conversely, could be a bit more general with just `/^[a-z0-9_]+$/i` to allow old tokens, but this is only run through the 'login to github dialog' so they'd have to be using a token created before today / really they *should* create a new token anyway in that case.)
here's a build: https://arcade.makecode.com/app/0f247e4a7a42ba773e2a1810f4acec7bc9c59e1f-20861107f6
=> allow new github token format

cli/server.ts, webapp/src/immersivereader.tsx
Similar to previous one but not using cdn, just going through requestAsync rather than cdnapiurl. Added a redirect in the local serve rather than an explicit check like in auth.ts so `pxt serve` can still fetch tokens.
=> Fix immersive reader in electron (v2)

webapp/src/carousel.tsx, webapp/src/projects.tsx, webapp/src/sui.tsx
- add titles to carousel "See more", "See previous", dialog "Help"
- add title and aria-label to dots on hero banner carousel
- add "button" role to all code cards
fixes https://github.com/microsoft/pxt-microbit/issues/3521
fixes https://github.com/microsoft/pxt-microbit/issues/3548
fixes https://github.com/microsoft/pxt-microbit/issues/3546
=> Add titles and aria-labels across homepage carousels, help icon

pxtcompiler/emitter/snippets.ts
Fixes: https://github.com/microsoft/pxt-arcade/issues/3379
=> Fix crash in getSnippet for PY auto-complete

theme/highcontrast.less, webapp/src/app.tsx
this fix adds our "hc" class when it detects that the operating system's high contrast is on. this seems like the right behavior because it ensures all future fixes to our high contrast will also propagate to windows/os high contrast users
one gotcha is if a user is swapping repeatedly between high-contrast on/off (i'm not sure if this is a real scenario?)--if you turn windows high contrast on, you'll need to refresh makecode to apply our high contrast styles. we also save high contrast preferences, so if you turn off the OS high contrast, makecode will still be high contrast for that session.
\+ one additional fix to invert the logo color if the user is in "light-mode" high contrast
fixes https://github.com/microsoft/pxt-microbit/issues/3551
fixes …
=> Apply high contrast styles when OS high contrast is enabled

pxtsim/simdriver.ts
We compute the set of builtin parts used by the program but loose the information between the compiled code and the simulator driver.
This explains why we never hit the static parts detection in microbit.
=> loosing builtinparts info in driver

webapp/src/app.tsx
Updated wording to mention "add or update" in the dialog "add extensions" dialog. (note that this only applies to non-approved extensions)
Fix for https://github.com/microsoft/jacdac/issues/280
=> updated "add extensions" dialog wording

theme/highcontrast.less, webapp/src/githubprovider.tsx, webapp/src/lang.tsx
- overrides OS hc colors for toggle (fixes https://github.com/microsoft/pxt-microbit/issues/3685)
- sets an href on the "Developer token" link (fixes https://github.com/microsoft/pxt-microbit/issues/3584)
- fix role for cards in language modal (addresses https://github.com/microsoft/pxt-microbit/issues/3666)
=> Fix toggle for OS high contrast, update Github modal link

skillmap/src/lib/codeCarryover.ts
bug: picking "Keep Code" from space explorer activity3 -> activity4 was loading without the Status Bars extension, because we were overwriting the config of the new project and erasing the dependencies.
we never want to take the pxt.json of the old project when doing code carryover, we only want to push the tilemap/image.g.jres files into the new config if the filenames are not there (eg activity A1 has images, activity A2 does not, so when carrying over assets from A1 -> A2 we need to add `images.g.jres` to the list of files in pxt.json)
=> Always use new project pxt.json for skillmap carryover

pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/simulator.ts
Pass down the list of dependencies to the simulators to allow them to compute which extension is missing in the project.
=> communicate dependencies to simulator

theme/common.less, theme/home.less, theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/globals/site.variables, theme/themes/pxt/modules/checkbox.overrides, theme/themes/pxt/modules/checkbox.variables
fixes https://github.com/microsoft/pxt-microbit/issues/3653 (increase opacity in blocks/js toggle)
fixes https://github.com/microsoft/pxt-microbit/issues/3650 (darken bg for selected file, add light border)
fixes https://github.com/microsoft/pxt-microbit/issues/3684 (add border to toggle and toggle handle)
fixes https://github.com/microsoft/pxt-microbit/issues/3547
=> Color contrast fixes for toggles, file explorer, card focus

pxtcompiler/emitter/languageservice.ts, pxtcompiler/emitter/snippets.ts, tests/language-service/languageservicerunner.ts, tests/language-service/snippet_cases/functions.py, tests/language-service/snippet_cases/functions.ts, tests/language-service/test-package/basic.ts
Fixes: https://github.com/microsoft/pxt-microbit/issues/3281
We weren't doing any sort of TS->PY translation for specified defaults on blocks.
=> Handle snippets with default values translating to py

webapp/src/app.tsx
On load, always make sure the header name matches what is in pxt.json (or "untitled")
=> always update header name on script load

webapp/src/editortoolbar.tsx, webapp/src/workspace.ts
Don't try to do too much magic and simply display the project name from pxt.json.
This solves rendering issues with mon-repo github projects.
=> Always use the pxt.json name in cards, even for github projects

libs/pxt-python/pxt-python-helpers.ts, libs/pxt-python/pxt-python.d.ts, tests/pyconverter-test/baselines/string_replace.ts, tests/pyconverter-test/cases/string_replace.py
The JS and PY String.replace behaviors are similar enough we can do a straight translation. Python technically has an option for a third param, but this is rare and if it comes up we can use a py override.
Fixes: https://github.com/microsoft/pxt-microbit/issues/3831
=> Fix py string.replace

pxtlib/package.ts
Just making sure to not double encode the stored SVG when loading an image from pxtpart.json. Fix for https://github.com/microsoft/pxt-microbit/issues/3968
=> don't double encode pxtparts.json images

theme/sidedoc.less
- sets sidedoc height instead of padding-bottom, so the editor toolbar buttons are still clickable
- additional height for thin editor toolbar with desktop simulator (sidedocs can be taller here)
fixes https://github.com/microsoft/pxt-microbit/issues/3707
fixes https://github.com/microsoft/pxt-microbit/issues/3014
=> Set sidedocs height instead of padding, add thin editor style

libs/pxt-python/pxt-python.d.ts, pxtpy/converter.ts, pxtpy/parser.ts, pxtpy/pydecompiler.ts, tests/pyconverter-test/baselines/sort.ts, tests/pyconverter-test/cases/sort.py
Fixes: https://github.com/microsoft/pxt-microbit/issues/3374
We supported lambdas in ts2py but not py2ts so I created a clearer error message and disabled them in ts2py for now.
Also, I allow the optional sort function in ts<->py even though py doesn't technically support that.
=> Support sort() and sort() w/ lambda in py

pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/ONLY_class_pub_members.ts, tests/runtime-trace-tests/cases/callback_names.ts, tests/runtime-trace-tests/cases/class_pub_members.ts
Fixes: https://github.com/microsoft/pxt-microbit/issues/3188
Widens support for classes in Python by allowing member declarations in the parameter list like `class Foo(public myMem: number)`
=> Support public parameters-members in ts2py class constructors

webapp/src/editortoolbar.tsx
Fixes: https://github.com/microsoft/pxt-microbit/issues/3959
Fixes: https://github.com/microsoft/pxt-arcade/issues/3413
This was a regression introduced by the cloud work. It's not cloud related, just that I changed the toolboxeditor from fetching the header from the props to instead fetch from the virtual APIs but there's a case (during delete) where the header from the virtual API is null.
=> Fix crash on project delete

pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/driver.ts, pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/reserved_words_decl.ts
Fixes: https://github.com/microsoft/pxt-microbit/issues/3145
- buildRenameMap considers ALL declarations (functions, classes, etc) instead of just variable declarations
- Add PY keywords to the reserved words list (should always have been there.)
=> Properly exclude python keywords & reserved words from ALL declarations

pxtpy/pydecompiler.ts, tests/runtime-trace-tests/cases/to_string.ts
Fixes: https://github.com/microsoft/pxt-microbit/issues/3977
Due to .toString's special presence on all objects, we add special handling directly in ts2py's call expression emitter.
=> Fix handling of .toString() <-> str()

pxtblocks/composablemutations.ts
This fixes the issue, but it seems like there's something really weird going on deep down in the gesture logic here or something of the sort. I looked around for a bit and didn't see anything obvious, and then Shannon gave it a quick look too, so for now leaving it at 'well it works now' and having it in the back of our head that something is broken... somewhere, and it's not necessarily worth the time to find right now.
Fix https://github.com/microsoft/pxt-arcade/issues/3421 (also affects the `player {1|2|3|4} dx` block)
This started happening with https://github.com/microsoft/pxt/pull/7845, but there's no obvious reason for why that broke it -- something to do with removing and re-adding the plus icon to these specific blocks makes it deeply upset / breaks the gestures on the block. I …
=> Fix dx / dy blocks

pxtblocks/composablemutations.ts
Cherry pick https://github.com/microsoft/pxt/pull/8094 to stable to fix the 'dx' / 'dy' blocks.
=> [stable6.12] Fix dx / dy blocks

theme/common.less
This just happened recently (in microbit/beta) so it looks like it was one of the rules we added for tab visibility on other buttons. Remove the outline from the active toggle in non-high contrast:
=> don't outline blocks/js toggle due to active style

skillmap/src/lib/skillGraphUtils.ts
checks if nodes are adjacent siblings (can be directly connected by a vertical line) and does not shift the node in that case. this makes the handling of connections within one depth layer a little better (used in Kiki's collector map)
=> Add skip the shift of nodes we've already seen if they are adjacent

theme/highcontrast.less, theme/serial.less, webapp/src/app.tsx, webapp/src/serial.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3587
technically the chart disappearing is the correct behavior--we are restarting the simulator, which changes the sim id, which means the serial output will render a new chart anyway. there's currently a behavior (on latest master) where if you turn high contrast on and off while the simulator/serial recording is running, it will just continuously append charts.
this fixes that bug, and also adds a placeholder div that looks like a chart, so that the space doesn't look so empty.
build link with test project: https://makecode.microbit.org/app/79daa6bbe818bc8fa3c2f8c3a43551026f6d811e-fb5e027396#pub:68673-35636-09676-33850
=> Add placeholder 'chart' to serial view when no charts are present

docfiles/apptracking.html, docfiles/tracking.html
I moved the check to /doccdn/ & /blb/ which for sure gets replaced by backend.
Works in the https://arcade.makecode.com/app/20f5f48d56153ea3ba8ae89a66761254161d37ed-22a00706f2
=> Moving to cdn & doccdn checks

pxtrunner/runner.ts, skillmap/src/App.tsx, webapp/src/app.tsx
When I gave https://github.com/microsoft/pxt/pull/8097 a quick check locally, my local markdown updates weren't going through and I noticed it was fetching everything from the server.
Turns out this weird behavior https://github.com/microsoft/pxt/pull/7989/files#r598994321 of updating as a side effect was the thing preventing it from serving docs from the server instead of the local versions when doing a `pxt serve`, as setting that to true makes us skip the local request path here:
https://github.com/microsoft/pxt/blob/108e3785e2ae20fdeb5b59e4f0956fd83092b4e1/pxtlib/emitter/cloud.ts#L184-L195
Fix that so we don't go to makecode.com/api/* for markdown on pxt serve. (the changes are just guarding with `pxt.BrowserUtils.isLocalHostDev()` in a few places where we don't want to default to …
=> serve local file in pxt serve again

package.json, webapp/src/immersivereader.tsx
Add an immersiveReader.error tick for when the immersive reader returns an error -- right now we can't see when the users are getting the "Immersive Reader is already launching" issue.
Also @jwunderl I think you pointed this out in the initial PR and I forgot, but I removed the double package dependency -- it was required for prod and dev before, and this removes it for dev.
=> Surface more Immersive Reader errors

theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/globals/site.variables, webapp/src/container.tsx, webapp/src/sui.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3510
by adding a white border and fading (which is different from any other header that isn't the home page -- I can add this to others too if we'd like.) I added a border bc there was a default border getting added to everybody except settings :( but if you guys think just the fade would be better I can do that toooo
this was the default border: 
fixes https://github.com/microsoft/pxt-microbit/issues/3651
=> Two more accessibility fixes

pxteditor/editor.ts, webapp/src/app.tsx
Potential fix for https://github.com/microsoft/pxt-microbit/issues/3280
This makes it so that we automatically pause on the first breakpoint when running a program in the debugger. It does *not* pause if you have slow-mo turned on, but I can change that if desired. Also, should it pause if you hit restart?
=> Break on first breakpoint in debugger

pxtblocks/blocklylayout.ts, theme/print.less
workspace comments don't have a `data-id` attribute, so we weren't picking them up. this adds them back in and has some light CSS for styling as well. 
this is a partial fix for https://github.com/microsoft/pxt-microbit/issues/3258, it doesn't include block comments yet because our "Format Code" doesn't factor in block comments, so they would overlap the other blocks in the print dialog. i THINK it shouldn't be terrible to add them in but i'm gonna switch gears and look at some other bugs first
=> Bring workspace comments back to print dialog

pxtsim/embed.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3194
Debugging is pretty terrible right now for radio programs because both simulators send/receive all messages from the debugger.
This pr does a few things to improve it:
1. Disables breakpoints in the second simulator
2. Disables trace messages coming from the second simulator
3. When the primary simulator pauses, the second simulator will also pause
=> Improve debugging of radio programs

docs/csp.md
Connect the link for MakeCode AP CSP curriculum guide.
This currently points to the `gh-pages` site for the [temporary](https://github.com/ganicke/makecode-apcsp) repo. This will change to https://microsoft.github.io/makecode-csp when migrated to that site's repo.
RE: https://github.com/microsoft/makecode-csp/pull/8#issuecomment-831504297
=> Link for MakeCode AP CSP curriculum guide

cli/cli.ts, localtypings/pxtarget.d.ts, pxtcompiler/emitter/driver.ts, pxtcompiler/emitter/service.ts, pxtlib/browserutils.ts, pxtlib/tutorial.ts, webapp/src/app.tsx, webapp/src/compiler.ts, webapp/src/gitjson.tsx, webapp/src/tutorial.tsx
- adds a new op to the service to decompile an array of ts snippets (strings) & return an array of xml snippets
- where previously we were caching "usedBlocks" (map of blockId to the number 1) we now also cache "snippetBlocks" (map of code snippet hash, to <map of blockIds to the number 1>). usedBlocks is kept as-is to prevent weirdness with existing caches (in git repos, indexeddb, etc)
- also checked with python
perf-wise, it did make things slightly slower (increased a ~2s load time by about ~0.1s on average, on my machine), but that should only be for the initial load, before the blocks are cached
build: https://arcade.makecode.com/app/779fd95829c1d84fb875251dbb9e2f8dc047d2ca-ea561d6c56
=> Decompile tutorial snippets separately, hash usedBlocks to individual code snippet

webapp/src/app.tsx
Fix https://github.com/microsoft/pxt-microbit/issues/3126. We were trying to restart here already but it was getting ignored in multiple places -- the restart always hits the 'fast restart' path which doesn't update the iframe options, and even with that fixed the start would ignore it as the simulator was already running.
We also don't want to use restart here because it steals focus to the simulator, which messes with tab accessibility a bit.
=> actually restart simulator when hc setting changes

theme/image-editor/imageEditor.less, webapp/src/components/assetEditor/assetCard.tsx
accidentally hid all the icons while attempting to hide the warning icon! this adds them back
=> Add back asset type icon, keep temporary asset warning hidden

theme/tutorial.less, webapp/src/container.tsx, webapp/src/marked.tsx, webapp/src/sui.tsx, webapp/src/tutorial.tsx
Variety of small nitpicky things as well
* fix https://github.com/microsoft/pxt-microbit/issues/3982 -- move tab stop from text content to hint btn 
* tutorial name -- make it not styled like a button -- remove pointer cursor, no background darken on click
* unfiled acc bug - move tabstop for the tutorial step content from the outer div to the one directly containing the p tags, so keyboard navigation can scroll when necessary / a scrollbar exists.
* remove pointer cursor from the step content
Got a build since I was testing mobile anyways https://makecode.microbit.org/app/384c3bdf51b88f2471fe118cab7e127600e7b85f-98538ccfad (pxt / microbit might be a few commits back though)
=> Tutorial accessibility fixes + no opening hint on content click

webapp/src/app.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/3998
adds a tick event for exiting the tutorial via this button also (`tutorial.exit` is exiting via the "Exit Tutorial" button)
=> Save project when exiting tutorial via target logo

common-docs/robots.txt
should address https://github.com/microsoft/pxt-microbit/issues/3829 by bumping the v2 site down in search results. we may want to consider disabling crawling for /v* paths altogether?
=> Update robots.txt to disable crawling for /v2

theme/home.less
fix https://github.com/microsoft/pxt-microbit/issues/3268:
js / blocks / python projects all have text overlaid on top of the icon, so leave those with the current opacity so that the text is still easily readable. 
https://github.com/microsoft/pxt/blob/9a2fc6ec1171e240e3d58450592a8232ffa3b08f/webapp/src/projects.tsx#L968-L979
=> homescreen detail view button icon contrast

docs/csp.md
Reverting the AP CSP document site address back to https://microsoft.github.io/makecode-csp.
=> Set the AP CSP docs address back to original site

cli/cli.ts
When files are referenced in `pxt.json` as `subfolder/somefile.ts` and are imported via `additionalFilePath`, it would break.
=> Fix files in subfolders with additionalFilePath

webapp/src/auth.ts, webapp/src/immersivereader.tsx, webapp/src/screenshot.ts
fixes https://github.com/microsoft/pxt-microbit/issues/4005
Use the nice auth APIs to store the reader preferences, which will use local storage (not idb) if not logged in, and will sync w/ cloud if you are :D it works!
Also snuck in the user language preferences, so the UI in Immersive Reader is the one you selected in Arcade! wow
oh also i found some logs i left before so i took those out sorry
=> Persist Immersive Reader preferences

localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, webapp/src/app.tsx
In a markdown file, this flag can be added:
`### @tutorialCodeValidation true/false`
If this flag is set to true, then the tutorial will go through the process of tutorial code validation. Otherwise features for tutorial code validation will not be included when a user is going through a tutorial.
=> Added Markdown Flag for Code Validation

skillmap/src/components/GraphNode.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/store/reducer.ts
will probably conflict with https://github.com/microsoft/pxt/pull/8160, i'll merge them in/handle issues
- add a color for completed nodes (by default, same as unlocked node), expose some theme override fields (internal use only) https://github.com/microsoft/pxt/commit/72bce1a4205b5faff423ad7763d2ed04c9bc78bf
- open an activity on double-click https://github.com/microsoft/pxt/commit/c7e86521705b7ac7b919d0ee32ae4c94c67b7e5f
=> Add color for completed skill map nodes, open activity on double-click

docs/js/profiling.md, localtypings/pxtarget.d.ts, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/backjs.ts, pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxtcompiler/emitter/ir.ts, pxtlib/service.ts
This generates `built/sizes.csv` that can be visualized like so (with Excel):
=> Add ?compiler=size switch

.vscode/launch.json, cli/cli.ts, pxtlib/package.ts
With multivariant, it is quite tricky to figure out when and why shims are generated. Only the 1st variant generates shims which does not current work when building a library with variant exclusions.
=> adding dedicated buildshims command

skillmap/src/components/SkillGraph.tsx, skillmap/src/components/SkillGraphContainer.tsx, skillmap/src/lib/skillGraphUtils.ts, skillmap/src/styles/skillgraph.css
some changes to support a fixed graph position relative to the background image. this does make the overall page less responsive, but was requested specifically for the beginner skillmap launch
- moves all graph layout computation code into `SkillGraphContainer.tsx`; previously each "path" was it's own SVG, now they are all positioned on the same parent SVG
- when the background image (if there is one) loads, we get the dimenions and scale the graph SVG to exactly match, that way it's always centered
- some CSS changes/cleanup to support this
=> Fix skill graph position relative to background image

pxtlib/service.ts
fix https://github.com/microsoft/pxt-microbit/issues/3985
Here's a build with a test block in it - it should say 'this failed' in any language except simplifed chinese, where it should say 'this succeeded': https://makecode.microbit.org/app/3b23aba2d03c06d2865dddd8098d647af20731b3-d8a2867831#pub:_icDCV21Wrhtk
in custom.ts:
```typescript
namespace test {
//% block="this failed"
//% block.loc.zh-CN="this succeeded"
export function testMyStuff() { }
}
```
=> fix block.loc.ab-CD where lang is fully enumerated (e.g. .zh-CN)

webapp/src/workspace.ts
MakeCode keeps an in-memory cache of all project headers, and some parts of the app assume these to be long-lived, i.e. they won't be replaced by a newer version but instead updated in place.
This is problematic for cloud save on a number of levels, and something that I think I'll need to address in a later PR.
In the short term, this change modifies the cached header update process to delete header fields in the cached version of the object that don't exist on the incoming version.
When a user deletes their cloud profile, we export their cloud-saved projects to local. Functionally, this happens by deleting the cloud information from the project header and re-saving it. During the above-mentioned cached header update, deleted fields on the incoming version were not being removed from the …
=> Delete old fields from project header on save

webapp/src/container.tsx, webapp/src/identity.tsx, webapp/src/projects.tsx, webapp/src/user.tsx
* Moved "Unlink GitHub" to the profile menu, and only show it if not signed into identity. When signed in, users can unlink GitHub from the "My Profile" screen.
* Clarified feedback text and updated link to point to a form survey (via aka.ms).
* Removed experimental feature warning from sign in dialog.
=> UI updates for identity

localtypings/pxtarget.d.ts, pxteditor/editor.ts, pxtlib/tutorial.ts, pxtlib/tutorialValidator.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/tutorial.tsx
Tutorial Code validation now extracts rules from a markdown file in the format:
```tutorialValidationRules
{"rule1":true, "rule2":false}
```
"rule1" corresponds to the name of the rule, and the boolean after the colon indicates if the rule is turned on/off. Associated with each rule is a boolean status flag that indicates if the user passes this rule and a rule message.
=> Tutorial Validation Extracts Rules from Markdown

theme/home.less, webapp/src/projects.tsx
* don't filter out cards without urls (make youtube videos / playlists in gallery work too)
* add 'start here' msg to translations
* allow overriding button label in gallery
* few minor prettifying updates
* speed up a bit (6seconds instead of 7.5 seconds
* keyboard nav (left / right keys while focus is on dots / start button)
* swipe support (mainly for mobile but works everywhere)
build: https://makecode.microbit.org/app/aacb838af702b5ff97c4dc393ede6781b547ea86-abf686df1b
will want these in for testing monday~
=> various hero gallery updates

webapp/src/cloud.ts
Syncing projects to/from the cloud is a complex process involving many async tasks running at once. Any one of these tasks could fail for reasons that aren't necessarily fatal to the overall sync process, so don't let an individual task failure cancel the entire sync. Instead, log the error and let the other tasks continue.
This is part of an effort to uncover why cloud sync mysteriously stops working. This particular code (cloud.syncAsyncInternal) needs more work and refactoring. It is terribly nuanced at the moment.
=> Add resilience to cloud sync tasks

webapp/src/cloud.ts
After synchronizing with the cloud, invalidate local project headers in case anything changed. This fixes the issue where a user's cloud projects don't show up after signing in. This solution is kind of blunt-force, but should be ok for now.
Fixes https://github.com/microsoft/pxt-arcade/issues/3476
Fixes https://github.com/microsoft/pxt-arcade/issues/2865
=> Invalidate project headers after cloud sync

theme/home.less
Set aside 3 lines worth of height for the hero banner description, so the buttons don't bounce up / down depending on how long each description is. (just in case if it's longer than 3 lines it scrolls, but we should aim for short/sweet descriptions for the banner anyways).
https://makecode.microbit.org/app/a62737398fa226bd5fa625a7e8e31da3a9739a21-0af9ff82f8
=> set a static height of 3 lines for hero banner description

cli/cli.ts, webapp/src/projects.tsx
Since the 'main' hero banner has to live in pxtarget to make sure it is readily available, it doesn't get the same auto localization we do from the gallery versions. Extract those strings in the same way we pull out name / title / etc
=> extract hero banner strings for localization

pxtblocks/blocklylayout.ts
we were exceeding the maximum canvas size when converting the SVG to a PNG. this scales the SVG down a bit before converting it to a dataURI. it looks like the maximum allowed size differs a bit by browser, so i just picked what felt like a reasonable number based on the stats i could find
test program: https://makecode.microbit.org/_0dyLcTXwJ19w
build: https://makecode.microbit.org/app/70144155d43c90e44e0154f6cbc6dd5de68761b5-d80046889c
fixes https://github.com/microsoft/pxt-microbit/issues/3302
=> Scale blocks SVG down when size is too large for screenshot

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/dialogs.tsx, webapp/src/editortoolbar.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4085
Fixes https://github.com/microsoft/pxt-microbit/issues/4087
Fixes https://github.com/microsoft/pxt-microbit/issues/4097
Complete list of changes:
1. "Download .hex file" -> "Download as file"
2. No longer shows the callout for pairing in browsers where it isn't supported (Firefox, Safari)
3. "Don't show this again" flag is now stored in memory
4. Fixes some ticks for the ... menu
5. ... menu now also shows on ios
6. Reset clears the "Don't show this again" flag
7. Selecting "save as file" now always shows the download dialog (even if selected "Don't show this again"). I can change this behavior if desired.
=> Webusb tweaks

pxtcompiler/emitter/languageservice.ts, pxtcompiler/emitter/service.ts, pxtcompiler/emitter/snippets.ts, pxtlib/service.ts, pxtlib/util.ts, pxtpy/pydecompiler.ts, webapp/src/monacoFlyout.tsx, webapp/src/monacoSnippets.ts
fixes https://github.com/microsoft/pxt-microbit/issues/4007
Similar to https://github.com/microsoft/pxt/pull/8076 except there wasn't a translation path for enums. Added a case to manually update enums, and also added the same function to webapp so the snippets will display correctly in the toolbox (for example, true **should** be capitalized here 
I couldn't find a good way to share code between pxtcompiler/webapp so I copied it, but if there's a better way please let me know 😭
=> Translate Python snippets

pxtblocks/fields/field_melodySandbox.ts
fixes https://github.com/microsoft/pxt-microbit/issues/4089
This uses the default color that the note picker uses when it has no parent
=> Use default color for orphan melody blocks

pxtlib/audioUtil.ts, pxtsim/simlib.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3703
The newest version of Safari doesn't respect changing the pitch directly, so I switched to using `linearRampToValue`. I also took this opportunity to make the field editors much, much quieter. They now are closer to the volume in the simulator.
I also fixed the clipping that happens in the simulator when playing notes/melodies. Clipping happens whenever there is a sudden shift in gain values with an oscillator attached. I fixed it by making it so that we never set the gain value directly once an oscillator is playing. Instead I use `setTargetAtTime` which interpolates to the value based on the time constant you pass in. Other interesting notes:
1. GainNodes start fully open, which means connecting an oscillator is the same as …
=> Fix pitch in safari and clipping in simulator

pxtlib/browserutils.ts
fix https://github.com/microsoft/pxt-microbit/issues/3894 (based off the provided user agent, but I don't have an ipod touch to check with / doesn't harm anything at least).
here's a test change for tests sake: https://regex101.com/r/f6Hwsu/1
=> fix useragent version check for ipod touch webview

theme/themes/pxt/modules/dropdown.overrides, webapp/src/scriptmanager.tsx, webapp/src/sui.tsx
fix https://github.com/microsoft/pxt-microbit/issues/4084
Also fix it going offscreen / repositioning when name is selected by aligning to right, as that was annoying me a lot while I was trying to debug this:
vs after this 
(also worth a note this component is very tedious to debug, as it's got fairly complex state management / actually changes in response to any clicks the user makes, even outside the window -- e.g. even in the debug tools. Something for the backlog I guess)
=> Fix dropdown menu flicker, going off screen

localtypings/pxtpackage.d.ts, webapp/src/scriptsearch.tsx
Add a flag to make it so a builtin package only shows up when the user searches for it for https://github.com/microsoft/pxt-microbit/issues/3933
=> add pkg flag to make builtin package show up only on search

webapp/src/app.tsx
When the user clicks a project to open it, we try to pull the latest version from the cloud before loading it into the editor. This process involves a variable number of asynchronous steps. The prior implementation chained these steps together as a set of `then` clauses appended to a resolved promise. It isn't entirely clear why, but this wasn't working correctly; the chained `then` clauses weren't executing in the expected order. This resulted in the project being loaded into the editor before the cloud sync completed. Note: This is a common pattern in the codebase, which is worrisome. I wonder if we were previously relying on a Bluebird-specific behavior.
I also increased the cloud sync timeout from 1.5 to 15 secs. I'd rather be generous here, and looking at the telemetry from different …
=> Fix on-demand sync from cloud

webapp/src/app.tsx, webapp/src/cloud.ts
This is a targeted fix on top of a previous tactical change. Some background: As part of integrating cloud sync into the existing workspace code, we made the tactical decision to add a quick cloud sync whenever a project is being loaded into the editor. This is to ensure that the latest version is being loaded. This cloud check has a timeout that I recently increased from 1.5s to 15s. Cut over to the cloud sync code: The process of saving a project to the cloud includes an etag check on the backend, and if that check fails that indicates a conflict. We handle the conflict by duplicating the project and loading the new one into the editor. After I increased the aforementioned timeout to 15 secs, it became obvious that conflict resolution codepath was somehow entangled with the cloud check …
=> Don't sync cloud when resolving conflict

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, pxtlib/tutorialValidator.ts, webapp/src/tutorial.tsx
Under each tutorial step, the tutorial maker will have the ability to inform the user that a block or blocks are required for a tutorial step. To enable required blocks in markdown, the tutorial maker must use...
```
```requiredTutorialBlock
[Insert block here]
```'
```
A custom pop-up message will appear informing the user what blocks they are required to use. In the screenshot below, this rule is combined with other rules.
This rule can be used as a standalone too, but if a step does not have required block specified, the 'next' button will turn green.
=> Added Strict Rule: Required Blocks

webapp/src/scriptsearch.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/4135
we pass `hide` as the onClick callback for the modal, so the first argument is actually the click event.
=> Fix issue of loading JS editor when exiting extensions

pxtpy/converter.ts, tests/pyconverter-test/baselines/empty_array_declaration.ts, tests/pyconverter-test/cases/empty_array_declaration.py
Fixes https://github.com/microsoft/pxt-microbit/issues/3849
Currently, we emit our internal type id with a question mark when we encounter a type we couldn't infer in the Python compiler. It ends up giving us something that looks like `let x: ?359;`. There's no real reason I can see to ever emit those internal type IDs when `any` should work most of the time.
We did use it in one place in the code to detect when we had an invalid type, but I think that information should probably be propagated in a more intentional manner if it's important.
=> Don't emit nonsense internal types when converting from Python

pxtlib/tutorial.ts, pxtlib/tutorialValidator.ts, webapp/src/tutorial.tsx, webapp/src/tutorialCodeValidation.tsx
Telemetry cases:
Once the tutorial loads, all validation rules are add to the telemetry. 
All user cases require the validation pop-up to be visible
- User clicks the next button
- User clicks 'Continue Anyways' 
- User clicks 'Keep Editing' 
Below is a sample console.log of telemetry with two rules enabled
=> Initial Telemetry for Tutorial Validation

localtypings/pxtarget.d.ts, pxteditor/editor.ts, pxtlib/cmds.ts, pxtlib/packetio.ts, webapp/src/app.tsx, webapp/src/cmds.ts
This adds a warning when users use code incompatible with connected hardware. I determine what hardware is used via the parts annotations (e.g. `//% parts="builtinspeaker"`). The packetio implementation in the target can optionally define a function called `unsupportedParts` that returns a list of unsupported part annotation ids.
If anything unsupported is used, you get a warning when you download. Clicking "download anyway" will predictable ignore the issues. I'll have a PR in pxt-microbit soon that does the target side of this. Also, I expect the design/text will likely get tweaked down the road.
p.s. this PR looks scarier than it is because I refactored the compile method to use async await (it had three nested promise chains). [ignore …
=> Add warning when users use code incompatible with connected hardware

localtypings/pxtarget.d.ts, pxtlib/tutorialValidator.ts, webapp/src/tutorialCodeValidation.tsx
i think the better way to do this would be with react hooks, but sticking with the old lifecycle for now, for simplicity's sake
=> Get typescript snippet from block id for rendering missing blocks in tutorial validation

webapp/src/projects.tsx
When the hero banner rotates around for the first time, it is currently fetching the images on demand  / when the card is first shown. This isn't so noticeable right now because the current gallery images are very small & there's already a weird transition between them as the sizes are different, but it's particularly noticeable with the new images in https://github.com/microsoft/pxt-microbit/pull/4149 -- the first time you go through the carousel, you'll get a momentary white flash while the image fills in.
This fixes that by prefetching the images to get them into the browser mem cache as soon as the gallery md is available. (there's a 6 second pause between that point & when it will rotate to the next screen for the first time, so unless network is a huge bottleneck there shouldn't be …
=> prefetch herobanner images on gallery load

pxtpy/converter.ts, tests/pyconverter-test/baselines/array_generics2.ts, tests/pyconverter-test/baselines/array_generics3.ts, tests/pyconverter-test/baselines/array_generics4.ts, tests/pyconverter-test/baselines/array_generics5.ts, tests/pyconverter-test/baselines/array_generics_map.ts, tests/pyconverter-test/baselines/array_generics_reduce.ts, tests/pyconverter-test/cases/array_generics2.py, tests/pyconverter-test/cases/array_generics3.py, tests/pyconverter-test/cases/array_generics4.py, tests/pyconverter-test/cases/array_generics5.py, tests/pyconverter-test/cases/array_generics_map.py, tests/pyconverter-test/cases/array_generics_reduce.py
We still don't support generics except for arrays
Fixes https://github.com/microsoft/pxt-microbit/issues/3579
=> Handle generics from array methods in pyconverter

pxtsim/runtime.ts, pxtsim/simdriver.ts
This fixes local serve in arcade when using the production simulator. It was a regression accidentally caused by #7720
If the simulator is missing, our CLI [redirects requests to the production simulator](https://github.com/microsoft/pxt/blob/master/cli/server.ts#L1136) which ends up changing the domain of the iframe. Because the origin changes with the redirect, the messages we send with `postMessage` never reach the content window.
This fixes that by sending to both domains when on localhost. Should be harmless since one of the messages will just always be ignored. I don't love how I got access to the target id (apptarget isn't usually visible in pxsim), but piping everything from the webapp for local serve seemed messy.
This really only effects arcade
=> Fix local host serve when pointing to production sim

pxtlib/tutorialValidator.ts, theme/tutorialCodeValidation.less, webapp/src/tutorial.tsx, webapp/src/tutorialCodeValidation.tsx
Few things in this PR
- Renamed variables
- Validation Blocks are rendered into the message
- Validation Messages disappears when anywhere in the workspace is clicked
=> Renamed Tutorial Validation Variables, Toggle Validation Message, and Render Blocks in Validation Message

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/dialogs.tsx, webapp/src/editortoolbar.tsx, webapp/src/webusb.tsx
Few changes:
1. Adds a link to the incompatible hardware dialog
2. Fixes the issue where the download button still said "Downloaded!" even if you cancelled it
3. Added `rel="noopener noreferrer"` to the webusub dialog
=> Add extra help link and don't say downloaded when cancelled

localtypings/monacoTypeScript.d.ts, webapp/src/tsworker.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4122
Unfortunately, I had to create a second language service because the monaco-typescript worker [keeps theirs private](https://github.com/microsoft/monaco-typescript/blob/main/src/tsWorker.ts#L40).
This duplicates a small amount of code from compiler/emitter, but nothing super important/likely to ever change so It should be fine.
=> Sort completion entries based on weight when possible

docfiles/script-page.css, docfiles/script.html
leaving the arcade share page alone for now, since long-term we plan to revisit the share page (and the tutorial) header
=> Align share page branding with editor and home screen

pxtsim/simdriver.ts
Also listen to the simulator state when it says it's running.
Fixes https://github.com/microsoft/pxt-microbit/issues/4038
=> Cleanup frames immediately after restart

localtypings/pxtarget.d.ts, theme/highcontrast.less, webapp/src/app.tsx, webapp/src/dialogs.tsx, webapp/src/monaco.tsx, webapp/src/notification.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/4165
fixes https://github.com/microsoft/pxt-microbit/issues/4176
I don't think there's a good way to open up the website in a browser instead of another app window, so just don't link to it. The text is copy-able, and we can include a link to the website in docs.
Looks like:
=> Windows App deprecation UI fixes

webapp/src/workspace.ts
Do not switch to memory workspace in windows app, get back the old behavior to close https://github.com/microsoft/pxt-microbit/issues/4095
=> ignore memory ws error in windows app

package.json, pxtblocks/blocklyloader.ts
Pick up https://github.com/microsoft/pxt-blockly/pull/351
* fixes https://github.com/microsoft/pxt-microbit/issues/4177 (one line addition added as second commit to make it swap to vertical after 2)
* fix https://github.com/microsoft/pxt-microbit/issues/4161
* fix https://github.com/microsoft/pxt-arcade/issues/1779
=> bump blockly for datalogger array fixes

pxtsim/simlib.ts
Part of a fix for this issue: https://github.com/microsoft/pxt-microbit/issues/4212
Sometimes Safari delays sounds before the user interacts with the page instead of just cancelling them. That means when the user does finally do something to unmute, whatever sound they tried to play five minutes ago will play. Adding a cancellation token like function to be used in pxt-microbit to prevent that from happening.
=> Add cancellation function to playPCMBufferAsync

pxtlib/emitter/cloud.ts, webapp/public/docs.html, webapp/src/container.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4216
There were a couple things going on here:
First, `isPxtElectron()` failed in the sidedocs iframe because it isn't affected by the preload script in pxt-electron. I added a query parameter to the sidedocs URL to set the `window.pxtElectron` global when we first load.
Second, we were always storing the results of the markdown request in the indexedDB, including when the server returned a status code 304 (nothing has changed). The 304 response doesn't include the markdown contents, so we were saving over whatever was in the indexedDB with the empty string when really we shouldn't have done anything.
=> Fix sidedocs in electron app

theme/themes/pxt/globals/zindex.variables, theme/themes/pxt/modules/dropdown.overrides, webapp/src/sui.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/4200
some items in our dropdown menus are links, and `preventDefault` breaks the link behavior. the dropdown flickering in the project view page appears to be coming from the CSS filter (https://github.com/microsoft/pxt/blob/master/theme/common.less#L600) and explicitly setting the z-index should fix it
build: https://makecode.microbit.org/app/add6f95af87d3c2d45477f356764cfa5fef457e6-d68371ac11
=> CSS fix for dropdown flickering

webapp/src/cmds.ts, webapp/src/headerbar.tsx, webapp/src/sui.tsx
tested this on my surface with touchscreen/mouse click, but have not tested on an iOS device. apparently iOS default long press duration is 500ms but that felt really fast to me
=> Send long press event on header bar back button press (for iOS app)

webapp/src/immersivereader.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/4213
-> in the scenario where you don't already have the token and you're offline:
- this change properly handles the error and shows the offline message
-> in the scenario where you do have the token and you're offline
- I added a ping to check the connection before starting the launch to the immersive reader. the "Launch Immersive Reader" call doesn't fail quickly enough if there's no internet, so this shows the offline error instead of white-screening it for 15 seconds first
=> Show offline message for Immersive Reader

pxtlib/cpp.ts
Fixes the main problem with https://github.com/microsoft/pxt-microbit/issues/4207
I will file an issue for fixing the hexcache so this also works better online
=> Always hit the live endpoint for compile requests

docfiles/apptracking.html, docfiles/tracking.html
trying to change this file as little as possible, since it's used everywhere... appinsights by default sets the page title as the EntityName for a page view event. however, in share pages this title is dynamic; this replaces the user's project name with a more generic "Share Page" string
=> Replace dynamic name (page title) in pageview data with 'Share Page'

pxtlib/emitter/cloud.ts
we're requesting markdown content from `makecode.microbit.org` and our markdown is hosted on `makecode.com` so i believe we're hitting CORS issues where the etag is not accessible from javascript: https://stackoverflow.com/questions/5822985/cross-domain-resource-sharing-get-refused-to-get-unsafe-header-etag-from-re
i think we can fix this by adding an `Access-Controls-Expose-Headers` header to the backend response but in the meantime, comparing the markdown should also work
=> Compare text content instead of etags when fetching markdown

pxtlib/emitter/cloud.ts
fix is working at https://makecode.microbit.org/v4.1.2
=> [stable7.0] Compare text content instead of etags when fetching markdown (#8268)

pxtlib/cmds.ts, webapp/src/cmds.ts, webapp/src/dialogs.tsx, webapp/src/editortoolbar.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4215
Hides the "Don't show this again" toggle in the download dialog when you manually download as file. Here's the logic for the three download options:
1. If you download using the download button, we respect the toggle
2. If you download using "Download as file" in the "..." menu, we always show the dialog but hide the toggle
3. If you download using the save button, we always show the dialog but hide the toggle
There is now no way to clear the "don't show this again" setting, but it isn't too bad since you can always get to it using 2 or 3
=> Don't show the hide dialog toggle when manually downloading

webapp/src/compiler.ts, webapp/src/tutorial.tsx, webapp/src/workspace.ts
In ios 13.3, indexedDB will not work in an iframe that is embedded in a separate domain. Most of the time we handle indexedDB errors gracefully, but we have a few places where we cache things that assume the DB exists and don't handle errors.
Adding a few try/catch statements so that we ignore failed cache operations. Makes everything slow, but at least it works at all!
=> Don't fail when indexed DB isn't available to cache

cli/cli.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4232
When building hexcache entries for the default project (e.g. libs/blocksprj), also cache hexfiles for those projects plus the other bundled packages.
This is a pretty naive implementation because I didn't want to go through the trouble of actually verifying which projects are compatible (that code is impossible to factor out cleanly). Instead I just try all of them and cache the ones that don't error.
I also took this opportunity to switch to async await, I recommend ignoring whitespace when reviewing the changes
=> Also cache common project variations in staticpkg

webapp/src/cloud.ts, webapp/src/cloudsync.ts, webapp/src/workspace.ts
Well, this isn't the change I was hoping to make, but it is less radical, and a nice intermediate step toward a better solution.
Main change: limit the number of projects syncing with the cloud at one time. Max concurrency is set to 10. While working on this, I noticed a race condition between the sync up and sync down processes. I fixed this by running the phases in serial.
I also discovered a case where signing into github could trigger a full cloud sync, so I untangled that.
Lastly, I deleted a bunch of unused code from cloudsync.ts.
=> limit concurrency when syncing cloud projects

theme/common.less, webapp/src/cloud.ts, webapp/src/codecard.tsx, webapp/src/editortoolbar.tsx
Addresses https://github.com/microsoft/pxt-arcade/issues/3608, but without the spinner as I didn't find an existing spinner widget. But it looks pretty nice as-is, imo. Will bring it to the next design office hours for review.
Also did some tidying up of how we track cloud sync status per project.
=> Improve cloud sync status indicator

pxtblocks/blocklyimporter.ts
If a shadow block somehow becomes a top-level block (e.g. via https://github.com/microsoft/pxt-arcade/issues/3623), blockly refuses to load the workspace and throws an error instead. We don't really care about that restriction, so just convert any top-level shadow blocks in the XML to regular blocks before loading the workspace.
This will make it so that if any projects were affected by https://github.com/microsoft/pxt-arcade/issues/3623, they can now be opened. The actual fix for that issue is here:
https://github.com/microsoft/pxt-blockly/pull/354
=> Patch top level shadow blocks

theme/common.less, webapp/src/editortoolbar.tsx, webapp/src/identity.tsx
This version more closely resembles the design, and uses a spinner to indicate save in progress.
As you can see, it is vastly superior.
Notice the spinner has two states:
* Spinner rotating counterclockwise: Debouncer is active, waiting for a span of 1.5 seconds with no new edits.
* Spinner rotating clockwise (and more quickly): Cloud save is in progress.
If this feels too busy we can just use the clockwise spinner for both. To me that makes cloud sync feel slower than it actually is.
=> Cloud status with spinner

pxtblocks/fields/field_asset.ts, pxtlib/tilemap.ts
Noticed this while I was working on skillmap code carryover stuff. We're using blockly's id for the id of temporary assets in blocks which is probably a bad idea, especially if we ever start having blocks with multiple asset field editors. The asset ids are also supposed to be identifiers (though I'm not sure they're used as such anywhere currently) so better to enforce allowable characters.
This makes it so that we switch to a proper id when upgrading the asset from temporary to real.
=> Don't use block id for asset id

webapp/src/app.tsx, webapp/src/editortoolbar.tsx, webapp/src/identity.tsx, webapp/src/workspace.ts
In app.tsx, tutorial state is written directly to the project header. When the project is later saved, some "smart diffing" happens to discover if any meaningful changes were made. If there were, then the change will be synced to the cloud. In the case of tutorial state, because it was written directly to the source project header, the diff process detected no meaningful changes - because it was diffing the header with itself!
The fix I made is a patch to the smart diff that makes an exception for header-only changes, to just always let them through.
* Show cloud sync indicator in tutorial view
* Save tutorial progress each time the step changes, not just when the user exits tutorial
* It would be nice if project changes were made via transformations on an immutable store. But that's not …
=> Cloud save tutorial state

cli/cli.ts, gulpfile.js, pxtlib/commonutil.ts, pxtlib/emitter/assembler.ts, pxtpy/converter.ts, pxtsim/localization.ts, webapp/src/dialogs.tsx
fix https://github.com/microsoft/pxt-arcade/issues/3627
one of the strings was formatted incorrectly (\` instead of \"), and when I was finding it I noticed a few others were broken as well (but not getting reported). This is because we were not properly extracting from a number of files (subfolders that weren't being checked, as well as a number of folders that had lfs but weren't included in the list: cli, pxtcompiler, pxteditor, pxtpy, pxtsim)
with this change updatestrings builds `334 files; 1811 strings`, where before it had `196 files; 1349 strings`
Also add an escape for skipping lfs on a given line to avoid a hack we had before for not erroring out on the lf function definitions.
=> Fix lf checks in gulpfile to grab missing translations

pxteditor/shell.ts, pxtlib/browserutils.ts, pxtlib/data.ts, pxtlib/localStorage.ts, pxtlib/shell.ts, pxtlib/util.ts, webapp/src/app.tsx, webapp/src/auth.ts, webapp/src/cloud.ts, webapp/src/cloudsync.ts, webapp/src/cmds.ts, webapp/src/core.ts, webapp/src/data.ts, webapp/src/gitjson.tsx, webapp/src/immersivereader.tsx, webapp/src/monaco.tsx, webapp/src/package.ts, webapp/src/scriptmanager.tsx, webapp/src/scriptsearch.tsx, webapp/src/workspace.ts
In preparation to move the auth system to pxtlib, I'm moving "virtual api" and "storage" in a separate step. auth has dependencies on these systems. This operation was mostly a lift-and-shift, whereas moving auth will require some mild refactoring.
=> Move virtual api and storage into pxtlib

webapp/src/headerbar.tsx, webapp/src/sui.tsx
for the microbit iOS app! we send a "backtap" message for click/short tap events, and a "backpress" message for presses > 750ms. this modifies it to also send a "backtap" message for any press < 750ms.
=> Send 'backtap' event for touchend events < longpress threshold

webapp/src/tutorial.tsx
We'll need to port this to microbit, though it's unlikely to be super urgent as the tutorials that error out here can't do anything.
Fix crash on https://makecode.microbit.org/#tutorial:https://makecode.microbit.org/_aCefY5KxgFJu . It's crashing because it doesn't get any block xml when decompiling, but it only doesn't get any block xml because there are no snippets in the first place. (I'm guessing this was only caught because it is the default tutorial over at https://makecode.com/tutorial-tool)
A bit of context here: https://forum.makecode.com/t/tutorial-help-please-check-your-internet-connection-and-check-the-tutorial-is-valid/9178/7?u=jwunderl
=> fix crash when tutorial does not contain any code snippets

pxtlib/auth.ts, webapp/src/accessibility.tsx, webapp/src/app.tsx, webapp/src/auth.ts, webapp/src/cloud.ts, webapp/src/container.tsx, webapp/src/core.ts, webapp/src/headerbar.tsx, webapp/src/identity.tsx, webapp/src/immersivereader.tsx, webapp/src/monaco.tsx, webapp/src/monacoFlyout.tsx, webapp/src/projects.tsx, webapp/src/sui.tsx, webapp/src/user.tsx, webapp/src/workspace.ts
Moved the core pieces of the auth system to pxtlib. The parts that need to do things like show notifications and interact with the workspace are still in webapp. I also left a proxy API in webapp just to minimize the number of code changes.
I fixed a few bugs along the way:
Fixes https://github.com/microsoft/pxt-arcade/issues/3092
Fixes https://github.com/microsoft/pxt-arcade/issues/3579
=> move auth to pxtlib

skillmap/src/components/ActivityActions.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/lib/skillMapParser.ts, skillmap/src/lib/skillMapUtils.ts
the double-click handler was opening the activity directly instead of hooking into the carryover flow. changes:
- double-click opens the code carryover modal if the activity has not been started and carryover is enabled
- tick event for double-click
- better error when loading an incorrect docs markdown path
=> Show code carryover modal on skillmap node double click

webapp/src/auth.ts
The short-circuit in these functions is making them return undefined instead of a promise that resolves to undefined when `client()` is falsy. That causes an exception downstream when whatever is calling them tries to `.then()` the promise. This was causing my local serve to fail.
Converting them to async await which handles undefined.
=> Fix exception when client is undefined

cli/cli.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4273
With this change we can't test the beta or /app/ urls, but that isn't a big deal. Testing the normal site should suffice in those scenarios
=> Fix pwa scope and starturl

webapp/src/compiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4274
=> Don't cache the translated language code on API info

pxtlib/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3642
When we attempted to create a RegExp, if the sprite had been generated with an ID that contained reserved regex symbols, this would fail. This fix aims at escaping all these special characters.
It was tested using https://github.com/eanders-MS/palette-sprite project.
=> Escape characters so regex creation doesn't fail

theme/common.less
for removing the long press event in ios; should be fine to apply generally
=> Disable touch and pointer events for unclickable logos

cli/cli.ts, cli/server.ts, cli/storage.ts, package.json, pxtlib/localStorage.ts
This PR adds a new storage API to pxtlib: `pxt.storage.localhost`. When calls to this API are made while running on localhost, it will route them to the pxt server running in the background on port 3232. In production, it routes calls to local browser storage. This API enables multiple localhost document frames to share local storage, the way they would if they were running in production (assuming the frames were served from the same domain). 
Browsers consider port number when determining same-origin, and skillmap and editor are served on different ports when running locally. This means their same-origin status is different when developing locally vs. running in production. In production, the two will share browser local storage, whereas they won't when running locally in development. …
=> Add storage api to pxt server

skillmap/src/lib/skillGraphUtils.ts, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts
allow fully manual skillmap layouts for @kiki-lee ! syntax:
specify the layout type at the *map* level (not the top of the page)
```
* name: Shark Splash
* layout: manual
```
each node has a position:
```
* position: 0 3 // defaults to 0 0 if unspecified 
```
and edges. edges are a comma-separated list of coordinates, and each edge corresponds to the node in the `next` list at the same index. if an edge is not specified the graph will connect the two with an L-shaped line, not accounting for collisions. the edge will always start from the current node and end at the "next" node, those coordinates do not need to be included.
```
* next: enemies-move, enemies-damage
* edges: 0 1, 0 2; 1 1
``` 
example markdown: https://raw.githubusercontent.com/shakao-test/demo/master/manual.md
=> Manual layout option for skillmaps

skillmap/src/components/makecodeFrame.tsx, webapp/src/app.tsx
fixes a bug where the makecode editor was not loading in the skill map iframe
we switched from the iframe workspace to the browser workspace, which has no implementation of `fireEvent`. starting the tutorial from the `editor.loaded` tick worked until we added some awaits that meant the event was firing before the message handlers were bound
this swaps the `createproject` tick out for an existing editor message and removes the `editor.loaded` handler--we want to wait until that initial load is done before attempting to load a tutorial
=> Use newproject instead of workspaceevent for skillmap project creation

pxtlib/auth.ts, pxtlib/localStorage.ts, webapp/src/cloud.ts
My storage changes had one more bug: If the JSON parse fails, it should fallback to returning the unparsed value.
While debugging this locally I hit some new cosmos exceptions due to how we were constructing the db queries server side (combined with a new limitation Cosmos put in place on the REST API). This caused some new error conditions in the client we weren't recovering from very well. Quick fix was to add a few try/catches. Longer term fix is to handle these errors better. Will log an issue for that.
**Once this is merged I will bump beta (again)**
=> Another storage fix. Also add some resilience to cloud ops

skillmap/src/components/GraphPath.tsx, skillmap/src/lib/skillGraphUtils.ts
the skillmap graph component was drawing edges inverted (rendering each edge node at (y, x) instead of (x, y)), i did not notice this previously because i made the same mistake where the edges were being generated and they cancelled. also renamed some variables to hopefully be less confusing
=> Flip edges in skillmap so they render correctly

webapp/src/immersivereader.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/4281
The issue was in the Electron app it was resolving to makecode.microbit.org/immreader (when it should be makecode.microbit.org**/api/**immreader ) so I'm just hardcoding the whole URL and also reverted to the old API for safety
https://github.com/microsoft/pxt/pull/8259/files?diff=split&w=1
I had changed it in this PR bc I thought it might be better (for offline use) but I don't think it really matters.
=> Use whole Immersive Reader API URL

pxtblocks/fields/field_position.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3672
We will now check values to see if they exist before displaying them as NaN
=> Screen picker should not display value as NaN if block is in it

theme/common.less
fixes https://github.com/microsoft/pxt-arcade/issues/2953
=> Fix project name input padding on thin screens

skillmap/src/components/AppModal.tsx, skillmap/src/components/Modal.tsx, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/styles/modal.css
syntax! in the reward node, specify an attribute called `actions`. this will have a nested list of actions which is indented with 4 spaces exactly. each action has the action type as the key, and a label/url using markdown URL syntax as the value:
```
* actions:
* map: [Go to skillmap](docs:/path/to/skillmap)
* docs: [Learn more](/path/to/docs)
* activity: [Try this activity](activity-id)
* editor: [Optional label]
```
the four kinds of action (represented above) are:
- map: link to another skillmap in a new tab
- docs: link to a makecode docs page
- activity: open another activity in this skillmap
- editor: export the last completed project to the full editor
=> Add custom actions in skillmap completion modal

pxtlib/emitter/cloud.ts
Include query parameter for language when fetching markdown, even when it is packaged (part of: https://github.com/microsoft/pxt-microbit/issues/4286)
Also minor fix for md expiration which didn't matter before this -- in pxt electron the window.pxtElectron doesn't consistently exist immediately on load, so we need to calculate expiration inside the function instead of at the top level for it to expire local markdown properly (and properly use the cache for the translated ones)
=> include lang query parameter when fetching md

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3089
=> don't auto-run simulator when the sim is collapsed

theme/common.less, theme/editor-sidebar.less, theme/greenscreen.less, theme/highcontrast.less, theme/pxt.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/components/core/TabContent.tsx, webapp/src/components/core/TabPane.tsx, webapp/src/sidepanel.tsx
this PR adds a TabPane component; the tabs are pulled from the children of the component, if there is only one child then no tabs are displayed (current scenario). this should make it easy to add the tutorial and sidedocs view later. 
it also separates the "filelist" div element (previously the sidebar, but also the floating simulator in mobile/tablet views) into an "editorSidebar" parent and a "simPanel" child element, so that we can later show the tutorial view and the small simulator. 
builds (everything should look basically identical to before):
https://arcade.makecode.com/app/17c2c55576a2d6c83d762d2a0e0e6a4342685280-77a8e65f69
https://minecraft.makecode.com/app/794632fa97b320d7ad5ebb0c65497a9e7a720d60-cc4756b75c
=> Move editor sidebar into a tabbed panel component

docs/csp.md
Some updates to the 'Computer Science Principles' launch page.
Closes #8342
=> Updates and edits to the 'CSP' page

cli/buildengine.ts, pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts, pxtlib/cpp.ts, pxtlib/hf2.ts, pxtlib/main.ts, tests/compile-test/lang-test0/51exceptions.ts
This adds UF2 generation support for ESP32-S2 (for boards with https://github.com/adafruit/tinyuf2).
Additionally:
* we now throw error when command line deploy is requested but cannot be completed
* break/continue/return inside of try-catch blocks are handled correctly (and ones inside try-finally give explicit errors - not implemented yet)
* .mk (Makefile includes) are now supported in buildengine
=> support for ESP32-S2

theme/themes/pxt/collections/menu.overrides, webapp/src/container.tsx, webapp/src/identity.tsx
associated with https://github.com/microsoft/pxt-arcade/pull/3725, increases padding for the icons on tablet since we're hiding the help icon and have a bit more space. small fix to hide sign in text on landscape ipad.
=> Increase header icon padding on tablet, hide sign in text on small desktop

theme/asset-editor.less, webapp/src/components/assetEditor/assetGallery.tsx, webapp/src/components/assetEditor/editor.tsx
grays out the button and changes the cursor to a "not allowed" (circle with line through it). small fix for https://github.com/microsoft/pxt-arcade/issues/3357 in this upcoming release, long-term we still want to add the ability to switch editors in a tutorial
=> Disable 'Create Asset' button in tutorials

webapp/src/auth.ts, webapp/src/projects.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3719
(clears automatically with the local storage cleanup in reset)
=> Only show cloud card after using identity

webapp/src/scriptmanager.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3686
pull the header by id, not by the index
=> Fix Open Project

skillmap/src/components/AppModal.tsx, skillmap/src/components/HeaderBar.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/lib/skillMapUtils.ts
- some null checks
- only open on doubleclick for unlocked activities
- check if previous activities present for displaying code carryover (fixes issue with first activity of carryover maps not opening)
=> Small skillmap fixes for opening activity, switching maps

pxtlib/cpp.ts
=> Increase the C++ build timeout from 2min to 3min

pxtlib/tilemap.ts, pxtlib/util.ts, webapp/src/components/assetEditor/assetGallery.tsx, webapp/src/components/assetEditor/assetSidebar.tsx
- don't set the display name on temporary assets at all
- some null checks
- move the default display name code to tilemap so it can be shared
- skips dispatching the change gallery view event if you're already on the correct (user assets) view, as it makes this very slow
fixes https://github.com/microsoft/pxt-arcade/issues/3068
=> Fix temporary asset duplication

webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/components/assetEditor/editor.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3502
two different places where we were using the asset returned from closing the sprite/animation editor to check if it was temporary--we actually generally care about whether the asset was initally temporary (and it might've gotten named during the editing process)
=> Fix naming of temporary assets in asset editor view

theme/common.less, webapp/src/codecard.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3216
(don't show it when on a smaller screen)
=> Don't show timestamp on tutorial cards

skillmap/src/lib/workspaceProvider.ts
When not signed in, load skillmap progress from local workspace.
=> Fix for skillmap progress save when not signed in

skillmap/src/components/HeaderBar.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3328
=> Use relprefix for the home button in skillmap

webapp/src/cloud.ts
The syncing of deleted projects was falsely detecting errors.
This is a quick fix. I'd like to clean up this code later to return a richer sync result.
=> Fix false-positive sync failures

skillmap/src/components/ActivityActions.tsx, skillmap/src/components/AppModal.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/lib/skillMapUtils.ts
fixes https://github.com/microsoft/pxt-arcade/issues/3744
bug was that the button was attempting to show the code carryover modal, but the previous activity wasn't completed so the code couldn't be carried over. 
i'm not going to do it for this release, but we have a lot of different ways to open an activity (start, restart, double-click on tile) and we should unify the "show carryover modal vs open activity" logic somewhere.
=> Check if previous activity is completed before trying to show skillmap code carryover

skillmap/src/components/HeaderBar.tsx
This should fix the broken logo in the skillmap page, but I'm not sure how to test it :\ I can't uploadtrg bc my build is super mad about it, but the issue was it was trying to fetch the logo at:
/static/skillmap/https://pxt.azureedge.net/blob/d6139e3d0af51f02aa5f8765ecb0985acbd98551/static/Micorsoft_logo_rgb_W-white_D.png
bc I was using resolvePath and it was prepending /static/skillmap.
This doesn't fix the localhost serve logo. I could only ever get it to work if I dropped something in pxt/skillmap/public, which *feels* like a place I shouldn't be touching???? Any advice is appreciated
=> Just use logoURL for skillmap logo

pxtsim/simlib.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3742
In the future if we want people to make rhythm games in arcade, we should probably rework this code. Promise.delay and setTimeout just aren't accurate enough. 
The best way to do timing for music is to run a metronome in a webworker that fires events in the main thread at regular intervals.
=> Fix timing in queuePlayInstructions

skillmap/src/components/ActivityActions.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3759
=> Only show completion modal on 'notstarted' action button click

pxtlib/util.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3446
This is consistent with Microsoft.com as well
=> Correcting the localized name of Traditional Chinese

pxteditor/editor.ts, pxteditor/editorcontroller.ts, skillmap/src/App.tsx, skillmap/src/actions/dispatch.ts, skillmap/src/actions/types.ts, skillmap/src/components/AppModal.tsx, skillmap/src/components/makecodeFrame.tsx, skillmap/src/store/reducer.ts, webapp/src/app.tsx, webapp/src/components/assetEditor/assetGallery.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3747
This changes the skillmap to always keep the iframe around in the background. When no tutorial is open, the editor unloads the current project and has its visibility hidden until the next activity is opened.
In the meantime, you can send whatever messages you want to the editor. For sharing, i'm doing it through the redux state (see makecodeframe's componentDidUpdate) but @eanders-MS I expect you might want to use the frame directly. Easiest way to do that is to probably pass a message channel of some kind from the makecodeframe in App.tsx
Not sure if this will improve perf at all, but it might! I think @shakao tried out something similar in the past but the gains weren't huge.
=> Always keep the skillmap iframe in the DOM

skillmap/src/components/SkillGraphContainer.tsx
skillmap appears very tiny when the background image doesn't load (attempts to scale the graph size to match a 0 x 0 image), this just skips the background scale if either dimension of the image is zero
=> Don't use background image size for skillmap if image didn't load

skillmap/src/components/makecodeFrame.tsx
think this just got dropped as stuff was being shifted around in the iframe component. we might be able to clean up some of this state later (after release) also!
fixes https://github.com/microsoft/pxt-arcade/issues/3778
=> Reset finishedActivityState when opening new activity

skillmap/src/App.tsx, skillmap/src/styles/skillgraph.css
there is still a slight jump when the page first loads as the graph goes from default size -> sized to fit the background image, but this should remove the jitter when going in between activities.
=> Don't unload/reload skillmap graph, reduces jittering

webapp/src/app.tsx
This fixes the koala bug, aka https://github.com/microsoft/pxt-arcade/issues/3786
=> Don't write the contents of nonexistent files when merging projects

skillmap/src/components/makecodeFrame.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3782
When the iframe is loading again, kick us back into the loading state for the makecodeFrame. I tested this with an automatic reload (suggested by richard!!) and not the scenario in the bug, but I *think* it should work. 
I will see if an uploadtrg might trigger the bug, and if it does, I'll try testing it there
=> Handle iframe reload in skillmap

skillmap/src/components/makecodeFrame.tsx
this seems to fix https://github.com/microsoft/pxt-arcade/issues/3789 on localhost--i couldn't get a repro on /beta so i'm not entirely sure.
this is a quick fix--the issue is there's some concurrency in the webapp that's causing the blocks editor to reload after we send an unload event, and send an extra editor.loaded tick, which causes the skillmap load a project even when the iframe is hidden. (only happens when clicking the tutorial "Finish" button as far as i can tell.) will try to untangle it from the webapp end later
=> Only load project if skillmap editorview open

skillmap/src/lib/browserUtils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3758
The issue here is that Safari is setting the "If-None-Match" header in the request to the etag the backend returns on the markdown request. Our backend doesn't include that header in the "Access-Control-Allow-Headers" list so Safari throws an exception (and clears the cached response). I'm not sure I know enough about CORS to know if we should add that to the list of headers or not (@eanders-MS @aznhassan ?)
Making the request a second time after the cache has been cleared fixes the issue. Obviously not *ideal*, but this does the trick. Not sure how to remove the header from the request directly.
=> Retry request for skillmap markdown in safari

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3794
=> Don't run sim in background when no project is loaded in the skillmap iframe

webapp/src/editortoolbar.tsx
The project name input in the editor toolbar uses the project name that comes from the parent editor state, which means that every time you do a keystroke the effect of that keystroke needs to propagate from the top down. That makes editing laggy and sometimes causes characters to be missed or the cursor to jump around. Fixing it by using local state.
This bug is easier to see if you open a big project and trigger a compile (i.e. drag a block) right before you start typing in the input.
I don't think this is filed anywhere but it has been annoying me a ton lately. Not a regression but should probably get cherry picked for either this release or next.
=> Fix the editor toolbar project name to use local state

theme/common.less, theme/editor-sidebar.less, theme/greenscreen.less, theme/highcontrast.less, theme/pxt.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/components/core/TabContent.tsx, webapp/src/components/core/TabPane.tsx, webapp/src/sidepanel.tsx
reopening https://github.com/microsoft/pxt/pull/8308
there is no visual difference with this change, it just shifts the DOM elements around to make the tutorial implementation easier! adds a tabbed pane component and separates the filelist div element into an editorSidebar parent and a simPanel child element, so that we can later show the tutorial view and the small simulator
=> Move editor sidebar into a tabbed panel component 

docs/blog/arcade/in.md
Tweeted link was truncated to https://makecode.com/blog/arcade/in, so let's put the blog post there.
=> blog link for tweeted url

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/components/core/TabPane.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/headerbar.tsx, webapp/src/sidepanel.tsx
bunch of small changes to hook up the new components! each commit is one item:
- https://github.com/microsoft/pxt/commit/c01809922b539ea161c3cd8863c1127b41370964 adds `tutoriallayout=v` url flag for viewing the new layout! temporary name, ultimately i want to turn the vertical layout on by default and have a force=horizontal flag or something 
- https://github.com/microsoft/pxt/commit/c8840d225b078a90876bb01b15706be949af95e3 clicking on the screen of the mini sim opens the simulator tab (no animation yet) 
- https://github.com/microsoft/pxt/commit/e17f1a487ffbd2af40375c1a649c134d8b32c034 callback for saving the step change into the project header 
- https://github.com/microsoft/pxt/commit/279c9750ea5f65faead447ca69c162e888e42ff4 open tutorial tab by default. might swap the Sidepanel to be …
=> Add flag for new tutorial layout, hook up to tutorialOptions state

webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/sidepanel.tsx
bringing back modals! two commits, first is displaying our standard modal for tutorial steps with `showDialog`, second is a fix to show the mini sim when we initially show the tutorial tab (also a tiny refactor so that the tab/mini sim state are easier to sync)
=>  Display modal for 'showDialog' steps

theme/tutorial-sidebar.less
was shifting the normal tutorial hint to the bottom left position! this fixes it
=> Only apply vertical tutorial hint CSS when flag is active

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_tilemap.ts, pxtlib/spriteutils.ts, webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/ImageEditor/SideBar.tsx, webapp/src/components/ImageEditor/tilemap/Minimap.tsx, webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/TilemapFieldEditor.tsx
A few changes to improve the performance of the image editor, especially for background images. This PR brings back light mode for the image+tilemap editor to remove transparency and one of the canvases. It also changes how we draw the images to use imageData instead of the rendering context, which has major perf gains on my machine.
Weirdly, when I attempted to time the perf gains from using ImageData I got worse numbers for the new implementation but it is way, way, smoother when actually in use. I have no idea how to explain that. You can try it for yourself though, using this link:
https://arcade.makecode.com/app/2646b82239a5635071a5c34c2e41d3e6025d9b68-58fd418611
I recommend trying to edit a 500x500 image to really see the difference.
=> Performance Improvement for background images

webapp/src/app.tsx
i can get into this state (https://github.com/microsoft/pxt-arcade/issues/3852) by forcing an error in `loadTutorialFiltersAsync`. not really sure how recent changes would have caused an error here but it's one of the only places that calls exitTutorial and throwing an error elsewhere causes the workspace to hang (instead of exiting the tutorial)
regardless, i think this fix won't cause any harm--instead of exiting we just load the entire toolbox. this is a slightly worse tutorial experience but at least the tutorial is still there
=> Load entire toolbox instead of exiting tutorial on filter error

pxteditor/editor.ts, pxteditor/editorcontroller.ts, skillmap/src/App.tsx, skillmap/src/components/UserProfile.tsx, skillmap/src/lib/skillMapUtils.ts, skillmap/src/lib/workspaceProvider.ts, webapp/src/app.tsx, webapp/src/cloud.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3861
Fixes https://github.com/microsoft/pxt-arcade/issues/3858
Makes a few changes to preserve the local user state when logging in on the skillmap page:
1. When syncing local skillmap headers to the cloud, syncs duplicates instead of the original
2. Local user state is no longer overwritten when logged in
3. Always copies state from the local user and not whatever is in the store
The copy only happens for maps that the signed in user has no progress in.
=> Make copies of local projects when importing skillmap progress to cloud

pxtlib/browserutils.ts
flipping the url flag, now `tutoriallayout=h` will give the old layout!
=> Enable new tutorial layout by default

theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/sidepanel.tsx
feedback from design office hours:
- hide back button on modal when there is nothing to go "back" to
- update hint design for tablet view
=> Hide back button on tutorial modals, tablet hint design

cli/cli.ts, localtypings/pxtarget.d.ts
Allow specifying a subset of bundleddirs to include hexfile combos for in staticpkg / offline app to fix electron app build; currently it's timing out due to trying every combination of two bundleddirs.
I'll note that there are still lots of hexfile errors sent out during the staticpkg build, as expected -- e.g. hw---rpi doesn't play nicely with lots of the hardware extensions.
There were also two issues with comparing to check that they might be compatible -- it wasn't recognizing versions of the package as being the same (e.g. it would attempt core + core---samd when they shouldn't work together), and depending on the os it would fail to compare in the first place as it resolved the paths first (e.g. it would end up with `libs\\core` vs `libs/core`).
Also added some more logging so it's …
=> allow specifying pkgs to compile hex files for in staticpkg

pxtlib/main.ts, pxtlib/util.ts, webapp/src/app.tsx, webapp/src/compiler.ts
I was doing some profiling on performance and noticed we spend a lot of time in our clone function in util.ts. That clone function just looks like this:
```ts
export function clone<T>(v: T): T {
if (v == null) return null
return JSON.parse(JSON.stringify(v))
}
```
Turns out, the vast majority of the time spent cloning was in two places: cloning the apptarget when initially setting it up and cloning the cached api info in webapp/src/compiler.ts. We were basically cloning the entirety of target.js (a 10.1 MB file in pxt-arcade) multiple times!
This PR speeds things up considerably by implementing functions for specifically cloning the SymbolInfo and TargetBundle types. In my testing, it cut it down to about 1/3 of what it was before when setting up the AppTarget (I didn't time the cached …
=> Speed up the clone operation for api info and apptarget

cli/cli.ts
fixes https://github.com/microsoft/pxt-arcade/issues/3851
I'm not 100000% sure that this will fix the problem, but let me tell you why I suspect it will:
The issue was that the icons.css in https://github.com/microsoft/pxt-32-built/blob/master/icons.css wasn't being updated at all, and the reason we were seeing it surface in skillmap and not the regular app is b/c the regular webapp takes icons.css and adds it to the semantic stylesheet (which is handled correctly).
I am suspicious that the reason why icons.css isn't uploading correctly is because of [this line](https://github.com/microsoft/pxt/blob/4d89bf1bfcaf541a43f558b735f11581a6bdcbdb/cli/cli.ts#L1252) only copying the last seen path for each filename -- and in this case, the last path was for …
=> Never use the icons.css from pxt-arcade-sim

skillmap/src/App.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3853
state.user is a unreliable source for getting the current user! Fetch it with getUserStateAsync and then consistently use that user
=> Use the cloud user when upgrading projects

skillmap/src/App.tsx
The way I was determining whether cloudSyncCheckAsync should execute was gross. This cleans it up (hopefully!) into something more clear and maintainable (hopefully!).
Targeting stable7.1 branch directly. We can merge stable7.1 back to master after we ship it.
=> cleanup cloudSyncCheckAsync trigger

skillmap/src/lib/skillMapParser.ts
fix for the skillmap end modal action to export the finished project to the full editor--it's formatted like `* editor: [Link Text Here]` without the parenthesis/link
=> Allow skill map end action without link

theme/common.less, theme/tutorial-sidebar.less, webapp/src/app.tsx, webapp/src/components/core/TabPane.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/sidepanel.tsx
i'm not doing any of the minecraft-specific styles (blocky buttons, fonts, colors) in this PR. there will also be a separate one to restore the HoC styles (hideiteration flag, etc)
=> CSS adjustments for headless (no simulator) tutorial view

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/headerbar.tsx, webapp/src/sidepanel.tsx
i've made this same mistake at least twice (isVerticalTutorial() checks for the URL flag but not whether the project is actually a tutorial) so i'm renaming `isVerticalTutorial` -> `useVerticalTutorialLayout` to hopefully make the flag clearer
this is the bugfix: https://github.com/microsoft/pxt/pull/8472/files#diff-94834a36659c6506f142b87ee5375cb5a79e412002687c17752c78627d9902b2L86
fixes https://github.com/microsoft/pxt-arcade/issues/3902
=> Rename 'isVerticalTutorial' check, only apply headerbar styles in tutorial mode

cli/cli.ts
fixes https://github.com/microsoft/pxt-arcade/issues/3925
the icons.css in the sim also has....semantic icons at the end. I can't figure out how to append that in our build, so I'm just gonna update icons.css in arcade-sim.
=> Use arcade-sim icons.css :)

theme/common-components.less, theme/tutorial-sidebar.less, webapp/src/components/core/TabContent.tsx, webapp/src/components/core/TabPane.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorial/TutorialStepCounter.tsx, webapp/src/sidepanel.tsx, webapp/src/simtoolbar.tsx
three small changes bundled together 
- https://github.com/microsoft/pxt/commit/39232e019a0346370596fad7004dec6ea410a147 - instead of fullscreen and collapse simulator buttons, show "switch to simulator tab" (with temporary icon) and start/stop (without collapse) buttons by the mini sim, in tutorial view 
- https://github.com/microsoft/pxt/commit/752f52970fd7ef66ab91fe79f93855c6d0f5379d - tutorial title by the step number
- https://github.com/microsoft/pxt/commit/3f21c08c50354db18d8b59da1b62897a2e9e84be - show a red dot on the tutorial tab when the simulator tab is visible 
fixes https://github.com/microsoft/pxt-arcade/issues/3905
fixes https://github.com/microsoft/pxt-arcade/issues/3906
=> Mini sim buttons, tutorial title, notification badge

theme/themes/pxt/collections/menu.overrides, theme/themes/pxt/globals/site.variables, theme/tutorial-sidebar.less, webapp/src/app.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/dialogs.tsx, webapp/src/editortoolbar.tsx, webapp/src/headerbar.tsx, webapp/src/sidepanel.tsx, webapp/src/sui.tsx
- exit tutorial button in tutorial tab bar, or in header when there are no tabs (headless)
- report abuse button styled like exit button, opens new modal with explanation of content + link to tutorial
=> Add exit tutorial button, style report abuse/exit to match new header

pxtrunner/runner.ts, skillmap/src/App.tsx, webapp/src/app.tsx
Looks like the logic for local serving docs broke again, this time I'm getting a different default locale from chrome (that is, "en-US" instead of "en"). This then failed the check here and enabled the server translations, which should only be enabled in non-default lang
If this breaks again I'll just add a url flag and cut out all the special casing logic here I think, it's getting way too tedious
=> fix local serve docs again

cli/hid.ts, pxtlib/hf2.ts, pxtlib/service.ts, pxtlib/util.ts, pxtsim/libgeneric.ts, pxtsim/runtime.ts, webapp/src/marked.tsx
A couple small changes to improve tutorial loading perf. All of these measurements were done in chrome with the 6x CPU slowdown:
1. When rendering the markdown snippets, do it outside the dom to prevent a style recalculation (went from ~90ms to ~45ms)
2. Replaced the UTF8 encoding/decoding we do in a few places to use the TextEncoder/TextDecoder APIs which are now supported in all the browsers we support and node. I mainly did this because I was noticing a lot of time spent getting a SHA256 hash on extensions (went from ~150ms to ~60ms but this is called a few times with different timings)
AFAIK the result of the TextEncoder/TextDecoder should be the same as our implementations. I confirmed it at least returned the same results in the calls to the SHA256 function.
Doesn't make a *ton* of …
=> A couple small perf improvements

pxtlib/browserutils.ts, webapp/src/app.tsx, webapp/src/headerbar.tsx, webapp/src/sidepanel.tsx, webapp/src/simtoolbar.tsx
moving away from "vertical"/"horizontal" naming, using "tabbed tutorial" for the new view. the flag to enable the old view will be `?tutorialview=old`
=> Small tutorial flag rename and cleanup

localtypings/pxtarget.d.ts, pxteditor/editor.ts, pxteditor/editorcontroller.ts, webapp/public/controller.html, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/3976
Adds an editor message to control the allowed languages of a project inside an iframe. The options are:
* "python-only",
* "javascript-only",
* "blocks-only",
* "no-blocks",
* "no-python",
* "no-javascript",
* "" (all languages)
The message should look like this:
```
{
type: "pxteditor",
action: "setlanguagerestriction",
restriction: "blocks-only"
}
```
=> Add editor message for restricting editor languages for loaded project

theme/home.less, theme/themes/pxt/views/card.overrides, webapp/src/codecard.tsx, webapp/src/projects.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3835
looks like 
with tags, but these are just test tags for now :)
=> Display meta data for skillmap cards

webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorial/TutorialHint.tsx, webapp/src/components/tutorial/TutorialStepCounter.tsx, webapp/src/sidepanel.tsx, webapp/src/tutorial.tsx
check to make sure all tick events from the old `tutorial.tsx` file are represented in the new components as well
the one i am not carrying over is `tutorial.hint.next` (from clicking "OK" on a modal in a tutorial), instead i'm adding an `isModal` measurement to the previous and next tick events, @abchatra does that work? i don't think we used the hint.next tick in many queries
=> Tutorial telemetry pass

cli/cli.ts, package.json, theme/common.less, theme/highcontrast.less, theme/home.less, theme/image-editor/imageEditor.less, theme/pxt.less, theme/style.less, theme/theme.config, theme/themes/pxt/modules/modal.overrides, theme/tutorial.less
Upgrading less, semantic-ui-less, karma, and karma-mocha. Once this is merged, I'll go around and do PRs on all the targets with the necessary less changes.
I *think* I fixed all of the problems with updating semantic-ui-less but we should definitely do some thorough UI testing on this.
Thanks to @jwunderl for reaching into his memory palace and remembering how to fix the less build.
=> Upgrade npm dependencies

theme/tutorial-sidebar.less, webapp/src/blocks.tsx, webapp/src/components/core/TabContent.tsx, webapp/src/components/core/TabPane.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/monaco.tsx, webapp/src/sidepanel.tsx
- set blockly field view bounds for monaco and blocks editors to not cover the tutorial sidebar (fixes https://github.com/microsoft/pxt-arcade/issues/3984)
- tab navigation + aria labels for sidebar tab pane and tutorial exit (fixes https://github.com/microsoft/pxt-arcade/issues/4022)
- reset scroll when navigating to new step (fixes https://github.com/microsoft/pxt-arcade/issues/4024)
- CSS fixes (top margin in sim tab, change icon for tutorial tab, fix fancy bullet CSS to handle semantic update)
=> Tutorial tab navigation, blockly field view sizing, CSS fixes

webapp/src/app.tsx, webapp/src/sidepanel.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/3996
\+ bonus fix for a console error with the old tutorial hint manager
=> Autofocus simulator when expanding the mini sim

theme/asset-editor.less
Fixes https://github.com/microsoft/pxt-arcade/issues/4026
The semantic ui upgrade made it so that a lot of our selectors are being overridden by the semantic ones and need to be made *slightly* more specific.
=> Make icon selector more specific to fix asset editor buttons

webapp/src/sidepanel.tsx, webapp/src/tutorial.tsx
- remove 'Exit Tutorial' button in locked editor mode
- remove lightbox button altogether as the semantic update is breaking it (future TODO for cleaning up lightbox mode)
- update icon name
=> Remove lightbox button, semantic compatibility fixes

theme/home.less, theme/themes/pxt/modules/modal.overrides, webapp/src/projects.tsx
css fixes
* first commit: fix https://github.com/microsoft/pxt-arcade/issues/4047
* second commit: fix https://github.com/microsoft/pxt-arcade/issues/4046 ( I just took my version from https://github.com/microsoft/pxt/commit/2269cd6d3f30feda7e3f2992fd3455e57347c00d and reverted the conflicting changes from https://github.com/microsoft/pxt/pull/8506, I *think* I checked all of the modals w/ this change)
* third commit: fix count on import modal so it doesn't go to two rows when not signed in: 
vs current incognito beta:
(I didn't fix this icons here, it looks like that just works in localhost currently?)
=> css fixes for release

pxtlib/browserutils.ts, theme/common.less, theme/tutorial-sidebar.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/components/assetEditor/editor.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/monaco.tsx
- only apply tablet simtoolbar styles when not full screen, hide unnecessary buttons from playable sim view (fixes https://github.com/microsoft/pxt-arcade/issues/4061)
- change z-index of tutorial-hint-mask component (fixes https://github.com/microsoft/pxt-arcade/issues/3999)
- add isTabletSize browser util function, add check to monaco, blocks, and asset editors to fullscreen the sprite editor on small screens (fixes https://github.com/microsoft/pxt-arcade/issues/4057)
=> Fullscreen sprite editor on tablet tutorial, CSS fixes

theme/home.less, webapp/src/projects.tsx
close https://github.com/microsoft/pxt-arcade/issues/4056
Make the transition animation take a bit longer, and the transition time 3 seconds longer~
=> slower hero banner

cli/cli.ts
fixes https://github.com/microsoft/pxt-arcade/issues/4045 I checked all the icons mentioned in the issue and it looks good!
issue was icons got broken up into three fonts -- icons, brand-icons, and outline-icons. The cli was doing some maneuvering to include the regular icons font, so I just added it for the two new fonts :)
=> Link brand fonts and outline fonts

webapp/src/sidepanel.tsx
fixes issue where navigating between recipes causes the mini simulator to be hidden
=> Show tutorial tab when navigating directly between tutorials or recipes

pxtlib/cmds.ts, webapp/src/browserworkspace.ts, webapp/src/cmds.ts
request from the foundation for the iOS app, they want to receive a message when the workspace is loaded/when the event listeners are fully registered (https://github.com/microbit-foundation/microbit-ios/issues/63). this implements loadedAsync on the browser workspace and adds a command for sending the message. i didn't want to add something too native host specific to our main browser workspace loading flow, open to other suggestions if folks have em!
=> Implement loadedAsync in browser workspace, add native host message

theme/themes/pxt/modules/modal.overrides
Port https://github.com/microsoft/pxt/pull/8539 to arcade stable, fix hw scroll in safari
I did look a bit to see when it regressed, looks like it was present in https://arcade.makecode.com/v1.6.16 so it actually wasn't a last minute bug / came from the semantic ui upgrade itself, not any of the follow up fixes. I guess we just hit an unlucky combo of undefined behavior for scrollable `position: fixed` here that only safari diverged on.
=> [stable7.2] fix scroll in safari

pxtcompiler/emitter/snippets.ts
for https://github.com/microsoft/pxt-arcade/issues/891
check to see if the parameter is visible on the block and includes it in the snippet if so. we also still include required parameters, regardless of if they're on the block.
=> Include parameters in monaco snippet if they are in the blockdef

package.json, theme/blockly-core.less, theme/tutorial.less, webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/1991
but needs this change! https://github.com/microsoft/pxt-blockly/pull/360
looks like this:
ideally would have more CSS changes to restrict the size of the flyout to always be a certain width. Right now the sizes get kinda wild sometimes. Another EZ option would be removing the double scroll, and just cutting off the blocks. You can see the whole block when you drag one out (shannon's idea!) 
a good way to test is to make your screen small, and then press the + button 
(I still need to test this in game)
Try here:
https://minecraft.makecode.com/app/ab924030ba350913bc71b432bfb45f4b33feb968-9ded06f80b#tutorial:/hour-of-code/reforestation
also fllyoutonly no hideiteration
https://minecraft.makecode.com/app/ab924030ba350913bc71b432bfb4 …
=> Don't let blocks overflow, add scrollbar

pxteditor/editorcontroller.ts, skillmap/src/components/makecodeFrame.tsx
and restore code for handling "exit" event ("Exit Tutorial" link in tutorial tab bar clicked) in the skillmap
fixes https://github.com/microsoft/pxt-arcade/issues/4285
=> Add tutorial exit event type to EditorMessageTutorialEventRequest

pxtlib/auth.ts, skillmap/src/App.tsx
At skillmap startup time, the app asks the editor iframe to do a cloud sync check to make sure skillmap has latest cloud state. This check does some complicated cloud operations, then posts back a completion message. Skillmap won't save anything to the cloud until it gets this message, but there are times when it never arrives. On these occasions, skillmap sync will stay in a disabled state. This PR adds a timeout to the cloud sync check. If it doesn't return in a reasonable amount of time, we assume it failed somewhere and move on.
The failure seems to be infrequent, and I will keep looking into the issue, but this timeout seems like a good thing regardless.
=> Add timeout to cloud sync check

theme/tutorial.less
fixes https://github.com/microsoft/pxt-minecraft/issues/2144
=> Make tutorial header content smaller so the text doesn't get cut off

pxtlib/auth.ts, webapp/src/auth.ts
Because skillmap updates user preferences so frequently, I added a debouncer to ease network traffic. Changes to user preferences are accumulated and sent in batch after a timeout. For signed in users, language setting is also saved in this blob. The issue was that after changing language, the page is reloaded. Due to the debounce, the change hadn't been synced to the cloud yet. When the page reloads, it pulls latest preferences from the cloud, which still has the old language selection.
I also added a queue to accumulate pending changes. I think we had a bug where only the most recent patch would be synced up.
Fixes: https://github.com/microsoft/pxt-arcade/issues/4310
=> Sync language change immediately, don't wait for debouncer to fire

skillmap/src/lib/browserUtils.ts
@dmonroym was right, looks like we aren't returning localized skillmap files right now! this updates it so that we're using the shared markdownAsync function, which should pull the correct locale from the user settings.
=> Use pxt.Cloud markdownAsync function in skillmap for localized files

react-common/components/profile/BadgeInfo.tsx
Fixes the URL in the badge info modal for docs skillmaps
=> Fix url for the skillmap in the badge modal

pxtlib/auth.ts, pxtlib/tilemap.ts, pxtlib/util.ts
When queuing changes to user preferences, don't accumulate redundant patches. Instead, replace the old one with the new one.
For this fix I needed an implementation of `arrayEquals`. I found an existing one in tilemap.ts and moved it over to util.ts.
Fixes https://github.com/microsoft/pxt-arcade/issues/4313
=> Smarter user preference patch queuing

webapp/src/extensionManager.ts, webapp/src/extensions.tsx
The check are overly aggressive and prevent from doing localhost testing. If localeditorextensions is set, trust localhost server.
=> trust editor extensions in debug mode

skillmap/src/App.tsx, skillmap/src/components/makecodeFrame.tsx, skillmap/src/styles/makecode-editor.css
fixes https://github.com/microsoft/pxt-arcade/issues/4331
we're still not really sure what's causing this bug.... but delaying the progress syncing until the workspace has loaded seems to fix it (for now). this means there's a noticable pause between logging in and your local progress importing, so we also added a loader during that state. 
build: https://arcade.makecode.com/app/de3eb561356a7951f9b6614556c3b56c968ee044-5f756ce822--skillmap
=> Delay the readyPromise until the workspace is loaded, add skillmap loader to main page

localtypings/pxtarget.d.ts, react-common/components/profile/Badge.tsx, react-common/styles/profile/profile.css, skillmap/src/App.tsx
This PR does two things:
1. Moves the "saving to cloud" loader earlier so that it shows up when you navigate to the page if you're signed in. This prevents the bait and switch of appearing to load before showing a loader
2. Adds support for locked badge images:
=> Make loading start earlier and add locked badges

gulpfile.js, localtypings/pxtarget.d.ts, react-common/components/profile/Badge.tsx, react-common/components/profile/BadgeInfo.tsx, react-common/styles/profile/profile.css, skillmap/.eslintrc.js, skillmap/src/App.tsx, skillmap/src/components/AppModal.tsx, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/lib/skillMapUtils.ts, skillmap/src/styles/modal.css, skillmap/tests/skillmapParser.spec.ts, skillmap/tests/tsconfig.json, theme/pxt.less, webapp/src/components/ImageEditor/ImageCanvas.tsx
Cherry picking my badge fixes from #8592 and #8600
Also an unrelated but safe change to fix tilemap cursors in #8601
=> [stable7.3] Cherry pick badge fixes

skillmap/src/App.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4363
we were skipping reward nodes since they don't have a headerid
=> Include reward node progress when importing local state

package.json, pxtblocks/blocklycompiler.ts, pxtblocks/blocklydiff.ts, pxtblocks/blocklyimporter.ts, pxtblocks/blocklylayout.ts, pxtblocks/blocklyloader.ts, pxtblocks/blocklyrenderer.ts, pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_base.ts, pxtblocks/fields/field_breakpoint.ts, pxtblocks/fields/field_ledmatrix.ts, pxtblocks/fields/field_melodySandbox.ts, pxtblocks/fields/field_note.ts, pxtblocks/fields/field_procedure.ts, pxtblocks/fields/field_tileset.ts, pxtblocks/fields/field_toggle.ts, pxtblocks/fields/field_turnratio.ts, theme/blockly-core.less, theme/melodyeditor.less, theme/print.less, theme/toolbox.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/toolbox.tsx, webapp/src/tutorial.tsx
requires https://github.com/microsoft/pxt-blockly/pull/359
mostly small fixes to sync with blockly-side changes. i also removed all the code for handling the accessible blocks experiment, since it's moved out of blockly-core into an extension and we need to re-integrate with it. 
(this will fail the build until i can update the npm package, since that's where the typings come from)
builds!
https://arcade.makecode.com/app/894739978b4be11010c202ea303e01047d102420-e3d1f85bce
https://makecode.microbit.org/app/9e9f521b48ac103e33139fe979e611db76c9eab1-d62781acca
=> Updates to sync with Blockly changes through July 2021

webapp/src/app.tsx, webapp/src/auth.ts
The high contrast setting on non-identity targets has been broken since the auth refactor to support identity in skillmap. This fixes it.
Fixes https://github.com/microsoft/pxt-arcade/issues/4388
=> Fix high contrast for non-identity platforms

package.json
fixes https://github.com/microsoft/pxt-arcade/issues/4403
fixes https://github.com/microsoft/pxt-arcade/issues/4399
removes calls to callValidator, which were causing console errors/blockly crashes.
=> Bump pxt-blockly to 4.0.6

pxtlib/blocks.ts
A number of built-in blocks have incomplete help paths (missing the leading '/'). This causes the help doc to open in a new tab rather than as sidedoc.
Fixes #7377
=> Fix some built-in block help paths

docs/translate.md
Add another section to help translators understand the block highlight format in tutorials. Also, re-level some of the sections in the page.
Closes https://github.com/microsoft/pxt-microbit/issues/4435
@microbit-mark
=> Block highlight section in 'Translate' page

skillmap/src/lib/skillMapParser.ts
fixes https://github.com/microsoft/pxt-arcade/issues/4419
issue was the trailing list from the certificate node set the current indent, which caused the parser to try and pop a list from the stack and add the current key/value pair (name: "activity name") to it. this fails gracefully, but means that the last activity doesn't have a name attribute and uses the node name ("forest6") instead
=> Reset current indent when parsing a new section of the skillmap

react-common/styles/profile/profile.css
fixes https://github.com/microsoft/pxt-arcade/issues/4401
I added some padding to the bottom of the email checkbox -- I didn't do anything with Delete/Sign Out since I think that's by design...?
looks like
=> Space out the email checkbox

webapp/src/monacoSnippets.ts
Our monaco snippets currently don't add indentations in between curly braces when they're dragged out for built-in language features. Functions (like `forever`) do add the indentation.
Changing the snippets for the built-in's to match.
=> Add indentation to all of our monaco snippets with curly braces

skillmap/src/App.tsx
we were always passing the user's locale to crowdin, even if it wasn't in the list of available locales for that target. this checks if there's a `force` flag or if the locale has been enabled, and if not it resets to the target's default locale. 
i tested `forcelang=ru`, as well as setting the browser locale to an enabled (chinese) and non-enabled (russian) locale and it seems to be working as expected (localizes for the first two cases, doesn't for the third), but let me know if there's any scenarios i missed!
=> Check skillmap user locale against target's available locales before setting

pxtlib/auth.ts
fixes https://github.com/microsoft/pxt-arcade/issues/4429
The issue is when we fetch the user preferences from the cloud, for new users they won't have any, and we don't pass in default preferences here. Adding default preferences
=> Use default preferences for users if none exist

skillmap/src/App.tsx
* Check skillmap user locale against target's available locales before setting
* Only persist user language for approved locales
=> [stable7.3] Check skillmap user locale against target's available locales before setting (#8619)

theme/common.less, theme/tutorial-sidebar.less, webapp/src/sidepanel.tsx
build: https://arcade.makecode.com/app/417ebce3e68c882a7e60fc089eddf4028974077b-ca22d467a8
=> Display Back and Next buttons on simulator tab in tutorial

gulpfile.js, localtypings/pxtblockly.d.ts, package.json, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/toolbox.tsx
- updates the build so we automatically bundle anything under the /@blockly node_modules folder as a plugin
- adds the keyboard nav plugin and integrates it into our accessible blocks experiment
=> Integrate blockly keyboard navigation for accessible blocks experiment

docfiles/tracking.html
In the simulator pxtConfig present and only contains simURL. Special casing for the same. This is spewing out "undefined" targets in the telemetry.
=> Fixing undefined target from Asphodel

localtypings/pxtarget.d.ts, localtypings/pxtblockly.d.ts, package.json, pxtblocks/blocklyloader.ts, theme/blockly-core.less, webapp/src/blocks.tsx
adds blockly's workspace search plugin! with some small tweaks to how rendering is handled
=> Add blockly workspace search plugin, hooked up to ctrl+F

pxtblocks/blocklylayout.ts, pxtblocks/fields/field_kind.ts
two bugs:
- docs/tutorial hint block snippets don't have the blockly css -> need to add the theme class
- spritekind dropdown always displayed "Player" when decompiling from blocks -> the fromXML flow changed so we need to initialize the spritekind variables differently
=> Fix Blockly CSS in docs snippet, SpriteKind decompilation

.github/workflows/codeql-analysis.yml, webapp/src/marked.tsx
- add ignore-path to skip tsWorker file, since we don't generate that one
- update marked regex to ignore case. this regex is cosmetic anyway, we'll dismiss the warning for it
=> Fix CodeQL scan errors in build

cli/cli.ts, cli/nodeutil.ts, gulpfile.js, skillmap/webpack.config.override.js
adds an alias for the react package so that react-common components and the general skillmap components use the same path for react (the path to pxt's node_modules rather than pxt/skillmap)
=> Customize webpack aliases for local skillmap build

webapp/src/components/ImageEditor/keyboardShortcuts.ts, webapp/src/components/ImageEditor/toolDefinitions.ts
On Friday we did an art livestream and it reminded me of two keyboard shortcuts I've been meaning to add to the image editor forever. These are both very self contained and should be safe to include in the patch release
1. Outline image (image editor only): **ctrl + shift + [1-9a-f]**
This one outlines the current sprite in the color indicated by the number. Outlining sprites is a super tedious process to do by hand
2. Replace color/tile: **ctrl + shift + r**
Replaces the currently selected background color/tile with the currently selected foreground color/tile. Another super tedious thing to do by hand, especially for larger images with a lot of colors
=> Adding a couple useful keyboard shortcuts to the image/tilemap editor

cli/cli.ts
Print label when refused for versioned build to diagnose build issues.
=> print label in build output

docs/writing-docs/tutorials.md
based on this feedback: https://forum.makecode.com/t/creating-a-tutorial-with-extension/11382/4
i put it under the main tutorial page, but am also down to move it under Resources (or duplicate the link under Resources?), happy to defer to what you guys think is best
=> Link snippets documentation from tutorial writing docs page

cli/buildengine.ts, cli/gdb.ts
RE: https://github.com/microsoft/pxt/issues/8650
@Amerlander try giving this branch a shot.
Also for the docker image, you can try using `pext/yotta:update-yotta3` instead of `pext/yotta:latest`. Let me know if this works locally for you, and I'll update our compile service.
=> Properly extract the name of the yotta target for the directory path

pxtlib/docsrender.ts
The braces on the tutorial doc headings aren't removed when served from azure. I suspect there is a difference in the behavior of `string.trim()`. Here is a suggested fix for `render.heading` to address this. An additional change is in there to better form the header id's as well.
Fixes #8670
=> Suggested fix for tutorial docs headings

webapp/src/components/ImageEditor/keyboardShortcuts.ts
Moving the outline shortcuts from ctrl+shift+[1-9A-F] to just be shift+[1-9A-F].
Also adds a few new shortcuts that we somehow missed the first time around:
1. **c** - select circle tool
2. **l** - select line tool
3. **\>** - increase cursor size
4. **<** - decrease cursor size
=> Don't use ctrl in image editor shortcuts

react-common/components/controls/Modal.tsx, react-common/styles/controls/Button.less, react-common/styles/controls/Modal.less, react-common/styles/react-common-variables.less, skillmap/src/components/UserProfile.tsx, theme/highcontrast.less, webapp/src/components/assetEditor/assetGallery.tsx, webapp/src/components/assetEditor/assetSidebar.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4544
fixes https://github.com/microsoft/pxt-arcade/issues/4549 
general CSS fixes for high contrast, updates the modal component to use a react portal so that we can render it at the root of the DOM
there's another issue with fontawesome icons not showing up in the webapp (looks like the font isn't included somehow?) which i'm still investigating
=> Fix asset editor modal high contrast, z-index

pxtblocks/blocklyloader.ts
fixes https://github.com/microsoft/pxt-arcade/issues/4545
restores the trash icon and red color of the toolbox as a block is dragged towards it
=> Update names of block drag and endDrag overrides

webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/toolDefinitions.ts
GROUP A
fixes https://github.com/microsoft/pxt-arcade/issues/4540
fixes https://github.com/microsoft/pxt-arcade/issues/4543
fixes https://github.com/microsoft/pxt-arcade/issues/4548
GROUP B
fixes https://github.com/microsoft/pxt-arcade/issues/4541
GROUP C
fixes https://github.com/microsoft/pxt-arcade/issues/4563
This PR fixes 3 things, and the first thing fixes all the bugs in GROUP A.
Group A's fix: The cursor wasn't registering anything when it moved off the canvas, so I allowed the cursor to be updated even if it was beyond the canvas.
Group B's fix: There's a bunch of control points and canvas surfaces being made when doing the tile editor within the tilemap editor. So I added some rules to only add control points if it's NOT the tilemap editor, and to pick the LAST main canvas …
=> Marquee resize fixes :)

localtypings/pxtarget.d.ts, pxtblocks/blocklyimporter.ts, pxtblocks/blocklyloader.ts, pxteditor/editor.ts, skillmap/src/components/ActivityActions.tsx, skillmap/src/components/AppModal.tsx, skillmap/src/components/SkillGraph.tsx, theme/highcontrast.less, theme/tutorial-sidebar.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/components/tutorial/TutorialCallout.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorial/TutorialHint.tsx, webapp/src/components/tutorial/TutorialResetCode.tsx, webapp/src/mergeProjects.ts, webapp/src/sidepanel.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4203
changes:
- add a TutorialCallout component that has the hint styling, so that we can reuse the bubble styles 
- adds the 'Replace my code' link and callout UI
- no longer deletes the template code from the header tutorialOptions; adds a 'templateLoaded' flag so that we can reload if necessary
- removes the keep code modal from the skillmap; always automatically carryover code
build: https://arcade.makecode.com/app/7cb86b6806a1f8147e41f0a59d907ca24aee0b15-694e1027e7--skillmap
=> Skillmap activities 'Keep Code' by default, add 'Replace my code' to tutorial pane

react-common/components/controls/Button.tsx, react-common/components/controls/FocusTrap.tsx, react-common/components/profile/BadgeInfo.tsx, react-common/components/profile/BadgeList.tsx, react-common/components/profile/Profile.tsx, react-common/components/profile/UserPane.tsx, react-common/components/types.d.ts, react-common/components/util.tsx, skillmap/src/components/GraphNode.tsx, skillmap/src/components/HeaderBar.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/components/SkillGraphContainer.tsx, skillmap/src/components/UserProfile.tsx, webapp/src/core.ts, webapp/src/coretsx.tsx
This pr does a few things:
1. Fixes aria labels, roles, hidden/not hidden, and descriptions throughout the skillmap. I did this based off testing with MacOS' VoiceOver, but we should also try this out on Windows with JAWS/NVDA
2. Fixes focus trapping on nested modals in the user profile
We should get rid of the showDialog stuff inside of react-common now that we're using the react portal thing for modals; just didn't want to do it in this pr
=> Better aria labels/descriptions and fix nested modal focus

cli/cli.ts
We should probably stop inlining all the fonts at some point, but the day before a release is not that day.
=> Fix fontawesome icons not showing up in the main webapp

pxtblocks/blocklyloader.ts
the function to close the workspace search also clears the blocks which unselects the selected input
=> Only close search on workspace click if search is open

theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialResetCode.tsx
- small CSS tweaks for tablet view
- keep the modal open until the workspace is visibly reloading
=> Keep Code CSS, closing behavior fixes

webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4586
eventually we might want to look at a cleaner way of hooking this into Blockly's setup, just patching the flow quickly for this release
=> Check flyout oldScale_ instead of current scale when rendering

pxtblocks/fields/field_toggle.ts
fixes https://github.com/microsoft/pxt-arcade/issues/4412
compute the correct sizing for the toggle!
=> Fix toggle sizing to use actual field width

package.json, pxtblocks/fields/field_toggle.ts, webapp/src/blocks.tsx, webapp/src/components/tutorial/TutorialCallout.tsx
- fix flyout scale cashing (#8693)
- fix 'Reset Code' x button (#8694)
- remove 'Inline/External Inputs' from block context menu (#8695) 
- fix toggle rendering (#8698)
=> [stable7.4] Cherry-pick blocks/blockly fixes

localtypings/pxtblockly.d.ts, pxtblocks/blocklyloader.ts
fixes https://github.com/microsoft/pxt-arcade/issues/4574
we're doing almost exactly the same thing as the default plugin, but centering the blocks instead of scrolling them just into view (except in the case of blocks taller or wider than the viewport, in which case we scroll the top/left side of that block into view)
=> Center offscreen blocks when doing workspace search

react-common/styles/profile/profile.less, react-common/styles/react-common-variables.less, theme/common.less
This PR duplicates the semantic ui screen size breakpoints in react common and adds new macros to make them easier to read. I only added helpers for the max-width media queries for each screen size; @shakao and I talked it over and we felt the best way to do media queries was to always cascade from large screen to small
I think going forward we want to standardize on this style (cascading from large to small) rather than our current jumble of media queries which are hard to read/interpret. In particular we want to move away from queries that specify both a min and max width like this:
```less
@media only screen and (min-width: @tabletBreakpoint) and (max-width: @largestTabletScreen) {
}
```
As we component-ize things, we'll slowly start removing the old ones (unless folks object). …
=> Add media query breakpoints

webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/4579
Blockly computes the field text height constants by dynamically measuring DOM elements. in the skillmap, we load the blocks workspace before the div is visible which causes these constants to be zero. this adds a `refreshTheme` call when the blocks div becomes visible so that we recompute these constants
=> Refresh Blockly theme when blocks div comes into view

webapp/src/marked.tsx
We use DOMPurify, so this rule shouldn't be an issue.
That being said, it makes me a little nervous that marked claims the "sanitize" feature is deprecated. I think that instead of passing DOMPurify to marked, we should implement our own wrapper that calls DOMPurify directly on the output HTML. I think that's likely what marked is doing internally anyhow...
=> disable lint rule in marked.tsx

package.json
fixes https://github.com/microsoft/pxt-arcade/issues/4651
=> Bump pxt-blockly to 4.0.9

package.json
almost everyone uses this patch anyway / it's long been stable and it fixes an issue in a transitive dep
=> bump browserify patch version to latest 16.2.* patch

pxtcompiler/emitter/emitter.ts, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/3050
Also fixes the breakpoints for for-of loops by adding a new one in the compiler that runs on each iteration when the initializer is assigned.
=> Adjust block breakpoints for all for-loops

webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/srceditor.tsx
First commit fixes https://github.com/microsoft/pxt-microbit/issues/2713
Second commit fixes https://github.com/microsoft/pxt-arcade/issues/3631
I _finally_ tracked down that second issue; we were resizing the blockly workspace when it wasn't visible in the DOM causing the view metrics to get messed up.
=> Remember block view

localtypings/projectheader.d.ts, webapp/src/workspace.ts
when we add the persistent share UI we can hook it up to this as well. open to other thoughts on the type of version timestamp, i'm using "temporary" and "persistent" because that's what we've been calling them but not sure if "onetime"/"persistent" or something would be better
=> Save generated ID to the project header when the user shares

react-common/components/controls/Button.tsx, react-common/components/controls/EditorToggle.tsx, react-common/components/controls/FocusList.tsx, react-common/components/controls/MenuBar.tsx, react-common/components/controls/MenuDropdown.tsx, react-common/styles/controls/EditorToggle.less, theme/image-editor/imageEditor.less, webapp/src/components/ImageFieldEditor.tsx
Add a secret accessibility menu to the editor toggle
This is sort of similar to the secret menu you get when you tab in the main editor. This is to work around our UI pattern of a toggle with a dropdown which doesn't really have a corresponding aria role. The secret menu takes the form of a tab list where all navigable items are present (including the ones buried in the dropdown). The menu is hidden until it receives focus; then the current tab takes over the toggle.
The tab list is navigable using the arrow keys, just like a menu bar. Unlike a menu bar, the first item to get focus when you tab in is always the active tab.
=> Add a secret accessibility menu to the editor toggle

react-common/components/controls/Input.tsx, react-common/components/controls/Textarea.tsx, react-common/components/share/GifInfo.tsx, react-common/components/share/GifRecorder.tsx, react-common/components/share/Share.tsx, react-common/components/share/ShareInfo.tsx, react-common/components/share/SocialButton.tsx, react-common/styles/controls/Modal.less, react-common/styles/react-common-variables.less, react-common/styles/react-common.less, react-common/styles/share/share.less, skillmap/src/App.css, webapp/src/app.tsx, webapp/src/share.tsx
react-common modal, new share components following Alex's fullscreen design for when screenshot/simulator is enabled and just the old modal design for when screenshots are disabled (microbit)
builds:
https://arcade.makecode.com/app/4fd34183d6d629192d9a075628999ec00a366090-b5a5921b34
https://makecode.microbit.org/app/548b0b0e67ceeaa611ad69936640cdd2ae58727f-93ebe2f317
i still need to clean up/reconnect the gif hotkeys but it's a little finicky because the gif encoder lives in the webapp (to avoid react-common dependencies) and all the gif state is in the new component, will do in a separate PR
=> New share modal components in react-common

skillmap/src/components/UserProfile.tsx
Spelling fix for form link text. Found by a Crowdin translator in:
https://crowdin.com/translate/makecode/10918/en-fr?filter=basic&value=3#1707519
=> Fix spelling in cloud save feedback link text

react-common/components/share/ShareInfo.tsx, webapp/src/share.tsx
I was going to do an all-up telemetry pass after the persistent stuff is merged in but since that is waiting on a backend release I figured I would add back the original share ticks
=> Restore share page tick events

webapp/src/scriptsearch.tsx
The name parameter just includes whatever the user typed, which can have a number of inconsistencies:
1. trailing slash
2. random uppercase/lowercase letters
3. may not include the repo owner if the extension is approved (e.g. pxt-color instead of jwunderl/pxt-color)
The slug is much more consistently formatted and should always be in the format owner/repo
=> Add slug to packages.github message to make queries easier

webapp/src/simulator.ts
When starting a run, we compute the complete list of dependencies resolved in the project; and pass it to the simulator.
This information is used by the Jacdac simulator to determine if an additional extension needs to be loaded.
=> compute recursive dependencies for run info

cli/cli.ts, pxtcompiler/simpledriver.ts, pxtlib/github.ts, pxtlib/package.ts, webapp/src/app.tsx, webapp/src/data.ts, webapp/src/db.ts, webapp/src/dialogs.tsx, webapp/src/package.ts, webapp/src/workspace.ts
Currently unbound github dependencies (no version tag specified) are bound to "master". The desired behavior should be to grab the latest release. There is also some caching involved which leads to some confusing situation where things might not work based on the state of the cache.
This project won't load in the current beta https://github.com/pelikhan/pxt-kitronik-air-quality/blob/master/jacdac/pxt.json if you happen to have an older version of jacdac cached.
=> Always try to resolve the latest release for github dependencies

localtypings/projectheader.d.ts, pxteditor/editor.ts, react-common/components/share/Share.tsx, react-common/components/share/ShareInfo.tsx, react-common/styles/share/share.less, webapp/src/app.tsx, webapp/src/cloud.ts, webapp/src/share.tsx, webapp/src/workspace.ts
plus some cleanup in `share.tsx` ! basically hooks the "Publish" button up to the new persistent share API when the user is logged in and adds a ellipsis menu with a "Create snapshot" option for generating the temporary link. the not-logged-in behavior should be exactly the same as before
requires https://github.com/microsoft/pxt-backend/pull/626 to be deployed
=> Hook logged in share up to persistent API, add dropdown for temporary share

react-common/components/share/ShareInfo.tsx, webapp/src/share.tsx
ah! dropped a commit, this fixes the generated URL to be relative to the target instead of `makecode.com`, and hides the share dropdown after publish (both only affect logged-in users)
=> Fix generated persistent URL, hide snapshot dropdown after publish

pxtblocks/blocklyloader.ts
Currently fixedInstance symbol are not sorted and based solely on import order. This PR adds basic `//% weight=...` sorting.
```
namespace yo {
//% fixedInstances
export class Foo {
///% block
bar() {
}
}
//% fixedInstance
export const aaa = new Foo()
//% fixedInstance weight=100
export const bbb = new Foo()
}
```
=> sort fixed instances drop down by weight

pxtsim/simdriver.ts
the jacdac sound level simulator uses the microphone; but it needs to be allowed on the iframe. The user still needs to give consent through the browser native permission dialog
=> allow simulator iframe to access microphone

webapp/src/workspace.ts
When creating a new project nested in a github repository (i.e. import url -> https://github.com/owner/project/jacdac), add the following features to the generated project
- dependency to root folder project (https://github.com/owner/repo/)
- better mangling of folder name and existing project name to generate nested project name
=> add root dependency, better naming when creating nested project

pxtlib/github.ts, webapp/src/package.ts, webapp/src/scriptsearch.tsx
When adding a new github project reference, resolve latest release using proxy instead of token. The token might not have access to reading this org (which happens for tokens with SAML access).
2 code paths:
=> use github proxy to resolve the latest version available

pxtblocks/fields/field_sound_effect.ts, pxtsim/sound/soundEmojiSynthesizer.ts, react-common/components/controls/DraggableGraph.tsx, react-common/styles/controls/DraggableGraph.less, react-common/styles/react-common-variables.less, webapp/src/components/soundEffectEditor/SoundEffectEditor.tsx
Includes the following changes:
1. Redraws the preview when sibling blocks change their values
2. Fixes some speaker-exploding clips that happen with the logarithmic interpolation
3. Adds the ability to trigger the sound by pressing a key on the keyboard. Any key works except those that are important to accessibility navigation
4. Redesigns the handles on the draggable graph to be circles:
=> More sound effect editor polish

pxtsim/simlib.ts, pxtsim/sound/soundexpression.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4541
Fixes https://github.com/microsoft/pxt-microbit/issues/4537
This restructures the audio context manager so that nodes that produce sound now all pass through a single gain node that can be used to mute/unmute sounds. Previously we just disconnected nodes whenever we received a mute request which made it tricky to restart sounds when the mute ends.
This also fixes a bug where long running soundexpressions weren't being cancelled properly when the sim restarted.
=> Better mute behavior and fix sound queuing

webapp/src/workspace.ts
Before starting the process of populating a sub-folder in a repo, make sure we have a github token.
=> Ensure github token is present before creating subproject

localtypings/pxtarget.d.ts, pxtblocks/blocklyloader.ts, webapp/src/blocks.tsx
Let blocks specify that they should be a the child of another block. This can sort of be thought of as a more generalized version of the flag that makes it so a block is within a "variable set" block. This is in support of the requested changes for 
https://github.com/microsoft/pxt-microbit/pull/4545
=> Add flag to make a block the child of another in the toolbox

webapp/src/filelist.tsx
Currently we only show a version number for top-level dependencies. This change shows all version numbers.
=> Display dependency version for dependent packages

localtypings/pxtarget.d.ts, pxtlib/browserutils.ts
Forces the editor to use the old tutorial layout. While the layout is the legacy one, the other new tutorial features like better markdown rendering still work fine. Here's a view of a tutorial in arcade that uses the fancy icon bullets:
=> Add app theme flag for using legacy tutorial layout

pxtblocks/fields/field_sound_effect.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4602
Not all of the CSS is included when we generate the snapshot. Specify the fill explicitly for this case.
=> Specify fill explicitly in svg to fix snapshot

pxtcompiler/emitter/decompiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4562
Instead of always decompiling with the block expanded, decompile with it collapsed. We can't know the exact number of arguments to show because we don't have any way of storing that information, unfortunately
=> collapse blocks with hidden arguments when decompiling

localtypings/pxtarget.d.ts, pxtlib/service.ts
Adding a new block attribute, `hiddenParts` that allows to filter out specific parts in the parts computation phase.
```
//% hideParts=servo <-- don't collect 'servo' parts
function someHighLevelfunctionUsingServo() {
...
// this triggers part 'servo'
pins.setServoValue(...)
}
```
In Jacdac, we use API that enable specific part but eventually the rendering is disabled. Downside of this flag is that it is pretty blunt and does not discriminate where the original part was used.
=> allow extension to hide parts

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtcompiler/emitter/emitter.ts, pxtlib/cpp.ts
When compiling for multiple hardware targets, we forget to collect the output files of other build platforms, like codal. So for micro:bit, we only see yotta.json and not codal.json.
This change walks the list of compile results and collects those values. (also yotta is set in codal for no good reason). The information in codal.json is used by pxt-microbit to determine if the compiled .hex file has Jacdac in the firmware.
=> Embed generated codal.json in compile results

webapp/src/app.tsx
At BETT Andrew asked for ability to create a new project with a hash so it can be embedded in a minecraft world to allow for a 'free coding' section sort of thing; I remembered we had these but right now it hits a path that creates a completely empty blocks project (i.e. no on start / default blocks: https://minecraft.makecode.com/#newproject); fixes that, and also just use preferred editor for javascript / create a parallel one for python to load up nicely.
=> make /#newproject create a non-empty project

pxtcompiler/emitter/service.ts, webapp/src/extensionsBrowser.tsx
This removes the fuzzy search from the client side. We need to do the fuzzy search in the server otherwise we will miss out on lot of packages and inconsistent results. 
This also removes pxt- prefix from names for the extensions to make it nicer as before.
Fixes: 
https://github.com/microsoft/pxt-microbit/issues/4568
https://github.com/microsoft/pxt-microbit/issues/4578
https://github.com/microsoft/pxt-microbit/issues/4596
=> Removing fuzzy search and fix the name

localtypings/pxtarget.d.ts, webapp/src/package.ts, webapp/src/toolbox.tsx, webapp/src/toolboxeditor.tsx
This removes the code logic to remove the extension from the toolbox. Basically, isTopLevelExtension returns false, so user doesn't see any option to delete the extension. 
I will do a separate check-in adding the logic to enable this feature later. Idea is to allow only top-level extension to be deleted and if there is any block is used, we won't allow for deletion.
=> Remove deletion of extension from the toolbox

webapp/src/components/tutorial/TutorialContainer.tsx
closes #8830
Added useEffect to clear the cache of snippets when the tutorial component unmounts.
=> clear snippet cache when user leaves tutorial

webapp/src/extensionsBrowser.tsx
The _Recommended_ extension tab shows extensions that are either already installed, or that should only be shown when the user searches for them.
* Only show `searchOnly` extensions when the user is searching for them
* Do not show extensions if they're already present in the current program
* Bring back bundled extension sorting so the servo and radio-broadcast have less precedence
https://microbit.staging.pxt.io/app/cd636c66f377800676b92dbea35b41e13c548206-1507b2a4d4#editor
Fixes microsoft/pxt-microbit/issues/4604
=> Hide search only and already installed extensions

localtypings/pxtarget.d.ts, theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/sidepanel.tsx
The simulator was broken in headless mode even though the UI worked fine.
The fix is just to make sure the div exists. This change puts it in the DOM, but it isn't visible anywhere.
=> Fix new tutorial in headless mode

pxtlib/soundeffect.ts, react-common/components/controls/DraggableGraph.tsx, react-common/styles/controls/DraggableGraph.less
Fixes https://github.com/microsoft/pxt-microbit/issues/4649
Fixes https://github.com/microsoft/pxt-microbit/issues/4634
The first issue was caused by the renderSoundPath code looping forever when it received out of range values. I just clamped the inputs (and also clamped the values in the draggable graph because it had a similar issue).
The second issue was caused by the browser trying to perform touch gestures when dragging the SVG. Fixed by setting the touch-action to none.
=> Sound effect editor fixes

webapp/src/monacoSnippets.ts
closes microsoft/pxt-microbit#4622
=> move extensions button to non-advanced categories

pxtblocks/blocklyloader.ts
I don't have a bug for this one but it came up while implementing data logger block changes; the block def became
```typescript
/**
* Log data to flash storage
* @param data Array of data to be logged to flash storage
*/
//% block="log data $dataA||$dataB $dataC $dataD"
//% blockId=dataloggerlogdata
//% dataA.shadow=dataloggercreatecolumnvalue
//% dataB.shadow=dataloggercreatecolumnvalue
//% dataC.shadow=dataloggercreatecolumnvalue
//% dataD.shadow=dataloggercreatecolumnvalue
//% inlineInputMode="inline"
//% group="micro:bit (V2)"
//% weight=100 help=datalogger/log-data
export function logData(
dataA: datalogger.ColumnValue,
dataB?: datalogger.ColumnValue,
dataC?: datalogger.ColumnValue,
dataD?: datalogger.ColumnValue
): void
```
and currently that makes it so all the parameters for …
=> allow nested params in optional (hidden) block parameters

pxtrunner/runner.ts, pxtsim/simdriver.ts, webapp/public/run.html
Adds support for relaying a request to display the sim without buttons by pulling it in from the request query string and configuring the sim iframe via its dataset.
=> Add support for hiding sim buttons

react-common/components/controls/Input.tsx, react-common/components/controls/Modal.tsx, react-common/styles/controls/Button.less, react-common/styles/controls/Input.less, theme/common.less, webapp/src/extensionsBrowser.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4646
Fixes https://github.com/microsoft/pxt-microbit/issues/4641
Fixes https://github.com/microsoft/pxt-microbit/issues/4639
Fixes https://github.com/microsoft/pxt-microbit/issues/4643
Fixes https://github.com/microsoft/pxt-microbit/issues/4638
Fixes https://github.com/microsoft/pxt-microbit/issues/4662
Fixes https://github.com/microsoft/pxt-microbit/issues/4647
Fixes https://github.com/microsoft/pxt-microbit/issues/4600
This PR does a few things:
1. Moves away from the search input component and uses the react-common input instead (fixes tabbing, search on blur)
2. Fixes the help icon button in the react-common so that it doesn't use any semantic classes
3. Tweaks CSS to make font size, spacing, borders, etc. more consistent
Before: …
=> Various extension browser styling fixes and use common input

webapp/src/data.ts, webapp/src/extensionsBrowser.tsx
When the extensions modal is first loaded it will show all extensions instead of just those that are recommended. Going back to the editor and then back to the extension modal will resolve the issue. We call `data.getDataWithStatus("target-config:");` when updating the preferred extensions. When the extensions deletion feature was in place, the toolbox would actually call `data.getDataWithStatus("target-config:");` first before the extension modal is loaded. The result of this call would eventually be cached by the virtual API system that we use well before the user can open the extension modal. By the time the extension modal was loaded, `getDataWithStatus` for the "target-config" would simply return the cached value. Though the getDataWithStatus is not marked as such it is an …
=> Fix Recommended Extensions Returning All Extensions

pxtsim/simdriver.ts
micro:bit beta currently can't open any projects because of https://github.com/microsoft/pxt/pull/8844/files
Turns out, runOptions can be undefined, which is news to me!
=> Fix crash when runoptions is not defined

pxtlib/github.ts
Use the slug instead of fullname to resolve upgrade rules, so that nested repoes are also always upgraded.
=> support upgrade rules for nested repoes

react-common/components/controls/Card.tsx, react-common/components/controls/LazyImage.tsx, react-common/components/extensions/ExtensionCard.tsx, react-common/styles/controls/Button.less, react-common/styles/controls/Card.less, react-common/styles/controls/LazyImage.less, react-common/styles/extensions/ExtensionCard.less, react-common/styles/react-common.less, theme/common.less, webapp/src/extensionsBrowser.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4635
Fixes https://github.com/microsoft/pxt-microbit/issues/4626
Adds two new generic components to react-common:
1. Card - A container for other components that acts like a button. Also includes support for those ribbon labels (most the css I just copied from semantic for those)
2. LazyImage - An image that is lazy loaded when it appears on screen. Also shows a spinner while it is loading.
This also uses those components in the extension browser to make things look much nicer. Changes include:
1. Text is no longer huge. Now follows the conventions for the rest of the webapp
2. Descriptions now get ellipsized after three lines
3. Extension cards and images now show loading spinners when they are loading and fade in when they finish …
=> Add Card and LazyImage to react-common and use in extension dialog

pxtsim/sound/soundexpression.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4660
There's no reason to ever reject this promise, so instead we just always resolve.
=> Don't crash if a sound expression gets cancelled

cli/cli.ts, localtypings/pxtarget.d.ts, pxtlib/github.ts, webapp/src/extensionsBrowser.tsx, webapp/src/scriptsearch.tsx
the current one expands out to be super big in target config / is a bit tedious to add to; this one you can get by with just adding a single line of `"{reposlug}": {}` most of the time and expanding on that when you want to add tags / upgrade rules / etc. Also collapses preferred extensions into field as an optional parameter.
As an aside, this makes it so in `allowedRepoLib` we require it to be in lowercase for the slug; if we want we can also handle that at runtime, but I think it's reasonable to leave as is (it was semi-inconsistent on casing matters in the past anyways) & at worst add a bit to the json file check part of the ci that throws if casing is off.
closes https://github.com/microsoft/pxt-microbit/issues/4675
=> new shape for allowed repos field in targetconfig

pxtblocks/blocklycustomeditor.ts, pxtblocks/fields/field_autocomplete.ts, pxtblocks/fields/field_utils.ts
Adding a blockly autocomplete field that draws values from other blocks of the same type. This field mostly extends from the field_textdropdown but I copied the rendering from field_string so that it looks like a normal string block.
In the field options on the API, you can specify an optional key that determines which fields are included in the list of potential values.
=> Adding an autocomplete field for datalogger

theme/common.less
The spacing on the cards / tab buttons in the extension page feels pretty off to me -- it's left aligned with some padding that ends up being ~~ 1/4 left 3/4 right or something like that, with the cards left aligned within that
current beta: 
having the cards be left aligned feels off, so just a quick centering of it
this change:
Changes spacing on the header bar with 'recommended' / 'in development' / 'import file' and the cards themselves so they're centered matching the rest of the elements in the view.
I put it up at https://makecode.microbit.org/app/ab3000df6e13e737ebefe89f0f8f1721610147d0-97a6a8050b#editor for a quick visual comparison in case anyone wants
=> center extension cards instead of left align

localtypings/pxtarget.d.ts, pxtblocks/composablemutations.ts, pxtlib/service.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4674
This adds two new comment attributes for use with expandable arg blocks:
1. **inlineInputModeLimit** - sets the number of expanded args at which the block switches from horizontal to vertical. The default is 4
2. **expandableArgumentBreaks** - sets the breakpoints for expandable args
=> Add a couple more options for expandable arg blocks

docs/csp.md
Modify the [CSP page](https://makecode.com/csp) for the new curriculum access initiative.
Comment:
The makecode.com site doesn't have a similar CSS to format link button text like in the targets, i.e..:  https://minecraft.makecode.com/setup/minecraft-windows10
Closes #8839
=> CSP page updates for curriculum access

webapp/src/extensionsBrowser.tsx
* Unselect tags when a search is begun so that it's clear we are not searching within the tags
https://user-images.githubusercontent.com/6496798/170350750-0ac771af-3896-4e55-87a9-3151acb5e720.mp4
Fixes microsoft/pxt-microbit/issues/4624
Fixes microsoft/pxt-microbit/issues/4595
build: https://microbit.staging.pxt.io/app/72d3350df53901d342c82efe3bd268d8085682f3-bde050c4f3#editor
=> Unselect tags when a search is begun

theme/common.less
chromium expands to full width but in this specific case firefox does not, so add an extra explicit setting fo rit
=> fix extensions view in firefox

webapp/src/extensionsBrowser.tsx
* Change the `In Development` tab to `Local`
Fixes microsoft/pxt-microbit/issues/4692
=> Change in development tab to local

webapp/src/githubbutton.tsx
This was buggin' me.
At issue: The `mobile hide` class names were being interpreted as icons.
Fixes https://github.com/microsoft/pxt-arcade/issues/4261
=> Fix status icon on github button

theme/blockly-core.less
fixes https://github.com/microsoft/pxt-microbit/issues/4499
This icon is now under a new font family, 'brand-icons' instead of 'Icons' so we override the font family for this element.
=> update font family for serial icon to brand-icons

pxtrunner/runner.ts, webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4291
This PR tweaks our print code behavior to only print the active code editor when printing a project.
Previously, it worked liked this:
1. If in blocks, print blocks, typescript, and python (even though python is not necessarily up to date)
2. If in typescript, print typescript and python (again, python might be invalid here)
3. If in python, print typescript and python
Now it works like this:
1. If in blocks, print blocks, 
2. If in typescript, print typescript
3. If in python, print python
If we want to bring back the behavior of also printing ts when in blocks, I can make that happen. Just let me know. @Jaqster FYI
=> Only print the active language when using print code

pxtpy/ast.ts, pxtpy/converter.ts, tests/pyconverter-test/baselines/class_extend_ts.ts, tests/pyconverter-test/baselines/class_namespace.ts, tests/pyconverter-test/baselines/class_scope.ts, tests/pyconverter-test/baselines/class_super.ts, tests/pyconverter-test/cases/class_extend_ts.py, tests/pyconverter-test/cases/class_namespace.py, tests/pyconverter-test/cases/class_scope.py, tests/pyconverter-test/cases/class_super.py, tests/pyconverter-test/testlib/classHandlerParameter.ts
This PR extends our Python class support. I still have a few more bugs to fix, but this adds a lot more functionality and fixes the more egregious bugs. Also this does *not* roundtrip.
Newly supported features include:
* Static methods and properties
* Floating statements in the class scope (i.e. not within a method or a constructor)
* Extending other Python classes
* Extending TypeScript classes
Intentionally unsupported features that we could conceivably support in the future:
* Calling protected properties/methods from a TypeScript class in a python class (right now the pyconverter uses the apiinfo from the language service which does not have access to those symbols; it's nontrivial to fix that)
* `__iter__`, `__str__`, and all the other "special" python methods
Also, for reference, …
=> Improved Python class support

pxtpy/converter.ts, tests/pyconverter-test/baselines/class_scope.ts, tests/pyconverter-test/baselines/class_static_local.ts, tests/pyconverter-test/cases/class_static_local.py
Fixes https://github.com/microsoft/pxt-microbit/issues/3456
Python's class semantics for static fields are a bit different than TypeScript's... Basically, if you try to access a field on a class instance and it is defined as a static field, the static field is returned. If that field is then assigned on the instance, then the assigned value is returned. Luckily, it's pretty easy to replicate that behavior using getters and setters in TypeScript!
This PR updates how we emit static fields so that classes like this:
```python
class Greeter:
greeting = ""
def __init__(self, message):
self.greeting = message
def greet(self):
return "Hello, " + self.greeting
```
now convert into TypeScript like this:
```typescript
class Greeter {
static greeting: string
private ___greeting_is_set: boolean …
```
=> Handle python class instance fields with the same name as static fields

pxtpy/converter.ts, tests/pyconverter-test/baselines/class_no_constructor.ts, tests/pyconverter-test/baselines/class_no_constructor_inherit_global.ts, tests/pyconverter-test/baselines/class_no_constructor_inherit_local.ts, tests/pyconverter-test/cases/class_no_constructor.py, tests/pyconverter-test/cases/class_no_constructor_inherit_global.py, tests/pyconverter-test/cases/class_no_constructor_inherit_local.py
Fixes https://github.com/microsoft/pxt-microbit/issues/4416
This PR fixes the conversion of python classes with no defined constructor by creating a dummy symbol with the correct parameters, type definitions, etc.
=> Fix conversion of python classes with no constructor

pxtlib/github.ts, webapp/src/app.tsx, webapp/src/dialogs.tsx, webapp/src/githubbutton.tsx
Here is a more scoped-down fix, supporting repo import from default branch.
Export to GitHub repo, and create new GitHub repo still go to master.
=> Support for GitHub import from default branch

pxtblocks/fields/field_autocomplete.ts, react-common/styles/extensions/ExtensionCard.less
Fixes https://github.com/microsoft/pxt-microbit/issues/4718
Fixes https://github.com/microsoft/pxt-microbit/issues/4719
Fixes two bugs:
1. A CSS bug where the border radius was being ignored in safari for extension cards
2. An iOS bug where the mobile prompt editor wasn't triggering a rerender for some reason
For bug number 2, I have no idea why the other mobile prompt editors are working. Doesn't seem like they should be! But in any case, this fixes it for autocomplete.
As a side note, the iOS autocomplete field does not provide autocomplete. I figured it was too much trouble to reimplement Blockly's prompt input. In any case, I think it's a separate issue from this one if we want to add it.
=> ios and safari microbit fixes

webapp/src/app.tsx, webapp/src/monacoSnippets.ts, webapp/src/toolboxeditor.tsx
fix https://github.com/microsoft/pxt-arcade/issues/2160
This ended up requiring a bit more context in the codebase / block definitions that expected so it ended up being that I fixed it while figuring out what wasn't working when the first portion lucas & I were looking at only half fixed it, and then lucas and I chatted about it.
It originally looked like the issue was here: https://github.com/microsoft/pxt/blob/master/webapp/src/toolboxeditor.tsx#L186, since the blocks toolbox has a button but the monaco functions toolbox category only has two fake blocks. However, the issue ended up being over in the monacoSnippets block definition, since those two were using the old blockly style function id for the two function snippets that show up in monaco which doesn't match the blockIds used in …
=> Add cache skip opt for tutorial info, fix tutorial functions in monaco

pxtpy/converter.ts, tests/pyconverter-test/baselines/class_ts_constructor.ts, tests/pyconverter-test/cases/class_ts_constructor.py, tests/pyconverter-test/testlib/classHandlerParameter.ts
Fixing a bug found by @alex-kulcsar!
When calling a constructor for a class defined in TypeScript, we were setting the python return type to void.
=> Don't use void type for ts constructors in python

gulpfile.js
Fixes https://github.com/microsoft/pxt-arcade/issues/4806
Run `npm install` instead of `npm ci --prefer-offline` for local development builds. The CI behavior should be unchanged
=> Fix skillmap npm install for local devs

react-common/components/controls/LazyImage.tsx, react-common/styles/controls/LazyImage.less
The icons for extensions can fail to load, this results in an infinite spinner a cards image.
Remove the spinner if the image fails to load and set the card's image as icon so the user knows the image didn't load
Build: https://microbit.staging.pxt.io/app/35e2f8faee7160c6a48f9bb5c3a1ce2a9b19ee3f-bbe5f6948a#editor
- Search for "blue" in the search bar and note how the `bluetooth-temperature-sensor` extension has an image icon instead of an image
Fixes microsoft/pxt-microbit/issues/4570
If there is a more common way that we indicate that a resource has failed to load, please let me know.
=> Use an image icon when extension card image fails to load

pxtlib/browserutils.ts, webapp/src/app.tsx
Fix for https://github.com/microsoft/pxt-microbit/issues/4694
While a deployment is on-going, do not automatically disconnect when page visibilty changes.
Testing:
Keep 2 makecode tab open, with two different program (using different C++ to trigger full flash). Start download, switch tab, wait until download is completed, tab releases USB
=> don't disconnect when deploying

react-common/components/controls/Input.tsx, webapp/src/components/soundEffectEditor/SoundControls.tsx
When searching for extensions you can no longer press the space bar to search multiple terms at the same time.
Change react-common Input to no longer treat the space button as an enter button by default. Now you have to specify if you want that behavior by setting the `treatSpaceAsEnter` property.
Build: https://microbit.staging.pxt.io/app/d6f9b2143795af11f5046326f410a0f5a9dc4598-667bbfa881#editor
- Press space in the extension search bar and see that the search doesn't begin until you click away or press enter
- Press space in the duration field of sound editor, see that it is not allowed
Fixes microsoft/pxt-microbit/issues/4717
=> Don't treat space as enter by default on an input field

pxteditor/editor.ts, webapp/src/serial.tsx
fix bug that blocked testing today; I must have been a bit behind master and hit a race condition that wasn't there? It started happening locally as well once I pulled & gulped.
This change makes it *much* more explicit when setting view ~
=> more explicitly set view state to fix race

react-common/components/extensions/ExtensionCard.tsx, react-common/styles/extensions/ExtensionCard.less, webapp/src/extensionsBrowser.tsx
The user-created-extension disclaimer is not being shown for unofficial extensions.
Bring back the disclaimer for non-bundled user-created extensions.
Build: https://microbit.staging.pxt.io/app/df47ae067c7d3d76e790488fd9f9c95489693025-767f2bc083
- See that the disclaimer is not present for approved extensions
- Search `blue` in the search bar and notice the bundled `bluetooth` extension does not have a disclaimer
- Search for a user extension such as `https://github.com/aznhassan/test-extension-three` and notice the disclaimer
Fixes microsoft/pxt-microbit/issues/4747
=> Show disclaimer for user-provided-extensions

pxtlib/package.ts, pxtlib/semver.ts
As we load packages and resolve github references, always try to upgrade the referenced version to avoid version clashes. This codepath only happens on github project references
For example, we can have a project with a dependency A, B, A/C where
A is a repo, version v2
A/C is a subproject in repo A
B references A/C#v1
With this program, A gets loaded first and locks to v2; then we need to make sure to all future loaded references of A or A/C are upgraded on v2.
To test this:
- create new project
- add jacdac, which should be something like v1.8.xx
- add https://github.com/pelikhan/pxt-kitronik-stopbit/tree/master/jacdac
- verify that jacdac-traffic-light is now v1.8.xx instead of v0.10.40
=> resolve and upgrade github versions as they are loaded

webapp/src/serial.tsx
re: https://forum.makecode.com/t/how-to-stop-console-from-aggregating-data-being-printed-to-it/13732, this pr would stop logs from getting grouped. This makes it more cli javascript like (node / etc) & matches behavior you would see in any java / python cli, but doesn't match webdev javascript style consoles.
(I have other things I need to finish so just putting this up and letting others decide when / if to merge this :) )
=> don't batch logs in serial view

docs/csp.md
A couple of changes to the CSP page FAQ:
Closes #8902
=> Add another faq entry to the CSP page

pxtlib/github.ts, pxtlib/package.ts
stringifyRepo changes the casing of the repo, which then surfaces deeper bug around equality of repo dependencies in the load path. This is a minor fix that makes sure the casing of the slug is not modified.
=> don't change casing when upgrading version

react-common/styles/controls/Modal.less
fix https://github.com/microsoft/pxt-microbit/issues/4756
(ignore the arrow button to the left of the qr code, that was another button I was testing out)
I haven't poked around but there's probably a decent number of modals this will benefit, 50% of mobile phones is way too tiny
=> make default modal take up more of screen on mobile

pxtlib/service.ts, webapp/src/extensionsBrowser.tsx
fix https://github.com/microsoft/pxt-microbit/issues/4752#issuecomment-1157016629
fix https://github.com/microsoft/pxt-microbit/issues/4587
funny enough this fails locally since our cli seems to miss the `/libs/pkg/docs/` path, but the live site verison of that page should be fine
=> make learn more for builtin point to /reference/{pkg}

pxtblocks/blocklylayout.ts, pxtblocks/fields/field_melodySandbox.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4753
Fixes https://github.com/microsoft/pxt-microbit/issues/4739
Fix the css that broke from the blockly update and explicitly set the color of the melody editor fields
=> Blockly snapshot fixes

pxtsim/runtime.ts, pxtsim/sound/soundexpression.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4736
Fixes https://github.com/microsoft/pxt-microbit/issues/4735
This does two things:
1. Clears the sound queue whenever the simulator gets killed
2. Changes the "in background" behavior to only queue a single sound, just like on hardware
=> Fixes for sound queue

react-common/components/share/ShareInfo.tsx, react-common/styles/react-common-breakpoints.less, react-common/styles/share/share.less
fix https://github.com/microsoft/pxt-microbit/issues/4760
@riknoll I added a new size to react-common-breakpoints for this; largestMobileScreen is actually pretty big to the point that it hits lots of tablets / not full screen monitors. 420 px is just above the biggest normal portrait screens (e.g. my samsung big phone is 412px) and I feel like the portrait size is probably what we intend most of the time we add 'phone size screen optimizations' since landscape can be pretty wide / fit most things
=> hide embed opt in share dialog on mobile devices

webapp/src/serial.tsx, webapp/src/serialindicator.tsx
As discussed, use data instead of console for the button:
and remove toggle / csv view when on hw as we don't currently have that option / it would be misleading to be in hw view but see sim data
=> Show data and dont show csv on hw

docfiles/domains-template.html
Domain used by Jacdac to host simulator.
- needs to be ported into servicing branch of microbit as well
=> add microsoft.github.io to domains

pxtcompiler/emitter/snippets.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/4719
Fixes https://github.com/microsoft/pxt-arcade/issues/4722
In addition to those two bugs, this also fixes two more bugs I discovered while testing:
1. When creating a tilemap from the asset editor, we were always adding "1" to the end of the asset name
2. When creating a tilemap from within the monaco editor, we were ignoring the name the user typed and instead always using the name "level#"
That's right, it's one of those classic "one bug fixed for every line changed" prs.
Sorry for the delay @bmarslandCN!
=> Various monaco tilemap fixes

webapp/src/app.tsx, webapp/src/scriptmanager.tsx
The mirror side of https://github.com/microsoft/pxt/pull/8936
Extract and import a zip file full of projects! There are two dialogs: an initial confirm dialog and a progress dialog once the import starts. See the full experience in the gif below
My test zip had 31 arcade projects
=> Add ability to import zip files of projects

theme/serial.less, webapp/src/serial.tsx
Cherry pick two csv view fixes over:
* Have last header stick to the top to avoid losing context on rows https://github.com/microsoft/pxt/pull/8924
* View latest button when you stop tracking the latest data & new data comes in https://github.com/microsoft/pxt/pull/8929
=> [stable8.0] csv view cherry picks

pxteditor/monaco-fields/field_soundEffect.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4732
Note that the regex is dumb and weird things might happen if you use parentheses inside the arguments of the sound you're trying to edit.
=> Adding monaco field editor for sound effects

pxteditor/monaco-fields/field_soundEffect.ts, pxteditor/monaco-fields/monacoFieldEditor.ts, theme/common.less, webapp/src/blocklyFieldView.tsx, webapp/src/monacoFieldEditorHost.ts
Re: conversation with @jwunderl in https://github.com/microsoft/pxt/pull/8941
This adds an optional function to validate/adjust monaco field editor ranges so that we don't have to cram more complicated logic into the regex (which becomes a performance concern). The validate range function here just counts parentheses and handles multiline, so a snippet like this:
```ts
music.playSoundEffect(
music.createSoundEffect(
WaveShape.Sine,
1,
input.acceleration(Dimension.X),
0,
0,
500,
SoundExpressionEffect.None,
InterpolationCurve.Linear
),
SoundExpressionPlayMode.UntilDone
);
```
...can now be edited. Note that the acceleration call in this example will be removed when you close the editor (better than the old behavior of breaking your program, though!)
I also accidentally left some css out of …
=> Add validate range for monaco field editors and some missing css

pxtsim/simdriver.ts
cross domain autofocus is annoying https://bugs.chromium.org/p/chromium/issues/detail?id=998450&q=autofocus%20iframe&can=2
Explicitly pass focus over after the simulator has loaded to make sure the sim can actually take the focus
=> explicitly give focus to iframe to get past cross domain security focus issues

webapp/src/app.tsx, webapp/src/package.ts
A null file entry can be added to pxt.json when a perfect storm of timing events occurs. I don't have a precise repro, but it tends to happen when code changes pending save start to get saved while assets.json is the current editor file.
This is a conservative change, adding guards to:
- ensure we don't try to write to an undefined file
- only save a "virtual file" if we can generate a filename for it
=> Fix for null file entry in pxt.json

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/comments.blocks, tests/decompile-test/cases/comments.ts
This fix addresses GitHub issue # 3169 in pxt-arcade:
https://github.com/microsoft/pxt-arcade/issues/3169
- Moves `getComments()` from `getStatementBlock()` private scope, updates signature.
- Renames `getComments()` to `getNodeComments()`, so to not be confused with `getComments()` in `emitter.ts`, which will also show up in `pxtworker.js`.
- Attaches comment to statement node for auto-declared variable.
- Update variable naming and commenting.
- Add test for comments associated with 'false' and "0" auto-declared variables
=> Fix commenting for specific auto-declared variables.

cli/buildengine.ts, cli/cli.ts, cli/nodeutil.ts, docs/cli/checkdocs.md
Add option to throw in a `.checkdocs-ignore` file to suppress checkdocs for the folder; we can ignore checkdocs in pxtarget but that's pretty aggressive. We have a few other cases where we do this anyways (`.ignorelargefiles`, `.crowdin-ignore`)
Also did a minor refactor on `nodeutil.allFiles` parameters because the parameter list was getting too long and we only ever end up passing one or two (and if you're not careful you can e.g. pass null for maxDepth when you intend to pass a file marker or something)
This would be used for https://github.com/microsoft/pxt-arcade/pull/4820 as that has a minor typescript api change that would need a docs fix post release (follow -> cameraFollow)
=> Option to ignore checkdocs in folder

react-common/components/controls/Input.tsx, react-common/components/share/ShareInfo.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2184
The new clipboard API isn't supported in all older versions of chrome. Luckily, the old deprecated copy api does work.
=> Fix share copy in chrome

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/multiple_events.blocks, tests/decompile-test/baselines/multiple_events_block_handler_key.blocks, tests/decompile-test/cases/multiple_events.ts, tests/decompile-test/cases/multiple_events_block_handler_key.ts, tests/decompile-test/cases/testBlocks/basic.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/860
I kinda can't believe i never implemented this before...
This makes it so that the decompiler no longer allows for multiple events with the same arguments to be decompiled. Previously we would decompile them and the blockly compiler would then disable them since you can't have multiple events with the same args in blocks. Now one of the offending calls will end up as a grey block
=> Don't allow multiple events with the same arguments to be decompiled

pxtlib/browserutils.ts
fix fb half of https://github.com/microsoft/pxt-minecraft/issues/2178 -- also have to set socialOptions in minecrafts pxtarget for twitter as that's failing here https://github.com/microsoft/pxt/blob/fixSocialShareMinecraft/react-common/components/share/SocialButton.tsx#L24 due to socialOptions being undefined
I took a look and it appears that there are a few options in window.open features that are allowlisted (e.g. noreferrer / noopener), but as soon as there is anything in there that is not allowlisted the window gets rejected -- in this case none of the parameters listed for pop up window are allowlisted
also remove url from the failure tick event -- it looks like the popupwindow is only used for these social share anyways, and those contain the share link as a query param
=> Fix social share minecraft

webapp/src/codecard.tsx
fix https://github.com/microsoft/pxt-minecraft/issues/2172
turns out the reason it worked on my machine (at first) & not abhijiths was because it worked in widescreen but not narrow screens :) it looks like at some point there was the idea to make it so we could have a codecard that opens in sidedocs for pcs & a new tab for others, but every other location I saw codecard being used passes the `onClick` so it was just mostly dead code that causes us to open a new tab only for this beta experiment. For what it's worth I don't think we would want that behavior anyways as you'd e.g. end up with mixed results in a classroom with half the class having side docs and half the class having a new tab which feels bad.
For what it's worth testing this is kinda annoying as the beta codecard only shows …
=> make it so beta experiment always opens in place

theme/tutorial-sidebar.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/2169
Really, it works much better if you just put the blocks in the hint since that isn't constrained by the width of the sidebar
=> Add scrollbar for when blocks overflow in tutorial sidebar

theme/serial.less, webapp/src/serial.tsx
Fix bug richard noticed, when you scroll up and the log is full so it starts throwing away rows it was changing the 'even-ness' of the rows -- so as you read old data it would flash gray/white. Instead just use a class
=> when log is full and you scroll up, don't change bkgd color of cells

webapp/src/immersivereader.tsx
we need to hit a live endpoint to get an imm reader token, not the local serve. these two calls were changed from requestAsync to privateGetAsync a while back (https://github.com/microsoft/pxt/pull/8259/files#diff-1fde1e59e8adfc854cf59f6d572551b0828f3f5a5c9d08a35b8d854006eacf87L194) when adding error messages for offline, but that has a slight change in behavior as this was hitting /immreader insteader of /api/immreader here https://github.com/microsoft/pxt/blob/makeImmReaderHitLiveEndpoint/pxtlib/emitter/cloud.ts#L74 because its static.
This sets 'forceLiveEndpoint' to true for both api requests so they know to go directly to our backend instead of local serve
=> fix imm reader on electron

package.json
picks up https://github.com/microsoft/pxt-blockly/pull/406 and https://github.com/microsoft/pxt-blockly/pull/401 -- I'm guessing 401 was just pulled directly to stable branches for micro:bit / arcade releases?
=> pick up blockly changes v4.0.12->v4.0.15

pxtblocks/blocklyloader.ts
Cherry picking the duplicate input fix from https://github.com/microsoft/pxt/commit/292ca0792104688d725cd3cd7506f5de3db23fd3
To fix an arcade bug introduced by the patch release that I noticed during stream.
=> Cherry pick duplicate blockly input fix

cli/gdb.ts
The `ioreg` doesn't seem to work for me anymore.
=> fix BMP debugger detection on macOS

pxtlib/github.ts
When checking whether a repo is approved / banned, check both fullname (`microsoft/pxt-jacdac/accelerometer`) and the slug (`microsoft/pxt-jacdac`).
In particular this is re: https://github.com/microsoft/pxt-minecraft/issues/2226, as when we load individual tutorials from repos the fullName is actually up to the full file (e.g. `mojang/educationcontent/CodingWithMinecraft/unit_2/lesson_A`), so they would have to be approved one by one (which also wouldn't really make sense, as we would probably try to fetch the pxt.json under lesson_A directory even though thats a md file [here](https://github.com/Mojang/EducationContent/blob/master/CodingWithMinecraft/unit_2/lesson_A.md)) .
I suppose could also fix specifically in the tutorial load path by changing how we store the filename vs the …
=> when checking repo approved / banned, check slug in addition to fullname

docs/github-teacher-verification.md
I'm assuming that this is the "Step 2" in question. There's another "Step 2" in the account verification section. I'd have to try and make another GitHub account to test this.
Closes #8974
=> Remove step 2 of github teacher signup

pxtblocks/fields/field_sound_effect.ts, pxteditor/monaco-fields/field_soundEffect.ts, pxtlib/soundeffect.ts, pxtsim/simlib.ts, webapp/src/blocklyFieldView.tsx, webapp/src/components/soundEffectEditor/SoundEffectEditor.tsx, webapp/src/components/soundEffectEditor/SoundGallery.tsx, webapp/src/components/soundEffectEditor/soundUtil.ts
This PR adds support for the mixer synth engine that @mmoskal wrote in pxt-common-packages to the sound effect editor.
In order to mimic the interpolation curves and the vibrato/tremolo effects, each sound is compiled to 20 synth instructions. Each instruction is 12 bytes long, so the end result is 240 bytes per sound which is roughly equivalent to a 16 x 32 image in arcade. If that ends up being too much (though I don't think it will) we can tweak the number of instructions.
As part of this I also rewrote the sim implementation of the synth because the old one wasn't so great at playing multiple short instructions in quick succession.
Here's a test build of arcade with the changes:
https://arcade.makecode.com/app/37e2d1ae2e70da5c0e4010586849d9ceca186a0f-895a1917a8
Please note that the …
=> Add support for mixer synth engine to sound effect editor

theme/home.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/2229
This isn't specific to minecraft; also happens in arcade.
=> Fix codecard button size on thin screens

pxtcompiler/emitter/snippets.ts, pxtlib/service.ts, tests/language-service/snippet_cases/emitAsConstant.py, tests/language-service/snippet_cases/emitAsConstant.ts, tests/language-service/test-package/minecraft.ts, tests/language-service/test-package/pxt.json
Fixes https://github.com/microsoft/pxt-minecraft/issues/2170
Does what the title says!
As a fun aside: when I finished fixing this I implemented an entire test runner for testing snippets from the language service only to realize that I had already done that two years ago
=> Fix python snippet for enums with emitAsConstant set to true

theme/tutorial-sidebar.less
Instead make them scroll if they are too wide to fit in the tutorial pane
Fixes https://github.com/microsoft/pxt-minecraft/issues/2228
=> Never word wrap tutorial code snippets

webapp/src/components/ImageEditor/ImageCanvas.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/4897
The Chrome issue seems to be specific to putImageData. Drawing the images using fill rect works fine
=> workaround for chrome canvas bug

pxtcompiler/emitter/emitter.ts, pxteditor/editor.ts, pxtlib/cmds.ts, pxtlib/emitter/assembler.ts, pxtlib/package.ts, webapp/src/app.tsx, webapp/src/cmds.ts
This is a workaround for https://github.com/microsoft/pxt-microbit/issues/4788
It doesn't fix the code size issues, but does allow multivariant editors to show a dialog when this happens and optionally recompile with fewer variants selected.
In other words: it lets us add a "download for V2 only" option to unblock micro:bit v2 users
Here is a gif showing how this works. Please note that the dialog is **very much not final** (that will be a different PR)
=> Add an editor extension for 'program too large' errors

pxtblocks/fields/field_gridpicker.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4815
My guess is that this function was removed in one of the Blockly updates. I don't know what it does, but the field editor seems to work fine without it. Its functionality was probably moved somewhere else in Blockly.
=> Fix gridpicker field editor in rtl languages

webapp/src/compiler.ts
I was playing in arcade/beta and hit https://github.com/microsoft/pxt-minecraft/issues/2209 (only pxt-core search results when doing block search) again even with the previous fix that made it so it only occurred when first loading a new project -- arcade's initial compile is *just* slow enough that it is pretty feasible to hit there. This should fix that case.
build with it: https://arcade.makecode.com/app/645365a6d33945b4c0d36686efe9d9db77508a67-3da56e082f#editor
strictly speaking the change in `apiSearchAsync` is enough to cover it, but the change in `typecheckAsync` feels like a good thing just to make sure~
closes  https://github.com/microsoft/pxt-minecraft/issues/2209
=> wait for first type check before completing api search

theme/asset-editor.less
Specify flex properties for the common-button-flex contained within asset-editor-create-button, ensuring the content of the button (image & text) will wrap as needed to fit within the shape of the button.
Fixes https://github.com/microsoft/pxt-arcade/issues/4839
Previously, these buttons relied on white-space wrapping to get this behavior, but that has since been disabled and the flex approach is hopefully more robust.
Before fix:
After fix:
=> Fix Asset Create Button Formatting

docs/js/profiling.md, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/backthumb.ts, pxtcompiler/emitter/hexfile.ts, pxtcompiler/emitter/thumb.ts, pxtlib/emitter/assembler.ts
When you add `?compiler=size` (or `PXT_COMPILE_SWITCHES=size` in command line) this will generate a comment similar to the following in the generated `binary.asm` file:
```
; Code size:
;
;   5280 _hexlit54 [_hexlit54]
;        by main.ts(1,1): <main> [_main___P1]
;   3628 game/physics.ts(349,5): ArcadePhysicsEngine.tilemapCollisions [ArcadePhysicsEngine_tilemapCollisions__P1078]
;        by game/physics.ts(113,5): ArcadePhysicsEngine.move [ArcadePhysicsEngine_move__P1075]
;        by ArcadePhysicsEngine__C1063_VT [ArcadePhysicsEngine__C1063_VT]
;        by game/physics.ts(624,5): ArcadePhysicsEngine.moveSprite [ArcadePhysicsEngine_moveSprite__P1081]
;   3110 mixer---rp2040/melody.ts(349,9): music.MelodyPlayer.play [music_MelodyPlayer_play__P475]
;        by music_MelodyPlayer__C472_VT …
```
=> Add dependency info when enabling ?compiler=size

webapp/src/compiler.ts
When you hit the download button, we generate an asm file and stick it in the file explorer. It's not super useful though because the next autorun immediately deletes it.
This is a tweak to the earlier fix that tried to keep around the asm files but didn't work for multivariants which use different filenames (e.g. mbdal-binary.asm)
=> Fix binary assembly file not sticking around in multivariant targets

webapp/src/app.tsx
When Python is set as the preferred editor for a tutorial, we still end up loading the blocks editor because main.py doesn't exist at the time we try to load it.
To address this issue, if the preferred file does not exist, we can create it rather than falling back on the blocks file. We also have to update config to ensure the python files are included in pxt.json. Without that, the python script won't actually be included when the app runs, so it doesn't do anything. This was also missing inside loadTutorialTemplateCodeAsync, so I've added it there, too.
Fixes https://github.com/microsoft/pxt-arcade/issues/4892
=> Fix Python Preferred Editor for Tutorials

skillmap/package-lock.json, theme/common.less
When clicking on extensions in the development environment of micro:bit, the extensions header was not the correct color. This code change fixed this issue and it was verified that the right color was maintained across pxt.
Closes https://github.com/microsoft/pxt-arcade/issues/4782
=> Fixed color theming in extension dialog.

pxteditor/experiments.ts, react-common/components/palette/ColorPickerField.tsx, react-common/components/palette/PaletteEditor.tsx, react-common/components/palette/PalettePicker.tsx, react-common/components/palette/PaletteSwatch.tsx, react-common/components/palette/Palettes.ts, react-common/styles/palette/ColorPickerField.less, react-common/styles/palette/PalettePicker.less, react-common/styles/palette/PaletteSwatch.less, react-common/styles/palette/palette.less, react-common/styles/react-common.less, theme/common.less, webapp/src/container.tsx, webapp/src/pxtjson.tsx
Adds an experiment for use in pxt-arcade that lets you change your project's color palette! 
Obviously this has gone through zero design iterations, so don't expect it to turn into anything other than an experiment anytime soon. Most of the palettes came from [lospec.com](https://lospec.com/palette-list) via @jwunderl's pxt-color extension.
I went through and reordered the colors so that they are somewhat close to our default palette. This makes it so that the gallery sprites are still somewhat usable.
=> Add palette picker/editor experiment

theme/common.less
Fixes https://github.com/microsoft/pxt-arcade/issues/4816
The custom width being applied when the scrollbar turns invisible differs from the visible scrollbar's width. As a result, when we show/hide the scrollbar, the size of the simulator changes. This opens an edge case where the change in size from adding/removing the scrollbar triggers a change in whether or not the scrollbar is needed, so we end up looping, adding and removing the scrollbar continuously.
By removing this line from the invisible scrollbar CSS, the width should remain unchanged whether the scrollbar is visible or invisible, so there's no size change when the bar is shown or hidden.
The comment on this line indicates that it was used to fix a "sim breakpoint" issue. We aren't certain what this issue was, but I've toyed …
=> Remove Custom Width for Invisible Scrollbar

theme/tutorial-sidebar.less
fix https://github.com/microsoft/pxt-arcade/issues/4920, we have a ` ```block` snippet that behaves similarly to ` ```blocks` that wasn't included in this rule
=> add scrollbar for lang-block snippets as well

pxtpy/ast.ts, pxtpy/converter.ts, tests/pyconverter-test/baselines/destructuring.ts, tests/pyconverter-test/cases/destructuring.py
Fixes https://github.com/microsoft/pxt-microbit/issues/4826
When a variable is already declared, we can't convert python destructuring into the TS syntax. Instead, fall back to a series of assigments. for example,
```python
g = 0
def initValue():
global g
g, _ = 1, 2
```
becomes
```typescript
let g = 0
function initValue() {
let __tempvar2 = [1, 2]
g = __tempvar2[0]
let _ = __tempvar2[1]
}
```
=> Fix Python destructuring for global/nonlocal variables

cli/cli.ts
Fixes the local build for codal in pxt-microbit
=> Don't override the compile variant when setting up the app target

pxtblocks/blocklyimporter.ts, pxtblocks/blocklylayout.ts, webapp/src/monaco.tsx
This fixes a pretty bad bug that i found yesterday while helping some folks on the forum. To repro the bug:
1. Create a new project and make a sprite
2. Add an extension to the project
3. Drag out a block from the extension so that it's disabled (not attached to anything)
4. Switch to JavaScript and remove the extension using the file explorer
5. Switch back to blocks and see that your project is broken and all assets are deleted
The issue had to do with disabled blocks specifically. When we decompile, the process looks something like this:
1. First we check to see if we have an existing workspace lying around from the last time the project was in blocks
2. If we do, we compile that workspace to TypeScript
3. If the compiled TypeScript is the same as the current content of the text …
=> Check to make sure blocks still exist before decompiling

pxtlib/blocks.ts
Because of how the symbols are rendered, it is hard to tell the difference between a plus sign and the division symbol in the math blocks. This PR changes the classic division symbol to a '/' so there is a noticeable difference between addition and division. 
**Before:**
**After:**
Closes: https://github.com/microsoft/pxt/issues/7907
=> Changed division symbol to '/' for math blocks.

docs/blog/minecraft/2022-release.md
Sadly, the **Block Detection** section is removed since the API demonstrated isn't public.
Closes #9001
=> Remove 'Block Detection' from Minecraft blog post

webapp/src/blocks.tsx
Before we load a workspace from xml, clean out any deletable flags that exist in the XML. There are currently no scenarios where we rely on this deletable flag, and it can be persisted erroneously with value "false" if the app closes unexpectedly while in debug mode, which then prevents users from being able to delete/duplicate blocks in their workspace.
This approach should also fix any existing projects that have gotten into that non-deletable state.
Fixes https://github.com/microsoft/pxt-arcade/issues/4906
=> Clean Deletable Flags Before Loading a Workspace

docs/writing-docs/tutorials/basics.md, localtypings/pxtarget.d.ts, pxtblocks/fields/field_kind.ts, pxtcompiler/emitter/decompiler.ts, pxtcompiler/emitter/driver.ts, pxtlib/tutorial.ts, pxtrunner/renderer.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/compiler.ts
`blockconfig` sections give tutorials the ability to reconfigure blocks in the toolbox, giving them different default parameters. Example:
**When player overlaps food**
This is a "local" block config, applies to the tutorial step in which it appears
````
```blockconfig.local
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
})
```
````
Resulting block in toolbox
**Multiple blocks can be configured in one blockconfig**
This is a "global" block config, and applies to the entire tutorial.
````
```blockconfig.global
randint(-10, 10)
let mySprite: Sprite = null
mySprite = sprites.create(img``, SpriteKind.Enemy)
mySprite.setPosition(randint(0, scene.screenWidth()), randint(0, scene.screenHeight()))
```
````
**Handler blocks can contain code snippets**
```` …
```
=> Add support for `blockconfig` tutorial sections

webapp/src/app.tsx
Conversion to switch statement makes this change look bigger than it is. All I did was remove the line `const variables_set = block.children[0];` (line 1835). I don't recall why I had to navigate into the children like that. Maybe we'll rediscover it in a future edge case. I expect some of these to pop up initially, and we'll have to play whack-a-mole(tm) for a while.
I do wonder if there's a better way to extract the value node from a variables_set/change dom heirarchy. Do we have an xml utility for this?
=> block config: Fix for variables_set parse issue

libs/pxt-common/pxt-helpers.ts, pxtblocks/blocklyloader.ts
In the Guitar Project for micro:bit, a link to the docs page for Math.abs was broken. Thanks to the edits suggested in the attached issue, the link is no longer broken.
Quick video demonstrating the fix: https://user-images.githubusercontent.com/49178322/186541056-5f59059c-70b3-4094-90e6-64ca0f4368f1.mp4
Closes: https://github.com/microsoft/pxt/issues/8142
**Updates:**
>A block now displays on the `abs` card because, as @jwunderl suggested, the real fix lied within code. When blocks are initialized, the function `mkCard()` is run for those that have the `codeCard` field in their object definition. `mkCard()` pre-pends a block's defined 'help' URL with `/reference` so the redirect takes the user to the specified block's docs page. 
This fix adds the `codeCard` field to the special case …
=> Fixes the broken link to Math.abs reference page

pxtlib/cpp.ts, tests/common/testHost.ts, webapp/src/cmds.ts
Fixes https://github.com/microsoft/pxt-calliope/issues/161
When we generate compile options for a project, we cache it based on the source of the project and pxt_modules.
The issue here was that we weren't updating the config in the MainPackage when generating the compile options but we were using the updated config in the key of the cache, thus we ended up caching the wrong result.
I also added a forcehex query parameter to make debugging this easier on localhost
@Amerlander FYI (and sorry for the delay! i've been out sick)
=> [stable7.0] Make sure the package config is up to date before caching extinfo

cli/cli.ts, pxtcompiler/emitter/backbase.ts, pxtcompiler/emitter/backjs.ts, pxtcompiler/emitter/backvm.ts, pxtcompiler/emitter/emitter.ts, pxtcompiler/emitter/hexfile.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3931
This fixes the memory leak in pxtworker that was causing us to crash the tab (and sometimes all of chrome) by running out of memory.
During a compile we annotate the TS ast with a bunch of information for our compiler. To support incremental compilation, we also store references to functions that we can call again when re-emitting the nodes. The closures for these functions were causing a reference to the Binary object to stick around, which in turn was referencing CompileOptions (which contains the entire source of the program) and CompileResult (which includes the text of the emitted `binary.js`). All together this amounted to many mbs of strings being allocated every time the compiler was invoked.
This PR removes the binary's …
=> Fix memory leaks in compile webworker

pxtcompiler/emitter/snippets.ts, tests/language-service/snippet_cases/imageThisParam.ts, tests/language-service/test-package/basic.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/4931
If a fixedinstance type has a variable shadow block set in its block definition, then we don't really want to reference one of the exported fixed instances.
=> Fix snippet for fixedinstance methods that use variables_get

pxteditor/editor.ts, pxteditor/editorcontroller.ts, react-common/components/share/ShareInfo.tsx, skillmap/src/actions/dispatch.ts, skillmap/src/components/AppModal.tsx, skillmap/src/components/makecodeFrame.tsx, skillmap/src/store/reducer.ts, webapp/src/app.tsx, webapp/src/share.tsx
Currently, recording a thumbnail is not supported in the skillmap. Other than that, this makes the share dialog the same in the editor and skillmap.
Also refactored the share/publish code in the webapp a little bit to clean things up.
=> Use new share dialog in skillmap

theme/image-editor/imageEditor.less, webapp/src/blocks.tsx
When a tutorial is open, there's a size threshold where the text in the image editor's top buttons overruns the buttons' bounds. This happens because the tutorial pane severely limits the horizontal space allowed for the popup, but we aren't in tablet mode yet when considering the whole available screen size. Regardless, the space allowed for the popup is too small.
To address this, I've allowed the popup to overlay the tutorial if the **container's** size is smaller than the tablet threshold (as opposed to the whole window). I also increased the weight on the buttons' section of the flexbox so they aren't quite so restricted on either side. Combined, these give us enough flexibility to still look okay until we get to tablet mode, at which point the buttons change into their smaller form …
=> Fix Image Editor Top Bar Button Sizing

docs/writing-docs/snippets.md, theme/tutorial.less, webapp/src/marked.tsx, webapp/src/toolbox.tsx
add tutorial block discoverability feature -- when user clicks on an inlineblock snippet (the little colored bars), open the associated toolbox category. (Note that the namespace needs to exactly match, so it might need some post release cleanup for existing tutorials, but should be fine for the most part):
=> Inline snippet click highlight

theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialContainer.tsx
* fixes https://github.com/microsoft/pxt-arcade/issues/4968
* margin on step label
* top border on the controls (next button) section so it's visually separated from the text content
* make next button 'tutorial color' instead of orange, so it doesn't clash with download button
=> Quick tutorial updates from testing

authcode/package-lock.json, gulpfile.js, package.json, skillmap/package-lock.json, skillmap/package.json, skillmap/src/components/AppModal.tsx, skillmap/src/components/Carousel.tsx, skillmap/src/components/HeaderBar.tsx, skillmap/src/components/InfoPanel.tsx, skillmap/src/components/SkillCarousel.tsx, skillmap/src/components/SkillGraph.tsx, skillmap/src/components/SkillGraphContainer.tsx, skillmap/src/components/UserProfile.tsx, skillmap/src/components/makecodeFrame.tsx, webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/ImageEditor/TopBar.tsx, webapp/src/components/ImageEditor/keyboardShortcuts.ts, webapp/tsconfig.json
Node 16 performs a stricter peer dependency check, and we were failing it after upgrading to React 17.
Changes in this PR:
* Upgrade react-redux
* Upgrade redux
* Upgrade react-modal
* Fixed up compiler errors that came in with the updated type definitions
* Run skillmap and authcode's `npm install` in pxt's `postinstall` step
=> Node 16 peer deps, and make TypeScript happy

package.json
The `prepare` script will be run only when installing dependencies directly, but not when the package is itself a dependency.
=> Use prepare script, not postinstall

webapp/src/marked.tsx
I don't think there was an issue for this? but richard noticed during testing, lots of the time we have different capitalization in md vs namespace names -- in particular with `Math` as it's capitalization is a bit weird.
e.g. 
```md
``||math:pick random||``
```
instead of 
```md
``||Math:pick random||``
```
this fixes that so it checks for namespaces ignoring case
=> fix clickable snippets when capitalization differs

pxtlib/audioUtil.ts
Sending a NaN into this API will crash the simulator.
=> guard against nan frequencies (crashes sim)

react-common/components/share/ThumbnailRecorder.tsx, react-common/styles/share/share.less, webapp/src/share.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/4954
Fixes https://github.com/microsoft/pxt-arcade/issues/4962
Fixes https://github.com/microsoft/pxt-arcade/issues/4965
Fixing a few of the thumbnail recording bugs. Each commit is broken out into one change.
Summary of the changes:
1. We now try and retake the screenshot if the thumbnail doesn't load
2. The screenshot button now disappears when you are recording a GIF
3. The thumbnail changes into a spinner when you're recording/rendering to make it more obvious when recording has started or stopped
4. Swapped the order of the "apply" and "cancel" buttons
=> Fix a few thumbnail recorder share bugs

webapp/src/marked.tsx
fix https://github.com/microsoft/pxt-arcade/issues/4995 -- when you open the blocks editor before starting a monaco editor tutorial the snippets would fail to open toolbox categories.
Issue was that we retain the toolboxes in the dom and just display:none the editor div that encompasses them, so the querySelector always found the blocks toolbox category instead of the monaco toolbox category when both exist. This change filters out non-visible editor divs when opening the category.
(if there's an easier way to grab active editor div I'd love a pointer, couldn't remember one when you don't have access to the ProjectView component)
=> fix snippets in monaco after blocks editor has been opened

pxteditor/editor.ts, react-common/components/share/Share.tsx, react-common/components/share/ShareInfo.tsx, react-common/components/share/ThumbnailRecorder.tsx, react-common/styles/share/share.less, webapp/src/app.tsx, webapp/src/components/SimRecorder.tsx, webapp/src/share.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/4991
Fixes https://github.com/microsoft/pxt-arcade/issues/4960
Fixes https://github.com/microsoft/pxt-arcade/issues/4964
Fixes https://github.com/microsoft/pxt-arcade/issues/4958
Changes include:
1. Clicking record now auto-focuses the sim
2. The GIF recorder now automatically times out after ten seconds
3. The share dialog buttons are now aligned to the bottom-right
4. The first share of a project is now always persistent, and subsequent shares have a checkbox asking if they want to update the existing link (defaults to checked)
For 4, the checkbox defaults to being checked. I can easily make it unchecked if that's preferred.
=> More share fixes

skillmap/src/components/AppModal.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/4959
Until we get the thumbnail recorder into the skillmap, removing the wide class
=> Remove wide class from share dialog in skillmap

webapp/src/app.tsx
The `emptyRunCode` var is a string with code in it, so `!!emptyRunCode` always returns true (as long as the string is set in pxttarget.json, which it usually is). As a result, we always return true for `autoRunOnStart()`, even if light mode is enabled. As I understand it, we should only do an empty code run if it's also the first run, so I've added an additional check to account for that.
This fixes the first part of https://github.com/microsoft/pxt-arcade/issues/2313: "Autorun should always be disabled for light mode"
=> Disable AutoRun in Light Mode

webapp/src/marked.tsx, webapp/src/toolbox.tsx
fix https://github.com/microsoft/pxt-arcade/issues/5042
(minor note that it only ever opens advanced / doesn't toggle it back closed, as closing advanced feels aggressive)
thanks for finding @thsparks
=> inline snippets: for advanced categories open advanced before toggle

theme/tutorial-sidebar.less
fix https://github.com/microsoft/pxt-arcade/issues/5036
=> don't show 'saving' text in sidepanel tutorial editortoolbar

theme/tutorial-sidebar.less, webapp/src/marked.tsx
Adds a button to pop out video for azure media service videos (when supported https://caniuse.com/picture-in-picture -- good support chrome / edge, pretty good safari, no firefox)
=> add a 'pop out video' button to ams videoseos when pip available

skillmap/src/styles/infopanel.css
Currently, the skillmap info panel has boxes that display a learning objectives, and they look very similar to the buttons lower down on the page, which can be confusing since the learning objective boxes are not interactive. This PR changes the shape of the learning objective containers so they're more visually distinct from the buttons.
Without this change:
With change:
Fixes https://github.com/microsoft/pxt-arcade/issues/4967
=> Change Shape of Skillmap Learning Objective Tags to Differentiate from Buttons

theme/tutorial-sidebar.less, webapp/src/app.tsx, webapp/src/simtoolbar.tsx
fix https://github.com/microsoft/pxt-arcade/issues/4986
fix https://github.com/microsoft/pxt-arcade/issues/5011 (not directly related but short / accidentally forgot to make a new branch >> )
=> Add mute button to tutorial mini sim, expand when going to full editor

theme/highcontrast.less, theme/tutorial-sidebar.less, theme/tutorial.less, webapp/src/components/tutorial/TutorialHint.tsx
close https://github.com/microsoft/pxt-arcade/issues/5028
\+ decision from alex + kiki on tutorial hint behavior, changing lightbulb to key + a label for 'answer key':
=> slight adjustment to tutorial hint colors, hint icon > key, title

pxtlib/crowdin.ts
We've been getting tons of spurious-ish build fails like this: https://github.com/microsoft/pxt-arcade/actions/runs/3147157788/jobs/5116383731#step:6:1552.
I think the root cause might be something changing on crowdin side (I feel like I remember it being 30 concurrent requests but they list 20 now, either way we haven't changed our usage patterns much but we're getting the error more often), but we should handle the error either way.
(this isn't explicitly tested as it's not something that can really be tested without intentionally overloading crowdin api to get it to crash, but it's just an extra case of the existing retry error case for updates so feels pretty safe)
=> try and handle crowdin 429s we've been getting

webapp/src/components/tutorial/TutorialCallout.tsx, webapp/src/components/tutorial/TutorialContainer.tsx
Not a regression but probably want to sneak this into the release build, I just noticed that the sidepanel tutorials next / hint buttons never got titles / aria labels for accessibility~
=> add titles / aria labels for hint & next/done buttons

theme/highcontrast.less, theme/tutorial-sidebar.less
we should port this one for release
fix https://github.com/microsoft/pxt-arcade/issues/5077
and make it so it shows up as a cursor when you hover over the clickable portion like all other buttons
=> fix expandable hints hc, add pointer cursor

webapp/src/marked.tsx
fix https://github.com/microsoft/pxt-arcade/issues/5093, looks like this optional parameter defaults to true?
=> autoplay off for ams videos

multiplayer/src/components/ReactionEmitter.tsx, multiplayer/src/components/ReactionParticle.tsx, multiplayer/src/components/Toast.tsx, multiplayer/src/hooks/index.ts, multiplayer/src/hooks/useWindowSize.ts, multiplayer/src/types/index.ts
The reaction emitter wasn't changing position when the window was resized.
Introduced a new project folder: `/hooks`. It's a place to our custom react hooks.
=> fix bug in reaction emitter. misc cleanup.

pxtlib/docsrender.ts, webapp/src/marked.tsx
Few quick fixes
* pause on exiting picture in picture mode as it's a bit of an 'escape video' behavior: fix https://github.com/microsoft/pxt-arcade/issues/5103
* on toggle accordion hint pause the contained videos (iff the video is not popped out into picture in picture where it is still visible)
* when you get to the endTime in a video, pop back to the beginning of the segment. Currently it just pauses at the end, and if you play again it will immediately pause again when the first PLAYBACK_TIME_UPDATED event is fired, which makes it hard to replay the video if you missed something.
=> video pause on hidden, restart at start time

multiplayer/src/components/Presence.tsx, multiplayer/src/components/ReactionEmitter.tsx, multiplayer/src/epics/playerJoinedAsync.ts, multiplayer/src/epics/playerLeftAsync.ts, multiplayer/src/epics/setReactionAsync.ts, multiplayer/src/services/gameClient.ts, multiplayer/src/state/actions.ts, multiplayer/src/state/reducer.ts, multiplayer/src/state/state.ts, multiplayer/src/types/index.ts
Using `clientId` to represent a player in a multiplayer game, to avoid confusion with the existing `userId` from auth world.
This is a breaking change as it affected the format of a network message. I'll merge this and the server-side PR at the same time, and bump the server at that point.
=> cleanup user/client terminology

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/components/HostGame.tsx, multiplayer/src/components/JoinGame.tsx, multiplayer/src/components/Presence.tsx, multiplayer/src/components/ReactionEmitter.tsx, multiplayer/src/components/ReactionParticle.tsx, multiplayer/src/components/Reactions.tsx, multiplayer/src/components/SignInPage.tsx, multiplayer/src/components/SignedInPage.tsx, multiplayer/src/components/Toast.tsx, multiplayer/tailwind.config.js
This helps avoid conflicts with existing css classes, like "hidden", which can break tailwind behavior.
For example, I noticed an issue where tailwind could not properly adjust if something was shown or hidden based on screen size. The tailwind css classes to make that happen are `hidden md:block`. According to [the docs](https://tailwindcss.com/docs/responsive-design#mobile-first), this should hide the item when the screen is smaller than md and show the item when the screen is md or larger. However, the behavior I saw was that the item was always hidden, regardless of screen size. This was happening because we already have a `hidden` css class in our common theme (see [here](https://github.com/microsoft/pxt/blob/master/theme/common.less#L860-L862)). That class prevented tailwind from …
=> Add Prefix to Tailwind CSS Classes

multiplayer/src/App.tsx, multiplayer/src/components/HostGame.tsx, multiplayer/src/components/JoinGame.tsx, multiplayer/src/components/Loading.tsx, multiplayer/src/epics/setUserProfileAsync.ts, multiplayer/src/index.tsx, multiplayer/src/types/index.ts
When served from staging, it looks like the auth check can complete before the app's first render. This change moves the auth check downstream, to a point where the app is initialized and ready to receive state changes.
I also added a "Loading..." state. This is shown at startup while the auth check is running and login status of the user is undetermined.
=> Move auth check. Add init state.

docs/csp.md
Remove the Professional Development Opportunities note from the CSP page now that their dates have past.
Closes #9098
=> Remove PD opportunities from CSP page

pxtlib/emitter/cloud.ts
fix https://github.com/microsoft/pxt-arcade/issues/5134
The regex produced by this for arcade can be tested here: https://regex101.com/r/qk2y2e/1, it's this whole thing:
```
/^(?:(?:https:\/\/)?(?:makecode\.com|arcade\.makecode\.com)\/)?(?:v[0-9]+\/)?(?:(?:api\/oembed\?url=.*%2F([^&#]*)&.*)|(?:([a-z0-9-_]+)(?:[#?&].*)?))$/i
```
The link I shared above has that (with the global and multi line flags enabled to allow for multiple test strings at once)
few quick notes;
* oembed check was already broken so I 'fixed it' but don't have a url handy to try it / don't know how a user would really end up using that as a share code. (the broken bit in particular was that it was checking `oembed?` instead of `oembed\?` in the produced regex)
* the domains check on line 246 was redundant -- we've …
=> fix parsing for shared scripts query params / hashes

multiplayer/src/App.tsx, multiplayer/src/components/AppModal.tsx, multiplayer/src/components/HeaderBar.tsx, multiplayer/src/components/SignInPage.tsx, multiplayer/src/components/SignedInPage.tsx, multiplayer/src/state/actions.ts, multiplayer/src/state/reducer.ts, multiplayer/src/state/state.ts, multiplayer/src/types/index.ts
This is a follow up from comments in https://github.com/microsoft/pxt/pull/9117. The design is based loosely on the skillmap modal design.
We want to create a simple way to show modals without having to pass around a bunch of callbacks. To do that, I've created a `modal` field in the app state which defines what type of modal (if any) is visible. The `AppModal` component handles displaying the actual modal based on this field's value. To display a modal, we can call into the dispatcher and fire the ShowModal event, passing in the type of modal to show.
=> Rework Modals for Multiplayer

pxtsim/runtime.ts
if you poke around `pxtlib/util.ts` you'll see it's *pretty similar* to the function there: https://github.com/microsoft/pxt/blob/master/pxtlib/util.ts#L739 . I need this function available for a change I'm making in arcade sim 
runtime has a number of these things that are just mirrored over (e.g. see `delay` / `nextTick` functions right above where this pr is) -- this is because the pxtsim/runtime code gets included in the sim iframe but pxtlib does not.
=> copy over throttle fn to pxsim/runtime

pxtcompiler/emitter/service.ts, pxtpy/converter.ts
Closes https://github.com/microsoft/pxt-arcade/issues/2149
=> Fixes bug with loading help resources (side docs) on Python methods

multiplayer/src/components/ArcadeSimulator.tsx, pxtrunner/runner.ts, pxtsim/simdriver.ts
When we're waiting for the host to start the game, preload the simulator so it's ready to go / there's not a big blank space on the page until users join in. 
Took a little bit more fiddling to get right than I expected, lots of subtle life cycle things across runner / simdriver / sim. Did notice and fix a memory leak along the way (pxtrunner creates a new simdriver each time simulate async is called, which attaches a message listener to window, which contains a ref to itself -- this wouldn't be a big deal but this means it keeps around it's _currentRuntime which contains the binary js / is multiple mb, and occasionally it would also send random messages / in this case when the container happened to be kept around it would start with old code.)
=> Multiplayer preload simulator before compile

multiplayer/config-overrides.js, multiplayer/package-lock.json, multiplayer/package.json, multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/epics/setGameModeAsync.ts, multiplayer/src/services/gameClient.ts, multiplayer/src/state/reducer.ts, multiplayer/src/types/index.ts, multiplayer/src/util/index.ts
The host sends screen updates at a rate of 20Hz, so we want to optimize their network size. The approach here is to XOR the current screen with previous screen to get the delta, then gzip the result. The current palette is concatenated to the buffer and included in the delta. We detect empty deltas and skip sending those frames entirely.
Size comparisons
* Uncompressed screen: 9.5k
* Compressed screen (non-delta): between 50b and 2.5k
* A compressed delta screen falls in the same size range as a compressed non-delta screen, but will be tend to be much smaller on average.
=> [multiplayer] send compressed screen updates

multiplayer/src/App.tsx, multiplayer/src/components/Footer.tsx
The code also supports a copyright section, but we don't have one in the target theme so it doesn't appear here.
This is lifted pretty directly from https://github.com/microsoft/pxt/blob/master/webapp/src/projects.tsx#L209-L216 with some tailwind-ification. I did remove the language section, though, as I suspect that may go in the gear menu. We can add it back here later if needed. I also made the text black because I think the original color wouldn't pass accessibility checks.
Links:
Microsoft MakeCode: https://makecode.com/org
Terms of Use: https://go.microsoft.com/fwlink/?LinkID=206977
Privacy: https://go.microsoft.com/fwlink/?LinkId=521839
Fixes https://github.com/microsoft/pxt-arcade/issues/5158
=> Add Multiplayer Footer with Privacy and Terms of Use

multiplayer/src/components/ArcadeSimulator.tsx, pxtrunner/runner.ts
Don't show sim until the player presses start, just load in background.
@thsparks for your mute pr to make it so we persist mute setting I added a pxtrunner opt to propagate mute state -- we'll need to add the muted state to getOpts here https://github.com/microsoft/pxt/blob/multMuteAndHideUntilStart/multiplayer/src/components/ArcadeSimulator.tsx#L93 after this and your pr are both merged, can update either pr when the other is merged.
=> Multiplayer: persist mute and hide sim until start

multiplayer/src/components/GamePage.tsx, multiplayer/src/components/HostGame.tsx, multiplayer/src/components/JoinCodeLabel.tsx, multiplayer/src/components/ToggleMuteButton.tsx
This change cleans up the multiplayer game page, moving the mute button and the join code label into their own components. It also adds a small quality of life improvement for the dev inner loop by including a default host share project when in local dev mode (saves on a few seconds of copy/paste when debugging).
I used Joey's https://makecode.com/_VvPX5u9bx7fx project for the default debugging project. Initially, I tried an aka.ms link so we could update it without a code change, but then it can't parse the share code. That may be an improvement for another time :)
To test the non-local-debugging scenario and ensure Host Project input is *not* populated, I used this: https://arcade.makecode.com/app/e9f0145aa441a8ce2728ea4492acecf78cb5c2f9-06259d28cd--multiplayer
=> Multiplayer Game Page Refactor & Quality of Life Updates

gulpfile.js, multiplayer/src/components/GamePage.tsx, multiplayer/src/hooks/useAuthDialogMessages.ts
our lf regex is a bit picky about spacing I guess, would slightly prefer to avoid touching the cli lf scraping code as I feel like that's been the same forever / might be dragons. Just pulling out a few strings so that prettier won't mangle them.
Should probably make it throw in this if https://github.com/microsoft/pxt/blob/fixAuthDialogLfs/gulpfile.js#L327? ~I guess would be a little annoying for local dev, would prefer not to do in this pr either way~ just made it so build will error if env == prod so it'll error in prs like lint but won't prevent you from doing local dev work
=> fix lfs that the regex will miss

multiplayer/src/components/ArcadeSimulator.tsx
Forgot this flag when moving things around, autofocus so initial keyboard / gamepad events should work in sim. Will eventually need to do a little more to grapple with focus issues though
=> auto focus on sim in multiplayer

localtypings/pxtarget.d.ts, react-common/components/share/ShareInfo.tsx, react-common/styles/controls/Button.less
like this:
the button color was picked at random to make it visually stand out from other social opts, would be happy to swap it given a good color
note dev side our share url logic needs some work, it's tangential to this so I didn't do anything to address it but 2/3 envs are broken currently:
* staging: when link is created, it is properly stored in staging but the displayed link is makecode.com/blah and does not work
* localhost: it's created on staging (which is a bit unexpected personally / would prefer to make it on prod as staging share links cannot be distributed) but also displays prod url
* prod is fine
in addition, we don't include the staging domains in the domains check here: https://github.com/microsoft/pxt/blob/master/pxtlib/emitter/cloud.ts#L243 so staging urls get …
=> add button to host a multiplayer game to share dialog

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/components/CopyButton.tsx, multiplayer/src/components/GamePage.tsx, multiplayer/src/components/HostLobby.tsx, multiplayer/src/components/JoinCodeLabel.tsx, multiplayer/src/util/index.ts
This updates the host lobby appearance to match the latest designs more closely, and it will copy a deep link rather than the code itself when the copy button is pressed (on both the host lobby and the game page).
Also sneaking in a fix to make the sim use the full screen width when on a smaller screen.
=> Use Deep Links for Copying Multiplayer Join Code, Update Host Lobby Appearance 

multiplayer/src/epics/setGameModeAsync.ts
I believe this should be the fix for https://github.com/microsoft/pxt-arcade/issues/5205 and https://github.com/microsoft/pxt-arcade/issues/5208
I'll hopefully find some time to make it so we propagate sim colors even if the sim has already been running, but this should fix it for now. the issue is that we were hitting the compile & run case before the slot was set, which is used to determine which color the sim should be. Currently, that is determined only when the sim is loaded for the session. (I'm assuming green sim in player 2 is that thomas joined a game, left, then joined another already started game which got the wrong color.)
=> multiplayer should fix sim colors for now

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/index.css
A little pumpkiny, but swapping from yellow to orange to fix contrast issues & match the player 3 theme in arcade game engine (e.g. when you set player 3 health)
also fix order on presence bar to match player color order on sim and in game
=> fix color order on presence bar, yellow -> orange to match sim

multiplayer/src/components/BetaTag.tsx, multiplayer/src/components/GamePage.tsx, multiplayer/src/components/HostLobby.tsx, multiplayer/src/components/JoinLobby.tsx, multiplayer/src/components/JoinOrHost.tsx
This adds a little "beta" tag to the home page, lobbies, and game page. Margins on the sim were a bit weird, so I just put it in the corner of the page in that scenario for now. If needed, we can revisit this later, but it may require css updates on the sim-side of things.
Also, I don't know the "right" way to position stuff in css/html so feel free to offer alternate suggestions.
Fixes https://github.com/microsoft/pxt-arcade/issues/5162
=> Add Beta Indicator to Multiplayer Pages

docs/playground.html
Added the title so it displays on the browser tab instead of the url. Closes https://github.com/microsoft/pxt-arcade/issues/3613
=> Added title html tag for the blocks playground page

localtypings/pxtarget.d.ts, pxtcompiler/emitter/emitter.ts, pxtlib/service.ts, pxtrunner/runner.ts
PR 1 of 3 for automatically detecting if a game is multiplayer at compile time.
This adds a PR that makes it so that the compiler keeps track of the used "parts" when compiling a program. By labeling all multiplayer APIs with `parts="multiplayer"`, then if one of those APIs is called by the user program it should show up in the usedParts array in the CompileResult.
This comment annotation is the same one we use to detect if you use a servo in micro:bit, etc.
=> Add compile option to calculate used parts

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/services/gameClient.ts, multiplayer/src/types/index.ts, pxtsim/simlib.ts
send and receive messages between pxt-c-p and pxt-backend, and add a little hook in sim sound that calls back on sound events. 
@riknoll if you see any events I need to propagate besides just mute channels & play buffer let me know, it seems fine as far as I can tell.
here's the bad test sound 'pad' I did: https://arcade.makecode.com/S05411-77245-32862-42860 (I should have asked richard for one of his cool sounds)
=> multiplayer propagate audio

webapp/src/components/ImageFieldEditor.tsx
We updated arcade gallery asset tags (https://github.com/microsoft/pxt-arcade/pull/5219) so we need to localize them as well.
We still need to extract the strings, so I've filed an issue here: https://github.com/microsoft/pxt-arcade/issues/5197
=> Added new asset tags/categories for localization

multiplayer/src/components/RemixGameButton.tsx
This should fix the issue for now, the webconfig values are still slightly wrong in multiplayer at the moment (pointing at live instead of beta when in beta) but good enough to test for now / that's a separate fix that might be bundled into my worker change later.
vs skillmap which has the correct values in webConfig
=> multiplayer fix remixurl

skillmap/src/components/AppModal.tsx, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts
if anyone has an icon suggestion, i'm all ears!
The authoring side of this is to just set `showMultiplayerShare` to true like so:
```markdown
* name: Congrats!
* kind: completion
* type: certificate
* url: /static/skillmap/certificates/mole-cert.pdf
* imageUrl: /static/skillmap/certificates/mole-cert.png
* position: 2 0
* showMultiplayerShare: true
* actions:
* map: [Create Another Carnival Game](/skillmap/balloon)
* editor: [Open in Creative Mode](/)
* rewards:
* certificate:
* url: /static/skillmap/certificates/mole-cert.pdf
* preview: /static/skillmap/certificates/mole-cert.png
* completion-badge:
* image: /static/badges/badge-mole.png
* name: Whack-the-Mole
```
@kiki-lee FYI
=> Add optional multiplayer callout in the skillmap

multiplayer/src/components/AppModal.tsx, multiplayer/src/components/GamePage.tsx, multiplayer/src/components/HeaderBar.tsx, multiplayer/src/components/Popup.tsx, multiplayer/src/components/Presence.tsx, multiplayer/src/components/ReactionParticle.tsx, multiplayer/src/components/Reactions.tsx, multiplayer/src/components/Toast.tsx, multiplayer/src/components/modals/ConfirmModal.tsx, multiplayer/src/epics/gameDisconnected.ts, multiplayer/src/epics/gameOverAsync.ts, multiplayer/src/epics/index.ts, multiplayer/src/epics/kickPlayer.ts, multiplayer/src/epics/leaveGameAsync.ts, multiplayer/src/hooks/index.ts, multiplayer/src/hooks/useClickedOutside.ts, multiplayer/src/services/gameClient.ts, multiplayer/src/types/index.ts, multiplayer/src/types/reactions.ts, react-common/components/controls/Button.tsx
* Host can kick a player, and the user will be perma-banned from that game session.
* Better "game over" messaging. User will be told why the socket disconnected, if we know. "got kicked", "game ended", "you left the game", etc.
* Added a player popup menu to the presence bar. It is contextual to whether the player clicked on is you or someone else, and whether or not you're the host.
* Emoji buttons are now based on react-common/Button, for better accessibility.
* Clicking outside the reaction palette closes it.
* Centered the reaction palette over the presence bar, for better experience on mobile (isn't half off-screen)
**Host's own popup**
**Host's popup for player 2**
**Player 2's own popup**
**Improved game over messaging**
**Centered reaction palette**
=> kick player, game over, player menu, misc refinements

multiplayer/src/components/GamePage.tsx, multiplayer/src/components/HostLobby.tsx, multiplayer/src/components/JoinLobby.tsx, multiplayer/src/components/JoinOrHost.tsx, multiplayer/src/components/RemixGameButton.tsx, multiplayer/src/components/SignedInPage.tsx, multiplayer/src/components/TabButton.tsx
This is just a first pass. Likely more changes to come, but I wanted to send this out first so the PR doesn't get too large.
Changes include:
1. Padding & margin adjustments
2. Removing "Remix Game" text on small screens (may remove button altogether later, TBD)
3. Remove "Keyboard Controls" on small screens
4. Shrink "Join Game" and "Host Game" to "Join" and "Host" on small screens
Fixes https://github.com/microsoft/pxt-arcade/issues/5215
Partially addresses https://github.com/microsoft/pxt-arcade/issues/5252
=> Improve Multiplayer Responsiveness to (Vertical) Mobile Screen Sizes

skillmap/src/components/AppModal.tsx
As discussed in testing today, making it so that the multiplayer share button replaces the regular share button when enabled in the skillmap
=> Make it so that only one share action shows up in the completion dialog

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/epics/pauseGameAsync.ts, multiplayer/src/epics/resumeGameAsync.ts
Pause guest sims as well as host, otherwise their controls are still active and it felt odd.
Also adjusted pause state visuals a bit:
* Leave some color rather than go pure grayscale.
* Add a blur affect to help the pause notification stand out from background detail, and really drive the message that the game isn't playable right now. Maybe it won't be performant on low end machines, needs testing.
=> pause all sims. tweak pause visuals

multiplayer/src/components/Reactions.tsx
Felt like adding this as I was testing a game and wanted it, only just saw that you assigned yourself a couple hours ago @eanders-ms, hope I'm not stepping on your toes! I saw a comment on throttling per reaction in sendReactionAsync so when that is implemented can remove throttle in this file
fixes https://github.com/microsoft/pxt-arcade/issues/5182
=> add support for keyboard emoji reactions

localtypings/pxtarget.d.ts, pxtblocks/blocklycustomeditor.ts, webapp/src/components/assetEditor/assetGallery.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/5288
Putting the song editor behind a flag so that not even clever extension authors can get to it! Still requires a change to pxt-common-packages to get rid of the block.
=> Hide the song editor behind a flag

multiplayer/src/components/Reactions.tsx, multiplayer/src/state/state.ts
* start muted in ios, as they're pretty restrictive on sound. This matches editor behavior, though we should probably do another pass and see if we can handle this better. fix https://github.com/microsoft/pxt-arcade/issues/5306, should improve both editor and multiplayer experience later.
* fix https://github.com/microsoft/pxt-arcade/issues/5309, ios sometimes lies about being desktop which bypasses mobile checks so also check ios
=> multiplayer Mobile safari fixes

multiplayer/src/components/HeaderBar.tsx, multiplayer/src/components/HostLobby.tsx
The link doesn't go anywhere yet, but I am assuming it will be created in the future. I followed the same pattern as our docs links in the JoinOrHost page.
I tried to find some way to incorporate it into the join lobby too, but struggled to make it look good, so for now I'm just relying on the gear menu option there (which, admittedy, people are unlikely to find on their own). Open to suggestions.
Fixes https://github.com/microsoft/pxt-arcade/issues/5274
=> Add Safety Links to Gear Menu and Host Lobby

multiplayer/src/components/KeyboardControlsInfo.tsx, multiplayer/src/components/Reactions.tsx
Feedback in testing this am was that reactions pane looked a little worse with all the keyboard hint, so took a stab at rearranging to hopefully look a little more inviting again.
* make the numbers on the emojis look a little 'like keys' as some weren't sure that users would understand the circled numbers:
* move from a text description under the reactions to the 'keyboard controls dialog'
took the same icon as the one on the reactions button to hopefully guide them to press that if they see it and haven't noticed the reactions yet.
@unthinkmedia let me know what you think~
=> multiplayer reactions keyboard ui updates from testing

pxtlib/emitter/cloud.ts
The reason that this does not affect the share page is because the share page makes the /text request for the current version that is embedded directly in the response, and not with the persistent share link
=> when fetching S link skip the cache

webapp/src/monacoSnippets.ts
Closes https://github.com/microsoft/pxt-arcade/issues/4621
=> Removed semicolon from create array snippet in JS toolbox

multiplayer/src/components/CopyButton.tsx, multiplayer/src/components/HostLobby.tsx, multiplayer/src/components/JoinCodeLabel.tsx
This makes the full join code clickable to copy the join link, rather than just the icon to the side. To make it work in a way that felt smooth, I had to do some refactoring of the CopyButton to allow for a label attached to the button (rather than managing them separately). It will also display a toast when the copy is successful.
=> Make Full Join Code Clickable for Copying Link

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/components/GamePage.tsx, multiplayer/src/components/SignedInPage.tsx, multiplayer/src/services/simHost.ts
Easiest to see with a build: https://arcade.makecode.com/app/99710e6c974bf62478eff348d40682c1d5dca5cc-3935cb69d8--multiplayer
make the sim a bit more greedy for space to fill out the page a bit more:
vs
also should fix the issue where the reactions occasionally go off screen by about 1em on  mobile too (at least it fixes it for me >>)
(also a one line fix for compiler so that it doesn't throw off a spurious error message, a debug message was assuming that optional parameter existed)
=> make simulator a bit more greedy for space, fix mobile reactions going off screen

multiplayer/src/components/CopyButton.tsx, multiplayer/src/epics/gameDisconnected.ts, multiplayer/src/epics/hostGameAsync.ts, multiplayer/src/epics/index.ts, multiplayer/src/epics/joinGameAsync.ts, multiplayer/src/epics/notifyGameDisconnected.ts, multiplayer/src/services/gameClient.ts, multiplayer/src/types/index.ts
There were a few conditions, such as when a game is full, where the client would appear to still be connecting and eventually show a "something went wrong" error. This change fixes that, and generally strengthens the error pathways in the connect/join process.
That said, it's still more complex than it should be. Will revisit someday.
=> improved error pathing in connect/join flow

multiplayer/src/components/HeaderBar.tsx
It's not clear that this will be necessary. Most "help" is already accessible through other parts of the page, like the keyboard controls button or the "online safety" item in the gear menu. Removing for now, can add back later if needed.
=> Remove the Help Button from the Multiplayer Gear Menu

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/services/gameClient.ts, multiplayer/src/types/index.ts
I needed this for testing https://github.com/microsoft/pxt-arcade/issues/5338, and it feels pretty useful / at least enough to keep around as a one line test similar to the vars for swapping on / off staging vs local backends.
Also a small change to catch any invalid inputs, in case e.g. someone tries to fake through messages by directly using the socket.
=> addd a function to fake p2-4 inputs, check against invalid button commands

common-docs/multiplayer.md, multiplayer/src/components/HostLobby.tsx, multiplayer/src/components/JoinOrHost.tsx
Fixes the help links for the multiplayer UI href elements. Also, a base `multiplayer.md` page is added as a place holder for `@extends`.
=> Multiplayer help links and base page

ThirdPartyNotice
It was added as a dependency in https://github.com/microsoft/pxt/commit/0f492f00ef08d9398a7ae07b9621cf459dce9a0a but I didn't add it here.
=> Add Qrcode.React to ThirdPartyNotice

webapp/src/dialogs.tsx, webapp/src/notification.tsx, webapp/src/util.tsx
This updates the top-bar notification and the no-text-editor modal that both appear in the WinJS app to signal deprecation. Now, they both point to the new windows app. The documentation link hasn't changed, but we'll probably want to update the docs to explain the new bulk download/upload options.
I wanted to be able to inject JSX into an LF statement, but the "jsxLF" function doesn't exist in stable7.0 so I just copied it in. Hopefully that's alright.
=> Update Microbit App Deprecation Notifications

pxtlib/service.ts, webapp/src/extensionsBrowser.tsx
* fix https://github.com/microsoft/pxt-arcade/issues/5367
* fix https://github.com/microsoft/pxt-arcade/issues/5361
* also lowered a delay that was waiting 1 second after the dependency was added until it reloaded headers, I'm a little suspicious of it but 1 second is quite a while if it's not strictly necessary / fighting against a known race condition somehow
left a few todos spread around as I didn't want to go to poke around too much besides fixing the known regressions as this will probably be ported to arcade, microbit, maybe minecraft (I'm guessing content authors could be using the share script extensions to test at least?) ~
Here's a build to double check: https://arcade.makecode.com/app/5dc92e4c8357413a5065b97411a4157ffd9c89ec-0aa863d716
=> Extension search fixes

webapp/src/dialogs.tsx, webapp/src/notification.tsx
These links worked in the browser but not in the web app, and my hypothesis is that this is because they were using window.open instead of the link's href. (I looked at "Support" in the help menu, which works, and that used href). Unfortunately, I can't test inside the app locally, so this is a best guess. Validated in the browser, but hard to say if it will be 1:1.
I've also updated the link to go directly to the windows store rather than the web version.
=> Fix Deprecation Notification Links for Microbit WinJS App

theme/common.less
fix little sim scrollbar that is showing up when running minecraft with latest pxt due to sim -- this came from a combo of my arcade tutorial layout change + this special casing headless layout for minecraft~
=> fix little scrollbar that shows up in headless sim

webapp/src/extensionsBrowser.tsx
fix issue where approved extensions are showing up as preferred in minecraft as there are no preferred ones yet; issue is that `fetchGithubDataAsync` uses `gh-search`  when <= 1 search terms  are sent, which will return all approved exts (presumably up to a limit in backend) when searching for "" 
I also made it so the 'recommended' header goes away when nothing is recommended as it felt weird having that label with nothing below it -- almost like it was saying 'recommended you use a file instead of github search' or something
=> when no preferred extensions, don't show all approved exts

webapp/src/app.tsx
fix https://github.com/microsoft/pxt-minecraft/issues/2266 - note that it was the entire blockly workspace that was partially hidden behind the toolbox label / menu bar, not just the toolbox -- you can drag the on start off screeen then too even without other blocks 
It's pretty easy to induce a repro, just make your browser as thin as possible and load https://minecraft.makecode.com/hoc2022?ipc=1&inGame=1&noRunOnX=1#tutorial:/hour-of-code/2022/kitchen_feedhouse . I had a little bit of a hard time narrowing down the exact reason it happens more consistently in game even if the window size is accounted for, but it appeared to be a combination of this window size issue + something that seemed like a race condition where `ProjectView.setEditorOffset` was occasionally not getting called at …
=> Fix minecraft hoc layout bug

webapp/src/extensionsBrowser.tsx
In https://github.com/microsoft/pxt/pull/9231 I forgot to account for 'nested' repos in the add logic so this is a quick fix for that
Just noticed this, doesn't matter too much as the only thing currently using nested repos is jacdac and that only encourages people to add the base package but good to fix early. If you search `microsoft/pxt-jacdac/accelerometer` and click after that patch it would just add `microsoft/pxt-jacdac`, where it was working before as the package names should be different (though have to double check that, it's very possible a few of the many subpackages had a typo or something.)
=> fix nested repos direct add

pxtlib/service.ts, webapp/src/extensionsBrowser.tsx
port https://github.com/microsoft/pxt/pull/9231 for arcade
=> [stable8.4] Extension search fixes port

webapp/src/app.tsx
Fix issue where certain hoc tutorials at certain widths under certain race conditions fail to show 'more / less' toggle & are incorrectly sized until you resize window (as there is only one step in these tutorials)
The toolbox block decompilation & `setState` changing `editorState` had to 'go slow' to cause the 'flyoutOnly' class to not be set for a render, causing the wrong font to be shown for a few ms (normal tutorials use the standard font, where minecraft hoc uses the nice `minecraft 7` which is slightly larger), which had to result in a snippet barely fitting in the tutorial text spot (which then had to not fit anymore after the font changed to the correct one), and none of the ~half dozen places that the size gets double checked can occur after the font changed or it would fix …
=> Check for flyout only tut option

cli/cli.ts
in pxt serve also watch for css changes and rebuild when they occur. little noisey in the serve window if you start making changes, but that's already super noisy if you're e.g. making common packages changers so doesn't feel like a big deal.
=> Auto rebuild css in pxt serve

webapp/src/components/tutorial/TutorialStepCounter.tsx
currently we're just sending the 'set step' tick when the step changes from the step bar, even if they click on the previous or next buttons up there. Make it so those two buttons match the other ones when they appear (e.g. the next at the bottom of the step, the back button that appears in modal steps midway through tutorial. Added a `isStepCounter: 1` field for those two messages to determine whether the user clicked the one in the top bar or anywhere else.
I also added a `prevStep` field to the data for tutorial.step, as that feels useful to determine transitions when the bubbles are used / might as well include it?
and for reference here's where the other two are defined: https://github.com/microsoft/pxt/blob/tutStepCounterNextPrevDiffTicks/webapp/src/components/tutorial/TutorialContai …
=> make next/prev step bar buttons use next / prev ticks

pxtblocks/blocklyimporter.ts
This allows multiple blocks to be highlighted in a tutorial hint.
From blockly docs, this additional boolean parameter (when set) prevents other highlight blocks from being reset when highlightBlock is called: https://developers.google.com/blockly/reference/js/blockly.workspacesvg_class.highlightblock_1_method
Multiple blocks highlighted in hint:
Fixes https://github.com/microsoft/pxt-arcade/issues/4856
=> Preserve Existing Highlights When Processing Typescript Metadata Comments

pxtblocks/blocklyimporter.ts, pxtblocks/blocklyrenderer.ts
fix https://github.com/microsoft/pxt-arcade/issues/4647; add a way to elide blocks from hints, such as functions variable declarations. (variable declarations we could already get around by just declaring without setting, but that's kinda weird / really gotta know that as a gotcha so I'd say it's nicer to have an explicit annotation)
Also added an options bag as an option parameter to `domToWorkspaceNoEvents`; the highlight only matters when it's called through rendering / this one should be the same, so making that explicit. This way ts -> blocks with the meta flags won't remove the comments / mess things up (e.g. any `@highlight` in a comment was previously getting deleted, which doesn't matter much but better to just not do it).
and for an example; the following markdown hint produces …
=> Add meta marker for deleting block

pxtlib/main.ts, react-common/components/controls/Modal.tsx, react-common/components/palette/ColorPickerField.tsx, react-common/components/palette/PalettePicker.tsx, react-common/components/palette/Palettes.ts, react-common/styles/palette/ColorPickerField.less, react-common/styles/palette/PalettePicker.less, theme/asset-editor.less, webapp/src/components/assetEditor/assetPalette.tsx, webapp/src/components/assetEditor/assetSidebar.tsx, webapp/src/package.ts
Users can now create unlimited custom palettes, allowing them to more easily test out how their assets look with different palettes. Before, users were only able to have one custom palette at a time and if they swapped to one of the built-in palettes, they would lose their custom palette. Now, their custom palettes are stored in a hidden file and users can access them through the dropdown.
I also changed the 'save' button to 'apply' which now applies the changes and closes the modal instead of saving and keeping the modal open. With this change, there is no intermediary palette and therefore 'reset' always sets the palette back to what it was when the palette editor was opened.
When a user edits a built-in palette, it automatically becomes a custom palette and prompts the user to name the …
=> Color palette editor: support for multiple custom palettes

multiplayer/src/index.tsx, pxtlib/analytics.ts, pxtlib/browserutils.ts, pxtlib/util.ts, pxtrunner/renderer.ts, skillmap/src/App.tsx, webapp/src/app.tsx
When the telemetry is enabled, we set the lang as custom dimension and if the user changes the language to new one, we observe setcookielang and update this.
This is dependent on language cookie which all our properties use to determine the locale.
Joey noted this won't work for forcelang and in context translation as they don't set the cookie. However, these are not the primary user scenarios, and I am ok not being right in these cases. Piggy backing cookie seemed cleaner to me.
=> Adding lang as customDimension for every tick

multiplayer/src/App.css, multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/components/Presence.tsx, multiplayer/src/components/ReactionParticle.tsx, multiplayer/src/components/Reactions.tsx, multiplayer/src/components/icons/UserIcon.tsx, multiplayer/src/epics/index.ts, multiplayer/src/epics/setCustomIconAsync.ts, multiplayer/src/services/gameClient.ts, multiplayer/src/state/actions.ts, multiplayer/src/state/reducer.ts, multiplayer/src/types/index.ts, pxtlib/imageConverter.ts
Support for passing up / down icons (imgs up to 64x64) from host -> all for use in reactions, player icons
closes https://github.com/microsoft/pxt-arcade/issues/5432
closes https://github.com/microsoft/pxt-arcade/issues/5431
I might take a pass at the sizing for the `pixel-art-image`s again after I add the player chooser sim / other things are ready, as sizing them correctly to fit in within rounded edges was slightly tricky to get right / might have missed some sizes if someone makes extra wide / tall images -- will be easier to test when it's in /beta as with just local host it's a bit tricky (e.g. have to push up a broken project as all user projects are pulled from prod and localhost can't push share scripts to prod)
=> Multiplayer post recieve play icons

theme/asset-editor.less, webapp/src/components/assetEditor/assetSidebar.tsx
Closes https://github.com/microsoft/pxt-arcade/issues/5489, closes https://github.com/microsoft/pxt-arcade/issues/5501
There's not enough space for "Color Palette" on the button, so I've shortened it to "Colors".
=> Fix asset editor button margins, fix palette button padding

multiplayer/src/components/icons/UserIcon.tsx
add a filter on non-present players so it's more clear they still didn't join:
=> add a grayscale on presence icon if playeris not in game

docs/SUMMARY.md, docs/extensions/approval.md, docs/writing-docs.md, docs/writing-docs/licensing.md, webapp/src/app.tsx
This is a base page on recommending the inclusion of a license when creating MakeCode related content. Feel free suggest additional info or any corrections.
Closes #9069
=> Add a 'licensing' page to the docs guidance pages

theme/common.less
closes https://github.com/microsoft/pxt-arcade/issues/4990
**Before**:
In tutorial
In project
**After**:
In tutorial
In project
=> Fix excessive padding for project name area, cloud icon

pxtblocks/fields/field_utils.ts, pxtlib/music.ts, react-common/styles/controls/Checkbox.less, theme/music-editor/PlaybackControls.less, webapp/src/assetEditor.tsx, webapp/src/components/musicEditor/MusicEditor.tsx, webapp/src/components/musicEditor/Note.tsx, webapp/src/components/musicEditor/NoteGroup.tsx, webapp/src/components/musicEditor/PlaybackControls.tsx, webapp/src/components/musicEditor/keyboardNavigation.ts, webapp/src/components/musicEditor/playback.ts, webapp/src/components/musicEditor/utils.ts
This PR does three things:
1. Adds a "show bass clef" checkbox to the music editor
2. Revamps how sharps/flats are handled to better support changing the enharmonic spelling of a note
3. Reorders the instruments so that the dog is first (sorry duck)
(2) is the big one because I had to change the way notes are represented. Now you can change any note to be sharp or flat by holding ctrl and clicking it. You can also use the **j** keyboard shortcut to cycle through the options on the selected note.
The unfortunate side effect of this PR is that any existing songs will no longer sound right after this is merged. ah, the dangers of living on the bleeding edge.
I will be opening a corresponding pxt-common-packages pr momentarily
=> Add toggle for music editor bass clef and better support for sharps/flats

webapp/src/marked.tsx
Possible quick fix for https://github.com/microsoft/pxt-arcade/issues/5490, since firefox doesn't support picture in picture api / have there own way to do it. 
We'd have to write a quick markdown page at `/firefox-picture-in-picture` which I didn't do, but would likely largely be similar to https://support.mozilla.org/en-US/kb/about-picture-picture-firefox
=> add help button for how to pop out video in firefox

localtypings/pxtpackage.d.ts, theme/home.less, webapp/src/projects.tsx
Needed to make these changes so that I could add a multiplayer icon to the code card for the new multiplayer row on the Arcade home screen (https://github.com/microsoft/pxt-arcade/pull/5520)
=> Add custom action icon for code card

webapp/src/components/assetEditor/assetPalette.tsx
The selected colors are now preserved when a custom palette is created via an edit to a builtin palette.
Closes #https://github.com/microsoft/pxt-arcade/issues/5503
=> Fix bug where first color change of builtin palette doesn't save

theme/highcontrast.less
* fix https://github.com/microsoft/pxt-arcade/issues/5388. card class on the icon was colliding with the big ole codecard class that's used all over the place, easiest to just say "apply only to things that aren't icons"
* fix another bug that I didn't see an issue for; the bubbles were disappearing 
so now fixed:
=> Tutorial high contrast bugs

multiplayer/src/components/HostGameButton.tsx
fix https://github.com/microsoft/pxt-arcade/issues/5336, I guess the line height was just getting set to something weird
=> make it so multiplayer sample games don't clip bottom of gs/ys

webapp/src/components/tutorial/TutorialCallout.tsx
fix https://github.com/microsoft/pxt-arcade/issues/5105
the issue is that react-common buttons swallow events by default, so we have to listen for the outside click in the bubbling phase to see when someone is interacting outside the screen - simulator clicks / download button side menu / etc were also not collapsing the hint.
@eanders-ms Probably not for this release but we should probably move your Popup class / `useClickedOutside.tsx` into react common and replace our other popups with it
=> handle outside clicks better in hint popup

multiplayer/src/services/gameClient.ts
fix for https://github.com/microsoft/pxt-arcade/issues/5531
I suspect this is the issue we were hitting with late joiners not getting the initial screen causing screen compression / partial screen updates to fail
here's a build: https://arcade.makecode.com/app/7b49972cc23786e9b7696c213f27dd03ddef93e7-82f76e9ff6--multiplayer (remember to not use the join link it gives you directly as that won't point you to the right build)
=> multiplayer: register both join handlers separately to avoid dropping msgs

theme/tutorial-sidebar.less, webapp/src/components/tutorialValidators.tsx
This adds a limit on the height of the code validation popup and adds a scrollbar around the hint blocks if it's needed. It also removes the border around the hint blocks and moves the popup to the right if we're in tablet mode.
Fixes https://github.com/microsoft/pxt-arcade/issues/5527
Fixes https://github.com/microsoft/pxt-arcade/issues/5530
Fixes https://github.com/microsoft/pxt-arcade/issues/5528
=> Limit height and add scroll bar for code validation popup

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorialValidators.tsx
We were seeing an issue with code validation, where after refreshing the page, the Next button in a tutorial no longer worked. To fix it, I've removed the caching of tutorial validators on the TutorialInfo and TutorialStepInfo objects.
When a tutorial is reloaded, these objects get serialized and then deserialized, but the "execute" method is not able to be stored in the serialized format, so it's lost in the process. As a result, when we try to call it, we get an error that it doesn't exist.
This cache isn't saving us from much work right now anyway (validation construction is relatively cheap), so I've opted to simply remove it. If we decide we need it later on, we could cache it elsewhere (like on the TutorialContainer itself) and make sure it's cleared/refreshed as needed.
Fixes …
=> Fix Tutorial Next Button After Refresh

multiplayer/src/services/gameClient.ts
Throwing up a build here since I think it's worth a bit of testing: https://arcade.makecode.com/app/a96a8a9ee5c0c294dc223795718b45eef90b5659-739e70271b--multiplayer?host=S72790-46070-28386-52415
I ran it with 4 connections on my pc (and 3 on pc / 1 on my phone) & exitted / reentered into the session about 40 times. I ended up getting screen artifacting 1 time (with my character 'set' mid right side of the screen while still moving on the other side - so something like the bits in that region were swapped), but that was when I had dev tools up / hit breakpoint on host while loading and I wasn't at all able to repro it. I think it's worth testing a bit :)
=> multiplayer reenable xor screeen diffs

localtypings/pxtarget.d.ts, pxtblocks/fields/field_note.ts, pxtcompiler/emitter/snippets.ts, pxtlib/service.ts, tests/blocklycompiler-test/commentparsing.spec.ts, tests/language-service/snippet_cases/paramOverride.py, tests/language-service/snippet_cases/paramOverride.ts, tests/language-service/test-package/basic.ts, webapp/src/components/musicEditor/utils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5416
This PR addresses 3 bugs with the music editor:
1. Fixes issue where drum notes couldn't be deleted
2. Fixes the rendering of the note editor when a min note is set
3. Adds the ability to override the snippet for a function parameter in the comment attributes of the declaration (part of the fix for https://github.com/microsoft/pxt-arcade/issues/5481)
=> A few music-related bugs

skillmap/src/components/RewardActions.tsx
We want it to be easy for users to get back to and play the game that they just created with the skillmap.
We are just opening the editor when this button is pressed for now because it is a quick solution. We might want to open a game with the share link or embed the simulator in a pop-up in the future.
Closes: https://github.com/microsoft/pxt-arcade/issues/5346
=> Skillmap: play game button added to reward node

pxtblocks/blocklyimporter.ts, pxtblocks/blocklyrenderer.ts
e.g. so if you have a template section in a tutorial like the following it starts off collapsed in order to 'hide' it from view at the start (or if you want to show it exists in a hint, but not in detail)
No bug associated, just a very quick feature that came out of a chat with kiki~
Maybe we could even emit this so collapsed / non collapsed state persists through compile / decompile ;)
=> add a flag to allow tutorials to show blocks collapsed in hints, template code

pxtlib/browserutils.ts
This change puts the `TutorialInfoIndexedDb` back to version 2. I had updated it to 3 in https://github.com/microsoft/pxt/pull/9300 but that isn't really necessary since we have null checks on the new field usage anyway, and the upgrade process was sometimes causing hangs.
The hang happens when another tab already has an open connection to the db and a new tab requests to upgrade it. The upgrade request just gets put into a pending state and never finishes, even if the original tab is closed again. It then stays in this state until the entire browser is closed. Requests from new tabs will similarly get stuck in the pending state behind the upgrade request, even if they're going back to the original version.
Fixes https://github.com/microsoft/pxt-arcade/issues/5540
=> Fix Hang on Tutorial Load

multiplayer/src/components/HostLobby.tsx, multiplayer/src/components/JoinCodeLabel.tsx, pxtlib/multiplayerUtils.ts, react-common/components/share/ShareInfo.tsx
This was an attempt to fix https://github.com/microsoft/pxt-arcade/issues/5500. It doesn't fix it, but seems like a change worth keeping. No need to use short links everywhere.
=> Support relative links in multiplayer urls

theme/blockly-core.less
I think white is a safe bet, since I believe the bubble's background is chosen based on the block color and it looks like we use white text for all the regular block text, too.
Before:
After:
Fixes https://github.com/microsoft/pxt-arcade/issues/4993
=> Make Block Errors Easier to Read

localtypings/pxtarget.d.ts, multiplayer/src/services/gameClient.ts, pxtlib/imageConverter.ts, pxtlib/service.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, theme/common.less, webapp/src/app.tsx, webapp/src/components/SimulatorPresenceBar.tsx, webapp/src/sidepanel.tsx, webapp/src/simulator.ts
Close https://github.com/microsoft/pxt-arcade/issues/5469
Adds a multiplayer bar underneath simulator when you're writing a multiplayer game so you can pretend to be someone else / preview what presence icons look like
Because there is lacking space in tutorials, I made a quick decision for now to just show it to the left
There was a little bit that I'm gonna try and rearrange, but I already rewrote where it was rendered (out of iframe to accommodate tutorials better) & where the data was stored (treating it similar to console logs / etc ends up way too clunky just to propagate a few images, and don't want to send out significant, root of react tree updates up to 120s and second and slow full editor perf). The current semi hacky version of latching it as a style var on root ends up …
=> Select active player in multiplayer mode

localtypings/pxtarget.d.ts, webapp/src/extensionsBrowser.tsx
- Adds a `builtinExtensionsLib` to the `PackagesConfig`
- Includes tags from builtin extensions to establish the categories/tags in the extension browser
Necessary to close https://github.com/microsoft/pxt-arcade/issues/4992
=> Categorize builtin extensions in the extension browser

react-common/components/share/ShareInfo.tsx
This partially addresses https://github.com/microsoft/pxt-arcade/issues/5447. I don't have an svg for the new icon yet, so I'll either add that in a future iteration or follow up with a separate PR once we get that.
Before:
After:
=> Move "Share to Kiosk" Button in Share Popup

react-common/components/share/Kiosk.ts, react-common/components/share/ShareInfo.tsx
Now giving feedback to users for different submission cases. 
**Empty Input**
I left it as doing nothing if there is nothing in the input, however, because I would imagine that this case is self-explanatory. I can add something here if we think it is valuable, though.
**Correct format, but errors on the backend (not found, etc.)**
Error notification in red; text changes between `kiosk code not found` and `something went wrong...` depending on the error received.
**Incorrect format (too few/many characters, non-alphanumeric)**
Error notification in red. 
**Successful Submission**
Info notification.
**Reasoning**
I know this really doesn't follow patterns for receiving feedback for input, but I don't think having text show up underneath the input field would be really appropriate for most …
=> Notifications added for kiosk submission errors

webapp/src/components/musicEditor/utils.ts
Fixing a little bug I just noticed. The bass clef wasn't automatically showing when there were notes in the bass clef for drums
=> Expand bass clef for drums as well

webapp/src/app.tsx
Finally fixes the problem where the serviceworker isn't reloading; I think at some point the initialization of the load event was moved below the auth code initialization, which was causing it to miss the window's load event
This puts us in a bit of a pickle.... Since the old "bad" payload was released in the last release there is no way I know of to force all of the existing clients to unregister the old serviceworker. As a result, nobody will get the updated payload from this release. That means everyone will be stuck on an old version of arcade unless they clear their browser storage (bad idea) or manually unregister the serviceworker (multi-step-process that involves the devtools). Not sure what to do here.
@abchatra it is ABSOLUTELY CRITICAL that this gets merged before release
=> Fix serviceworker race condition

multiplayer/src/components/ArcadeSimulator.tsx, multiplayer/src/epics/resumeGameAsync.ts, multiplayer/src/services/gameClient.ts
since messages can be dropped while sim is paused, propagate current user state.
(we only fire events when connected state changes https://github.com/microsoft/pxt-common-packages/blob/sendConnectionEventsOnScreenPop/libs/game/controller.ts#L257 so no worries on the event coming in twice)
=> propagate presence on host resuming pause game

react-common/components/share/ShareInfo.tsx
I noticed that if I tried to type in a kiosk id not in upper case, I would get a "Kiosk code not found" error. If I typed the same code in with upper case, it would successfully submit. It shouldn't matter if the user types in upper or lowercase, if it is the right sequence of characters, it should be a successful submit.
=> Kiosk share: input strings converted to upper case

webapp/src/app.tsx
fix https://github.com/microsoft/pxt-arcade/issues/5614, we don't load `shareEditor` in this iframe. These guards were added to just not crash here https://github.com/microsoft/pxt/pull/9214 when these were calls to methods on `shareEditor` vs just `setState`
You can test on the final level of this tutorial: https://arcade.makecode.com/app/e3ee7dc5421ae4217a36fe347cc69168ff9805fa-eed2f68d38--skillmap?debugCompleted=1#docs:/test/skillmap/mole
=> fix so presence bar shows up in multiplayer skillmap

webapp/src/components/tutorialValidators.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/5605
Not 100% consistent, but sometimes, if the user opens the answer key and then tries to proceed to the next step, validation will flag an error, even if the user has the correct code. This happens because, in this scenario, the call to Blockly.getMainWorkspace() sometimes doesn't return the user's actual workspace. Instead, it returns a workspace with no blocks in it.
To fix this, I've gotten rid of the call to Blockly.getMainWorkspace and instead grab it directly from the ProjectView editor (using an existing `getBlocksEditor()` function)
FWIW blockly docs actually suggest avoiding the getMainWorkspace method: https://developers.google.com/blockly/reference/js/blockly.getmainworkspace_variable
=> Fix Answer Key Causing Code Validation to Incorrectly Detect Error 

multiplayer/src/components/BetaTag.tsx, multiplayer/src/components/EditGameButton.tsx, multiplayer/src/components/GamePage.tsx, multiplayer/src/components/HostLobby.tsx, multiplayer/src/components/JoinLobby.tsx, multiplayer/src/components/JoinOrHost.tsx
Remove `[beta] multiplayer` label, remix game -> edit game
One more quick thing I just remembered we had talked about but didn't make it into the release was potentially giving a light border around the join code on the host page, so that it looks more like a button / less temptation to manually copy & paste to send it to friend; should I sneak that in as well or just leave it alone for this release?
=> Multiplayer quick UI updates

webapp/src/components/tutorialValidators.tsx
Fix Answer Key Causing Code Validation to Detect Error Incorrectly (#9346)
Not 100% consistent, but sometimes, if the user opens the answer key and then tries to proceed to the next step, validation will flag an error, even if the user has the correct code. This happens because, in this scenario, the call to Blockly.getMainWorkspace() sometimes doesn't return the user's actual workspace. Instead, it returns a workspace with no blocks in it.
To fix this, I've gotten rid of the call to Blockly.getMainWorkspace and instead grab it directly from the ProjectView editor (using an existing getBlocksEditor() function)
=> Fix Answer Key Causing Code Validation to Detect Error Incorrectly

pxtsim/embed.ts, webapp/src/app.tsx, webapp/src/components/SimulatorPresenceBar.tsx
requires https://github.com/microsoft/pxt-arcade-sim/pull/87, https://github.com/microsoft/pxt-common-packages/pull/1422
sends connected state re: https://github.com/microsoft/pxt-arcade/issues/5625. Also got the types for multiplayer messages in pxsim itself -- I'll dedup them with multiplayer app and pxt-common-packages separately as there are some slightly tedious null / undefined differences that will take up a lot more swaps.
This one just adds the connect message sending, as I think we still need to talk more on how to handle testing disconnection -- but implementing it in a way that makes it hard to test player 2 interacting with player 3 feels wrong / kindly handling disconnection & reconnection are much more 'advanced' scenarios than typical multiplayer stuff
quick test …
=> send connection message when user selects presence icon

multiplayer/src/components/HeaderBar.tsx, multiplayer/src/components/JoinOrHost.tsx, multiplayer/src/util/index.ts
Made targeted fixes to the multiplayer header bar so that the org logo and profile pic don't get squished on mobile.
I would have liked to tighten up the spacing between menu items, but doing so would require changes in react-common, and the effects would be felt in webapp, skillmap, etc. We can tackle this in another pass.
Fixes https://github.com/microsoft/pxt-arcade/issues/5372
=> multiplayer: responsive layout improvements

pxtsim/embed.ts, webapp/src/app.tsx, webapp/src/components/SimulatorPresenceBar.tsx
cherry-pick https://github.com/microsoft/pxt/pull/9351 to send user presence in editor more similarly to how it is handled in webapp. the diff in pxsim/embed.ts is just mirroring over existing types for multiplayer
=> [stable8.5] send connection message when user selects presence icon

pxtlib/react.ts, webapp/src/app.tsx, webapp/src/blocklyFieldView.tsx, webapp/src/components/musicEditor/MusicEditor.tsx, webapp/src/components/musicEditor/keyboardNavigation.ts
Fixes copy and paste for the music editor and also stops the simulator from starting if one of the react field editors is open.
=> Music editor hot fixes

tests/tutorial-test/baselines/codeValidation.json, tests/tutorial-test/cases/codeValidation.md
This test has a global BlocksExistValidator specified in the tutorial markdown as well as a local disable in one step, and it ensures that both get parsed correctly into validator metadata.
I basically copied the files from the steps test and just added some validation markdown, too.
Fixes https://github.com/microsoft/pxt-arcade/issues/5542
=> Add a Test for Code Validation

webapp/src/components/musicEditor/MusicEditor.tsx, webapp/src/components/musicEditor/Workspace.tsx, webapp/src/components/musicEditor/types.d.ts, webapp/src/components/musicEditor/utils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5596
Stop aggressively snapping the events to the grid. Now just note add and note drag are grid aligned
=> Better handling of click events on the music workspace

webapp/src/components/assetEditor/assetPalette.tsx
closes https://github.com/microsoft/pxt-arcade/issues/5632
We've determined the warning exit modal is not necessary since all changes to custom palettes are saved, regardless of whether the user applies it to the project.
=> Remove exit modal from color palette

webapp/src/components/assetEditor/assetCard.tsx
closes https://github.com/microsoft/pxt-arcade/issues/5659
=> Add music icon for song assets in asset editor

pxteditor/monaco-fields/field_musiceditor.ts, webapp/src/components/musicEditor/keyboardNavigation.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5653
I broke the regex when I did the playable change in pxt-common-packages and forgot to fix it!
=> Fix monaco field editor regex and support ctrl+A

pxteditor/monaco-fields/field_musiceditor.ts, webapp/src/components/musicEditor/keyboardNavigation.ts
* fix monaco field editor regex
* also fix comment
* Support ctrl+A in music editor
=> [Stable8.5] Cherry pick regex fix and ctrl+A

webapp/public/asseteditor.html, webapp/public/index.html, webapp/src/assetEditor.tsx, webapp/src/components/ImageFieldEditor.tsx
This PR includes the following changes for the asset editor page:
1. Enables the gallery (but not "my assets")
2. Fixes the icons not showing up in music editor
3. Adds support for custom palettes
=> Add a few missing features to the asset editor page

pxtlib/initprj.ts
ignore generated .pxt files, and default 'on' for the `explorer.excludeGitIgnore` setting which makes explorer not show built files can drop that second one if we don't like that or think it's potentially confusing? I guess the thing to note is that it'll hide pxt_modules unless you e.g. go to definition which might be controversial:
test repo: https://github.com/jwunderl/ignore-me-testing-2
=> add default .pxt git ignore, set excludeGitIgnore setting

pxtlib/initprj.ts
using files exclude instead of the gitignore setting so built will still show up. (I tried `"**/built": false` but that just got ignored)
=> just ignore pxt_modules / .pxt, not /built

localtypings/pxtmusic.d.ts, pxtlib/music.ts, pxtsim/simlib.ts, pxtsim/sound/metronome.ts, pxtsim/sound/sequencer.ts, pxtsim/sound/song.ts, webapp/src/components/musicEditor/MusicEditor.tsx, webapp/src/components/musicEditor/Staff.tsx, webapp/src/components/musicEditor/keyboardNavigation.ts, webapp/src/components/musicEditor/playback.ts
This moves the song sequencer into pxsim and cleans up the code a bit. I'm doing this so that I can improve playback in the sim; right now the timing in the game is *not great*. I will have a corresponding pr in pxt-common-packages that supports this in the browser sim.
As a bonus, I also added support for setting the volume for each track/drum sound. I haven't surfaced this anywhere yet but I have nefarious plans.
This PR looks scarier than it is; it is mostly just moving code around.
=> Refactor song sequencer/playback into pxsim

webapp/src/marked.tsx
fix https://github.com/microsoft/pxt-arcade/issues/5671
For reference, the issue is that the namespace in ts is `Array` but in blocks we've always used `Arrays` -- so it's one of the special cased ones in the first place so the namespace opening logic didn't work with either (if you did array it'd get wrong color & wouldn't be able to open the category as the name didn't match, if you did arrays you'd get right color but we wouldn't see it as a namespace)
probably should port this. I put up an uploadtrg to test it real quick https://arcade.makecode.com/app/78fa5169e463d537c5233eda10a1bcf8597ee579-09f260dd5e--skillmap?debugCompleted=1#space
=> fix arrays inline snippets

cli/cli.ts
we had some logic to minify json for prod environments but we must have stopped setting the 'production' env flag in our builds at some point (probably when we moved to github actions, because it's only relevant exactly for minifying js?). Anyway, this is the only place this field is actually read: https://github.com/microsoft/pxt/blob/minifyTargetJson/cli/nodeutil.ts#L619, which says to minify json produced in our build (e.g. `target.js` and `target.json`). So setting this at the beginning of ci should cut off about 3mb of arcade's target.js/json (~~ 11mb -> 8mb) (which are the same things besides target.js setting it to a variable), which brings the gzipped size down from ~2.1mb to 1.9mb when I did a quick check. 
It's worth noting target.js(on)? is super required / part of the initial …
=> make it so stringify minifies json for prod

webapp/src/assetEditor.tsx, webapp/src/components/ImageEditor/ImageCanvas.tsx
I would not be surprised if this change fixes all of our "blockly is swallowing our keyboard events" bugs for the image/tilemap/animation editor.
This PR does 2 things:
1. Makes the image canvas focusable
2. In the --asseteditor page, map ctrl+s to the same callback as the done button
=> Focus image canvas and support ctrl-s in asset page

react-common/styles/controls/Checkbox.less
The size of the email checkbox would change based on the size of the window. A checkbox like that is so small that it doesn't need to be responsive, so I just set the size to a fixed rem. It will always look the size shown in the picture. 
Closes https://github.com/microsoft/pxt-arcade/issues/5687
=> Email checkbox on profile page now a set size

theme/common.less
Noticed this while touching-up layout for microbit, the mini-playable sim would overlap the scrollbar in desktop mode. Then in mobile and table mode, it was actually a bit far away from them.
| Scenario | Before Fix  | After Fix |
| ------------- | ------------- | ------------- |
| Desktop Arcade | <img width="257" alt="image" src="https://user-images.githubusercontent.com/69657545/219152245-06382846-911d-4ea8-a911-206611694d8b.png"> | <img width="271" alt="image" src="https://user-images.githubusercontent.com/69657545/219146444-3c698110-be9e-4ee9-aa89-8cda73ea9bee.png">  |
| Desktop Microbit | <img width="260" alt="image" src="https://user-images.githubusercontent.com/69657545/219151428-0b0c32f5-a02c-4747-a04f-9b11d086d79f.png"> | <img width="289" alt="image" …
=> Prevent Mini-Playable Sim from Overlapping Scrollbars

theme/tutorial-sidebar.less
The sidebar for microbit is larger than the sidebar for arcade. TBD if it should stay that way, but regardless, I think it's better to make the code validation popup position reactive to changes in the sidebar width.
Without change:
With change:
=> Adjust code validation popup position based on sidebar

pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_tileset.ts, pxtblocks/fields/field_utils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5723
Not sure when this got broken, but for some reason we stopped adding the tiles referenced by tileset blocks to the projectReferences array that we use to prevent deletion.
=> fix blockly exception when deleting tile referenced by tileset field

pxtlib/package.ts
This bug was making it impossible for me to test multiple local extensions together, so here is a partial fix. It addresses a gap in the logic to check a project's dependencies for conflicts. We need to consider that a dependency might be a local project reference.
This fix is "just enough" to get it working. A more complete solution would require some refactoring to allow for the loading of the local project's dependencies and walking those.
Fixes https://github.com/microsoft/pxt-arcade/issues/5509
=> allow local projects in dependency check

localtypings/pxtblockly.d.ts, pxtblocks/blocklyloader.ts
Fixes microsoft/pxt-arcade#5716
Today, we can only search forward in our blockly editor:
Updating this means diverging slightly from the library we use, [blockly-workspace-search](https://github.com/google/blockly-samples/tree/master/plugins/workspace-search).
Overwrite the `onKeyDown_` method in `PxtWorkspaceSearch`, use _almost_ the exact same code as the source, call `previous()` when you press enter while holding shift.
Original code:
https://github.com/google/blockly-samples/blob/c190eca57865090d9b6027ae4af7eecf425396e8/plugins/workspace-search/src/WorkspaceSearch.js#L376-L389
**Note:** I did get rid of some code from the original method, but that code path was never hit because `searchOnInput` defaults to true and we never change the value.
=> Shift + Enter Searches Backwards in Blockly

webapp/src/assetEditor.tsx, webapp/src/components/ImageEditor/BottomBar.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx, webapp/src/components/ImageFieldEditor.tsx, webapp/src/components/MusicFieldEditor.tsx, webapp/src/components/musicEditor/EditControls.tsx, webapp/src/components/musicEditor/MusicEditor.tsx
was this about how you'd want this to happen? Instead of a `setInterval` I suppose I add could add a field in the image editor itself to make it happen on each edit that goes in the undo/redo stack but not sure there'd be much difference there in the end.
~(I suppose might be worth renaming the `onDoneClick` now that it's gone from that to 'on done click, ctrl+s clicked, or we noticed it updated')~ cut out done, probably need to look at a throttle on the vscode ext side when saving
=> auto save assets for vscode ext

theme/greenscreen.less, theme/highcontrast.less, theme/toolbox.less, theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/greenscreen.tsx
The new tutorial backgrounds weren't being set to transparent when in greenscreen mode.
When I made the switch, I also noticed green screen mode was adding a scroll bar that allowed the user to scroll the entire site horizontally. This was happening because the video element that gets created was larger than the site itself (it gets scaled up to fill the screen, but this usually means `width` becomes larger than 100% so `height` can be 100% while maintaining the correct aspect ratio). To avoid this behavior, I set 100% `width` in the `video` element itself rather than the css, then cap the `width` to 100% in css and set `object-fit` to crop the `video` element appropriately, so it doesn't shrink down again when css limits its size.
I also noticed that, since the tutorial pane extends 100% …
=> Make Tutorial Background Change with Green Screen Mode

webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorial/TutorialStepCounter.tsx, webapp/src/components/tutorial/TutorialValidationErrorMessage.tsx, webapp/src/components/tutorialValidators.tsx
1. Added a field to several events which records how many times the user has tried to click next and encountered an error on the step. Basically, how many failed attempts have they made. This will simplify queries and I think it will be helpful in understanding if users are actually getting the error popup and fixing things, or if they just see the popup a few times and continue anyway.
2. Remove a redundant event that wasn't firing anyway due to a bug.
3. Fix a bug where two tutorial.next events were firing when the step counter was used.
=> Code Validation Telemetry Improvements

webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorial/TutorialStepCounter.tsx, webapp/src/components/tutorial/TutorialValidationErrorMessage.tsx, webapp/src/components/tutorialValidators.tsx
Port of https://github.com/microsoft/pxt/commit/6d731ade66e4f518b091b35af498f7c0506d296f
1. Added a field to several events which records how many times the user has tried to click next and encountered an error on the step. Basically, how many failed attempts have they made. This will simplify queries and I think it will be helpful in understanding if users are actually getting the error popup and fixing things, or if they just see the popup a few times and continue anyway.
2. Remove a redundant event that wasn't firing anyway due to a bug.
3. Fix a bug where two tutorial.next events were firing when the step counter was used.
=> Port to Stable8.5: Code Validation Telemetry Improvements

theme/image-editor/bottomBar.less, webapp/src/components/ImageEditor/BottomBar.tsx, webapp/src/components/ImageEditor/ImageEditor.tsx
Fixes https://github.com/microsoft/vscode-makecode/issues/100
checks to see if the done button is hidden and then doesn't hide the asset name
also fixed a random exception while i was in there; we weren't checking if assetname was defined before calling trim
=> don't hide asset name in asseteditor page

webapp/src/assetEditor.tsx, webapp/src/components/ImageEditor/util.ts
Fixes https://github.com/microsoft/vscode-makecode/issues/92
Fixes https://github.com/microsoft/vscode-makecode/issues/94
The issue was that we delay creating a real asset until we receive a save message from outside the iframe, so autosave was saving the "fake" asset and hilarity ensued.
Also fixes the issue where dragging a marquee leaves the original image behind
=> Fix autosave weirdness in asset editor page

webapp/src/assetEditor.tsx
Fixes https://github.com/microsoft/vscode-makecode/issues/95
Just gotta "inflate" the tilemap with all of the tiles in the project before opening it.
Remember to inflate your tiles, kids!
=> Inflate tilemaps before opening in asset editor page

localtypings/pxtpackage.d.ts, pxtlib/package.ts, pxtlib/tilemap.ts
@kiki-lee wanted to put some gallery images for a tutorial but they don't show up in the background image gallery; currently the only way to sneak em in without running the cli tool would be via the assetsjres but that ends up creating ~40-200k long lines which can break things.
Basically, make https://github.com/jwunderl/arrow-images/blob/master/images.g.jres#L11 work to define tags for assets (I editted this by hand (don't tell anyone >.>) but we should probably just add the option to list out tags somewhere in the arcade-sprite-pack tool)
test build https://arcade.makecode.com/app/b7117e402ed06a7aaeda7ead979300400be20fee-8a1cae52b6#pub:_F3kbef0rbhzE
=> add tags field so .g.jres can have gallery tags

pxtlib/tilemap.ts
Fixes https://github.com/microsoft/vscode-makecode/issues/130
The issue, in a nutshell:
1, We create a song (mySongs.Song1)
2. We emit that with the wrong namespace (myImages.Song1)
3. The user creates a new song
4. Since mySongs.Song1 is not used, we use that id
5. We emit again, the new asset goes to the wrong namespace and overwrites the original
=> Don't emit songs in the 'myImages' namespace

theme/image-editor/imageEditor.less, webapp/src/assetEditor.tsx, webapp/src/components/ImageFieldEditor.tsx
fix https://github.com/microsoft/vscode-makecode/issues/119
Also fixes some mobile view / thin desktop view sizing issues in gallery filter as it didn't look good in the thin webciew, and makes the section scrollable when it doesn't fit so it's still possible to select things when you have  a lot of categories. Probably looking at pr as separate commits is easiest as two of them were just moving some css rules below the ones they're overriding / removing unneeded importants now that the cascading order was correct
and adds a flag to the image field editor that makes it so background / tile / dialog will show up as options in the filter for vscode extension. Was just thinking again and might be worth throwing that flag on when it's loading the monacofieldeditor as well?
here's a build …
=> Fixes for filters in asset editor page (mobile view, read out tags from ts file)

theme/image-editor/imageEditor.less
quick follow up to https://github.com/microsoft/pxt/pull/9423 -- I was playing around on very thin views and the words got a little closer than I wanted, so just give it a wrap / some gap
build: https://arcade.makecode.com/app/3a4976d9a846afecd7a9248ba447046535e8b16b-4d237bd7dd
and anywhere it's wide enough display is normal:
=> one more small adjustment for very thin phones

package.json, pxtlib/analytics.ts, webapp/src/app.tsx
Add a url parameter (`consoleticks`), which will send all tick events to the console. I find this makes it much easier to test and debug telemetry events.
It comes with a two "modes". By default (`consoleticks=1` or `consoleticks=verbose`), it will print output like so:
```15:34:29 - Tick - activity.autorun {"editor":"blocksArea"} <no opts>```
You can also specify `consoleticks=2` or `consoleticks=short` to get a more abbreviated output:
```activity.autorun {"editor":"blocksArea"} <no opts>```
=> Enable Logging Tick Events to Console with URL Parameter

react-common/components/controls/Modal.tsx, react-common/styles/controls/Input.less
Fixes https://github.com/microsoft/pxt-arcade/issues/5701
Fixes https://github.com/microsoft/pxt-microbit/issues/4997
At first glance, high contrast seemed to be working, but that was only the case if you had just turned high contrast on. If instead, you already had high contrast on from a previous session or reloaded the page, the palette editor and extensions page would not be in high contrast mode.
=> Fix high contrast issues for palette editor and extensions page

ThirdPartyNotice
Fixes https://github.com/microsoft/pxt-backend/issues/776
Done manually by searching for each of our dependencies in our current ThirdPartyNotice. There's a lot more that we don't have, see below for details.
These are (roughly) the npm libraries we don't have licenses for. They're all under the `devDependencies` element in package.json. Is there a reason we don't already have licenses for many of these? Seems weird that so many would have slipped through.
```
"@microsoft/eslint-plugin-sdl": "^0.1.5",
"@types/chai": "4.0.6",
"@types/fuse": "2.5.2",
"@types/highlight.js": "9.12.2",
"@types/jquery": "3.3.29",
"@types/marked": "0.3.0",
"@types/mocha": "2.2.44",
"@types/node": "10.14.2",
"@types/react": "17.0.50",
"@types/react-dom": "17.0.17",
"@types/react-modal": "3.13.1", …
```
=> Add missing third party licenses

theme/common.less
changing the selector from `#editorSidebar` to `.editor-sidebar` made this one have less specificity then a few other rules / become tiny. Might want to check on the rules that were changed by this as I think some others slipped through too (e.g. the section was scrollable before too, so there's probably a selector that got overridden making https://github.com/microsoft/pxt/pull/9437/commits/08cd330479b23a05d5ba7fc4e3ff85980af6977b necessary)
=> fix tiny width explorer
