microsoft/pxt

webapp/src/sidepanel.tsx
I recently added a check in the sidepanel to display the minisim if we're not in sim-sidebar view, but I had forgotten to only do so in tutorial mode, so it was happening even in a regular projects when the user refreshed the page.
Fixes https://github.com/microsoft/pxt-arcade/issues/5814
=> Fix Sim Layout on Page Refreshed

theme/common.less, theme/greenscreen.less, theme/highcontrast.less, theme/tutorial-sidebar.less, theme/tutorial.less
This change fixes https://github.com/microsoft/pxt-microbit/issues/5003. The fix for this happens in `common.less` around line 1419.
It also goes through and adds `#simulator` to the places where I used .editor-sidebar so that the css specificity is closer to what it was before my changes in https://github.com/microsoft/pxt/pull/9430. It used to be id-level and I changed it to class level, which had layout side-effects because the priority of certain styles was now different. The hope is that this will reduce the likelihood of those bugs.
=> Hide Tutorial Instructions in Fullscreen Mode and Fix CSS Specificity 

react-common/components/controls/TeachingBubble.tsx, webapp/src/components/onboarding/EditorTour.tsx, webapp/src/container.tsx
This PR adds telemetry for all button clicks within the editor tour: next, back, exit, and finish.
The data passed includes:
- the title of the content
- stepDuration (time in s the user has been on this step)
- tourDuration (time in s since the user started the tour)
- [current] step
- totalSteps
Example ticks:
=> Editor Tour: add more telemetry

.github/workflows/codeql-analysis.yml
re: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
=> maybe fix codeql

webapp/src/sidepanel.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5026
The check that runs when sidepanel receives new props was causing the minisim to get displayed on javascript and python tutorials, but if we're in sim-sidebar layout, it should get shown on the sidebar instead. I simply forgot to update this check to account for the new layout, so I've added a condition to ensure it only shows the minisim if we're not in "sim-sidebar" mode.
=> Fix Minisim Display in Python/JS tutorials.

theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialStepCounter.tsx
This addresses the following tutorial layout issues:
1. Makes Next and Back buttons the same height (fixes https://github.com/microsoft/pxt-microbit/issues/5029).
2. Aligns top of hint and next/back buttons, and shrinks hint button to be the same size as the next/back buttons (fixes https://github.com/microsoft/pxt-microbit/issues/5030).
3. Reduce space between hint button and popup (fixes https://github.com/microsoft/pxt-microbit/issues/5031).
Try it here on Micro:bit: https://makecode.microbit.org/app/1b7457b8c6c200710558a2c93bb057d5a46513fc-e3db915f82
And here on Arcade: https://arcade.makecode.com/app/1cff0a1e2c5efd69dd0811a54ec7ccb282cbfb0e-24044b6328
=> Fix Tutorial Layout Bugs

authcode/src/services/auth.ts, multiplayer/src/services/authClient.ts, pxtlib/auth.ts, react-common/components/profile/Profile.tsx, skillmap/src/lib/authClient.ts, webapp/src/auth.ts, webapp/src/cloud.ts, webapp/src/identity.tsx, webapp/src/workspace.ts
This set of changes looks big, but the bulk is contained in `pxtlib/auth.ts`. The main purpose here is twofold:
- be tidier about cleaning up local auth state when logging out.
- be more resilient against stale auth state that might have been left over from a previous session.
This change also contains several important bug fixes:
- Fixes https://github.com/microsoft/pxt-arcade/issues/3878
- Fixes an issue where if a cloud project is synced down and any error occurs while processing it, some number of other cloud projects will not be listed in My Projects.
- Fixes the infinite reload issue @srietkerk saw yesterday in microbit.
Once merged, I will bump beta and test skillmap and multiplayer in the beta channel. Skillmap + auth is especially difficult to test effectively on localhost.
=> client-side auth cleanup

react-common/components/controls/TeachingBubble.tsx, react-common/styles/onboarding/TeachingBubble.less, webapp/src/components/onboarding/EditorTour.tsx
This PR introduces the following changes:
- transition animation for teaching bubbles
- larger font size
- border around bubble instead of drop shadow
- removed toolbox from being highlighted in the workspace callout
- made tour in order of anticipated use (toolbox -> workspace -> simulator -> share -> download)
- (Jacqueline) updated content to be more concise
- increased padding/margin for readability
- aligned lower edge of button and progress indicator / step count
- lighter font color for steps
Closes https://github.com/microsoft/pxt-microbit/issues/5009, closes https://github.com/microsoft/pxt-microbit/issues/5013
Try it out here: https://makecode.microbit.org/app/145250d33320d7b8b2a9b197a224a222bdeda9b2-8b591e28cd
**Still need to do some refactoring to clean up the teaching bubble …
=> Editor tour / onboarding feature: styling and animation

localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxteditor/editor.ts, pxtlib/gallery.ts, pxtlib/tutorial.ts, pxtrunner/runner.ts, pxtsim/embed.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/simulator.ts
Allow setting a theme in tutorial / pxt.json, and send that to the sim: https://arcade.makecode.com/app/777ae82cacd76f735a2b99ee0ee53328ed69906c-7731d4169b
w/ tutorial loading bubblegum theme:
https://arcade.makecode.com/app/777ae82cacd76f735a2b99ee0ee53328ed69906c-7731d4169b#tutorial:44182-86552-65080-62109
loading normal project w/ theme set:
https://arcade.makecode.com/app/777ae82cacd76f735a2b99ee0ee53328ed69906c-7731d4169b#pub:_gmeV5DWmEfKf
re: https://github.com/microsoft/pxt-arcade/issues/5819, I took a look around and this should be very simple to implement, but I didn't attach anything for that in this pr / I'll take a look again for next release -- the code is easy but the ux flow / user testing will take a bit and we can't fit that in for a hotfix. I'll find some time to put in …
=> Allowing setting a theme for sim (& palette) from tutorial md

react-common/components/controls/TeachingBubble.tsx, react-common/styles/controls/Button.less, react-common/styles/onboarding/TeachingBubble.less
This PR improves:
- animation by making it faster and including width and height in transitions
- visibility of tabbing / focus on buttons (closes https://github.com/microsoft/pxt-microbit/issues/5012)
- screen reading (closes https://github.com/microsoft/pxt-microbit/issues/5014)
- tested with Narrator and NVDA
- it's not perfect, but it should read all the content now
Try it out: https://makecode.microbit.org/app/ad2675c5dac61c2bed8b9b8816708b290fda6d92-5997b1ced2
=> Onboarding tour accessibility fixes, animation improvement

pxtblocks/blocklyloader.ts
There are a couple of strings from the "Variables" and "Functions" flyouts that aren't getting to Crowdin. Hope this is the correct way to get them into strings.json.
RE: https://crowdin.com/project/makecode/discussions/119
=> Add flyout labels to the translate path

react-common/components/animations/Confetti.tsx, react-common/components/controls/TeachingBubble.tsx, react-common/styles/animations/Confetti.less, react-common/styles/onboarding/TeachingBubble.less, react-common/styles/react-common.less, skillmap/src/components/AppModal.tsx, skillmap/src/styles/modal.css, webapp/src/components/onboarding/EditorTour.tsx
This PR adds:
- Confetti as a react common component (this code comes from Shannon's implementation within skillmaps)
- Final congrats step in tour with confetti
- Initial transition animation for cutout (full screen to toolbox)
Try it out: https://makecode.microbit.org/app/7ce1ca36335e9776ca7ab2161f3747d9689808da-3c95e373c1
=> Editor tour: add congrats with confetti

webapp/src/marked.tsx
re: email, support ` ``||abc.def||`` ` syntax again
=> support ||namespace.words|| syntax as a backup

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/tagged_template_multiple.blocks, tests/decompile-test/cases/tagged_template_multiple.ts, tests/decompile-test/cases/testBlocks/templateStrings.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5738
Adding support for multiple tagged templates to decompile a parameter from; the music editor supports two:
```
assets.song`name`
hex`1234`
```
=> support decompiling more than one tagged template for a parameter

cli/cli.ts, localtypings/pxtarget.d.ts
It looks like we only actually create output from this in sim only targets, so add a flag to skip it -- it takes a few seconds and generates about 150 lines of output / couple dozen spurious errors in arcade (https://github.com/microsoft/pxt-arcade/actions/runs/4704080574/jobs/8343339084#step:6:27 down to where it first says 'looking for tutorial markdown')
=> add flag to skip simshims check

localtypings/pxtarget.d.ts, pxtlib/cmds.ts, pxtlib/webusb.ts, theme/common.less, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/dialogs.tsx, webapp/src/editortoolbar.tsx, webapp/src/webusb.tsx
When pressing download, show pairing flow first to encourage webusb use.
* if they exit the flow (click outside, x) it will bail out and generate a hex file
* if they go through the pairing flow as normal and end up not connecting, there is a secondary option for 'download as file' which will generate the hex file && not show pairing prompt automatically again (in memory) (similar to a "don't show this again" toggle, but in this case we have to give an indication that clicking it will still download as well)
* Above two points will probably be fiddled with after testing in beta to get something that feels right without making it too easy to accidentally not pair
* Minor tweaking of the download completed dialog to ideally make webusb pairing a bit more appealing
* label from new to …
=> Prioritize webusb downloads when available

theme/tutorial-sidebar.less
Moves the immersive reader button a little to the left so it doesn't overlap with the scrollbar. Also had to adjust the margin on the tutorial content text so it doesn't overlap with the reader button.
Fixes: https://github.com/microsoft/pxt-microbit/issues/5040
With fix:
=> Move Immersive Reader Button to Avoid Scrollbar Overlap

localtypings/pxtpackage.d.ts, pxtlib/package.ts, pxtlib/spriteutils.ts, pxtlib/tilemap.ts, webapp/src/package.ts
This PR adds a field to pxt.json that allows you to turn a project into an asset pack.
When the field is set, we do the following things:
1. Remove all files except for *.jres
2. Remap all of the asset ids to be under a new namespace
3. Add a gallery.ts file that declares variables for all of the assets, allowing you to reference them in TS as well
The namespace we generate is based on the key for this dependency in the project pxt.json. When referencing a package in a tutorial it is very important that you make the id in the `````` ```packages`````` block match the id field in the pxt.json of the package to avoid weird bugs.
For example, if the imported project is named "my asset pack", then the namespace for referencing the assets will be "my_asset_pack".
=> Allow projects to be imported as asset packs

localtypings/pxtpackage.d.ts, pxtlib/package.ts, pxtlib/tilemap.ts
This is an extension to my asset pack pr that allows for projects that import dependencies to declare those dependencies to be asset packs. it looks like this:
```
{
"name": "Untitled",
"description": "",
"dependencies": {
"device": "*",
"tagged-assets": "pub:37366-48747-84953-13766"
},
"files": [
"main.blocks",
"main.ts",
"README.md",
"assets.json"
],
"preferredEditor": "tsprj",
"assetPacks": {
"tagged-assets": true
}
}
```
Also added tag emitting to the declaration file generated for asset packs. If tags are not specified in the jres, i check the name of the asset for "dialog" or "background" and add those tags if missing.
=> Allow projects to declare dependencies to be asset packs and emit tags

pxteditor/editor.ts, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/gitjson.tsx, webapp/src/identity.tsx, webapp/src/projects.tsx
Add a button at the bottom of the screen to sign out of GitHub:
Arcade
Microbit
I changed the wording from "Unlink" to "Disconnect" because it made more sense to me. Curious what others think.
Resolves https://github.com/microsoft/pxt-microbit/issues/4398
=> Add "Disconnect GitHub" button to GitHub screen

localtypings/pxtarget.d.ts, theme/common.less, webapp/src/editortoolbar.tsx, webapp/src/webusb.tsx
Simplifying webusb pair flow -- starting from discussion from https://github.com/microsoft/pxt/pull/9464#issuecomment-1511822423 down. image changes are in an associated pxt-microbit pr~
No build because images have to be checked in, so extra details on flow below
* when the download button will started you into the pairing flow, don't show any icon; icon will fill in when the user either successfully pairs or selects to download file in pairing flow
* remove text from first modal, expand title, large gif front and center. Also makes this one **not** have an escape button, as first reaction a lot of users have is accidentally clicking out and getting lost / missing things; they have to click 'next'
* pairing step: simplify text, make image focus only on computer where action is happening. …
=> Webusb pairing simplification

localtypings/pxtarget.d.ts, webapp/src/sidepanel.tsx
Adding the `showOpenInVscode` flag so that we can avoid showing this button in microbit.
closes https://github.com/microsoft/pxt-microbit/issues/4979
I'll have another PR shortly to add the flag and set to true for Arcade.
=> Add open in vscode flag

webapp/src/tsworker.ts
Currently, we're showing deprecated apis in ts completions; e.g. `tiles.setTilemap` is shown which was deprecated in favor of `tiles.setCurrentTilemap`: 
vs with this:
I think there is some race condition where we don't attach the info correctly so sometimes we don't actually apply the filters, but it seems rare / would affect this whole fn anyways (most likely just before the project is fully loaded / etc type thing)
=> elide hidden and deprecated apis from ts completions

pxtlib/initprj.ts, webapp/src/gitjson.tsx, webapp/src/workspace.ts
When integrating a blocks project with GitHub, we add some pngs of the blocks to the repo (showing either the entire canvas or just the most recent diff). They look nice in the README, but are a source of problems for collaboration via GitHub. These are binary files, which make them a guaranteed source of merge conflicts when more than one user is committing to the repo.
I also removed the build status badge because it's never worked for me. If you know what the url should be, please let me know and I'll update it.
Test target for **microbit**: https://makecode.microbit.org/app/7881dff3cd82ba086e640657975c2cfb0eb3d4d9-df8e864a28
Test target for **Arcade**: https://arcade.makecode.com/app/d6e06a69c459bfeb811db0abe049789288cf62f8-58b4692010
Fixes …
=> GitHub Integration: Don't commit block pngs to repo

.vscode/settings.json, pxtlib/auth.ts, webapp/src/projects.tsx
Also in this PR: vscode flags to disable auto-formatting
Fixes https://github.com/microsoft/pxt-microbit/issues/5079
Fixes https://github.com/microsoft/pxt-microbit/issues/5076
=> Fix for high-contrast and language settings when not signed in

backendutils/tsconfig.json, cli/cli.ts, docfiles/pxtweb/tsconfig.json, gulpfile.js, pxtblocks/tsconfig.json, pxtcompiler/tsconfig.json, pxteditor/tsconfig.json, pxtlib/tsconfig.json, pxtpy/tsconfig.json, pxtrunner/tsconfig.json, pxtsim/tsconfig.json, tests/blocklycompiler-test/tsconfig.json, tests/blocks-test/tsconfig.json
TypeScript 5.0 deprecates tsconfig's "out" compiler option in favor of "outFile". Even though we don't yet use TS5, VSCode recently started flagging this as an error in some of pxt's tsconfig.json files. This is a fix to remedy that. This change must also be made in all target repos, and pxt-arcade-sim.
Reference: https://github.com/microsoft/TypeScript/issues/51909
=> [pxt] Fix deprecation of "out" option in tsconfigs

webapp/src/cmds.ts, webapp/src/container.tsx, webapp/src/dialogs.tsx, webapp/src/editortoolbar.tsx, webapp/src/webusb.tsx
fix https://github.com/microsoft/pxt-microbit/issues/5102
expanded on the text a bit: 
open to any suggestions if it's still not clear; would prefer to avoid making it any longer / adding pictures if possible as kids in the user testing were very much distracted on this step when there were images /  didn't read the lengthy spots of text.
=> Expand on the failure step text a bit

webapp/src/webusb.tsx
fix https://github.com/microsoft/pxt-microbit/issues/5099
wasn't using the result from the recursive call, a little interesting this has stuck around for > a year without being noticed but I guess not that many people were using webusb and failing the first time / succeeding the second.
=> webusb try pair again: return the recursive call

pxtblocks/fields/field_imagedropdown.ts
This change is related to this PR to correct the misspelling of "eighth" note: https://github.com/microsoft/pxt-microbit/pull/5107
Now any JavaScript using the old spelling will convert to blocks and show up as text instead of a symbol. Without this fix, converting to blocks would show the default heart icon. Note: upgrade rules will correct the spelling in any old code and display the eighth note symbol. This text will only show if users write new code in JavaScript with the old spelling and then convert to blocks.
=> Make "show icon" block display text when icon is undefined

pxtblocks/blocklyloader.ts
Fixing a bug that @thsparks ran into while using the `//% toolboxParent` comment attribute.
If a block doesn't specify a shadow block id or default value for a parameter, then we don't actually create a value tag for that parameter in the toolbox block XML. That's a problem when that block is used as the toolboxParent for another block.
If that value tag doesn't exist in the parent XML, the query selector we use when applying the toolboxParent attribute comes up empty and the attribute is ignored completely.
If you want to see the bug for yourself, you can use this code:
```
enum Bar {
A,
B
}
//% weight=100 color=#0fbc11 icon=""
namespace custom {
export class Foo {
}
//% block="create foo"
//% toolboxParent=use_foo
export function createFoo(): Foo {
return new Foo();
}
//% block="create …
```
=> Fix toolboxParent attr when no shadow is given in the parent block

localtypings/pxtpackage.d.ts, pxtlib/package.ts, pxtlib/spriteutils.ts, pxtlib/tilemap.ts, webapp/src/package.ts
Cherry picking https://github.com/microsoft/pxt/pull/9475 and https://github.com/microsoft/pxt/pull/9477
Together, these PRs make it so that you can import dependencies as asset packs. @kiki-lee mentioned that she would like to see if we can have this merged/released by Friday because she would like to use this feature in the skillmaps and tutorials she's publishing.
=> [Stable8.5] Cherry picking asset pack PRs

theme/common.less, theme/themes/pxt/modules/dropdown.overrides, webapp/src/identity.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5077
Layout is better at the previously problematic breakpoint:
Also:
* Fixed this button squeezing issue:
* Removed some extra css that was complicating the signed-in/avatar button.
=> Sign-in button css improvements

react-common/styles/extensions/ExtensionCard.less
Fixes https://github.com/microsoft/pxt-microbit/issues/5078
=> Fix high contrast bug so that extension descriptions are visible

pxtsim/sound/sequencer.ts, webapp/src/components/musicEditor/PlaybackControls.tsx, webapp/src/components/musicEditor/keyboardNavigation.ts, webapp/src/components/musicEditor/playback.ts
This allows users to start playback in the music editor from the keyboard cursor position (as opposed to the beginning). In the interest of minimizing confusion, I've only added it as a (new) keyboard shortcut, shift+space, rather than changing the behavior of the existing play button & shortcuts.
Upload target: https://arcade.makecode.com/app/e90f14585861682776e190f5f6988269505c5ce2-95604db35f
=> Music editor: Add ability to start playback from cursor position.

pxtlib/webusb.ts, webapp/src/editortoolbar.tsx
re: https://github.com/microsoft/pxt-microbit/issues/4914, I did a quick check and it looks like about 3-3.5% of our chrome / edge users end up with webusb being unavailable. There are several known reasons for that, which will cause us to cut webusb features from being displayed (same as behavior in firefox / safari), but most versions of chrome / edge *should* support it so debugging can be hard.
This ads in a download menu item when 1. on chrome or edge and 2. webusb features are disabled for some reason.
This pops up a quick modal with a short explanation of the issue 
and just to note explicitly, this only shows up in chromium edge / chrome, safari and firefox will not get this option as the browsers explicitly do not support webusb. If anyone feels that I should put it in for all …
=> add button when webusb is disabled in chrome/edge

pxtlib/service.ts, webapp/src/marked.tsx
This check is needed to prevent a broken translation in Italian, in which the definition name was "note" instead of "name."
Fixes #https://github.com/microsoft/pxt-microbit/issues/4905
There will also be a PR shortly to add upgrade rules in pxt-microbit to prevent breaking old projects that have the broken translation.
=> Check definition name before accepting translation

cli/cli.ts
re: https://github.com/microsoft/pxt-microbit/issues/4629, fix the defaults for webmanifest / pwa install; allow any orientation / system default. See https://stackoverflow.com/questions/68522783/web-app-manifest-orientation-property-what-is-the-difference-between-its-proper for a quick description of all the options; any allows it to rotate freely if that's what the device wants / to match device. The other option would be natural, which is basically 'any' but doesn't allow the 180 flipped ones (e.g if you rotate your phone 90 counter clockwise instead of clockwise when making it go to landscape it'll be upside down), but I don't see a reason to enforce that personally.
Quick build: https://makecode.microbit.org/app/c282d34d33f1de156bded94036d54eb692dc8b14-217c936519 you can see the …
=> Fix defaults for web manifest

pxtsim/simdriver.ts
fix https://github.com/microsoft/pxt-microbit/issues/4986
~If we want I can make it a little more extensible by tagging each sim with an id and including that in `deferredMessages`, so if we extend to > 2 sims in the future it'd still work as expected, but that feels pretty low priority / it's been years with just 2 in the first place. But it wouldn't be hard / would make the code a little more explicit so just let me know what you prefer, whoever ends up reviewing this 😸~ I just went ahead and did it
here's the build without the fix: https://makecode.microbit.org/beta#pub:_KPJbgURehgML - press a and see nothing happens on first press
here's the build with the fix; https://makecode.microbit.org/app/40bfbd4a142932c6ba83c231537276246a59f908-2dfbec65d1#pub:_KPJbgURehgML press a and see it is …
=> when spawning sim from broadcast, defer msg till spawned

localtypings/pxtarget.d.ts, webapp/src/blocks.tsx
This option allows blocks to specify that they should be duplicated in the toolbox, and the duplicate should be wrapped in a parent. It functions much like `toolboxParent` (and `toolboxParentArgument`) but adds a new block instead of wrapping the existing one.
Needed for https://github.com/microsoft/pxt-microbit/pull/5123 so we can include the sound effect block by itself *and* include the sound effect block wrapped in the play block parent without having to create a whole new play block. (See comment: https://github.com/microsoft/pxt-microbit/pull/5123#issuecomment-1544424908)
=> Add "Duplicate with Parent" option for blocks in the toolbox.

webapp/src/components/tutorial/TutorialContainer.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5083
The `focus` call was re-positioning the scroll in our tutorial container and pushing the title out of view. By moving `scrollTo` after that call, we can avoid the issue.
=> Ensure title is visible when tutorial loads a new step

webapp/src/extensionsBrowser.tsx
fix https://github.com/microsoft/pxt-microbit/issues/4959; see https://github.com/microsoft/pxt-microbit/issues/4959#issuecomment-1542583536 for an easier repro.
~The root of the issue is that onBlur is kinda a messy place to start the search from -- it running means you've already clicked / navigated elsewhere (e.g. the scrollbar or one of the extension buttons), so the results will be changing from underneath you (sort of like if you're reading a website and about to click a link, and then a big add pops in and pushes down the link you were going to click; it feels bad), and typically navigating away can mean that something has caught your eye in the first place -- so the update will potentially cause that to disappear.~
~Tagging in hassan / abhijith here as well as a check on if this …
=> don't extension search on blur + fix for blur losing input on repeated blur

pxtlib/browserutils.ts, pxtsim/visuals/boardhost.ts, react-common/components/share/ThumbnailRecorder.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/4988
This removes the duplicate simulator and also fixes the aspect ratio of the preview. Before, the thumbnail looked squished because the rendering was including extra padding. Now we use the `viewBox` to get the width and height, which does not include the padding.
I also made a fix for the label so that if no keyboard shortcuts are defined, it doesn't show `((undef))`
Before:
After:
=> Fix duplicate simulator in thumbnail

localtypings/pxtarget.d.ts, pxtblocks/blocklycompiler.ts, pxtblocks/blocklyloader.ts, pxtcompiler/emitter/decompiler.ts, tests/blocklycompiler-test/baselines/grid_template_string.ts, tests/blocklycompiler-test/cases/grid_template_string.blocks, tests/blocklycompiler-test/test-library/mbit.ts, tests/blocklycompiler-test/test.spec.ts, tests/decompile-test/baselines/images.blocks, tests/decompile-test/cases/images.ts, tests/decompile-test/cases/testBlocks/mb.ts
Basically, just the grid field editor that doesn't require explicit sim / cpp side handling / emits to a string template
```typescript
//% color="#AA278D" weight=100
namespace hello {
//% weight=75
//% blockId=buildagrid block="my special grid"
//% imageLiteralColumns=7
//% imageLiteralRows=4
//% gridLiteral=1
export function createImage(leds: string) {
console.log(leds)
}
//% weight=70
//% blockId=gridthatreturns block="my special grid that returns"
//% imageLiteralColumns=7
//% imageLiteralRows=2
//% gridLiteral=1
export function createImageAndReturn(leds: string) {
return leds;
}
}
```
ends up as 
and doesn't go through the all the special cases in the -> binary js / -> cpp compilers, so it's useable for defining grids that aren't explicitly micro:bit images (and therefore doesn't just …
=> add block attribute for grid that emits to string literal

pxtsim/embed.ts, webapp/src/serial.tsx
fix for https://github.com/microsoft/pxt-microbit/issues/5129 alongside https://github.com/microsoft/pxt-microbit/pull/5147 to send the clear message
build / test https://makecode.microbit.org/app/75ac18b1b2f92b85fefac4d9a613dbda9ca3bcfe-f17fea3dbb#pub:S73614-71882-80362-66035
=> datalogger sim: clear when clear block is used

cli/server.ts, pxtlib/localStorage.ts
re: https://github.com/microsoft/pxt/pull/9516, I've been getting ~10-40 of these in my console whenever I do local host development when not logged in and it's been a bit distracting when looking for 'real' errors -- the console doesn't suppress the default 404 error logs even when caught. This changes to a [204 (no content)](https://http.cat/204) and handles the rest client side, feel like an okay compromise?
And just to double check my understanding, this one is only used for localhost sign in / shared context related things, and doesn not get touched on the prod / uploaded versions? Is it just that it forks on https://github.com/microsoft/pxt/blob/cleanUpCsrfErrors/pxtlib/localStorage.ts#L127 in `getAsync` to use `getLocal` / `setLocal`, so 'prod' uses the `else` path vs. the `if` I …
=> return a 204 (no content) for local host storage failure, handle client side

cli/cli.ts, cli/server.ts
just fixes a 404 on local serve that constantly shows up (`sim.webconfig`), still get the `/api/store/` ones a lot (in particular when not logged in) but those seem less trivial to remove / probably need a little rethinking if we wanted to clear them -- they're semi 'expected' failures but they're quite noisy when you're not logged in
/ I still see some spurious 404's even when signed in occasionally that fill up the log a bit (for csrf token & for theme)
=> fix trgblb/sim.manifest req

pxtlib/emitter/cloud.ts, pxtrunner/runner.ts
fix https://github.com/microsoft/pxt-microbit/issues/4933
This one is a little fun as it had issues on each level (code, docs, and translations)
* the code was aggressively showing a network error on any compile issue, which doesn't match our docs behavior
*  That page in particular had a bad package import statement; trying to import music? https://github.com/microsoft/pxt-microbit/blob/master/docs/reference/music/volume.md looks like a few of the others did as well
* The japanese translation for that page had a bad translation applied to that import statement, causing the import to fail: https://crowdin.com/translate/makecode/10350/en-ja#967414
we should also fix the docs pages with that bad import (which will also fix the translation by just getting rid of it),  but this change will …
=> only show internet connection page in sidedocs for network failure, not rendering errors

webapp/src/webusb.tsx
If you have already paired your micro:bit, press download while unplugged, and get the 'plug in your micro:bit' dialog, we currently still go through the browser pairing flow. With this, we'll bypass that flow when a device successfully reconnects their device, and just skip straight to the 'congrats!' screen, instead of making them go through the pair dialog / failing when they click out even when they've already authorized the device previously and the confirmation is a no-op.
build: https://makecode.microbit.org/app/eaba39d3894b7e260579074cc9edfb971b64899e-98b1d17bae
while testing, when you unplug and replug in micro:bit please wait a few seconds for any existing download to finish -- I ran into issues a few times where it would try and repair + start download on top of eachother when …
=> if you have connected an already paired device, skip browser pair dialog

pxteditor/editor.ts, pxteditor/editorcontroller.ts, pxtlib/cmds.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/dialogs.tsx, webapp/src/webusb.tsx
https://makecode.microbit.org/app/ffbdd7bc4924b3b24a8d03c86d3dd5b68a77b717-cc763a8701
I'll be double checking this on monday, I'm sure I messed something up a bit, but this should overall catch the errors more consistently, route to 'congrats you succeeded' screen more accurately (both confirming connection was actually successful before congratulating user, and ignoring false negatives when e.g. escaping from browser pair screen with an already pair micro:bit), giving download dialog consistently when downloading to device was unsucessfully, and deploy automatically when 'download success -> pair now for faster downloads -> successful pairing' path occurs
Should:
* fix https://github.com/microsoft/pxt-microbit/issues/5146
* fix https://github.com/microsoft/pxt-microbit/issues/5090
* fix …
=> Webusb: catch errors more errors, stop saying success when pairing not complete

pxtblocks/fields/field_melodySandbox.ts
The tempo field wasn't syncing with the block correctly anymore. This was happening because, in the new block, the input field is called "bpm", not "tempo". Updated the sync code to account for both.
Upload Target: https://makecode.microbit.org/app/ac0f4fe2dc3372d752d581d359dc3294da026f15-80284e55a1
Fixes: https://github.com/microsoft/pxt-microbit/issues/5179
=> Fix Tempo in Melody Editor

pxteditor/editor.ts, react-common/components/controls/TeachingBubble.tsx, webapp/src/app.tsx, webapp/src/onboarding.ts, webapp/src/projects.tsx
Closes https://github.com/microsoft/pxt-microbit/issues/5149
This change will auto-start the editor tour when a user creates a new project and they have zero other projects. So, if you delete all your projects, the next project you open will trigger the tour again. The tour is also still available in the help menu.
This change depends on a change in pxt-microbit to add a welcome step to the editor tour markdown.
Here's a build: https://makecode.microbit.org/app/ae6a0123d79e5e04105f1a55ce497865d6942e07-a402fe3471
Note: The welcome step won't show up in the build since it's from the markdown in pxt-microbit and docs are live.
=> Auto start the editor tour on first project

localtypings/pxtarget.d.ts, pxtlib/cmds.ts, pxtlib/packetio.ts, webapp/src/app.tsx, webapp/src/simulator.ts
for skipping over 'too big for v1' modal on v2.
Also included a flag to pass it as the theme if that is not explicitly defined for the project (same field I use in arcade for e.g. zune), since I realized that was easy to address https://github.com/microsoft/pxt-microbit/issues/4724 with this field anyways
For ref i added devVariant over in microbits packetio wrapper implementation https://github.com/microsoft/pxt-microbit/blob/a0d6ca1b5d1c33386d6374101dbcdbd5bd25f36a/editor/flash.ts#L248, this is exposing it on the wrapper interface / using it from the existing implementation
=> packetio expose deviceVariant, propagate to sim/flashing

pxtlib/package.ts, pxtlib/service.ts
fix https://github.com/microsoft/pxt-microbit/issues/5186; we should not crash when loading extensions with invalid localization files; just ignore them. (if we want I can walk up the loading path here a bit and find a place to place to catch more broadly, but I don't see errors here often / feels like something we can do later as clean up, probably go to an "extension failed to load" dialog of something?).
@abchatra not sure if we'd care about ticks for this, as it should only really apply to third party extensions? I left it as just a log for now similar to the existing 'ignored translations' logic without the `reportError` https://github.com/microsoft/pxt/blob/ignoreInvalidLocalesFiles/pxtlib/service.ts#L767 so extension developers can check that without a tick for that reason, happy …
=> Ignore invalid locales files in extensions

react-common/components/controls/VerticalResizeContainer.tsx, react-common/styles/controls/VerticalResizeContainer.less, react-common/styles/react-common.less, theme/common.less, theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/sidepanel.tsx
This makes the instructions resizable (when in the top-instructions view). I created a new `VerticalResizeContainer` so it will _theoretically_ be easier to make similar changes easier in the future, if we decide to make other components resizable. (I did consider adding horizontal resizing too, but since it's not needed for this change, I decided to hold off. Can be added later if/when we need it.)
The change is primarily based on @jwunderl's https://github.com/microsoft/pxt/pull/9102.
Try it here: https://makecode.microbit.org/app/c07cbb23d6fd576dccb1afa91e15a1566e0a2c68-80c4cf5b23
Fixes https://github.com/microsoft/pxt-microbit/issues/5024
=> Make Top-Instructions Resizable

localtypings/pxtarget.d.ts, pxtlib/cmds.ts, pxtlib/webusb.ts, webapp/src/cmds.ts, webapp/src/webusb.tsx
close https://github.com/microsoft/pxt-microbit/issues/5109
also part of https://github.com/microsoft/pxt-microbit/issues/5164, I'll close that one in a separate pr over in micro:bit adding the two images in this pr.
Could use wording critique on the two dialogs I'm updating:
New short dialog for 'we successfully disconnected your device' case, where forget worked:
gif is just the 'connected device' one reversed. This dialog is purely informational, besides a suggestion to unplug (but that only really matters if they wish to reconnect right away, which is a bit of a niche use case.)
The other one is the existing dialog, just updated the wording a bit to accommodate upcoming browser changes (getting rid of lock icon). This one shouldn't be hit for up to date browsers that support the api, …
=> Use forget device api to directly disconnect when available

pxtpy/pydecompiler.ts, tests/pydecompile-test/baselines/indentation.py, tests/pydecompile-test/cases/indentation.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4891
When a block like the one shown below is converted to Python, the lines after the first are over-indented.
This
Turns into this
```py
def on_forever():
basic.show_leds("""
. # . . .
. . . . .
. . . . .
""")
basic.forever(on_forever)
```
when it _should_ look like this:
```py
def on_forever():
basic.show_leds("""
. # . . .
. . . . .
. . . . .
""")
basic.forever(on_forever)
```
The problem function is `emitMultiLnStrLitExp`. In it we see `return asExpRes(`"""\n${indent1(s.text.trim())}\n"""`)`.
Notice `s.text` is trimmed before being passed into indent1, and see an example string that gets passed into the function:
```
8-spaces. . . # #
. . . # .
. . . . .
. . . . .
. . . . .
```
The `trim()` call removes the first line's indent, …
=> Fix Python Over-Indenting 

pxtlib/browserutils.ts, pxtsim/visuals/boardhost.ts
Closes https://github.com/microsoft/pxt-microbit/issues/5155
This also fixes a lingering issue where the thumbnail had two simulators duplicated. It was fixed for screenshots before, but it became apparent during this bug fix that it was lingering for gifs. (See https://github.com/microsoft/pxt-microbit/issues/4988)
This change does not impact Arcade.
=> Only show micro:bit board (no external parts) for thumbnail recorder

pxtsim/visuals/boardhost.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5211
Before I was looking only at the child nodes to find the simulator svg (class = "sim"), but when there are no external parts, the node itself contains the simulator svg. So now we first check if the node itself contains the class "sim" and if not, we check the child nodes. I also added a null check in case neither the parent or children contain the "sim" class.
Here's an upload target for testing: https://makecode.microbit.org/app/54d7a1abebbcc13f4668cc9838aa322ba63372e8-19f5fb88ef
=> Fix screenshot null pointer exception

react-common/styles/controls/ProgressBar.less
Just noticed the skillmap progress bar was missing the hc theming while testing other pr, reason was that skillmap uses `.high-contrast` class instead of `.hc`. Might be good to unify that a bit as there isn't really a good reason to have to remember to support two classes for this, but just patching this for now :)
=> fix high contrast mode for skillmap progress bar

pxtlib/auth.ts, pxtlib/localStorage.ts, webapp/src/app.tsx, webapp/src/auth.ts, webapp/src/core.ts
fix https://github.com/microsoft/pxt-microbit/issues/5209
Here's a forked build from the one in that issue pointing at a build with this change: https://wyttlr.csb.app/ (there will be an overlay button in the bottom right to see the code of the sandbox)
microbit build: https://makecode.microbit.org/app/4e857c4bdf435b028015828dbd8d4af76e3d2c48-72860080ee
arcade build: https://arcade.makecode.com/app/15ee7b4f6abf540a00d30fa275c70925a5bdceeb-35abd09842--skillmap
I believe the change in `pxtlib/auth.ts` should technically be enough to cover this regression (+ https://github.com/microsoft/pxt/commit/a673adfed979c0356fcd270d331e0c4ed54e2012 to make it so language / high contrast persist through refreshes), but I ran into some other things while trying to figure out why it wasn't working so …
=> Fix settings in iframe editor embed

localtypings/pxtarget.d.ts, react-common/components/profile/Profile.tsx, react-common/styles/profile/profile.less, webapp/src/user.tsx
For micro:bit that doesn't have any badges, or any other targets that might not have something to fill the profile page space, we don't want the profile page to be the full screen. With these changes, a target can have a smaller profile page. 
EDIT: Here's an upload target: https://makecode.microbit.org/app/29277b08cefbec40fdc2f89cd0afd2933226581d-321f1764ea
Part of the solution for: https://github.com/microsoft/pxt-microbit/issues/5084
=> Profile pages: added option for smaller dialog

localtypings/pxtarget.d.ts, react-common/components/profile/Profile.tsx, react-common/styles/profile/profile.less, webapp/src/user.tsx
Cherry pick from https://github.com/microsoft/pxt/pull/9551
* Made the profile modal small for microbit
* Adds an info section for profile pages that don't have badges
* Got rid of links for profile, alt text for decorative image on profile dialog
=> [stable 9.0] Profile pages: added option for smaller dialog 

theme/common.less, theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialCallout.tsx, webapp/src/sidepanel.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5227
When a hint is going off the bottom of the screen, move it up. While debugging this, I found that the tutorialCalloutTop variable wasn't working or doing anything, so I removed it.
I also added a small tick event for when someone resizes the tutorial instructions.
Upload Target: https://makecode.microbit.org/app/e973301c9b0f9be87ba85072fe0864b54855b967-ca062a1773
=> Keep Long Hints In Screen

pxtlib/browserutils.ts, webapp/src/cmds.ts, webapp/src/hidbridge.ts
closes https://github.com/microsoft/pxt-microbit/issues/5241
Apparently firefox has always (> 2 years, code from 2017 and we changed the flow a good amount a while back) been hitting an alternate save dialog path:
vs what you normally see on other browsers, plus or minus a webusb suggestion:
Also fixed a minor, mostly ignored null pointer exception that's also been around forever where we tried to connect to hidbridge that doesn't work on non-webusb targets (init was returning without setting iface when on not localhost, and then crashing a little bit later in initAsync)
build https://makecode.microbit.org/app/7f06460f3a35e00446f1080eeba1b5ed14b71522-86ebee0213
=> Fix firefox download dialog, ignored null pointer exception on firefox/safari

theme/common.less, theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialCallout.tsx, webapp/src/sidepanel.tsx
When a hint is going off the bottom of the screen, move it up. While debugging this, I found that the tutorialCalloutTop variable wasn't working or doing anything, so I removed it.
I also added a small tick event for when someone resizes the tutorial instructions.
Port of https://github.com/microsoft/pxt/pull/9557
=> [Port to Stable] Keep Long Hints In Screen (#9557)

webapp/src/components/tutorial/TutorialCallout.tsx
@jwunderl warned me and I forgot... Fixes https://github.com/microsoft/pxt-microbit/issues/5245
With the greater than (and not equals) check, it would back and forth between the two cases. By using >= instead, that won't happen.
=> Fix Hint Flickering

webapp/src/components/tutorial/TutorialContainer.tsx
Port of https://github.com/microsoft/pxt/pull/9565
We were persisting horizontal/vertical layout in state, but it was getting out of sync with the actual screen size and there's not really a need for it to be persisted. We can just recompute isHorizontal every time, and it works as intended.
=> Fix Step Counter on Tutorial Window Resize (#9565)

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpr.yml, .github/workflows/pxt-buildpush.yml
I noticed in https://github.com/microsoft/pxt/actions/runs/5250237669 we seemed to be getting a spurious warning in all of our builds related to the node 12 deprecation 
I checked some of our other repos and backend had it pointing at main without that warning. The error in that run comes down to 'weird, inconsistent npm install' stuff (if you search the error, the most common result is "try rm -rfing node modules" followed by "that worked thanks"), and the error seems to indicate it's trying to use different versions of node within the same workflow run. I can pin to v3 if we want latest, just figured it's probably fine on main for this standard action.
I only put it in for buildpr in this change to start so I can watch the build go through / read through it for a quick check, since that …
=> bump version of checkout, setup-node in pr workflow

theme/common.less
This partially addresses the issues seen in https://github.com/microsoft/pxt-microbit/issues/4828. While it's not a perfect fix, it's a step in the right direction, and it's at least usable now. I wanted to get this out in time for the hotfix, since I suspect some of the remaining improvements will take me longer to implement.
This change fixes the sim sizing and stops it from disappearing on smaller screens, and it simply removes the sim toolbar for now (which is currently offscreen anyway).
Future improvements that would be worth doing, perhaps in a separate change, would be:
1. Fix weird gap on the right-hand side where background doesn't fully extend (looking into this now, will add to PR if I figure it out but didn't want to block on it).
2. Bring back the sim toolbar, but probably …
=> Improve Share Page Sandbox Display on Small Screens

pxteditor/editor.ts, pxtsim/embed.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, pxtsim/simlib.ts, webapp/src/app.tsx, webapp/src/simtoolbar.tsx, webapp/src/simulator.ts
Part 1 of https://github.com/microsoft/pxt-microbit/issues/5158 fix
This PR adds a third "disabled" state to the simulator mute button that can be triggered by a message from the simulator.
This is for Safari, so that we can show a mute button inside the iframe. I'll be opening a PR in pxt-microbit that adds that button momentarily
=> Add disabled state for mute button

pxtblocks/fields/field_kind.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5899
Adds "rename" and "delete" options to the SpriteKind dropdown! These work exactly the same as the variable ones; if you delete a kind you will delete all blocks that use that field and have the kind set as the value. In practice this is less destructive than the variable delete because we always use this field on shadow-style blocks so there are no children that will also get deleted.
One caveat: the built-in kinds (Player, Enemy, Projectile, and Food) cannot be deleted or renamed.
=> Add option to rename and delete user kinds

react-common/components/controls/VerticalResizeContainer.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5280
The issue is not actually specific to touch. When the hint is open, the popup is considered a child of the VerticalResizeContainer that contains the instructions, and it causes the resize "OnPointerDown" event to fire even when the mouse is below the main instruction container. Since I didn't add a max bounds check on before entering resize mode, it resize would trigger even when the mouse was below the instruction pane. We can stop this by checking that the mouse Y is less than the container's height before entering resize mode.
Upload target: https://makecode.microbit.org/app/7d3a8cce6382ea9e2e55876ff04fdc0e72505fa6-23a81c7051
=> Fix instruction resize when hint is open

react-common/components/controls/VerticalResizeContainer.tsx
Port of https://github.com/microsoft/pxt/pull/9576
The issue is not actually specific to touch. When the hint is open, the popup is considered a child of the VerticalResizeContainer that contains the instructions, and it causes the resize "OnPointerDown" event to fire even when the mouse is below the main instruction container. Since I didn't add a max bounds check on before entering resize mode, it resize would trigger even when the mouse was below the instruction pane. We can stop this by checking that the mouse Y is less than the container's height before entering resize mode.
=> Fix instruction resize when hint is open (#9576)

cli/cli.ts, webapp/src/extensionsBrowser.tsx
This pr https://github.com/microsoft/pxt/pull/7320 is some context you'll probably need to understand why this actually matters; when compiling we alphabetically sort to generate a stable order so the produced sha is consistent even when packages are imported in different orders (e.g. if radio happens to be before or after audio-recording in the list). Probably worth revisiting that logic and sorting in a way that takes into account the source better, but since these are all builtin extensions the behavior I used in the cli should be consistent with webapp (e.g. for builtin packages can use id since it's "*" at runtime / behaves like this change, but make sure github packages use slug / version / etc). Several of the other changes were just minor style nits or fixing logging so I'll point …
=> Fix audio recording offline compilation

theme/common.less
In microbit, this worked without !important, but in arcade it gets overridden, so the !important is necessary.
=> Hide SimToolbar in Arcade's Sandbox Mode

webapp/src/simtoolbar.tsx
Port of https://github.com/microsoft/pxt/pull/9582
These two css classes on the tutorial-specific mute button were dropped in #9568 but are needed so we don't get two mute buttons in the sim toolbar on a tutorial.
=> Prevent Duplicate Mute Buttons in Tutorial (#9582)

pxtblocks/fields/field_kind.ts
fix https://github.com/microsoft/pxt-arcade/issues/5965; we may want to think on prohibiting names from duplicating across kinds, but that seemed a little unnecessary as it wasn't a regression / arguable in the first place.
This one's targeting the release branch since I was already on that accidentally (which I suppose is a good thing), will reverse port to master.
build (off stable1.12 in arcade, stable8.5 here): https://arcade.makecode.com/app/bf6c7d16c202bec13b3afdab05cdd54b7d5a5093-6edb864625
with the sample from that issue: https://arcade.makecode.com/app/bf6c7d16c202bec13b3afdab05cdd54b7d5a5093-6edb864625#pub:S63783-19068-25507-81035
=> [stable8.5] only mutate kinds of the same type on delete / rename

theme/common.less
fix https://github.com/microsoft/pxt-microbit/issues/5307
I believe the class got moved up slightly at some point and this associated css did not get fixed alongside it. The `collapsedEditorTools` class is applied to root, so have to make the selector start with & so it narrows the element selected by the rule it's enclosed in, rather than another element inside this one
Worth noting this hides the other buttons on the mini sim button as well when collapsed (debug, fullscreen) so it gives back even more space; e.g. live:
(with a bit of the area to the left of the buttons not working as blockly canvas / just being a fullscreen button)
vs with this change:
built to test with (based off master, not stable) https://makecode.microbit.org/app/a0cdefb6098a3c45d9938770d948941667ec095a-d0114f0c19
=> hide extra buttons when sim is collapsed in mobile view

theme/common.less
port https://github.com/microsoft/pxt/pull/9595
=> [stable9.0] hide extra buttons when sim is collapsed in mobile view

common-docs/blocks-embed.md
Add a section about including extensions for embedded blocks rendering in the `blocks-embed` page.
RE: https://github.com/microsoft/pxt-microbit/issues/5303#issuecomment-1629843784
=> Update 'blocks-embed' topic to describe use with extensions

cli/cli.ts
=> include ico file extension to patch /static/* images in pxtarget to point to cdnUrl

docfiles/pxtweb/cookieCompliance.ts, docfiles/tracking.html
Here's an example of what the tick looks like when it goes through this fn:
into ->
```json
{
"name": "Microsoft.ApplicationInsights.{0}.PageviewPerformance",
"time": "2023-07-12T16:44:43.715Z",
"iKey": "9801ed01-c40f-46ec-aa40-2a1742a9e71c",
"ext": {
"app": {
"sesId": "{b64ish}"
},
"device": {
"localId": "browser",
"deviceClass": "Browser"
},
"trace": {
"traceID": "{b16ish}",
"name": "/75618-11489-17671-85517"
},
"user": {
"id": "{b64ish}"
}
},
"tags": [],
"data": {
"duration": 3642.60000000149
},
"baseType": "PageviewPerformanceData",
"baseData": {
"name": "world_race",
"uri": "http://localhost:3232/75618-11489-17671-85517",
"isValid": true,
"durationMs": 3642.60000000149,
"duration": "00:00:03.643",
"perfTotal": "00:00:03.643",
"networkConnect": "00:00:00.319",
"sentRequest": …
```
=> clean up PageviewPerformanceData tick a bit

docfiles/pxtweb/cookieCompliance.ts, docfiles/tracking.html
port #9602 for arcade release; unfortunately to really test this need to just port & ship a hotfix so we can see the telemetry data change a day or so later; going to arcade first as a standalone fix & can do rest later on after validating
=> [stable8.5] clean up PageviewPerformanceData tick a bit

theme/themes/pxt/elements/loader.overrides, theme/themes/pxt/globals/site.variables, webapp/public/index.html
The following loading screen is displayed on first load for all targets instead of a target-specific icon.
=> Branding: Add Microsoft logo to first loading screen

cli/server.ts, pxtlib/emitter/cloud.ts
when fixing https://github.com/microsoft/pxt/pull/9609 took me a second to realize I was using an S link to check, which wasn't supported. This makes the localhost serve resolve _asdfasdfasdf links & s12345-... links in addition to just share ids.
Also make it so `pxt.Cloud.parseScriptId(window.location.pathname)` works when on a script page (that is, support a leading slash in case of copy paste typos / etc)
=> Local serve share page quick fixes

docfiles/pxtweb/cookieCompliance.ts, docfiles/tracking.html
quick follow up on https://github.com/microsoft/pxt/pull/9602 before I port it to other editors, include pathname so we can compare those as well (vs. just page titles); share pages come in as xxxxx-xxxxx-xxxxx-xxxxx e.g.
=> one more fix for pageviews; include pathname

pxtlib/service.ts
cherry pick https://github.com/microsoft/pxt/pull/9502 for arcade. Spanish translations seem to have about half a dozen of these issues, which is causing issues for some teachers; gonna try to push this out in next hotfix with a few upgrade rules to clean it up, will try those now~.
For ref:  https://forum.makecode.com/t/error-when-using-makecode-arcade-in-google-chrome/21210/4
=> [stable8.5] Check definition name before accepting translation (#9502)

pxtlib/browserutils.ts
This is concerning issue #5328 in the Microbit repo (https://github.com/microsoft/pxt-microbit/issues/5328). The issue was that the simulator was not showing up when the window width was exactly 991px wide. After a lot of digging I was able to pinpoint that the issue was stemming from the `isTabletSize()` function within the `browserutils.ts` file. 
```
return window?.innerWidth = pxt.BREAKPOINT_TABLET;
```
to
```
return window?.innerWidth <= pxt.BREAKPOINT_TABLET;
```
=> Re: Sim missing at exactly 991px width from MicroBit repo

README.md, gulpfile.js
Optional flag to skip building authcode, skillmap, multiplayer, and soon kiosk. Usage:
```bash
gulp --no-webapps
```
```bash
gulp watch --no-webapps
```
=> Add `--no-webapps` gulp option

backendutils/tsconfig.json, cli/cli.ts, docfiles/pxtweb/tsconfig.json, gulpfile.js, pxtblocks/tsconfig.json, pxtcompiler/tsconfig.json, pxteditor/tsconfig.json, pxtlib/tsconfig.json, pxtpy/tsconfig.json, pxtrunner/tsconfig.json, pxtsim/tsconfig.json, tests/blocklycompiler-test/tsconfig.json, tests/blocks-test/tsconfig.json
for arcade hotfix, easiest to pull this in vs. retroactively porting off change in pxt-arcade-sim (and makes switching branches easier as less dep graph thinking)
=> [stable8.5] Fix deprecation warning in tsconfigs (#9492)

theme/tutorial-sidebar.less
This is one part of the fix needed for Minecraft's tutorial layout after the PXT bump. The other part is in the pxt-minecraft repo: https://github.com/microsoft/pxt-minecraft/pull/2314
Tutorials with fixes applied can be seen here: https://minecraft.makecode.com/app/8ef76a97727b2cdaf01a9b01e0703b80e23721a8-8e733a6100
Note that this does **not** fix https://github.com/microsoft/pxt-minecraft/issues/2312, which I'll investigate and address in a separate change.
Before:
After:
=> Fix Minecraft (Headless) Tutorial Layout

multiplayer/src/services/simHost.ts, pxtrunner/runner.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6003
This fixes a bug that was happening when an arcade game was storing a setting as an empty array. When saving the settings on restart, it was getting serialized as an empty string, which resulted in the value not being set since it evaluates to falsey. Then later the game referenced the setting, causing a "dereferencing null/undefined value" error.
Now we check for null/undefined instead of falsey values when setting the storedState.
Big thanks to @jwunderl for walking me through this bug.
=> Null check instead of falsey check for storedState value

multiplayer/src/services/simHost.ts, pxtrunner/runner.ts
Cleanup for https://github.com/microsoft/pxt/pull/9634, https://github.com/microsoft/pxt-arcade/issues/6003
We don't actually want to check that the value is null before calling `setStoredState` because that function uses the null check to determine whether to set the value or delete the entry. If we check beforehand, we won't be deleting the entry.
See `setStoredState` function here: https://github.com/microsoft/pxt/blob/master/pxtrunner/runner.ts#L552
=> Remove preliminary null check for storedState

docs/extensions/pxt-json.md
Some DAL config examples/description added to the [pxt.json](https://makecode.com/extensions/pxt-json) page.
Not sure if this is correct, but I 'yotta' know by now.
Closes https://github.com/microsoft/pxt-microbit/issues/5329
=> Add yotta config section to pxt.json doc page

multiplayer/src/services/simHost.ts, pxtrunner/runner.ts
One more set of fixes; port
* https://github.com/microsoft/pxt/pull/9634
* https://github.com/microsoft/pxt/pull/9635
so we can include in hot fix. This bug impacts one of the 'honorable mentions' in the game jam (it used an array of numbers for a setting, and will get a npe forever if you lose the first time you enter a level)
=> [stable8.5] Port share page fixes

react-common/components/controls/VerticalResizeContainer.tsx, theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/sidepanel.tsx
Fixes up a few additional tutorial layout bugs, including:
1. Fixes https://github.com/microsoft/pxt-minecraft/issues/2312 (need to ensure the vertical resize container is turned off and reset once the instructions are re-expanded)
2. Fix navigation buttons on mobile screen size (more headless-mode css adjustments)
Upload Target: https://minecraft.makecode.com/app/2d4dd01b4eb9f96d87fb427cf3ccf4d91e0af147-cb16e8b4bb
=> More Minecraft Tutorial Fixes

theme/tutorial-sidebar.less
This panel is empty anyway, but it was blocking the play button's mouse interaction on certain screen sizes (as seen below) causing https://github.com/microsoft/pxt-minecraft/issues/2315.
Sim Panel blocking interaction:
Fixes https://github.com/microsoft/pxt-minecraft/issues/2315
Upload Target: https://minecraft.makecode.com/app/0ea39a6562a0aa92f02d646175612dbe5d70428d-ae0451e946
=> Remove SimPanel in Headless-Mode Tutorials

webapp/src/app.tsx
When a tutorial ends and the user clicks "Done" to go to the main code editor, we were calling into `expandSimulator`, which will open the sidebar even when we don't have an actual simulator to show. This change prevents that call if we're in headless mode (i.e. no simulator).
I considered putting this check inside `expandSimulator` so it no-oped there if we're in headless mode, but I think this may still be used to see the file explorer in javascript mode, so I left that untouched for now.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2323
=> Do Not Expand Sim After Tutorial in Headless Mode

kiosk/src/Components/AddingGame.tsx, kiosk/src/Components/GameList.tsx, kiosk/src/Components/GameSlide.tsx, kiosk/src/Models/Kiosk.ts
Pulling in changes from pxt-arcade/kiosk/src
=> Sync kiosk changes

webapp/src/components/tutorialValidators.tsx
The insufficient blocks case is when the tutorial step requires more than one of the same type of block and the user has at least one of that type of block, but not all of the blocks. For example, in the picture below the user needs two "variables_set" blocks but only has one. Note: this example is a made-up tutorial step as I don't think we have any current tutorials that require more than one block of the same type in a single step.
Joey already added a check for insufficient blocks here: https://github.com/microsoft/pxt/blob/master/pxtblocks/code-validation/validateBlocksExist.ts#L27
This PR just uses that check to create the appropriate code validation message to the user.
=> Add insufficient blocks case to code validation

pxtlib/package.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6034. Essentially, if you switch to python and then change back to typescript or blocks, your typescript/blocks changes will be ignored.
This was happening because the preferred editor in our compile options remained set to python. The call to `getPreferredEditor()` was returning the correct value, but there's a scenario where, when iterating through variants, opts.target is overwritten with the old value from `appTarget.compile` (`opts.target = etarget.target;` in line 1235).
The simplest fix is to set the preferred editor after this happens, so we don't override it. A more involved solution would be to change how we're tracking the editor "mode" (js/py/blocks) and ensure a single source of truth, but I think that'd be a fairly …
=> Fix Non-Python Changes After Leaving Python Mode

theme/scriptsearch.less, webapp/src/scriptsearch.tsx
In the experiments view in all of our editors, the beta card was a bit off. It wasn't aligned to the other cards and it would also cover the "beta" label when someone would hover over it. The reason that the hover was behaving differently from the other experiment cards is because was are taking advantage of semantic ui's button creation. On hover, the button that we're using just for styling is popped up a bit and thus covers the beta label. My solution is to essentially make the button disabled even though it looks enabled. 
I feel like there should be a better solution to this rather than just kind of hacking around the semantic ui button. I'm not a huge fan of the accessibility implications of this, either. Everything on the card does essentially behave like a button, but something …
=> Experiments: beta card bugs fixed

react-common/components/share/ShareInfo.tsx, webapp/src/share.tsx
The new share dialog allows for the recording and screenshotting of the simulators in micro:bit and arcade, but we don't have something to easily preview in Minecraft at the moment. That means that the "record gif" or "take screenshot" area of the share dialog is not useful and is also buggy. 
If one of our targets specifies that it doesn't want to record GIF previews or allow screenshots of a simulator in `pxtarget.json`, we now get rid of that part of the share modal. When getting rid of the preview area of the share modal, the input for the project name was awkwardly long. So I've also updated the styling so that if we don't have something to preview for the project, we use a smaller share modal.
**Before**
**After**
Closes https://github.com/microsoft/pxt-minecraft/issues/2317
=> Allow for smaller share dialog when we don't want previews

webapp/src/scriptmanager.tsx, webapp/src/sui.tsx, webapp/src/workspace.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6035
Changing the script manager to always sort by relevance if there is any search term entered. It switches back once you delete the search term.
The search results we get back from the webworker are sorted by relevance, but we were completely ignoring that and sorting by name/time instead which is 100% useless.
=> Always sort by relevance when searching projects in script manager

webapp/src/app.tsx, webapp/src/container.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6028
With this change, when a user selects `main.py` (or any other python file) while in typescript mode, the editor will fully switch to python mode, which means any updated javascript will be translated into python before the file switch occurs, preventing code loss. The same will also happen in reverse when selecting a typescript file while in python mode. This behavior aligns with what happens when you click on `main.blocks` (it will switch to the blocks editor).
Upload target: https://arcade.makecode.com/app/962a0b823b61325c162a2fed0995f02a87f2aec4-d0020cc65b
=> Switch Editor Modes When Changing Between Py/TS in File Explorer

kiosk/src/Components/AddingGame.tsx
I broke it when moving the codebase to pxt :(
This uses window.location.origin to complete the url. I believe this will work everywhere.
=> Restore absolute url on kiosk qr code

localtypings/pxtarget.d.ts, webapp/src/app.tsx
Cherry-picked https://github.com/microsoft/pxt/pull/9458, which apparently isn't in stable8.5.
=> [Stable8.5] Enable Clever AutoLogin

theme/toolbox.less, webapp/src/toolbox.tsx
All of our other targets still have the colors on the icons for the block categories, so we want Minecraft to match that. 
Most of the categories are super straightforward because you can just change the icon color via code. However, the `Agent` category is a bit tricky because the icon that we're using doesn't have an associated icon in Semantic; we're using a static png. Because of this, changing the color of the `Agent` icon via code isn't really possible. That's where the new `Agent_icon_orange` file comes in. I just alternate between the two files to make the color changes work. I wasn't sure if referencing files across the repos like this would cause problems in production, so we might have to find another solution, but it works locally. One thing to note, though, is that when you …
=> High contrast: Icons for block categories now have colors in Minecraft

kiosk/src/config.json
Faster polling to reduce odds of missing an input event.
=> kiosk: increase gamepad polling frequency

docfiles/apptracking.html, docfiles/tracking.html
This seems to disable the sending of the `traceparent` header in fetch requests.
Hopeful this fixes https://github.com/microsoft/pxt-arcade/issues/6013
=> disable app insights correlation headers

theme/common.less, theme/tutorial-sidebar.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/2338.
The play button was being covered up by editor sidebar, which was invisible but still capturing mouse clicks. We can simply hide the editor sidebar in headless mode, since it's empty anyway, but it's still needed in tutorials to show the instructions, so I've moved some of the css into `tutorial-sidebar.less` instead.
Upload target: https://minecraft.makecode.com/app/fd04ae820f3da7f25778379ab1dd7ec0f64b937c-450a4c099f
=> Make Minecraft Play Button Clickable Again

common-docs/SUMMARY.md, common-docs/homepage-content.md
This is a draft of a base page for content additions of user content to a target home page. This is a base page and is extended in the target doc space for target specific images and approval info.
Closes #9666
=> Home Page content inclusion page

gulpfile.js
I think this will fix the bug that rare build issue that caused https://github.com/microsoft/pxt-arcade/pull/6077. The bits leading me to think that are that it's pointing at `/codicons/codicon/codicon.ttf` while grabbing the editor.css, which matches the error we got
and that `inlineCodiconFont`'s job is to replace that relative path with an inline font - so the replace in that fn is not being applied to the end result (it's just a few lines above this change). It's a bit hard to induce the bug, but I think it's a race condition with the `fs.readFileSync` vs `gulp.src` in `inlineCodiconFont` and `copyMonacoEditor` functions, where it normally runs fine but very rare fs lag causes inlineCodiconFont to get applied first then overwritten. I guess I can try inducing it by throwing in a `for …
=> potentially fix monaco editor build bug

pxteditor/history.ts, pxtlib/emitter/cloud.ts, react-common/components/controls/Tree.tsx, tests/pxt-editor-test/editorrunner.ts, theme/timeMachine.less, webapp/src/timeMachine.tsx, webapp/src/workspace.ts
These have a share icon next to them:
We already store shares in the project header, so share entries will actually appear for pre-time machine projects (albeit, all with the same timestamp).
=> Adding project shares to the version history

pxteditor/history.ts, theme/timeMachine.less, webapp/src/dialogs.tsx, webapp/src/workspace.ts
Fixes three bugs:
1. If you shared a script and then immediately opened the history, the share wouldn't show up
2. There was a minor text bleeding issue in the header on small screens
3. Sometimes the updateHistory would calculate an extra diff when collapsing history entries: one to check for equality, another to actually push on the stack. I replaced the first one with a simple equality check since that's a much cheaper operation
=> Fixing a few time machine bugs

localtypings/pxtarget.d.ts, webapp/src/projects.tsx
needs https://github.com/microsoft/pxt-arcade/pull/6089, we want to remove dependency on that hardware page and move live content to be rooted from targetconfig
fwiw I removed the `reportError` case as that seems like a valid use case when we have `experimentalHardware`; can add it back if we want
=> Pull hw options from target config

cli/cli.ts, multiplayer/src/components/JoinOrHost.tsx, webapp/src/extensionsBrowser.tsx, webapp/src/projects.tsx
re: https://github.com/microsoft/pxt/pull/9688, should fix https://github.com/microsoft/pxt-microbit/issues/5357 (the tags bit)
I'll merge https://github.com/microsoft/pxt/pull/9696 first & then add in localization for descriptions of hardware options, but I'm not certain whether we want names since they're actually products? Will check in stand up tomorrow & update this pr. Also need to check I formatted it correctly for multiplayer, just gotta spin up multiplayer serve tomorrow
=> extract localization for multiplayer hero games & tags

common-docs/blocks/custom.md
Add a custom.ts property to the example so that you can quickly change the display name for the specified namespace.
The user will always be in front of how to change the display name of the category.
=> Quick change display name for custom namespace

docs/csp.md
Remove the "Professional Development" section from the CSP course landing page. The section only applies seasonally.
Closes #9098
=> Remove PD section from CSP page

docs/github-teacher-verification.md
Add a troubleshooting/faq section for the [GitHub Teacher Verification](https://makecode.com/github-teacher-verification) page.
Closes #9701
=> Troubleshoot section for github-teacher-verification page

cli/cli.ts, localtypings/pxtarget.d.ts, multiplayer/src/components/JoinOrHost.tsx, webapp/src/extensionsBrowser.tsx, webapp/src/projects.tsx
Porting over the changes for pulling from target config -- reading hw options from targetconfig, and extracting out localization for that and a few others we're currently missing
=> [stable8.5-Arcade] Port hw dialogue fixes

theme/themes/pxt/views/card.overrides
Fixes https://github.com/microsoft/pxt-minecraft/issues/2243
I also had to make the (+) icon smaller on the new project card and nudge the blocks file image 4 pixels to the left because the svg for it has margins baked in
=> Fix the home screen's project row card size on mobile

kiosk/src/Components/GameList.tsx, kiosk/src/Components/GameSlide.tsx, kiosk/src/Services/GamepadManager.ts, kiosk/src/Services/NavGrid.ts, kiosk/src/Utils/domUtils.ts, kiosk/src/config.json
Also made tweaks to control focus logic for more reliable behavior on Xbox.
=> kiosk: support gamepad dpad for navigation

react-common/components/controls/Button.tsx
This is to ease porting Kiosk to react common. Kiosk displays button content as JSX children.
=> react-common: support for button children

common-docs/identity/cloud-sync.md, common-docs/identity/sign-in.md, common-docs/share.md
An update for the Identity and Share pages. Images are sourced from the target's static asset path for target specific context.
RE: https://github.com/microsoft/pxt-microbit/issues/5366 and https://github.com/microsoft/pxt-arcade/issues/6105
=> Update the 'Identity' and 'share' base pages

libs/pxt-python/pxt-python-helpers.ts
fixes https://github.com/microsoft/pxt-minecraft/issues/2024
We were throwing an Index Error when trying to pop the 0th element because our check didn't include 0 as a valid index.
=> Fix indices check for pop operation in Python

cli/cli.ts, cli/server.ts
Add option to disable request authentication when running `pxt serve`. This is a security feature for external users that might be running pxt serve in production, but it was getting in the way for me when connecting to pxt serve remotely during local development (connecting from Xbox to my dev PC, in this case).
=> Add `--noauth` option to `pxt serve`

pxteditor/history.ts, webapp/src/dialogs.tsx, webapp/src/package.ts, webapp/src/workspace.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/2356
Three version history fixes:
1. Filter the history file out of the file explorer and github diffs
2. Explicitly save a history snapshot before restoring an old version of the project so that we definitely save the old version of the project
3. Save history whenever we do a share so that we don't have to wait for the user to make a change before it shows up in the version history
=> Force version history to update when restoring a version or sharing

webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/headerbar.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2366
Fixes https://github.com/microsoft/pxt-minecraft/issues/2325
Tweaks the simulator collapse toggle when in headless mode so that:
1. It doesn't show up in blocks
2. In JavaScript/Python, it says "Toggle the File Explorer" rather than "Toggle the Simulator"
3. When switching back to blocks the simulator pane automatically collapses if toggled on
This only affects headless mode which is only used by Minecraft.
=> tweak toggle simulator settings menu option in headless mode

kiosk/src/Components/GameList.tsx, kiosk/src/Services/LocalStorage.ts
* The compiled js for games can exceed local storage quota. Added protection for that.
* Fixed a bug where carousel touch/scroll could result in app state confusion around which game is the currently selected game.
=> kiosk: fixes for carousel touch nav, storage exceptions

theme/tutorial-sidebar.less, webapp/src/components/tutorial/TutorialCallout.tsx, webapp/src/components/tutorial/TutorialContainer.tsx
Fixes two perf issues for tutorials:
First, the tutorial callout was running it's resize observer even when not visible. The callback for the observer was checking the height of an element, which forces the browser to rerender elements to get an accurate number. I guarded this behind a check to see if the callout is visible and also cleaned up the event listeners in that component a little bit while I was there.
Second, the tutorial container was running a querySelector to get a reference to its container so that it could run a resize observer on it. Query selectors also force reflows, so I changed this to instead use a ref of the container element.
Finally, I fixed a small CSS bug that I noticed when resizing tutorials where the editor sidebar wasn't taking up the whole height of the …
=> Fixing a couple of forced reflows in our tutorial components

kiosk/src/Services/GamepadManager.ts
This will allow us to answer questions like: "how many kiosks use the shoebox controller?"
=> kiosk: log detected gamepad type to telemetry

kiosk/src/Components/PlayingGame.tsx, webapp/public/run.html
.. and added support setting color of "loading" text in run.html
Fixes https://github.com/microsoft/pxt-arcade/issues/5407
Fixes https://github.com/microsoft/pxt-arcade/issues/6137
=> kiosk: set color of "loading" text in run.html

kiosk/src/Components/PlayingGame.tsx, kiosk/src/Services/GamepadManager.ts
I also bound the reset button to exit game. There isn't a way to do this using only the shoebox controller otherwise.
Fixes https://github.com/microsoft/pxt-arcade/issues/6143
=> kiosk: fix for shoebox controller

kiosk/src/Components/PlayingGame.tsx, kiosk/src/config.json
Exit a game using the controller's back button (view button on newer controllers), not the start button (menu button on newer controllers). Start/view is used by the simulator to open the in-game settings menu.
Fixes https://github.com/microsoft/pxt-arcade/issues/6145
=> kiosk: remap esc to the controller's back button

kiosk/src/Components/HighScoreInitial.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6134
=> kiosk: fix for skipped letters when entering high score

kiosk/src/Components/AddingGame.tsx, kiosk/src/Components/AppModal.tsx, kiosk/src/Components/GameOver.tsx, kiosk/src/Components/Modal.tsx, kiosk/src/Components/NewScoreEntry.tsx, kiosk/src/Components/PlayingGame.tsx, kiosk/src/Services/GamepadManager.ts, kiosk/src/Services/SimHostService.ts, kiosk/src/Transforms/navigate.ts, kiosk/src/config.json
Change looks bigger than it is due to some symbol renaming. Essential diff is at GamepadManager.ts:507.
Fixes https://github.com/microsoft/pxt-arcade/issues/6149
=> kiosk: map controller Y to escapebutton functionality

webapp/src/gitjson.tsx
This is a very targeted fix. I tried going through and making "main" and "master" equivalent throughout the github integration code ([thsparks/fix_main_in_github_integration](https://github.com/microsoft/pxt/tree/thsparks/fix_main_in_github_integration)), but I struggled with how to determine which one is used by a repo when on a non-main/master branch and I didn't think it was worth spending a ton of time on, so I paused that and focused on this quick fix instead. At least now, you can push releases and create branches from a Main branch.
=> Enable GitHub Release Zone in Main Branches.

localtypings/pxtarget.d.ts, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5350
Also adds an option to pxtarget.json that lets you control the volume of the sounds for a target (e.g. if they've been overridden)
=> Fix blockly sound effects and add volume option

webapp/src/dialogs.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2382
Now when you save a copy of a project from version history, a toast shows up telling you it happened.
=> Add info message after saving a copy of a project in time machine

webapp/src/editortoolbar.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2381
We can't use the simulator from within version history for minecraft so i'm hiding the run button altogether.
=> hide the big run button in time machine embed frames

kiosk/src/Components/PlayingGame.tsx, kiosk/src/Services/SimHostService.ts
This change is just enough to enable regression testing of the simulator on touch-only devices. More work is needed to make kiosk functional on mobile.
Also: filter key events from the sim to just the ones we want.
Fixes https://github.com/microsoft/pxt-arcade/issues/6103 (technically)
=> kiosk: show sim buttons on mobile, and an input tweak

common-docs/identity/cloud-sync.md
Remove the 'arcade only' notes from common target 'identity' pages.
The note in `sign-in.md` was removed by a direct commit earlier: https://github.com/microsoft/pxt/commit/58dcaae51cb33bbecf6b255ec808f75528d120d0. A similar note is removed from `cloud-sync.md` here.
Closes https://github.com/microsoft/pxt-microbit/issues/5263
=> remove arcade only note from identity pages

kiosk/src/App.tsx, kiosk/src/Components/GameSlide.tsx, kiosk/src/Components/PlayingGame.tsx, kiosk/src/Services/BackendRequests.ts, kiosk/src/Services/GameRefreshService.ts, kiosk/src/Services/IndexedDb.ts, kiosk/src/Services/SimHostService.ts, kiosk/src/State/Actions.ts, kiosk/src/State/Reducer.ts, kiosk/src/State/index.ts, kiosk/src/Transforms/saveNewGamesAsync.ts, kiosk/src/Types/index.ts, kiosk/src/Utils/index.ts, pxtlib/emitter/cloud.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6159
Fixes https://github.com/microsoft/pxt-arcade/issues/6138
I tried to keep this simple, but it ended up being a pretty big change.
=> kiosk: periodically refresh persistent shared games

kiosk/src/App.tsx, kiosk/src/Components/GameList.tsx, kiosk/src/Components/GameSlide.tsx, kiosk/src/Kiosk.css, kiosk/src/State/Reducer.ts, kiosk/src/State/State.ts
More fun with Swiper idiosyncrasies. When Swiper's `loop` option is enabled, it will duplicate slides until there are three, but it won't distinguish between them when rendering, so you won't know which is actually selected. Transitioning between these duplicated slides doesn't reliably trigger a React re-render. I had to work around this behavior to get the carousel rendering correctly when there were less than three games uploaded and clean=1. @srietkerk this probably sounds familiar to you! :)
Fixes https://github.com/microsoft/pxt-arcade/issues/6169
Fixes https://github.com/microsoft/pxt-arcade/issues/6136, incidentally
=> kiosk: Fix for clean=1 param

webapp/src/extensionsBrowser.tsx
When searching for extensions in the Minecraft target, clicking on the magnifying glass icon on the right of the search bar wouldn't do anything. It was unclear to me why it was behaving differently. As far as I could tell, there weren't any flags that would set this in the target itself and when inspecting the html, everything looked the same as it does in arcade, where clicking the icon will kick off a search as expected. 
Adding the `onIconClick` field to the input _does_ change the icon into a button, but I think this is a fine change. I actually think that this modification makes it clearer that the icon can be clicked since it comes with the css that we have defined for common-buttons (pointer and darker background color on hover). 
This is a quick video showing how it looks as only …
=> Added `onIconClick` to extension search input

webapp/src/onboarding.ts
To enable the editor tour in Minecraft, we need to include the play button which is specific to Minecraft.
=> Editor tour: add play button for Minecraft

docs/writing-docs/snippets.md, docs/writing-docs/tutorials/basics.md
Wanted to update the docs to include the changes made in https://github.com/microsoft/pxt/pull/9675.
These can now be utilized in Minecraft to validate non-highlighted blocks, which is nice!
=> Update Code Validation Docs to Include Validate-Exists Marker

localtypings/pxtarget.d.ts, pxtcompiler/simpledriver.ts, pxtlib/patch.ts, webapp/src/compiler.ts
Need this so we can update python code when we make a breaking change. I mostly just copied whatever we were doing for typescript and tried to do it for python as well.
=> Add Support for Python Upgrade Rules

pxtcompiler/emitter/snippets.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/2438
Thanks to @riknoll for pointing me in the right direction.
I'm removing the `emitAsConstant` check which was originally added (https://github.com/microsoft/pxt/pull/8983/files) to address this issue https://github.com/microsoft/pxt-minecraft/issues/2170 that is also regarding python snippets.
The snippet is still correct even with the removal of the `emitAsConstant` check as shown below.
=> Prevent python snippet enums from being snakified

localtypings/pxtarget.d.ts, pxtcompiler/simpledriver.ts, pxtlib/patch.ts, webapp/src/compiler.ts
Cherry-pick of https://github.com/microsoft/pxt/commit/98cda85365e9eaef2a97c7f52eec030507c2033d
Need this so we can update python code when we make a breaking change. I mostly just copied whatever we were doing for typescript and tried to do it for python as well.
=> Add Support for Python Upgrade Rules (#9776)

pxtlib/emitter/cloud.ts, pxtrunner/runner.ts
In pxtrunner, before building the project from source, attempt to fetch the compiled game from the backend.
Tested with run.html and works locally. I'm unsure this is the best approach though, and I don't know if this will work with the share page.
=> Before compiling, try to fetch built js from backend

pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_sprite.ts
The sprite editor will now check for qualified names such as "sprites.food.smallBurger" when converting to blocks from JS and maintain those names when converting back to JS.
This change in combination with https://github.com/microsoft/pxt-common-packages/pull/1459 is a fix for the image picker problem that @kiki-lee was having in which using a qualified name resulted in the block having an image picker instead of the sprite editor.
Before:
After:
=> Check for qualified name in sprite editor

pxtsim/embed.ts, pxtsim/simdriver.ts
In the radio scenario, the robot simulator (https://github.com/microsoft/microbit-robot) will receive messages from multiple microbits. The botsim needs know if a message is coming from the primary or secondary microbit.
=> Add index of the source iframe to the broadcast message

pxtsim/embed.ts, pxtsim/simdriver.ts
* Add index of the source iframe to the broadcast message
* avoid using potentially filtered frame array
=> [stable9.0] cherry-pick: Add index of the source iframe to the broadcast message (#9790)

pxtrunner/runner.ts
Enables telemetry in `runner.ts` to track the time it takes to either download the compiled JS or download and compile the text. These events will help know the impact the pre-compilation step is having.
Ran pxt-arcade locally with a local `pxt` on this branched linked. I then changed the InstrumentationKey in [apptracking.html](../blob/master/docfiles/apptracking.html) and [tracking.html](../blob/master/docfiles/tracking.html) to the PPE app insights instance. 
- Visited http://localhost:3232/68336-13291-41085-56601 in an incognito tab a few times. I was then able to confirm the new `runner.fetchSimJsInfo` event was present.
- Visited http://localhost:3232/56776-01920-30861-75662 in an incognito tab a few times. Confirmed that the new `runner.buildSimJsInfo` event was present.
Both these …
=> Track js compilation time

docs/writing-docs/tutorials/basics.md
Link to the reference for ```` ```package```` broke in the last redo of the tutorial docs.
=> Fix link to package spec reference in tutorial docs.

docfiles/pxtweb/cookieCompliance.ts, pxtlib/analytics.ts, pxtlib/main.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/simulator.ts
This adds two tick events that contain all of the info from the performance report that we print out to the console:
* `performance.milestones` - a map of event names to the elapsed time since page load for when that event occurred. For example, if blockly loaded 2 seconds after page load you'd get an entry like this: `loadBlockly: 2000`
* `performance.durations` - a map of task names to the amount of elapsed time that task took to complete
These ticks are only sent once per session! That makes them most useful for activities that are loaded directly from a URL, as the minecraft tutorials are.
I also added three new duration measures:
* `startActivity` - this is the overall time it takes for a tutorial or example to load into the editor
* `downloadMarkdown` - this is the time it takes to …
=> add tick events for perf measurements

cli/server.ts, pxtlib/main.ts
We already have this set to eval in the backend. Just changing it here so it works locally too.
=> Change Expected Web App Name from TeacherTool to Eval

pxtlib/blocks.ts
Change the old help paths for the built-in number blocks to something valid.
RE: https://github.com/microsoft/pxt-arcade/issues/6231
=> Set valid help paths for built-in number blocks

localtypings/pxtarget.d.ts, pxteditor/history.ts
I'm a little worried about accidentally making projects too big in arcade and messing with cloud sync. Adding a couple of pxtarget.json options to increase the project history interval so that we can start with a higher interval and lower it if all goes well.
=> Add pxtarget.json options for tuning time machine intervals

package.json, scripts/npm-prepare.sh
Moved for maintainability. It was getting very long and unwieldly.
=> Move npm prepare to a script

pxtlib/emitter/cloud.ts, pxtrunner/runner.ts
* Before compiling, try to fetch built js from backend (#9778)]
* Track js compilation time (#9794)
- Ran these changes locally with `pxt-arcade` on the `stable1.12` branch.
- Hit the http://localhost:3232/68336-13291-41085-56601 endpoint and confirmed the already compiled JS was downloaded.
- Confirmed the new `perfMeasurement` event was sent via the network tab.
=> [stable8.5] Cherry-pick built sim JS changes

pxteditor/editorcontroller.ts, webapp/src/app.tsx
This change adds an event that gets sent to the parent when the editor content loads. We need this for the teacher tool app, so we know once the project has finished loading inside the iframe.
=> Send Notification to Parent Frame when Editor Content has Loaded

webapp/src/idbworkspace.ts
I originally did this so that I wouldn't have to worry about accidentally giving too low a version, but this ends up bricking the old pouchdb database and making it inaccessible. 5 is the value that pouchDB uses internally.
=> Don't give a ridiculously high pouchdb version

pxtlib/browserutils.ts, webapp/src/idbworkspace.ts
This fixes a couple of pouch db migration bugs.
First, I was writing back to the pouchDB db to mark each entry as migrated so that we didn't accidentally re-import them. This was causing problems due to the internal structure of the pouchDB which has some uniqueness constraints that were being violated. Now I just sidestep that issue by storing the ids of the projects that have already been migrated in a separate db. This fixes the issue we were seeing with github projects in testing.
Secondly, I now check to see if the pouchDB actually exists before doing any migrating. This fixes an issue that prevented accessing old versions of the editor if you were in a browser with no pre-existing pouchDB. Figuring out if the db already exists was a little tricky; see the comment in the function for …
=> Fix pouch db migration edge cases

webapp/src/idbworkspace.ts
This fixes one of the issues I mentioned in standup with cloud sync and the pouchDB migration.
This is an internal property that pouchDB uses as its primary key. We have no reason to keep it around, and if it goes out of sync with the other project metadata it prevents a project from being synchronized on older versions of the editor.
=> Delete the _doc_id_rev when migrating entries

pxtblocks/code-validation/evaluationResult.ts, pxtblocks/code-validation/rubricCriteria.ts, pxteditor/editor.ts, pxteditor/editorcontroller.ts, teachertool/src/App.tsx, teachertool/src/components/EvalResultDisplay.tsx, teachertool/src/teacherTool.css, webapp/src/app.tsx
Big thanks to @thsparks for helping me get this set up.
Currently, the validation works for `BlockCheckCriteria` only. It takes the rubric and sets the required block counts for each block id. Then it runs the `validateBlocksExist` function for each set of blocks in the rubric.
Upload target: https://arcade.makecode.com/app/5df94cd2b924c898ff9960973789eff8048cc4c5-2776605799--eval
Sample share link: https://arcade.makecode.com/S42128-59682-77192-60950
Sample rubric:
```JSON
{
"criteria": [
{
"displayText": "One or more custom functions that must be called",
"criteriaId": "blockCheck",
"blockRequirements": [
{
"blocks": ["function_call", "function_call_output"],
"count": 1
},
{
"blocks": ["function_def"],
"count": 1
}
]
},
{
"displayText": "Two different kinds of loops used",
"criteriaId": …
```
=> Teacher tool: Initial validation logic

pxtblocks/blocklyloader.ts, pxtlib/blocks.ts, webapp/src/app.tsx
This adds the tooltipBlockIds URL parameter. When set to 1 in the URL (?tooltipBlockIds=1), blocks will include their block id in the tooltip when you hover over them.
I'm doubtful that an exported bool directly inside pxt.blocks is the best way to store this, but I figured I'd send the PR anyway and get feedback. If anyone has thoughts on a better approach, please let me know!
=> Add URL Parameter to Show Block IDs in Tooltip

teachertool/src/components/DebugInput.tsx, teachertool/src/components/MakecodeFrame.tsx
Changed the url query parameters to include `readonly=1` and `teachertool=1`. 
Relies on https://github.com/microsoft/pxt-arcade/pull/6327 for the `teachertool=1` styling.
This is what the iframe looks like with the current changes:
And here's an upload target (updated, with the mem flag, so projects in iframe in teacher tool should not show up in your project list): https://arcade.makecode.com/app/10ca0330285532cd740f0c3893c6f8850eb544c6-133a36c7a3--eval
=> Teacher tool: updated iframe url to be readonly

gulpfile.js, pxtrunner/debugRunner.ts, pxtrunner/embed.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, pxtrunner/tsconfig.json, webapp/public/embed.js
This PR looks much bigger than it actually is; you probably want to view the diff with ignore whitespace turned on.
Making this change because our new Blockly code is module based so everything that interacts with Blockly needs to be a module as well. There are no real changes to code here, just a straight conversion from namespaces to modules and fixing a bunch of qualified names.
I also defined a new file, `pxtrunner/embed.ts`, which puts all of the runner code into the global namespace so it can be appended to pxtembed.js (which is itself included in various pages like --docs, --embed, --run, etc.). The file serves as the entrypoint for browserify
Eventually I'll get around to converting everything into modules and that file will no longer be necessary
=> Convert pxtrunner into modules

react-common/components/util.tsx, teachertool/src/App.tsx, teachertool/src/components/HeaderBar.tsx, teachertool/src/components/MainPanel.tsx, teachertool/src/components/MakecodeFrame.tsx, teachertool/src/components/SplitPane.tsx, teachertool/src/components/styling/MainPanel.module.css, teachertool/src/components/styling/SplitPane.module.css, teachertool/src/teacherTool.css
The main reason for this PR is to introduce "module css". This is a feature we get with create-react-app that scopes css class names to their module, making it easier to use simple names for css classes and they won't clash with one another.
Module css docs:
* https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/
* https://css-tricks.com/css-modules-part-1-need/
This PR contains some React changes too, but it is work in progress and will likely change a lot.
=> teacher tool - set module css pattern

teachertool/src/App.tsx, teachertool/src/components/ActiveRubricDisplay.tsx, teachertool/src/components/CatalogModal.tsx, teachertool/src/components/DebugInput.tsx, teachertool/src/components/EvalResultDisplay.tsx, teachertool/src/components/HeaderBar.tsx, teachertool/src/components/MainPanel.tsx, teachertool/src/components/MakecodeFrame.tsx, teachertool/src/components/Notifications.tsx, teachertool/src/components/SplitPane.tsx, teachertool/src/index.tsx
In the interest of long-term code maintainability, prefer not to use default export unless there is a compelling reason for it. Default exports have a few gotchas that I'd like to avoid:
* The name assigned to the import can be anything, and doesn't reflect what you're actually importing.
* They're not discoverable by IntelliSense. You have to open the file to see what you're actually importing. The filename isn't a reliable source of information.
* During the inevitable refactor/renaming, you must search the code and manually update every import to match the new component name. The compiler can't help you.
Sometimes a default export is the appropriate pattern to employ, but let's not make them the default export pattern we employ. (Did I break your parser? :))
=> teacher tool - don't default export components

cli/cli.ts
When `pxt serve` is running and I make the slightest typo in a .less file, the less compiler errors and the cli dies. This adds a lot of friction during development due to the overhead of restarting `pxt serve`.
With this change, the cli will log the build failure and move on.
=> allow pxt cli to survive css build errors

teachertool/src/components/EvalResultDisplay.tsx, teachertool/src/components/MakecodeFrame.tsx, teachertool/src/services/makecodeEditorService.ts, teachertool/src/transforms/loadProjectMetadataAsync.ts
Fixes a bug where you couldn't run eval multiple times. (In fact, messaging to the iframe was totally breaking down.)
Before this change, the `makecodeEditorService` unset its `readyForMessages` flag anytime the iframe ref was updated. This was done under the assumption that the ref updating also means the iframe would reload, which turns out to be untrue. As a result, we end up setting `readyForMessages` to `false` and get stuck because the editor inside the iframe does *not* send its `editorcontentloaded` event again, since it already did so a while ago.
I basically took the simplest approach to fixing this, which is to make the `readyForMessages` reset an intentional action, and only call that when we change the iframe url. It seems to work in my testing and I'm struggling to find a …
=> Fix MakeCode Editor Service Ready State

docs/teachertool/catalog-shared.json, docs/teachertool/validator-plans-shared.json, pxtblocks/code-validation/runValidatorPlanAsync.ts, pxtblocks/code-validation/validateCommentsExist.ts, pxtblocks/code-validation/validateSpecificBlockCommentsExist.ts, pxtblocks/code-validation/validatorPlans.ts
I added two block comments validators to be used in the teacher tool but should also be usable in tutorials. 
The first is a very rudimentary validator. It's for the use cases that users might not care where or how the comments are used, just that comments exist in the project.
The second is for when a users want to check that a specific type of block has a block comment on it. For example, a common ask I had from my professors was to add comments to every function definition. Users of the teacher tool might want to do the same, so if there is a block type specified, the validator will make sure that all blocks of that type has a comment on it. For teacher tool purposes, this is pre-defined only for function definitions at the moment, but an expansion would be when we introduce …
=> Teacher tool: added block comments validators

.github/workflows/codeql-analysis.yml
Adding the `security-events: write` permission to the code ql workflow. This should fix the [errors we've seen in the workflow](https://github.com/microsoft/pxt/actions/runs/7746005421/job/21123225546#step:9:55).
=> Add permission block for Code QL workflow

docs/teachertool/validator-plans-shared.json, pxtblocks/code-validation/runValidatorPlanAsync.ts, pxtblocks/code-validation/validateBlocksInSetExist.ts, pxtblocks/code-validation/validateSpecificBlockCommentsExist.ts, pxtblocks/code-validation/validatorPlans.ts
This PR establishes the block in set validator. I thought the `blocksInSetExist` terminology made more sense than `blockSetExists` since we're not checking that a group of blocks exist. With this validator, we're checking that some kinds of blocks from a set exist, so I'm hoping `blocksInSetExist` is more descriptive. I'm up for changing it, though, if people feel strongly.
For its use for now, I plugged it into the `custom_function_call` validator plan we have in an example in our OneNote. It's a good example of how we'd want to use two different validators together where we want to make sure that a function is made and it is either called and the return function is accessed or it's just called. The `blocksInSetExist` validator is meant to handle this "or" scenario. 
Here are some other …
=> Teacher tool: block in set validator added

pxtlib/util.ts
The locale name for `sr` should be `Serbian (Cyrillic)` and not `Serbian (Latin)`. The locale names in the [Crowdin Language Codes](https://developer.crowdin.com/language-codes/) list them as:
Crowdin Code | Name
-- | --
sr | Serbian (Cyrillic)
sr-CS | Serbian (Latin)
Naming it as "Serbian (Latin)" is a bit misleading to users seeing Cyrillic while expecting Latin script.
=> Correct the Serbian locale name field

teachertool/src/components/RubricWorkspace.tsx, teachertool/src/components/styling/RubricWorkspace.module.scss
=> teacher tool: autorun placement

pxtblocks/fields/field_tilemap.ts, pxtblocks/fields/field_tileset.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/spriteutils.ts
The desire for this came up on stream last week and we occasionally get people asking for it on the forum. Adding support for tilemaps that have 4x4 tiles. Stay tuned for the very small common packages PR supporting this.
I also tried out 2x2 tiles for the heck of it but looks like that is not supported by our physics engine (which I more or less expected to be the case).
=> Add support for tilemaps with 4x4 tiles

teachertool/src/transforms/addCriteriaToRubric.ts, teachertool/src/transforms/removeCriteriaFromRubric.ts, teachertool/src/transforms/setRubricName.ts
This change sends all `setRubric` calls through the `setRubric` transform (https://github.com/microsoft/pxt/blob/master/teachertool/src/transforms/setRubric.ts), so they don't call into the action directly. This is just a refactor; there is no change in functionality.
I didn't do this originally because the setRubric transform was doing a bunch of validation that would have been redundant, but I refactored that out and forgot to go in and change these calls. Now with this change, we can rely on the transform to poke autorun and we don't need to call that separately every time.
=> Teacher Tool: Consolidate Calls to SetRubric

pxteditor/code-validation/validateSpecificBlockCommentsExist.ts
I noticed a bug for the criteria "all function definitions have comments" where if there were no functions defined, the validator would be successful because of the condition I set for the passed variable. I modified it to make it so if there aren't any blocks of the specified type, passed is just false. 
Through this I learned that filter is totally fine with operating on an empty list. Being that this is the case, I don't feel the need to check the length of `allSpecificBlocks` before filtering for `uncommentedBlocks`. If anyone feels strongly otherwise, I can add a check/optional chain.
=> Comments on specific blocks validator now fails if no specific blocks exist

common-docs/teachertool/catalog-shared.json, common-docs/teachertool/validator-plans-shared.json, localtypings/validatorPlan.d.ts, pxteditor/code-validation/runValidatorPlan.ts, pxteditor/code-validation/validateBlockFieldValueExists.ts
A validator that checks the field values of a block has been added to our validator library. Field values are a specific type of input for a block. The easiest type that I can demonstrate is the different operators that are associated with the `math_arithmetic` block. In this case, the field value _type_ is "OP" or, I'm guessing, the shorthand for operation. Some others that I've seen in `blocklycompiler.ts` are: `TEXT, EXPRESSION, VAR, BOOL, NAME, VALUE` and more. The "OP" field value for the `math_arithmetic` block can be `ADD, MINUS, MULTIPLY, DIVIDE` and more.
You'll see that the validation I made for `logic_compare` is looking for something very specific. The `logic_compare` blocks in the following program don't pass because the one that has the `EQ` "OP" type doesn't have two …
=> Teacher tool: field value validator added

scripts/patchUglifyify.js, teachertool/src/components/CriteriaTable.tsx
pxtblocks.d.ts no longer exists
also, fixing the patch script i have so that it does nothing if pxt-core is installed as a dependency
=> fix uglify script and remove pxtblocks reference

teachertool/src/services/storageService.ts
Fixes https://github.com/orgs/microsoft/projects/1046/views/1?pane=issue&itemId=53913156 ("bug: criteria don't persist for unnamed rubric.")
=> Allow a Rubric with an Empty Name to be Loaded

teachertool/src/state/helpers.ts, teachertool/src/types/criteria.ts
As we start to make rubrics for some tutorials, it's going to come up that we don't want those very specific rubric-based criteria to show up in the catalog list. This flag will make it so if you specify `"hideInCatalog": true` in the `catalog__.json` entry, then that criteria will not show up in the modal.
=> Teacher tool: Added hidden flag for catalog criteria

gulpfile.js, pxtblocks/plugins/math/fieldSlider.ts, tests/blocks-test/blocksrunner.ts, tests/blocks-test/blockssetup.ts, tests/blocks-test/karma.conf.js
This PR fixes the blocks test runner that we use to prevent breaking changes in target blocks.
These tests are only used in pxt-microbit AFAIK
Also fixed a bug that the tests actually caught, which is that the slider field was constraining values more aggressively than it should.
=> Fix target blocks test runner (and slider field)

pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_sprite.ts, pxtblocks/fields/field_tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6296
Fixes https://github.com/microsoft/pxt-arcade/issues/5942
So, turns out we always supported default values for assets in block definitions; the only thing that was broken was the preview in the flyout. This fixes that flyout and also restores the qname change that @kimprice made a while back that got lost in the blockly merge.
Here is an example of setting default values for an image three different ways:
```typescript
namespace custom {
/**
* This version sets the default using an image literal. Note that
* newlines need to be replaced by \n
*/
//% blockId=screen_image_picker2 block="$img"
//% shim=TD_ID
//% img.fieldEditor="sprite"
//% img.fieldOptions.taggedTemplate="img"
//% …
```
=> restore qname support for image editor and default preview in flyout

teachertool/src/components/MainPanel.tsx, teachertool/src/components/SplitPane.tsx, teachertool/src/components/styling/SplitPane.module.scss, teachertool/src/services/storageService.ts, teachertool/src/state/helpers.ts
This makes it so the splitter can actually be used to resize the windows. I've also made it so you can double-click the split to reset it to its original position.
I intentionally did not tie the split position into app state, so the control will be more reusable in the future, if we move it to react common.
It'd be nice to merge this and the existing VerticalResizeContainer, but they've approached the problem from two somewhat different angles that makes the refactor a bit messy. The VerticalResizeContainer is a single window that can have its height changed, but it doesn't care what's shrinking/expanding below it. Meanwhile, this is a container for two different panels that manages both sides. In the future, I think it'd make sense to move this SplitPanel into React Common and take …
=> Teacher Tool: Make Splitter Functional

pxtblocks/plugins/renderer/connectionPreviewer.ts, pxtblocks/plugins/renderer/constants.ts, pxtblocks/plugins/renderer/index.ts, webapp/src/blocks.tsx
The latest version of Blockly added the ConnectionPreviewer extension point. This adds one to render our reindeer connections and increases the snap radius to match what we had in pxt-blockly
=> Restore the reindeer connection previewer

webapp/src/idbworkspace.ts
This fixes the bug we saw when trying to add browser prefixes to arcade yesterday.
If there is no prefix set for a previous version of the editor, we should migrate scripts from the default prefix instead of migrating nothing.
=> Fix importing past scripts when no previous browser prefix is set

webapp/src/blocks.tsx
Readonly mode wasn't being honored in the blockly workspace because we were resetting the flag based on whether or not we were in debug mode. With this change, we will also account for the original readonly mode in that check.
=> Fix Readonly Mode

teachertool/src/components/styling/ImportRubricModal.module.scss, teachertool/src/global.scss, teachertool/src/style.overrides/Modal.scss
We should consider porting this to react-common.
=> tt: enable vertical scrolling in modal dialog

teachertool/src/services/backendRequests.ts
I was getting old versions of validator-plans and catalog.json. Turns out they're getting cached by the browser. Specifying `no-cache` on the fetch request so that the files, if cached, will still work offline, but the cache will be refreshed after each new request.
=> re-cache json docs on request

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_sprite.ts, pxtlib/package.ts, pxtlib/spriteutils.ts, pxtlib/tsconfig.json
This is an addendum to my earlier pr https://github.com/microsoft/pxt/pull/9878 which neglected to fix the palette when it was in the pxt.json of a dependency rather than the top package.
Also adds the ability to configure the image and animation editors to compile/parse different tagged template literals since micro:bit can't use `img`. To use it, simply add it to the field options on the function defining the field editor like so:
```
//% bmp.fieldOptions.taggedTemplate="bmp"
```
it might already be there since this is the same field option we use for configuring the decompiler.
=> Fixes for image editor in micro:bit

teachertool/src/components/SplitPane.tsx
When the user hasn't set a size directly, we were seeing the panel resize depending on the tab. This was because the startingSize was an empty string and we were doing a nullish check instead of a falsey one for the initial splitter position, so it was using that empty string for the initial flexBasis instead of the default 50%.
=> Fix Comparison in Splitter Default Size

pxtblocks/plugins/renderer/connectionPreviewer.ts, pxtblocks/plugins/renderer/pathObject.ts
@thsparks pointed out that when I added in reindeer connectors, we lost insertion markers. I didn't realize these has been moved from the InsertionMarkerManager into a ConnectionPreviewer, so now I'm just extending the previewer so that we get insertion markers back.
=> Extend default connection previewer

pxtblocks/fields/field_textdropdown.ts, pxtblocks/plugins/flyout/verticalFlyout.ts, webapp/src/blocks.tsx
Fixing our keyboard navigation. Three small bugs:
1. The dummy workspace was never initialized in the multi-flyout and caused an exception during init
2. We were immediately closing the flyout when the cursor moved because of the workspace event being fired
3. The dropdown portion of the text dropdown field was being focused, which broke typing into the field.
=> Fix the keyboard navigation plugin support

teachertool/src/components/ShareLinkInput.tsx, teachertool/src/components/styling/ShareLinkInput.module.scss, teachertool/src/style.overrides/Button.scss
https://makecode.microbit.org/app/8064d90149396080f7266d4f8935b133be8e7173-7d530bca36--eval
Just a note that the styling is a bit off in the upload target, even though I built the css, the upload target is using `-0.75rem` for the margin instead of `-1rem` to get the button hugging the right side more like in our design right now. 
This is what it looks like with `margin-right: -1rem`
=> Teacher tool: icon in sharelink input now clickable

common-docs/teachertool/test/validator-plans-shared.json, common-docs/teachertool/validator-plans-shared.json, localtypings/validatorPlan.d.ts, pxteditor/code-validation/runValidatorPlan.ts
The structure of the `blockCounts` input for `blocksExist` validator plans was not JsonPath friendly, as the customizable `blockId` was treated as a property and it was also a part of the path for count. This change adjusts the schema so both `blockId` and `count` can be referenced more easily by [JsonPath](https://github.com/json-path/JsonPath), which we will need for parameterized criteria.
No user-facing functionality changes.
=> Update Blocks Exist Json Schema for JsonPath Friendliness

teachertool/src/components/CriteriaEvalResultDropdown.tsx, teachertool/src/components/CriteriaResultEntry.tsx, teachertool/src/components/EvalResultDisplay.tsx, teachertool/src/components/PrintButton.tsx, teachertool/src/state/actions.ts, teachertool/src/state/reducer.ts, teachertool/src/transforms/initNewProjectResults.ts, teachertool/src/transforms/loadProjectMetadataAsync.ts, teachertool/src/transforms/setEvalResultNotes.ts, teachertool/src/transforms/setEvalResultOutcome.ts, teachertool/src/transforms/setEvalResultsPending.ts, teachertool/src/transforms/setRubric.ts, teachertool/src/types/criteria.ts, teachertool/src/types/index.ts, teachertool/src/utils/index.ts
Noticed we had quite a large list of prettier issues. Wanted to clean those up. No functional changes, just ran "npm run prettier" from the teachertool folder and confirmed it built/ran fine.
=> Teacher Tool: Run Prettier

pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_tilemap.ts
Cherry picking https://github.com/microsoft/pxt/pull/9886 to the stable branch used by arcade.
The diff looks different than the original pr because in that pr i was also restoring some code that accidentally was lost in the blockly merge. that code was already cherry picked to this branch a while ago, so no need to replicate it.
=> [Stable8.5] Cherry pick https://github.com/microsoft/pxt/pull/9886 to arcade stable

.github/workflows/codeql-analysis.yml
This isn't actually blocking anything (the action that handles pxt bumps is still running fine) but this PR fixes the codeql action on stable8.5 because it was annoying me.
=> [Stable8.5] Cherry pick codeql fix

pxtservices/iframeDriver.ts, pxtservices/tsconfig.json, teachertool/src/components/MakecodeFrame.tsx, teachertool/src/services/makecodeEditorService.ts, teachertool/tsconfig.paths.json, webapp/src/app.tsx, webapp/src/cloud.ts
This PR adds a new top-level package called pxtservices to be shared between our many webapps. Currently it just contains a single file that defines a nifty class for driving iframes that embed the makecode editor. Features include:
* All currently defined requests now have type checked methods (no more calling postMessage directly)
* An optional host object parameter that lets you implement all of the methods required by the iframe workspace (no need to figure out how that protocol works)
* All editor events/messages can be accessed via `addEventListener()` (also type checked)
As part of this, I also fixed three editor events that were being incorrectly fired with the "pxteditor" type instead of "pxthost". The "pxteditor" versions still fire so as not to break existing implementations.
I …
=> Add pxtservices package and iframe driver

pxtsim/sound/sequencer.ts
This is an exception we ran into on stream today. The dispose function in music sequencers was throwing an exception when it tried to communicate with the metronome after the metronome was already disposed of.
=> Fix exception when disposing sim sequencers

teachertool/src/services/makecodeEditorService.ts
We're seeing intermittent errors in teacher tool where we're trying to call ToString() on undefined. This is happening because, in `setEditorRef()`, we are calling `driver.setHighContrast(highContrast);` without initializing the `highContrast` var to anything. As a result, we were passing in `undefined` which was breaking things down the line.
=> Fix Set High Contrast Error

webapp/src/idbworkspace.ts
When going to pxt-microbit beta the other day, I noticed a few of my scripts being left behind. Turns out I didn't account for the possibility of the same header existing multiple times in different versions of the pouch db!
This corrects that by prepending the browser prefix to the id we use for checking if something has been migrated.
=> Include prefix when marking scripts as already migrated

common-docs/teachertool/test/catalog-shared.json
Putting this into a separate change so it can be checked in and used to verify the block picker in an upload target when I send that PR, that way others can see it without needing a local build.
=> Teacher Tool: Set Block Type for "Block" Used "N" Times

libs/pxt-common/pxt-core.d.ts, pxtblocks/builtins/loops.ts, pxtblocks/builtins/variables.ts, pxtblocks/plugins/functions/blocks/functionDefinitionBlock.ts, pxtblocks/plugins/functions/extensions.ts, pxtblocks/plugins/math/fieldSlider.ts, pxtblocks/plugins/renderer/pathObject.ts, pxtblocks/plugins/text/fieldString.ts, pxtblocks/toolbox.ts, pxtlib/blocks.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5564
Fixes https://github.com/microsoft/pxt-microbit/issues/5562
Fixes https://github.com/microsoft/pxt-microbit/issues/5555
Fixes https://github.com/microsoft/pxt-microbit/issues/5554
Fixes https://github.com/microsoft/pxt-microbit/issues/5553
Several fixes of new-blockly regressions:
* quotes are now red again
* text blocks now have default parameters again (this was actually a bug in our old Blockly code, but I brought the default values back to mimic the old buggy behavior)
* adds a light contrasting outline for dark shadow blocks
* removes references to inDebugWorkspace, which is a method that no longer exists
* restores the old behavior of the slider field where it grabbed the track color from the parent block
I want to add a …
=> Several Blockly fixes

gulpfile.js, localtypings/pxteditor.d.ts, pxteditor/editorcontroller.ts, pxtservices/.eslintrc.js, pxtservices/assetEditorDriver.ts, pxtservices/editorDriver.ts, pxtservices/iframeDriver.ts, pxtservices/iframeEmbeddedClient.ts, teachertool/src/services/makecodeEditorService.ts, webapp/src/assetEditor.tsx
This PR does a few things:
1. Refactors the IFrameDriver into a base class and adds a new EditorDriver that takes the place of the old class
2. Adds another IFrameDriver that can be used to drive the asset editor embed (arcade.makecode.com/--asseteditor)
3. Adds a new IFrameEmbeddedClient that can be used within the embedded iframe to handle communication with the parent frame
4. Refactors our messaging protocol to use a MessageChannel so that we can support multiple iframe embeds at the same time
This is all 100% backwards compatible with old embeds. To use the new MessageChannel stuff, you need to add `?frameid=<some-unique-id>` to the iframe's src url, then everything will just work and it will automatically switch to using the MessageChannel. If you don't add that, the new code falls …
=> Refactor iframe communication and use MessageChannel

pxtsim/simlib.ts, pxtsim/visuals/boardhost.ts
This change is needed because the only thing that interacts with the BoardView is the BoardHost, and I need to be able to kill event listeners that were added to the BoardView. Needed for the fix for https://github.com/microsoft/pxt-microbit/issues/5434.
Edit: Part of this PR: https://github.com/microsoft/pxt-microbit/pull/5578
=> Pxsim: remove event listeners now a method that can be called from boardview

common-docs/teachertool/test/catalog-shared.json, common-docs/teachertool/test/validator-plans-shared.json
The implementation is not included here, but the docs changes are still needed to have the criteria appear in uploaded targets.
Of note: this _does_ introduce the idea of a "system" parameter, which is an input needed for the validator plan that can change based on context, but which the user doesn't really need to specify in their criteria template. In this case, that's the share id. The teacher tool will automatically populate system parameters based on the provided key.
=> Add Catalog and Validator Plan Entries for AI Questions

common-docs/teachertool/test/catalog-shared.json, common-docs/teachertool/test/validator-plans-shared.json
Cherry pick of #9950 into the v10 branch
The implementation is not included here, but the docs changes are still needed to have the criteria appear in uploaded targets.
Of note: this does introduce the idea of a "system" parameter, which is an input to the validator plan which can change based on context, but which the user doesn't really need to specify in the crtitera template. In this case, that's the share id. The plan is for the teacher tool to automatically populate system parameters based on the provided key.
=> Cherry-Pick to v10: Add catalog and validator plans for ai questions.

webapp/src/container.tsx, webapp/src/editortoolbar.tsx, webapp/src/headerbar.tsx, webapp/src/identity.tsx, webapp/src/projects.tsx, webapp/src/sui.tsx
Mostly fixes https://github.com/microsoft/pxt-microbit/issues/5424
The "mostly" lies in the fact that I left the `meta-viewport` failed rule. It's failing because we don't allow zooming on mobile. This is something that I can't nicely fix with our single-page app. It would be nice to allow for zooming on the homepage and disable zooming in the editor on mobile, but giving a pattern like that opens a lot of problems. A big one is that when I zoomed in on the home page and then switched over to the editor, the zoom would persist and just cause all sorts of problems. I could try setting the zoom styling when initially visiting the editor, but that property is not supported everywhere and not recommended by MDN. If we want to allow for zooming on mobile, we need to investigate a bit more and …
=> Accessibility insights fixes

webapp/src/identity.tsx
The data that we receive from the Microsoft auth service is does not have a `dataUrl` anymore, but a whole picture object where the image is encoded. I added a function to handle an encoded image for the avatar picture.
Fixes https://github.com/microsoft/pxt-microbit/issues/5477
=> Bug fix: Microsoft profile pic not showing

webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/immersivereader.tsx, webapp/src/tutorial.tsx
A change went live that returned Immersive Reader tokens with invalid expiration dates. Those tokens will effectively never expire; this becomes a problem since we do not remove invalid tokens. Meaning anyone who received the bad token is stuck unless they manually remove the token from local storage themselves.
Change the name of the Immersive Reader token so that those with a broken token will pick up a new one. Then make sure to remove the Immersive Reader token if there is a problem using it. That way if something like this happens again, we do not have to worry about old tokens sticking around.
[See Arcade build using these changes](https://arcade.staging.pxt.io/app/621989a31abe52ace25e198b1bd7b85d4c7a3f80-acef86db3b#editor).
- Using the above build navigate to the home page and …
=> Update the immersive reader token

cli/crowdin.ts, cli/crowdinApi.ts
Re-implementing the crowdin stats command with the v2 APIs.
FYI, I tweaked the behavior somewhat. The previous version of the command always checked translations for all targets even if it was run from within a target repo. I assume this was a mistake, so I made it so that it now filters the translations to only include core and the strings from the target repo it's run within (e.g. running within pxt-arcade will only check for translations of strings in pxt-arcade and pxt-core). Running the command within pxt-core will go back to the old behavior and collect stats for all targets at the same time. @abchatra FYI
Also, this will probably take a lot longer to run then the old version. The new APIs require us to make many separate requests as opposed to the old API's single request.
=> Re-enable crowdin stats command

cli/cli.ts, localtypings/pxtarget.d.ts, localtypings/pxtpackage.d.ts, pxtlib/browserutils.ts, pxtlib/emitter/cloud.ts, pxtlib/package.ts, pxtlib/util.ts, pxtrunner/runner.ts, skillmap/src/App.tsx, webapp/src/app.tsx
As mentioned in https://github.com/microsoft/pxt/pull/9954, I removed support for crowdin branches with the V2 upgrade. This PR removes the remaining traces of support we had throughout the webapp.
There was surprising amount of code for a crowdin feature that AFAIK we have never used.
=> Remove all traces of crowdin branch support

cli/cli.ts, cli/crowdin.ts, cli/crowdinApi.ts
When I was testing out my crowdin changes on pxt-ev3, I realized that I accidentally removed all pre-existing translations on the uploaded files when I pushed new versions (even though the new versions didn't actually change anything). The problem was that I didn't include the [update mode parameter that we used to include](https://github.com/microsoft/pxt/blob/cffd25243efa7b387843943791ac9b9fe7808b3c/pxtlib/crowdin.ts#L150) in our API requests. This PR restores that parameter so that when we upload files pre-existing translations stick around but are marked as unapproved. 
I also figured it was a good idea to restore the old versions of the pxt-ev3 files, so I added a new crowdin command for bulk restoring old file revisions:
```bash
pxt crowdin restore <date> [force]
```
This command …
=> Add restore command and keep translations when updating

pxtrunner/renderer.ts
There were three code snippets that were rendering on docs pages when we don't want them to:
1. Template snippets that are used to define the starting blocks of a tutorial
2. Global and local block configs so that blocks in tutorials could be given different default values in the toolbox (this was just a bug with the selector string we were using in JQuery)
3. Tutorial validation snippets
This change leverages what we already did for `renderGhost` and `renderBlockConfig`, and just creates new functions for the other cases. I was thinking about making two functions to cover all of the different cases where we need to remove the snippet, one for the snippets that also have the scoping and one for the rest (ghost, template), but I found that it didn't add any clarity to the code and actually …
=> Bug fix: global config snippets in tutorials no longer rendering on docs pages

docfiles/tocheader.html, pxtblocks/codecardRenderer.ts, pxtrunner/renderer.ts, theme/docs.less, theme/docs/tocheader.less
Fixes https://github.com/microsoft/pxt-microbit/issues/5475
Fixes https://github.com/microsoft/pxt-arcade/issues/4869
Also fixes the roles for the search box in the menubar @srietkerk FYI (sorry, I thought this was part of my bug. hopefully you weren't working on it)
While I was at it, I also removed some semantic ui stuff (but not all of it)
=> Fix TOC header and card list roles in docs

docfiles/docs.html, docfiles/tocheader.html, gulpfile.js, pxtrunner/renderer.ts, theme/docs.less, theme/home.less, webapp/public/docs.html
This PR fixes a bunch of small accessibility bugs. Each commit is a single fix, so you can also review it one by one if that helps.
Fixes https://github.com/microsoft/pxt-microbit/issues/5495
Fixes https://github.com/microsoft/pxt-arcade/issues/4865
Fixes https://github.com/microsoft/pxt-arcade/issues/4868 
Fixes https://github.com/microsoft/pxt-microbit/issues/5466
Fixes https://github.com/microsoft/pxt-arcade/issues/3969
Fixes https://github.com/microsoft/pxt-microbit/issues/5473
Does the following:
1. Adds underlines to links within paragraphs in docs pages
2. Adds a tile attribute to simulator frames embedded in docs pages
3. Sets the lang on docs html pages to "en" instead of `@locale@`
4. Gives the carousel arrows on the homepage an outline when focused
5. Marks landmark roles on …
=> Fix various docs/homepage accessibility bugs

localtypings/pxtarget.d.ts, pxtblocks/builtins/misc.ts, pxtblocks/loader.ts, pxtlib/color.ts, pxtlib/toolbox.ts, pxtrunner/renderer.ts, webapp/src/monacoFlyout.tsx, webapp/src/toolbox.tsx
Motivated by: https://github.com/microsoft/pxt-arcade/issues/4870
This PR adds a little code to automatically adjust all block background colors to have a contrast ratio of at least 4.5 with white foreground text. The algorithm I'm using is pretty dumb: I just lower the luminosity until a color with the correct contrast ratio is generated and cache the result.
I placed this behind a feature flag for now because the general consensus is that this makes all the blocks look duller/uglier and creates a breaking change with old screenshots. The goal should be for us to eventually turn this on in all targets; we might have to adjust the base colors of some categories to make them more visually appealing though (arrays is particularly ugly).
Here is an upload target in micro:bit with the feature …
=> Automatically adjust block colors to have a contrast ratio of 4.5

react-common/components/controls/Accordion/Accordion.tsx, react-common/components/controls/Accordion/context.tsx, react-common/components/controls/Accordion/index.tsx, react-common/hooks/useId.ts, react-common/styles/controls/Accordion.less, react-common/styles/react-common.less, theme/github.less, webapp/src/coretsx.tsx, webapp/src/gitjson.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5498
Fixes https://github.com/microsoft/pxt-microbit/issues/5503
Fixes https://github.com/microsoft/pxt-microbit/issues/5500
This PR contains two small accessibility fixes for the github integration and one larger one that also adds a new react-common accordion component.
The "History" portion of the GitHub integration is where the accordion is used. This overhauls that section with react-common components and fixes https://github.com/microsoft/pxt-microbit/issues/5500 in the process. The UI is basically unchanged.
=> Fix github accessibility bugs and add an accordion component

webapp/src/idbworkspace.ts
I finally figured out what's causing all of the project conflicts in beta! As I was debugging things today, I happened to notice that PouchDB was sometimes keeping multiple entries for the same document. I'm guessing this is part of some sort of internal redundancy mechanism that we don't use, but it was thwarting our project migration because we would sometimes end up migrating an older version of a script instead of the more recent version. When we go to sync this older version, we get an exception and it causes the conflict.
Luckily, it appears the revision number is stored in the pouch db document id, so it's easy to parse.
=> Fix bug causing project conflicts when migrating scripts from pouch db

common-docs/teachertool/catalog-shared.json, common-docs/teachertool/test/catalog-shared.json, teachertool/src/components/CatalogOverlay.tsx, teachertool/src/components/MakecodeFrame.tsx, teachertool/src/state/helpers.ts, teachertool/src/types/criteria.ts
This change allows us to specify a maximum count for catalog criteria, which defines how many instances a user is allowed to have for a given catalog criteria. It also removes the attempted auto-detection of whether or not we should allow multiple instances (which was based the presence of parameters), since that didn't work well for criteria like "Must have [count] comments". If the field is not set, we assume no max.
I decided to go with a max count rather than a simple `allowMultiple` boolean, because I thought it might be useful to have some criteria where multiple instances are allowed, but not an unlimited number of them. (For example, I've limited the copilot questions to a max of 10, since they're expensive.)
I've also removed "All function definitions have comments" per feedback …
=> Teacher Tool: Max Count for Catalog Criteria

pxtservices/iframeEmbeddedClient.ts
I *think* this is the culprit for what we saw in testing today.
If the editor is not embedded, then window.parent points to the window itself. This meant we were posting the ready message on the window which caused us to fire another ready message and so on and so forth.
=> Fix post message loop

teachertool/src/components/HeaderBar.tsx
Potential branding concerns about having user content beside logo, and we have a bug on it. Just removing it for now.
Fixes https://github.com/microsoft/pxt-microbit/issues/5634.
=> Teacher Tool: Remove rubric name from header bar

docs/writing-docs/tutorials.md, docs/writing-docs/tutorials/resources.md, docs/writing-docs/tutorials/troubleshooting.md
Here's is a start on a troubleshooting page for tutorial writing. Suggest other tips to include.
Closes https://github.com/microsoft/pxt-arcade/issues/6408
=> Make a troubelshooting page for tutorial authoring

docfiles/pxtweb/cookieCompliance.ts
Adds a query parameter that lets you add a custom "partner" property to all of the telemetry items that are logged to app insights. The purpose of this feature is to let us differentiate between traffic generated by partners that link to or embed us; think of it as a manual referrer property that can be embedded in a URL. This parameter is added to all tick events.
url should look like this:
```
arcade.makecode.com/?partner=partnerName
```
Right now I am not removing the query parameter from the URL. I can do that, though, if we want.
Here is a test upload:
https://arcade.makecode.com/app/088c007a20a09fcee83221eeda1df6c9dd2a1f5b-590b47925d
=> Add partner telemetry flag

docfiles/pxtweb/cookieCompliance.ts
=> [Stable9.0] Cherry pick "Add partner telemetry flag" (#10005)

webapp/src/monacoFlyout.tsx
This is not fixing the accessibility issues that this button has, just the functionality.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2524
Also changes it so that the docs open in the sidedocs and not a new tab.
=> Fix the help link button in the monaco flyout 

pxtcompiler/emitter/decompiler.ts, webapp/src/monaco.tsx
People run into this all the time on the forum, most recently here:
https://forum.makecode.com/t/my-code-seems-to-big-to-be-decompile-in-block/28637/4
If you have a very large blocks project, you can get stuck if you switch to text because we have a limit in place for the maximum size of a project we decompile. This limit was added many years ago in response to an issue where someone tried to decompile a gigantic script (they had copy+pasted code over and over again) and it basically hung the browser when Blockly tried to load the gigantic workspace file we generated.
I think this made sense at the time, but nowadays Blockly perf has improved and I don't think we need the restriction anymore. I was able to decompile a 9000 block program locally just now (on my admittedly nice laptop) and …
=> Remove the decompiler block limit

common-docs/teachertool/catalog-shared.json, common-docs/teachertool/test/catalog-shared.json, react-common/components/controls/Accordion/Accordion.tsx, react-common/components/controls/Accordion/context.tsx, teachertool/src/components/CatalogOverlay.tsx, teachertool/src/components/styling/CatalogOverlay.module.scss, teachertool/src/components/styling/ReadonlyCriteriaDisplay.module.scss, teachertool/src/constants.ts, teachertool/src/services/storageService.ts, teachertool/src/transforms/loadCatalogAsync.ts, teachertool/src/types/criteria.ts, teachertool/src/types/errorCode.ts
This change adds tags to criteria in the catalog. The schema is setup to support criteria having multiple tags, but for now we only adjust our display based on the first tag. This may change if we add more criteria and start using more granular tags, but it's not necessary given the current catalog.
If a criterion doesn't have any tags, it gets assigned an "Other" tag. Currently, all visible catalog criteria have tags, so the other tag is never shown.
Initially, the first tag in the catalog is expanded, but the tool remembers which tags the user expands/collapses and preserves those for the next time the catalog is opened.
I made a few adjustments to the accordion display to support this change:
1. A flag to allow multiple items to be expanded
2. The ability to specify an initial "open" …
=> Add Tags to Catalog Criteria

react-common/components/controls/FocusTrap.tsx, react-common/components/util.tsx, webapp/src/sui.tsx
If a user were to close a modal with keyboard navigation, their focus would be put on the root rather than the most recent element they were focused on, which is a poor user experience. This PR fixes that and, upon closing a modal, will put focus on the DOM element that had focus before the modal was opened.
I want to give a quick thanks to @thsparks for this idea! Going with this approach greatly limited the amount of work that was needed for this fix.
EDIT: I wanted to add a quick note that the "Experiments" full-screen modal isn't performing correctly.. I want to look into this in a follow-up since the other full-screen modals are working as expected.
Follow-up: The "experiments" modal does not restore focus to the "settings" menuitem as expected because the last item that was focused …
=> Accessibility compliance: fixed focus for closed modals

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6386
When you try to carry code between skillmap steps, we refuse to import the old code if the destination tutorial doesn't have a template code block. This behavior was confusing to content authors, so adding an explicit warning to the console to hopefully make everything a little more discoverable. Check out the forum thread in the linked issue for more info.
=> Add warning when trying to carry over code without a template code block

skillmap/src/arcade.css, theme/asset-editor.less, theme/highcontrast.less, theme/home.less, webapp/src/codecard.tsx
Related to the changes with this PR: https://github.com/microsoft/pxt-arcade/pull/6425
There are some parts of the colors that needed to be changed in pxt rather than just arcade. The asset editor and skillmap styling is defined in pxt, so I needed to change colors here for those things.
=> Accessibility compliance: arcade color changes

pxtrunner/renderer.ts, theme/docs.less, theme/toolbox.less, theme/tutorial.less, webapp/src/marked.tsx, webapp/src/toolbox.tsx
Because not all of our block colors are accessible, we've come up with an alternative solution for displaying inline blocks. With this update, we are using underlines and namespace icons to depict the blocks. For block highlights in tutorials and docs that are not clickable, we just use an underline. 
Fixes https://github.com/microsoft/pxt-arcade/issues/4870
**IMPORTANT** 
This will also affect micro:bit, so if, after testing, users respond positively to this, we might need to go through more steps to get approval from the micro:bit team.
Upload targets:
micro:bit ~~https://makecode.microbit.org/app/5ad32a6d20c70ec72517ad979b75b21a90250a27-45f381e4aa#~~
https://makecode.microbit.org/app/b01d093aa836e1a318f38be16d589f5d608836f9-3fe55a0f54#
arcade …
=> Accessibility compliance: inline blocks styling updates

pxtblocks/plugins/logic/ifElse.ts
We shouldn't have a completely empty spot in a block, as does else if in the conditional in live. I added a shadow to the else if now that defaults to false since the `if` shadow defaults to true.
**Live**
**The Fix**
Fixes https://github.com/microsoft/pxt-microbit/issues/5387
=> Bug fix: expanded else if now has shadow block with false as default

cli/nodeutil.ts
Fixed issue with spawning `npm.cmd` during `pxt bump` on Windows due to NodeJS security update.
Starting from NodeJS v18.20.2, a security update changed the default behavior of `spawn`, causing it to fail on Windows when spawning executables ending in ".bat" or ".cmd" unless the `shell: true` option is specified.
NodeJS security release notes:
https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2
and
https://github.com/nodejs/node/issues/52681
Note: This fix is scoped to the pxt cli. There may be other instances in the codebase that to be updated.
=> cli: default to "shell: true" when spawning child process on win32

pxtlib/github.ts
Fixes: https://github.com/microsoft/pxt-microbit/issues/5389
**The Root Cause**
TL;DR: We needed to follow the same steps for decoding content that we do for encoding content.
As the issue notes, the problem was with how we compare the SHAs generated from parsing the text from the files in GitHub repositories. When a user creates a new repo from one of our targets, we convert the text to UTF-8 and then use `btoa` to base64 encode the content: https://github.com/microsoft/pxt/blob/master/pxtlib/github.ts#L412. If a user then deletes that repo and imports it back into the target, we were only using `atob` to decode the contents, meaning that there would be inconsistencies in the text that upon importing if there were any non-ASCII characters in any files: …
=> Bug fix: GitHub import with different languages in private repos

webapp/src/monaco.tsx
This was hit by a forum user here:
https://forum.makecode.com/t/oops-something-went-wrong-trying-to-convert-your-code/1159/6
I'm not sure how they got their project into the state of having an empty blocks file, but whatever the case we shouldn't refuse to decompile if that happens.
The issue was that we were passing the empty string to the xml parser which caused an exception. Fix is to just check if the file is empty before parsing
=> Dont break decompilation when blocks file is empty

docs/writing-docs/user-tutorials.md
Fixes https://github.com/microsoft/pxt-microbit/issues/5385
When a user makes a tutorial, what happens with `main.ts` and `.ts` files in general is dependent on how the tutorial is consumed (via GitHub repo vs. share link). This is expected, so we need to update our documentation to better reflect what happens. Let me know if I explained something incorrectly.
@ganicke, please take a look at these changes and let me know if there is anything I can re-word or clarify. Thanks!
=> Bug fix: update user tutorials documentation

pxtblocks/toolbox.ts, webapp/src/blocks.tsx
Fixes the issue reported here: https://forum.makecode.com/t/blocks-from-extension-stacking-in-pile-when-attempting-to-view-them/29738
Blockly doesn't allow shadow blocks to have non-shadow children
=> Don't generate toolbox blocks that have shadows with nonshadow children

kiosk/src/Components/EnterHighScore.tsx, kiosk/src/Components/PlayingGame.tsx, kiosk/src/Services/SimHostService.ts, kiosk/src/State/Reducer.ts, kiosk/src/State/index.ts, kiosk/src/config.json
Because it was tricky to know what type of scoring a user-added game had, we didn't give user-added games the option for high score entries on the creation of the kiosk. When a new game was added, we would set the "highScoreMode" to "None" and never change it. There are two important pieces that needed to happen in order to accept user's games' high scores:
1. Modify the game over block's event that gets recognized by the kiosk to include the scoring type. This change is made in common packages. We utilize this "scoring type" data in kiosk to sort the high score lists properly.
2. Update the game's scores and scoring type on the kiosk if the game supplies it upon playing said game. This is to allow for user-added games to be sorted from lowest scores at the top or highest scores at the …
=> Kiosk: user-added games can now have high scores

localtypings/pxtparts.d.ts, pxtblocks/importer.ts, pxteditor/experiments.ts, pxtsim/debugger.ts, pxtsim/langsupport.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/debuggerToolbar.tsx, webapp/src/debuggerToolbox.tsx, webapp/src/debuggerVariables.tsx
This PR does four things:
1. Fixes a bug where the debugger's variables get cleared when you swap tabs while stopped on a breakpoint
2. Improves the dumpHeap function to properly handle RefMap and RefImage properties
3. Makes it so that the JavaScript debugger now includes the "hidden" fields of objects (anything that starts with a _)
4. Adds an experiment that you can use to enable the "advanced" JavaScript debugger in the blocks editor. This lets you use step in/out/over, see the call stack, and see the hidden fields mentioned above
=> Add advanced blocks debugger experiment and fix debugger issues

kiosk/src/Components/PlayingGame.tsx
This change to kiosk is to make sure that we are using the correct run url in our different environments. For example, in stable, we should be using stable in order to test the changes that we're trying to ship or change. We can make sure that's the case by using the webConfig's run url. However, when testing locally, webConfig was null. While I am already specializing local host, I also wanted to keep that case in mind for the live/built scenarios, so I'm keeping the hard-coded "PlayUrlRoot" as a fall back just in case webConfig is null.
Edit: Here's an upload target (this upload target includes some console logs for testing but those console logs are now removed): https://arcade.makecode.com/app/b864d38cd277079aa0d82d37340a2a5c08132a96-51ba117ade--kiosk. You can see in those logs and …
=> Kiosk: now using the config run url if it exists

cli/buildengine.ts, cli/cli.ts, cli/commandparser.ts
This adds a new secret flag for compiling targets locally using the compile service docker images. The flag is currently hidden because right now this requires you to have pxt-deployment-config checked out locally; I might in the future duplicate the relevant parts of that repo in this one so that we don't have that restriction.
To test docker images locally:
* Build the docker file locally
* Open the pxtarget.json of a target that uses the relevant image (e.g. pxt-microbit for yotta:main and yotta:main-gcc5)
* If necessary, fix the tag in pxtarget.json to match your locally compiled docker image (e.g. in pxt-microbit, you want to change [pext/yotta:gcc5](https://github.com/microsoft/pxt-microbit/blob/master/pxtarget.json#L178) to pext/yotta:main-gcc5)
* Set the GH_ACCESS_TOKEN …
=> Support compiling locally with the new compile service images

pxtsim/runtime.ts, pxtsim/simlib.ts
This adds simulator support for the various CODAL message bus listener modes. These modes are:
* **MESSAGE_BUS_LISTENER_QUEUE_IF_BUSY** - the default mode that queues events if an event handler is busy. this has been the only supported mode in our simulator until now
* **MESSAGE_BUS_LISTENER_DROP_IF_BUSY** - events are dropped if fired while the event handler is already executing
* **MESSAGE_BUS_LISTENER_REENTRANT** - events are always fired immediately, even if the event handler is already executing
* **MESSAGE_BUS_LISTENER_IMMEDIATE** - this is used by the scheduler and throws an error if used elsewhere
this is part of the fix for https://github.com/microsoft/pxt-microbit/issues/5709, i'll have two more prs (one in pxt-common-packages and one in pxt-microbit)
=> Add support for different codal message bus listener flags

common-docs/browsers/technical.md
Update the supported version number for **Mobile Safari** from **9** to **13**.
Closes https://github.com/microsoft/pxt-microbit/issues/5596
=> Update min supported version for Mobile Safari

cli/buildengine.ts, cli/cli.ts, localtypings/pxtpackage.d.ts
We have [this property](https://github.com/microsoft/pxt-microbit/blob/eb1498eb70c937b8c132fb32893bf49374e6188c/libs/core/pxt.json#L78) set in the pxt-microbit/libs/core pxt.json but AFAIK we never actually consumed it in the pxt cli. Well, I was rebuilding the dal.d.ts for pxt-microbit and it was broken so I added support to fix it.
This just lets us specify which build engine to use when parsing C++ files to regenerate dal.d.ts
=> support compileServiceVariants in daldts command

cli/buildengine.ts, cli/cli.ts, cli/prepYotta.ts
One annoying thing about using our CLI to build locally w/ docker images is that yotta is constantly getting throttled by GitHub. We even have a GITHUB_ACCESS_TOKEN environment variable that we advertise as something you can configure, but it only gets used by PXT and not yotta which is a bummer.
Well, not anymore! This PR passes that GITHUB_ACCESS_TOKEN variable to the docker container and runs a script to setup the local `~/.yotta/config.json` and `~/.netrc` files to prevent throttling. This token doesn't actually need to have any permissions at all, GitHub just wants to use it for authentication.
Also, this PR fixes the `--local` flag which I had accidentally disabled in my last pr.
Completely unrelated to this, I also converted a function in `cli.ts` to use async await because it was …
=> Use github access token when running docker locally

kiosk/src/Transforms/exitToEnterHighScore.ts, kiosk/src/Transforms/gameOver.ts
A quick fix for a bug that evaded me until today for user high scores. Whether we would exit to entering a high score or just exit to game over had a condition that was reliant on the high score mode being high to low. If all the possible high scores slots were filled for a low to high score game, and you got a lower score than the last value, the game would exit to game over instead of enter a high score. 
I've fixed this now with having exitToHighScore use the high score mode to determine if the score has to be lower or higher than the last recorded score.
=> Kiosk: make sure exit condition for low score as best score is correctly handled

pxtblocks/plugins/renderer/constants.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5690
Fixes https://github.com/microsoft/pxt-microbit/issues/5663
By default, inputs in blocks using the zelos renderer just pull their shape from the parent block; I'm not sure why anyone would want it to work that way, but go figure.
Our old renderer didn't do that, so this PR restores our old behavior of always respecting the types for inputs instead of copying the parent.
=> Override default zelos behavior for input shapes

webapp/src/app.tsx
should fix https://github.com/microsoft/pxt-microbit/issues/5758
The `.then(reloadEditor, reloadEditor)` handles figuring out what the hash should be (https://github.com/microsoft/pxt/blob/dev/jwunderl/fix-reset/webapp/src/app.tsx#L2771), so this line is unnecessary / seems to be cause of the race condition. If anyone happens to recall changes in the hash change / loading path would be interesting to see if anything actually did change to cause this, I didn't dig that deep but nothing stood out immediately. 
mildly interesting note, the only way I was able to reproduce was setting breakpoint here 
and stepping into the two lines -- putting the breakpoint any further into function or stepping over has not reproduced on my machine. it's slightly rare for me to see it occur even when doing …
=> do not set hash before reset, as reloadEditor already does that.

pxtblocks/fields/field_gridpicker.ts, theme/fieldeditors.less
Part of the fix for https://github.com/microsoft/pxt-microbit/issues/5730
In live, that width parameter was just being ignored by the browser. I have no idea how that works (it was being set on the element, just had no effect), but for the pins dropdown we want it to just expand to wrap the whole list anyhow.
Also fixing the font/size of the menu items.
=> Add option to have an unset gridpicker dropdown width

pxtblocks/contextMenu/workspaceItems.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5774
This was throwing an exception when it attempted to delete a block that had already been deleted. For example, if the block was within an event and the event had already been disposed.
Also fixed the event grouping while I was at it.
=> Fix the "Delete all" blocks context menu option

webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/blocksSnippets.ts, webapp/src/srceditor.tsx, webapp/src/toolbox.tsx, webapp/src/toolboxeditor.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5541
Tweaks the keyboard navigation of the toolbox:
* Selecting the extensions category no longer automatically opens the extension dialog
* When exiting the extension dialog, the cursor now refocuses on the extensions category of the toolbox
The keyboard navigation is still quite buggy for the toolbox. I'll try and file some issues about all of the specific places it's broken.
=> Fix the extensions dialog when keyboard navigation is enabled

pxtblocks/plugins/functions/commonFunctionMixin.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5784
Basically the same problem as https://github.com/microsoft/pxt/pull/10071
I think this must be a new restriction that came in from the most recent Blockly update.
=> Don't dispose already disposed block when creating function declaration

common-docs/teachertool/test/catalog-shared.json, teachertool/src/components/CriteriaFeedback.tsx, teachertool/src/components/CriteriaResultEntry.tsx, teachertool/src/components/styling/CriteriaFeedback.module.scss, teachertool/src/components/styling/EvalResultDisplay.module.scss, teachertool/src/constants.ts, teachertool/src/index.tsx, teachertool/src/state/appStateContext.tsx, teachertool/src/types/criteria.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5742
This change adds an optional flag on catalog criteria which indicates that we should request feedback from the user on the tool's response. It's currently only set to true on the copilot criteria. When feedback is provided, it simply sends a tick event (collecting actual prompt and response data will require a more thorough privacy review). 
There's one slightly odd note about this change: it felt weird to lock a user into their first feedback selection they make, so I've allowed the response to be changed or cleared, but we can't "take back" a tick event. I considered adding a delay before sending the event, but that seemed flaky, like there could always be scenarios where the delay wasn't long enough or the user closed the page …
=> Teacher Tool: Add Optional Feedback on Criteria

pxtblocks/plugins/renderer/css.ts, pxtblocks/plugins/renderer/index.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5789
This is something we did by changing Blockly's PNG spritesheet in our fork a while back: https://github.com/microsoft/pxt-blockly/pull/118
I don't want to override that PNG, so instead I'm using some css filters to make it white:
=> Make dropdown checkbox white

common-docs/reference/arrays/remove-at-statement.md, common-docs/reference/arrays/remove-at.md, libs/pxt-common/pxt-core.d.ts
Make another `arrays.removeAt()` reference page for the "statement only" version of the function: `arrays._removeAtStatement()`.
Closes https://github.com/microsoft/pxt-microbit/issues/5802
=> Add another 'removeAt' reference page

pxtblocks/plugins/duplicateOnDrag/dragStrategy.ts, pxtblocks/plugins/duplicateOnDrag/duplicateOnDrag.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5785
Fixing the allowlisted duplicate on drag blocks not allowing anything else to connect to their inputs!
=> don't include duplicate on drag shadows in connection checker

pxtblocks/plugins/renderer/pathObject.ts, pxtlib/color.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4962
Automatically tweaks the block border color when the parent and child are the same color.
The results do indeed have better contrast, but do look a bit worse imo.
@Jaqster @microbit-carlos please try out this upload target before I merge:
https://makecode.microbit.org/app/cdb16cf340702c5347c39a1b207988ec2a9bad1c-621f187ad4#editor
=> Lighten or darken border colors for nested same-color blocks

webapp/src/app.tsx, webapp/src/monaco.tsx
fix https://github.com/microsoft/pxt-microbit/issues/5568
split into two commits, first fixes the issue, second is some clean up while in the area. The resize at the end of `completeTutorialAsync` is needed to change it during the session a user completes the activity, the force resize is needed on future sessions (e.g. refreshing the page). Blocks would have had the same issue, but got by as it already had the same applied https://github.com/microsoft/pxt/blob/dev/jwunderl/fix-tutorial-check/webapp/src/blocks.tsx#L157
=> Show mini sim in tablet sized monaco projects that originated from tutorials

package.json, pxtblocks/index.ts, pxtblocks/loader.ts, pxtblocks/workspaceSearch.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5629
This restores all of our extensions to Blockly's workspace search plugin; I had disabled them temporarily when we upgraded Blockly. The changes include:
* Pressing Shift+Enter navigates backwards through the list of search matches (default plugin can only move forwards)
* The content of the searchbox is selected when the search box is opened, which matches the behavior of most ctrl+f search boxes
* Custom rendering (selected blocks are outlined, all non-matching blocks in the workspace are faded out)
I had to do some hacks to customize the keydown behavior and get a reference to the text input element. I'll probably try to contribute the first two things back to Blockly since that's how all search boxes work.
=> Restore workspace search extensions

localtypings/pxteditor.d.ts, pxteditor/editorcontroller.ts
See my comment in https://github.com/microsoft/pxt/pull/10082#discussion_r1712312836 for an explanation.
Just fixing the typing of this switch statement's argument to enforce that all messages exist within the typing for `EditorMessageRequest`. Also adding the missing `switchpython` message
=> Fix typing for editor message requests

pxtblocks/fields/field_dropdown.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5486
See the comment in the PR for a more detailed explanation on why this matters.
=> Always have border for fields in blocks with multiple fields

docs/static/playground/samples/field-editors/dropdowns/sample.js, pxtblocks/fields/field_numberdropdown.ts, pxtblocks/fields/field_textdropdown.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5695
The textdropdown field has been broken for a long time. This PR fixes that field and also unites its authoring with the numberdropdown field. For context, the numberdropdown field is the field used by our `pause` block which shows a dropdown of options while also allowing you to type in any number. The textdropdown works the same way but uses strings instead of numbers.
Previously the textdropdown used the `values` field and comma separated values:
```ts
//% word.fieldOptions.values="hi,goodbye"
```
while the numberdropdown used the `data` field and JSON array syntax:
```ts
//% num.fieldOptions.data='[["1 mm", 1], ["1 cm", 10], ["1 m", 1000]]'
```
Now both of them support both `fieldOptions.data` and `fieldOptions.values`
I've …
=> Fix textdropdown and unite its syntax with numberdropdown

webapp/src/app.tsx
When I was stepping through here in a program that was too big for v2 microbit, it started getting stuck in a retry loop; the putting a breakpoint after `compiler.compileAsync` would reset `pxt.appTarget.multiVariants` to the original value with 2 variants while the `if (res?.recompile) {` block was going / before it got to the finally. Just storing prior to attempting compile so `pxt.commands.showProgramTooLargeErrorAsync` gets the correct value for now, worth looking into a bit more later.
(big program https://makecode.microbit.org/_6oaTMe08Yc7b)
=> store variants attempted before compiling

pxteditor/history.ts, tests/pxt-editor-test/editorrunner.ts, webapp/src/dialogs.tsx, webapp/src/timeMachine.tsx, webapp/src/workspace.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5674
Fixes https://github.com/microsoft/pxt-microbit/issues/5788
Fixes the time machine restore function so that the timestamp that the user chooses in the timeline matches the code at that point in time. There was both an off-by-one error in the getTextAtTimeAsync function and we weren't saving the correct time when creating new diffs in the history file.
Also added a test to keep it from regressing.
=> Fix time machine restore

pxtblocks/builtins/functions.ts, pxtblocks/plugins/duplicateOnDrag/variablesGetReporter.ts, pxtblocks/plugins/functions/blocks/argumentReporterBlocks.ts, pxtblocks/plugins/functions/utils.ts, pxtblocks/plugins/renderer/pathObject.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5813
adding a check to the mutateCallersAndDefinition function to ensure that an argument reporter actually belongs to the mutating function before deleting it.
also fixed a random typo I noticed.
=> Don't delete unrelated arguments when mutating and fix typo

pxtlib/webusb.ts
At least make an attempt to call disconnect code before forgetting usb device, to give firmware a notice it's being disconnected. Does not currently consistently make it so you can forget then repair, but mild improvement / makes best effort.
Close https://github.com/microsoft/pxt-microbit/issues/5672, the issue does show them skipping over the modal that gives instructions on reconnecting / indication of the requirement to fully disconnect and reconnect (depending on firmware version). Perhaps this will get improved with other micro:bit webusb fixes, but doesn't seem like a thing to prioritize when it's already an edge case button / it gives proper instructions to fix it.
=> webusb attempt to disconnect on .forget

pxtblocks/layout.ts, pxtlib/browserutils.ts, webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5795
when we load a blocks file we check to see if any of the blocks/comments are in the default position (x=10 and y=10) and format the whole workspace if they are. seems like blockly now [automatically bumps blocks neighbors](https://github.com/google/blockly/blob/ec8f9c8589fd0ea849eba4ae80f59cb878a0f24a/core/render_management.ts#L146) when doing renders, so even if there is no location information the blocks are bumped away from that default position in the first render which thwarts our check.
this PR changes that check so that it looks at the XML we loaded instead which is not subject to any phantom bumping
=> fix layout logic for decompiled code

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, webapp/src/app.tsx
adds a python template (and typescript template) code block for tutorials
this sets the language for the tutorial to python and allows you to author the template in python rather than typescript
=> Adding tutorial option for a python template

localtypings/pxteditor.d.ts, pxteditor/editorcontroller.ts, pxteditor/index.ts, pxteditor/projectImport.ts, pxtservices/editorDriver.ts, webapp/public/controller.html, webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5748
Adds a command for importing projects for the embedded editor scenario. It works pretty similarly to the skillmap codepath, but it doesn't require the projects to be stored on the same domain.
The flow goes like this:
1. Outside frame sends the `importexternalproject` command to the iframe with a project
2. The inner frame saves the project to a temporary DB (not the workspace DB)
3. The inner frame responds with a URL that the outer frame can open in a new tab to import the project
4. When the URL gets opened, the project is removed from the temporary DB and stored in whatever workspace is active (e.g. the indexedDB, the cloud, etc.)
The temporary db gets cleared whenever a new project is written or removed, so this can't be …
=> add importexternalproject editor command

localtypings/navigationController.d.ts, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5540
This fixes two issues:
* the blockly flyout would sometimes close itself when you clicked on the Make a Variable or Make a Function buttons
* the 'out' shortcut in the blockly keyboard navigation wasn't working when the flyout was open
The first issue was being caused by an event firing when the current block is unselected.
The second issue was because the Blockly injection div wasn't being focused.
=> Fix a couple blockly flyout issues

pxtsim/embed.ts, pxtsim/runtime.ts
When developing the pxt-bedrock target, I was seeing major performance problems when our code ran within Minecraft's JavaScript runtime. The culprit turned out to be this fixed value of 5ms for the yield delay. Lowering the value to zero completely resolved the issue. Would we see similar improvement in pxt-minecraft? The runtime environments are very different. Experimentation will tell.
Making this value configurable so we can adjust it in the pxt-minecraft target.
=> Make runtime yield delay configurable

teachertool/src/components/styling/EvalResultDisplay.module.scss
It still has problems with long titles without any spaces, but that isn't a common scenario, so I think this is an acceptable fix for now.
Fixes https://github.com/microsoft/pxt-microbit/issues/5638
=> eval tool: better print preview handling of long title

teachertool/src/components/HeaderBar.tsx, teachertool/src/components/styling/HeaderBar.module.scss, teachertool/src/constants.ts, teachertool/src/global.scss
This change adds a beta tag to the code evaluation tool. To give the tag a place to anchor, I included the app title in the header bar, which also aligns with previous feedback. However, since the title is wide and doesn't fit well on small screens, I defined standard media breakpoints to allow the header layout to be responsive. If the teacher tool already has a set of generic breakpoints, I'll use those; otherwise, these breakpoints can be adopted across the app when we address responsiveness.
The design of these breakpoints is somewhat unique in that they're composable.
Test target: https://makecode.microbit.org/app/cf32d5a03e863c227a7d4bee10b3b9193dc75b08-0e9e16aba4--eval
Header layouts at different widths:
Fixes https://github.com/microsoft/pxt-microbit/issues/5743
=> code eval: add beta tag

cli/pyconv.ts, pxtcompiler/emitter/service.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5703
This removes the mapping between JavaScript's `Array.indexOf` and Python's `List.index` function. Python's index function throws an exception if the value is missing instead of returning -1, so this isn't a safe conversion to make.
This means that if you are using `Array.indexOf` in Blocks or TypeScript, when you switch to Python you will now get the non-standard `.index_of`, which will maintain the same behavior at the cost of being a function that doesn't exist.
=> Don't convert indexOf to python's .index

teachertool/src/components/CriteriaEvalResultDropdown.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5625
We had originally hidden this by design, but it caused some confusion so let's just show it for now. Can adjust again later if we get feedback on it.
Print view with N/A shown:
=> Teacher Tool: Show N/A in Print View

teachertool/src/components/CriteriaResultEntry.tsx, teachertool/src/components/styling/EvalResultDisplay.module.scss, teachertool/src/constants.ts, teachertool/src/services/backendRequests.ts, teachertool/src/transforms/mergeEvalResult.ts, teachertool/src/transforms/runSingleEvaluateAsync.ts, teachertool/src/types/criteria.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5819
If a criterion fails to evaluate through a non-user error (i.e. we can't reach the AI service), we don't really provide any indication of the issue to the user, it just shows no result.
With this change, we show an error window:
Upload target (easy to get an error by using "Ask AI", since ai endpoint doesn't exist yet): https://makecode.microbit.org/app/d51851820874badb8277c7a4bf73ce82ff4bf5f9-eb19b40cfa--eval?tc=1
=> Show Error on Failed Criteria Evaluation

pxtlib/package.ts, webapp/src/app.tsx
One benefit of the new compile service is that it can now execute compile jobs in parallel. This PR takes advantage of that feature and makes it so that when hitting the compile service for micro:bit, we request the compiling of both the V1 and V2 hexes at the same time.
In other words, it should cut the CPP compile time in half (but only for micro:bit, since it's the only "fat hex" target).
I'm planning on doing the same thing with our CLI builds in the near future, which should speed up `pxt buildtarget` significantly for targets with multiple compile variants.
=> Poll for compile variant hex files in parallel

teachertool/src/components/CatalogOverlay.tsx, teachertool/src/style.overrides/Button.scss, teachertool/src/transforms/runEvaluateAsync.ts
This adds two additional points of feedback when evaluation is done. It colors the borders of the result (since we got rid of the background colors). There's also a success toast that shows if evaluation was done through user interaction (not auto-run).
Also includes small bug fix to add missing key to criteria elements in the catalog.
Upload target: https://makecode.microbit.org/app/ee74f3fe2b38baaaad633e6599a962c6642ee0a9-a4d5ebb2c1--eval
=> Teacher Tool: More Visual Feedback on Evaluation

pxtcompiler/emitter/service.ts, pxtcompiler/emitter/snippets.ts, webapp/src/monaco.tsx, webapp/src/monacoFlyout.tsx, webapp/src/toolbox.tsx
Fixes: https://github.com/microsoft/pxt-microbit/issues/5349
As described in the bug, the problem we were having is that the music play blocks, with the new Playable infrastructure that we have in place, have a `toolboxParent`. This parent is the `play(toPlay, playbackMode)` block. We handle this `toolboxParent` in blocks, but it was not getting handled in JS/Python snippets, so when the play blocks would get dragged into the Monaco editor from the toolbox, the inner block would be generated, but not the outer parent block.
Big thank you to @riknoll for all your help getting situated in the right files and implementation guidance.
This PR does the following:
1. Fixes the snippet drag out problems that are the root of the linked issue. These changes can be found in `snippet.ts` and has to …
=> Blocks with toolbox parents will have correct snippets and toolbox previews in JS/PY

pxtblocks/compiler/compiler.ts, pxtblocks/compiler/typeChecker.ts, webapp/src/blocks.tsx
Blockly lets you set multiple warnings on a block at once by giving them different ids. This PR sets an id for all of the core pxt warning messages so that field editors can contribute additional warnings without them being clobbered the next time we run a type check.
=> Use an id when setting blockly warnings

localtypings/pxteditor.d.ts, webapp/src/appcache.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5824
turns out we already have an [appTheme flag](https://github.com/microsoft/pxt/blob/39fe06ad93b7e6b639f7b228db967a74f0ac89ea/localtypings/pxtarget.d.ts#L414) that prevents us from reloading when we get a serviceworker update. this pr adds a new editor event to compliment that flag which is fired when a new serviceworker is registered so that the page hosting the editor in an iframe can handle the refresh themselves instead of getting surprised.
@thsparks for the code eval tool, I recommend that you:
* create a query variant in `pxtarget.json` that sets the `noReloadOnUpdate` flag
* use that query variant in your embedded url
* when you receive the new `serviceworkerregistered` message, either reload the frame in the background or …
=> add editor event when a new serviceworker is registered

webapp/src/dialogs.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5853
fixes three tiny bugs with the time machine dialog:
* when trying to save a copy from "Now", the project name would contain "invalid date" instead of a timestamp
* projects saved using the "save a copy" button weren't keeping around the project history from before the selected time
* opening the time machine dialog for a project with no history (e.g. you clicked the button too fast) would cause an exception
=> Fix 'save a copy' time machine bugs

webapp/src/filelist.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5367
It's frustrating to not have something to work off of if it's your first time creating custom blocks. Including our "creating blocks" template should not depend on that file's name being `custom.ts`. However, for those that are making a lot of custom blocks, having a template in every new file that you make would be frustrating to deal with. Thus, we've changed it so that we are no longer special casing `custom.ts`. For the first custom file that you make, no matter the name, the template will be included in that file. Any subsequent custom files made will have the `Add your code here` comment as is the current behavior.
Upload target: https://makecode.microbit.org/app/6b84da6b59b4491ed7055b51c377ce774d5774e0-f63aae8ed5
=> Add the template code to the first custom file created, no matter the name

pxtblocks/fields/field_dropdown.ts, pxtblocks/plugins/newVariableField/fieldVariable.ts
this fixes a bug i noticed while testing today.
blockly's dropdown field treats the entire block as a click target when the block has only a single field in it. that generally works fine except when the block also has an icon on it (e.g. a warning or a comment) since it causes the field to swallow up the click events on those icons. this pr overrides the event binding to fix that.
i should probably open an issue against blockly for this
also annoying is the fact that i have to duplicate this code in two places. i briefly tried to get this working with mixin classes, but typescript doesn't like mixin classes that have private or protected properties.
=> don't prevent block icons from being clicked on full block fields

teachertool/src/components/CriteriaInstanceDisplay.tsx, teachertool/src/components/CriteriaResultEntry.tsx, teachertool/src/components/styling/CriteriaInstanceDisplay.module.scss, teachertool/src/components/styling/EvalResultDisplay.module.scss, teachertool/src/global.scss
**Improvements to print layout**
- Animation-based resize of notes textarea wasn't reflowing properly in print preview. Fixed by showing a div in this view instead of the textarea.
- Prevent insertion of page breaks before notes if feedback runs over a page, as this was causing insertion of blank pages.
**Other tweaks**
- Format criteria description in italics in print preview. Without this distinction it looked like it was part of the feedback notes.
- Don't hide label of the Evaluate button on narrow panels. The removal of autorun allowed for this button to remain prominent.
- prettier
Fixes https://github.com/microsoft/pxt-microbit/issues/5611
=> print layout improvements

webapp/src/simtoolbar.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5619
originally we talked about keeping it, but as noted in the linked issue there is no toolbox in readonly mode so there's nowhere for the debug controls to go.
=> remove debug button in read only mode

theme/blockly-core.less
this fixes the glitchiness seen in this gif: https://github.com/microsoft/pxt-microbit/issues/5726#issuecomment-2284630270
it does not, however, fix the bug that the linked issue mentions in the top comment. that seems to be a blockly bug and i'll open it against them
=> fix safari comment rendering glitch

teachertool/src/components/CriteriaFeedback.tsx, teachertool/src/components/CriteriaResultEntry.tsx, teachertool/src/components/styling/CriteriaFeedback.module.scss, teachertool/src/state/actions.ts, teachertool/src/state/reducer.ts, teachertool/src/transforms/mergeEvalResult.ts, teachertool/src/transforms/runSingleEvaluateAsync.ts, teachertool/src/transforms/setUserFeedback.ts, teachertool/src/types/criteria.ts, teachertool/src/types/index.ts
Store user feedback in state so that it isn't cleared when the feedback control unmounts for any reason.
Feedback state will be programmatically cleared when:
* The criteria evaluation returns a different value for `notes`
* The criteria fails to evaluate.
When feedback is given, the text label now changes to "Thanks for your feedback!". Because of this, I removed the toast that appears with the same message.
Fixes https://github.com/microsoft/pxt-microbit/issues/5815
Fixes https://github.com/microsoft/pxt-microbit/issues/5831
=> teacher tool: persist user feedback

pxtblocks/importer.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5876
the decompiler doesn't set the initial comment width/height so we have to patch it when loading the xml into the workspace
=> fix the size of decompiled comments

localtypings/pxteditor.d.ts, pxtservices/editorDriver.ts, teachertool/src/components/MakecodeFrame.tsx, teachertool/src/services/makecodeEditorService.ts, webapp/src/appcache.ts
With https://github.com/microsoft/pxt-microbit/pull/5875, we disabled the automatic webapp reload that occurs when a new service worker is registered. We did that because the unexpected reload was causing https://github.com/microsoft/pxt-microbit/issues/5824 and https://github.com/microsoft/pxt-microbit/issues/5822.
Now, however, we have to handle that refresh ourselves. In this change, we listen for the event added in https://github.com/microsoft/pxt/pull/10120 and refresh the iframe (via changing the src) when we get it.
A few details:
1. I had to change the event type for the serviceworkerregistered event. Since this comes from the iframe unprompted, we want "pxthost" rather than "pxteditor" (which is more for responding to requests)
2. I moved the iframe url into the component's …
=> Teacher Tool: Handle Reload on ServiceWorkerRegistered Events

pxtblocks/fields/field_ledmatrix.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5860
i think the behavior of the .select() function must have changed with the blockly upgrade. now it just adds the selection highlight but does not set the global selection
=> fix selection behavior of the ledmatrix field

teachertool/src/App.tsx, webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5877
when setting the warning message on a block it changes the size of the block (the icon adds width).
this pr makes sure to resize the highlight border post render once the icon is visible.
=> fix warning highlight resizing

pxtlib/packetio.ts, pxtlib/webusb.ts
Noticed something interesting in the video of the hang in https://github.com/microsoft/pxt-microbit/issues/5530#issuecomment-2318234233, which was that when the download started to halt it came after these two logs: 
which would indicate it was stalling as it never gave out the following logs https://github.com/microsoft/pxt-microbit/blob/master/editor/flash.ts#L460 after '; retrying' --would expect either the ';retry success' or the log to error. Looking at this code path, it looks like that would be from falling into final & recursing indefinitely. Adding a timeout to pass in from flash side to make this not go until device gets unplugged, at minimum.
(still not able to reproduce the error, but something we'll want either way)
=> add optional timeout to recvPacketAsync

localtypings/evaluation.d.ts, localtypings/validatorPlan.d.ts, pxteditor/code-validation/runValidatorPlan.ts, pxteditor/editorcontroller.ts, teachertool/src/constants.ts, teachertool/src/services/backendRequests.ts, teachertool/src/transforms/runSingleEvaluateAsync.ts, teachertool/src/validatorPlanOverrides/runAiQuestionValidationPlanAsync.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5873
While fixing this, I decided to avoid relying on Error throwing/catching to communicate these kinds of errors. Instead, I added a field inside our evaluation result.  This will hopefully help make it clear that the error messages are user-visible and should be understandable text.
I considered just using a blanket error message for all criteria evaluation failures which would essentially just say "Evaluation failed" with no details at all, but as a user, I'd find that frustrating, especially when it's not clear if it's a "me" issue or a product issue. This change is trying to strike a middle-ground, where different criteria can surface different errors if they want to, but we will never end up displaying random, unfiltered …
=> Teacher Tool: User-Friendly Error Messages

teachertool/src/components/CriteriaResultEntry.tsx, teachertool/src/constants.ts, teachertool/src/transforms/runEvaluateAsync.ts, teachertool/src/transforms/runSingleEvaluateAsync.ts
The user interaction flag is what determines if we should bypass the "run if unchanged / modified" check. We just need to pass it through.
I've pushed the toast display code back up to the callers of runSingleEvaluateAsync since we want different behavior in a run-all scenario vs a single run scenario that can't be totally decided via user interaction. 
Fixes https://github.com/microsoft/pxt-microbit/issues/5829
=> Teacher Tool: Ensure Run-All Re-Runs Everything

common-docs/teachertool/test/catalog-shared.json
Bringing this down to a more reasonable number. 10 feels excessive, and since these calls can be expensive, best to keep it more limited.
=> Limit Max AI question count to 5 instead of 10

webapp/src/cloudsync.ts
Shouldn't matter basically at all, but noticed it this gets called an annoying amount while trying to nail down a webusb issue with the devtools `pause on caught exceptions` flag on. The api just ends up pointing `github:user` data at https://github.com/microsoft/pxt/blob/dev/jwunderl/add-cache-github-data/webapp/src/cloudsync.ts#L115, and constantly gives an exception parsing undefined when not signed into github (or just reparses the info, if you are signed in). This happens around half a dozen times on any interaction with the workspace (e.g. dragging a block).
As mentioned, can't imagine this specifically impacting performance, but just a tiny thing i saw / maybe worth peeking if there's any 'quick fix' we can make to avoid unnecessary cascading renders. Really the cache here could …
=> add cache to github:user data api

pxtlib/webusb.ts, webapp/src/webusb.tsx
Was walking through this code line by line on friday to try and figure out what was up with chromebook webusb, so async/await-ified the remaining bits along the way. Also added some type info to navigator to remove some unnecessary casting, & made the 'connection failure' dialog a bit more explicit in cases where user gave a device but it didn't work (as that most often comes down to them having it already open in another browser / application, e.g. incognito + normal browser at once).
=> async/awaitify remaining logic in webusb.ts, tweak error message on locked device

teachertool/src/components/EvalResultDisplay.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5900
Also curious if we should add a bit more detail in the tooltips for the action buttons.. It seems a bit funky to me that exporting gives me a JSON representation of the checklist and printing gives me exactly what's on the page. As a user, I think I would expect the export and print to give me the same thing or, that exporting would give me the option for file types. 
I'm totally fine with leaving as is, but wanted to have a discussion about it. If we did want to add a bit more explanation, I was thinking of, for export tooltip: "Export checklist JSON for reimport" and then keep print the same. Another option could be rename "Export" to "Save" so that it's a bit clearer that we're giving the export functionality so a user doesn't …
=> Code eval tool: make exporting available without a project

common-docs/reference/text/char-at.md, common-docs/reference/text/char-code-at.md
Put in a reference page the new text api - `charCodeAt()`. The help path is already set as `./text/char-code-at`.
This is the third part of the fix for https://github.com/microsoft/pxt-microbit/issues/5859. See https://github.com/microsoft/pxt-microbit/issues/5859#issuecomment-2309637961.
RE: #10093 
Closes https://github.com/microsoft/pxt-microbit/issues/5859, again.
=> Add a reference page for 'char-code-at'

teachertool/src/services/backendRequests.ts
Now that I can actually see real successful responses from the staging server, it seems this response parsing was incorrect (likely from when we switched to using `staticApiAsync` instead of sending the request directly via `fetch`). The response passed back from `staticApiAsync` has already handled the `json()` call.
=> Fix AI Response Parsing

common-docs/teachertool/catalog-shared.json
Fixes https://github.com/microsoft/pxt-microbit/issues/5901. All of our other criteria have the at least wording in the description and "title" area, so the block used criteria now matches that pattern.
=> Code eval tool: "at least" added to block used criteria

webapp/src/compiler.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5896
The issue here is that we cache Block definitions when we inject all of the blocks from our API info. This cache gets cleared [when we load a new blocks file](https://github.com/microsoft/pxt/blob/1ba230653cad6aa67f70398b4636996b8b3f075d/webapp/src/blocks.tsx#L1059), but the compiler upgrades happen before that function is called so it's using the cached blocks from the previous injection.
I still haven't figured out when this was introduced, but it appears to be a while ago. My guess would be that this repros on arcade live as well though I haven't tried it.
=> clean block definitions before attempting to upgrade blocks

common-docs/teachertool/catalog-shared.json
Added parentheses around the s's in criteria because it would read incorrectly if there was only one block being checked.
=> Code eval tool: put s's in parentheses for criteria

pxtblocks/workspaceSearch.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5902
The workspace search plugin's buttons just use the padding from the user agent's button style. Whoever implemented this the first time around was probably testing with Chrome, which has 6px padding on its buttons by default. Firefox has 4px padding, which results in the error in the issue.
This was an issue in the plugin itself. I have also [filed it on the Blockly team](https://github.com/google/blockly-samples/issues/2458) and [opened a PR](https://github.com/google/blockly-samples/pull/2459) to fix it.
=> fix workspace search plugin CSS in Firefox

localtypings/pxtarget.d.ts, webapp/src/cmds.ts, webapp/src/webusb.tsx
re: https://github.com/microsoft/pxt-microbit/issues/5530#issuecomment-2329825860; with some fiddling you can get your micro:bit into a state where you cannot read from it, and in that scenario the device appears to just be stalled / unrecoverable without power cycling it. This detects the cases where we call into connections from the webapp side -- when refreshing the page, downloading, or just 'pairing'.
The main case this doesn't cover is when you just plug in the micro:bit without downloading; for now it'll still wobble on the status & only show error when they press download, because that path happens entirely over on the micro:bit flash.ts side & it'll take a little more work to get that to pop this dialog properly.
=> detect and warn on webusb stall

pxtblocks/contextMenu/workspaceItems.ts, pxtblocks/layout.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/5885
Well, I hate this fix. Hate it. Hate it Hate Hate it Hate it Hate it. But it works.
The only substantive thing in here is the change in workspaceItems.ts, which takes a second snapshot in Safari after the first. For some reason, this fixes the mysterious issue where icons sometimes don't load.
The changes in the other file are just a small optimization; we were loading the images in the cache in parallel which is actually a bad idea when 99% of the icons being loaded are just the same dropdown chevron
=> fix icons in snapshot in safari

webapp/src/timeMachine.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/5925
I assumed the date parser would take locale into account but that is apparently not the case!
=> Fix dates for various languages

pxtblocks/fields/field_utils.ts, pxtblocks/plugins/comments/blockComment.ts, pxtblocks/plugins/comments/bubble.ts, pxtblocks/plugins/comments/textinput_bubble.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5889
one of the additions we made in pxt-blockly was the ability for block comments to serialize their position to the XML when saving workspaces. unfortunately, we can't do the same thing with unforked blockly because there are no extension points in the XML serialization of comments. however, blockly _does_ have a data element on blocks that you can stick arbitrary data into and will get saved in the XML (we already use this for persisting data for some of our field editors)
this pr brings back the saving of the comment position by shoving it into the block's data element. note that this will not fix existing projects from before the blockly upgrade, but i really don't think anyone will notice.
=> store block comment position in block data

webapp/src/idbworkspace.ts, webapp/src/workspace.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5926
this fixes a bug caused by interleaving save/sync operations when duplicating a project from within the code editor.
we maintain a global array of all the available headers in the current workspace that we pull projects from. currently, that array gets updated in two places:
1.  when we do a sync operation
2. when we start to save a new project (but before the project is actually saved)
if a sync operation gets triggered after we start saving a new project but before that save has actually completed, it can accidentally overwrite the change that was made when we saved a new project.
luckily, it's an easy fix. we just need to wait to add the project to the header array until after it's actually saved.
=> fix interleaving of save/sync operations

cli/cli.ts
missing a safe navigation operator & a fallback value
=> fix staticpkg if availableLocales not defined in pxtarget

cli/cli.ts, cli/prepYotta.ts, pxtlib/package.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5915
the global state in our CLI is definitely going to be the death of me
this PR fixes the issue with local builds by de-parallelizing them using a promise queue. i also took this opportunity to remove the last reference to the old GH_ACCESS_TOKEN environment variable (missed this one i guess)
=> Don't run local CLI builds in parallel

pxtblocks/importer.ts
Fixes the issue described here: https://forum.makecode.com/t/cannot-restore-from-history/30482
Blockly doesn't allow shadow blocks to have no parent. This shouldn't actually be possible in the editor but the evidence suggests otherwise! This change will simply convert those shadow blocks to normal blocks to prevent them from interrupting project loading.
Still don't know what the actual cause of this state is. I added a tick event so that we can at least figure out what blocks are causing it.
=> patch projects with top-level shadow blocks

webapp/src/timeMachine.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5935
turns out the `getDay()` method returns the index of the day of the week not the day of the month! I guess those just happened to coincide last week while i was testing this ¯\\\_(ツ)\_/¯
the correct method to use is the confusingly named `getDate()`
i also fixed up the 'x days ago' logic so that it's a little easier to read
=> use getDate not getDay and simplify date logic

webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5942
not sure how this got disabled in the first place, but it's probably my fault
=> re-enable scroll to zoom in blocks

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, webapp/src/app.tsx
I guess I cherry picked to the wrong stable branch before, cause it certainly isn't in this one!
=> [Stable 9.3] Cherry pick adding tutorial option for a python template (#10097)

localtypings/pxtarget.d.ts, localtypings/pxtelectron.d.ts, pxtlib/cmds.ts, webapp/src/cmds.ts, webapp/src/electron.ts
start on gluing up electron file deploy / exposing to target editor.js
=> [WIP] start on electron file deploy

localtypings/pxteditor.d.ts, pxtlib/cmds.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/projects.tsx
pxt side glue
Guess one question, we don't fill in on this screen
but I could if we wanted? Don't really mind behavior as is, if they click through it generates a name, but don't get in their way if they actually plan to fill it out
=> Add generated name mirrored from vscode-edu

localtypings/pxtarget.d.ts, pxtcompiler/emitter/annotate.ts, pxtcompiler/emitter/service.ts, pxtlib/blocks.ts
Support blocks defined as static methods on classes.
This works fine in the editor, but for some reason when I attempted to add a test case to the decompiler tests I was getting errors. I'll need to do some more investigation to figure out what's different between those two scenarios; this isn't the first time that the decompiler tests have given me grief on things that worked fine. I'm guessing it's an issue with the annotate function.
=> support blocks generated from static class methods

docfiles/offline-app-head.html
so we don't have to manually create the links when testing
=> add option to pin offline-app page to a specific version

teachertool/src/App.tsx, teachertool/src/components/BlockPickerModal.tsx, teachertool/src/components/CatalogOverlay.tsx, teachertool/src/components/CriteriaEvalResultDropdown.tsx, teachertool/src/components/CriteriaInstanceDisplay.tsx, teachertool/src/components/CriteriaResultEntry.tsx, teachertool/src/components/EvalResultDisplay.tsx, teachertool/src/components/HomeScreen.tsx, teachertool/src/components/ImportChecklistModal.tsx, teachertool/src/components/ShareLinkInput.tsx, teachertool/src/constants.ts, teachertool/src/services/makecodeEditorService.ts, teachertool/src/state/helpers.ts, teachertool/src/transforms/loadBlockImagesAsync.ts, teachertool/src/transforms/loadChecklistAsync.ts, teachertool/src/transforms/mergeEvalResult.ts, teachertool/src/transforms/runEvaluateAsync.ts, teachertool/src/transforms/runSingleEvaluateAsync.ts, teachertool/src/transforms/setEvalResult.ts, teachertool/src/transforms/setEvalResultOutcome.ts, teachertool/src/transforms/setParameterValue.ts, teachertool/src/transforms/setRunOnLoad.ts, teachertool/src/types/criteria.ts, teachertool/src/types/criteriaParameters.ts, teachertool/src/types/errorCode.ts, teachertool/src/utils/index.ts
This change adds a few telemetry events and some code changes to support them:
1. Changing the eval result (including a field indicating whether or not it's manual and whether the previous result was manual, which necessitated adding resultIsManual to the result type. I think this could be helpful in the future too, if we decide not to overwrite manual results when doing bulk evaluate)
2. Changing eval notes (debounced)
3. Run single eval (including hash of the checklist which should help with understanding evals / checklist and usage of pre-made checklists)
4. Run bulk eval
5. Importing a checklist (whether there's an invalid file, a successful import, or closed without doing anything)
6. Loading in new projects
7. Block picker opened & block selected
8. Adjusted logging of opening …
=> Teacher Tool: More Telemetry

theme/toolbox.less, webapp/src/blocks.tsx, webapp/src/toolbox.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5962
our webapp doesn't use the blockly toolbox, but it does use the blockly toolbox div (we just inject our own react component). however, blockly registers an onclick handler on that div that tries to figure out which toolbox category is being clicked based on [the id of the element](https://github.com/google/blockly/blob/bc2b142f62443ce3851c000d990d5a96006b4f5d/core/toolbox/toolbox.ts#L261). our toolbox search input was the only element in that div with an id set, so it was triggering an exception whenever it was clicked. 
fixed in the simplest way possible: i removed the id
also worth noting that this exception was also occurring in chrome; ios safari seems to be the only case where this broke the toolbox for whatever reason. …
=> remove id from blockly search input

localtypings/pxteditor.d.ts, pxteditor/editorcontroller.ts, pxtservices/editorDriver.ts, teachertool/src/components/CriteriaInstanceDisplay.tsx, teachertool/src/components/styling/BlockPickerModal.module.scss, teachertool/src/components/styling/CatalogOverlay.module.scss, teachertool/src/components/styling/CriteriaInstanceDisplay.module.scss, teachertool/src/services/makecodeEditorService.ts, teachertool/src/services/storageService.ts, teachertool/src/transforms/loadReadableBlockName.ts, theme/themepacks.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/blocksSnippets.ts, webapp/src/monacoFlyout.tsx, webapp/src/monacopyhelper.ts, webapp/src/toolboxHelpers.ts
This changes the inline block display for the "Block used count times" criteria in the teacher tool. I've reused the approach taken by the monaco editor to generate the javascript toolbox entries (meaning some of that code has been refactored into a shared helper method). This approach looks at the attributes for a block (mostly the block string), then breaks it up into labels, parameters, and breaks. Those sections are returned and can be displayed however the caller sees fit.
I cache the information to minimize any loading time (fewer messages to the iframe) and to reduce the likelihood of ending up with a block where we can't get a display (i.e. a rubric with a block loaded from an extension, opened later from a project without that extension installed).
There are a few things I don't …
=> Teacher Tool: Change block display

webapp/src/greenscreen.tsx
Have to disable greenscreen on electron on mac again, as mac10.14+ requires a check electron side along lines of
https://www.electronjs.org/docs/latest/api/system-preferences 
```typescript
systemPreferences.askForMediaAccess("camera")
```
but also have to add some descriptions / etc to info plists as described by api; skipping for now.
=> disable again on mac, as new mac versions require explicit permissions

docs/github-teacher-verification.md
Add a survey reminder note and link to the Github Teacher Verification page.
How's this?:
Closes #10201
=> Add survey reminder to teacher verification page

docs/csp.md
Remove the 'Professional Development' section from the CSP page now that school terms are back.
Closes #9098
=> Remove 'Professional Development' section from CSP page

localtypings/pxteditor.d.ts, pxteditor/editorcontroller.ts, pxtservices/editorDriver.ts, teachertool/src/components/CriteriaInstanceDisplay.tsx, teachertool/src/components/styling/BlockPickerModal.module.scss, teachertool/src/components/styling/CatalogOverlay.module.scss, teachertool/src/components/styling/CriteriaInstanceDisplay.module.scss, teachertool/src/services/makecodeEditorService.ts, teachertool/src/services/storageService.ts, teachertool/src/transforms/loadReadableBlockName.ts, theme/themepacks.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/blocksSnippets.ts, webapp/src/monacoFlyout.tsx, webapp/src/toolboxHelpers.ts
=> Port to Stable - teacher tool: change block display

webapp/src/app.tsx, webapp/src/idbworkspace.ts, webapp/src/workspace.ts
as i was tracing our tutorial loading code, i went ahead and fixed a few tiny bugs and converted some functions to async/await. i know the async/await changes make it a little difficult to tell what changed, so here's a summary of the few actual behavior changes:
1. removed a redundant call to `compiler.newProjectAsync()` in `internalLoadHeaderAsync`
2. removed a redundant call to `pxt.github.cacheProjectDependenciesAsync()` in `createProjectAsync()`
3. made the github repo db keys in `idbworkspace.ts` case insensitive so that we don't miss the cache when a markdown author is inconsistent with their capitalization (this was happening in the HOC minecraft tutorials)
=> Some app.tsx cleanup

.vscode/launch.json, cli/cli.ts, cli/server.ts, localtypings/pxtarget.d.ts, pxtlib/browserutils.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, webapp/src/app.tsx, webapp/src/simulator.ts
This change introduces a more robust system for supporting simulator extensions, making it possible to support third-party extensions (though such extensions must be approved by the team).
* **New config section in targetconfig.json**
- Entries in the existing `approvedRepoLib` map have a new subsection called `simx`. This is used by both the client and the backend to specify and serve simulator extensions. See `SimulatorExtensionConfig` in `localtypings/pxtarget.d.ts` for specifics.
* **New config section in pxtarget.json**
- To support testing new or updated 3rd party simulator extensions before they go live, I've added a `testSimulatorExtensions` section to `pxtarget.json`. This allows simulator extensions to be configured in an upload target.
* **New URL parameter for local testing** …
=> Support for 3rd-party simulator extensions

pxtblocks/index.ts, pxtblocks/loader.ts, pxtblocks/monkeyPatches/grid.ts, pxtblocks/monkeyPatches/index.ts, webapp/src/blocks.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2552
This rather heinous monkey patch brings back our old image background for the minecraft editor workspace. Currently, this isn't possible without a monkey patch like this or something even hackier like observing the DOM.
I'll open an issue on Blockly to see if they can surface an extension point for customizing the Grid class. Seems like a reasonable thing to want to do!
=> Add monkey patch to restore background to minecraft workspace

webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/2557
minecraft is our only editor that actually customizes the blockly theme. setting the theme was causing blockly to fire an event which in turn triggered a type check on the home screen. that type check fails because there is no project open when you're on the home screen
=> don't fire type checks on blockly theme changes

pxtsim/runtime.ts, pxtsim/simdriver.ts
* Simulator extensions can be configured with a custom `aspectRatio`, but it was getting ignored. Modified `startSimulatorExtension` method to take an `aspectRatio` parameter and apply it to the simulator extension's iframe.
* Sanitize message channel string before using it as a class name in the simulator extension frame.
=> simulator extensions: apply aspect ratio to simx iframe

pxtblocks/contextMenu/contextMenu.ts
potential fix for https://github.com/microsoft/pxt-minecraft/issues/2560
when refreshing the blockly workspace, we call prepare blockly a second time which was throwing because of double registration of the workspace comment context menu options
=> catch exception when double registering comment context menu items

gulpfile.js, scripts/inlineBlocklySourceMaps.js
something changed in blockly that broke my old local debugging setup; i used to npm link my local clone of blockly and change their build files to inline the sourcemaps so that i could actually debug the compressed blockly code.
so i decided to solve the issue directly by writing my own script to inline the source maps from the released blockly npm package. i went ahead and added this to the gulpfile for non-production builds so that everyone can enjoy actually debugging blockly in a sane way.
one note: this does make it so that you correctly see the blockly source when stepping through files but it doesn't fix the names of variables that show up in the debugger; you still see the minified variable names. still it's a huge improvement over the old setup which didn't even point you to the …
=> inline blockly sourcemaps in development builds

webapp/src/marked.tsx
The icons are a bit clunky for Minecraft hour of code, and also don't make much sense because there are no toolbox categories with the `flyoutOnly` flag being used. Thus, we want to prevent the icons from being added when the `flyoutOnly` flag is being used in tutorials.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2562
=> Tutorial snippet highlights: check for the flyout flag to not include icon, clicking

pxtblocks/codecardRenderer.ts
Thanks to @riknoll for all the help.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2508
=> Match punctuation for code card descriptions

docs/extensions/getting-started.md
Add a hint section that includes the 'Authoring MakeCode Extension' video to the extension's "Getting Started" page.
https://youtu.be/XSskpMEHYlo
Closes #10230
=> Add the 'Authoring MakeCode Extension' video to 'getting-started'

pxtblocks/composableMutations.ts, pxtblocks/plugins/arrays/createList.ts, pxtblocks/plugins/functions/blocks/functionCallBlocks.ts, pxtblocks/plugins/functions/blocks/functionDeclarationBlock.ts, pxtblocks/plugins/functions/blocks/functionDefinitionBlock.ts, pxtblocks/plugins/functions/commonFunctionMixin.ts, pxtblocks/plugins/logic/ifElse.ts, pxtblocks/plugins/text/join.ts, webapp/src/blocks.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/5989
replaces all of our calls to `block.render()` with `block.queueRender()`.
for the linked bug, here's a timeline of what was happening:
1. the duplicate function is invoked
2. appendPrivate is called in Blockly to paste the blocks that are duplicated
3. the root block (in this case a forever block) starts to initialize which causes its children to be added to the render queue
4. each of the child blocks is initialized
5. as part of the function call block's initialization, `block.render()` is called which immediately flushes the render queue
6. the blocks in the render queue other than the function call are not actually rendered because they are marked as still initializing, but they are still removed from the queue
7. the child …
=> Use queueRender rather than render

docs/writing-docs/tutorials/control-options.md, localtypings/pxtarget.d.ts, pxtlib/docsrender.ts, pxtlib/tutorial.ts, theme/tutorial.less, webapp/src/app.tsx, webapp/src/marked.tsx, webapp/src/monaco.tsx, webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2571
This adds a hideToolbox metadata field for tutorials (only supported for monaco at the moment, not sure it makes much sense in a blocks scenario). When present, the toolbox is not shown and the user actually has to type things out.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2595
It also fixes a separate issue (that I initially thought was related to these changes but actually wasn't) with the workspace header, where it was always assuming we were in blocks mode. Now it accepts a property for the workspace id, which allows it to size everything correctly (thus, fixing the border).
In our Minecraft css, we've evidently started using flyoutOnly as a de facto indicator for HOC tutorials, so I've had to include it even …
=> Hide Toolbox in Minecraft Python Hour of Code

theme/tutorial.less, webapp/src/tutorial.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2579
We were trying to compute the tutorial pane's height directly to the scroll height of the content plus a hard-coded buffer, and I think the fixed buffer eventually got out of date when the styles changed.
Rather than simply updated the buffer size to a different fixed value, I set the height to `auto` which just dynamically resizes to fit content (Googling tells me it's well supported across different browsers, so I think it's safe).
There was also an issue where the clientHeight / scrollHeight comparison was slightly off when determining if there was overflow because the clientHeight value contains padding, which eats into the actual "user visible" area for the child content. I've added a function to calculate the height …
=> Fix Scrolling in Minecraft HOC Tutorial View

pxtblocks/plugins/math/fieldSlider.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/2576
The blockly fieldSlider styling was being applied generically to all range inputs, including the zoom slider. To stop this, I've added a class to the fieldSlider input and added that more specific selector to its css.
Fixed Zoom Slider:
Field Slider Unaffected:
=> Fix Minecraft HOC Zoom Slider

pxtlib/tutorial.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/2578
When a tutorial specifies `python-template` code (i.e. https://github.com/microsoft/pxt-minecraft/blob/master/docs/hour-of-code/2024/setdesign_python_activity2.md?plain=1#L8-L12) we were not parsing it correctly and ended up adding curly braces around the code. In some scenarios, the compiler could recover from the unexpected curly braces and still produce a few statements (seemed to happen when loops / indentation was present in the snippet), but in other cases, it was not able to recover. As a result, toolbox filtering wouldn't work and an error toast would appear. (Note that without this fix, the error toast still appears, even with the toolbox hidden.) Technically, even when the compiler did recover, some statements would be …
=> Fix Python Toolbox Filtering with Tutorial Template Code

theme/tutorial.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/2601
Fixes https://github.com/microsoft/pxt-minecraft/issues/2603
In commit https://github.com/microsoft/pxt/commit/a7e5cdee61f04a8c86a25bc6d7aaf4787ed231d3, I changed the height of the tutorial card to "auto" instead of a fixed value, and that meant the child (with height 100%) started overflowing when it exceeded the size of the parent. To fix this, I just set a max height on the child that's tied to the max height of the parent - basically the same setup we have for when the instructions are minimized, just at a bigger size.
I also made it so code snippets can wrap on spaces. There are some long-ish lines of code (or code-like) snippets in the Minecraft HOC tutorial, and they can cause horizontal scrolling on small widths, since …
=> Fix overflowing instructions and horizontal scrolling

webapp/src/editortoolbar.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2602
These started appearing as a side-effect of my changes to hide the toolbox (https://github.com/microsoft/pxt/commit/9e6dd9e5e5ac372d6a043265dc79af48c0850e55), since it's no longer in flyoutOnly mode. Add extra check for hideToolbox as well.
=> Hide Redundant Undo/Redo and Zoom Controls in Python

pxtblocks/loader.ts, pxtblocks/polyfills.ts
fixes https://github.com/microsoft/pxt-minecraft/issues/2555
this pr adds a simple polyfill for `Element.checkVisibility` to fix comment rendering in ancient browsers. i wrote the polyfill myself because a cursory search didn't find a suitable one and the method itself is pretty simple. the only thing mine doesn't do is traverse ancestors to check their `content-visibility`, but that's not needed for the linked bug.
=> Add Element.checkVisibility polyfill for Blockly

webapp/src/components/tutorial/TutorialCallout.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2556
Previously, the top location of this popup was simply "unset". Sometimes it'd happen to be in the correct location (I think because of how other elements are laid out in the DOM), but often times it wouldn't line up correctly. Rather than relying on that somewhat ill-defined behavior, this just sets the top directly so it's underneath the tutorial window.
I spent half a day trying to get this more in the css and less in the typescript, but I wasn't making progress so I decided to leave it be for now. I have other bugs to work on :)
Upload Target: https://minecraft.makecode.com/app/b43f1cf83819e95134eb935cf604acf0318dbb44-669fb69e00
FYI you may notice this issue while playing around with the upload target (I did...). I'll be …
=> Fix Hint Popup Location in Tutorials

cli/cli.ts, localtypings/pxteditor.d.ts, pxtcompiler/simpledriver.ts, pxteditor/editorcontroller.ts, pxtlib/browserutils.ts, pxtlib/cmds.ts, pxtlib/emitter/cloud.ts, pxtlib/github.ts, pxtlib/tutorial.ts, pxtservices/editorDriver.ts, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/idbworkspace.ts
This consumes the newly proposed /api/ghtutorial/ endpoint. Opening as a draft PR because this endpoint isn't actually released yet.
When loading a tutorial from github, this takes the response from /api/ghtutorial/ and uses it to populate all of the caches that we maintain in indexeddb. The rest of the markdown loading pipeline is unchanged, the requests it makes simply hit the cache instead of actually making requests to the backend.
This PR also makes it so that we now cache the latest versions of github repos inside indexeddb just like we do everything else. Unlike the other things we cache, the entries for latest versions expire after an hour. I might end up increasing this period, though, since that isn't very much time at all.
I also added a `skipgithubcache=1` query parameter that …
=> Consume new ghtutorial route when loading tutorials from github

theme/common.less, webapp/src/app.tsx, webapp/src/sidepanel.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2612
In the tutorial view, we were using the same `VerticalResizeContainer` component regardless of whether the tutorial was at the top (where you can actually resize the container) or the side (where resizing was disabled), and when switching between the two modes, that container was retaining state. As a result, if the user switched from top-bar to side-bar and then back to top-bar, the resize container would immediately pop back to its former height, but it didn't signal that change to the rest of the elements, so things were not positioning themselves to account for it.
I toyed with a few ways to fix this, but ultimately, I think it's odd for us to keep the `VerticalResizeContainer` around at all when the tutorial is in the …
=> Fix Gray Bar on Tutorial Resize

pxteditor/monaco.ts, theme/monaco.less, webapp/src/monaco.tsx
We had disabled this because it didn't work, but now we need it, so I hope it just works? I'm afraid I can only test on my phone. If anyone can try to put it through its paces on a chromebook, that'd be helpful.
Upload target:<s> https://minecraft.makecode.com/app/e42873906d2ffabc19ec09ae999dfd28c7beeedf-7a6367562b</s> https://minecraft.makecode.com/app/8429027c1a6da2fe4ee6f7e271b5680a162dfc7e-cd7ec17b08
The change that disabled it was https://github.com/microsoft/pxt/pull/7099, which references bug https://github.com/microsoft/pxt-microbit/issues/3170. Thankfully, things are clearly better now than they were then, so there's a good chance this is fine. Will still need some testing, though.
=> Re-enable intellisense on android

pxtblocks/layout.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/2613
Just wanted to note that the `disableFileAccessinMaciOs` flag is something that gets set in the `appTheme` when the `inGame=1` query variant exists. So there's a niceness because if the file access is disabled, we shouldn't allow for screenshots, but it also is a tell that we're in game for Minecraft. 
Another point is that we are also setting `disableFileAccessInAndroid` to true with the `inGame=1` query variant. I'm thinking about adding the check for that in the `enableSnapshot` function as well. However, I think leaving snapshots on for android is fine; at least testing in browser on my phone worked great. I would need to test on a Chromebook to see if it would work in game, though.
Upload target: …
=> Editor snapshots: added extra check for mac and ios for allowing screenshots

docs/writing-docs/tutorials/control-options.md, localtypings/pxtarget.d.ts, package.json, tests/tutorial-test/baselines/hideDone.json, tests/tutorial-test/baselines/hideToolbox.json, tests/tutorial-test/cases/hideDone.md, tests/tutorial-test/cases/hideToolbox.md, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorial/TutorialStepCounter.tsx, webapp/src/sidepanel.tsx, webapp/src/tutorial.tsx
Addresses https://github.com/microsoft/pxt-minecraft/issues/2539 (though that tutorial will still need a content update).
This adds a "hideDone" flag that can be set on a tutorial to indicate that the Done button should not be shown on the final step.
Also added tests for hideDone and hideToolbox (which I added in https://github.com/microsoft/pxt/commit/9e6dd9e5e5ac372d6a043265dc79af48c0850e55). Not sure how much value they bring beyond parsing validation, but I suppose that's better than nothing!
Vertical Sidebar:
Horizontal Top-bar:
=> Add "Hide Done" Option for Tutorials

cli/buildengine.ts, cli/cli.ts, cli/commandparser.ts, kiosk/src/index.tsx, localtypings/pxteditor.d.ts, multiplayer/src/index.tsx, pxteditor/experiments.ts, pxtlib/logger.ts, pxtsim/allocator.ts, pxtsim/debugProtocol.ts, pxtsim/embed.ts, pxtsim/langsupport.ts, pxtsim/libgeneric.ts, pxtsim/logger.ts, pxtsim/runtime.ts, pxtsim/simdriver.ts, pxtsim/simlib.ts, pxtsim/visuals/boardhost.ts, pxtsim/visuals/wiring.ts, teachertool/src/index.tsx, tutorialtool/src/index.tsx, webapp/src/app.tsx, webapp/src/cmds.ts, webapp/src/scriptsearch.tsx
part two of my master plan to allow you to copy logs in minecraft.
allows targets to add experiments to the experiments dialog. in this case, we'll be adding an experiment that copies logs to your clipboard.
also adds support for experiment cards that act like buttons rather than toggles, and passes the showNotification function to editor extensions so that we can show toasts
=> let editor extensions contribute experiments

docs/writing-docs/tutorials/control-options.md, localtypings/pxtarget.d.ts, package.json, tests/tutorial-test/baselines/hideDone.json, tests/tutorial-test/baselines/hideToolbox.json, tests/tutorial-test/cases/hideDone.md, tests/tutorial-test/cases/hideToolbox.md, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/components/tutorial/TutorialStepCounter.tsx, webapp/src/tutorial.tsx
Port of https://github.com/microsoft/pxt/pull/10248 (a few merge adjustments needed, but nothing major)
This adds a "hideDone" flag that can be set on a tutorial to indicate that the Done button should not be shown on the final step.
=> Port to Stable: Add "Hide Done" Option for Tutorials

pxtblocks/layout.ts, pxtlib/browserutils.ts, webapp/src/scriptmanager.tsx
I forgot that there were parts of this PR (https://github.com/microsoft/pxt/pull/10255) that were actually good fixes that I wanted to keep. I realize now that I could've just reopened  that PR, but here we are. 
We shouldn't let the user download a zip of their projects if they don't have access to the file system, so I added the check to the `Download Zip` button. I moved the `hasFileAccess` function to `BrowserUtils` because of this. If there are more places where we might want to check for file access, we now have the function in a more accessible place. 
The addition of the `inGame` check to `BrowserUtils` is no longer being used, however, there were a couple of scenarios where I almost needed a check like this and I think it's just nice to have in case there are needs for it.
Upload …
=> Only download zips if you have file access

webapp/src/idbworkspace.ts, webapp/src/workspace.ts
Fixes https://github.com/microsoft/pxt-minecraft/issues/2648
Most of the tables mentioned in the bug were already being cleared, but these were not.
During my initial investigation, I was looking into the resetAsync function, so I also converted that to async/await.
Upload target: https://minecraft.makecode.com/app/06aeece4ee1fde85d8cd6cae7c8f6a4d958c6efa-e055c7f346
=> Clear Additional Info on Workspace Reset

theme/tutorial.less, webapp/src/marked.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2655
There are blocks categories, in this case the agent category, that use images for their category icon rather than an icon within our font library. This change allows us to support these in the tutorial inline block styles. 
Upload target: https://minecraft.makecode.com/app/7e56fe5acb243e068f9ed4aa6a11126b94008019-2870f4b5c3#
=> Inline blocks for tutorial content: agent icon now showing up

pxtblocks/fields/field_gridpicker.ts
fixes https://github.com/microsoft/pxt-minecraft/issues/2661
conditional bind is only used for events that are part of the current gesture (e.g. after the click has started). for hover, you need to use bind instead.
=> use bind instead of conditional bind

pxtblocks/fields/field_gridpicker.ts
for whatever reason, the safari webview in minecraft is returning 0 for `window.outerHeight` but a correct number for `window.innerHeight`. this is definitely a browser bug given that the outerHeight should always be a bigger number than innerHeight as the name suggests.
this was causing both the block picker being too tall error and the animal picker being too short error. the difference between the two was that the block picker has the search bar, which was causing the div to be given a negative height whereas the animal picker was getting a height of 0
=> fix in game safari webview gridpicker height

pxtlib/emitter/cloud.ts
@thomasjball brought it to my attention that mkc was failing with a weird error when trying to fetch github repo dependencies. turns out it was crashing on this code because window isn't defined in node.
this will need to be ported over to micro:bit stable
=> fix cdn check for node

webapp/src/idbworkspace.ts
cherry pick https://github.com/microsoft/pxt/pull/10282 to minecraft stable
=> [Stable11.2] handle repopaths with github prefix

pxtlib/github.ts, tests/pxt-editor-test/editorrunner.ts, webapp/src/idbworkspace.ts
re: https://github.com/microsoft/pxt/issues/10279#issuecomment-2492435819
this restores compatibility with this tutorial URL format:
```
https://minecraft.makecode.com/#tutorial:https://github.com/mojang/educationcontent/computing/unit-2/lesson-1
```
note that the URL here is not a valid github url. going to https://github.com/mojang/educationcontent/computing/unit-2/lesson-1 will result in a 404. however, we used to support this format so i'm restoring that support.
i also added support for actual links to markdown files in github, for example https://github.com/Mojang/EducationContent/blob/master/computing/unit-2/lesson-1.md
and i added tests for all of these.
this will have to be ported to stable yet again
=> backwards compatibility for github tutorial paths

pxtlib/github.ts, tests/pxt-editor-test/editorrunner.ts, webapp/src/idbworkspace.ts
cherry picking the fix for https://github.com/microsoft/pxt/issues/10279#issuecomment-2492435819
=> [Stable11.2] cherry pick backwards compatiblity for github tutorial paths (#10286)

localtypings/pxtpackage.d.ts, webapp/src/package.ts, webapp/src/toolboxeditor.tsx
this adds the ability for projects and extensions to filter the toolbox. inspired by https://forum.makecode.com/t/creating-micro-bit-sandbox-restrict-available-blocks/32008
an extension or project can add a "toolboxFilter" entry in `pxt.json` like so:
```json
{
"toolboxFilter": {
"blocks": {
"device_show_leds": "hidden"
},
"namespaces": {
"pins": "hidden"
}
}
}
```
the possible values for each block or category are "hidden", "visible", and "disabled", though i don't think disabled actually does anything? i'm just matching the values we have available in our current toolbox filtering for tutorials and afaik disabled is just ignored.
toolbox filters are merged starting with the leaf extensions in the dependency tree and moving upwards to the main package. in other words, the top-level …
=> allow packages to filter the toolbox

teachertool/src/components/MakecodeFrame.tsx, teachertool/src/components/MakecodeFramePlaceholder.tsx, teachertool/src/components/styling/CriteriaInstanceDisplay.module.scss, teachertool/src/components/styling/MakeCodeFrame.module.scss, teachertool/src/components/styling/MakecodeFramePlaceholder.module.scss, teachertool/src/style.overrides/Input.scss, teachertool/src/transforms/setEvalResult.ts
This was some low hanging fruit we discussed after the customer interviews which I didn't get around to fixing until just now. Since I don't want to spend too long on it, I just done a "bare minimum" implementation. Haven't put together any nice graphics or anything like that, but I think it's still an improvement.
I've also increased the contrast for placeholder text in the input field (a11y issue and also came up multiple times in the interviews) and fixed a null ref exception that came up in testing.
Upload target: https://makecode.microbit.org/app/910ba06ba32792294020a356752fa127895f5f68-329df429fe--eval
=> Teacher tool: Show placeholder text when no project is loaded

webapp/src/blocks.tsx
i'll add docs to https://github.com/microsoft/pxt/pull/10305 after this is merged.
adds the ability to localize help pages for extensions. simply put a `_locales` directory next to the markdown and put the translations inside just like how our other localization stuff works. see https://github.com/riknoll/arcade-character-animations/tree/main/docs/_locales/es for an example
=> Add the ability to localize help pages for docs

docs/extensions.md, docs/extensions/getting-started/github-docs.md, docs/extensions/github-docs.md
adding detailed docs on how to add help pages for blocks in github hosted makecode extensions.
i wrote this mostly from memory so @tballmsft i would appreciate it if you gave it a once over since you recently went through this process.
=> add docs for help pages in github extensions

teachertool/src/components/MakecodeFrame.tsx, teachertool/src/components/MakecodeFramePlaceholder.tsx, teachertool/src/components/styling/CriteriaInstanceDisplay.module.scss, teachertool/src/components/styling/MakeCodeFrame.module.scss, teachertool/src/components/styling/MakecodeFramePlaceholder.module.scss, teachertool/src/style.overrides/Input.scss, teachertool/src/transforms/setEvalResult.ts
Port of https://github.com/microsoft/pxt/pull/10303
This was some low hanging fruit we discussed after the customer interviews which I didn't get around to fixing until just now. Since I don't want to spend too long on it, I've just done a "bare minimum" implementation. Haven't put together any nice graphics or anything like that, but I think it's still an improvement.
I've also increased the contrast for placeholder text in the input field (a11y issue and also came up multiple times in the interviews) and fixed a null ref exception that came up in testing.
=> Port to Stable - Teacher tool: Show placeholder text when no project is loaded (#10303)

webapp/src/blocks.tsx
For French the code is 'fr' which just returns a single part. We can just use whichever parts are returned for the paths.
@riknoll spotted this testing out #10307, we were lucky/unlucky enough to pick French to try it out.
=> Fix localisation of help docs for langs like 'fr'

pxtblocks/composableMutations.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6580
another rendering bug that was very hard to track down but easy to fix. this one should maybe be hotfixed to minecraft but i don't think microbit has any expandable blocks...
=> fix extra render trigger when initializing expandable blocks

docs/static/tutorial-tool/tutorial.js
Add to tutorial tool ev3 beta.
https://github.com/microsoft/pxt/issues/10253#issuecomment-2513284973
I didn't understand if I need to change tutorial.ts
https://github.com/microsoft/pxt/blob/master/docs/static/tutorial-tool/tutorial.ts
=> Adding tutorial tool beta option to ev3 beta

common-docs/teachertool/catalog-shared.json, common-docs/teachertool/test/catalog-shared.json, common-docs/teachertool/test/validator-plans-shared.json, common-docs/teachertool/validator-plans-shared.json, teachertool/src/transforms/setEvalResult.ts
This puts the AI criteria & validation plan in our normal (non-test) catalog for the teacher tool. <s>Also fixes a null-ref I hit while testing</s> (moving to separate PR).
After this change, users will no longer need to add the `tc=1` url param to see the criteria.
=> Show AI Criteria in Teacher Tool

docs/blog/tools/code-eval-tool.md
Ugh, fix a messed up link in the blog post for "Code Evaluation Tool".
Closes #10338
=> Fix broken link find "Code Evaluation Tool" blog post

webapp/src/app.tsx
noticed this exception in the console; initGithubDb is called before the app target is being set which was throwing an exception. the exception happens in an async context so it wasn't actually causing any errors but it does prevent the indexeddb from purging  expired entries
=> move github init after app target setup

pxtblocks/builtins/loops.ts, pxtblocks/loader.ts, pxtblocks/plugins/duplicateOnDrag/connectionChecker.ts, pxtblocks/plugins/duplicateOnDrag/dragStrategy.ts, pxtblocks/plugins/duplicateOnDrag/duplicateOnDrag.ts, pxtblocks/plugins/functions/blocks/functionDefinitionBlock.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6626
the mutation method of storing if a block should duplicate on drag is thwarted by undo/redo because blockly doesn't restore the mutation value for whatever reason. anyway moving to a new strategy where we instead just allowlist particular combinations of parent blocks and inputs. this is probably less error prone anyhow!
=> new strategy for duplicate on drag blocks

pxtblocks/toolbox.ts
we had a bug where a toolbox block would not be recursively expanded if a shadow block within it happened to return something with an array type. this pr simply prevents the logic we have for the lists_create_with block from running if the shadow block id is not lists_create_with
=> fix shadow block generation for non-array blocks that return arrays

pxtblocks/composableMutations.ts
not an ideal solution, but this fixes the insertion marker bug i mentioned in standup. here's what the bug looks like:
=> clean up shadow blocks in insertion markers for expandable blocks

docs/asset-editor-shortcuts.md, webapp/src/components/ImageEditor/ImageCanvas.tsx, webapp/src/components/ImageEditor/actions/dispatch.ts, webapp/src/components/ImageEditor/keyboardShortcuts.ts, webapp/src/components/ImageEditor/store/imageReducer.ts
this tweaks a lot of existing shortcuts and adds a few more that are specific to the animation editor. all of the shortcuts that are affected by the marquee tool can now be combined with the `shift` key to affect all animation frames at the same time. for example:
look at the timeline in that GIF to see all of the frames editing at once.
this also means that all of the shortcuts that were previously tied to uppercase letters have now been moved to the lowercase versions of those letters. the shifted versions will still work, but will affect all frames in animations. they are unchanged in the image/tilemap editor. also the pan tool shortcut was moved from `h` to `q` so as not to conflict with the horizontal flip shortcut. this breaks from the standard set by most image editors for pan, but …
=> Add new animation editor keyboard shortcuts

docs/asset-editor-shortcuts.md, react-common/components/controls/Button.tsx, webapp/src/components/ImageEditor/keyboardShortcuts.ts
adds four new shortcuts:
* **PageUp** - Swap the current animation frame with the previous frame in the timeline
* **PageDown** - Swap the current animation frame with the next frame in the timeline
* **shift + PageUp** - Rotate all frames in the animation backwards one frame
* **shift + PageDown** - Rotate all frames in the animation forwards one frame
also fixes the right click handler on react-common buttons which i guess i never tested
=> Add animation editor shortcuts for moving frames in the timeline

theme/common.less
fixes https://github.com/microsoft/pxt-arcade/issues/2410
this issue might be filed in a few more places, this was the only instance i knew of.
fixes the bug where you can still see blockly field editors when the sim is made fullscreen
=> put root z-index above blockly widgets when sim is fullscreen

pxtsim/simdriver.ts
A very infrequent race condition occurs where the extension's simulator appears and the micro:bit simulator never appears. This is very curious, as the extension simulator can only be invoked by static typescript (user-level code), which must be executing, which should bring up the micro:bit simulator.  The problem is that the start function of simulatorDriver does not start the simulator in the case when it is being created the first time.  Most often, some other path then creates the simulator, and the start function is called, which does start the simulator. But this change ensures the the micro:bit simulator will always appear first.
=> need to start the simulator after create to avoid race

pxtblocks/plugins/duplicateOnDrag/connectionChecker.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6640
needs to be cherry picked to minecraft and mbit. the connection checker was being a little overzealous in the connections it disallowed
=> fix connection checks for draggable shadows

theme/image-editor/timeline.less, webapp/src/components/ImageEditor/Timeline.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6641
this fixes the issue where the click target for dragging an animation frame was off and adds automatic scrolling when you drag the animation frame to the edge.
enjoy this poorly cropped gif:
=> fix animation timeline drag and drop and add edge scrolling

pxtlib/docsrender.ts
The TOC/breadcrumb match is relying on an `indexOf() == 0` check instead of a full string match. Therefore a path string of `code-eval-tool` will match both of the TOC entries for `code-eval-tool` and `code` with a recursive TOC lookup. This will render an aggregated breadcrumb of both the TOC entries.
**Note**: The fix included here is a suggestion for a full path match. You can offer better or more efficient check.
Closes https://github.com/microsoft/pxt-microbit/issues/6069
=> Terminate TOC recursion on full filepath match

pxtlib/spriteutils.ts, pxtlib/tilemap.ts, webapp/src/package.ts
my riknoll/arcade-overworld extension has a block with a ton of tilemaps in it that you can expand using +/- mutator buttons. because of how our tilemap field editor works, an asset gets created for every one of these fields regardless of whether it's actually expanded in the project or not. as a result, your project gets flooded with hundred of tilemaps that you aren't even using.
this change isn't a proper fix for that issue, but it does at least prevent those tilemaps from being included in the compiled binary. the proper fix is to change how fields work so that those maps are lazily allocated. in any case, this is a good change even if we do eventually fix that root cause.
=> filter serialized tilemaps to only include used ones

docfiles/pxtweb/cookieCompliance.ts, localtypings/pxteditor.d.ts, pxteditor/editorcontroller.ts, pxtlib/cmds.ts, pxtlib/main.ts, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/projects.tsx
Changes in this PR:
* **Caching change**: Allow previously logged performance events to be sent to listeners that subscribe after the fact.
* **Configurable duration threshold**: Made the threshold for measurement reporting dynamic and configurable by the target extension. This preserves the default behavior while allowing targets to change it once they're initialized.
* **Include project id**: When available, include project header id in perf events.
=> Tweaks to performance metrics handling

pxtblocks/plugins/newVariableField/fieldDropdownMixin.ts
Blockly dropdown menus that include a `HorizontalRuleMenuItem` (menu separator) as a `MenuItem` have an issue where the menu separator becomes the selected menu item in a non-obvious way when navigating the dropdown via keyboard. 
See the video below for an example of this. Keyboard navigation should only visit the 4 'real' items in this dropdown, however, it also visits the menu separator as a 5th item.
https://github.com/user-attachments/assets/962f7043-bee6-4246-8810-f1a5aff5ae49
This PR disables the separator menu item so that it is ignored by keyboard navigation.
=> Remove block dropdown menu separator from keyboard navigation

common-docs/robots.txt, localtypings/pxtarget.d.ts, multiplayer/src/components/HeaderBar.tsx, pxtlib/util.ts, react-common/components/experiences/UnsupportedExperienceModal.tsx, skillmap/src/components/HeaderBar.tsx, teachertool/src/App.tsx, teachertool/src/constants.ts, tutorialtool/src/components/HeaderBar.tsx
This introduces the notion of "supported experiences", which could be extended to indicate if other CRAs like kiosk and skillmap are supported on a given target, though it is currently only implemented for Teacher Tool. I'm not attached to the term "experience" for these; it came up in standup, and it was better than anything I could think of, but I'm open to suggestions if others have ideas there.
I've definitely taken the "simple & quick" approach here. If we want to spend more time on this, it might make sense to shift things around so there's an allow-list of targets on each CRA (instead of allow-listing CRAs on targets), but it wasn't immediately apparent how to do that in a shareable fashion. Or we could handle it all in the backend before we even serve the app, though that'd be …
=> Add unsupported notification if accessing Code Eval from non-micro:bit targets

pxtblocks/copyPaste.ts, pxtblocks/external.ts, pxtblocks/loader.ts, webapp/src/blocks.tsx
this adds support for copy/pasting code between tabs and projects. i borrowed the strategy of the [cross tab copy paste](https://github.com/google/blockly-samples/tree/master/plugins/cross-tab-copy-paste) plugin which stores copied data in localstorage instead of the clipboard (thanks for the pointer @srietkerk!). the reason we can't just use that plugin directly is because we have some extra error cases to deal with that the plugin doesn't handle:
first off, it's possible to copy code from one project that has an extension and paste a block from that extension into another project that does not have it installed. in this case, i display an error message explaining that the block can't be pasted. it might be good in the future to give information about what the exact missing extension is; …
=> support copy/pasting between tabs and projects

webapp/src/app.tsx
After triggering the full screen simulator, the "escape" key does nothing. After minimising the simulator using the relevant button, the "escape" key now triggers the full screen simulator.
The logic in the code appears to be inverted. The call to focus the simulator also seems dubious as it feels like the best thing to do is leave focus on the fullscreen toggle button in both the expand and collapse case, however, I'd welcome feedback on this.
This PR fixes the inverted logic in the code ~~and removes the dubious focus call~~.
=> Fix key handling after simulator is made full screen

pxtblocks/plugins/comments/blockComment.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6593
with the new blockly, the block comments i implemented now remember the position you leave them in. old projects, however, don't have any comment position data stored with them so they were just getting jostled around into random locations when being imported.
this pr sets an offset of 16 pixels for x/y to mimic the behavior of the old editor for old projects
=> set a default offset for block comments with no position data

common-docs/reference/string.md, common-docs/reference/text.md
Remove the deprecated `parseInt()` function from card pages. Add in the newer `char-at()` methods.
Closes https://github.com/microsoft/pxt-arcade/issues/6576
=> Remove deprecated 'parseInt' from card pages

webapp/src/sui.tsx
This PR fixes the following bugs in keyboard handling for the dropdown menu component:
- There is currently a bug where key handlers are added to the menu items on `componentDidMount`. Any items that are added after `componentDidMount` (such as "Connect Device" in the settings menu) do not get key handling.
- On narrow screens, additional items are shown in the settings menu, however, none of these have key handling. This is because `getChildren` checks for mobile via `userAgent` and not whether the menu item is visible based on screen width.
All key handling has been moved up to the parent dropdown to address the first bug and the use of `offsetParent` replaces the call to `pxt.BrowserUtils.isMobile()` to address the second bug. This PR maintains the existing keyboard and mouse behaviour …
=> Fix keyboard navigation for the dropdown menu component

pxtcompiler/emitter/decompiler.ts, tests/decompile-test/baselines/compile_hidden_arguments.blocks
fixes https://github.com/microsoft/pxt-arcade/issues/6592
mainline blockly strictly enforces that shadow blocks cannot have non-shadow children, but there are still some cases where code like that is generated by the decompiler. it doesn't matter for project code since that code gets patched to fix this issue, but the block config decompiled code doesn't get patched.
rather than just apply the patches to the decompiled code here, i figured it was easy enough to just fix it from the source.
=> don't decompile non-shadow blocks within shadows

theme/soundeffecteditor.less
fixes https://github.com/microsoft/pxt-arcade/issues/6579
some css from the sound effect editor was tainting the color palette dropdown. fix is to nest it inside the sound effect editor's parent class
=> stop sound effect editor dropdown css from affecting other components

pxtblocks/fields/field_tileset.ts, pxtblocks/fields/field_utils.ts, pxtblocks/importer.ts, webapp/src/blocks.tsx, webapp/src/compiler.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6602
fixes https://github.com/microsoft/pxt-arcade/issues/6635
fixes https://github.com/microsoft/pxt-arcade/issues/6601
our old method of upgrading tilemaps doesn't seem to be working with the new blockly; when blockly sets the values of the created fields the field validation code is causing their values to be overwritten before we can perform our upgrades.
to bypass that issue, i converted the upgrade code to be performed directly on the blocks xml instead of the workspace.
also, since people might not be familiar with this ancient code, this is the upgrade logic that i put into place ages ago when we started having a concept of "assets" in projects. previously we stored the tileset in the variables of the blockly workspace and …
=> perform tilemap upgrade on xml instead of workspace

webapp/src/sui.tsx
The dropdown menu contents are currently `aria-hidden="true"` when the menu is open, and `aria-haspopup` has a similar inverted logic bug. This PR fixes the inverted logic for both attributes.
=> Fix inverted logic for dropdown aria

webapp/src/monacoSnippets.ts
When navigating the Toolbox using the keyboard arrow keys while in JavaScript or Python mode, as soon as the "Extensions" category is selected, it opens unexpectedly. This PR adds the `onlyTriggerOnClick` field to match the more expected behaviour in Blocks mode.
=> Prevent extensions page from being triggered unintentionally

webapp/src/sui.tsx
This is minor tweak to the `sui.DropdownMenu` component to ensure that "Enter" or "Space" via the keyboard match mouse click behaviour. This discrepancy was noticed when using keyboard controls on the "Sign In" button which unexpectedly opened a menu. See screenshot below:
=> Fix "Enter" on dropdown to match mouse click behaviour

react-common/components/controls/Feedback/FeedbackEventListener.ts, webapp/src/container.tsx, webapp/src/core.ts, webapp/src/projects.tsx
As the title says, this makes it so when we switch to high contrast, we use a high contrast/dark themed version of OCV.
This is what it looks like toggled on:
(Image updated)
=> OCV: add support for high contrast toggling

webapp/src/editortoolbar.tsx, webapp/src/simtoolbar.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6661
fixes https://github.com/microsoft/pxt-arcade/issues/6664
hides the two remaining buttons that download files because you can't do that from within iframes, apparently.
=> hide download and sim screenshot in time machine

react-common/components/controls/FocusList.tsx, react-common/components/util.tsx
Focus appears to get stuck while using the keyboard to navigate the versions in the "Version History" feature when parent tree items are not expanded. See the point at which focus becomes stuck in the screenshot below:
The `isFocusable` method checks the visibility of the sub-tree item using its computed display property, but this does not take into account that the item's parent div is hidden.
This PR uses `offsetParent` as an alternative approach to checking element visibility. In addition, `findNextFocusableElement` now passes the optional isFocusable argument to itself when called recursively.
The [`getComputedStyle` approach is still used in `findNextFocusableElement` as a fallback](https://github.com/microsoft/pxt/blob/master/react-common/components/util.tsx#L103), but perhaps not …
=> Fix isFocusable for FocusList component

theme/common.less, webapp/src/dialogs.tsx
Anchor tags without href attributes are not keyboard accessible. This PR replaces the anchor tag with a button which is natively keyboard accessible.
@microbit-matt-hillsdon
=> Make the "Pair Now" button keyboard accessible

pxtblocks/fields/field_numberdropdown.ts, pxtblocks/fields/field_tileset.ts, webapp/src/blocks.tsx
each commit is a different fix!
fixes https://github.com/microsoft/pxt-arcade/issues/6630
the issue here was that the min/max properties on the field were unset, which was causing it fail to parse values passed in as the default
fixes https://github.com/microsoft/pxt-arcade/issues/6643
this issue was that we weren't busting the flyout cache properly for tutorials where the contents of a flyout can change for each step
fixes https://github.com/microsoft/pxt-arcade/issues/6627
there are a ton of different ways to decompile to the tileset field and each one has slightly different syntax. adding a fallback case to the if statement that just tries to find the asset by name even if the value passed in isn't in the full asset reference format
=> A few blockly tutorial fixes

pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_tileset.ts, pxtblocks/fields/field_utils.ts, pxtlib/tilemap.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6656
this changes the asset fields' serialization so that they also include any referenced assets when saving state. saveState/loadState aren't called on fields during XML serialization, but they are called during copy/paste so this handles that scenario nicely without changing the save format of our projects.
when loading the state of a saved asset, there are a few scenarios to consider:
1. pasting the asset into a project that doesn't have an existing asset with that id
2. pasting the asset into a project that does have an asset with that id, where the value of the existing asset matches that of the serialized asset
3. pasting the asset into a project that does have an asset with that id where the value of the existing asset does not …
=> support copy/pasting assets between projects

pxtblocks/fields/field_ledmatrix.ts, pxtblocks/plugins/renderer/css.ts
This change is compatible with the current [keyboard navigation experiment](https://www.npmjs.com/package/@blockly/keyboard-navigation) and the [new work-in-progress one](https://www.npmjs.com/package/@blockly/keyboard-experiment).
To test it with the current experience having created a showLeds block:
1. enable the experiment via About
2. enable Accessible Blocks in the cog menu
3. focus the workspace
4. use D to navigate to the block and press enter to edit
When the new experiment is integrated we'll remove the WASD support.
This field is unusual in that it is immediately editable with a stub showEditor implementation.
Detail:
- Adds grid, row and gridcell roles
- Adds switch role for LED rect elements with aria-checked
- Adds aria-labels
- Applies CSS to clear the Blockly cursor fill …
=> Implement keyboard and screen reader accessibility for LED matrix field

webapp/src/blocksSnippets.ts
This pr is simple.
Like other blocks related to array variable, make "list" in for-of translatable.
Before (Japanese):
After:
@riknoll
=> Make "list" in for-of translatable

pxtblocks/builtins/loops.ts, pxtblocks/builtins/variables.ts, pxtblocks/help.ts, pxtblocks/plugins/duplicateOnDrag/variablesGetReporter.ts, pxtlib/spriteutils.ts, webapp/src/components/ImageEditor/ImageCanvas.tsx
each commit is a different fix!
abbf61b192c43cf7a32a28aef6688f880aaaeaee fixes https://github.com/microsoft/pxt-arcade/issues/6685 which was an issue with the bitmap equality function not handling the case where the floating layer's bitmap was set to undefined.
4061281f0013acdefe80c4e2c23135c24e184e35 fixes https://github.com/microsoft/pxt-arcade/issues/6686 by making sure that the image canvas properly takes focus when interacting with it.
dc6b429f79ec1dfd9d2eff1b78d1461a2040e661 fixes a longstanding issue where the first pixel was skipped when starting a drag
dd367051b6d2af88f9a28af669d9cc22bfddcf1e removes a monkey patch for the variable field that no longer works with latest blockly; this was causing sprite kinds to show up in the regular variable blocks. now we filter the variable …
=> Collection of fixes for bugs found on livestream

webapp/src/blocks.tsx
fixing a bug that was found on stream. the variable flyout wasn't refreshing when a new variable was created
=> refresh variable flyout when a new variable is created

react-common/styles/controls/DraggableGraph.less, theme/common.less, theme/soundeffecteditor.less
Fixes https://github.com/microsoft/pxt-arcade/issues/6733
Fixes https://github.com/microsoft/pxt-arcade/issues/6705
The header bars for field editors are hard-coded to match the colors of the blocks (mostly, though I did have to fix this for the sound effect editor in this change). With this in mind, we should also hard-code the editor toggle color to ensure good contrast.
Also, the sound effect editor graphs had some elements that were hard to see in dark mode. This includes some changes that should make them more apparent.
Before:
After:
=> Theme Fixes: Sound Effect Editor & Field Editor Header Bar

common-docs/blocks.md, common-docs/javascript/call.md, common-docs/javascript/functions.md, common-docs/javascript/operators.md, common-docs/javascript/sequence.md, common-docs/javascript/statements.md, common-docs/python/call.md, common-docs/python/functions.md, common-docs/python/operators.md, common-docs/python/statements.md, common-docs/types.md, common-docs/types/array.md, common-docs/types/boolean.md
Do some clean-ups in the *language* pages.
* Remove `@boardname@` macro where no longer appropriate or needed.
* Fix some spelling.
* Fix some formatting. 
Closes https://github.com/microsoft/pxt-minecraft/issues/2710
=> General cleanups in the language pages

pxtblocks/plugins/flyout/verticalFlyout.ts, pxtblocks/plugins/functions/blocks/functionCallBlocks.ts, pxtblocks/plugins/functions/blocks/functionDefinitionBlock.ts, pxtblocks/plugins/functions/commonFunctionMixin.ts, pxtblocks/plugins/functions/utils.ts, webapp/src/blocks.tsx
this fixes a few bugs with functions in new blockly that were discovered on livestream. namely:
1. the function toolbox flyout was being cached too aggressively causing it to not update when existing functions were edited
2. undoing/redoing edits to function definitions (e.g. right click + edit function) were not always working correctly
3. editing functions was causing any attached shadow blocks to have their state reset in the calls to those functions
to fix all these issues, i've overhauled how the mutation of function blocks works. firstly, our old implementation disposed all of the argument inputs when a function was edited and then recreated them which led to the shadow issue mentioned above. now, only the edited arguments are created/destroyed. the rest of the inputs on the block …
=> fix several function bugs in new blockly

teachertool/public/index.html, teachertool/src/App.tsx
Not adding support for changing themes yet, but we can at least load the default one.
=> Load Default Target Theme in Teacher Tool

webapp/src/codecard.tsx, webapp/src/scriptsearch.tsx
This affects code cards on the experiments page. At the moment, it is not possible to trigger the feedback link of these cards via keyboard, this action simple toggles the experiment on and off. This PR addresses this and also improves the appearance of the focus-visible outline around the "Beta Editor" card.
@microbit-matt-hillsdon
=> Improve keyboard accessibility of the codecard component

cli/cli.ts, pxtlib/main.ts, webapp/public/asseteditor.html
as i was messing with the asset editor page in the vscode extension, i noticed that it was referencing target.js. that file is huge (it contains all of the source of the target) and we definitely don't need it in the asset editor so this PR swaps it out for the targetlight version instead. i had to add a step to the target build to actually write out a js version of that file because previously we only included the json form.
also put a guard in main.ts for when bundledpkgs isn't defined
=> use targetlight in asset editor

webapp/src/editortoolbar.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/5912
Edit:
Also fixes https://github.com/microsoft/pxt-arcade/issues/6184
=> fix file download in download menu

localtypings/pxteditor.d.ts, pxteditor/editorcontroller.ts, pxtlib/auth.ts, pxtservices/editorDriver.ts, react-common/components/theming/themeManager.ts, react-common/styles/theming/base-theme.less, skillmap/src/App.tsx, skillmap/src/components/HeaderBar.tsx, skillmap/src/components/makecodeFrame.tsx, skillmap/src/lib/authClient.ts, theme/color-themes/high-contrast.json, theme/color-themes/overrides/high-contrast-overrides.css, theme/common.less, theme/highcontrast.less, theme/home.less, theme/semantic-ui-overrides.less, theme/themes/pxt/views/card.overrides, theme/tutorial-sidebar.less, theme/tutorial.less, webapp/src/app.tsx, webapp/src/auth.ts, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/container.tsx, webapp/src/filelist.tsx, webapp/src/immersivereader.tsx, webapp/src/projects.tsx, webapp/src/tutorial.tsx
This contains a few theme fixes.
**Changed theme preference storage to be target-based** 
Fixes https://github.com/microsoft/pxt-arcade/issues/6735
Before, it was a single theme id regardless of target, so if you changed themes in arcade, that would clear your preference for microbit, and so on...
**Menu Text Change**
Change "Select Theme" to just "Theme" (more consistent with "Language" in the same menu)
**A Few Color Fixes**
1. Fixes https://github.com/microsoft/pxt-arcade/issues/6743
2. Fixes https://github.com/microsoft/pxt-arcade/issues/6748
3. Fixes https://github.com/microsoft/pxt-arcade/issues/6739
4. Fixes https://github.com/microsoft/pxt-arcade/issues/6745
5. Fixes https://github.com/microsoft/pxt-arcade/issues/6309
6. A few others that didn't have bugs filed... (disabled …
=> Several Theme Fixes - New Preference Format, Color Tweaks

pxtlib/markdownMetadataParser.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6717
There were two issues happening causing the bug:
Firstly, some of the strings (location & highlight) should not be translated but were translated. They're used by the code to reference positions and elements in the DOM respectively, so when they're in french, they don't map to anything. I've gone through and removed the translations in crowdin.
Secondly, some of the properties had spaces before the semicolon, i.e: `location : center`, and that was being left in for the property name. For these, I think it's safe to trim the string, hence this PR.
=> Fix Editor Tour in French

webapp/src/app.tsx, webapp/src/sidepanel.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6747
fixes https://github.com/microsoft/pxt-arcade/issues/6305
just hiding some buttons in the version history preview!
=> hide "open in vscode" and "host multiplayer" in time machine

webapp/src/timeMachine.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6303 by sending a set-theme message when initializing version history. 
Upload target: https://arcade.makecode.com/app/3529fb9d4b915467271bdff5a5b12045037a1ba8-a0b65f11b2
=> Load Theme in Version History Preview

react-common/styles/controls/EditorToggle.less, react-common/styles/extensions/ExtensionCard.less, react-common/styles/theming/base-theme.less, theme/blockly-core.less, theme/color-themes/high-contrast.json, theme/common.less, theme/semantic-ui-overrides.less, webapp/src/components/assetEditor/assetGallery.tsx
Fixes some of the dark theme issues spotted in testing today. Generally speaking, each commit = 1 issue (though some are split in arcade changes too: https://github.com/microsoft/pxt-arcade/pull/6785).
Fixes https://github.com/microsoft/pxt-arcade/issues/6781
Fixes https://github.com/microsoft/pxt-arcade/issues/6762
Fixes https://github.com/microsoft/pxt-arcade/issues/6763
Fixes https://github.com/microsoft/pxt-arcade/issues/6774
Fixes https://github.com/microsoft/pxt-arcade/issues/6778
Also fixes input fields in report abuse and the dropdown menu for choosing hardware.
Upload Target: https://arcade.makecode.com/app/5711563fab6ebb9e9bae48fac06f5fed01f9053d-867f791e15
=> Dark Theme Fixes

react-common/components/theming/ThemeCard.tsx, theme/melodyeditor.less
This adds keyboard nav support for the theme picker modal (just needed to add the cards into the tab ordering), and it fixes the bpm box in the melody editor (since the whole thing is hard-coded to block colors, we can just hardcode the input color as well).
Fixes https://github.com/microsoft/pxt-arcade/issues/6773
Fixes https://github.com/microsoft/pxt-arcade/issues/6758
=> Theme Keyboard Nav & Melody Editor Fix

pxtlib/diff.ts
also bumps up the maximum diff size
i ran into this limit when messing around with a particularly huge project full of background images.
=> don't error out when the version history diff is too big

theme/color-themes/overrides/high-contrast-overrides.css, theme/common.less, theme/keymap.less, theme/semantic-ui-overrides.less, theme/themes/pxt/views/card.overrides, webapp/src/simtoolbar.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6761
Mute and debug buttons now switch to a darker shade of the same color when toggled on, rather than a separate bright color. Requires changes in pxt-arcade also necessary to update secondary-accent colors.
Fixes https://github.com/microsoft/pxt-arcade/issues/6788
This just wasn't themed before. I've updated the css to use theme colors.
Fixes https://github.com/microsoft/pxt-arcade/issues/6789
Just needed to add a border in the semantic ui overrides.
Upload target: https://arcade.makecode.com/app/a2b90411277dc31bf416b4bc830035728af40d75-0cd92e0a68
=> Fix Sim Button Toggle, Card Outlines, and Keymap Theming

pxtlib/browserutils.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6338
Here's what a screenshot of Jumpy Platformer looks like on live:
With the increase:
I played with the max size number, and this seemed to be the value that best suited really big games. Something like The MakeCode Forums 0.5 with the blocks spread around a bit (https://makecode.com/_HKvMx5AcviWd) still renders pretty clearly with 10mb. That's a pretty big game, though, and I'm not sure what sized games we're wanting to say "this will certainly render clearly."
One thing to note that I've seen is that the thing that really cuts down on the quality is halving the size of the image twice or more. It was very common that a screenshot reduces the size once, but twice really kills the quality of the image. Another thing to note is that …
=> Increase max screenshot size to 10mb

localtypings/pxteditor.d.ts, webapp/src/app.tsx, webapp/src/simtoolbar.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6634
removes the restriction where the debug state can only be toggled from within main.py, main.ts, or main.blocks
=> allow debug to be toggled from any file open in monaco editor

pxtlib/util.ts, webapp/src/components/ImageEditor/toolDefinitions.ts, webapp/src/components/musicEditor/MusicEditor.tsx, webapp/src/components/musicEditor/Workspace.tsx, webapp/src/components/musicEditor/utils.ts
fixes https://github.com/microsoft/pxt-arcade/issues/5694
this PR does a few things to make the music editor erase tool more friendly:
* you can now start the drag for the erase tool in the area above the staff (the part where the measure numbers are). previously drags that started there were just ignored
* the erase cursor is now "wider", in other words we now check all notes that overlap with 1 tick before and after the drag coordinate
* the eraser now interpolates from the last coordinate in the drag which prevents us from skipping notes when the mouse is moving really fast
finally i also fixed an unrelated bug where dragging drum tracks on the bass clef was registering notes in the treble clef. i don't know if this is filed anywhere; i just noticed it while debugging.
=> improve music editor erase tool

skillmap/src/components/HeaderBar.tsx, theme/semantic-ui-overrides.less
Fixes https://github.com/microsoft/pxt-arcade/issues/6797 (skillmap sign-in button text)
Fixes https://github.com/microsoft/pxt-arcade/issues/6796 (theming for semantic ui toggle checkbox)
Fixes https://github.com/microsoft/pxt-arcade/issues/6795 (better theming for disabled buttons)
Upload target: https://arcade.makecode.com/app/28f0a2c656bd46638304120d8906b7b03fa965aa-289c4aa7df
For skillmap: https://arcade.makecode.com/app/28f0a2c656bd46638304120d8906b7b03fa965aa-289c4aa7df--skillmap
=> More Dark Theme Fixes

pxtlib/tilemap.ts
fixes https://github.com/microsoft/pxt-arcade/issues/5721
a long while ago we had a bug where songs were serialized incorrectly so that the namespace for their ID in the project jres was the image namespace instead of the song namespace. at some point i fixed this bug, but old projects might still have this issue in their saved jres files. this fixes that by remapping the namespace when the project loads the jres files
=> add patch to fix bad song asset ids from old bug

webapp/src/editortoolbar.tsx
Reverts https://github.com/microsoft/pxt/pull/10408
Fixes https://github.com/microsoft/pxt-arcade/issues/6818
=> make the file click compile rather than save as file as happens on live

react-common/components/controls/TeachingBubble.tsx, theme/semantic-ui-overrides.less
Mostly, this fixes https://github.com/microsoft/pxt-arcade/issues/6817. To get the id-card-looking icon in the tutorial view, we add a "card" class to the icon's css, which conflicted with the "card" css class we use for code-cards. I just added a bit of special casing to avoid the conflict.
I have also added the `teaching-bubble-button` class to the buttons in the teaching bubble, because I need to be able to access them specifically to fix https://github.com/microsoft/pxt-arcade/issues/6807. However, the main chunk of that fix will happen in pxt-arcade with https://github.com/microsoft/pxt-arcade/pull/6825
Upload target: https://arcade.makecode.com/app/806ccd6ac700307751a9a55c0f3bdd0143e45dd4-5c060effad
=> Fix Card Icons in Tutorials

react-common/components/share/ShareInfo.tsx
Currently it redirects, but best to avoid that
=> use /edu/makecode

pxtlib/browserutils.ts, pxtlib/main.ts, webapp/src/editortoolbar.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6655
The `getReasonUnavailable` function that the switch statement relies on for the Cannot Pair dialog content can return undefined. There was no case covering the undefined option, so I added a default case for defining the modal body content. It looks like it would be pretty hard to hit this case in micro:bit with the playing that I did, but in case any other target also hits the undefined scenario, I wanted to make sure that we had some more generic messaging in the content.
As mentioned in the issue, on live the "Connect Device" button only shows up if you have a device connected and chosen in the hardware dialog. Changing the flags around to avoid showing this option before hardware was selected didn't seem to do anything, so I …
=> add a default option to the cannot pair dialog

pxtlib/shell.ts, theme/common.less, webapp/src/app.tsx, webapp/src/headerbar.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6800
this fixes the click behavior of the brand logo so that we don't try to open the home screen when clicked if we are in controller mode or locked editor mode. while i was there, i also fixed the cursor css and the aria roles on the brand and organization logos
=> fix aria roles of brand logo and locked editor behavior

pxtcompiler/emitter/emitter.ts
our compiler intelligently compiles unicode fonts such that the binary file only includes the characters that appear in the program text. this is great for hardware because it reduces the size of the compiled binary (our unicode font is fairly large) but it isn't necessary in the browser since we don't have that limitation.
you can try it out for yourself, try running this program in the simulator:
```ts
game.onShade(() => {
screen.print(String.fromCharCode(38190), 30, 30, 1)
})
```
nothing will print out on the screen because the character with char code 38190 isn't being included in the binary. however, this program will print it out fine:
```ts
game.onShade(() => {
screen.print("键", 30, 30, 1)
})
```
this PR removes that behavior from the binary.js compilation. the motivation here is …
=> disable unicode character filtering in binary.js compilation

cli/cli.ts, react-common/components/theming/ThemeCard.tsx
This adds theme names to our target strings file for translation and adjusts our theme-picker modal to lookup the localized name, when available.
Fixes https://github.com/microsoft/pxt-arcade/issues/6806
=> Make Theme Names Localizable

skillmap/src/components/makecodeFrame.tsx, webapp/src/auth.ts
This change saves the user's preference when setting a theme in skillmaps, and it fixes an error where I was double-parsing the json string and hitting exceptions when it was empty.
It's a bit of a shot in the dark, but I'm hoping this will fix https://github.com/microsoft/pxt-arcade/issues/6808 by ensuring any skillmap-specific setting stays in-sync with the main editor setting. Hard to say for sure if that's what was happening though, since we don't have a concrete repro.
=> Save Skillmap Theme Settings

theme/themes/pxt/views/card.overrides
Fixes the color in the "see all projects" card.
Before:
After:
=> Fix "See All Projects" Color

react-common/components/controls/Input.tsx
Fixes https://github.com/microsoft/pxt-arcade/issues/6851
A lot of the inputs that are most commonly used don't use our react common input so it's a bit hard to catch, but the `preserveOnBlur` is falsey by default, so any use of the react common input that doesn't have `preserveOnBlur` defined would automatically lose the values on blur.
The other places I have seen this behavior in beta are: in the music editor name, the duration for the sound effect editor, the namer for the color picker, and maybe more.
`preserveOnBlur` should default to true; a user shouldn't lose the text if they click off of the input.
=> give preserve on blur a default

theme/semantic-ui-overrides.less
Fixes https://github.com/microsoft/pxt-arcade/issues/6877
Before:
After:
After (other themes):
=> Add theming for github repo descriptions

theme/home.less, webapp/src/projects.tsx
Addresses the lack of contrast on some of focus-visible highlights on the home screen, as well as making the carousel buttons a single tab stop, which brings it closer to [the WAI-ARIA recommendations for tabbed carousels](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/#wai-ariaroles,states,andproperties).
[Demo](https://home-screen-keyboard-focus.review-pxt.pages.dev/)
Using tab to navigate
https://github.com/user-attachments/assets/9dc2b409-cd8e-4883-8b53-aecdc8de2fe5
https://github.com/user-attachments/assets/b714ec3a-6aa6-4b9f-a3fd-9253a4d315b0
https://github.com/user-attachments/assets/2a6ee186-aabd-4f2f-9287-060e08666116
=> Home screen keyboard focus

react-common/styles/onboarding/TeachingBubble.less, theme/accessibility.less, theme/common.less, theme/highcontrast.less, theme/themes/pxt/globals/site.variables
This makes the focus borders on buttons thicker and more noticeable in the default and high contrast themes.
Includes: the menu bar, editor selection, simulator transport, sidebar toggles, download and editor bottom bar buttons.
Does not include improvements to the simulator or workspace (Blockly et al).
Addresses https://github.com/microsoft/pxt-microbit/issues/5538#issuecomment-2694537592
There is discussion below around https://github.com/microsoft/pxt-microbit/issues/6082
Related work:
- Work on integrating the new Blockly keyboard navigation will remove the hidden tab stops due to the injection div and the Blockly workspace SVG. We also intend to remove the individual tab stops for the toolbox categories in favour of the arrow key navigation.
- Simulator tab sequence is OK here but …
=> Editor focus borders on keyboard navigation

pxtcompiler/emitter/backjs.ts, pxtsim/langsupport.ts, pxtsim/libgeneric.ts, pxtsim/runtime.ts
this pr surfaces some new functions in pxsim for reporting type errors like failed casts, accessing properties on null/undefined, etc. these new messages all actually go through localization and are generally more readable than what we have today.
i've also slightly tweaked our binary.js emitter to include the vtable information for failed casts so that we can include the expected type in the error message for that case.
finally, i went ahead and added type checking for all of our default sim implementations of the "native" types like strings, arrays, buffers, etc. i will have another pr in pxt-common-packages shortly that adds even more of these type checks.
=> unifying the messaging for type errors and adding type checks for builtin types

pxtlib/spriteutils.ts, pxtlib/tilemap.ts
this fixes the issue encountered by @UnsignedArduino [here](https://github.com/microsoft/pxt-arcade/issues/6837#issuecomment-2770210833) but doesn't fix the underlying issue that got the project into that state in the first place.
=> don't parse junk tilemaps literally

cli/cli.ts, gulpfile.js, pxtblocks/builtins/functions.ts, webapp/src/createFunction.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6891
looks like we were never getting the strings from react-common which is wild if true?
also, @thsparks, i edited your extra function types code slightly so that it now also includes the types without labels
=> add some missing localization strings

pxtblocks/builtins/functions.ts, pxtblocks/plugins/functions/blocks/functionDeclarationBlock.ts, pxtblocks/plugins/functions/extensions.ts, pxtblocks/plugins/functions/utils.ts, webapp/src/blocks.tsx, webapp/src/createFunction.tsx
fixes https://github.com/microsoft/pxt-arcade/issues/6897
this PR changes everywhere we call centerOnBlock, which at some point was given a second argument that i did not know about! without that boolean passed, centerOnBlock will center the block and all blocks attached below it, which is pretty much never what we want.
the bulk of this PR, however, is in blocks.tsx, where i reworked our centering behavior for the debugger. previously we would check to see if the currently highlighted block was off screen and then center the screen on that block. now i've changed it so that we do the minimal scroll to put the block into view rather than jumping it to the center of the screen. overall, this feels much more natural since the workspace moves less.
=> fix centering behavior for blocks

webapp/src/workspace.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6901
this changes our pull/merge code so that we don't completely obliterate any locally added dependencies when merging upstream changes from github.
sorry for the large change; it's just because i renamed some variables that i found hard to remember the meaning of when reading the code. and because i converted a `.forEach` to a `for of` loop.
=> don't delete dependencies when merging upstream changes

react-common/styles/theming/base-theme.less, teachertool/src/components/styling/CatalogOverlay.module.scss, teachertool/src/components/styling/EvalResultDisplay.module.scss, teachertool/src/components/styling/Toasts.module.scss, teachertool/src/style.overrides/Button.scss, theme/color-themes/high-contrast.json
I was originally thinking we could just use the colors-green, colors-yellow, and colors-red variables for this, but as was noted in https://github.com/microsoft/pxt/pull/10481, those may be a bit too generic to work well for these scenarios. In the teacher tool, for example, the microbit green color is a little too dark to work well as a "success" color. Separating them will lead to some duplication in certain themes, but it's nice to have the flexibility.
As is the case for all theme colors, any themes that do not specify a value in their json file will default to the value in base-theme.less.
For now, I've only used these new colors in the teacher tool. We can swap them out in other areas as needed.
With the new colors:
Fixes https://github.com/microsoft/pxt-microbit/issues/6137
=> Add theme colors for success, warning, and error

localtypings/pxteditor.d.ts, pxteditor/monaco-fields/field_musiceditor.ts, pxteditor/monaco-fields/field_react.ts, pxteditor/monaco-fields/field_soundEffect.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/field_tilemap.ts, pxteditor/monaco-fields/monacoFieldEditor.ts, webapp/src/cmds.ts, webapp/src/monaco.tsx, webapp/src/monacoFieldEditorHost.ts
this PR allows targets to create custom monaco field editors. it's part of the work i'm doing for minecraft right now.
most of this change is just moving the type definitions into pxteditor.d.ts
=> let editor extensions surface monaco field editors

pxtlib/spriteutils.ts, pxtlib/tilemap.ts
this is me throwing spaghetti at the wall to prevent the weird asset disappearing bug from breaking projects. i still have no repro for that bug, but this change just puts in some common-sense checks to make sure that we don't ever overwrite assets with obviously invalid ones.
again, because i can't repro the actual issue, i'm not sure that this will actually fix anything. it's possible that when that bug occurs all of the assets get overwritten with perfectly valid transparent assets or all of the assets are just summarily deleted from the project. but the project in [this comment](https://github.com/microsoft/pxt-arcade/issues/6837#issuecomment-2770210833) at least has an invalid tilemap (it has a tile width of 0) so maybe this would have prevented that one specific problem. we'll see …
=> try to validate assets before committing them

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_musiceditor.ts, pxtblocks/fields/field_sprite.ts, pxteditor/monaco-fields/field_musiceditor.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/tilemap.ts, webapp/src/components/assetEditor/assetSidebar.tsx
fixing a bug i found while investigating asset errors. when converting temporary assets to named assets, the temporary asset id was not being updated correctly everywhere except in the blockly asset field editors. all other ways to edit assets (monaco field editors and the asset editor tab) were not updating the junk id that we use for temporary assets into a valid qualified name.
=> fix temporary asset ids when converting to named assets

cli/server.ts
we already have support for redirecting simx requests to a different url for local development and for redirecting simx requests to a local instance of the backend.
however, @tballmsft informed me that the basic scenario of just hitting normal non-dev simx endpoints fails! this adds a case to our server to fix that
=> redirect simx requests on localhost

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_musiceditor.ts, pxtblocks/fields/field_sprite.ts, pxteditor/monaco-fields/field_musiceditor.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/spriteutils.ts, pxtlib/tilemap.ts, webapp/src/components/assetEditor/assetSidebar.tsx
gotta make sure we test these thoroughly...
=> [Stable11.3] Cherry pick asset fixes

cli/cli.ts, localtypings/pxtarget.d.ts, webapp/src/pxtjson.tsx
this pr allows targets to add extra non-compiler flag checkboxes to the pxtjson editor (aka the project settings dialog). the goal here is add a checkbox for the assetPack flag for arcade projects. for reference, this editor is only accessible in arcade by clicking on pxt.json in the file explorer so it's really just for content authors or power users.
currently this only supports boolean properties on the top level of pxt.json
=> add the option for targets to contribute checkboxes to pxtjson editor

pxtblocks/plugins/renderer/pathObject.ts
fixes https://github.com/microsoft/pxt-microbit/issues/6148
this was broken by blockly 12, but a pretty simple fix! the disabled pattern was overriding the `fill: none` attribute on the svg path of the error highlight
=> prevent disabled pattern from leaking into the highlight path

pxtlib/spriteutils.ts, pxtlib/tilemap.ts
this fixes the issue with the latest hot fix release.
the new code to patch the ids of temporary assets was causing us to lose the edited/deleted tile metadata that we store in the tilemap asset data (which was always a kind of hack). this PR simply adds a parameter to cloneAsset to make it so that the temporary editor data is also cloned
=> fix edited/deleted tile metadata being lost when patching temp assets

.github/workflows/pxt-buildpush.yml, .github/workflows/pxt-buildvtag.yml, cli/cli.ts, cli/nodeutil.ts, gulpfile.js, package.json
This pull request introduces changes to enhance the build and release process, improve flexibility in version bumping, and update dependencies. Key updates include adding support for conditional npm publishing, introducing new flags for version bumping, and updating branch protection checks.
* `.github/workflows/pxt-buildpush.yml` and `.github/workflows/pxt-buildvtag.yml`: Updated the npm test step to use `npm test:publish` for consistency with the new `test:publish` script. [[1]](diffhunk://#diff-faeeadae9c041a72aff1a45d90dd28d2431f90582953453de6f76c5dd2b4993eL73-R75) [[2]](diffhunk://#diff-07a664aee039fb6f0f6ab672a97a7da207410f2e026ea9764af334d7273b7186L32-R34)
* `gulpfile.js` and `package.json`: Added a `--publish` flag to the `travis` task and introduced a `test:publish` script in …
=> pxt bump tweaks

pxtblocks/fields/field_animation.ts, pxtblocks/fields/field_asset.ts, pxtblocks/fields/field_musiceditor.ts, pxtblocks/fields/field_sprite.ts, pxteditor/monaco-fields/field_musiceditor.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/field_tilemap.ts, pxtlib/spriteutils.ts, pxtlib/tilemap.ts, webapp/src/components/assetEditor/assetSidebar.tsx
we were still running into some flaky behavior with the new asset changes in stable. because these fixes were for minor bugs and not really needed for the hotfix, reverting them so that we can release the rest of the payload.
=> [stable11.3] reverting asset fixes for patch release

pxtblocks/compiler/typeChecker.ts, pxtblocks/loader.ts, pxtblocks/plugins/duplicateOnDrag/connectionChecker.ts, pxtblocks/plugins/functions/blocks/argumentReporterBlocks.ts, pxtblocks/plugins/functions/utils.ts, pxtblocks/toolbox.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5999
this fixes the connection checks for argument reporters so that they can't be dropped outside of a function definition, callback block, or event that defines them as a parameter. well, except if the block is disabled (i.e. orphaned on the workspace) because that is very useful when refactoring or copy+pasting code. argument reporters with the same name and type can also be shared between different functions/events.
here is a GIF showing off the behavior:
not thrilled that this is increasing the coupling between our plugins... at some point i need to do a refactor to make everything a lot more modular if we ever want to release these plugins externally. it won't be a ton of work, but needs to be done.
=> stricter connection checks for function and callback reporters

libs/pxt-common/pxt-core.d.ts, localtypings/pxtarget.d.ts, pxtblocks/toolbox.ts, pxtlib/service.ts, tests/decompile-test/baselines/block_text.blocks, webapp/src/monacoSnippets.ts
fixes https://github.com/microsoft/pxt-microbit/issues/6184
the length parameter of `String.substr` is optional, but it's not currently optional in blocks. this PR corrects that by deprecating the old block and creating a new one with an optional length parameter (with the usual + button to access optional parameters).
this change requires no upgrade rules. the old block definition has been moved on to `String.__substr` but will still convert to `String.substr` when switching to JavaScript because of the `blockAliasFor` annotation.
here is the old block:
and here is the new one:
the expanded text is exactly the same as the old one.
=> deprecate String.substr block in favor of one with optional length

react-common/components/controls/Input.tsx, theme/soundeffecteditor.less, webapp/src/BlocklyKeyboardIntercept.tsx, webapp/src/components/soundEffectEditor/SoundControls.tsx
Demo build: [https://dropdown-key-input-capture.review-pxt.pages.dev/](https://dropdown-key-input-capture.review-pxt.pages.dev/)
This PR attempts to make keyboard accessibility closer to the [WAI-ARIA standard for combo boxes](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) when an input provides a dropdown. Specifically:
* Down arrow opens the dropdown, where it exists
* The dropdown is given focus and is navigable by arrow keys, space and enter to select, and escape to abort
* There is only one active tab stop, removing the need for a separate stop to display the menu as that is nonstandard
1. Enable the Accessible Blocks plugin and add a Sound Effect block ([example project](https://makecode.microbit.org/_5UHgrUFrmfmg))
2. Open the sound effect block using the keyboard and navigate …
=> Keyboard accessibility improvements to Input component's dropdown area.

localtypings/pxtarget.d.ts, pxtlib/package.ts, webapp/src/app.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6010
when compiling programs that are too large for a variant, we currently just omit the disabled variant from the compiled hex entirely. for targets with alwaysMultivariant set (just micro:bit) that means we end up generating a non-fat hex with only a program for v2 hardware. flashing that hex to v1 hardware gives you a blank screen instead of a panic code.
this pr makes it so that we instead respect that setting and emit a program for each variant; the disabled variant program will just be the usual 927 panic code that indicates unsupported hardware.
=> when compiling too-large programs include disabled variants if alwaysMultivariant

pxtblocks/plugins/flyout/blockInflater.ts
fixes https://github.com/microsoft/pxt-microbit/issues/6181
for a detailed explanation of the behavior in blockly that necessitates this change, see https://github.com/google/blockly/issues/9007
=> workaround blockly flyout variable clearing behavior

pxtblocks/plugins/functions/blocks/argumentReporterBlocks.ts, pxtblocks/plugins/functions/fields/fieldArgumentReporter.ts, pxtblocks/plugins/functions/index.ts, pxtblocks/toolbox.ts, pxtcompiler/emitter/service.ts, pxtlib/blocks.ts
fixes https://github.com/microsoft/pxt-microbit/issues/1507
this PR adds the ability to localize callback parameters in blocks with draggable reporters. the json entries for callback parameters look like this:
```
// qname|handlerParam|paramName
"radio.onReceivedString|handlerParam|receivedString": "receivedString",
```
i went with this format over the usual `{id:whatever}` thing we use for most `rlf` strings because i wanted to match what we do for the other block strings, which i guess predate the nicer curly brace syntax. 
in order to actually display these strings, i store this localization `rlf` key as a mutation in the block when generating XML for the toolbox. that means this will not retroactively apply to old projects, which will not have the mutation present. also, this will …
=> add ability to localize callback parameters

package.json
=> [pxt-cli] bump version to v11.4.20

cli/nodeutil.ts
`child_process.spawn` handles the escaping of arguments in bash, but not in windows. this meant that we were getting double quotes in prs made from WSL (see https://github.com/microsoft/pxt/pull/10575) which in turn broke the regex in our github action that detected whether the merged commit should be tagged or not.
=> Only quote commit messages if bumping in windows command prompt

package.json
=> [pxt-cli] bump version to v11.4.21

docfiles/style.css, theme/accessibility.less
Fixes https://github.com/microsoft/pxt-microbit/issues/6198
=> Color contrast: have skip links use a black color rather than navy

teachertool/README.md, teachertool/src/App.tsx
msft login is currently broken on staging when serving on localhost so i had to put in this little workaround for bypassing the need to sign in to the teacher tool.
=> add localhost flag for skipping auth check in teacher tool

pxtblocks/loader.ts, pxtblocks/plugins/functions/fields/fieldArgumentReporter.ts, pxtblocks/plugins/functions/utils.ts, pxtlib/service.ts
in my earlier callback param localization pr, i mistakenly assumed that all block translation keys were included in the lookup table for `rlf()`. well, turns out they aren't, instead they get crammed into the symbol info of the corresponding function. that doesn't quite work for my scenario since i need them to be globally available
this pr works around that issue by storing them in our global translation cache. while i was fixing this, i also went ahead and did a little refactor to reduce the coupling between the plugin and pxt and also added some logic to lookup the translation for the containing block which fixes the issue i mentioned [here](https://github.com/microsoft/pxt/pull/10567#issuecomment-2860481254)
=> store block param localization in translation cache

package.json
=> [pxt-cli] bump version to v11.4.22

webapp/src/sidepanel.tsx
Approach to fixing https://github.com/microsoft/pxt-microbit/issues/6208
Can't think of a need for having a tab stop for board view when the simulator is full screen so I have removed it in this PR. Open for change if we think it is better to have a tab stop for board view in which case I can make the focus ring clearer when focus is at board view.
Try it out here: https://sim-fullscreen-tabstop.review-pxt.pages.dev/#editor
=> Remove boardview tab stop when simulator is fullscreen

localtypings/pxteditor.d.ts, pxteditor/monaco-fields/field_musiceditor.ts, pxteditor/monaco-fields/field_react.ts, pxteditor/monaco-fields/field_soundEffect.ts, pxteditor/monaco-fields/field_sprite.ts, pxteditor/monaco-fields/field_tilemap.ts, pxteditor/monaco-fields/monacoFieldEditor.ts, webapp/src/cmds.ts, webapp/src/monaco.tsx, webapp/src/monacoFieldEditorHost.ts
This is in anticipation of us hotfixing the minecraft file read/write changes
=> [Stable11.2]Cherry pick editor extension monaco field editors to Minecraft stable

pxtblocks/fields/field_note.ts
Enable the user to select a note value via the keyboard using the up and down arrow keys.
https://github.com/user-attachments/assets/c2919ede-4f62-44c0-b617-6fded5545142
This is an unusual field for keyboard navigation because the Block's "frequency" input remains focused rather than moving focus to the piano view as an editor would. To make the piano view into a separate keyboard-navigable widget would be a larger piece of work. I suggest this as a pragmatic improvement that improves accessibility and makes the editor more engaging to keyboard users without otherwise changing the note field.
**Live demo:** https://note-field-keyboard-accessib.review-pxt.pages.dev/
1. Enable keyboard navigation.
2. Add a "Play Tone" block from the "Music" flyout.
3. Navigate to the block using the …
=> Use Up and down arrow keys in note field to select notes

pxtblocks/fields/field_ledmatrix.ts, pxtblocks/fields/field_matrix.ts, pxtblocks/fields/field_melodySandbox.ts, pxtblocks/loader.ts, pxtlib/melody-editor/melodyGallery.ts, theme/melodyeditor.less
**Demo link** https://melodysandbox-keyboard-acces.review-pxt.pages.dev/
This makes the MelodySandbox and gallery easily navigable with the keyboard, including
* keyboard handling
* Tab and arrow key navigation as appropriate and with reference to WAI-ARIA including role information.
* visible focus highlighting
* keyboard focus trapping while working in the editor
Architecturally, it now shares common code with the LED matrix field, to facilitate consistent changes across accessible matrix elements.
https://github.com/user-attachments/assets/c3c9ede7-6ed4-4fde-b6e9-a9dc22bc082f
The melody editor is a single tab stop, navigating with the arrow keys following the WAI-ARIA grid pattern. Up and down arrow keys immediately change the pitch of a note if it is enabled, space enables or disables …
=> Keyboard accessibility for the MelodySandbox field.

pxtlib/melody-editor/melodyGallery.ts, react-common/components/controls/DraggableGraph.tsx, theme/soundeffecteditor.less, webapp/src/components/soundEffectEditor/SoundGallery.tsx
**Live demo:** https://music-blocks-rtl-fixes.review-pxt.pages.dev/
Multiple issues found while testing in Arabic
**Gallery views**
For the Sound Effect and Melody editors, both their gallery views have the left and right arrow keys reversed.
**Text anchoring issues in Sound Effect editor**
Draggable graphs, before:
After:
Play button before:
After:
=> Music blocks rtl fixes

webapp/src/editortoolbar.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6173
this was introduced by https://github.com/microsoft/pxt/pull/10475
looks like we were checking if the array was undefined or not, but in fact it is always defined and just points to an empty array if there are no external options
=> bring back the download as file option

package.json
=> [pxt-cli] bump version to v11.4.23

pxtblocks/loader.ts
fixes https://github.com/microsoft/pxt-microbit/issues/5839
in my brief testing, it didn't seem like this caused any ill effects. this is working around a blockly bug where the touch identifier isn't cleared properly when the text area in a comment is focused.
=> force blockly to clear touch identifier on ios safari

pxtblocks/fields/field_ledmatrix.ts, pxtblocks/fields/field_matrix.ts
Blocked on #10596 so draft for now. [Diff once that's merged](https://github.com/microbit-matt-hillsdon/pxt/compare/blockly-12...microbit-matt-hillsdon:pxt:focus-rect).
Fix matrix focus indicator on Safari
foreignObject leads to mysterious positioning issues.
Easier to just use more SVG.
=> Fix matrix focus indicator on Safari

package.json
=> [pxt-cli] bump version to v11.4.24

package.json
=> [pxt-cli] bump version to v11.2.34

pxtcompiler/emitter/decompiler.ts, pxtlib/service.ts
blocks with the `constantShim` annotation are used to collect all of the constants on a namespace. for example, all of the Math constants. we associate constants with this block by checking if they have a `blockIdentity` annotation pointing to the qualified name of the function marked as `constantShim`
this fixes two bugs:
* constants that have a `block="name"` annotation were creating extra blocks in the toolbox. fixed by changing the service to not add auto-generated block ids to constants that have the `blockIdentity` annotation
* fixed decompilation of these blocks, which was HTML escaping the qualified name. those should already be HTML safe, so no need to escape again!
=> fix a couple bugs for blocks with the constantshim annotation

package.json
=> [pxt-cli] bump version to v11.4.25

webapp/src/accessibility.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6260
currently "skip to blocks editor" only shows up if keyboard nav is turned on. now, if it's turned off we have a new option "enable blocks keyboard controls" in its place to turn on the keyboard nav
@microbit-matt-hillsdon FYI
=> Add blockly keyboard controls to accessibility menu

package.json
=> [pxt-cli] bump version to v11.4.26

webapp/src/blocks.tsx, webapp/src/monaco.tsx, webapp/src/monacoFlyout.tsx, webapp/src/toolbox.tsx, webapp/src/toolboxeditor.tsx
Only select / highlight the search category when it is actually selected by the user. This can happen if the user hits "Enter", "Tab", or "ArrowDown" from the search input. The previous behaviour resulted in users thinking they could use "ArrowRight" from the search input to move into the flyout and this PR aims to address that.
This PR also:
-  fixes a toolbox focus bug resulting from clicking on a toolbox category, then clicking on the sim, then re-focusing the toolbox again via keyboard and doing this more than once. This resulted in no category being selected by default.
- clicking on Monaco flyout entries no longer results in a focus event and a click event being handled. Only focus events are now handled and roving tab index is used to reduce tab stops and ensure that clicking on a …
=> Improve search category selected state

webapp/src/container.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/6120
When I was fixing that bug initially, I wanted to follow the menubar pattern that the download button followed, but the editor toggle is different enough from the download button that it needs to be kept as an option. This is mostly because the role menubar doesn't allow for the "selected" attribute, and setting whether or not something is selected is pretty important for the editor toggle.
=> change editor toggle back to a listbox

webapp/src/app.tsx
Eric,
So the major issue here is that with my fix to jacdac/pxt-jacdac (to use "jacdac" channel) raises an issue in pxt, which is that the logic in app.tsx causes the old simulator and new simulator both to appear.  Once the old simulator is removed from pxtarget.json, I think the new one may stop working. So, need to figure out how to generalize the logic here. 
Update:
- this happens without any real device on the jacdac bus
- it's purely a function of "jacdac" being sent around with iframes. what I am pretty sure happens is that the new simx sends a "jacdac" to the makecode sim, and that triggers the logic to bring up the old sim
the basic problem is the use of "jacdac" message that with the old sim makes the simulator appear. it doesn't separate initialization from this messaging, …
=> jacdac bridge logic

webapp/src/container.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6325
the onclick was double triggering. this removes the onclick from the inner element since clicking on that element also triggers the outer one anyway
=> fix onclick for checkbox menu items

pxtsim/simdriver.ts
Context:
- We will have both old and new jacdac sims alive for a while; 
- We don't want old jacdac sim showing when new jacdac sim already is up; 
- also don't want to change the logic for dealing with old message sim, since they are going away. 
Solution:
- A temporary fix for the explicit case we want to rule out that will become dead code and can be eliminated once old jacdac sim is removed from pxtarget.json
=> don't allow old jacdac sim if new one is present

react-common/components/controls/Checkbox.tsx, react-common/styles/controls/Checkbox.less, theme/common.less, webapp/src/container.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6325
swaps out the native checkboxes for a fake checkbox
=> switching menuitemcheckboxes to use icons rather than real checkboxes

package.json
=> [pxt-cli] bump version to v11.4.29

localtypings/pxtarget.d.ts, pxtlib/github.ts, webapp/src/extensionsBrowser.tsx
this is the feature work for https://github.com/microsoft/pxt-microbit/issues/6011
i'll open a separate pr on pxt-microbit to actually hide the extension.
this PR adds a new flag to the targetconfig that allows extensions to be hidden from search results. originally i wanted to use the "hidden" flag that we have in pxt.json, but we don't actually have access to that when doing a search since it would require us to clone the repo
=> add targetconfig flag for hiding extensions from search results

package.json
=> [pxt-cli] bump version to v11.4.30

pxtblocks/compiler/compiler.ts, pxtblocks/compiler/typeChecker.ts
fixes https://github.com/microsoft/pxt-microbit/issues/6255
adds a descriptive error for for-of loops that are missing the list input. this error does appear in the error pane as well
i emit `[0]` here as that is consistent with how we handle emitting unknown arrays in other places in the blocks compiler.
=> add blocks compiler error for missing for-of list

pxtlib/emitter/cloud.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/6339
This fixes the static package scenario by making `initRegionAsync` more resilient to network & URL format failures. I couldn't find a reliable way to detect if we were in "static package" mode (and adding one seemed out of scope for this fix). But I think it can be fixed more simply: instead of throwing an exception when we can't get the region, just log the error to console, set a default, and move on. There's no particularly good reason to fail noisily in this case, so I think the simple log is sufficient.
Confirmed `pxt staticpkg` works again after this change.
=> Fix Static Package InitRegion Failure

package.json
=> [pxt-cli] bump version to v11.4.31

pxteditor/history.ts, pxtlib/package.ts, tests/pxt-editor-test/editorrunner.ts, webapp/src/package.ts, webapp/src/workspace.ts
this fixes an issue that was reported on the forum where a project's history file was growing huge and making the editor super slow and preventing sharing from working. the underlying issue was that `_history` was being added to the `files` list in `pxt.json`. i'm still not sure how that happened exactly, but this PR fixes that and also adds some fixes to control the file size.
changes include:
* prevents `_history` from being added to `pxt.json` (or at least prevents it on the code path that i think is most likely the culprit)
* prevents `_history` from being included in the result of `filesToBePublishedAsync`, which decides which files are included in downloaded and share projects
* prunes existing history snapshots to remove `_history` if it's present in case any projects ran into this …
=> fix history file size issues

pxtblocks/fields/field_dropdowngrid.ts
Live demo: https://rtl-dropdowngrid-keys.review-pxt.pages.dev/
Dropdown grid arrow keys updated to reflect whether the screen has been laid out for a RTL or LTR language. For instance:
**As used in pxt-maqueen**
**As used in pxt-planetx**
In both cases, this fix allows the left arrow to move the cursor left, and the right arrow to move it right, when the language is RTL.
=> Inverts keys for left and right in dropdowngrid

theme/common.less
Fixes https://github.com/microsoft/pxt-microbit/issues/6218
The `hc` class that used to get applied to the div with the root id is now getting applied to the div with the main class, so I updated the css here to reflect that, causing the css to be applied when we want it.
=> fix high contrast editor dropdown hover

package.json
=> [pxt-cli] bump version to v11.4.32

pxtcompiler/emitter/service.ts
fixes https://github.com/microsoft/pxt-microbit/issues/6247
fixes the toolbox search to take the parent attributes into account when generating searchable strings for each block
before:
after:
=> take toolboxparent into account when generating block search string

pxtblocks/layout.ts, pxtrunner/renderer.ts, pxtrunner/runner.ts, theme/docs.less, webapp/public/docs.html, webapp/src/container.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6330
this pr fixes a few side docs tab navigation bugs
* the "go back" button wasn't tab navigable. it now has a tabindex and was converted to an `<a>` element
* the pop-out button was at the end of the tab order in the side docs. it's now the first element in the order
* the rendered SVG blocks still had the tabindex attribute on some elements
=> fix tab navigation in side docs

pxtblocks/plugins/comments/blockComment.ts
fixes https://github.com/microsoft/pxt-microbit/issues/6391
i made the setBubbleVisible method async a while ago to fix an issue with comment rendering. as a result, it's possible for the bubble to not have been created when getBubbleLocation is called even though bubbleIsVisible returns true.
=> fix exception when accessing bubble position before rendered

package.json
=> [pxt-cli] bump version to v11.4.36

localtypings/pxteditor.d.ts, package.json, pxtsim/accessibility.ts, pxtsim/embed.ts, theme/areamenu.less, theme/pxt.less, theme/sidedoc-keyboard-nav-help.less, webapp/src/app.tsx, webapp/src/components/AreaMenuOverlay.tsx, webapp/src/components/KeyboardControlsHelp.tsx, webapp/src/shortcut_formatting.ts
Tweaks in response to feedback and discussions around terminology.
- "Jump to region" renamed to "Open area menu" and corresponding internal renames. This makes it clearer that you don't need to hold Cmd+B.
- Cmd+B now toggles the area menu rather than just opens it.
- Tweak text describing move mode.
- Tweak shortcut display to prefer Ctrl+Y on Windows for redo.
- Tweak the platform detection to make it easier to hack locally to try the other platform's scenario.
I've also opened a Blockly PR to sort out the weirdly ordered Shift+Cmd+Z.
=> Keyboard Controls help tweaks

package.json
=> [pxt-cli] bump version to v11.4.39

package.json
=> [pxt-cli] bump version to v11.4.40

pxtsim/simlib.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/6408
To test: https://makecode.microbit.org/app/39186a02f452020872fe9c95c14f43a1cefb8b66-476243682f#
=> audio sim: lower the volume to be closer to that of the other audio blocks

theme/blockly-core.less, theme/common.less, theme/serial.less
- Removed keyboard focus outlines around Sound Effect and Melody editors
- Show data screen
- Extensions page
On the Extensions page, the css is using an `::after` pseudo-element to apparently implement focus outlines, and I don't understand why but it was causing issues with the high contrast outlines. I disabled the `::after`  specifically for the Extensions page, but I'd like to flag it here. The correct solution might be to fix the buttons and inputs at a higher level, or alternatively it is implemented this way for a good reason.
When opened using the mouse.
**Before**
**After**
**Before**
https://github.com/user-attachments/assets/ee3810f7-d797-4c70-9e33-a0c08b8bff3f
**After**
https://github.com/user-attachments/assets/68ea266e-4ec1-4dd6-8d72-5103b8321098
**Before** …
=> Improved keyboard focus outlines for various screens

react-common/styles/onboarding/TeachingBubble.less, theme/color-themes/overrides/high-contrast-overrides.css
Fixes https://github.com/microsoft/pxt-microbit/issues/6419
This moves the teaching bubble high contrast css into our high-contrast-overrides file and updates it to account for some of the new error help elements.
Before:
After:
=> Fix teaching bubble in high contrast

webapp/src/blocks.tsx, webapp/src/errorList.tsx, webapp/src/monaco.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/6372
For text errors, we were able to determine if an error was a compile or runtime error using the presence of a stack trace, but for block errors, there are some that do not prevent running the program but also do not have a stack, so the same method was not as reliable (hence, we just always showed the button).
However, looking more closely, I believe we can determine if it's a run-blocking error based on whether we detect the error in the typescript compile diagnostics or not. With that in mind, I've added a specific `preventsRunning` flag to errors, which we can now set and use for determining if we should show the debugger suggestion. When we detect a typescript compile error in blocks, we set this to true. If it's a runtime or …
=> Do not show debug suggestion when a project can't compile

package.json
=> [pxt-cli] bump version to v11.4.41

localtypings/pxteditor.d.ts, webapp/src/accessibility.tsx, webapp/src/app.tsx, webapp/src/auth.ts, webapp/src/container.tsx, webapp/src/core.ts, webapp/src/projects.tsx
fixes https://github.com/microsoft/pxt-microbit/issues/6396
this pr makes a few tweaks to our accessibility tick events:
* combines all of the toggleAccessibleBlocks ticks into a single tick. the source of the tick (settings, homesettings, or accmenu) is now a custom dimension.
* adds tick events for showing/hiding the navigation regions
* adds tick events for showing the keyboard control sidedocs
* adds a custom dimensions to our `app.editor` tick which indicates what file type is loaded for the editor and whether accessible blocks are enabled
@abchatra @microbit-matt-hillsdon @microbit-lucy are there any other scenarios you'd like to collect data on? any keyboard shortcuts you want me to instrument?
=> clean up accessibility tick events and add missing ticks

package.json
=> [pxt-cli] bump version to v11.4.42

package.json
=> [pxt-cli] bump version to v11.4.43

localtypings/pxteditor.d.ts, webapp/src/app.tsx, webapp/src/blocks.tsx
This addresses https://github.com/microsoft/pxt-microbit/issues/6433
The melody editor suspends the simulator while it is open, to prevent audio issues. However, restarting contains a call to close any blockly dropdowns, which is a problem if you closed the melody editor by clicking on a dropdown.
This plumbs through the `background` flag to enable the melody editor to restart the simulator without closing any unnecessary dropdowns.
**Before**
https://github.com/user-attachments/assets/a7aa3825-d84e-4716-b3f1-e46cf1939a65
**After**
https://github.com/user-attachments/assets/4f21a8d3-c3c6-4282-8438-3e1e52d5abfd
=> Stop simulator from closing dropdowns when restarted from melodyeditor

webapp/src/blocks.tsx
This avoids us remembering workspace selections (via 'w') for new projects.
This fixes this scenario: https://github.com/microsoft/pxt-microbit/issues/6421#issuecomment-3023424575
The remaining scenarios on that ticket will be fixed by the next blockly/plugin upgrade next week.
Demo: https://blockly-ws-focus-reset.review-pxt.pages.dev/ (once built)
=> Reset the focus manager when loading a header

package.json
=> [pxt-cli] bump version to v12.0.0

webapp/src/container.tsx, webapp/src/headerbar.tsx
It was missing on first load (with the setting enabled) because there isn't an editor at that point so isBlocksEditor returns false. Nothing causes the menu to re-render when an editor has been assigned. The settings component had a working inBlocks prop so we've switched to use that approach. I think that only really works because the parent component of the menus is not pure. So far as I can tell, there's no React state for the current editor.
Also simplify the conditions which had become over complicated since the decision was made to require the blocks editor to be active, not just the project to use blocks.
Fixes https://github.com/microsoft/pxt-microbit/issues/6447
=> Fix not showing Keyboard Controls in help menu

package.json
=> [pxt-cli] bump version to v11.4.44

package.json
=> [pxt-cli] bump version to v12.0.2

package.json
=> [pxt-cli] bump version to v12.0.3

package.json
=> [pxt-cli] bump version to v12.0.5

theme/theme.config
part of the fix for https://github.com/microsoft/pxt-microbit/issues/6457
for some reason, icons weren't being included in the built css for the makecode docs. this fixes that, but the semantic file in doccdn still needs to be updated (which i'll do in a separate PR)
=> make sure icons are included in the built semantic.css for pxt-core docs

pxtblocks/builtins/variables.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/6508
It is currently possible to open the context menu for a `Change variable` block and select the `Create [instance of variable]` option, adding an erroneous and persistent instance of the variable to the flyout (see video). This fix simply guards the display of that context menu option.
I have searched the pxt codebase for other uses of custom context menus that could be a problem, and this seems to be the only one affected by this issue. It mirrors a mixin implemented in blockly (`blocks/variables.ts`) for the variable setter and getter blocks- they are already guarded by `!this.isInFlyout`.
**Before**
https://github.com/user-attachments/assets/0bb0f1dc-c02d-4b1d-aacc-b0660eb12f55
**After** …
=> Fix erroneous option in flyout menu change variable block

webapp/src/app.tsx
Fixes https://github.com/microsoft/pxt-microbit/issues/6509
Fixes https://github.com/microsoft/pxt-microbit/issues/6510
Using escape to close the context menu for a block in the flyout should not close the flyout.
In the area menu, if the mini-simulator view is visible, selecting it should open it in fullscreen mode.
The first issue was manifested because escape fires `app.setSimulatorFullScreen(false)` which eagerly closes the flyout even though nothing is being fullscreened. I changed it to only fire if it is called with `true` which solves the problem.
It is not possible to solve this through managing event propagation, as the context menu key handlers are managed in Blockly and the simulator handlers are managed in Makecode.
While testing the other triggers for …
=> Context menu close on escape preserves flyout. Mini-sim from area menu fullscreens

package.json
=> [pxt-cli] bump version to v12.1.1

teachertool/src/components/MakecodeFrame.tsx, teachertool/src/components/ShareLinkInput.tsx, teachertool/src/state/actions.ts, teachertool/src/state/reducer.ts, teachertool/src/state/state.ts, teachertool/src/transforms/loadProjectMetadataAsync.ts
This change is in response to https://github.com/microsoft/pxt-microbit/issues/6506. It doesn't fix the underlying issue (which is still a mystery), but it does provide a way for the user to trigger a reload of the project when it occurs.
Previously, if the `shareId` didn't change, the project wouldn't reload, even if you clicked enter in the input field. With this change, we force the reload even if `shareId` remains the same. This was a little weird to do, since we rely on the `shareId` state update to trigger the normal iframe reload, but by adding a simple counter to increment in addition to the URL, we can force that code to run even if `shareId` is the same.
Try it: https://makecode.microbit.org/app/9cc5d126301788ec0096f6b3cd3c050d73e691a7-0166509874--eval
=> Reload code eval iframe even when URL is the same

package.json
=> [pxt-cli] bump version to v12.0.9

package.json
=> [pxt-cli] bump version to v12.1.2

webapp/src/errorList.tsx, webapp/src/monaco.tsx
This adds some debounce logic before we display the error list in the monaco editor, which is reset by any additional incoming errors or by any user typing.
I don't think we want this for blocks, since those errors are more immediately relevant (no mid-word typing scenarios), hence keeping the changes confined to monaco.
Try it: https://makecode.microbit.org/app/1fbaa8c7c5d8f918df6b430ffa705a682fc15887-0c5fd79306
Fixes https://github.com/microsoft/pxt-microbit/issues/6517
=> Debounce showing monaco error list

package.json
=> [pxt-cli] bump version to v12.0.10

pxteditor/experiments.ts, webapp/src/errorList.tsx
Since this feature requires login (and an internet connection), we don't want to show it in the offline app. With these changes, the experiment is hidden and the button is not shown in electron mode.
Fixes https://github.com/microsoft/pxt-microbit/issues/6529
=> Do not show AI Error Help in offline app

package.json
=> [pxt-cli] bump version to v12.0.11

package.json
=> [pxt-cli] bump version to v12.1.3

package.json
=> [pxt-cli] bump version to v12.0.12

webapp/src/app.tsx, webapp/src/onboarding.ts
It sounds like the error that we were getting for this bug (https://github.com/microsoft/pxt-microbit/issues/6532) has more to do with electron package updates than with the actual tour handling, but I figured that it wouldn't hurt to add some more error handling.
=> if the tour steps are empty, don't try to load anything

package.json
=> [pxt-cli] bump version to v12.0.13

package.json
=> [pxt-cli] bump version to v12.1.4

webapp/src/app.tsx
This PR maintains the existing behaviour of rendering the untrimmed README.md content into the sidebar.
Closes https://github.com/microsoft/pxt-microbit/issues/6528
=> Open localized README.md file if available

package.json
=> [pxt-cli] bump version to v12.1.5

package.json
=> [pxt-cli] bump version to v12.0.14

package.json
=> [pxt-cli] bump version to v12.0.15

package.json
=> [pxt-cli] bump version to v12.0.16

pxtblocks/compiler/typeChecker.ts, pxtblocks/composableMutations.ts, pxtblocks/loader.ts, pxtcompiler/emitter/decompiler.ts, tests/blocklycompiler-test/baselines/variable_reporter_args.ts, tests/blocklycompiler-test/cases/variable_reporter_args.blocks, tests/blocklycompiler-test/test-library/actionEvent.ts, tests/blocklycompiler-test/test.spec.ts, tests/decompile-test/baselines/variable_reporter_args.blocks, tests/decompile-test/cases/testBlocks/basic.ts, tests/decompile-test/cases/variable_reporter_args.ts
this pr adds support for combining the `//% optionalVariableArgs` and `//% draggableParameters=reporter` annotations. 
the `optionalVariableArgs` annotation is what gives us the expandable callback parameters in the on chat blocks in minecraft. here's what those look like:
with this pr, when you add the `draggableParameters=reporter` annotation you get the same behavior but with draggable blocks instead:
=> add support for reporter parameters with the optionalVariableArgs annotation

package.json
=> [pxt-cli] bump version to v12.1.7

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, webapp/src/projects.tsx, webapp/src/scriptmanager.tsx
this is for minecraft. currently we only filter tutorials with the `hideIteration` flag from projects, but that flag has other side effects. this lets you have a regular-old multistep tutorial that doesn't go into your projects.
=> add tutorial metadata flag for hiding from projects

cli/cli.ts
this tweaks the `quick` cli option when building targets so that we skip the step where we cache used blocks for tutorials. notably, the quick option is passed to the target build when using the `--rebundle` flag on `pxt serve`.
in pxt-minecraft, we cache a bunch of hour of code tutorial blocks which takes a very long to cache when doing a serve:
* without this change, `pxt serve --rb` takes about 59 seconds on my machine to actually start the local dev server.
* with this change, `pxt serve --rb` takes 17 seconds
just know that if you're testing tutorial perf locally, make sure to not use rebundle (this is globally true of all perf investigations)
=> don't cache used blocks when doing quick builds

theme/common.less, webapp/src/projects.tsx, webapp/src/sui.tsx
seems like the minecraft client isn't a fan of `<select>` elements on ios. this works around that issue by replacing the one in the new project modal with our react-common dropdown. that was the only place actually using that sui component, so i removed it entirely.
added bonus is that this makes that dropdown more consistent with our other ones appearance wise.
=> use dropdown instead of select for language restriction

react-common/components/share/SocialButton.tsx, react-common/styles/share/share.less
this is a redo of https://github.com/microsoft/pxt/pull/10277
replaces the button elements for the social buttons with anchor elements. also changes the minecraft in game behavior so that we use the default browser navigation instead of window.open (which is unsupported in their embedded webview).
=> use anchor elements for social buttons

webapp/src/components/AreaMenuOverlay.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/2807
don't adjust the toolbox rect size when the simulator is collapsed and a tutorial is open as the sim sidebar causes the rect to be misplaced. this is only an issue in headless targets because the sim cannot be collapsed in a tutorial otherwise.
also makes it so that we don't render a shortcut for the simulator in headless targets since there is nothing to focus.
=> fix area menu overlay for headless sim targets

localtypings/pxtarget.d.ts, localtypings/pxteditor.d.ts, theme/tutorial-sidebar.less, webapp/src/app.tsx, webapp/src/headerbar.tsx
This change adds support for switching to the tutorial "sim sidebar" layout for specific editor languages (blocks, javascript, or python).
The name is confusing here. "Sim sidebar" means two things - the simulator is on the lefthand side *and* the instructions are at the top. It was made for Micro:bit, where it is used for all tutorials and having the sim on the side (vs minisim) is the more prominent difference. But in Minecraft (in-game), the simulator is hidden, so it just moves the instructions to the top, which is what we want. I considered renaming it to something like "top instruction layout", but that is overloaded with the layout for tablet-sized screens, so you could end up not enabling "top instructions" mode but still ending up with instructions at the top...which felt …
=> Support different tutorial instruction layouts per editor language

pxtblocks/fields/field_dropdown.ts, pxtblocks/fields/field_gridpicker.ts, webapp/src/app.tsx
fixes https://github.com/microsoft/pxt-minecraft/issues/2806
adds a bunch of fixes related to using the gridpicker with keyboard controls in minecraft:
* pressing escape when the field editor is expanded no longer opens the simulator
* fixes the focus indicator outline on shadow blocks with dropdown fields and labels, but no other editable inputs/fields (like the item block in the linked issue)
* focus is now trapped in the gridpicker when either the searchbar or selection bar is present
* the selected item is now actually visible when selecting using the keyboard arrows (uses the standard focus color)
* tabbing out of the searchbar no longer resets the selected item
* fixes keyboard nav when the items in the grid are filtered via the searchbar
* the tooltip is now displayed underneath …
=> lots of keyboard accessibility fixes for gridpicker

docs/writing-docs/tutorials/control-options.md, localtypings/pxtarget.d.ts, theme/toolbox.less, theme/tutorial-sidebar.less, webapp/src/app.tsx, webapp/src/blocks.tsx, webapp/src/editortoolbar.tsx, webapp/src/marked.tsx, webapp/src/monaco.tsx, webapp/src/monacoFlyout.tsx, webapp/src/toolboxeditor.tsx
This adds a `unifiedToolbox` flag for tutorials, which groups all blocks into a single flyout that is always open. Basically, it's `flyoutOnly` without the side effects, and it works for blocks and text. I did not change `flyoutOnly` because some tutorials may rely on the side effects to work. (Minecraft HOC, for example, has zoom + undo buttons at the top, so `flyoutOnly` hides those buttons from the editor toolbar).
Also fixes a tiny layout bug I noticed where tutorial instructions weren't having their top set correctly when in tablet mode, which caused a little overlap between the instructions & the editor below.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2720
Monaco:
Blocks:
=> Add a "unified toolbox" option which works for blocks and text

pxtblocks/plugins/duplicateOnDrag/duplicateOnDrag.ts, webapp/src/blocks.tsx
A few bug fixes:
1. Fix a null ref in duplicateOnDrag, which seemed to happen when the block was created for the flyout
2. Ensures we have an actual CachingFlyout before calling clearBlockCache
3. If the toolbox isn't in the DOM and `getFocusableElement()` is called (can happen when transitioning from flyoutOnly -> regular mode), then return the blocksArea (next closest parent) instead. Returning null here causes a crash and the blockly injection fails.
4. Prevent duplicate calls to `KeyboardNavigation.registerKeyboardNavigationStyles()`, which cause an exception.
Fixes https://github.com/microsoft/pxt-minecraft/issues/2859.
=> Fix flyoutOnly (and unifiedToolbox) bugs

react-common/components/controls/VerticalResizeContainer.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2852
We were missing the call to prevent the pointer down event from propagating when entering resize mode, so dragging the cursor was still causing text to get selected.
=> Prevent selection when resizing tutorial instructions

react-common/styles/controls/Button.less, theme/tutorial-sidebar.less, webapp/src/app.tsx, webapp/src/container.tsx, webapp/src/headerbar.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2853
This makes a few changes related to this issue:
1. Fixes CSS styling for the width of the tutorials in tablet mode, so it won't be overridden by non-tablet styles that keep it to the left
2. Hides "show file explorer" from the settings menu when in tutorials
3. Forces the file explorer to close when opening a blocks or tutorial project in minecraft
4. Fixes styling on the menu button icon, so it doesn't have extra padding
Upload target: https://minecraft.makecode.com/app/d173665bb290e6ae3f7d05fd869a9fdde751b1a9-7f317c4fc0?ingame=1&ipc=1
=> Prevent file explorer from opening in Minecraft tutorials

webapp/src/immersivereader.tsx
Fixes https://github.com/microsoft/pxt-minecraft/issues/2882
Trying to go full screen causes some issues in Minecraft. Specifically, it'll only fill the Minecraft window (not the actual full screen), and it messes with the position of the MakeCode iframe when you exit. For now, just hide the button so users can't get into this state.
=> Hide immersive reader full screen button in Minecraft

skillmap/src/App.tsx, skillmap/src/actions/dispatch.ts, skillmap/src/components/SkillGraphContainer.tsx, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/store/reducer.ts, skillmap/src/styles/skillgraph.css
this is for bug arena.
adds an option to skillmaps called pixellatedbackground which simply sets `image-rendering: pixellated` on the skill map's background. i need this because i want the background of bug arena to be a GIF, and in order to keep the GIF tiny i recorded it at native resolution (160x120). the browser upscales the image by default which results in a super blurry background unless you override it with css.
this should be a very safe PR and I want to hotfix it to pxt-arcade ASAP
=> add skillmap option for pixelating the background image

skillmap/src/App.tsx, skillmap/src/actions/dispatch.ts, skillmap/src/components/SkillGraphContainer.tsx, skillmap/src/lib/skillMap.d.ts, skillmap/src/lib/skillMapParser.ts, skillmap/src/store/reducer.ts, skillmap/src/styles/skillgraph.css
cherry picking to arcade stable
=> add skillmap option for pixellating the background image (#10877)

package.json
=> [pxt-cli] bump version to v11.3.60

localtypings/pxtarget.d.ts, pxtlib/tutorial.ts, webapp/src/app.tsx, webapp/src/components/tutorial/TutorialContainer.tsx, webapp/src/toolboxeditor.tsx
part of the fix for https://github.com/microsoft/pxt-arcade/issues/7012
part of the fix for https://github.com/microsoft/pxt-arcade/issues/7013
part of the fix for https://github.com/microsoft/pxt-arcade/issues/7010
adds a few tutorial features/fixes for bug arena:
* new `hiddenNamespaces` snippet in tutorial markdown that lets you edit the toolbox filters in the tutorial project. this is a useful alternate method of filtering the toolbox that lets you remove categories without having to enumerate every single block from the categories you want to keep inside a `ghostBlocks` snippet
* new `### @hideReplaceMyCode true` config that will hide the "replace my code" button in skillmap tutorials
* fixes a bug where the toolbox filters in a project's `pxt.json` could not filter the variables or …
=> adding a few tutorial options and fixing toolbox filters

react-common/components/controls/MenuDropdown.tsx, react-common/styles/controls/MenuDropdown.less, theme/color-themes/high-contrast.json, theme/color-themes/overrides/high-contrast-overrides.css, theme/common.less, theme/highcontrast.less
Fixes https://github.com/microsoft/pxt-minecraft/issues/2890
This change ensures items in the menu dropdown:
1. Don't change foreground color on hover (even when they're links)
2. Do have the expected border on hover in high contrast mode
As a part of this, I also removed some redundant CSS and moved a few rules into the high contrast overrides file, making things more consistent with the new theming.
Lastly, I turned off the automatic focus on the first element in the list. This was causing double highlighting (keyboard focus on one, mouse hover on the other) which seemed confusing. It's also more consistent with our other dropdowns. I confirmed you can still use arrow keys to navigate into the menu once it's open.
With auto-focus, you get double highlights:
Without, you can still …
=> High contrast dropdown menu fixes
